### ISSUE TITLE
temporarily move Node.js Interactive Banner to top of home page

### ISSUE THREAD

**Issue by gtewallace** [nodejs/nodejs.org#1004]
* **https://nodejs.org/en/**:
* **Browser version**:
* **Operating system**:

Hi,

with less than a month before Node.js Interactive Austin, we'd like to ask that the banner on nodejs.org  be moved temporarily (just for the next couple weeks) to the top of the home page to help ensure the event gets maximum visibility across all devices.

with this move, I think it's totally cool to make the banner narrower so that all the download and latest release info stays above the fold.

thanks in advance!

**Comment by mikeal** [comment]
Last year the banner was "above the fold" on the website. This year, because of changes in the main content, it is "below the fold." It would be nice to find a way to get this above the fold for the next month until the conference is over.

**Comment by ryanmurakami** [comment]
Opened a PR for this. I noticed the original issue only referenced /en/, but I applied this to all locales. Let me know if anything needs a change.

**Comment by ryanmurakami** [comment]
@gtewallace @mikeal Looking for feedback on the PR whenever you have a moment.
