### ISSUE TITLE
Add Missing Working Groups to About Section

### ISSUE THREAD

**Issue by ryanmurakami** [nodejs/nodejs.org#1010]
* **URL**: https://nodejs.org/en/about/working-groups
* **Browser version**:
* **Operating system**:

The Working Groups page in the About section has several working groups missing. Some may be defunct (Promises?) but others are likely new. I'm wondering if there is a need to update this page with the current active working groups. 

Here are some of the groups I found that were missing:
[LTS working group](https://github.com/nodejs/LTS)
[API working group](https://github.com/nodejs/api)
[Hardware working group](https://github.com/nodejs/hardware)
[Promises working group](https://github.com/nodejs/promises)

I'm happy to add them to the page, but wanted to see what everyone else thought.

**Comment by williamkapke** [comment]
These are not real Working Groups. They are just labeled inappropriately. [I've raised this issue before](https://github.com/nodejs/help/issues/130) but there hasn't been any changes to remove the confusion.

There are 2 more BTW.... I have them listed as "unchartered" here: http://node.red/decision-makers.html

/cc @nodejs/ctc @nodejs/tsc

**Comment by williamkapke** [comment]
I really appreciate your review of this info BTW- we need more of this! THANKS!

**Comment by ryanmurakami** [comment]
@williamkapke Ah, okay. That page is super awesome! 
Hmm... think we should leave this issue open for discussion or just close it out?

**Comment by williamkapke** [comment]
I guess we should close it since there's no work to do, at this time, on THIS repo. However, I invite/encourage you to open an issue at https://github.com/nodejs/CTC/issues

**Comment by ryanmurakami** [comment]
@williamkapke Sounds good. Thanks!
