### ISSUE TITLE
Input on coverage.nodejs.org

### ISSUE THREAD

**Issue by mhdawson** [nodejs/nodejs.org#1019]
* **URL**:https://coverage.nodejs.org/
* **Browser version**: all 
* **Operating system**: any

Possibly a bit late, but better late than never.

Now that we've added coverage.nodejs.org (as per issue https://github.com/nodejs/testing/issues/36) I'd like to see if the website WG has any comments/suggestions on the layout.

**Comment by ryanmurakami** [comment]
@mhdawson This looks cool! I noticed that the coverage links currently go to 404. Known issue?
Here are my suggestions:
- Change "Node.js Core" header to non-link, increase the size, and have the link to the repo beside the title. Perhaps you could use an icon like [this](http://fontawesome.io/icon/external-link/).
- At the title/header level, indicate this is nightly coverage. 
- Format the date/time to make it easier to read. Maybe a format like this: mm/dd/yyyy hh:mm
- Increase distance between each column, so it's clear where each ends/begins. 

If you need any help on this just let me know. Good job!

**Comment by ryanmurakami** [comment]
Is there an existing ingress point to this page from nodejs.org? Seems like a good opportunity.

**Comment by mhdawson** [comment]
@ryanmurakami. This looks cool! I noticed that the coverage links currently go to 404. Known issue?

> > > You managed to look just at the wrong time.  :) I was integrating a PR which led to a hickup.  Should be all ok now.

In terms of helping, if you'd like to submit a PR to make the changes against https://github.com/nodejs/testing/blob/master/coverage/generate-index-html.py that would be great.

Currently I don't think we have ingress points from nodejs.org for coverage.nodejs.org or benchmarking.nodejs.org.  Would be good to have both of those.

**Comment by fhemberger** [comment]
@mhdawson FYI: UTF-8 characters in the footer of http://coverage.nodejs.org are broken.

**Comment by ryanmurakami** [comment]
@fhemberger I'll take care of this in my PR

**Comment by ryanmurakami** [comment]
@mhdawson I'm noticing there are a lot of material design classes, but the CSS isn't included so there aren't styles being applied. Do you want me to strip that out, or add the styles in? Personally, I don't think we need it, but wanted to check with you.

**Comment by ryanmurakami** [comment]
@mhdawson Here's what I've done. Thoughts?

<img width="1142" alt="screen shot 2016-11-10 at 2 10 17 pm" src="https://cloud.githubusercontent.com/assets/767105/20196451/8e25cea8-a74f-11e6-95d9-76462765d5aa.png">

**Comment by mhdawson** [comment]
@ryanmurakami, PR landed in nodejs/testing to update and looking good so closing this issue.  Thanks for the input and the work to submit the change.  I'll open a separate issue so that we don't forget about considering an ingress point for the coverage and benchmarking pages.
