### ISSUE TITLE
Ingress point for the coverage and benchmarking pages. 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/nodejs.org#1024]
* **URL**: coverage.nodejs.org, benchmarking.nodejs.org
* **Browser version**: N/A
* **Operating system**: N/A

In an issue to get feedback on coverage.nodej.org it was suggested that it might make sense to have an ingress point somewhere on nodejs.org for coverage.nodejs.org.  I think that also applies to benchmarking.nodejs.org.

Thoughts ? Suggestions of where links could make sense ?

**Comment by fhemberger** [comment]
@mhdawson It would be nice if the projects where linked somewhere, but I don't see a fitting section in our current content structure.

For the time being, I'd link them in the core's README.

**Comment by mhdawson** [comment]
What about a new link under in the "about" page.  I could be named something like 'Nightly Metrics"

**Comment by fhemberger** [comment]
Linking: https://github.com/nodejs/website-redesign/issues/4#issuecomment-365957539

**Comment by ovflowd** [comment]
Closing as this is obsolete.
