### ISSUE TITLE
Travel funding for Collaborators to attend Summit in December

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/nodejs.org#1025]
Hey All,

I wanted to make sure you were all aware of this thread from the TSC repo 

https://github.com/nodejs/TSC/issues/166

TLDR active collaborators in this working group who want to participate in the summit, but cannot get funding from their employers, should feel free to apply

**Comment by Fishrock123** [comment]
@nodejs/website time is running short but if necessary we might still be able to get you there

**Comment by ryanmurakami** [comment]
Closing this as the Summit has passed.
