### ISSUE TITLE
Downloading Older version

### ISSUE THREAD

**Issue by ranjithprabhuk** [nodejs/nodejs.org#1026]
I downloaded windows 64-bit msi installer file. Its downloading 6.9 version file. But the latest is 7.1.0. URL is wrong in download link. Kindly update it.

* **URL**:
* **Browser version**:
* **Operating system**:

**Comment by fhemberger** [comment]
You downloaded the latest LTS release (which is 6.9.1) instead of the current release:
https://nodejs.org/en/download/current/
