### ISSUE TITLE
Analytics drop for blog in Oct/Nov

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#1028]
Something is going on with the analytics on the blog.

In Oct/Nov we show something like 60 session total, where prior we had ~50K.

The analytics on the rest of the website seem unchanged, still showing over a million sessions per month.

Anyone ideas on what might have happened?

**Comment by phillipj** [comment]
Sorry about the late response here. In short, this was my fault when introducing the changes in #885 which I obviously should have tested better.

**Comment by phillipj** [comment]
@mikeal Analytics should be up-n-running again now. Once again, sorry for the blooper caused in #885 :/
