### ISSUE TITLE
Track relevant issues from iojs.org/old nodejs.org

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs.org#103]
There is a small list of issues (mainly enhancements and ideas), which might be relevant for nodejs.org as well:

https://github.com/nodejs/iojs.org/labels/new%20nodejs.org
https://github.com/nodejs/nodejs.org/labels/new.nodejs.org

**Comment by mikeal** [comment]
I think we're up to date now, closing.

**Comment by fhemberger** [comment]
I think we should keep those around:
- https://github.com/nodejs/iojs.org/issues/235 (Browser language based redirection for i18n)
- https://github.com/nodejs/iojs.org/issues/80 ('latest' symlink for downloads)
- https://github.com/nodejs/nodejs.org/issues/144 ('how to verify downloads' guide)
- https://github.com/nodejs/nodejs.org/issues/74 (document supported versions + lts)
- https://github.com/nodejs/nodejs.org/issues/49 (aka fix old documentation)
