### ISSUE TITLE
[redesign] What are we going to do about the events page.

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#1031]
So, I'm starting to wonder if the events page is actually useful or not.

It's dominated by a dump of meetups from meetup.com I scraped like a year ago and organizers don't appear to be using it at all.

We should talk about what we think the events page should offer and who it should be serving. If we can reach a consensus on where we want to go I'm up for helping implement it.

**Comment by ryanmurakami** [comment]
I like the existing location based information. I think the only thing that is really missing/not helpful is some sort of calendar of events. For conferences, it would be super helpful. For meetups, perhaps the Meetup API could be used?

Also, it might help to put it in a different location on the nodejs.org site. It's kind of hidden behind the "Get Involved" menu, so I wonder how many people can even find it.

**Comment by mikeal** [comment]
The current data is pulled from Meetup.com over a year ago. We don't have a great way to keep it updated from that feed or to figure out which meetups are actually still happening.

**Comment by edsadr** [comment]
What about adopting a system like nodeschool.io? and maybe put some effort in contacting the events organizer so it could provide useuful information about next events and involve the community to maintain this content updated

**Comment by id304m** [comment]
https://runkit.io/runkit/json-endpoint-example-1/branches/master?url=http://google.com

**Comment by fhemberger** [comment]
I like the idea of listing conferences and nodeschool events, but I don't think we need to list every meetup possibly related to Node.js. Many of them are tagged wrong so we include a lot of unrelated events (e.g. Ember, Angular, Meteor) but still are missing some others. Plus the meetup.com API isn't well suited for retrieving and filtering such an event list and the results are hard to maintain.

**Comment by ryanmurakami** [comment]
@fhemberger Yeah, I like that idea. In addition, I think meetup has a friendly interface that makes it easy to find local meetups, so we don't really need to provide an index of them all. I'm wondering, though, if some new users may be unfamiliar with even meetups. Perhaps we could just provide a call out  and link the the meetup site. Something like "There are many local meetups that focus on Node.js. Check out meetup.com to find one near you." Then we can keep out of the weeds while sharing a local resource for users.

**Comment by lpinca** [comment]
I totally agree with @fhemberger.

**Comment by vdeturckheim** [comment]
related to https://github.com/nodejs/evangelism/issues/251

**Comment by CharlesBeeler** [comment]
What about putting together a simple form that event organizers can fill out that generates the script necessary to include the event and pushes that to whomever would oversee the list? There are a lot of events that would be great to include but it would be difficult for Mikeal or others to have to search for and update each one - seems reasonable to expect the event organizers to at least provide the relevant data in a usable format. If you see an event that is not listed it might be as easy as emailing a link to the form to let the organizer they should fill it out to have their event listed.

Could also skip the form and just provide a sample format that they need to send in to be considered for inclusion.

Would also second/third the notion that the meetups end up making the map hard to use.  One suggestion would be to have a separate map for Meetups.  Agree that finding local meetups is relatively easy to do on the meetup website but would still be great to have a repository of this, especially if you can capture a more complete set of meetups than would appear when searching on meetup.org.

Happy to help on any of this as desired.

**Comment by Trott** [comment]
The events page should be deleted or replaced with a simple copy/pasted list from the events list in the weekly newsletter sent out by the Foundation. Right now, clicking on "Events" and getting a map that has a lot of pins placed incorrectly and events that aren't actually happening etc..... it's a bad user experience. Having no information about events may be better than this experience, to be honest. It was a neat thing to set up, but the website is about the end user, and this isn't helping the end user.

Meetups have been covered, and there seems to be consensus that they should be removed. But the conference list isn't necessarily much better. If you find Node.js Interactive in the list and click on Map, you end up in Portland, where it was two years ago. And things like upcoming Code + Learn events (which are Node.js Foundation sponsored!) are not on the page (or are not particularly findable if they are). 

A map can be restored later, perhaps, if there's a way to reliably keep things up to date. But when I click "Events", I expect to see a chronological list or a calendar, not a map. Removing the map entirely would not be much of a loss for the typical end user, in my opinion at least.
