### ISSUE TITLE
https://nodejs.org/de/docs/guides/ 404s

### ISSUE THREAD

**Issue by sarahmeyer** [nodejs/nodejs.org#1039]
* **URL**: https://nodejs.org/de/docs/guides/
* **Browser version**: Chrome Version 54.0.2840.98 (64-bit)
* **Operating system**: OSX Version 10.11.6 (15G1004)

The [guides page](https://nodejs.org/de/docs/guides) linked from the [docs page in German](https://nodejs.org/de/docs/) gives a 404.

**Comment by outsideris** [comment]
It looks like redirection to English page doesn't work for German. 

https://nodejs.org/de/blog is 404. but https://nodejs.org/ko/blog is redirect to https://nodejs.org/en/blog .

**Comment by lpinca** [comment]
Should be fixed by https://github.com/nodejs/build/pull/557.
Thanks for reporting.

**Comment by Fishrock123** [comment]
Ohhh right we need a separate ngnix overload for each one. Doh.

**Comment by lpinca** [comment]
Closing as it seems to work now.
