### ISSUE TITLE
"Planet Node" link does not work anymore

### ISSUE THREAD

**Issue by amandeepmittal** [nodejs/nodejs.org#1045]
* **URL**:http://planetnodejs.com/
* **Browser version**:Google Chrome
* **Operating system**:macOS 10.12.1

[Planet Node](http://planetnodejs.com/) is not working (or no longer maintained) on [Getting Involved](https://nodejs.org/en/get-involved/) page. Please update or remove the link from the website.

**Comment by fhemberger** [comment]
Fixed: 8e1ae4a53ccdbcbae7b0894535984c615af9cc23
