### ISSUE TITLE
Link to punycode library 403s

### ISSUE THREAD

**Issue by sjwalter** [nodejs/nodejs.org#1052]
* **URL**: https://nodejs.org/dist/latest-v7.x/docs/api/punycode.html
* **Browser version**: Chrome latest
* **Operating system**: Linux

Link to userland Punycodejs on the punycode docs page is 403. The link href is https://mths.be/punycode. Possibly the href should be updated to https://github.com/bestiejs/punycode.js/

**Comment by lpinca** [comment]
@sjwalter thanks but you should create an issue in https://github.com/nodejs/node. The documentation is there.

**Comment by lpinca** [comment]
@sjwalter https://mths.be/punycode now redirects to https://github.com/bestiejs/punycode.js/ so no changes are needed.

Closing this. Thanks for reporting.
