### ISSUE TITLE
Evangelism Working Group: Please add Node.js Survey

### ISSUE THREAD

**Issue by serenam18** [nodejs/nodejs.org#1057]
Hello, 

Can you please add the following survey to the working group? 

Node.js has launched its second user survey, which will remain open until the end of December.  

This survey builds on the questions asked in the first Node.js survey from January 2016, and adds a number of questions designed to shed even more light on who, what, where, why and how Node.js and related technologies are being used. As with the January survey, the Node.js Foundation will produce and make available publicly for free a report with the survey's key findings.  

Please take the survey and tell your friends and colleagues:

https://www.surveymonkey.com/r/Node16

thank you! 

* **URL**:
* **Browser version**:
* **Operating system**:

**Comment by fhemberger** [comment]
Survey is closed, closing issue as well.
