### ISSUE TITLE
Evangelism: Weekly Update for December

### ISSUE THREAD

**Issue by JungMinu** [nodejs/nodejs.org#1058]
Let's write down for next week :gift:

**Comment by hfeeri** [comment]
Hey there,

We published a detailed tutorial on JavaScript Clean Coding:

https://blog.risingstack.com/javascript-clean-coding-best-practices-node-js-at-scale/

Bests,
Ferenc

**Comment by hfeeri** [comment]
Hello,

We created a detailed checklist that helps companies with the adoption of Node.js
https://node-checklist.risingstack.com/

Cheers,

**Comment by vsemozhetbyt** [comment]
[V8 ❤️ Node.js](http://v8project.blogspot.com/2016/12/v8-nodejs.html) by @fhinkel on v8 blog,

**Comment by hfeeri** [comment]
[The 10 Most Important Node.js Articles of 2016](https://blog.risingstack.com/10-most-important-node-js-articles-2016/)

**Comment by hfeeri** [comment]
Hi,

we wrote: [Node.js Best Practices - How to Become a Better Developer in 2017](https://blog.risingstack.com/node-js-best-practices-2017/)

Cheers,

**Comment by fhemberger** [comment]
Closing this …
