### ISSUE TITLE
Provide node+npm zip download

### ISSUE THREAD

**Issue by silverwind** [nodejs/nodejs.org#1059]
Lifted from https://github.com/nodejs/node/issues/10174, @NN--- suggests that we provide a third download option for Windows, a zip that includes node and npm.

**Comment by fhemberger** [comment]
I think we should replace the link to `node.exe` to the zip file with both node/npm. Thoughts?

**Comment by MylesBorins** [comment]
+1 on replacing the exe link with a zip link

**Comment by silverwind** [comment]
Sounds good.

**Comment by mhdawson** [comment]
+1 from me as well.

**Comment by edsadr** [comment]
+1 pretty useful

**Comment by ryanmurakami** [comment]
Yes. Also,  should we provide zip and 7z options like the all download options page?

**Comment by fhemberger** [comment]
@ryanmurakami I think zip is enough. We only provide one format for the other builds on the download page as well and 7zip doesn't have the same relevance on Windows than zip.
