### ISSUE TITLE
The website is super slow, breaking builds using nvm

### ISSUE THREAD

**Issue by SimenB** [nodejs/nodejs.org#1061]
Unsure if this is the correct place to report it...

`nvm ls-remote` hangs forever, and builds time out on Travis, sometimes trying  to compile from source, which fails spectacularly.

E.g https://nodejs.org/dist/latest-boron/node-v6.9.2.tar.gz takes a loooong time to download.

![image](https://cloud.githubusercontent.com/assets/1404810/21049720/d616a4ac-be16-11e6-9de2-f381b1cf0df4.png)

**Comment by EloB** [comment]
The download is super slow for me as well.

**Comment by ghost** [comment]
Don't know if it is related, but I also suddenly have errors during chef downloads:
```
remote_file[c:\chef\cache\package\node-v5.5.0-x64.msi] (dynamically defined) had an error: Chef::Exceptions::ContentLengthMismatch: Response body length 360194 does not match HTTP Content-Length header 10383360.
This error is most often caused by network issues (proxies, etc) outside of chef-client.
```

**Comment by phillipj** [comment]
@jbergstroem ping, you know of any issues currently?

**Comment by PeterDaveHello** [comment]
+1 from my side

**Comment by o-e** [comment]
Same problem here. From what I can see nodejs uses Cloudflare, and they are having issues right now, according to https://www.cloudflarestatus.com/

**Comment by jbergstroem** [comment]
See https://github.com/nodejs/build/issues/562 for discussion/updates -- will leave open for visibility (can some mod lock this?).

**Comment by PeterDaveHello** [comment]
I don't have the problem on the other websites using Cloudflare, that's not Cloudflare's problem IMO.

**Comment by lpinca** [comment]
Locked as per @jbergstroem request.

**Comment by Trott** [comment]
All operations should now be back to normal. If you're still experiencing issues with downloading node or accessing parts of the website, please post a comment in https://github.com/nodejs/build/issues/562. Thanks.
