### ISSUE TITLE
Mirror

### ISSUE THREAD

**Issue by cgountanis** [nodejs/nodejs.org#1063]
Is it safe to use this mirror?

https://npm.taobao.org/mirrors/node

**Comment by PeterDaveHello** [comment]
Don't know but it's inside the mainland china, the internet connection may not be reliable and stable enough, I think this issue may be related with https://github.com/nodejs/build/issues/562, and maybe we should discuss about the mirror setup process.

**Comment by cgountanis** [comment]
Does match:

789af29eba3a43213dfab7a71ada7e2c513a9fa023f0987b2076b10754da907e  node-v7.2.1-x64.msi

**Comment by PeterDaveHello** [comment]
@cgountanis to your origin question, I think you can still down the tarball from it, but carefully compare its checksum with the official site(as the checksum files are not that huge, I think we can still download it).

**Comment by MylesBorins** [comment]
We do not officially support any mirrors not on the nodejs.org domain

If you are going to get tarballs from a 3rd party mirror please verify the SHASUMS using the instructions found [in our readme](https://github.com/nodejs/node#verifying-binaries)
