### ISSUE TITLE
A few questions about the Website from the Foundation

### ISSUE THREAD

**Issue by bnb** [nodejs/nodejs.org#1065]
I briefly talked with @ZibbyKeaton about the website, and she said that, on the Foundation end, they'd like to see if we can help out with some things:

* The Foundation wanted to know if there's way that we can begin to track the "Resource" section. Something along the lines of downloads or clicks on the case studies in this section. Is this possible, or already being done?
* The Foundation wanted to know if it's possible to track the views of the videos on the resource section site. The Foundation folks would like to know who is coming to this site and what actions they're taking - i.e. watching the videos. Is there a simple way we can assist on this front?
* Apparently, the Blog/News parts of the site are no longer tracking the blog reads. This started sometime around October. Zibby said she wasn't sure if this could be amended, but said it would be awesome if it could be. Does anyone know if there was an accidentally destructive change to an analytics tool that the Blog had implemented?

**Comment by mikeal** [comment]
> The Foundation wanted to know if there's way that we can begin to track the "Resource" section. Something along the lines of downloads or clicks on the case studies in this section. Is this possible, or already being done?

We have Google Analytics on it already so we know what happens on the html pages. For views/downloads of PDFs and other documents we'd need to check with the build team to see if we have the same metrics for this that we have for the tarball downloads.

> The Foundation wanted to know if it's possible to track the views of the videos on the resource section site. The Foundation folks would like to know who is coming to this site and what actions they're taking - i.e. watching the videos. Is there a simple way we can assist on this front?

The videos are youtube embeds so we have the youtube analytics for all of that.

> Apparently, the Blog/News parts of the site are no longer tracking the blog reads. This started sometime around October. Zibby said she wasn't sure if this could be amended, but said it would be awesome if it could be. Does anyone know if there was an accidentally destructive change to an analytics tool that the Blog had implemented?

I looked into this and even logged an issue. I honestly don't know what is going on, we appear to have lost analytics for *only* the blog, our website wide metrics appear unchanged. I really have no idea what happened.

**Comment by lpinca** [comment]
The only thing I can think of is this https://github.com/nodejs/nodejs.org/pull/885 but I honestly don't know why it would affect only the blog section.

**Comment by mikeal** [comment]
Something got moved around because that code isn't even showing up on the blog.

I can run the `_dntEnabled()` function on the main site but when I go to /news and try it, that function is undefined.

**Comment by lpinca** [comment]
Refs: #1068

**Comment by fhemberger** [comment]
@ZibbyKeaton Can you please let me know, if all the issues mentioned have been resolved for you?

**Comment by ZibbyKeaton** [comment]
@fhemberger everything appears to be fine here. All the issues were resolved, so we can close it.
