### ISSUE TITLE
Clarification on Merge Policy

### ISSUE THREAD

**Issue by bengl** [nodejs/nodejs.org#1066]
It appears as though many PRs, including primarily blog posts, have landed without a single reviewer commenting or approving.

If it's the case that blog posts are not subject to review (or that review is optional), then that needs to be clarified.

There *does* appear to be an exception to review. While he [collaborator guide](https://github.com/nodejs/nodejs.org/blob/master/COLLABORATOR_GUIDE.md#accepting-modifications) has the following in it:

> Only the Website Admin group can merge their own work and should do so with great care.

This appears to be the only exception. However, the "Website Admin" group is not clearly defined, except for referencing a @nodejs/website-admin group which appears to not exist. Also, this is in spite of the [contributing guide](https://github.com/nodejs/nodejs.org/blob/master/CONTRIBUTING.md#contributions) explicitly stating:

> No pull request can be merged without being reviewed.

So, what is the **actual** merge policy, and can it please be reflected in contributing and collaborator guides?

**Comment by MylesBorins** [comment]
AFAIK it has been discussed regarding landing the release blog posts
without review and is included in the release guide. I can put together a
pr to this repo to clarify this.

**Comment by williamkapke** [comment]
Also- is it a Corp Member benefit to include product releases in the blog posts? I assume so... I just don't know where we document those benefits. If not documented, I could see outside companies wanting to get in the blogs too.

**Comment by bengl** [comment]
@TheAlphaNerd that would be great! Thank you! I see it in the [release guide](https://github.com/nodejs/node/blob/master/doc/releases.md#14-create-a-blog-post).

However, not all blog posts that aren't being reviewed are releases.

**Comment by phillipj** [comment]
Thanks for bringing this up. You're certainly not the first asking about this WG inner workings, we obviously has improvements to make!

> However, the "Website Admin" group is not clearly defined, except for referencing a @nodejs/website-admin group which appears to not exist.

The admin group equals the **Website Working Group Members** found in `README.md`. It was named the admin group in `README.md` for a while, but changed back to WG members in #606. We should also have remembered to change the collaborator guide.

It was thought to be nice to have @nodejs/website-admin when this WG was created, but never happened obviously. Can't remember we have had the need to either. Just referring to the WG members list would probably suffice.

**Comment by mikeal** [comment]
Initially we had concern about review times for certain time sensitive posts like press releases.

At this point there are so many committers and reviewers though that PRs get merged before admin members can even do it themselves :) We can probably alter the language and move to a more standard merge policy.

**Comment by MylesBorins** [comment]
So I was just thinking... perhaps we need to make a split between the review process for infrastructure and content. This really seems to be where some of the problems are coming into play. Could we perhaps introduce a much more liberal policy for landing content on the site?

**Comment by mikeal** [comment]
@MylesBorins that's a really good point, we can be much more liberal about content changes.

**Comment by fhemberger** [comment]
I think this has been addressed by now, so I'm closing this issue. Feel free to re-open if there's still something to be discussed.
