### ISSUE TITLE
[redesign] Website users and use cases

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#1074]
It's clear to me that we need a re-design of the website.

The design we originally built out was meant to handle far less content than we have now.

As a first step, let's start to enumerate all the reasons people come to the website, what kinds of people, what they are looking for, and the kinds of answers we want to give them as a project.

From there, I think we can work with a designer come up with something new that satisfies our users' needs much better than what we have now.

**Comment by fhemberger** [comment]
What happened to all the work and planning in #508? We were all eagerly waiting for a new concept, design and content structure to emerge from it so we could start giving feedback and iterating over it.

**Comment by mikeal** [comment]
@fhemberger I think we all like the visual direction of #508 but, IMO, it still doesn't address fully the degree to which we need to rethink the structure of the information we present. It's a better design than we have today but the information presentation is derivative of what we do now. It has a much better use of space, so the problems are less evident, but still there.

I'd love to see us return to that design after we define better what visitors to the site need to see and have more thoughts on the best way to accomplish them. If that's the direction we go in then this thread will be useful in helping us return to that design.

**Comment by fhemberger** [comment]
I thought @leo was already [working on that](https://github.com/nodejs/nodejs.org/issues/508#issuecomment-215130007) together with the TSC …

But yes, I totally agree: We need a plan on what we want to achieve and a better content structure first. At the moment there's also lot of outdated organizational stuff on the site. I also think that the whole foundation structure, committees and how contributing works (not only code!) could be explained better.

**Comment by mikeal** [comment]
In the time since that thread was last updated we've added another concurrent release line :/

Enough have changed that this is all worth revisiting. Also, I hope that @leo has the time to work on this but I'm sure he's busy at Zeit cause they are releasing a lot of great stuff right now :)

**Comment by MylesBorins** [comment]
fwiw we consciously decided to drop the older Lts line from the download
page and it may responsible for the quick overtake v6 had over v4. I for
one am open to keeping it that way

**Comment by leo** [comment]
The website project has a fixed position in our official, private roadmap. To be more precise: We're going to release a huge feature (sadly can't tell you what it will be) somewhere in January. After that, the  immediately following thing I'll be working on will be this site.

We also managed to get @evilrabbit (he's the one who designed @zeit's branding) on board, so he'll help me polish it.

Until then, I think it's a good idea to simply continue evaluating what exactly needs to be on this site and where. This will make creating the new design much easier/faster for us!

A while ago, we created [this repo](https://github.com/nodejs/nodejs.org-new/issues) for that. 📢 🐢

**Comment by MylesBorins** [comment]
@leo just to confirm, you are referring to a new zeit feature and your internal roadmap? The phrasing could be read as a private nodejs website roadmap

**Comment by leo** [comment]
@TheAlphaNerd Yep! 😊

**Comment by mikeal** [comment]
> fwiw we consciously decided to drop the older Lts line from the download
page and it may responsible for the quick overtake v6 had over v4.

That's a really good point.

**Comment by mikeal** [comment]
@leo great to hear (both that zeit is shipping more features and that you'll be returning to the redesign) :smile: 

I'll try and wrap up threads like this one in the next few months so that when you get time to work on the redesign you'll have a bunch of the research and discussion out of the way.

**Comment by fhemberger** [comment]
Outdated, closing.
