### ISSUE TITLE
[redesign] How many front page download buttons?

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#1075]
We need to reduce the amount of information people are presented when they hit our front page.

IMO, we should have **one** download button w/ a link underneath it to our downloads page which contains the full releases list.

If we were to pair down, which would we pair down to?

What do we think the user profile is of the average website visitor clicking this link?

**Comment by fhemberger** [comment]
Speaking of the front page, linking #686.

**Comment by Fishrock123** [comment]
Is "Recommended for most users." actually not clear enough, or do people not really read that?

The `changelog` links can probably be removed, but if we have more than version, having API doc links to each is probably a good idea?


I personally suspect this link is mostly used by people just new to Node.js. In which case, `Current` may be the most appropriate so they can use the latest language features without issue that they may see in tutorials.

**Comment by italoacasas** [comment]
Question, why we need to have a direct download button on the front page? Is this decision made because of some stats? 

In case that the button is something that needs to stay on the front page, we can add just one btn and redirect to the `download page`.

examples:
- https://www.microsoft.com/net
- https://www.ruby-lang.org/

**Comment by andmeics** [comment]
I think corrent front page is the best solution，it is briefness and clarity

**Comment by ghost** [comment]
I think corrent front page is the best solution，it is briefness and clarity.And how to distinguish which version people need?

**Comment by ovflowd** [comment]
Closing as this is obsolete.
