### ISSUE TITLE
Question: node jobs board at jobs.nodejs.org no longer available?

### ISSUE THREAD

**Issue by rmharrison** [nodejs/nodejs.org#1077]
Joynet opened the node.js jobs board back in '11 [[1]](https://www.joyent.com/blog/node-js-job-board-get-paid-to-code-in-node). It'd been active as recently as a few months ago.

However, as of 19 Dec 2016, [jobs.nodejs.org](https://jobs.nodejs.org) just redirects to [nodejs.org](https://nodejs.org).

**Is the job board still available?** 

Was the takedown temporary or permanent (the current redirect is 302: Moved Temporarily)?

**Comment by Fishrock123** [comment]
cc @mikeal?

**Comment by mikeal** [comment]
We're actually revisiting this in early 2017.

**Comment by rmharrison** [comment]
Awesome. Thanks for the heads-up. Look forward to hearing about your plans going forward.
