### ISSUE TITLE
Font glitches while clicking around

### ISSUE THREAD

**Issue by phillipj** [nodejs/nodejs.org#108]
Am I the only one seeing this on page load while clicking around? The text seems slightly bigger for the first few 100 milliseconds, before suddenly changing. Must be recent change as I havent noticed this before.

Chrome v45.

![nodejs font glitch](https://cloud.githubusercontent.com/assets/1231635/9729296/bab98e8e-560e-11e5-85fb-847fa57d80ab.gif)

**Comment by fhemberger** [comment]
It's the web-fonts kicking in. For performance reasons, they are loaded dynamically to avoid FOIT (Flash Of Invisible Text) on mobile/slow connections.

**Comment by phillipj** [comment]
Works very good on Safari / iOS :+1: 

Any ideas on improving it slightly for Chrome OS X and iOS? It would be really nice if this repaint only occured on the initial page atleast, not every subsequent page.

Found [Font Loading Revisited](https://www.filamentgroup.com/lab/font-events.html) from filamentgroup, but it seems we would have to have some serverside logic for it to work perfectly.

**Comment by fhemberger** [comment]
There's a PR in line which will probably fix that:
https://github.com/nodejs/new.nodejs.org/pull/69

There are some merge conflicts to be resolved and I was short on time, so I went for a slightly different solution. Maybe we can merge both ideas.

**Comment by evanlucas** [comment]
Yea, I've noticed it as well...

**Comment by phillipj** [comment]
Fingers crossed that #69 / #139 does the job!
