### ISSUE TITLE
Introduce policy to expidite landing press releases

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/nodejs.org#1081]
I think we should introduce a policy similar to the one we have for release notes for press releases. As long as they are properly formatted they should simply land. Once the press release is out, it is not within our ability to change what is in the release.

The new policy I would suggest would be

* any press release can land with no time constraints as long as the copy is properly formatted
* it is not the responsibility of the website group to review the copy itself

**Comment by williamkapke** [comment]
link: #1066

**Comment by phillipj** [comment]
SGTM 👍

**Comment by bengl** [comment]
I think with some clarification, this makes sense. For example: Is "press release" well defined? Do they come from a canonical source? Or is nodejs.org the canonical source? Can anyone create a press release commit and land it immediately? (Obviously not, but the clarity of who can is necessary.)

**Comment by mikeal** [comment]
"Press Release" refers to a particular kind of document produced by our PR team and circulated to reporters in advance. It usually goes out on wire services in addition to being published here.

**Comment by fhemberger** [comment]
@MylesBorins I think it's decided then (as nobody seems to disagree).

Could you please add 1-2 sentences to the repo's README outlining the general PR/review policy and that release notes and press releases are the only exception from this rule?
