### ISSUE TITLE
Evangelism: Weekly Update for January

### ISSUE THREAD

**Issue by JungMinu** [nodejs/nodejs.org#1084]
Let's write down for next week :gift:

**Comment by hfeeri** [comment]
[Node.js Interview Questions and Answers (2017 Edition)
](https://blog.risingstack.com/node-js-interview-questions-and-answers-2017/)

**Comment by hfeeri** [comment]
[Tutorial: Building ExpressJS-based microservices using Hydra](https://community.risingstack.com/tutorial-building-expressjs-based-microservices-using-hydra/)

**Comment by hfeeri** [comment]
[Yarn vs npm - The State of Node.js Package Managers](https://blog.risingstack.com/yarn-vs-npm-node-js-package-managers/)

**Comment by mhdawson** [comment]
Update on community code coverage:https://developer.ibm.com/node/2017/01/11/node-js-code-coverage-data-paying-dividends/

**Comment by hfeeri** [comment]
[OpenCV tutorial: Computer vision with Node.js](https://community.risingstack.com/opencv-tutorial-computer-vision-with-node-js/)

**Comment by vdeturckheim** [comment]
[How to prevent NoSQL injections in MongoDB in a Node.js app](https://blog.sqreen.io/prevent-nosql-injections-mongodb-node-js/)

**Comment by hfeeri** [comment]
[Node.js Async Best Practices & Avoiding Callback Hell](https://blog.risingstack.com/node-js-async-best-practices-avoiding-callback-hell-node-js-at-scale/)

**Comment by hfeeri** [comment]
[How to find Node.js Performance Optimization Killers](https://community.risingstack.com/how-to-find-node-js-performance-optimization-killers/)

**Comment by watilde** [comment]
[Interested in Contributing to Node.js Core? Read On.](https://medium.com/@nodejs/interested-in-contributing-to-node-js-core-read-on-5614f60d074d#.b5105zfqo)

**Comment by hfeeri** [comment]
[Event Sourcing with Examples](https://blog.risingstack.com/event-sourcing-with-examples-node-js-at-scale/)

**Comment by hfeeri** [comment]
[Event Sourcing with Examples](https://blog.risingstack.com/event-sourcing-with-examples-node-js-at-scale/)

**Comment by hfeeri** [comment]
[CQRS (Command Query Responsibility Segregation) Explained](https://blog.risingstack.com/cqrs-explained-node-js-at-scale/
)

**Comment by mhdawson** [comment]
We are in Feb but since I don't see an issue for Feb yet I'll put it here for now:

CI testing for node-report
https://developer.ibm.com/node/2017/02/03/improved-testing-for-node-js-problem-investigation-tool/

**Comment by hfeeri** [comment]
[Getting Node.js Testing and TDD Right](https://blog.risingstack.com/getting-node-js-testing-and-tdd-right-node-js-at-scale/
)

**Comment by hfeeri** [comment]
[Using Heroku with Node.js: Production-Ready Application Checklist](https://community.risingstack.com/using-heroku-node-js-production-ready-application-checklist/
)

**Comment by sotayamashita** [comment]
@JungMinu it should close ? because it passed.

**Comment by hfeeri** [comment]
[10 Best Practices for Writing Node.js REST APIs](https://blog.risingstack.com/10-best-practices-for-writing-node-js-rest-apis/)

**Comment by fhemberger** [comment]
Closing this, as January has passed.

@hfeeri If you want the links to be included in the February update, please post them there again.
