### ISSUE TITLE
Download link broken for SunOS Binaries - 64-bit LTS Version: v6.9.2

### ISSUE THREAD

**Issue by tlhakhan** [nodejs/nodejs.org#1086]
* **URL**: https://nodejs.org/dist/v6.9.2/node-v6.9.2-sunos-x64.tar.xz
* **Browser version**: Chrome Version 55.0.2883.87 m (64-bit)
* **Operating system**: 

The download link for [SunOS Binaries] [64-bit] is not available for LTS Version: v6.9.2.

Main Links:
https://nodejs.org/en/download/

https://nodejs.org/dist/v6.9.2/

https://nodejs.org/dist/v6.9.2/node-v6.9.2-sunos-x64.tar.xz

404: Page could not be found
ENOENT: no such file or directory

Thanks,
Tenzin

**Comment by fhemberger** [comment]
Oh, you're right … the file is missing for other versions as well.

@nodejs/build Don't we build 64bit versions any longer? They are missing since v4.6.2.

**Comment by jbergstroem** [comment]
We do -- something happened with this release and we're not sure why.

**Comment by rasantel** [comment]
Maybe someone stopped publishing it because of this issue? https://github.com/nodejs/nodejs.org/issues/1086

**Comment by MylesBorins** [comment]
closing as the link now works. getting it to work has caused a bit of a mess 😁
