### ISSUE TITLE
node 4.7.1 sha256 sums differ between release post and SHASUMS256.txt

### ISSUE THREAD

**Issue by febLey** [nodejs/nodejs.org#1093]
* **URL**: https://nodejs.org/en/blog/release/v4.7.1/
* **Browser version**: 56.0.2924.51 beta (64-bit)
* **Operating system**: macOS 10.12.2 (16C67)

https://nodejs.org/en/blog/release/v4.7.1/

https://nodejs.org/dist/v4.7.1/SHASUMS256.txt

**Comment by MylesBorins** [comment]
We are aware of this an in the process of fixing it. You can follow along in https://github.com/nodejs/build/issues/586

TLDR; build assets were accidentally replaced with different shasum when promoting new builds. New release likely going out soon
