### ISSUE TITLE
Transfer nodejs.org domain name ownership to foundation

### ISSUE THREAD

**Issue by snostorm** [nodejs/nodejs.org#11]
From https://github.com/nodejs/iojs.org/issues/386 @mikeal 

We need to figure this out. We'll have to find a way to transfer the management of the domain name without interrupting the service. @misterdjules @mkdolan @nodejs/build

**Comment by mkdolan** [comment]
Hi, we control the domain but as I mentioned earlier we were a bit hesitant taking ownership as I don't think we know what the community wants us to do with it yet. Our IT team is here to help if someone can provide them with instructions. I'm not sure what services would/could be disrupted but we'll have to coordinate with Joyent's team perhaps as they may have the best visibility on the dependencies out there.

**Comment by misterdjules** [comment]
I thought the person managing the nodejs.org domain at Joyent had already confirmed to the Linux Foundation that it was fine to transfer the domain ownership, as long as no entry in the domain were removed or changed. I seem to remember that Joyent already provided all that was needed for that to happen.

Am I missing something?

**Comment by mikeal** [comment]
the foundation has the domain name but it's still pointed at the old DNS provider because nobody wants to change that without understanding all the records we might break :) I think Rod is working on a plan for this in another issue though.

**Comment by Starefossen** [comment]
Yes, a new DNS setup is being discussed in nodejs/build#124.

**Comment by mikeal** [comment]
Resolved.
