### ISSUE TITLE
[Error msg] nodejs has been replaced by nodejs4; please install that instead.

### ISSUE THREAD

**Issue by Hellgold** [nodejs/nodejs.org#1102]
* **URL**: https://nodejs.org/en/download/package-manager/#osx
* **Browser version**: not relevant
* **Operating system**: OS X.8, bash version 3.2.53(1)-release

Issue details:

There is a wrong or outdated instruction on the page https://nodejs.org/en/download/package-manager/#osx: 

Using MacPorts:
port install nodejs

When trying to install node.js this way, Terminal (bash) gives back this error:

--->  Configuring nodejs
Error: nodejs has been replaced by nodejs4; please install that instead.
Error: org.macports.configure for port nodejs returned: obsolete port
Please see the log file for port nodejs for details:
    /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_devel_nodejs/nodejs/main.log
To report a bug, follow the instructions in the guide:
    http://guide.macports.org/#project.tickets
Error: Processing of port nodejs failed

So either it is node.js or MacPorts that needs to update the installation routine.

Thanks for correcting

**Comment by fhemberger** [comment]
Thanks, we need to update the description. MacPorts packages:

```
nodejs 4.4.3 (source)
Obsolete port, replaced by nodejs4
Licenses: MIT BSD 
Maintained by: nomaintainer
Categories: devel net
Platforms: darwin 

nodejs4 4.6.1 (source)
Evented I/O for V8 JavaScript
Licenses: MIT BSD 
Maintained by: ciserlohn
Categories: devel net
Platforms: darwin 
Dependencies: openssl icu pkgconfig python27 

nodejs5 5.12.0 (source)
Evented I/O for V8 JavaScript
Licenses: MIT BSD 
Maintained by: ciserlohn
Categories: devel net
Platforms: darwin 
Dependencies: openssl icu pkgconfig python27 

nodejs6 6.9.1 (source)
Evented I/O for V8 JavaScript
Licenses: MIT BSD 
Maintained by: ciserlohn
Categories: devel net
Platforms: darwin 
Dependencies: openssl icu pkgconfig python27 

nodejs7 7.0.0 (source)
Evented I/O for V8 JavaScript
Licenses: MIT BSD 
Maintained by: ciserlohn
Categories: devel net
Platforms: darwin 
Dependencies: openssl icu pkgconfig python27 
```
