### ISSUE TITLE
Logo at top of the benchmarking.node.org and coverage.nodejs.org

### ISSUE THREAD

**Issue by mhdawson** [nodejs/nodejs.org#1110]
* **URL**:https://benchmarking.nodejs.org/, https://coverage.nodejs.org/
* **Browser version**: firefox 45.6.0
* **Operating system**: windows

The logo at the top of the coverage and benchmarking pages seems to have been changed to something that does not work out so well.

The link seems to be https://nodejs.org/static/images/logos/nodejs-new-white-pantone.png

The result used to something that was a reasonable band across the top, now its way too big and you don't see the letters.

**Comment by mhdawson** [comment]
Ok, https://nodejs.org/static/images/logos/nodejs-new-white-pantone.png was not modified recently so must be something more general.

**Comment by mhdawson** [comment]
Not sure but wonder if this might be related, as its recent: https://github.com/nodejs/nodejs.org/commit/f499302bda7b1c15d10d2ae840f530f59c9beebc

**Comment by mhdawson** [comment]
Found this which probably is a fix for the coverage problem, https://github.com/nodejs/testing/pull/47/files and it looks like it would fix the issue caused by f499302.

If it does resolve we'll just need to same fix on the benchmarking side.

**Comment by mhdawson** [comment]
Ok fix in https://github.com/nodejs/testing/pull/47 resolved the issue, so will apply same for benchmarking page tomorrow.

**Comment by silverwind** [comment]
While the logos sizes are now fixed, the PNGs should really be replaced with the [SVG](https://github.com/nodejs/nodejs.org/blob/master/static/images/logo.svg) versions I added recently. They are 1/8th of the size at no quality loss.

**Comment by mhdawson** [comment]
Ok , created issues in the appropriate repos to get those changed. Closing this issue.
