### ISSUE TITLE
about page links to 404 for "Blocking vs Non-Blocking" link

### ISSUE THREAD

**Issue by tconroy** [nodejs/nodejs.org#1111]
* **URL**: https://nodejs.org/en/about/
* **Browser version**: any
* **Operating system**: any

if you go to `https://nodejs.org/en/about/`, and click the link for `Blocking vs Non-Blocking`, it takes you to this URL: https://github.com/nodejs/node/blob/master/doc/topics/blocking-vs-non-blocking.md

which is a 404.

**Comment by fhemberger** [comment]
Good catch, thanks! I created a PR for it: #1112

**Comment by tconroy** [comment]
Thanks @fhemberger!
