### ISSUE TITLE
Turkish translations

### ISSUE THREAD

**Issue by gokaygurcan** [nodejs/nodejs.org#1116]
Hello everyone,

I'd like to help about translating nodejs.org and the api docs to Turkish. When I check https://github.com/nodejs/nodejs-tr I see it's inactive for a long time (more than a year since the last commit).

Right now, I have no rights on the repository and obviously I don't want to do all the translations and get rejected at some point. But also don't want this to become a hostile takeover. 

So, as a sum, I'm volunteer to manage that repository and the translations.

**Comment by yasinaydinnet** [comment]
Hi
I also want to help :) I already requested repo access months ago but still no response :(

**Comment by fhemberger** [comment]
Hi, great to hear you want to join us!
@mikeal Can you please help with the access to the repo?

**Comment by mikeal** [comment]
Done :) Invites should be in your inbox.

**Comment by gokaygurcan** [comment]
Thanks @mikeal and @fhemberger ^_^

**Comment by yasinaydinnet** [comment]
Done, thanks

**Comment by gokaygurcan** [comment]
@yasinaydin let's have a chat and decide how to follow. Which platform do you prefer? Slack, Gitter, Messenger, something else?

**Comment by yasinaydinnet** [comment]
@gokaygurcan Gitter would be my choice: https://gitter.im/nodejs/nodejs-tr

**Comment by fhemberger** [comment]
Closing this issue for now, as further discussions take place in https://github.com/nodejs/nodejs-tr.
