### ISSUE TITLE
Typo on https://nodejs.org/en/blog/announcements/nodejs-certified-developer-program/

### ISSUE THREAD

**Issue by dougstowell** [nodejs/nodejs.org#1124]
* **URL**:
* **Browser version**:
* **Operating system**:

To quote:

"The Node.js Certified Developer program, which is being developed with input from leading Node.js experts and contributors, is expected to be available in Q2 of"

Think you are missing 2017 on the end.

**Comment by italoacasas** [comment]
Btw I check and the year is in the file, I don't know why is not showing. 

cc: @nodejs/website

**Comment by sotayamashita** [comment]
We are talking about this file, [blog/announcements/nodejs-certified-developer-program.md](https://github.com/nodejs/nodejs.org/blob/master/locale/en/blog/announcements/nodejs-certified-developer-program.md) right?

**Comment by italoacasas** [comment]
Yes

**Comment by sotayamashita** [comment]
@italoacasas OK and it looks difference from [published one](https://nodejs.org/en/blog/announcements/nodejs-certified-developer-program/). so I try to debug.

**Comment by sotayamashita** [comment]
@italoacasas I hope that It will be solved by my PR.

**Comment by fhemberger** [comment]
Fixed by #1126.
