### ISSUE TITLE
All ivy.xml files respond with a 404 error

### ISSUE THREAD

**Issue by kidkuro** [nodejs/nodejs.org#1134]
* **URL**: https://nodejs.org/dist/v6.9.5/ivy.xml
* **Browser version**: All
* **Operating system**: All

The ivy.xml files on nodejs.org for all versions respond with a 404 error.

Anything that uses Ivy to automatically resolve the correct standalone version of Node.js from your dist directory will fail.

For example the [Gradle Node Plugin](https://github.com/srs/gradle-node-plugin) uses Ivy to download the specified version for the correct OS and architecture.

Specifically, https://nodejs.org/dist is the default [distBaseUrl](https://github.com/srs/gradle-node-plugin/blob/2573090ec2417b64ea0f5476a1d82d0119f94614/src/main/groovy/com/moowork/gradle/node/NodeExtension.groovy#L24) which is used as an [Ivy repository](https://github.com/srs/gradle-node-plugin/blob/f66eb30df530820892d6117f12a5732200bf19a4/src/main/groovy/com/moowork/gradle/node/task/SetupTask.groovy#L169).

**Comment by kidkuro** [comment]
Closing, as unnecessary. The ivy.xml file isn't required, Ivy uses a standard naming pattern to locate the files if the ivy.xml file 404s. However, our plugin was failing due to the connection closing while attempting to download the ivy.xml and it stopped immediately. A red herring.

**Comment by amnonkhen** [comment]
So, what's the solution to make gradle-node-plugin work?
