### ISSUE TITLE
Evangelism: Weekly Update for February

### ISSUE THREAD

**Issue by JungMinu** [nodejs/nodejs.org#1136]
Let's write down for next week :gift:

**Comment by mhdawson** [comment]
Update on work being done by abi stable module API team
https://developer.ibm.com/node/2017/02/16/abi-stable-module-api-node-js/

**Comment by PatrickHeneise** [comment]
We're organising NodeConf Barcelona on April 7 http://barcelona.nodeconf.com

**Comment by mhdawson** [comment]
https://developer.ibm.com/node/2017/02/21/easier-node-js-code-coverage-generation/

**Comment by watilde** [comment]
https://blog.wikimedia.org/2017/02/17/node-6-wikimedia/

**Comment by mhdawson** [comment]
https://nodejs.org/en/blog/community/quality-with-speed/

**Comment by hfeeri** [comment]
[Node.js Tutorial: End-to-End Testing with Nightwatch.js](https://blog.risingstack.com/end-to-end-testing-with-nightwatch-js-node-js-at-scale/)

**Comment by hfeeri** [comment]
[I've been a Web Developer for 17 Years, and this is what I learned - Daniel Khan at NodeConfBP](https://community.risingstack.com/ive-been-a-web-developer-for-17-years-and-this-is-what-i-learned-daniel-khan/
)

**Comment by fhemberger** [comment]
Closing this because March is almost over. ;)
