### ISSUE TITLE
Add new collaborators to the repo

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs.org#1140]
It has been a while since we added collaborators, I need to run the script again

**Comment by sotayamashita** [comment]
@fhemberger What is script ?

**Comment by fhemberger** [comment]
@sotayamashita I have a forked version of https://github.com/bengl/contribution-report to determine new collaborators. I will do it later today.

**Comment by sotayamashita** [comment]
@fhemberger I understood. Thanks

**Comment by fhemberger** [comment]
@mikeal New collaborators:

```
* @pnn 49 commits
* @ZibbyKeaton 8 commits
* @bf4 4 commits
* @junedev 4 commits
* @joshgav 3 commits
* @amandeepmittal 2 commits
* @tpreusse 2 commits
* @Qantas94Heavy 2 commits
* @Tanuja-Sawant 2 commits
* @pierreneter 2 commits
* @anirudh24seven 2 commits
* @ruggertech 2 commits
* @nhquiroz 2 commits
* @htynkn 2 commits
* @piperchester 2 commits
* @dshaw 2 commits
* @sakinac 2 commits
* @bmeurer 2 commits
* @tungtouch 1 commits
* @jjlangholtz 1 commits
* @Devinsuit 1 commits
```

**Comment by mikeal** [comment]
Should I just add everyone?

**Comment by fhemberger** [comment]
I haven't looked into individual contributions, so I'd say anybody who likes to join should do so.

Any thoughts, @nodejs/website?

**Comment by phillipj** [comment]
Not @pnn, previous contrib which stepped down voluntarily: #970

**Comment by fhemberger** [comment]
@phillipj Good catch! I lost track with all the account renaming. ;)

**Comment by ghost** [comment]
@fhemberger whoops sorry!!!

**Comment by mikeal** [comment]
ok, so all the rest then?

**Comment by fhemberger** [comment]
![Make it so](http://www.quickmeme.com/img/62/628b747f8ccdfb757062f36a27eedecfc2295f515c0586e05fbfb0620c0571a2.jpg)

**Comment by ghost** [comment]
I think so

**Comment by mikeal** [comment]
Ok, they've all been invited.

Once they accept the invitations we'll be well over 100 committers! :fireworks:

**Comment by fhemberger** [comment]
Closing this.
