### ISSUE TITLE
Help Adding Node.js Community Newsletter to the Website

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs.org#1142]
Hey -

We launched a Node.js Community newsletter a couple of months ago. The intention is to showcase cool projects that are happening within the Node.js community. It's published weekly on Tuesday. I'm wondering if we can swap out the Node Weekly link for the Node.js Community Newsletter link? You can find the community newsletter link here: http://us14.campaign-archive2.com/home/?u=c7c2e114a827812354112c23b&id=f006b61f29

The Node Weekly link is in the tab "get involved" - https://nodejs.org/en/get-involved/. Let me know what can be done here. cc: @hackygolucky and @mikeal

**Comment by fhemberger** [comment]
It would be nice if we could set up a subdomain for it, like `news.nodejs.org`. Makes it look more official then referencing `us14.campaign-archive2.com`.

/cc @nodejs/build

**Comment by jbergstroem** [comment]
Sounds good to me. Anyone else in @nodejs/build wants to chip in?

**Comment by Fishrock123** [comment]
Maybe `newsletter.nodejs.org`? So as to not be confused with the regular "news" blog?

**Comment by mikeal** [comment]
+1 to newsletter.nodejs.org

These are pretty easy to add, we should do it.

Once that is setup we should replace the other mailing list on Get Involved with this one.

**Comment by amandeepmittal** [comment]
I agree with @mikeal. 
+1

**Comment by DavidTPate** [comment]
Agreed, `newsletter.nodejs.org`

**Comment by mikeal** [comment]
@nodejs/build can we get this CNAME setup?

**Comment by ZibbyKeaton** [comment]
@nodejs/build and @mikeal wondering if you were able to easily update this. Not seeing it on the website. I'm wondering in the meantime, if we want to just add it to the "Get Involved Section" We have a link to Node Weekly, maybe we just add in the Node.js Community letter with a link to this: http://us14.campaign-archive2.com/home/?u=c7c2e114a827812354112c23b&id=f006b61f29. Copy being "Sign up for the Node.js community letter to get a weekly update on all the cool Node.js projects out there."

**Comment by mikeal** [comment]
Ok, https://newsletter.nodejs.org is live.
