### ISSUE TITLE
Can we add the release team to have push access?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/nodejs.org#1144]
New members of the release team do not necessarily already have push access to this repo.

**Comment by mikeal** [comment]
What team do we use for the release engineers?

What do the release engineers need to push on release?

We already give the build team write access because we sit on top of infra they manage so I'm just checking if we already do this.

**Comment by MylesBorins** [comment]
@nodejs/release 

When doing a release the release notes + blog post need to be published

Not everyone on release is part of build

**Comment by mikeal** [comment]
ah, i see. 

makes sense to add that team to the repo.

any objections?

**Comment by Fishrock123** [comment]
oh heh, guess we haven't run into that in quite a long time

+1

**Comment by italoacasas** [comment]
Hello everyone, any update on this?

**Comment by Trott** [comment]
+1. Let's do this thing!

**Comment by Fishrock123** [comment]
I've added the `release` team to have write access to this repo. Please let me know if you have any concerns.
