### ISSUE TITLE
Why can`t I download mp3 files from nodeup.com

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#1147]
* **URL**:http://nodeup.com/
* **Browser version**:All Browser
* **Operating system**:All Operating System

I am in Zhejiang,China.I can`t reach all mp3 files from nodeup.com.Is nodeup.com has been shielded by Great Firewall?

**Comment by ruggertech** [comment]
not sure this is something they would want to block.
maybe a different network problem.  Can you ask someone in your neighborhood or another city to try and see if they succeed?

**Comment by fhemberger** [comment]
Still, this is not a **nodejs.org** issue, so I'm closing this. :smile:
