### ISSUE TITLE
Editorial governance of the website

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#1158]
There's been a lot of questions and concerns recently about how editorial decisions are made across the website.

The website has always had a clear separation of concerns between the website *code* and the website *content*. Over time the number of groups involved in content has grown and some of the content needs have required substantive code changes (like analytics).

It's worth revisiting and better defining the editorial governance after all of that growth.

First, I'd like to catalog the groups involved in content and then, later, try to define which types of content they might need editorial control over.

Please let me know of additional groups to add to this list:

* Evangelism WG
* Localization WGs (there's 7 currently active in the website but more could be involved in the future)
* Core Release Team
* Node.js Foundation Communications/Marketing Team
* Node.js Foundation Administrators (community managers, program managers, directors, member services)

**Comment by fhemberger** [comment]
@mikeal It would be nice if all those groups could be added as GitHub teams, so if we need to get in contact, we know who's responsible for what.

There are still some issues where I'd like to get some "official" feedback from the Foundation (e.g. regarding content and design) or at least know the right persons to get in touch with. There are a lot of things that I'd like to see addressed. Sometimes it's only a simple "yay" or "nay" missing or someone taking the initiative to address an issue.

Issue list:
- [content](https://github.com/nodejs/nodejs.org/issues?q=is%3Aissue+is%3Aopen+label%3Acontent)
- [design](https://github.com/nodejs/nodejs.org/issues?q=is%3Aissue+is%3Aopen+label%3Adesign)

**Comment by fhemberger** [comment]
Closing: Node.js Foundation has their own website now, release team takes care of the release blog posts, the rest is mostly shared between the WGs for Website, Evangelism and ComCom.

Please feel free to re-open if there are further topics to be discussed.
