### ISSUE TITLE
There is a bug about the require function

### ISSUE THREAD

**Issue by huge818** [nodejs/nodejs.org#1160]
* **URL**:
* **Browser version**:
* **Operating system**:  windows8.1   x64

There is  a bug in the require function.

I found that if I **require** a  .node file。the bug on the  the latest version (LTS), older version is ok!

node6.10.0  is not ok!
node 4.3.1   is ok.

command line error show that the path is error,  There are redundant characters in front of path
example: **\\?** G:\Program Files (x86)\test

the other else version have not test.

by the way ,I use the npm package module **cap**

**npm install cap,** 

I build is success in node4.3.1 （windows10） （It took me a long time，You know, windows compiler is very troublesome ） , 
but I use it in node6.10.0 on the other computer(win10, node 6.10.0)
 
excuse me，my english is poor！but ,my means is clear.

that's all!

**Comment by fhemberger** [comment]
Hi,

this is the bug tracker for the node.js **website**, so I think you're looking for [Node.js issues](https://github.com/nodejs/node/issues) instead. Maybe someone from @nodejs/nodejs-cn can help you with the details of the issue.

(As far as I understood, could this be an utf-8 or BOM issue?)

**Comment by huge818** [comment]
this is Start from iojs

**Comment by laosb** [comment]
@Einsy 你好，根据你上面的描述，这是一个 Node.js 的 bug，而不是一个Node.js 网站的问题。请汇报至 https://github.com/nodejs/node/issues ，谢谢！如果您在语言上存在一定问题，请在汇报后 at nodejs/nodejs-cn 或者直接 at 我，我将尽力提供帮助。
