### ISSUE TITLE
Please add Enterprise Conversation #10 to the Node.js Website under "Resources"

### ISSUE THREAD

**Issue by serenam18** [nodejs/nodejs.org#1169]
Hi Can you please add this new enterprise conversation to the website? 

**Emerging Technology Advisors (Episode 10)** 
Tracy and Mikeal chat with Chris Williams, founder of  Emerging Technology Advisors, about a variety projects in which companies have adopted Node.js during different stages of transition and growth.

https://youtu.be/w9gbcZJOgPY

Thanks so much for your help!
Serena 

* **URL**:
* **Browser version**:
* **Operating system**:

**Comment by serenam18** [comment]
thank you!

**Comment by lpinca** [comment]
@serenam18 no problem. PR is waiting to be reviewed.
