### ISSUE TITLE
Some `dist/` folders are offline

### ISSUE THREAD

**Issue by marcomarcianesi** [nodejs/nodejs.org#1172]
* **URLS**: https://nodejs.org/dist/v0.10.47/ , https://nodejs.org/dist/v0.10.46/ and others

the page is offline

![image](https://cloud.githubusercontent.com/assets/19145520/24035540/3775e966-0af6-11e7-9da7-0dbf85881e77.png)

Marco

**Comment by cacogr** [comment]
The LTS one too https://nodejs.org/dist/v6.10.0

**Comment by Eugene1982** [comment]
https://nodejs.org/download/release/v6.9.0/node-v6.9.0-win-x64.zip too

**Comment by cacogr** [comment]
Came back to life just now
