### ISSUE TITLE
Improve navigation through guides

### ISSUE THREAD

**Issue by jitendra3109** [nodejs/nodejs.org#1173]
* **https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction/**:
* **Chrome**:
* **Linux(Ubuntu 16.04)**:

 Reading documents of Nodejs.Something I feel to a problem, again and again, go to up and then go to next page too.It will user face problem.
So suggestion why not create a button or sticky sidebar which more helpful.
![image](https://cloud.githubusercontent.com/assets/10773353/24092048/e8e4d40a-0d71-11e7-8813-5de1b151695a.png)
[Link](https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction/)

**Comment by vsemozhetbyt** [comment]
Do you suggest something [like this](http://docs.nwjs.io/en/latest/For%20Users/Getting%20Started/) for the guides section?

![1](https://cloud.githubusercontent.com/assets/10393198/24098919/8209bc92-0d75-11e7-827a-df3469b2e628.png)

'sticky sidebar' is 1, 'a button' is 2.

**Comment by jitendra3109** [comment]
@vsemozhetbyt 
Both of are good if these will be implemented here also [link](https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction/)
I prefer personally 2nd it will be good.

**Comment by vsemozhetbyt** [comment]
Thank you for the suggestion. Let's hope it will be accepted by the site developers.

**Comment by Fishrock123** [comment]
As a note, the docs themselves and the styling lives in the main node repo: https://github.com/nodejs/node

That is so that we can distribute static, offline docs, and keep them perfectly in-sync with api changes.

I think here is fine to discuss this for now though.

---

I think both 1 and 2 are good ideas.

Both probably have interesting challenges relating to file locations though.

**Comment by vsemozhetbyt** [comment]
@Fishrock123 Sorry, it was me who [has redirected](https://github.com/nodejs/node/issues/10218) @jsroyal here, I wrongly thought this case is not for `nodejs/node` doc set.

**Comment by fhemberger** [comment]
Fixed by #1286.
