### ISSUE TITLE
Help adding Call for Paper to Node.js website

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs.org#1174]
Hey All - We are trying to get more awareness around our call for presentations (CFP) for Node.js Interactive. Given the amount of traffic to the website, we thought it would be nice to have banner on the homepage of the website to focus on the CFP and attract folks that might not normally follow us on social.

I have an .eps [file here ](https://drive.google.com/drive/folders/0BwyeYdMvqcwFRkwzRWxzT3M0Zms?usp=sharing) and can also share a psd file. The CFP closes on April 10, so we are trying to get this up as soon as possible. Thanks as always for your help here. cc: @hackygolucky and @mikeal

**Comment by lpinca** [comment]
Also cc: @nodejs/website

**Comment by bnb** [comment]
@ZibbyKeaton I can't access that file 🤔

**Comment by ZibbyKeaton** [comment]
@bnb I just added you to the doc. Let me know if you can access now?

**Comment by ZibbyKeaton** [comment]
@bnb just poking to make sure you can access and use these files. Happy to try to get something else for you here.

**Comment by lpinca** [comment]
Fixed by #1179.

**Comment by lpinca** [comment]
@ZibbyKeaton is it possible to make a zip with the files and upload it here?
