### ISSUE TITLE
State Compilation Requirements on Downloads Webpage

### ISSUE THREAD

**Issue by DarioS** [nodejs/nodejs.org#1177]
Although the requirements are contained in the BUILDING.md file, it would be nice to see them before downloading the software, such as in the list of links at the bottom of the [Downloads ](https://nodejs.org/en/download/) webpage.

**Comment by fhemberger** [comment]
Would replacing the sentence "Note: Python 2.6 or 2.7 is required to build from source tarballs." with a link [Building Node.js on supported platforms](https://github.com/nodejs/node/blob/master/BUILDING.md#building-nodejs-on-supported-platforms) be okay for you?

**Comment by DarioS** [comment]
That's a good idea. It would make clear the gcc version necessary.
