### ISSUE TITLE
dshaw listed twice on board page

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#1178]
Just realized Daniel Shaw is listed twice on the board page https://nodejs.org/en/foundation/board/

**Comment by fhemberger** [comment]
@mikeal So what's his role? Gold-Level Director or Secretary?

**Comment by mikeal** [comment]
Both ;)

**Comment by fhemberger** [comment]
As he has two distinct positions, let him appear twice. ;)

**Comment by mikeal** [comment]
Or... and hear me out on this, we use a comma :)

**Comment by fhemberger** [comment]
THAT'S CRAZY TALK!

**Comment by williamkapke** [comment]
Yes. And actually, the Platinum directors should be labeled as being Platinum. Furthermore, the TSC Director probably should not have an affiliation with their company or Ashley should have NPM after her name.

List this:
* Platinum Director, Chairperson: **Danese Cooper**, Distinguished Member of Technical Staff - open source at PayPal.
* Platinum Director, Vice-Chairperson: **Scott Hammond**, Chief Executive Officer at Joyent.
* Gold Director, Secretary: **Dan Shaw**, Chief Technology Officer at NodeSource.
* Platinum Director: **Todd Moore**, Vice President of Open Technology at IBM.
* Platinum Director: **Gaurav Seth**, Principal Program Manager at Microsoft.
* Platinum Director: **Rich Sharples**, Senior Director of Product Management at Red Hat.
* Platinum Director: **Mark Skarpness**, Vice President, Software and Services Group at Intel.
* Gold-Level Director: **Dan Shaw**, Chief Technology Officer at NodeSource.
* Silver-Level Director: **Brian McCallister**, Chief Technology Officer of Platforms at Groupon.
* Silver-Level Director: **Justin Beckwith**, Product Manager at Google.
* TSC Director: **Rod Vagg**
* Individual Director: **Ashley Williams**
* Individual Director: **William Kapke**

**Comment by mikeal** [comment]
Maybe we can also show the term for each Individual Director.

* Individual Director (2016-2018): Ashley Williams
* Individual Director (2017-2019): William Kapke

**Comment by fhemberger** [comment]
Did a quick PR for that.
