### ISSUE TITLE
Rewrite outreachy page (was: remove outreachy page?)

### ISSUE THREAD

**Issue by Trott** [nodejs/nodejs.org#1185]
Our Outreachy participation is over (for now at least?). I think https://nodejs.org/en/foundation/outreachy/ can be removed. /cc @hackygolucky

**Comment by fhemberger** [comment]
I'm against removing it, let's edit it instead to show, that the Node.js project participated (and intends to do so in the future as well). When people visit our website, this commitment to an inclusive environment should be visible.

**Comment by amandeepmittal** [comment]
I am  with @fhemberger & I think a showcase will significantly improve the commitment to expand the program.

**Comment by hackygolucky** [comment]
Good question! I should update the page to reflect that is a prior year and to look forward towards news of our next round of Node.js intership offerings. We are running through our Outreachy post-mortem with our mentors and mentees over the next few weeks to see how we can improve, but we will continue to invest in this work.

**Comment by Trott** [comment]
Sure, update instead of remove, sounds good. Either way.

**Comment by fhemberger** [comment]
@hackygolucky Any feedback from the post-mortem? It would be great if you could find the time to update the page with the results.

**Comment by ghost** [comment]
Any update on this?

**Comment by Trott** [comment]
I'm back to "let's remove it". Here's my thinking:

* A new page can be created if/when Node.js is doing something similar again. (Maybe @hackygolucky already knows of something in the works?)

* IMO, in this particular instance, having outdated/wrong content is worse than having no content at all.

* Also, IMO, when in doubt, remove the content. There is certainly too much stuff on the website, not too little. It's easy to add things if there's a gap. It's often difficult or impossible to get people to remove things, even things that are outdate/wrong. As such, removal requires advocacy. So I'm advocating. :-D

**Comment by ghost** [comment]
LGTM

**Comment by fhemberger** [comment]
@trott Ok, makes sense. Can you please submit a PR?

**Comment by Trott** [comment]
https://github.com/nodejs/nodejs.org/pull/1429
