### ISSUE TITLE
Request on Highlighting the Community Newsletter on the Website

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs.org#1190]
Hey All -

We received the below request on the community newsletter. I understand that the builds team, just added it to our Get Involved section, but if this group feels like it should be highlighted more and has a good place to put, I wanted to pass this along.

![screen shot 2017-04-04 at 4 02 15 pm](https://cloud.githubusercontent.com/assets/15021989/24676218/23652ef6-1950-11e7-804f-4f3a835cb2f4.png)

**Comment by mikeal** [comment]
We should feature it more prominently, perhaps on the front page.

**Comment by RCMainak** [comment]
I would like to fix this issue. Where can I start?

**Comment by mikeal** [comment]
@RCMainak should just be able to edit the Get Involved markdown file in the english content directory :)

**Comment by RCMainak** [comment]
@mikeal Sorry, I'm bit lost. Why do I need to edit the Get Involved file? Isn't the plan was to bring that link to the front page?

I thought I need add the Newsletter link to the front page or the footer.

**Comment by mikeal** [comment]
Sorry, my bad, I read the original description incorrectly.
