### ISSUE TITLE
Receiving intermittent 522 Timeouts on nodejs.org download

### ISSUE THREAD

**Issue by jasnell** [nodejs/nodejs.org#1191]
The https://nodejs.org/download site is running very slow and is returning intermittent 522 connection timeouts from cloudflare. It's very inconsistent but definitely having an issue.

**Comment by williamkapke** [comment]
Yup. Downtime again :(

@nodejs/build

**Comment by fhemberger** [comment]
Just tested it from Germany: Same issue, page takes forever to load, then a Cloudflare snapshot is shown instead.

**Comment by WayneUong** [comment]
A few weeks ago it was AWS, now Node..

**Comment by mjhea0** [comment]
https://nodejs.org/dist/v7.8.0/node-v7.8.0-linux-x64.tar.xz is down for me (Denver, CO)
<img width="1134" alt="screen shot 2017-04-04 at 4 27 54 pm" src="https://cloud.githubusercontent.com/assets/2018167/24681725/bad32100-1953-11e7-9bc8-cc24d0860ad2.png">

**Comment by NWitmer** [comment]
Occurred at  2017-04-04 22:22:25 UTC for us in case it helps looking through the logs

**Comment by easauceda** [comment]
https://nodejs.org/dist/v6.10.0/node-v6.10.0-headers.tar.gz <-- can't download this either

Same issue, Cloudflare snapshot with 522 error

**Comment by MichaelSullivan** [comment]
+1 - We are seeing the issue every time we attempt to hit https://nodejs.org/dist/v6.9.4/node-v6.9.4-linux-x64.tar.xz -- not intermittently.

**Comment by dorogarcia** [comment]
+1 - I have the same problem :(

**Comment by mtthwgry** [comment]
http://nodejs.org/dist/v0.10.30/node-v0.10.30-linux-x64.tar.gz has been dead in the water for the past 30-ish minutes.

**Comment by feross** [comment]
FYI, for anyone wondering why Travis is running their tests using Node 0.10, no matter what you specify, it's because of this issue.

**Comment by blakewest** [comment]
We're seeing this on Circle CI too, every time, for node 6.7:
![image](https://cloud.githubusercontent.com/assets/2524396/24682347/0ca515ca-194e-11e7-8f4d-850de4a2174b.png)

**Comment by brocoli** [comment]
Same here, can't even open the "all downloads" page from nodejs.org in Brazil.
Can't deploy app because npm install fails when trying to download node v4.6.2 headers for node-gyp

**Comment by fluxsauce** [comment]
Similar on Travis CI.

![screen shot 2017-04-04 at 3 52 26 pm](https://cloud.githubusercontent.com/assets/976391/24682470/c2eca956-194e-11e7-9426-8c0b53e91242.png)

**Comment by jonnylynchy** [comment]
Same here. Getting checksum verification issues after timeout.

> ######################################################################## 100.0%
> Checksums do not match.
> Binary download failed, trying source.

**Comment by vvillait88** [comment]
Heroku node deploys are broken too

**Comment by guilherme-salome** [comment]
Same here, trying to install v7.8.0 through nvm and Checksum fails.

<img width="638" alt="screenshot 2017-04-04 18 54 37" src="https://cloud.githubusercontent.com/assets/7663115/24682523/2c916734-1968-11e7-84eb-9e95fb4d8351.png">

**Comment by drazisil** [comment]
CircleCI here. Monitoring this thread. Can the NodeJS team ping us when resolved?

**Comment by MicahZoltu** [comment]
# PSA - Read Before Commenting

Anyone interested in getting update notifications, click the "Subscribe" button on the right side of this page.

**If you don't have additional information beyond "nodejs.org (or some component thereof) isn't working for me" please don't comment on this issue**, just subscribe and/or use the reaction emojis so the rest of us who are subscribed don't get spammed.

The NodeJS team is aware of the problem and are directing users here via twitter: https://twitter.com/nodejs/status/849390481314373635 so keeping the spam down is valuable.

**Comment by iameli** [comment]
If all you need is a node download, there's a mirror at https://cnpmjs.org/mirrors/node/.

**Comment by jules2689** [comment]
There is also this mirror: https://mirrors.ustc.edu.cn/node/
I was able to successfully download 6.1.0 for linux x64 and verify the checksum.

**Comment by krypt3d** [comment]
Thanks for the mirror sites guys

**Comment by feryardiant** [comment]
Same issue here.

Can't install node 6 & also with checksums missmatch

```
$  nvm install --lts=boron
Installing with latest version of LTS line: boron
Downloading and installing node v6.10.2...
Local cache found: $NVM_DIR/.cache/bin/node-v6.10.2-linux-x64/node-v6.10.2-linux-x64.tar.xz
Computing checksum with sha256sum
Checksums do not match: '5124e2795f221508a4000d8c6c0ff5cf978480c5cbff8c9ff69caae9e8c06a1c' found, 'b519cd616b0671ab789d2645c5c026deb7e016d73a867ab4b1b8c9ceba9c3503' expected.
Checksum check failed!
Removing the broken local cache...
Downloading https://nodejs.org/dist/v6.10.2/node-v6.10.2-linux-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums do not match: '21710d0294b2ac034d4452b3be6ba556ceab6bb13ad812c4ff3db49d167b6954' found, 'b519cd616b0671ab789d2645c5c026deb7e016d73a867ab4b1b8c9ceba9c3503' expected.
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Binary download failed, trying source.
Local cache found: $NVM_DIR/.cache/src/node-v6.10.2/node-v6.10.2.tar.xz
Computing checksum with sha256sum
Checksums do not match: '5606211d79c42b667108022e0fcc3f0d7b1fd1f14c0a8022dd49fe1955b0ceec' found, '80aa11333da99813973a99646e2113c6be5b63f665c0731ed14ecb94cbe846b6' expected.
Checksum check failed!
Removing the broken local cache...
Downloading https://nodejs.org/dist/v6.10.2/node-v6.10.2.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums do not match: 'f38c8f8bbe5601c1b6901207b5e57bf3a5dc0c7aa78055ec6b4f52927620e1d5' found, '80aa11333da99813973a99646e2113c6be5b63f665c0731ed14ecb94cbe846b6' expected.
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
nvm: install v6.10.2 failed!
```

**EDIT**

Thanks for the mirror sites 😁

**Comment by simllll** [comment]
I'm using elastic beanstalk, my deployment fails right now due to 
> ursa@0.9.4 install /tmp/deployment/application/node_modules/ursa
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 522 response downloading https://nodejs.org/download/release/v6.10.0/node-v6.10.0-headers.tar.gz
gyp ERR! stack at Request. (/opt/elasticbeanstalk/node-install/node-v6.10.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack at emitOne (events.js:101:20)

Do you have any idea how I could specify a mirror site in this case?? thanks

**Comment by ecoruh** [comment]
Australia. No luck, I have error 522 too. I first suspected nvm-windows playing up, and uninstalled node.js. Now i can't download it either.

**Comment by interglobalmedia** [comment]
Still down. Any idea when it might be running again?

**Comment by ecoruh** [comment]
The lesson for me: stick to your msi.

**Comment by jasnell** [comment]
No clear picture yet. The issue appears to be with a file system failure at the New York data center. Will update when we can.

**Comment by enzoftware** [comment]
I can't download nodejs from the official web , when will be return the downloads?

**Comment by jbergstroem** [comment]
Disk issue; digitalocean confirmed. We have an issue opened. Http://unencrypted.nodejs.org acts as mirror should you need.

**Comment by interglobalmedia** [comment]
Luckily I'm in no rush. I can wait until issue is resolved. Thanks guys!

**Comment by interglobalmedia** [comment]
Wow. Trying to be nice and such reactions. Oh well, can't please everyone.

**Comment by interglobalmedia** [comment]
Well, hopefully it gets fixed quickly!

**Comment by dorogarcia** [comment]
low cost server to important project... :(

**Comment by codingwaysarg** [comment]
Is it working now? https://nodejs.org/en/download/

**Comment by ibc** [comment]
> FYI, for anyone wondering why Travis is running their tests using Node 0.10, no matter what you specify, it's because of this issue.

@feross, in my case, even if my `.travis.yaml` file specifies node 4, 6 and 7, the executed version is always v4.1.2.

**Comment by llama** [comment]
My server just successfully downloaded from nodejs.org. Go download fast before the thundering herd arrives.

**Comment by jbergstroem** [comment]
> @llama said:
> My server just successfully downloaded from nodejs.org. Go download fast before the thundering herd arrives.

Let me remind everyone that http://unencrypted.nodejs.org is available over http and rsync if you need to download.

We're working as quick as we can to be back online.

**Comment by makeawebsitewithhtml** [comment]
@llama Still not working for me.

**Comment by interglobalmedia** [comment]
Also still not working for me.

**Comment by dorogarcia** [comment]
working!!!

**Comment by cleondz** [comment]
working on my side now 👍

**Comment by ericjiang97** [comment]
Working!!!

**Comment by josephgrossberg** [comment]
@interglobalmedia et al. -- please note the highlighted text. Your comments on this thread are sent to hundreds of people, waiting to hear crucial updates. I understand your intent is to be helpful; hopefully this additional context clarifies all the 👎 reactions. 

<img width="887" alt="screen shot 2017-04-04 at 5 31 39 pm" src="https://cloud.githubusercontent.com/assets/1637/24684693/b6b67f50-195c-11e7-8473-14238602b8c2.png">

**Comment by ghost** [comment]
Working!

**Comment by jbergstroem** [comment]
DO just told us that everything should be fixed. We can expect a post-mortem tomorrow (think 24h). We will update as we get more information.

Edit: should also mention that I can confirm that disk IO and load have returned to near-normal levels.

Edit2: the build team will confer on a few actions so we become more resilient against one hosting provider having issues. I'll link to the issue once created.

**Comment by jasnell** [comment]
Now that we're back up and running, I'm going to close and lock this issue. Thank you everyone for your patience during the outage.

**Comment by PeterDaveHello** [comment]
Try this one http://ftp.yzu.edu.tw/nodejs.org-dist when you need it, ping me if you need support.
(`export NVM_NODEJS_ORG_MIRROR="http://ftp.yzu.edu.tw/nodejs.org-dist"` for the node version manager!)
