### ISSUE TITLE
nodejs.org down or having serious performance problems, breaks CI builds with `nvm`

### ISSUE THREAD

**Issue by hovissimo** [nodejs/nodejs.org#1192]
* **URL**: https://nodejs.org/dist/v6.10.2/node-v6.10.2-linux-x64.tar.xz
* **Browser version**: Any (tested with latest Chrome, nvm, and curl)
* **Operating system**: Any (tested with W10 and Ubuntu 16.04)

Downloads of node failing during CI builds while using `nvm`.  Cloudflare is returning 522.  This looks similar too, but is almost certainly not the same as, #1061 

Cloudflare status page reports green. (https://www.cloudflarestatus.com/)

Visiting https://nodejs.org directly is extremely slow (>20s) when it works at all.

**Comment by paladox** [comment]
Im too am having this problem with building jenkins.

it try to download https://nodejs.org/dist/v4.0.0/node-v4.0.0-linux-x64.tar.gz

**Comment by hovissimo** [comment]
Didn't see #1191.
