### ISSUE TITLE
Slight error in documentation

### ISSUE THREAD

**Issue by Flegnor** [nodejs/nodejs.org#1195]
* https://nodejs.org/en/docs/es6/:
* Chrome 57
* Windows 10

On the above-mentioned page, there is the following text:

"The V8 team is constantly working to improve the performance of new language features to eventually reach parity with their transpiled or naive counterparts in EcmaScript 5 and earlier. "

I believe that "naive" should read "native," shouldn't it?
I've also never seen the word "transpiled" before, but I get the idea.

**Comment by drazisil** [comment]
`transpiled` is valid, see http://www.thefreedictionary.com/transpiler :)

https://babeljs.io/ is a common example.

**Comment by Flegnor** [comment]
Is "naive" also correct?

**Comment by gibfahn** [comment]
Pretty sure you're right about `naive`->`native`.

**Comment by gibfahn** [comment]
Looks like it was added in https://github.com/nodejs/nodejs.org/commit/d89e5a73863d18554861d0c0f900620b4886b4aa, so cc/ @bmeurer

**Comment by elboletaire** [comment]
It could be refer to `naive` as `primitive`. It makes sense in this sentence, but I may be wrong.

http://www.wordreference.com/definition/naive

**Comment by Fishrock123** [comment]
It should be `native`.

**Comment by alex-blair** [comment]
I'll take this up (been looking for a good first contribution!)

**Comment by vsemozhetbyt** [comment]
@alex-blair Thank you! If I get it right, the file is https://github.com/nodejs/nodejs.org/blob/master/locale/en/docs/es6.md

And there are 2 'naive' in that paragraph.

**Comment by gautamkrishnar** [comment]
can we close this one?
