### ISSUE TITLE
Node in Catalan!

### ISSUE THREAD

**Issue by williamkapke** [nodejs/nodejs.org#1197]
We have a volunteer for Catalan translations! @elboletaire would like to give it a shot. How does a new site get added?

@elboletaire, be sure to check out these in the meantime:
https://github.com/nodejs/nodejs.org/blob/master/CONTRIBUTING.md
https://github.com/nodejs/nodejs.org/blob/master/TRANSLATION.md

/cc
@nodejs/website 
@nodejs/documentation

**Comment by elboletaire** [comment]
Yeah, I would be glad to translate this. And I'm sure others will help too 😃

**Comment by watilde** [comment]
I think we can add a new locale directory in [here](https://github.com/nodejs/nodejs.org/tree/master/locale), and that's it on the website. For the i18n WG, opening an issue on [TSC](https://github.com/nodejs/TSC) repository would help :)

**Comment by davesnx** [comment]
I can help too 👍

**Comment by franher** [comment]
Hello, I just created the PR with the initial set of translated files #1221 

I encourage NodeConf BCN colleagues to help me with the remaining files to have a really good catalan translation 💪

**Comment by jseijas** [comment]
@franher Good Job! I would like to help, but unfortunately my catalan skill is too basic :( But for sure you can engage people to help you with this, the Catalan Node Community is great :)

**Comment by fhemberger** [comment]
Closing this issue, as Catalan translations are coming in. If you need further help, please let us know!
