### ISSUE TITLE
Clearer instructions for new contributors in README.md

### ISSUE THREAD

**Issue by alex-blair** [nodejs/nodejs.org#1199]
https://github.com/nodejs/nodejs.org/blob/master/README.md

The instructions for contributing to nodejs.org could be made a little clearer for beginners (especially those who haven't contributed to open source before). 

At the moment the instructions for getting started say:

<img width="595" alt="screen shot 2017-04-11 at 10 48 41 am" src="https://cloud.githubusercontent.com/assets/23412989/24885787/8c964ca8-1ea4-11e7-9a75-686649c1722b.png">

I think it would be helpful for first-time contributors if there was an extra line saying "To get started, fork the repository. Then: 
$ git clone https://github.com/nodejs/nodejs.org.git
$ cd nodejs.org
$ npm install
$ npm start "

**Comment by fhemberger** [comment]
Hi, good point! I rephrased the paragraph a bit, please let me know what you think:
https://github.com/nodejs/nodejs.org/pull/1203
