### ISSUE TITLE
Create a page for 2017 Collaborator Summit

### ISSUE THREAD

**Issue by ashleygwilliams** [nodejs/nodejs.org#1208]
per convo with @hackygolucky @mikeal @williamkapke @addaleax @jasnell 

- set expectations for the event
- include details re: location and time
- list working groups that will be present
- link to a page to reserve a ticket

**Comment by hackygolucky** [comment]
Awesome @ashleygwilliams ! @mikeal already got the ti.to account open and I created a ticket. Link is here but let me know when to set it to live https://ti.to/node-js/collaboration-summit-2017-berlin/with/oqfqossh4-u

**Comment by lpinca** [comment]
Can this be closed?

**Comment by fhemberger** [comment]
Summit is over, so yes.
