### ISSUE TITLE
Add Node Todo link under Code and Learn section?

### ISSUE THREAD

**Issue by amandeepmittal** [nodejs/nodejs.org#1209]
* **URL**: https://nodejs.org/en/get-involved/code-and-learn/
* **Browser version**: Chrome 55.0.2883
* **Operating system**: macOS X

I think it'd be appropriate to add a link of [Node Todo](http://nodetodo.org/) under [Code + Learn](https://nodejs.org/en/get-involved/code-and-learn/) section. It will be good association for the new developers who want to contribute and having something to read on the matter on the official website.

**Comment by lpinca** [comment]
I agree, 👍

**Comment by lpinca** [comment]
It could go also under [contribute](https://nodejs.org/en/get-involved/contribute/), maybe that is a better place as Code + Learn is an event with mentors etc, not sure.

**Comment by amandeepmittal** [comment]
@lpinca I think you are right. `contribute` is better suited since it contain all the links. Shall I make a PR then if `contribute` is good?

**Comment by lpinca** [comment]
I would say go for it.

**Comment by amandeepmittal** [comment]
I think this issue can closed since PR #1210 is merged.
