### ISSUE TITLE
Mentioning Software Collections for RHEL/CentOS install

### ISSUE THREAD

**Issue by kasicka** [nodejs/nodejs.org#1212]
I was wondering, if Software Collections could be listed as a way to install Node.js on RHEL/CentOS. While we can support newer releases of Node.js in EPEL 7, we are not able to build them on older systems, so we only provide them through SCLs.

**Comment by gibfahn** [comment]
If you mean adding something to https://nodejs.org/en/download/package-manager/ , then that seems reasonable. Would you be interested in filing a PR?

Relevant file is https://github.com/nodejs/nodejs.org/blob/master/locale/en/download/package-manager.md

**Comment by fhemberger** [comment]
Fixed by #1279, closing.
