### ISSUE TITLE
Adding Node.js Collection to the website

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs.org#1217]
I thought it might be nice to add a link to the Node.js Medium publication (Node.js Collection) to the website. It seems to fit in the "Get Involved" tab under the "discussion" subhead. Here's a link to the site: https://medium.com/the-node-js-collection cc: @hackygolucky @mikeal

**Comment by sotayamashita** [comment]
@ZibbyKeaton who does maintain this collection?

**Comment by ZibbyKeaton** [comment]
@sotayamashita it's a collaboration between the Node.js Foundation and the evangelism working group. Here's a bit more background if you need it: http://bit.ly/2lzkmjD

**Comment by sotayamashita** [comment]
@ZibbyKeaton Thank you. I think it is great.
