### ISSUE TITLE
Silent fail installation instructions

### ISSUE THREAD

**Issue by haanjde** [nodejs/nodejs.org#1220]
* **URL**: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
* **Browser version**: NA
* **Operating system**: Debian 8.7.1 Jessie

The instructions on the mentioned page contain an error in that when the "curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -" command fails by being unable to reach a DNS server, it fails silently and with a returncode of 0.

Please correct this or put a warning in place.

**Comment by lpinca** [comment]
The installation script is provided by NodeSource so I think this issue should be reported here: https://github.com/nodesource/distributions.

**Comment by gibfahn** [comment]
Raised https://github.com/nodesource/distributions/issues/477, we should close this.

**Comment by fhemberger** [comment]
@gibfahn But we need to make sure that updates of `nodesource/distributions` find their way back again, that's the reason I wanted to keep this issue open.

**Comment by gibfahn** [comment]
>But we need to make sure that updates of nodesource/distributions find their way back again, that's the reason I wanted to keep this issue open.

You mean that https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions will need to be updated once that issue is resolved? I don't think that's the case, that page will stay the same, it's just the script you curl that will have some changes.

**Comment by fhemberger** [comment]
@gibfahn Ah, my bad. You're right. Closing.
