### ISSUE TITLE
v0.12 docs missing a page

### ISSUE THREAD

**Issue by jandrieu** [nodejs/nodejs.org#1227]
* **URL**: https://nodejs.org/docs/v0.12.0/api/tracing.html
* **Browser version**: Chrome Version 58.0.3029.110 (64-bit)
* **Operating system**: Ubuntu 64 14.04 64-bit

The page is a 404 not found, despite its entry on the main api page https://nodejs.org/docs/v0.12.0/api/

Fortunately, it is the only link on that page with this problem.

Looking at https://nodejs.org/docs/v0.12.0/api/all.html, it appears that there simply shouldn't be a tracing.html entry.

**Comment by fhemberger** [comment]
Wrong link seems to appear only in

- https://nodejs.org/docs/v0.12.0/api/
- https://nodejs.org/docs/v0.12.1/api/

subsequent versions look fine, so is https://nodejs.org/docs/latest-v0.12.x/api/.
Thanks for reporting, but manually editing generated docs on the web server (especially for a long long deprecated version) is a bit of a hassle. So I hope you don't mind me closing this issue.
