### ISSUE TITLE
Self-Serve Case Studies and Testimonials 

### ISSUE THREAD

**Issue by serenam18** [nodejs/nodejs.org#1230]
Hi, I’m Serena from the Node.js Foundation Marketing Team. The Marketing Committee, led by @ShubhraKar, has been working on some really exciting ideas to help promote Node.js and we are ready to detail a new section under the Foundation portion of the website.

In order to make it easier to highlight various ways people and businesses are using Node.js, we would like to add a few pages to the Foundation/Resources section. 

Below is the workflow we’d like to implement for capturing “Self-Serve Case Studies” as well as some ideas on how to best present them. These changes will help us capture new innovations with how Node.js is being utilized. 

This request for discussion invites ideas and collaboration on the proposed workflow as well as developing the web pages and assets needed. The proposal is only for reference purposes and in not intended to serve as the final design.

Primary Landing Page: [https://nodejs.org/en/foundation/case-studies/](https://nodejs.org/en/foundation/case-studies/)

  

![image11](https://cloud.githubusercontent.com/assets/23459465/26177124/55f6c940-3b0d-11e7-9b76-3703f65c3c17.png)

The proposed changes to the case study section  are the following: 

## Sample workflow and layouts

1. Listings (Example) 

#### 1.1 Categories (Click to see relevant case studies & testimonials)
![image8](https://cloud.githubusercontent.com/assets/23459465/26177202/a3005cec-3b0d-11e7-87b1-7aad7824c9bb.png)

 

#### 1. 2 Logo Board under each category (Click to see relevant case studies & testimonials)

<img width="479" alt="screen shot 2017-05-17 at 2 39 05 pm" src="https://cloud.githubusercontent.com/assets/23459465/26177509/bc8f0c16-3b0e-11e7-8a2a-135fa04b72c0.png">

         

                          
#### 1.3 CTA (Call to Action)

<img width="469" alt="screen shot 2017-05-17 at 2 51 13 pm" src="https://cloud.githubusercontent.com/assets/23459465/26177884/6d87a3d8-3b10-11e7-85e2-a7547ca9c0f7.png">

                                       

#### BBOXX (Mock example)

  
  
![image18](https://cloud.githubusercontent.com/assets/23459465/26178120/7c9c75f0-3b11-11e7-8901-aa41afcea8a1.png)

Synopsis:

BBOXX had an interesting problem to solve — how to become a data-driven company by continuously monitoring their geographically dispersed 85,000 solar rooftop units (IoT monitoring) providing insights into customer-usage patterns and anomaly detection. They turned to Node.js, because “it was easy, scalable, modularized, open — it just worked!”

  

The Challenge:

The company grew on a fast trajectory; in just seven years it has 350 employees across five offices in China, UK, and East Africa, and has sold more than 85,000 BBOXX units running in more than 35 countries, providing 350,000 people with electricity. Becoming a data-driven business meant that their solution needed to have real-time data at its core which had another set of challenges. But, their outsourced system of apis were not scaling.
  
The Result:

The initial goal of becoming a data-driven business is a reality, due to their use of Node.js. They are now able to develop microservices and are applying lessons learned from analyzing past data to develop new and exciting products that exceed customer expectations. Although gathering data was not a core part of their business plan, the insight it has created is a core asset to the business.
  
Company Description:

BBOXX (pronounced “Bee Box”) develops and manufactures products to provide affordable, clean solar energy to off-grid communities in the developing world. The name is short for “Battery Box.” Their systems comprise of a solar panel connected to a battery and a set of USB and DC connectors to power lights, radios, and low powered televisions. The unit also includes a set of electronics to allow BBOXX to control it remotely.

### 3. Self Service Form

  
<img width="375" alt="screen shot 2017-05-17 at 3 02 20 pm" src="https://cloud.githubusercontent.com/assets/23459465/26178205/e19b4936-3b11-11e7-815c-efbdfd072559.png">

Tool Tip: What is the solution, what technology problem does it solve, describe the technical stack and solution architecture.

<img width="442" alt="screen shot 2017-05-17 at 3 09 21 pm" src="https://cloud.githubusercontent.com/assets/23459465/26178428/dd4de6bc-3b12-11e7-8a13-75ff8ef490e9.png">

  

Tool Tip: for Business benefit: Who are the end users, why would they use this product/project/solution? Do they save money, have productivity gains, improve time to market? Reduce complexity?....

<img width="396" alt="screen shot 2017-05-17 at 3 09 58 pm" src="https://cloud.githubusercontent.com/assets/23459465/26178444/ee810d06-3b12-11e7-86c2-3c609a9bcf91.png">
<img width="161" alt="screen shot 2017-05-17 at 3 10 44 pm" src="https://cloud.githubusercontent.com/assets/23459465/26178454/06773ce6-3b13-11e7-9cd8-a36aa5a41456.png">

  
  
  
  
  
  
  
  
  
  

### 4. Design and Resources Considerations:

  

1. Database - Where will the form data be stored. Ideally we save to a db, which can be queried. 
2. Data Aggregation - Marketing Team will need to aggregate the use case submissions to segment them horizontally (technology solutions) or vertically (industries) 
3. Refine Messaging - Work with the person submitting the testimonial / use case to refine the messaging and make it crisp. This would be an email follow up done by marketing team 
4. Publishing and Promotion - Web dev working with marketing team will create web pages, upload logos, publish the use case summary and details in a repeatable and agreed upon format.

**Comment by hackygolucky** [comment]
@serenam18 What's the deadline for input here? When would you be able to like to go back to the committee before work move forwards?

**Comment by mikeal** [comment]
Ideally, data storage would be simple, like in a Google Sheet posted from an embedded Google Form. That seems like the best way to ensure we can have proper access controls around it. 

Also note that whatever we do has to conform to the foundation's privacy policy https://github.com/nodejs/nodejs.org/blob/51bfa346fcdb5cc1a3dce2cfbaa2a8465408db17/locale/en/about/privacy.md

**Comment by serenam18** [comment]
Thanks @mikeal!

@hackygolucky looking to receive feedback by Thursday, 61.

**Comment by geek** [comment]
Looks like a great idea. @nodejs/website any thoughts on the resource considerations?
> 4. Publishing and Promotion - Web dev working with marketing team will create web pages, upload logos, publish the use case summary and details in a repeatable and agreed upon format.

**Comment by serenam18** [comment]
Does anyone have any other feedback? What is the best way to move forward? Thanks for your help!

**Comment by fayazg** [comment]
@mikeal using google forms will add the google branding.
@hackygolucky @serenam18 @geek 
Is there a standard/template for adding (google) forms?

**Comment by bnb** [comment]
With the new Foundation site in development, is it more appropriate to add this there? I think it'd probably be a better fit and would enable the Foundation team to get the data they needed faster. 

I just dug this issue up because of a comment by @dshaw on [Twitter](https://twitter.com/dshaw/status/910938318979850240) about how the Foundation membership form gets blocked by ad blockers - it seems like this form is within the same scope of a Foundation resource, and something that would be better managed on the Foundation end. 

Thoughts?

**Comment by gtewallace** [comment]
@bnb yup, totally agree! thanks. I think we can close this issue.
