### ISSUE TITLE
Better way to promote translations

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs.org#1235]
We should add a language switch/list of translations or something similar to the site to better promote the internationalization efforts. Also we need to discuss, if a translated home page alone qualifies as "site translation".

Tools like GitLocalize (discussed in https://github.com/nodejs/nodejs.org/issues/972#issuecomment-303208008) would really help.

**Comment by sotayamashita** [comment]
> We should add a language switch/list of translations or something similar to the site to better promote the internationalization efforts. 

@fhemberger I appreciate you creating an issue. I can help to implement these features. We provide GitLocalize for free and would like to help Node.js let developers know more. :smile:

cc:/ @bnb

**Comment by bnb** [comment]
Big +1 to GitLocalize from me - looks like a solid tool to really lower the barrier to participation in docs/site translation.

**Comment by kahwee** [comment]
Nice find. This looks fantastic.

**Comment by watilde** [comment]
Big +1 on this from me as well. It would be nice to keep having both of the workflows for a while to try the tool out quickly.

**Comment by sotayamashita** [comment]
We need to discuss it with a lot of people. 
cc:/ @nodejs/website @nodejs/localization

**Comment by Lellansin** [comment]
It's great. I think we need a plan (how about Github Project?), and I've prepared to PR for it.

**Comment by fhemberger** [comment]
Again, before using GitLocalize, we need to discuss access rights to the organization (same as with Snyk or Greenkeeper):

[Quoting](https://github.com/nodejs/nodejs.org/issues/1094#issuecomment-272292962) @mikeal:
> As a general rule we don't enable org wide access to external applications for security reasons. We have sensitive information in private repositories.

**Comment by Rukeith** [comment]
It's a great ideal. I would like to help to translate

**Comment by pierreneter** [comment]
You and me can do it with left and right panel in Sublime Text or whatever editor, granting a third party permission is a real risk. Why we need GitLocalize? Do not be lazy.

**Comment by sotayamashita** [comment]
@fhemberger 
Do we use Snyk or Greenkeeper now? If it does, how to solve the issue? 
<br/>

@pierreneter
> You and me can do it with left and right panel in Sublime Text or whatever editor, 

We are not only offering the split view. **Our focus is how to keep translated ones up-to-date when the original language is updated** and provide the following necessary features for it below:

- Link each sentence between original and translated ones so we let you know which is updated or not.
- Check it out our video how we work: https://youtu.be/b09LDukIJiU

> granting a third party permission is a real risk.

I would like to know the risk. You are talking about @fhemberger mentioned in [#issuecomment-303936003](https://github.com/nodejs/nodejs.org/issues/1235#issuecomment-303936003)

**Comment by laosb** [comment]
Agree with @sotayamashita, I've been doing translating with plain git & text editors, and it was a disaster.

**Comment by fhemberger** [comment]
@sotayamashita No, we don't use them because of the rights they require.

**Comment by pierreneter** [comment]
@sotayamashita 
![fireshot capture 33 - authorize application_ - https___github com_login_oauth_authorize](https://cloud.githubusercontent.com/assets/12815768/26480164/70afd85c-4202-11e7-8b84-49bb7486523f.png)
Here is why it's dangerous.

**Comment by sotayamashita** [comment]
@fhemberger I understood.

@pierreneter & @fhemberger 
We will consider the permission again. I would like to know what permission setting is great so if there are great apps, please tell me! I will look into it.

**Comment by sotayamashita** [comment]
We just get webhook from GitHub and create a pull request to GitHub. Does anyone have any idea of permission?

**Comment by sotayamashita** [comment]
Please join the conversation. @JustinBeckwith, @mikeal, @phillipj, @rvagg

thanks in advance. :bow:

**Comment by zlatanvasovic** [comment]
The current system is too inefficient. You can't keep up with the English version easily. I'd suggest dropping out the usage of raw translating (translate whole file into new file). How about making an array of phrases to be translated one by one?

**Comment by preco21** [comment]
This might not be proper solution because it requires additional sync server, but anyway what about trying out https://crowdin.com/ with https://github.com/thejameskyle/crowdin-sync solution?

**Comment by sotayamashita** [comment]
@zdroid It might be backup plan :+1:.

**Comment by sotayamashita** [comment]
@preco21 I have thought of crowdin but your translation will not be your commit in GitHub in crowdin.

**Comment by zeke** [comment]
> [crowdin] requires additional sync server

Not any more.

Crowdin actually has a GitHub integration built in now, so a standalone server is not required.  They can connect to your repo, sync content, generate pull requests, etc. I believe @thejameskyle created `crowdin-sync` before Crowdin supported GitHub syncing. See https://github.com/github/opensource.guide/pull/295#issuecomment-281568350

The Electron project is embarking on a localization effort, and we are using Crowdin. See https://github.com/electron/electron-i18n for details.

**Comment by sotayamashita** [comment]
@zake 

It seems that Crowdin is getting better and [`electron/electron-i18n`](https://github.com/electron/electron-i18n) is the very great project :smile: We will use it as a reference to help Open Source Translation.  By the way, I can help the project if you need a translator for Japanese :jp:.

**Comment by sotayamashita** [comment]
@fhemberger 

We are implementing the new way to get appropriate permission. 
We will share it soon :smile:

**Comment by fhemberger** [comment]
Okay, this issue went waaaaaaay of track from my original intention. :wink: 

> We should add a language switch/list of translations or something similar to the site to better promote the internationalization efforts.

Can we please move translation workflow related discussions to #972?

**Comment by fhemberger** [comment]
Oh, noticed we already had a discussion about a language switching mechanism in #806, closing this for now.
