### ISSUE TITLE
How to Node Website security certificate outdated

### ISSUE THREAD

**Issue by mkoshy** [nodejs/nodejs.org#1243]
https://howtonode.org/  URL has a outdated security certificate and we cannot get to the website.

**Comment by fhemberger** [comment]
This is an external website and not maintained by the Node.js website team.

/cc @creationix

**Comment by creationix** [comment]
I think something is wrong with my monthly cronjob.  I'm running it manually to see if it updates.

**Comment by creationix** [comment]
Ok, fixed it!  Sorry for the trouble.

**Comment by mkoshy** [comment]
Thanks ...the issue surfaced today again.

**Comment by mkoshy** [comment]
The error is  "
502 Bad Gateway

nginx/1.11.3"

**Comment by mkoshy** [comment]
The issue on the 502 error was fixed yesterday but back today ...any chance of a permanent fix as its a great website to learn from. Thanks in advance Mathew
