### ISSUE TITLE
Node.js 8 version listed with a `v` in Downloads

### ISSUE THREAD

**Issue by julianduque** [nodejs/nodejs.org#1246]
![](https://cldup.com/MBp1f60yui.png)

**Comment by lpinca** [comment]
Hmm what's wrong?

```
$ node -v
v8.0.0
```

**Comment by vsemozhetbyt** [comment]
I think maybe [this](https://nodejs.org/en/blog/release/v8.0.0/#long-term-support) is implied:

> Note that, when referring to Node.js release versions, we have dropped the "v" in Node.js 8. Previous versions were commonly referred to as v0.10, v0.12, v4, v6, etc. In order to avoid confusion with V8, the underlying JavaScript engine, we've dropped the "v" and call it Node.js 8.

**Comment by gibfahn** [comment]
So these all match the output of `node -p process.versions` (except `npm`, which matches `npm -v`). I don't think there's a downside to removing the `v` from this table.



```bash
➜  ~ ❯ node -p process.versions                                                                    ~
{ http_parser: '2.7.0',
  node: '9.0.0-pre',
  v8: '5.8.283.41',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '55',
  openssl: '1.0.2k',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
➜  ~ ❯ node -v                                                                                     ~
v9.0.0-pre
```
