### ISSUE TITLE
Update "Installing Node.js via package manager" to Node.js 8

### ISSUE THREAD

**Issue by bnb** [nodejs/nodejs.org#1247]
* **URL**: https://nodejs.org/en/download/package-manager/

Just took a look at the Installing Node.js via package manager guide, and noticed that it still suggests [Node.js 7](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) for Debian/Ubuntu.

Would it be possible to update these? 🤔

**Comment by vsemozhetbyt** [comment]
A try to update : https://github.com/nodejs/nodejs.org/pull/1248
