### ISSUE TITLE
Feature Request: nodejs.org/sponsors

### ISSUE THREAD

**Issue by gibfahn** [nodejs/nodejs.org#1257]
* **URL**: https://nodejs.org/en/sponsors (proposed)

@nodejs/build are looking for ways we could improve what we offer sponsors (see https://github.com/nodejs/build/issues/741).

One suggestion was that we have a page similar to https://adoptopenjdk.net/sponsors.html, where we can prominently display a list of our sponsors.

The list is currently in [the Build WG README](https://github.com/nodejs/build#infrastructure-providers), we'd have to work out where the list would go (and ideally not have two lists that can get out of sync).

I'd be interested to know what @nodejs/website think of the idea!

**Comment by lpinca** [comment]
I like the idea. We can add a page (not sure where) similar to https://nodejs.org/en/foundation/members/ where we add the logos and maybe a small description of our sponsors.

**Comment by bnb** [comment]
One thing that will be helpful for streamlining this is ensuring that we define logo parameters to give to the companies so we can make this pretty consistent. Most conferences do this to make it easier on their end, and the companies are usually happy to oblige (and even often ask for these requirements). 

Would be great if we were able to define what we are looking for while designing our implementation of this.

**Comment by gibfahn** [comment]
>One thing that will be helpful for streamlining this is ensuring that we define logo parameters to give to the companies so we can make this pretty consistent. 

Good point, as I understand it we also need to make sure we get permission from the donors to use their logos at all, so we could do both at the same time.

**Comment by mhdawson** [comment]
@bnb sounds good to me.

**Comment by ovflowd** [comment]
We discussed the redesign initiative to not add sponsors for now, as it is tricky and requires intervention from the Foundation and permission from the sponsors.

Closing this Issue.
