### ISSUE TITLE
Add support for PubSubHubbub

### ISSUE THREAD

**Issue by SimenB** [nodejs/nodejs.org#1263]
* **URL**: E.g. https://nodejs.org/en/feed/blog.xml
* **Browser version**: N/A
* **Operating system**: N/A

PubSubHubbub allows close to live notifications on new entries in a feed. The transitive [`node-rss`](https://github.com/dylang/node-rss) from [`metalsmith-feed`](https://github.com/hurrymaplelad/metalsmith-feed) already supports a `hub` option.
I have never used PubSubHubbub before, so I don't know how involved it is other than just connecting to a Hub, such as https://pubsubhubbub.appspot.com/

https://en.wikipedia.org/wiki/PubSubHubbub

**Comment by fhemberger** [comment]
Hmm, if there's no real demand for adding this feature, I'm reluctant to do so just for the sake of adding it. You said yourself you never used PubSubHubbub before and I personally never heard of anybody consuming their feeds via PubSubHubbub (many people don't even use RSS any more). But please, prove me wrong!

Opinions @nodejs/website?

**Comment by SimenB** [comment]
I meant I've never implemented it, I have consumed feeds which uses it though (from Medium) 🙂

**Comment by fhemberger** [comment]
Seems there is no interest in adding this feature, so I'm closing this issue for now.
However, this might change in the future, so feel free to reopen this issue then.
