### ISSUE TITLE
official website background image repeat in big size device

### ISSUE THREAD

**Issue by jsspace** [nodejs/nodejs.org#1273]
[official  website](https://nodejs.org/en/), background image repeat  in big size device

**Comment by pierreneter** [comment]
I find it okay, if you have problem with this, can you describe clearly for me? If the it's logical, please give a solution that you find it okay to solve that problem. Many thanks

**Comment by jsspace** [comment]
May be I am wrong

**Comment by pierreneter** [comment]
Wait, let's see our site at 5000px width
![screen shot 2017-06-23 at 10 54 55 am](https://user-images.githubusercontent.com/12815768/27466126-8ed5e040-5802-11e7-8b6f-65ce6b1a8f7f.png)
And i will set background no-repeat with position is center, below
![screen shot 2017-06-23 at 10 58 48 am](https://user-images.githubusercontent.com/12815768/27466184-f5966228-5802-11e7-84fb-3a8b7bc62136.png)
I find it nice. Okie I will set it. Hope everyone agrees

**Comment by jsspace** [comment]
yean, that is what I mean

**Comment by fhemberger** [comment]
@pierreneter Ok, you'll be our test candidate for responsive design issues from now on. :smiley:

**Comment by pierreneter** [comment]
@fhemberger thank you.

**Comment by lpinca** [comment]
@pierreneter all changes must be approved and reviewed, so next time, please open a PR instead of pushing directly to master.

Thanks.

**Comment by pierreneter** [comment]
It's my mistake. I forget that I can edit directly. Thank you. I will do it next time.
