### ISSUE TITLE
Package Manager Install instructions

### ISSUE THREAD

**Issue by gitlcr2131** [nodejs/nodejs.org#1299]
* **URL**: https://nodejs.org/en/download/package-manager/
* **Browser version**: Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)
* **Operating system**: Windows 10 Home

CentOS Command reads: curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -

Command should read: curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -

You need root to access the rpm directory.  It is indicated for package install, however its also necessary to download.

**Comment by pierreneter** [comment]
exactly.

**Comment by pierreneter** [comment]
But it have `Run as root on RHEL, CentOS or Fedora, for Node.js v6 LTS:` above. My PR is needed or not?
