### ISSUE TITLE
Request: Sponsorship on Docs Page

### ISSUE THREAD

**Issue by sayzlim** [nodejs/nodejs.org#1304]
**URL: https://nodejs.org/api/**

I sent an invitation to Mikael to join [Carbon](http://carbonads.net/), and he told me it’s best to seek everyone feedbacks here.

I manage Carbon and want to suggest displaying Carbon on the docs page at https://nodejs.org/api/. You can check out the demo I came up with at https://s.codepen.io/carbonads/debug/xrmGJr

The main idea is to generate a consistent revenue from sponsorship for the foundation without cluttering the docs. We’ve worked with few projects to display sponsors on their docs page: **[lodash.com/docs/](https://lodash.com/docs/4.17.4), [flask.pocoo.org/docs/](http://flask.pocoo.org/docs/0.12/), and [laravel.com/docs/](https://laravel.com/docs/5.4)**

Carbon partners receive 60% of the earning. It’s about $1.10–$1.60 nett per 1,000 pageviews/impressions. So, a site with 5 million monthly pageviews can make $5500–$8800. Given the popularity and quality of Node.js project, **it should make more than $7500 per month**.

I know there are many things we have to consider, so it would be great to learn whether Carbon can help Node.js to reach the funding goal.

**Comment by evanlucas** [comment]
We currently store and build the api docs in the core repo (https://github.com/nodejs/node). Maybe this should be opened there?

**Comment by sayzlim** [comment]
Evan, is it okay for me to open another similar request there, or should I just point the issue back to this page? I would like to avoid opening issues on other repo unless necessary.

**Comment by evanlucas** [comment]
@sayzlim I would move this one to nodejs/node. I would like to hear what the collaborators think

**Comment by tniessen** [comment]
I don't think nodejs/node is the correct repository to discuss this. Implementation can still happen in nodejs/node (*if* the foundation decides to implement it), but I don't think a discussion about putting advertisements into our docs belongs there. This might be a topic for discussion by @nodejs/ctc or TSC.

**Comment by sayzlim** [comment]
@evanlucas got it. I’ll close this issue here.
