### ISSUE TITLE
Add new contributors (July 2017)

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs.org#1317]
It's been a long time since we last added new contributors to the project.

It's a bit of manual labor, since I use a customized script to determine all new committers since a given date which are not already project contributors. Then we need someone with admin rights on GitHub to add those people to the website team. This has been done by @mikeal in the past, we need to find someone who is willing to take over …

**Comment by phillipj** [comment]
Finding new contributors could possibly be done by adding functionality to the https://github.com/nodejs/github-bot if someone feels for a challenge.

As for adding people into the nodejs organisation, there has been a somewhat controversial discussion using a bot for that as well. Maybe @williamkapke has some updates around that, as he has given that a shot more than once..

**Comment by sotayamashita** [comment]
@fhemberger Will you write code for nodejs-github-bot to add collaborators?

**Comment by williamkapke** [comment]
The latest discussion on using a bot to do it was here: https://github.com/nodejs/community-committee/issues/22

Any member of the CTC or TSC is empowered to add people you ask them to. In fact, that is one of their specific duties. It would be good to have some of those folks getting familiar with doing it.
So- as soon as ya'll decide who is a new collaborator- just ping those groups and ask for someone to volunteer to invite them to the org and add them to the `Website` and `Members` team. (it's pretty easy)

Of course- ping me again if you don't get a volunteer in a reasonable time and I'll escalate it
<sup>(I really doubt that'll be needed- I'm just making sure you know you'll never be stuck on this!)</sup>

**Comment by bnoordhuis** [comment]
I can add people.  How many are we talking?

**Comment by fhemberger** [comment]
@williamkapke Great, thank you!
@bnoordhuis Still working on that, I'll let you know.

@sotayamashita I'm currently quite busy with a client project, so it still may take some time.

**Comment by refack** [comment]
@fhemberger if you can point me to when the last onboarding happened, I think I can compile a list of new contributors since then.

**Comment by fhemberger** [comment]
@refack Last onboarding was here: https://github.com/nodejs/nodejs.org/issues/1140

**Comment by fhemberger** [comment]
@bnoordhuis Here's the list of new committers since February:

```
262 commits in `nodejs/nodejs.org` since 2017-02-13:
* @refack 4 commits
* @kasicka 3 commits
* @Mohamed3on 2 commits
* @sudowork 2 commits
* @ivandotv 2 commits
* @arkwright 2 commits
* @clakech 2 commits
* @matteocontrini 2 commits
* @eckerdj7 2 commits
* @rm-rf-etc 2 commits
* @mlosh 2 commits
* @daxlab 2 commits
* @tniessen 2 commits
* @ovo4096 2 commits
* @LinusU 2 commits
* @knpwrs 2 commits
* @aruneshchandra 2 commits
* @franher 2 commits
* @jseijas 2 commits
* @motet-a 2 commits
* @danbev 2 commits
* @thescientist13 2 commits
* @romanshoryn 2 commits
* @jessicaquynh 1 commits
* @chris--young 1 commits
* @alex-blair 1 commits
* @june07 1 commits
* @ysdanielkim 1 commits
```

**Comment by fhemberger** [comment]
@bnoordhuis @Fishrock123 @bnb Can someone please add the new contributors to the website team?

**Comment by gibfahn** [comment]
@fhemberger FWIW it looks like you're a maintainer (assuming we're talking about [nodejs/website](https://github.com/orgs/nodejs/teams/website/members)) so you should be able to add anyone who's already in the org to the team.

I think you still need an [owner](https://github.com/orgs/nodejs/people?utf8=%E2%9C%93&query=%20role%3Aowner) to add new people to the org.

**Comment by fhemberger** [comment]
@gibfahn I know, that's why we need an org owner to add new folks.

**Comment by bnb** [comment]
I don't think I can add folks to the org, unfortunately 😬

**Comment by fhemberger** [comment]
Ok, let's ask one of the org's owners for help.
/cc @cjihrig @evanlucas @fhinkel @Fishrock123 @mcollina @MylesBorins

**Comment by Fishrock123** [comment]
You want me to add that full list?

**Comment by Fishrock123** [comment]
Ok, done. All invites sent / added to the website team.

**Comment by fhemberger** [comment]
@Fishrock123 Great, thank you!
