### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#1318]
* **URL**:https://nodejs.org/fr/docs/
* **Browser version**: Version 59.0.3071.109 (Developer Build) Chronium
* **Operating system**: elementary

This issue applies to locale, for example, going to https://nodejs.org/fr/, selecting 'Downloads', 'Foundation', 'Docs' etc.. would return error 404 instead of redirecting to /en locale. Example (https://nodejs.org/fr/docs/). I can see this is applied to /about, and I think it should be applied on the rest of the routes.

**Comment by sotayamashita** [comment]
@jevtovich I tried it on my local and it works. I look into it

- ~~ref: https://github.com/nodejs/nodejs.org/blob/master/server.js#L41-L58~~

**Comment by sotayamashita** [comment]
@fhemberger Does master branch deployed into node.js org?

**Comment by lpinca** [comment]
@sotayamashita yes.

**Comment by lpinca** [comment]
See https://github.com/nodejs/build/pull/816

**Comment by sotayamashita** [comment]
@lpinca Thanks a lot

**Comment by ghost** [comment]
Needs to be applied on ca, gl as well
