### ISSUE TITLE
Guide article - slash instead of dot

### ISSUE THREAD

**Issue by Damaged-Organic** [nodejs/nodejs.org#1319]
* **URL**: https://nodejs.org/en/docs/guides/getting-started-guide/#how-do-i-start-with-node-js-after-i-installed-it
* **Browser version**: Chrome 58.0.3029.110 (64-bit)
* **Operating system**: Ubuntu 16.04

There is a slash character instead of dot.

>Once you have installed Node, let's try building our first web server\ Create a file named "app.js", and >paste the following code:

**Comment by fhemberger** [comment]
Thanks, fixed it.
