### ISSUE TITLE
wrong node school location on events

### ISSUE THREAD

**Issue by mrfarhadir** [nodejs/nodejs.org#1323]
* **https://nodejs.org/en/get-involved/events/**:
* **Chromium 59.0.3071.86 **:
* **LinuxMint 18.1 (64-bit)**:

Hello , 
I'm from Tabriz and I want to state a problem.
At mentioned address (events) , node school in Asia-Iran-Tabriz is wrong and there is no any node school at that place also the web page (http://nodeschools.ir/) is not a web site ! 
it should be removed.
Also there is one question  , How I can add our node school and node conference to the events map in Tabriz city
my node school url : http://learnodejs.ir
Thanks

**Comment by lpinca** [comment]
Hi, we are not sure what to do with the events page.

See https://github.com/nodejs/nodejs.org/issues/1031 and https://github.com/nodejs/nodejs.org/pull/1314.

**Comment by lpinca** [comment]
Closed as the event has been removed for now.
