### ISSUE TITLE
Automating Announcement Section

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs.org#1327]
Hello - The Node.js Foundation is now issuing all of its announcements on Medium. Given this, I thought we should update our announcement section to be more like the "In the News" section. Essentially, I just put the title and link into a google document and the "In the News" section is automatically updated.

Is this group okay with this and if so, would anyone know how to do this? I'm sure it's fairly simple, I just don't know how to go about and create it.

**Comment by pierreneter** [comment]
In layout:
https://github.com/nodejs/nodejs.org/blob/master/layouts/in-the-news.hbs
We get data from https://docs.google.com/spreadsheets/d/1jSxgB5MYd1xCOmhb5QZ90PbDiY57n4z4A0lcdQD-UG8/pubhtml
The need to do is add you to this doc, but i don't have access permissions.
Maybe someone can do it.

/cc @nodejs/website

**Comment by ZibbyKeaton** [comment]
@pierreneter yes, I have access to this google document. I would like to create a similar document for the "announcement" section of the website, so I can easily upload announcements when we post them on Medium. Hope that makes more sense.

**Comment by pierreneter** [comment]
Sorry for my misunderstanding. You can create a doc have a format like doc of "In the News" section and `publish to the web`, after share me this publish link. I will edit layout of "announcement" section for you.

**Comment by pierreneter** [comment]
Sorry for my misunderstanding. You can create a doc has a format like doc of "In the News" section and publish to the web, after share me this publish link. I will edit layout of "announcement" section for you.

**Comment by pierreneter** [comment]
Or I can create a doc for you and you just add content to it. Give me your address email.

**Comment by pierreneter** [comment]
Or I can create a doc for you and you just need add content to it. Give me your address email.

**Comment by ZibbyKeaton** [comment]
@pierreneter that works for me. Please feel free to use zkeaton@linuxfoundation.org
