### ISSUE TITLE
stability index wrapping

### ISSUE THREAD

**Issue by Trott** [nodejs/nodejs.org#1337]
* **URL**: https://nodejs.org/dist/latest-v8.x/docs/api/documentation.html
* **Browser version**: Chrome 60.0.3112.90 (Official Build) (64-bit)
* **Operating system**: macOS 10.12.6

The stability index text banners do not wrap, requiring lots of scrolling right to read the text.

**Comment by saadq** [comment]
It looks like the styles for the docs and the api stability stuff was in the main `node` repo, so I opened a [PR](https://github.com/nodejs/node/pull/14809) that should fix this over there. Is that alright?
