### ISSUE TITLE
Problem with Building a Docker Image

### ISSUE THREAD

**Issue by RichardHill** [nodejs/nodejs.org#1342]
* **https://nodejs.org/en/docs/guides/nodejs-docker-webapp/**:
* **CHROME - Version 59.0.3071.115 (Official Build) (64-bit)**:
* **MAC OS Sierra system**:

I am using Docker version 17.06.0-ce, build 02c1d87 

I've been following the tutorial documented on the page and there seems to be an issue with one step.

Scroll to the section where it says -: Building your image

And note that you say to run the command -:

>  docker build -t <your username>/node-web-app .

This did not work for me. Upon reading the Docker documentation the format for the -t flag would seem to have changed to -: 

> -t, --tag list                   Name and optionally a tag in the 'name:tag' format

Changing my command line to -:

>  docker build -t your username:node-web-app .

Worked fine.

**Comment by fhemberger** [comment]
Hi Richard,

it's because you left out the "username" part: `docker build -t <your username>/node-web-app .`
If you wish to omit it, you need to remove the slash separator as well.  
For example `docker build -t RichardHill/node-web-app .` would have been totally fine. Adding a user name prefix can help distinguish your own Docker images from official ones.

We should make this more clear in the tutorial, thanks for pointing this out!

**Comment by RichardHill** [comment]
Hello FHemberger and thank you for taking the time to review the issue I found. 

I took a look at my original post and to my horror I found that it looked as if I had not posted correctly. However it was my mistake in not understanding that if I use '<' content '>' - it is not rendered out. So you could not see that I had actually created the post correctly but the site was not rendering it as I expect. 

Lesson Learned.

I have no updated the original post now so that it is formatted to be able to see my issue. 

The issue still stands. The documentation says to use a '/' but Docker now says you should split the user name with a ' : '. 

Is it possible to update the document to reflect this?

**Comment by fhemberger** [comment]
The slash is correct, you use a colon to separate the image name from a(n optional) version (e. g. `fhemberger/myapp:1.0.0`). 

Valid Docker image tags (examples):
- `appname`
- `appname:latest`
- `appname:v1.0-beta`
- `nodejs:lts`
- `username/appname`
- `username/appname:version`
-…

**Comment by RichardHill** [comment]
Hi Fhemberger - I took another look and you are right. I do apologise. If you use that approach it just adds 'latest' as the tag.

Incredibly minor but it might be worth adding that the user should include the period '.' in the command.
