### ISSUE TITLE
Error in guide to dockerizing nodejs

### ISSUE THREAD

**Issue by rm-rf-etc** [nodejs/nodejs.org#1344]
* **URL**: https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

The following instruction, given by the above tutorial, causes a build to fail.
`COPY package.json package-lock.json .`

The error message reads:
```
Step 3/7 : COPY ./package.json ./package-lock.json .
When using COPY with more than one source file, the destination must be a directory and end with a /
```

**Comment by pierreneter** [comment]
I think it should be `COPY package.json package-lock.json ./`. can you submit a PR to fix this tutorial?

**Comment by rm-rf-etc** [comment]
Created pull/1346. Sorry if I missed any aspects of standard protocol.

**Comment by pierreneter** [comment]
Thanks!
