### ISSUE TITLE
foundation.nodejs.org for Node.js Foundation website page

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/nodejs.org#1349]
My colleague from the Node.js Foundation internal team, Greg Wallace @gtewallace , has been chatting with me about the Foundation content on the web for quite some time. It seems as though now is a good time to place the Foundation section of www.nodejs.org on a WordPress CMS and under the day-to-day management of the Linux Foundation staff.

The rationale is:

Linux Foundation marketing and communications staff initiate the bulk of the content changes to this section, with help of the web WG with PRs and content review. With some new pages planned (such as an application showcase) that will increase the web content management workload, we feel a move to a CMS with which the LF staff are familiar and makes sense.
Over the past several months, the Linux Foundation marketing and communications team and the Node community have established a strong working relationship to ensure that the right content gets promoted via the right channels. I am confident that this would extend to this new web site arrangement. 
Timing this change to coincide with the planned redesign of nodejs.org also seems to make sense

Our suggestion for path forward is for the Linux Foundation to stand up a simple WP site (see www.jsfoundation.org or www.cncf.io or www.openmainframeproject.org for a few examples). Once in place, the Node Foundation staff will apply CSS and copy the content over from the current Foundation section of nodejs.org. 

We would then ask the Website WG to implement a simple redirect to the new Node.js Foundation site from https://nodejs.org/en/foundation/ to foundation.nodejs.org This will prevent the Website WG from having to maintain and admin a CMS.

We're eager to hear the community’s thoughts on this idea.

**Comment by gibfahn** [comment]
Sounds reasonable, I like the idea of keeping it separate and just having a redirect.

**Comment by refack** [comment]
I think it's a bad idea to run the Foundation's website off WP.
I don't know what the current status of [Ghost](https://github.com/TryGhost/Ghost), but if push comes to shove, I'd rather we maintain a basic CMS ourselves then use WP.

**Comment by gtewallace** [comment]
hi @refack 

Want to be sure it's clear that we're only talking about the Foundation section of the current nodejs.org  (images here for illustration)

All the rest would stay either on github as it is today or whatever else the Web WG decides, such as maybe Ghost, which I know has been talked about previously.

Does that alleviate your concern any?
![nf1](https://user-images.githubusercontent.com/12159820/29939904-864367e2-8e5b-11e7-909a-f23c39d8d67d.PNG)
![nf2](https://user-images.githubusercontent.com/12159820/29939915-8c49cdd4-8e5b-11e7-80a7-f1c61932dd74.PNG)

**Comment by refack** [comment]
Still IMHO it's a bad statement that we serve any of our content off PHP. "dogfooding" should be higher on our priority list
I did a quick sanity test on Ghost, and it seems like a viable node.js based alternative. Also probably if we reach out to them they'll be willing to donate the hosting.

Just two tabs to the left we are making the following statements 😄 
![image](https://user-images.githubusercontent.com/96947/29940493-70f29ef6-8e5d-11e7-8654-9e1b3eda596a.png)

**Comment by refack** [comment]
I also forgot about GoDaddy, maybe they have a node.js based hosted CMS?

**Comment by gibfahn** [comment]
>"dogfooding" should be higher on our priority list
>I think it's a bad idea to run the Foundation's website off WP.

I agree in general, and it would be great if we could get the foundation to use node for this part of the website, but on the other hand if the team there are already familiar with Wordpress, and they're already using it on a bunch of other sites, then consistency is probably a priority for them. Given that the proposal is for them to manage the website separately, and just have a link to their site from nodejs.org, I'd be fine with it.

I get the thinking behind using a Node based solution if possible, might be worth looking at Ghost (@hackygolucky ).

**Comment by refack** [comment]
Consider my objection non blocking (I'm also not a Website WG member).

For further consideration neither PHP nor WordPress are members of the Linux Foundation, so they might consider migrating too (just saying 😉).

**Comment by fhemberger** [comment]
+1 for extracting all foundation content to a different platform, if it makes it easier for Foundation staff to contribute. That's the whole point. Not everybody feels comfortable wrangling with Git/GitHub for simple content updates.

I also think Ghost would be a great choice, they'd be thrilled to have the very organization creating the platform their software runs on amongst their users. There could be nice synergy effects for both sides. However, as the Website WG won't be responsible for that part of the website any longer, it shouldn't be our decision. Choose whatever suits you best.

**Comment by gtewallace** [comment]
Hi everyone,

We have the foundation site up and running - https://foundation.nodejs.org/
Wanted to see if we could arrange for someone to implement the server-side redirect to the above from https://nodejs.org/en/foundation/
Thanks in advance and please let me know any questions.

Greg

**Comment by fhemberger** [comment]
Hey @gtewallace, I had a look and we're still missing a few pages for the redirects:

```
/en/foundation                 https://foundation.nodejs.org/
/en/foundation/case-studies    https://foundation.nodejs.org/resources
/en/foundation/members         https://foundation.nodejs.org/about/members
/en/foundation/board
/en/foundation/tsc             https://github.com/nodejs/TSC
/en/foundation/certification
/en/foundation/in-the-news     https://foundation.nodejs.org/news/in-the-news
/en/foundation/announcements   https://foundation.nodejs.org/news/announcements
/en/foundation/education
```

Redirects can be configured in @nodejs/build, once we have all new targets:
https://github.com/nodejs/build/blob/master/setup/www/resources/config/nodejs.org

**Comment by gtewallace** [comment]
@fhemberger 
thanks!
/en/foundation/board --> https://foundation.nodejs.org/about/leadership
/en/foundation/certification --> this page is still under construction @hackygolucky might have an eta on it
/en/foundation/education --> @hackygolucky do you want to keep this page on the new foundation site or replace with the cert page?

**Comment by gtewallace** [comment]
@refack @fhemberger 

we are all set. 

both 
/en/foundation/certification 
and 
/en/foundation/education should redirect to https://foundation.nodejs.org/resources/certification

thanks again for all the help!

**Comment by fhemberger** [comment]
@gtewallace Here's the PR for the redirects: https://github.com/nodejs/build/pull/1005

**Comment by fhemberger** [comment]
Waiting for https://github.com/nodejs/build/pull/1009 to land.

**Comment by mhdawson** [comment]
My only comment is it would be nice if it did not look like a completely different website.  At the very least I think there should be some link back to the main website.  'Home' just takes you back to the foundation home as opposed to the main node site.

**Comment by fhemberger** [comment]
For the same reason, we should move the Foundation link in the main navigation.

**Comment by fhemberger** [comment]
FYI: All redirects are in place, we can now remove the Foundation pages from nodejs.org

**Comment by fhemberger** [comment]
@hackygolucky Found a dead link on the Foundation page:

https://foundation.nodejs.org/about/leadership: "Meeting Minutes" links to `https://nodejs.org/en/foundation/tsc/minutes/`, should be `https://github.com/nodejs/TSC/tree/master/meetings`

**Comment by fhemberger** [comment]
Please have a look at #1492
