### ISSUE TITLE
Restructure GitHub labels

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs.org#1356]
At the moment, we have 43 labels for issues, most of them have never been used. I'd like to cut down the number and restructure them.

This is a first idea:

| Current labels  | New proposal |
| ------------- | ------------- |
| accessibility | |
| ~~blog~~ |  |
| bug | |
| content | |
| | content/downloads |
| | content/foundation |
| ~~cross-browser~~ | |
| ~~deprecate~~ | |
| ~~deps~~ | |
| design | |
| ~~diag-agenda~~ |  |
| discuss | |
| do not merge | wait |
| merge conflict | wait/merge conflict |
| needs feedback from original poster | wait/original poster |
| needs i18n +1 | wait/i18n +1 |
| needs tests | wait/tests |
| needs WG +1 | wait/wg +1 |
| duplicate | |
| ~~easy-fix~~ |  |
| enhancement | |
| ~~evangelism~~ | |
| external issue | external |
| build | external/build |
| docs | external/docs |
| ~~faq~~ | |
| ~~future~~ | |
| good first contribution | |
| help wanted | |
| i18n | |
| ideas | see 'enhancement' |
| ~~invalid~~  | |
| ~~investigate~~ | |
| ~~irc~~ | |
| ~~low priority~~ | |
| ~~meeting~~ | |
| ~~pending~~ | |
| pr | |
| question | |
| ~~release~~ | | 
| ~~rush~~ | | 
| templating | | 
| ~~tests~~ | | 
| ~~WG Agenda~~ | | 
| ~~wontfix~~ | | 

- I added `content/downloads` and `content/foundation` as we often have issues/PRs belonging to those categories (with the foundation planning to setup their own website, the last one will become redundant in the future).
- To make it clearer, that build and doc related questions are not part of this repo, I renamed them `external/build` and `external/docs`.
- I don't think we need `invalid` and `wontfix`: It doesn't sound very friendly to have an issue rubber-stamped with that label, instead they can be closed with a comment.

This would cut down 19 labels, while only introducing two new ones.

Thoughts?

**Comment by refack** [comment]
> I don't think we need invalid and wontfix: It doesn't sound very friendly to have an issue rubber-stamped with that label, instead they can be closed with a comment.

There was a discussion about this in core https://github.com/nodejs/CTC/issues/102. There `invalid` was kept mostly for statistics about really weird stuff [(see top 3)](https://github.com/nodejs/node/issues?q=is%3Aissue+label%3Ainvalid+is%3Aclosed)

**Comment by fhemberger** [comment]
Oka, as there were no further objections, I changed/deleted the labels. If you feel there's something missing we should add, please feel free to do so.
