### ISSUE TITLE
Some links to anchors in Spanish doc fails.

### ISSUE THREAD

**Issue by riderSide** [nodejs/nodejs.org#1374]
* **URL**: https://nodejs.org/es/download/package-manager/
* **Browser version**: Chrome 61.0.3163.91
* **Operating system**: Windows 10 x64

Some Links to anchors from the main menu are not working.
Example: 
Item two points to "#debian-and-ubuntu-based-linux-distributions" but it should point to "#distribuciones-de-linux-basadas-en-debian-y-ubuntu"

**Comment by lpinca** [comment]
It seems that some links have not been updated when this [file](https://github.com/nodejs/nodejs.org/blob/master/locale/es/download/package-manager.md) has been translated.

Would you mind opening a PR to fix the issue?

Thank you.
