### ISSUE TITLE
Working group meeting to discuss the future of the website

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/nodejs.org#1375]
I think it would be a good idea for the working group to have a meeting, potentially prior to interactive, to discuss future direction of the website and what resources / support the group would like.

We could also do a session during the collaborator summit and video in people not attending in person

Thoughts?

**Comment by bnb** [comment]
@MylesBorins We've been trying to work on this for some time - check out: https://github.com/nodejs/nodejs.org/issues/1338

We finally pinned down a meeting with the parties involved, but only @hackygolucky and I showed up 😢 

This is _definitely_ a huge deal, and we're finally moving past some of the blockers that have really prevented this from happening for well over a year at this point. This is a pretty big deal, and something that's desperately needed.

Having a meeting would be stellar, as we really need to nail down a plan of action where there are achievable steps.

**Comment by hackygolucky** [comment]
For how much work this is going to be, I think having a session where people can remote in at Collaborator Summit would be amazing. There's a lot of stakeholders here(various working groups and committees, Node.js Foundation team such as PR and Comms) that would probably love to provide input on how we can better address our ecosystem of needs. Is there someone who is especially stellar in project management and user experience who could lead the charge on this?

**Comment by bnb** [comment]
Unfortunately we weren't able to have such a session at the Collaborator's Summit, purely in the interest of time and the other issues that were raised to be discussed. 

As such, we *do* need to have a discussion going forward. We need to gauge interested in participating at every level - design, implementation, and content. One of the discussions that I had at the Collaborator Summit landed on the idea that we **really** need to plan and manage this project.

As such, I'd like to suggest we go through a few phases:

* Information Structuring:
    * How does the site need to be structured?
    * What goes where, and how can we simplify the site as much as possible?
* Design:
    * Finding and on-boarding a designer (paid via request for funds to the board? Volunteer?)
    * Design phase
    * Feedback phase
    * Final deliverables
* Implementation phase
    * Information and design implementation

Additionally, I do think there's an additional step here that needs to happen throughout: gauging interest in contributors and consistent outreach. I've talked with MANY people who are interested in helping, and I think having a place to direct them to is a good way to start getting them involved- even if that's this issue as an initial platform 😄

**Comment by fhemberger** [comment]
Somewhat related: I'm looking for a contact for the Foundation website's code/design (maybe @ZibbyKeaton?). I've noticed some accessibility issues and it would be nice if both websites would at least use some similar overall design language (colors, fonts, grid, etc).

**Comment by gtewallace** [comment]
Hi @fhemberger 
please use me as your point of contact on the Foundation site.
full disclosure, I am not a web designer, so changes that cannot be accomplished through config changes to the WP theme we are using may need to wait until approx first half 2018 when we conduct a design refresh (this is not firmly committed, but has been discussed).

**Comment by fhemberger** [comment]
Closing, as we're working on it in [nodejs/website-redesign](https://github.com/nodejs/website-redesign/)
