### ISSUE TITLE
tiny typo in Timers in Node.js

### ISSUE THREAD

**Issue by Laassari** [nodejs/nodejs.org#1380]
typo in: https://nodejs.org/en/docs/guides/timers-in-node/#right-after-this-execution-setimmediate

setImmediate() returns **an** Immediate object, which can be used to cancel the scheduled immediate (see clearImmediate() below).

**Comment by Fishrock123** [comment]
Heya. You can edit this file on the nodejs.org repo: https://github.com/nodejs/nodejs.org/blob/master/locale/en/docs/guides/timers-in-node.md

**Comment by Fishrock123** [comment]
Please open an issue, or file a PR, on [that repo](https://github.com/nodejs/nodejs.org). :)

**Comment by fhemberger** [comment]
Thanks for reporting, I just did a quick fix in 8066cd1.
