### ISSUE TITLE
no ARMv6 download of Nodejs 8.x available, 404 link

### ISSUE THREAD

**Issue by jimmont** [nodejs/nodejs.org#1382]
* **https://nodejs.org/en/download/current/**:
* **ALL**:
* **ALL**:

see heading: "Linux Binaries (ARM)" with link "ARMv6" with href "https://nodejs.org/dist/v8.6.0/node-v8.6.0-linux-armv6l.tar.xz" which is a 404 error and browsing to "https://nodejs.org/dist/v8.6.0/" has no ARMv6 compatible download.

**Comment by refack** [comment]
@jimmont I think I found them https://github.com/nodejs/build/issues/897 for some reason they were named ARM7, and it's actually the ARM7 binaries that are missing.

/cc @nodejs/build @nodejs/release

**Comment by jimmont** [comment]
@refack unfortunately the ARM7 binary you mentioned from https://nodejs.org/dist/v8.6.0/node-v8.6.0-linux-armv7l.tar.xz segfaults on my ARM6 machine so I don't think it's an option.

**Comment by jimmont** [comment]
Reverting to Nodejs 8.4 per what appears to be the best option based on descriptions of the most recent 2 security issues (as of today).
https://nodejs.org/en/blog/vulnerability/september-2017-path-validation/
https://groups.google.com/forum/#!forum/nodejs-sec

**Comment by refack** [comment]
So it's not a simple misnaming, shame.
You might want to checkout nodesource's repository https://github.com/nodesource/distributions, they build binaries to various linux distributions and support ARM6 & ARM7

**Comment by jimmont** [comment]
Unfortunately Nodejs 8.x and 7.x are not supported for ARM6 on nodesource. Appreciate the tip @refack, might be time to retire the rpi I've been using.

**Comment by joaocgreis** [comment]
This happened because all of our ARMv6 infra is down. ARMv6 is still supported and the binary will probably be released as soon as we're able to get the machines back online (cc @rvagg).

The ARMv7 issue is a different one, ref https://github.com/nodejs/build/issues/829.

**Comment by mhdawson** [comment]
I guess I need to find time to get the backup Raspberry PI 1 (ARM v6) connected to the CI.  However, that won't like be until at least after Node Interactive.

**Comment by jimmont** [comment]
@mhdawson Michael is it possible to please update the page to reflect the status for these downloads accurately? If there's a change in support or outage (indicated above) it would be helpful to have that information on the website so that we can plan accordingly. Thank you.

**Comment by refack** [comment]
ping @jasnell who cut the release (No ARM6 and ARM7 are corrupt)

**Comment by johnwebbcole** [comment]
I appears that node source isn't an option for armv6l versions of v8.x

```
## Installing the NodeSource Node.js v8.x repo...


## You appear to be running on ARMv6 hardware. Unfortunately this is not currently supported by the NodeSource Linux distributions. Please use the 'linux-armv6l' binary tarballs available directly from nodejs.org for Node.js v4 and later.
```

Any word on the armv6 builds?

Thx!

**Comment by mhdawson** [comment]
The arm machine seems to be online but fails with this:

```
/home/iojs/build/ws/out/Release/.deps//home/iojs/build/ws/out/Release/obj.target/v8_base/deps/v8/src/ic/arm/handler-compiler-arm.o.d.raw   -c -o /home/iojs/build/ws/out/Release/obj.target/v8_base/deps/v8/src/ic/arm/handler-compiler-arm.o ../deps/v8/src/ic/arm/handler-compiler-arm.cc
FATAL: command execution failed
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:208)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFil
```

@rvagg is it possible that some cleanup is needed on the release machine ?

**Comment by bertlea** [comment]
Hi Guys, the same issue seems happening to v8.9.1 now.  No armv6l distribution in the download list.  the v8.9.0 still got it and also v9.2.0 got it too.

**Comment by mhdawson** [comment]
We do have issues with our arm6 builds in that they take a long time to compile due to the low machine resources and often timeout or have some other issue during the long run.

@gibfahn I've added a new arm6 only build that we can run to rebuild just the arm6 binaries in case of failure. If we run that for 8.9.1 with the right parameters is that enough or do we need additional steps to sign/validate the hashes ?

**Comment by gibfahn** [comment]
>If we run that for 8.9.1 with the right parameters is that enough or do we need additional steps to sign/validate the hashes ?

Steps are:

- Run the job with the correct parameters
- I run `tools/release.sh 8.9.1` to sign the shasums txt
- Run `rm locale/en/blog/release/v8.9.1.md && scripts/release-post.js 8.9.1` and submit a PR.

Only the second needs to be done by me.

**Comment by mhdawson** [comment]
@gibfahn what I'm trying to figure out would be the flow if we wanted to publish an arm binary after the fact to see if it is feasible.  We could start but running the arm6 only job with the same date/commit hash. 

We now have a binary and a new hash.  Would rerunning tools/release.sh do the right thing an result with a file that had the old hashes as well as the new one ?

**Comment by gibfahn** [comment]
>We now have a binary and a new hash. Would rerunning tools/release.sh do the right thing an result with a file that had the old hashes as well as the new one ?

Yes, I just ran `tools/release.sh -s v8.9.1` and it created a new hash.

You have to open a new PR against nodejs.org though, see https://github.com/nodejs/nodejs.org/pull/1489

**Comment by mhdawson** [comment]
We must be missing a step as https://nodejs.org/dist/v8.9.1/node-v8.9.1-linux-armv6l.tar.xz still shows as 404.  Maybe there is a step to push the binary into dist ?

**Comment by gibfahn** [comment]
```bash
▶▶▶ tools/release.sh                                                                                                                                                      ~/wrk/com/DANGER/node (master*)
# Selecting GPG key ...
You have multiple GPG keys:

/Users/gib/.gnupg/pubring.gpg
-----------------------------
sec   rsa4096 2016-10-07 [SC]
      77984A986EBC2AA786BC0F66B01FBB92821C587A
uid           [ultimate] Gibson Fahnestock <gibfahn@gmail.com>
ssb   rsa4096 2016-10-07 [E]

1) 821C587A
2) 2C482931
Select a key: 2

Using GPG key: 2C482931
  Fingerprint: 77984A986EBC2AA786BC0F66B01FBB92821C587A

# Checking for releases ...
No releases to promote!
```

The script should do that, not sure why it doesn't.

**Comment by mhdawson** [comment]
@gibfahn are the manual steps for the promotion something we can do by hand.  I see you landed the update to node.js org but we still need to fix the 404 on the download.

**Comment by gibfahn** [comment]
@mhdawson yes, that's what I tried to do by running `tools/release.sh`, but it didn't find any builds to promote.

Docs for that are here: https://github.com/nodejs/node/blob/master/doc/releases.md#12-promote-and-sign-the-release-builds

**Comment by mhdawson** [comment]
Ok just checked an job to build the 8.9.1 binaries for arm6 passed here: https://ci-release.nodejs.org/job/iojs+release-arm6-only/nodes=pi1-raspbian-wheezy/

@gibfahn can you re-run the script to promote ?

**Comment by gibfahn** [comment]
Done

**Comment by mhdawson** [comment]
@gibfahn thanks, download link now works.  I think we also have the process for recovering if we don't get an arm build out.  Where do you think we should best document that ?  The Release repo ?

**Comment by gibfahn** [comment]
>Where do you think we should best document that ? The Release repo ?

I think it should go in the release guide:

https://github.com/nodejs/node/blob/master/doc/releases.md#12-promote-and-sign-the-release-builds

**Comment by bertlea** [comment]
Thank you all for fixing that.  Will download and install that to my Raspberry Pi Zero W on Monday.  @jimmont , I guess you wanted to changed the title to "... 8.x..." instead of "...8.6.x...".

**Comment by jimmont** [comment]
@bertlea yes thanks.

**Comment by mhdawson** [comment]
PR for addition to docs: https://github.com/nodejs/node/pull/17455

**Comment by fhemberger** [comment]
Closing, as the link works now.
