### ISSUE TITLE
doc - nodejs.org website doc links are broken

### ISSUE THREAD

**Issue by prototypeme** [nodejs/nodejs.org#1390]
* **URL**: 
https://nodejs.org/dist/latest-v6.x/docs/api
https://nodejs.org/dist/latest-v8.x/docs/api

* **Browser version**: Chrome latest
* **Operating system**: Windows

nodejs.org website doc links are broken

![image](https://user-images.githubusercontent.com/11896633/31284972-b13023c4-aa7f-11e7-8e11-610b3ad9032c.png)

![image](https://user-images.githubusercontent.com/11896633/31285067-f4d13690-aa7f-11e7-97e1-bc6d99db454d.png)

**Comment by evanlucas** [comment]
This actually would go through nodejs/build, so I've gone ahead and opened an issue at https://github.com/nodejs/build/issues/905. Thanks for reporting!
