### ISSUE TITLE
Docs are 404ing

### ISSUE THREAD

**Issue by gtilma** [nodejs/nodejs.org#1392]
* **URL**: `https://nodejs.org/*/api/`
* **Browser version**: Chrome 61.0.3163.100
* **Operating system**: Kubuntu 17.04

Any version of the API docs is returning 404.

**Comment by gibfahn** [comment]
This is a duplicate of https://github.com/nodejs/build/issues/905, please follow that for more info.

I'll leave this open so people (hopefully) find it before raising more issues here.

**Comment by lpinca** [comment]
Is this still an issue?

**Comment by lpinca** [comment]
Closing as https://github.com/nodejs/build/issues/905 has also been closed.
