### ISSUE TITLE
Update board membership?

### ISSUE THREAD

**Issue by Trott** [nodejs/nodejs.org#1395]
* **URL**: https://nodejs.org/en/foundation/board/
* **Browser version**: n/a
* **Operating system**: n/a

I think the board membership needs to be updated. If I'm not mistaken, @sarahnovotny is now on the board. See https://www.youtube.com/watch?v=huYi9x5sXKQ

@nodejs/board for confirmation and also maybe a check to see there aren't any other changes that need to be made to that page.

**Comment by lpinca** [comment]
That page has been recently updated with https://github.com/nodejs/nodejs.org/pull/1381.

cc: @hackygolucky

**Comment by fhemberger** [comment]
Fixed by c9076f232d3b41da5c47c4deb2a3ad56e490f4d5.
