### ISSUE TITLE
Possible line spacing issue in nightly docs

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/nodejs.org#1399]
* **URL**: https://nodejs.org/download/nightly/*/docs/api/*
* **Browser version**: Google Chrome 63.0.3239.0 Canary
* **Operating system**: Windows 7 x64

It seems nightly docs have unequal line spacing in lines with and without code fragments, Compare:

https://nodejs.org/api/tty.html

![0](https://user-images.githubusercontent.com/10393198/31570802-d4898722-b090-11e7-972f-012fce5cf354.png)

https://nodejs.org/download/nightly/v9.0.0-nightly20171013981595c316/docs/api/tty.html

![1](https://user-images.githubusercontent.com/10393198/31570803-dcb17180-b090-11e7-8d70-2b9a05ee7105.png)

**Comment by fhemberger** [comment]
`line-height` is missing in the nightly docs. Maybe changes made in  https://github.com/nodejs/node/pull/15660 are not deployed there?

/cc @silverwind @lpinca

**Comment by silverwind** [comment]
I removed `p {line-height: 1.5}` because it seemed superflous. The case here is that `<code>` sets it to 1.5, but `<p>` defaults to 1.2. Restoring that rule fixes it. I'll send a PR.
