### ISSUE TITLE
Wrong date on vulnerability

### ISSUE THREAD

**Issue by patrickdbakke** [nodejs/nodejs.org#1410]
* **URL**: https://nodejs.org/en/blog/vulnerability/oct-2017-dos/
* **Browser version**: All 
* **Operating system**: All

Date is wrong. The [issue released this month](https://nodejs.org/en/blog/vulnerability/oct-2017-dos/) is listed as published on "2018-05-10" / "May 10, 2018". That's in the future. 

Also, "Octoboer" is spelled wrong.

**Comment by fhemberger** [comment]
Fixed, thanks!
