### ISSUE TITLE
/about/working-groups anchors don't work

### ISSUE THREAD

**Issue by wmonk** [nodejs/nodejs.org#144]
[On the working groups page](https://nodejs.org/en/about/working-groups/), the list of links to different types of working groups don't actually work. The titles of each subsection need to have the corresponding `id` added to them.

**Comment by wmonk** [comment]
Potentially fixed by #143

**Comment by mrkiffie** [comment]
This should be resolved by #196

**Comment by phillipj** [comment]
You're right, closing this for now. Feel free to re-open it if you've got some URLs which still doesnt work @wmomk
