### ISSUE TITLE
Different order in summary and rest of page

### ISSUE THREAD

**Issue by Tiriel** [nodejs/nodejs.org#1449]
* **URL**: https://nodejs.org/en/about/working-groups/
* **Browser version**: All
* **Operating system**: All

Hey there,

I just noticed that on the WG page, the order in tu summary at the top of the page is different from the actual order of paragraphs.

Example: in the summary, Intl group is the penultimate group, whereas in the body of the page it's just after i18n groups.

I can change it for the fr locale since I'm working on this page, but I guess it should be made the same on each locale.

**Comment by fhemberger** [comment]
Thanks for catching this, will be fixed in #1451.
