### ISSUE TITLE
Jerky scroll on entire website

### ISSUE THREAD

**Issue by Tiriel** [nodejs/nodejs.org#1460]
* **URL**: all
* **Browser version**: Chrome 62.0.3202.89
* **Operating system**: Ubuntu 16.04.3

I've noticed for some time that scrolling is deeply uneasy on the website. Some times using mouse scroll isn't taken into account at all, some times it does scroll a bit, but very jerkily.

Is it just me?

Edit: Just to add a precision, this issue is only on Chrome Ubuntu AFAIK, I can't reproduce on FF

**Comment by Tiriel** [comment]
The problem seems to be coming from the 'Scroll to top' button script, in `layouts/partials/footer.hbs`.

Looking into it.

**Comment by ghost** [comment]
Any update on this? Is there anyone running Ubuntu that can confirm this?

**Comment by Tiriel** [comment]
Still trying to figure out other ways to scroll without the jerky effect on Chrome, but so far, no joy :(

**Comment by JakeCalkins** [comment]
Scrolling is like a slow motion rubber banding effect for me, when I scroll down it moves like molasses then speeds up rapidly towards the end. I imagine it's some sort of smooth scrolling issue or a scroll to top issue like mentioned by @Tiriel .

**URL** | All
**Browser** | Chrome Canary* Version 70.0.3501.0 (Official Build) canary (64-bit) on win 8

edit: only appears to be on Chrome Canary (with just the new UI tweaks). I tested on Beaker, Brave, Vivaldi, Firefox, IE, Opera and regular Chrome. Worth keeping an eye out when the Material Design 2 refresh drops, as this may go from affecting 0% of your users to 90%.

**Comment by fhemberger** [comment]
@Tiriel @JakeCalkins Could you please check out https://github.com/nodejs/nodejs.org/tree/fix/scroll, run `npm run serve` and check if the scrolling improves?

**Comment by JakeCalkins** [comment]
Seems fixed to me, but I am using a different machine (same browser, different version) as when I originally posted so cannot scientifically confirm.
