### ISSUE TITLE
Node.js logo very tiny on MS Edge (Windows 10)

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs.org#1461]
* **URL**: https://nodejs.org/en
* **Browser version**: Microsoft Edge
* **Operating system**: Windows 10

The logo seems to be very tiny in MS Edge on Windows 10. I could only test in VirtualBox, can a Windows 10 user please check this?

![bildschirmfoto 2017-11-08 um 14 34 00](https://user-images.githubusercontent.com/153481/32551933-7d396b34-c492-11e7-978f-b38ffebe8abb.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/13847095/32553883-5e04cb86-c498-11e7-89bb-fcc4bc79c70a.png)
This is a comparison of the icon on a PC running Windows 10.
Compared Chrome to Edge

**Comment by fhemberger** [comment]
@mlosh Sorry, wasn't talking about the icon but the logo on top of the main navigation.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/13847095/32554998-dc0cf42e-c49b-11e7-96fe-dd9a8df59e99.png)
Logo seems fine as well

**Comment by fhemberger** [comment]
Ok, then it seems to be some VirtualBox weirdness, I guess. Thanks!
