### ISSUE TITLE
403 Forbidden on trying to download from distribution

### ISSUE THREAD

**Issue by binarymee** [nodejs/nodejs.org#1469]
I am installing nodejs in my EC2 instance with NVM. I used to follow below steps to install nodejs ,

- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
- . ~/.nvm/nvm.sh
- nvm install 8.4.0
- I have automated this with Chef recipes and it was working fine without any issues.

For past 1 week, the same steps didn't work. nvm install failed. On running nvm ls-remote, it returned N/A I went through this [issue](https://github.com/creationix/nvm/issues/1389). But my server certificate was valid. When I ran
`
curl -O https://nodejs.org/dist/v8.4.0/node-v8.4.0.tar.xz --verbose`

I didn't see any server certificate issues but the response was` HTTP/1.1 403 Forbidden`

I am using Amazon Linux 2017.03 in the region us-east-1a

Why I am getting 403 Forbidden suddenly. Seems most of the EC2 instances in that region is getting it.

**Comment by fhemberger** [comment]
Hmm, download link works for me (Germany), cc'ing @nodejs/build.
Which AWS region do you use? Which AMI are you using for your EC2 instance?

**Comment by binarymee** [comment]
@fhemberger 
I am using Amazon Linux 2017.03 in the region us-east-1a

**Comment by fhemberger** [comment]
@binarymee Does this problem still occur? I'm sorry, but I don't know what the issue could be here besides a temporary glitch …

**Comment by fhemberger** [comment]
No reply from OP, closing for now. Feel free to re-open this issue if the problem still occurs.
