### ISSUE TITLE
https://nodejs.org/download/

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#1479]
![screenshot 1](https://user-images.githubusercontent.com/33800905/32989032-44e3ae32-cd36-11e7-9df6-b73ca953a06e.png)

**Comment by vsemozhetbyt** [comment]
@maheshjagdale565, hi! What is wrong with this page in your opinion?

**Comment by ajmeese7** [comment]
@vsemozhetbyt I'm guessing that @maheshjagdale565 was hoping for a more intuitive UI.

**Comment by vsemozhetbyt** [comment]
There are also more intuitive ones:

https://nodejs.org/en/download/current/
https://nodejs.org/en/download/

The https://nodejs.org/download/ usually serves as an entry point for more granular access.

**Comment by fhemberger** [comment]
The `/download/` path is also used by third party scripts, so this can't be changed.

Closing, as @vsemozhetbyt already stated the websites' "official" download URLs.
