### ISSUE TITLE
guides: use of GET method in echo server

### ISSUE THREAD

**Issue by bneevan** [nodejs/nodejs.org#1480]
* **URL**: https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction/
* **Browser version**: all
* **Operating system**: all

`Echo Server` code in _[Anatomy of an http transaction](https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction/)_ uses GET method to handle the request. But this cannot work since any additional data in the request (eg: /echo?hello) will change the route and return a 404 response. 

To handle this data processing and routing properly we should use the POST method.

**Comment by lpinca** [comment]
Fixed by #1481.
