### ISSUE TITLE
No shasum files for RPM.

### ISSUE THREAD

**Issue by BorisLeumi** [nodejs/nodejs.org#1486]
Hi,
I would like to use the RPM version but I have not found shasum files.
i was looking at:
Nodejs 8.9.1:
https://rpm.nodesource.com/pub_8.x/el/7/x86_64/
Nodejs: 6.11.4
https://rpm.nodesource.com/pub_6.x/el/7/x86_64/

Can you help please? :)

**Comment by fhemberger** [comment]
Hmm, RPMs are not provided by Node.js itself but by NodeSource.

/cc @rvagg @chrislea – can you help?

**Comment by rvagg** [comment]
there's no shasums but they are signed so as long as you have the nodesource key that should come in the nodesource-release rpm @ https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm then it should verify when installed and complain if it's not signed properly. This is all set up with the script @ https://rpm.nodesource.com/setup_8.x (`curl -sL https://rpm.nodesource.com/setup_8.x | sudo -E bash -`). @chrislea can correct me if I'm wrong on any of this.
