### ISSUE TITLE
Layout Right-To-Left direction

### ISSUE THREAD

**Issue by ouadie-lahdioui** [nodejs/nodejs.org#1495]
Hello All,

working on Arabic localisation of nodejs.org web site, i've noticed that the web site doesn't support the direction attribute to set the base direction of text for display. 

for some languages, is essential to write in right-to-left instead of left-to-right such as : Arabic, Hebrew, Persian, etc.

Can you confirm that the web site doesn't yet support the right to left writing direction ? if so, i will be happy to make a PR to bring that.

Thank you !

**Comment by fhemberger** [comment]
Yes, you're right. So far we didn't have any RTL languages.

Probably the easiest way is to introduce a new attribute in `site.json`: `rtl: true`, then replace `<html lang="{{site.locale}}">` in the templates with `<html lang="{{site.locale}}"{{if site.rtl}} dir="rtl"{{/if}}>`.

**Comment by ouadie-lahdioui** [comment]
well done #1500
