### ISSUE TITLE
Update opengraph metadata for social cards

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/nodejs.org#1497]
Would be nice to add more meta data to posts to include a better image for cards on social such as twitter and facebook.

<img width="617" alt="screen shot 2017-12-04 at 5 08 16 pm" src="https://user-images.githubusercontent.com/498775/33578820-c90278b6-d915-11e7-9208-37c0d37e2285.png">

We can use this tool to debug https://developers.facebook.com/tools/debug/sharing/

it looks like we want to specify og:image at the very least

**Comment by MylesBorins** [comment]
Looking at raw open graph data it looks like we already specify a twitter image... I wonder why it doesn't come up

```
<meta charset="utf-8" />
<meta name="author" content="Node.js Foundation" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta property="og:site_name" content="Node.js" />
<meta property="og:title" content="Data Confidentiality/Integrity Vulnerability, December 2017 | Node.js" />
<meta name="og:image" content="/static/images/logo-hexagon.png" />
<meta name="og:image:type" content="image/png" />
<meta name="og:image:width" content="224" />
<meta name="og:image:height" content="256" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@nodejs" />
<meta name="twitter:title" content="Data Confidentiality/Integrity Vulnerability, December 2017 | Node.js" />
<meta name="twitter:image" content="/static/images/logo-hexagon.png" />
<meta name="twitter:image:alt" content="The Node.js Hexagon Logo" />
```

**Comment by ghost** [comment]
I guess we should use `<meta property="og:image" content="/static/images/logo-hexagon.png" />` instead of "name".

**Comment by ghost** [comment]
#1498

**Comment by alecperkins** [comment]
I think the image links need to be fully qualified URLs. Twitter validator: https://cards-dev.twitter.com/validator
