### ISSUE TITLE
Code fragments have color issues

### ISSUE THREAD

**Issue by bogas04** [nodejs/nodejs.org#151]
https://nodejs.org/en/get-involved/development/ has issues with color of the text. 

![screen shot 2015-09-14 at 5 48 20 pm](https://cloud.githubusercontent.com/assets/6177621/9849460/e44b95d6-5b08-11e5-9fe6-ae3ef54eb8c1.png)

**Comment by fhemberger** [comment]
Thanks, should be fixed now (requires force-reload due to caching).
