### ISSUE TITLE
Share new v9.3.0 blog on Facebook text is wrong

### ISSUE THREAD

**Issue by gonenduk** [nodejs/nodejs.org#1517]
When sharing a link to the blog about v9.3.0 on facebook, the title and text of the share is a default 404 error title and text.
For reference, v9.2.0 is ok.

Here is the result of 9.2 (good one):
[v9.2.0](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fnodejs.org%2Fen%2Fblog%2Frelease%2Fv9.2.0%2F)

And of 9.3 (bad one):
[v9.3.0](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fnodejs.org%2Fen%2Fblog%2Frelease%2Fv9.3.0%2F)

**Comment by pierreneter** [comment]
It's cached. Just click `Scrape Again`. Clicked.

**Comment by gonenduk** [comment]
Cool. When you clicked on scrape - it fixed for everyone 👍
