### ISSUE TITLE
Npm run server blocked 

### ISSUE THREAD

**Issue by webolabo** [nodejs/nodejs.org#1519]
* **URL**:
* **Browser version**:
* **Operating system**:

Hello,
After the last update of node.js v8.9.3 on windows 
My angular4 + jee project stopped 
Here is the error message:
WARNING in ./~/jsdom/lib/jsdom/utils.js
216:21-40 Critical dependency: the request of a dependency is an expression

WARNING in ./~/jsdom/lib/jsdom/utils.js
216:21-40 Critical dependency: the request of a dependency is an expression

WARNING in ./~/jsdom/lib/jsdom/living/xmlhttprequest.js
20:23-30 Critical dependency: require function is used in a way in which depende                                                                                                                                                             ncies cannot be statically extracted

ERROR in ./~/jquery/lib/node-jquery.js
Module not found: Error: Can't resolve 'xmlhttprequest' in 'C:\Users\ASUS\Deskto                                                                                                                                                           p\****\***\git\front-client\node_modules\jquery\l                                                                                                                                                             ib'
 @ ./~/jquery/lib/node-jquery.js 8:28-53
 @ ./src/lib.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/jquery/lib/node-jquery.js
Module not found: Error: Can't resolve 'location' in 'C:\Users\ASUS\Desktop\****\*****\git\*****\front-client\node_modules\jquery\lib'
 @ ./~/jquery/lib/node-jquery.js 13:24-43
 @ ./src/lib.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/jquery/lib/node-jquery.js
Module not found: Error: Can't resolve 'navigator' in 'C:\Users\ASUS\Desktop\***\*****\git\*****\front-client\node_modules\jquery\lib'
 @ ./~/jquery/lib/node-jquery.js 17:25-45
 @ ./src/lib.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/jsdom/lib/jsdom/living/xmlhttprequest.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\ASUS\Desktop                                                                                                                                                             \****\***\git\front-client\node_modules\jsdom\lib                                                                                                                                                             \jsdom\living'
 @ ./~/jsdom/lib/jsdom/living/xmlhttprequest.js 4:18-42
 @ ./~/jsdom/lib/jsdom/browser/Window.js
 @ ./~/jsdom/lib/jsdom.js
 @ ./~/jquery/lib/node-jquery.js
 @ ./src/lib.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.

Any help please ?

**Comment by fhemberger** [comment]
Hi there! Sorry, this is the issue tracker for the **Node.js website**.

You may want to look at:
https://github.com/tmpvar/jsdom
https://github.com/nodejs/help
