### ISSUE TITLE
Downloading node is very slow

### ISSUE THREAD

**Issue by swkimA** [nodejs/nodejs.org#1520]
* **URL**: https://nodejs.org/dist/v8.9.3/node-v8.9.3-x64.msi, https://nodejs.org/dist/v8.9.3/win-x64/node.exe
* **Browser version**: Chrome, nvm-windows
* **Operating system**: Windows 10 x64

Downloading node is very slow.

**Comment by fhemberger** [comment]
Node.js downloads are distributed via Cloudflare CDN, which always chooses a mirror closest to your location. Download performance may vary depending on your local network connection or your ISP.
