### ISSUE TITLE
Question in the home page of the website

### ISSUE THREAD

**Issue by QC-L** [nodejs/nodejs.org#1524]
* **URL**: https://github.com/nodejs/nodejs.org/blob/31e4313f78b3cfc613e8b792bb764afc53b53945/build.js
* **Browser version**: 
* **Operating system**:

Hey, I found that `Important security releases, please update now!` in the build.js file does not support i18n.
```
function getSource (callback) {
  // Loads all node/io.js versions.
  loadVersions((err, versions) => {
    const source = {
      project: {
        versions,
        latestVersions: {
          current: latestVersion.current(versions),
          lts: latestVersion.lts(versions)
        },
        banner: {
          visible: true,
-->       content: 'Important <a href="https://nodejs.org/en/blog/vulnerability/december-2017-security-releases/">security releases</a>, please update now!'
        }
      }
    }

    callback(err, source)
  })
}

```
I don 't know how to solve.

**Comment by fhemberger** [comment]
Yes, you're right. At the moment, this is not translatable. We need to fix that.

**Comment by QC-L** [comment]
@fhemberger Good job! You are so efficient!
