### ISSUE TITLE
[Nodejs-AR] Right to left footer not properly displayed

### ISSUE THREAD

**Issue by ouadie-lahdioui** [nodejs/nodejs.org#1530]
Hello, 

i've noticed that in all web site supported languages, the footer is not translatable, However, it's also displayed in right to left :

<img width="865" alt="ko" src="https://user-images.githubusercontent.com/2996203/34358958-760fadc2-ea54-11e7-8bf1-872dd674b77a.png">

I think that the direction of footer should be ````ltr```` all time to be displayed juste like that :

<img width="961" alt="ok" src="https://user-images.githubusercontent.com/2996203/34358951-6c766922-ea54-11e7-9c01-a47b79eed098.png">

WDYT ?

* **URL**: nodejs.org/ar

**Comment by fhemberger** [comment]
Adding `.linuxfoundation-footer { direction: ltr; }` (and probably `.issue-link-container { direction: initial; }`) fixes this. Not sure about translating the footer (because of legal foo).

**Comment by ouadie-lahdioui** [comment]
Adding juste direction ltr to linuxfoundation footer classe work fine.

**Comment by ouadie-lahdioui** [comment]
Thank you @fhemberger
