### ISSUE TITLE
Error with packages

### ISSUE THREAD

**Issue by a-ta-ta** [nodejs/nodejs.org#1540]
* **https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora**:
* **Firefox 57.0.3 64-bit**:
* **Ubuntu 16.04 LTS**:

 The command for 9.x nodejs for **Enterprise Linux** seems to be broken cause I got _the same 8.x package_ set for `curl --silent --location https://rpm.nodesource.com/setup_9.x | sudo bash -`. 

```
[deploy@albus ~]# yum --showduplicates list nodejs | expand
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Available Packages
nodejs.x86_64             1:6.12.2-1.el7                              epel      
nodejs.x86_64             2:8.0.0-1nodesource.el7.centos              nodesource
...
nodejs.x86_64             2:8.9.3-1nodesource                         nodesource
nodejs.x86_64             2:8.9.4-1nodesource                         nodesource

```

This ruined installation `(yum install -y nodejs`) with:
```
Error downloading packages:
2:nodejs-8.9.4-1nodesource.x86_64: [Errno 256] No more mirrors to try.  
```

In other words it sets the wrong path: rpm.nodesource.com/**pub_9.x**/el/7/x86_64/nodejs-**8.9.4-1**nodesource.x86_64.rpm

and leads to the error: `https://rpm.nodesource.com/pub_9.x/el/7/x86_64/nodejs-8.9.4-1nodesource.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found`
because there's no such package!
I do not really know if this issue regards to the site or the nodejs itself. =(
Hope eventually you set the right 9.x package path for us.  Anyway thanks for the work are doing there. If you have any additional questions or else: panale89@mail.ru

Regards,
Alex

**Comment by daxlab** [comment]
\cc @gibfahn

**Comment by gibfahn** [comment]
Those packages are entirely maintained by https://github.com/nodesource/distributions, so please raise an issue on that repo.

There might already be one...

I'll close this, as no-one in this issue tracker knows about these things, but feel free to comment further here. A comment here with a link to the nodesource/distributions issue once you've created/found one would be helpful for others who may hit this.
