### ISSUE TITLE
One mistake in the article of guides

### ISSUE THREAD

**Issue by evanzlj** [nodejs/nodejs.org#1542]
* **URL**:https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#why-use-process-nexttick
* **Browser version**:none
* **Operating system**:none

Thanks for this article, but when I try to convert this to chinese, I find a error:

> Say that listen() is run at the beginning of the event loop, but the listening callback is placed in a setImmediate().

I think the listening callback is placed in the nextTick queue, right?~~

**Comment by gibfahn** [comment]
>Say that listen() is run at the beginning of the event loop, but the listening callback is placed in a setImmediate(). Unless a hostname is passed, binding to the port will happen immediately. For the event loop to proceed, it must hit the poll phase, which means there is a non-zero chance that a connection could have been received allowing the connection event to be fired before the listening event.

As I understand it, this paragraph is explaining why the listening callback needs to be placed in the `nextTick` queue, by saying that _if_ it was a `setImmediate()`, then it would cause problems. 

I think the confusion here is the use of the word `Say`, I would translate `Say` as 假如 , as in 假如`on('listening')`是个`setImmediate()`，会出......的问题，所以得用`process.nextTick()`.

Original PR to add this was: https://github.com/nodejs/node/pull/4936 FWIW

**Comment by evanzlj** [comment]
Got it! Thanks for your help~~^_^
