### ISSUE TITLE
Bug at API::Buffer::readable.read(0)

### ISSUE THREAD

**Issue by asier-gutierrez** [nodejs/nodejs.org#1543]
HTML tag \<a href="....">\</a> can be seen on the title & content of that section.

* **URL**: https://nodejs.org/api/stream.html#stream_a_href_http_man7_org_linux_man_pages_man0_readable_read_0_html_readable_read_0_a
* **Browser version**: Chrome 63.0.3239.84 & Firefox 57.0
* **Operating system**: Windows 10

Sorry for not reading contribution guidelines, I only wanted to help with the few free time that I have.

**Comment by vsemozhetbyt** [comment]
Thank you for the report!

I think this will be fixed when https://github.com/nodejs/node/pull/17724 is backported.
