### ISSUE TITLE
fs.chmod documentation 8.x & 9.x : The value of "mode" is not an "integer"

### ISSUE THREAD

**Issue by warlock** [nodejs/nodejs.org#1545]
https://nodejs.org/dist/latest-v8.x/docs/api/fs.html#fs_fs_chmod_path_mode_callback
https://nodejs.org/dist/latest-v9.x/docs/api/fs.html#fs_fs_chmod_path_mode_callback

The "mode" value on the web is a "whole number". But sometimes you need an "octal". "number is the correct type in javascript.

Thank you.

**Comment by tniessen** [comment]
Octals (`0755`) are integers, so I don't really get the problem. The type `number` includes integers and floating point numbers, so why would `number` be more appropriate than `integer`?

**Comment by warlock** [comment]
He thought that the "integer" type does not exist in js and the official type was "number".

I found that it uses the word "integer" in js:
Number.isSafeInteger(0o777) -> true
Thank you.
