### ISSUE TITLE
Cloudflare prevents maven from downloading Node binaries.  403 from server.

### ISSUE THREAD

**Issue by glennconnell** [nodejs/nodejs.org#1546]
* **URL**: https://nodejs.org/dist/v8.9.4/node-v8.9.4-darwin-x64.tar.gz
* **Browser version**:
* **Operating system**:Mac OSX

Starting January 4, 2018, maven using rontend-maven-plugin:1.6:install-node-and-npm fails to download Node binaries.  This is due to Cloudflare.  It now sends you to a captcha page.  Maven cannot handle this and we get a 403 from the server.  
I can individually click on the "I am not a robot" checkbox on the captcha page to download but, this is our company's product build script and is run from other machines.  
We need a way to allow maven, etc. to download without having the captcha get in the way.

**Comment by fhemberger** [comment]
Hmm, does Maven set a special user-agent header that triggers the Cloudflare captcha?
Because the URL above works for me in the browser, as well as wget and curl.

**Comment by glennconnell** [comment]
I get the captcha on my browser too.  This was all working on Jan 3 and before.  On Jan 4 it broke.
Did you already  do the captcha on your system before?  It may remember for a period of time.

**Comment by glennconnell** [comment]
[INFO]
[INFO] --- frontend-maven-plugin:0.0.27:install-node-and-npm (install node and npm) @ matlab-drive-webapp ---
[INFO] Found proxies: []
[INFO] Installing node version v5.7.1
[INFO] Creating temporary directory /Users/gconnell/Perforce/gconnell_maci_1/eps/matlab-drive-webapp/main/node_tmp
[INFO] Downloading Node.js from https://nodejs.org/dist/v5.7.1/node-v5.7.1-darwin-x64.tar.gz to /Users/gconnell/Perforce/gconnell_maci_1/eps/matlab-drive-webapp/main/node_tmp/node.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.186 s
[INFO] Finished at: 2018-01-05T14:36:13-05:00
[INFO] Final Memory: 18M/296M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm (install node and npm) on project matlab-drive-webapp: Could not download Node.js: Got error code 403 from the server. -> [Help 1]
[ERROR]


The 403 is due to the going to the captcha page.

FYI

Glenn

**Comment by glennconnell** [comment]
Hi Frederic,

I do not see the captcha from my home browser.  However, I see it from any machine on our company’s network.

**Comment by mhdawson** [comment]
Works for me as well, both browser and using curl. (I tested by downloading the linux 64 binaries for version 8)

**Comment by mhdawson** [comment]
@jbergstroem  I think you were going to look at the cloudflare settings, did you change anything recently ?

**Comment by mhdawson** [comment]
From what I can see of the config, you should only be prompted if cloudflare believes you fall into a the moderately threatening or higher category.     I'm not a cloudflare expert but might be able to dig up more info if I had info about your ips/org.

**Comment by glennconnell** [comment]
Yes, I think our corporate networks makes all of us appear to be from the same IP address.  Perhaps, it’s something for our side to look into.  I just noticed the sudden change of behavior and it was only with your website so I opened the ticket.

Thanks

**Comment by silverwind** [comment]
This issue should apply to all sites hosted on Cloudflare. Only they can tell you why they think that you're "suspicious". You could also check your IP for any RBL entries which may give you more hints.
