### ISSUE TITLE
Terrible download speed

### ISSUE THREAD

**Issue by dnjstlr555** [nodejs/nodejs.org#1551]
* **URL**: https://nodejs.org/dist/v9.4.0/node-v9.4.0-x64.msi
* **Browser version**: Chrome 63.0.3239.132 (64-bit) (cohort: Stable)
* **Operating system**: Windows 10 Pro 1703(15063.786)

I live in south korea, and i'm sure that nodejs.org's server located far land
average downloading speed is 10KB ~ 30KB which tooks me about 30 minutes to download whole 15.7MB
That's not end. I lost connection to server every 2-3 minutes!!!
It's not my router or internet problem.
Could you make a Mirror server or Torrent files?? I've suffered enough please

**Comment by fhemberger** [comment]
Node.js is distributed via Cloudflare.

/cc @nodejs/build

**Comment by tniessen** [comment]
> I live in south korea, and i'm sure that nodejs.org's server located far land

Cloudflare has at least one data center in korea.

**Comment by dnjstlr555** [comment]
I didn't know that! but i'm still having this problem.
Any reason?

**Comment by gibfahn** [comment]
I guess it's possible that Cloudflare is either misconfigured, or having an outage or something. Looking at the cloudflare status page might be helpful, would need to be done by @mhdawson @rvagg @joaocgreis @jbergstroem or myself.

@dnjstlr555 have you had this problem before? Can you tell us roughly where you're based in South Korea (city is fine)? It might be helpful to check another site that uses cloudflare and see if you have the same problem.

**Comment by dnjstlr555** [comment]
My city is seoul and I had this same problem few years ago i think. there's Network Performance Issues in Seoul, Korea according to https://www.cloudflarestatus.com/ this page in Jan 8, 2018 but it was resolved.

**Comment by joyeecheung** [comment]
CNPM has a mirror for Node.js releases: https://npm.taobao.org/mirrors/node They are distributed via the Alibaba Cloud CDN, which by default only provides services from data centers in China. It could be faster if you are connecting from South Korea.

**Comment by dnjstlr555** [comment]
@joyeecheung Speed is lower than before.... 7.8kb. I have no clue what is going on ㅠ_ㅠ

**Comment by fhemberger** [comment]
@dnjstlr555 Any changes on the download speed for you?
(I'm not really sure if we can fix this issue on our end. Could be anywhere on the network.)

**Comment by dnjstlr555** [comment]
Still it's slow. release it with torrent would only way to solve this problem I think.

**Comment by fhemberger** [comment]
@nodejs/build Could https://github.com/webtorrent/create-torrent be a solution for this?

**Comment by cedx** [comment]
Same issue here : I'm located in France. Usually, I haven't any problem to download a Node.js release, but since a few weeks this has become almost impossible (no more than 800 bytes/sec... when it works !). I have a very good DSL connection (about 5 Mb/sec), only Node.js downloads are affected.

It would definitely be a good option to have Torrent files to avoid CloudFlare issues.

**Comment by mat-ale** [comment]
+1, same problem currently in Italy

**Comment by fhemberger** [comment]
This will be discussed during the relaunch planning of the nodejs.org website.

**Comment by refack** [comment]
> @nodejs/build Could webtorrent/create-torrent be a solution for this?

I'm generally +1 on this. It's just that we have > 30 variants of each release (including nightlies and daily V8 canary builds). This should to be addressed from a UX perspective.

**Comment by dnjstlr555** [comment]
this issues are fixed these days so I'm closing it.
