### ISSUE TITLE
Debian versions need updating

### ISSUE THREAD

**Issue by ezhukov** [nodejs/nodejs.org#1557]
* **URL**: https://nodejs.org/en/download/package-manager/
* **Browser version**: Firefox 52.5.0 (64-bit)
* **Operating system**: Debian Buster

The webpage is out of date:
Supported Debian versions:
    Debian 7 (wheezy)
    Debian 8 / stable (jessie)
    Debian testing (stretch, aliased to jessie)
    Debian unstable (sid)
Should be:
Supported Debian versions:
    Debian 8 (jessie aka old-stable)
    Debian 9 / stable (stretch)
    Debian testing (buster to-be-released-as-next-stable)
    Debian unstable (sid never-to-be-released aka rolling)

Reference: https://wiki.debian.org/DebianStable

Thanks for your work!

**Comment by ghost** [comment]
Closing as this has been landed in #1559
