### ISSUE TITLE
Windows .msi 64bit includes npm 3.10.5, rather than stated 5.6.0

### ISSUE THREAD

**Issue by bcullman** [nodejs/nodejs.org#1558]
* **URL**: https://nodejs.org/en/download/https://nodejs.org/en/download/
* **Browser version**: not relavent
* **Operating system**: win 2k8r2

Windows .msi 64bit includes npm 3.10.5, rather than stated 5.6.0

**Comment by gibfahn** [comment]
What version of the msi did you download? Node 8.9.4?

**Comment by gibfahn** [comment]
Also have you previously installed npm on your system?

**Comment by bcullman** [comment]
The file: 
https://nodejs.org/dist/v8.9.4/node-v8.9.4-x64.msi

listed on https://nodejs.org/en/download/.

I uninstalled the previous version of node. This also uninstalled the version of npm that came with it. I verified I did not have node or npm on my system. I then tried the .msi. 

It put npm 3.10.5 on my machine.

**Comment by gibfahn** [comment]
cc @nodejs/platform-windows , a reproduce would be useful

**Comment by bcullman** [comment]
Arg. My bad.

While there was no npm located in `C:\Program Files\nodejs`, I had another npm located at `C:\Users\[username]\AppData\Roaming\npm`.
