### ISSUE TITLE
Fedora 27 Install Update

### ISSUE THREAD

**Issue by kirenpillay** [nodejs/nodejs.org#1563]
* **URL**: https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora
* **Browser version**:  Chrome
* **Operating system**:  Any

Installation with the latest Fedora is achieved by:
`sudo dnf install nodejs`

**Comment by fhemberger** [comment]
… as it says on the page if you scroll down a bit: https://nodejs.org/en/download/package-manager/#alternatives There are the official Node.js packages (provided by NodeSource in this case) and the distro's packages. We list them in this order, as the distro sometimes may be behind the official release.

**Comment by kirenpillay** [comment]
Thanks Frederic. I'm a newbie so I wanted to get going quickly.

I think maybe a hint saying that the Fedora distro may be behind and your
alternative packages are recommended might help. Also a link to the
alternatives might be useful?

Also someone seeing this for the first time will see yum being used and
like me think this is out of date?

I don't find this layout user friendly, but if you think it works, not a
problem.

Regards
Kiren

**Comment by fhemberger** [comment]
@kirenpillay Thanks for your feedback. We're already working on a website relaunch, where also the whole "install via package manager" section will be overhauled.
