### ISSUE TITLE
executing bash script as root to install nodejs

### ISSUE THREAD

**Issue by olangella** [nodejs/nodejs.org#1566]
* **URL**:
* **Browser version**:
* **Operating system**:

Dear nodejs website maintainer,

I went to this URL to install an up to date version of nodejs for debian stretch.
It's a very good idea to use the package management system... the problem is how to install it : 
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
executing a bash script as root is not very secure...
The minimum, as a system administrator, is to check to content before executing it... I did it, and hopefully, it is simple to avoid it and just create a source list and retrieve the gpg key.

Would it be possible at least to just give a signed script to be able to check that we are really executing something that you have created ?
Or just give the sources list to write and the repository key (such as many other sites) ?
Or pehaps that I've missed something ?

Best regards,
Olivier

**Comment by lpinca** [comment]
That script is not maintained by us, the issue should be opened here: https://github.com/nodesource/distributions

**Comment by gibfahn** [comment]
Please open an issue in nodesource/distributions, that's a third-party repo and not something the nodejs team have control over (it's also what the third line of the script asks you to do).

As an aside, if you've checked the script, then you can probably work out the lines to remove to just create the source list and add the gpg key. If you suggested that nodesource make that available somewhere I guess that might be fine, however the rest of that script is mostly checking that you're on the right architecture, that you're trying to fetch a supported version of node, and then checking your distribution so it can run the right commands. These all seem like useful additions.

@fhemberger hope you're okay with me closing this.
