### ISSUE TITLE
Coverage not getting updated on NodeJS website

### ISSUE THREAD

**Issue by trivikr** [nodejs/nodejs.org#1568]
* **URL**: https://coverage.nodejs.org/
* **Browser version**: N/A
* **Operating system**: N/A

The coverage is not getting updated at https://coverage.nodejs.org/
It's 18/02/2018, and the latest coverage being shown is from 13/02/2018

**Comment by trivikr** [comment]
The nightly coverage job [node-test-commit-linux-coverage](https://ci.nodejs.org/view/All/job/node-test-commit-linux-coverage/) has been failing since Feb 13th

**Comment by trivikr** [comment]
Looks like this had happened in the past, when tests were missing for the following days:
* 07/01/2018 to 09/01/2018
* 28/11/2017 to 13/12/2017

**Comment by trivikr** [comment]
cc: @mhdawson 
Example CI build failure https://ci.nodejs.org/view/All/job/node-test-commit-linux-coverage/534/nodes=benchmark/console

**Comment by trivikr** [comment]
Hi, any update on this issue?

**Comment by trivikr** [comment]
Hi, any update on this issue?

**Comment by gibfahn** [comment]
See https://github.com/nodejs/node/issues/18938

**Comment by mhdawson** [comment]
Closing as this is now fixed.  Thanks for reporting and sorry it took so long, I was out of the office last week.
