### ISSUE TITLE
Provide prebuilt binaries for musl libc as well?

### ISSUE THREAD

**Issue by asottile** [nodejs/nodejs.org#1569]
* **URL**: http://nodejs.org/dist/v9.5.0/
* **Browser version**: N/A
* **Operating system**: Alpine Linux v3.7

Probably a shot-in-the-dark ask, and potentially the wrong project to create an issue but here goes!

The current binaries provided at http://nodejs.org/dist/v9.5.0/ are all `glibc` binaries and do not function inside `alpine` docker containers.  Executing the binary after extraction leads to:

```console
# ./node --version
sh: ./node: not found
```

Here's the specific operating system in question:

```
$ docker run -ti py:2.7.14-alpine3.7 sh -xc 'uname -a && cat /etc/os-release'
+ uname -a
Linux 6913c996248d 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 Linux
+ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.7.0
PRETTY_NAME="Alpine Linux v3.7"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

**Comment by fhemberger** [comment]
Hi, we're providing official Docker containers based on Alpine, e.g. [`node:9.5-alpine`](https://github.com/nodejs/docker-node/blob/master/9/alpine/Dockerfile).

**Comment by asottile** [comment]
Yep, I've seen those -- still I think standalone prebuilt muslc downloads would be beneficial in a few situations where the `node:x.x-alpine` docker images aren't helpful:

- using _some other_ alpine docker image (in this specific instance, I'd like to use the `python` alpine images)
- using some other platform which also uses muslc and is neither docker nor alpine (gentoo musl for instance)

**Comment by fhemberger** [comment]
I'm not sure if we have the build/test infrastructure right now to support musl as well, there hasn't been any demand for it yet besides for the Docker images. Maybe @nodejs/build can comment on that.

For other Docker images, you could still use [multistage builds](https://docs.docker.com/develop/develop-images/multistage-build/). I know, it's only a crutch, but it would help for now.

**Comment by asottile** [comment]
My actual intention is to use it with `nodeenv` and not with docker (I can already `apk --no-cache add node-js` just fine!) -- see the linked issue: https://github.com/ekalinin/nodeenv/issues/204 and the link-linked issue: https://github.com/pre-commit/mirrors-jshint/issues/4

**Comment by gibfahn** [comment]
>I'm not sure if we have the build/test infrastructure right now to support musl as well, there hasn't been any demand for it yet besides for the Docker images. Maybe @nodejs/build can comment on that.

Yeah, @asottile could you raise an issue in https://github.com/nodejs/build and link to this one?

**Comment by asottile** [comment]
via https://github.com/nodejs/build/issues/1140#issuecomment-564330014
