### ISSUE TITLE
Dockerizing a Node.js web app guide improve Dockerfile

### ISSUE THREAD

**Issue by ramonvanstijn** [nodejs/nodejs.org#1571]
* **URL**: https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
* **Browser version**: N/A
* **Operating system**: N/A

The Dockerfile in the Dockerizing a Node.js web app guide contains the instruction:
```
COPY . .
```
This also copies `Dockerfile` and `.dockerignore` into the image and that does not seem right to me.

**Comment by styfle** [comment]
Should we change `.dockerignore` to the following?

```
node_modules
npm-debug.log
.dockerignore
Dockerfile
```

**Comment by fhemberger** [comment]
@styfle You can't seem to ignore `.dockerignore` and `Dockerfile`.

**Comment by styfle** [comment]
@fhemberger The [documentation](https://docs.docker.com/engine/reference/builder/#dockerignore-file) says you can.

> You can even use the `.dockerignore` file to exclude the `Dockerfile` and `.dockerignore` files. These files are still sent to the daemon because it needs them to do its job. But the ADD and COPY instructions do not copy them to the image.

**Comment by fhemberger** [comment]
Tried it a few days ago, didn't work for me. But feel free to check for yourself.

**Comment by ramonvanstijn** [comment]
For this example I would suggest to do `COPY server.js .` instead of `COPY . .`

**Comment by styfle** [comment]
Yeah it does seem a bit odd. Why does it have two copy steps?

```
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .
```

I would think the js source and the package.json could be copied in the same step.

**Comment by fhemberger** [comment]
It's for caching your `node_modules` in a separate layer, faster successive build times.

**Comment by ramonvanstijn** [comment]
@fhemberger You are spot on.

About the second copy, in anything else than a simple example the source code of an application typically consists of multiple `.js` files which are collected in a folder named`src`. One would do a `COPY src /usr/src/app` in that case for example.

I think a good project folder structure together with explicitly copying what you want/need into an image delivers the best result. Using wildcard copies will end up in a mess.
