### ISSUE TITLE
doc-eventLoop

### ISSUE THREAD

**Issue by zzuligy** [nodejs/nodejs.org#1573]
* **URL**:https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/
* **Browser version**:
* **Operating system**:

the event loop graph is in the top down order,which make me confuse the poll phase.
if say poll phase like a moniter,which kick off the cycyle, loop and execute the callback in the phase may be most clear。

**Comment by zzuligy** [comment]
┌───────────────────────┐
                ┌─>│        timers         │
                │  └──────────┬────────────┘
                │  ┌──────────┴────────────┐
                │  │     I/O callbacks     │
                │  └──────────┬────────────┘
                │  ┌──────────┴────────────┐
                │  │     idle, prepare     │
             looper└──────────┬────────────┘
                │  ┌──────────┴────────────┐
                │  │        check          │
                │  └──────────┬────────────┘
                │  ┌──────────┴────────────┐
                └──┤    close callbacks    │
                   └───────────────────────┘

i think this is clear

**Comment by amandeepmittal** [comment]
@zzuligy But then where will you put the retrieval of I/O events?

**Comment by dmcghan** [comment]
I think the confusion comes from another part of the doc being wrong. In the [Phases Overview](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#phases-overview) section, the **I/O Callbacks** bullet states: 

> executes almost all callbacks with the exception of close callbacks, the ones scheduled by timers, and setImmediate().

However, in the [Phases Detail > I/O Callbacks](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#i-o-callbacks) section, the detail states:

> This phase executes callbacks for some system operations such as types of TCP errors.

Unless I'm misunderstanding something, it's the **poll** phase that "executes almost all callbacks with the exception of close callbacks, the ones scheduled by timers, and setImmediate()". 

This seems to be confirmed in the [libuv doc on the I/O loop](http://docs.libuv.org/en/v1.x/design.html#the-i-o-loop) which says this regarding the poll phase (#8 in the doc):

> All I/O related handles that were monitoring a given file descriptor for a read or write operation get their callbacks called at this point.

Perhaps the Node.js doc should change the phase names to be more in sync with the libuv doc.

- **I/O callbacks** could be renamed to "pending I/O callbacks"
- **poll** could be renamed to "poll for I/O"

So the **Phases Overview** would look more like this:

- **timers**: this phase executes callbacks scheduled by `setTimeout()` and `setInterval()`.
- **pending I/O callbacks**: executes I/O callbacks deferred to the next loop iteration.
- **idle**, prepare: only used internally.
- **poll for I/O**: retrieve new I/O events; execute I/O related callbacks (almost all with the exception of close callbacks, the ones scheduled by timers, and `setImmediate()`); node will block here when appropriate.
- **check**: `setImmediate()` callbacks are invoked here.
- **close callbacks**: e.g. `socket.on('close', ...)`.

**Comment by fhemberger** [comment]
@dmcghan Sounds good, would you mind creating a PR for it?

**Comment by amandeepmittal** [comment]
@dmcghan in `pending I/O callbacks` is it good to mention `process.nextTick()`?

**Comment by dmcghan** [comment]
@fhemberger Sure, will do.

@amandeepmittal I don't think so. [`process.nextTick()`](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#process-nexttick) gets it's own section in the doc because it's technically not part of the event loop. It has its own queue that is processed after each phase.

**Comment by dmcghan** [comment]
I created PR https://github.com/nodejs/nodejs.org/pull/1603. I simplified "pending I/O callbacks" to "pending callbacks" and left the name of the "poll" phase alone since it was referred to in other places.

**Comment by ghost** [comment]
Since PR #1603 is submitted now, so this issue should be over here. I'm closing it.
Thanks @dmcghan.
