### ISSUE TITLE
No documentation for installing with a package manager

### ISSUE THREAD

**Issue by Morgul** [nodejs/nodejs.org#158]
There used to be a nice page with instructions for installing Node with a package manager, but those docs were lost in the conversion to the new node site.

Can we please get those docs added back?

**Comment by Morgul** [comment]
For those looking for the documentation (on Ubuntu, at least), it's here: https://github.com/nodesource/distributions#installation-instructions

**Comment by fhemberger** [comment]
Hmm, these instructions were not part of the old nodejs.org website, but it's a good idea to add them.

EDIT: Ha, found them:
https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager, also
https://github.com/nodesource/distributions/blob/master/README.md

**Comment by Morgul** [comment]
@fhemberger Glad it's back. Two issues, however:
- the 'Other Downloads' link on the main node page (under the green download button) does not take you to the same page as the 'Downloads' link at the top of the page, which makes finding these instructions difficult.
- these instructions reference `v0.12`, not `v4.0.0`.

**Comment by fhemberger** [comment]
Thanks, things are pointing now to `v4.0.0`.
