### ISSUE TITLE
Add new contributors (March 2018)

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs.org#1582]
```
nodejs/nodejs.org committers since 2017-09-10, which aren't contributors yet:

* alexdunne (Alex Dunne)
* rbnswartz (Reuben Swartz)
* uyu423 (Yu Yongwoo / CX)
* oncletom (Thomas Parisot)
* petershank (Peter Shank)
* eugeneo (Eugene Ostroukhov)
* WaleedAshraf (Waleed Ashraf)
* cheruvian (null)
* AyushG3112 (Ayush Gupta)
* ouadie-lahdioui (Ouadie Lahdioui)
* code-chris (Christian Kotzbauer)
* jedsmith (Jed Smith)
* naskapal (Rizky Agung Saputro)
* QC-L (QiChang Li)
* Tsuna-mi (Ana Gamito)
* davisjam (Jamie Davis)
* davidfekke (David Fekke)
* amiller-gh (Adam Miller)
* jugglinmike ()
* ajmeese7 (Aaron Meese)
* watson (Thomas Watson)
* bneevan (naveen)
* Megajin (Güney Özdemir)
* bnoordhuis (Ben Noordhuis)
* jbottigliero (Joe Bottigliero)
* yuryu (Emma Haruka Iwao)
* maclover7 (Jon Moss)
* marswong (Mars Wong)
* allevo (Tommaso Allevi)
* rgbkrk (Kyle Kelley)
* bdharrington7 (Brian Harrington)
* ctsuei (Christine Tsuei Hong)
* Webysther (Webysther Nunes)
```

@bnb @Trott @MylesBorins: Could one of you please add them?

**Comment by Trott** [comment]
@fhemberger You are a Maintainer of the website team so you should be able to add them yourself. Can you try? Go to https://github.com/orgs/nodejs/teams/website/members and click the green "Add a member" button near the top right.

**Comment by fhemberger** [comment]
@trott Unfortunately, the Maintainer role is not enough. I can change people's role or remove them from the team, but not add them in the first place. 🤷‍♂️ 


![bildschirmfoto 2018-03-08 um 05 45 47](https://user-images.githubusercontent.com/153481/37133520-18a9df36-2294-11e8-8fd3-a224c85f2997.png)

**Comment by Trott** [comment]
Ah, so you can add people to the team if and only if they are already members of the org. So you should be able to add eugeneo and bnoordhuis, for example. But most of the people on that list are not in the org.

**Comment by Trott** [comment]
(Adding people right now, by the way. So eugeneo and bnoordhuis may be added by the time you get around to trying.)

**Comment by Trott** [comment]
Added everyone. For folks not currently in the org, it sends an invitation. So there are 28 pending invitations right now.

**Comment by Trott** [comment]
I *think* this can be closed. If I'm wrong, re-open! :-D

**Comment by fhemberger** [comment]
Awesome, thank you! 👍

**Comment by WaleedAshraf** [comment]
Thanks, @Trott  @fhemberger 
Looking forward to making more contributions to Node.js and its WGs.

**Comment by Trott** [comment]
One of the invitees reached out via email to ask what the invitation to join the org is all about. For notification purposes, I'm @-mentioning folks here, so they'll see this issue

* @alexdunne (Alex Dunne)
* @rbnswartz (Reuben Swartz)
* @uyu423 (Yu Yongwoo / CX)
* @oncletom (Thomas Parisot)
* @petershank (Peter Shank)
* @eugeneo (Eugene Ostroukhov)
* @WaleedAshraf (Waleed Ashraf)
* @cheruvian (null)
* @AyushG3112 (Ayush Gupta)
* @ouadie-lahdioui (Ouadie Lahdioui)
* @code-chris (Christian Kotzbauer)
* @jedsmith (Jed Smith)
* @naskapal (Rizky Agung Saputro)
* @QC-L (QiChang Li)
* @Tsuna-mi (Ana Gamito)
* @davisjam (Jamie Davis)
* @davidfekke (David Fekke)
* @amiller-gh (Adam Miller)
* @jugglinmike ()
* @ajmeese7 (Aaron Meese)
* @watson (Thomas Watson)
* @bneevan (naveen)
* @Megajin (Güney Özdemir)
* @bnoordhuis (Ben Noordhuis)
* @jbottigliero (Joe Bottigliero)
* @yuryu (Emma Haruka Iwao)
* @maclover7 (Jon Moss)
* @marswong (Mars Wong)
* @allevo (Tommaso Allevi)
* @rgbkrk (Kyle Kelley)
* @bdharrington7 (Brian Harrington)
* @ctsuei (Christine Tsuei Hong)
* @Webysther (Webysther Nunes)
