### ISSUE TITLE
doc-http

### ISSUE THREAD

**Issue by beglex** [nodejs/nodejs.org#1593]
* **URL**: http://nodejs.org/dist/latest/docs/api/http.html#http_event_connect
* **Browser version**: Any
* **Operating system**: Any

Event: 'connect'
response <http.IncomingMessage>

I think there shoud be li with text 'request <http.IncomingMessage>'

**Comment by amandeepmittal** [comment]
Can you be more specific? Are you talking about that in the source code of the document, there should be an `<li>` element?

**Comment by beglex** [comment]
Nope, I mean should there be text 'request <http.IncomingMessage>' rather than 'response <http.IncomingMessage>' in the li element?

**Comment by amandeepmittal** [comment]
I think it refers to the class `http.IncomingMessage` which has access to response status, headers and data.

See [here](http://nodejs.org/dist/latest/docs/api/http.html#http_class_http_incomingmessage)

**Comment by beglex** [comment]
Ah, okay. My bad then, sorry
