### ISSUE TITLE
More user friendly stream docs

### ISSUE THREAD

**Issue by wuweiweiwu** [nodejs/nodejs.org#1595]
Originally from: https://github.com/nodejs/node/pull/19143 to resolve https://github.com/nodejs/node/issues/8646

Creating a new guide to introduce users to streams with examples.

**Comment by tniessen** [comment]
cc @nodejs/documentation

**Comment by fhemberger** [comment]
Is there anything to be done here? Has the change landed in the docs?

**Comment by fhemberger** [comment]
Closing this for now due to inactivity. We're still happy to accept a PR for stream related guides or documentation updates.
