### ISSUE TITLE
node.foundation / nodejs.foundation

### ISSUE THREAD

**Issue by indexzero** [nodejs/nodejs.org#16]
I bought these domains ages ago. If we'd like to use them I'm happy to transfer them over. Wanted to get the discussion started about stand-alone foundation website vs. foundation as a page on the new Node.js website. 

In either case I think the `.foundation` gTLD is a bit fun. Even if they were just redirects to a page on another website.

**Comment by jasnell** [comment]
+1, it's a minor thing but worthwhile. The person to contact would be @mkdolan

**Comment by bnb** [comment]
+1. As @jasnell it's small but worth the extra work. What content would be appropriate here?

**Comment by snostorm** [comment]
I've liked the idea of a foundation specific site for a while. As we begin to redesign nodejs.org it might be worth considering going down that road as a potential option.

**Comment by fhemberger** [comment]
What would be the content of the foundation site that won't be available on the regular nodejs website?
(And I don't see cross posting as an option, more as a bad practice in this case.)

**Comment by mikeal** [comment]
Foundation site should have:

* the list of members
* membership agreement 
* bylaws
* list of projects and committees in the foundation
* IP agreement
* certificate of incorporation

**Comment by fhemberger** [comment]
Ok, it makes sense to have those things on a separate domain (also foundation related blog posts). Also  people editing those kind of documents may be a different subset than the folks working regularly on  new.nodejs.org.

**Comment by mikeal** [comment]
We have a page for this now, we can just forward to it via these other domains but we should create a seperate issue for that.
