### ISSUE TITLE
Subscription not allowed

### ISSUE THREAD

**Issue by thenishchalraj** [nodejs/nodejs.org#1602]
* **URL**: https://foundation.nodejs.org/
* **Browser version**: Firefox quantum 58.0.1
* **Operating system**: Kali linux

Seems the subscribe button does not really do anything. I was eager to subscribe to the newsletter but found that the button doesn't work.
On viewing the page source, it seems that the form is invalid. And a message in comment is there about the same I think.

![screenshot from 2018-03-25 17-37-14](https://user-images.githubusercontent.com/15857220/37874805-d8a8b4ac-3053-11e8-93d1-1d13a746f23b.png)
![screenshot from 2018-03-25 17-38-02](https://user-images.githubusercontent.com/15857220/37874806-d8eacc98-3053-11e8-9939-a0cb33a63be1.png)

**Comment by WaleedAshraf** [comment]
I think foundation.nodejs.org comes from some repo in https://github.com/linuxfoundation
Not able to find any related repo here in Node.js.

**Comment by fhemberger** [comment]
I don't think there's a foundation website repo at the moment, however, the page is not administrated by the folks around here.

@gtewallace Can you please look into it?

**Comment by shawnpreissner** [comment]
Hi @nishchalraj @WaleedAshraf @fhemberger  - thanks for raising, we'll get resolved ASAP and report back.

**Comment by shawnpreissner** [comment]
This is now resolved, please find the working form on the homepage -> https://foundation.nodejs.org/ 
@nishchalraj @WaleedAshraf @fhemberger

**Comment by WaleedAshraf** [comment]
@shawnpreissner awesome! Just tested it. 👍 🎉
