### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by francoFerraguti** [nodejs/nodejs.org#1608]
* **URL**: https://nodejs.org/es/download/current/
* **Browser version**: Chrome 63.0.3239.132 (64-bit)
* **Operating system**: Windows 8 64-bit

I've found some issues with the spanish translation:
 -Instead of **Firmas SHASUMS de los arvhivos de versiones**, it should be **Firmas SHASUMS de los archivos de versiones**
 -Instead of **Building Node.js from source on supported platforms**, it should be **Compilando Node.js del código fuente en las plataformas soportadas**

**Comment by thenishchalraj** [comment]
:1st_place_medal:  This was amazing man.

**Comment by vrunoa** [comment]
@francoFerraguti wouldnt it be better:
`Compilando Node.js desde el código fuente en las plataformas soportadas`
than
`Compilando Node.js del código fuente en las plataformas soportadas`

**Comment by a0viedo** [comment]
> @francoFerraguti wouldnt it be better:
Compilando Node.js desde el código fuente en las plataformas soportadas

:+1:

**Comment by fhemberger** [comment]
Could someone please submit a PR for the change?

**Comment by ghost** [comment]
PR is merged, feel free to reopen if needed.

**Comment by pin3da** [comment]
I added the missing translation in #1642, but in the page, the content is still in English. I only changed the content in a markdown file, do I need to do something else?

Thanks (:

**Comment by fhemberger** [comment]
@pin3da Maybe it's a caching issue on your side, the translation is online:

![bildschirmfoto 2018-05-07 um 05 55 21](https://user-images.githubusercontent.com/153481/39684319-514bd366-51bb-11e8-9276-e08131054bd9.png)

**Comment by pin3da** [comment]
@fhemberger I just noted that the translation was missing in "index.md" too. I submitted a PR for that: #1646
