### ISSUE TITLE
Duplicate inspector docs

### ISSUE THREAD

**Issue by ofrobots** [nodejs/nodejs.org#1609]
We seem to have two docs:

* https://github.com/nodejs/nodejs.org/blob/master/locale/en/docs/inspector.md
* https://github.com/nodejs/nodejs.org/blob/master/locale/en/docs/guides/debugging-getting-started.md

They have overlapping content. Which should be the canonical? Can we redirect from one to the other?

I need to add some more details about security implications of the Inspector, and I would like to to that in one place.

**Comment by marswong** [comment]
@fhemberger maybe [Inspector](https://nodejs.org/en/docs/inspector/) can be merged into [Debugging Guide](https://nodejs.org/en/docs/guides/debugging-getting-started/)?

**Comment by fhemberger** [comment]
Just submitted a PR (#1610), please review.

Removed `inspector.md` in favor of the Debugging Guide, still needs a redirect (will create one in afterwards).
