### ISSUE TITLE
build script: generate unexpected hyperlink for fullwidth comma

### ISSUE THREAD

**Issue by marswong** [nodejs/nodejs.org#1612]
When translating the docs, we need to use other input source, at present the script seems to mark the end of hyperlink with `halfwidth comma`, but if we use a `fullwidth comma` it would generate unexpected hyperlink, for example:

```
// generate expected "http://localhost:3000"
visit http://localhost:3000, and you will see a message 'Hello World'

// generate unexpected "http://localhost:3000，xxx"
visit http://localhost:3000，and you will see a message 'Hello World'
```

**Comment by ghost** [comment]
@marswong：This has been fixed at #1943，and the result seems fine by using "<>" to quote the link——
![image](https://user-images.githubusercontent.com/40081831/50060889-1ac09000-01d5-11e9-840a-50b5ae74f506.png)

**Comment by stevemao** [comment]
It should be fixed at the parser level so that you don't need to wrap the link with "<>"

**Comment by ghost** [comment]
@stevemao ：OK. But this is a temporary fix :)

**Comment by ghost** [comment]
@marswong , @stevemao , @fhemberger ：I don't know when and how to fix this parse. But for a temporary fix, I submitted this and if this parser is fixed, I'll change back.

Thanks all!!!

**Comment by UziTech** [comment]
I think the only way to prevent a full-width comma from being part of the url is to surround the urls with `<>` or add a space before the comma

**Comment by XhmikosR** [comment]
@Trott this no longer happens

**Comment by XhmikosR** [comment]
Agreed, the only proper solution would be to disallow GitHub flavored links and require all of them to be wrapped in `<>`. But it's not a simple change, there's so much old content and inconsistencies.

For starters, we should check how is this addressed upstream in core. Then we need to verify the release post template and tools follow this scheme, enable the check in the markdown linter and have some kind of basic link checker set up.

**Comment by ovflowd** [comment]
Closing as the legacy build script is not used anymore.
