### ISSUE TITLE
Inspector docs broken link

### ISSUE THREAD

**Issue by zackurben** [nodejs/nodejs.org#1614]
* **URL**: https://nodejs.org/en/docs/inspector/guides/debugging-getting-started/
* **Browser version**: 
  1. FireFox 58.0.2 (64-bit) (Ubuntu)
  2. Chrome Version 65.0.3325.181 (Official Build) (32-bit) (Win)
* **Operating system**:
  1. Ubuntu 16.04.03
  2. Win 7 

Hello,

[the inspector page](https://nodejs.org/en/docs/inspector/) has a link to a moved page (Guides: Debugging - Getting Started) which 404s.

Broken page: https://nodejs.org/en/docs/inspector/guides/debugging-getting-started/
Correct page: https://nodejs.org/en/docs/guides/debugging-getting-started/

```
404: Page could not be found
ENOENT: no such file or directory
```

I went to fix it myself, but it works locally on my fork. I see there was just some activity with https://github.com/nodejs/nodejs.org/pull/1610, so is this possibly a build issue or has the build not occurred yet?

Cheers!

**Comment by marswong** [comment]
@fhemberger it seems the link should be `../guides/debugging-getting-started/`

**Comment by fhemberger** [comment]
Thanks, fixed!

**Comment by zackurben** [comment]
Great, thanks for the quick turnaround!
