### ISSUE TITLE
Not working redirect from https://nodejs.org/en/docs/inspector page.

### ISSUE THREAD

**Issue by n-filatov** [nodejs/nodejs.org#1619]
* **URL**: https://nodejs.org/en/docs/inspector
* **Browser version**: Google Chrome 65
* **Operating system**: MacOS

When i follow link https://nodejs.org/en/docs/inspector  i get 404 error. But when i follow link https://nodejs.org/en/docs/inspector/ i get redirect on https://nodejs.org/en/docs/guides/debugging-getting-started/ page.

**Comment by fhemberger** [comment]
Where did you find the first link without the trailing slash? This is indeed wrong (thus the 404) and the redirect was introduced in #1610. So everything works as intended.

**Comment by n-filatov** [comment]
I found this link in message when executed `node --inspect index.js`.

**Comment by ckotzbauer** [comment]
Found it: https://github.com/nodejs/node/blob/master/src/inspector_socket_server.cc#L108

**Comment by n-filatov** [comment]
Yep, i have crated pull request in node repo to fix this url, also think that getting 404 error when u follow link without trailing slash may be confuse somebody.

**Comment by fhemberger** [comment]
Awesome, thanks. I will also fix the redirect - just in case.

**Comment by fhemberger** [comment]
Redirect is fixed, closing.
