### ISSUE TITLE
feature request: search functionality in docs

### ISSUE THREAD

**Issue by Almenon** [nodejs/nodejs.org#1620]
I'm very suprised there is not search functionality in the node docs.  This would be a great addition to the docs and make it easier to navigate inside them.

Current workarounds are google or [all page](https://nodejs.org/api/all.html) but they are not quite as convenient.

See https://github.com/nodejs/node/issues/19873

**Comment by thom4parisot** [comment]
Maybe something to consider: https://community.algolia.com/docsearch/

**Comment by Almenon** [comment]
looks like the docs are actually maintained in the other repo - closing
