### ISSUE TITLE
request: add appropriate documentation/links to the SHASUMS listing

### ISSUE THREAD

**Issue by ryzokuken** [nodejs/nodejs.org#1621]
Recently, @marxsal submitted the issue https://github.com/nodejs/help/issues/1203, where they seemed to be confused about verifying the node binaries.

I suggested them to look into https://github.com/nodejs/node#verifying-binaries which resolved their query.
Should we add a subset of this documentation on the website itself? The least we could do would be to add a link to this section of the README in there somewhere.

**Comment by fhemberger** [comment]
I think a link would be a good idea right next to the SHASUM link. Example:

[Signed SHASUMS for release files]() ([How to verify]())

Would you like to create a PR for this?

**Comment by ryzokuken** [comment]
@fhemberger I'd love to!
