### ISSUE TITLE
Displaying Node.js 4 EOL on Homepage of the website

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs.org#1628]
This is a bit more of a communication item vs. technical item on the website, but with Node.js 4 going into EOL at the end of the month, I thought it would be good to have a little banner on the homepage so folks are aware that this is going to happen. Similar to what we have re: the March 2018 security upgrades.  

@MylesBorins is going to draft a quick blog that explains Node.js 4 EOL status and Node.js 6 maintenance status via a blog post that we can link to on the homepage or we could just have content that states "Important: Node.js v4 EOL on April 30, 2018; please upgrade" and link this to the release working group repo. 

The website gets a ton of users per month, so I think we should 100% have something on it that discusses this along with all the social content that we are working on here (i.e. posting on Twitter and on nodejs.org blog + Node.js Foundation Medium blog).

Let me know what this group thinks. cc'ing: @bnb @Fishrock123 @fhemberger

**Comment by mhdawson** [comment]
+1 very good idea to highlight it there.

**Comment by bnb** [comment]
@ZibbyKeaton sounds good to me, +1. Been trying to help with this as much as possible from the NodeSource social accounts, as it is relatively important.

@MylesBorins I'm curious what your suggestion on an upgrade path will be in the article - I'd assume the suggestion will be 4 -> 8? 🤔

**Comment by WaleedAshraf** [comment]
SGTM.
We upgraded from 4 -> 8 a few months ago and the only thing we were worried about was any major breaking change.
It'd be good if we can include a list of known major breaking changes in that blog? Most of it is already in CHANGELOG.md but that has a lot of other stuff too.

**Comment by ZibbyKeaton** [comment]
@WaleedAshraf what do you think of a blog post for Node.js Collection on that topic? Or do you have a link to the changelog that I can include in our blog? I posted the blog on Monday: https://medium.com/@nodejs/april-2018-release-updates-from-the-node-js-project-71687e1f7742

Also, what are the next best steps here to get this added to the homepage?

**Comment by WaleedAshraf** [comment]
@ZibbyKeaton 
There are 4 major changelogs, which everyone should check before upgrading the version.

6.0.0: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.0.0
8.0.0: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.0.0
9.0.0: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V9.md#9.0.0
10.0.0: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.0.0

I can create a gist with all these in one file and attach that to medium post. I think this would be helpful for anyone planning to upgrade.

**Comment by ZibbyKeaton** [comment]
Sounds good to me @MylesBorins are you okay with this as well?

**Comment by fhemberger** [comment]
As soon as we have a final link and a label for it, we can add it in a similar way to the important security updates on the homepage.

**Comment by ZibbyKeaton** [comment]
@fhemberger can we use this link: https://medium.com/@nodejs/april-2018-release-updates-from-the-node-js-project-71687e1f7742 ? In terms of table, it could read something like April Release Updates (Please Read). Let me know if that works or if I'm way off here.

**Comment by fhemberger** [comment]
@ZibbyKeaton I'll prepare a PR later …

**Comment by fhemberger** [comment]
PR: #1636

**Comment by fhemberger** [comment]
Merged with `2e8c943`
