### ISSUE TITLE
On download page, define LTS

### ISSUE THREAD

**Issue by loriF** [nodejs/nodejs.org#1643]
* **URL**:
* **Browser version**:
* **Operating system**:

Please add the definition "(Long Term Support)" after LTS, on the download page. A student developer accidentally downloaded the latest version instead of the LTS version, because they didn't understand what LTS meant. The current text alone "Recommended for most users" doesn't indicate why it's recommended.

**Comment by ghost** [comment]
I think 'Recommended For Most Users' should stay where it is, and if we add Long Term Support below, it will consume too much space and buttons won't look symmetric.
But I think we could change LTS schedule below into Long Term Support schedule, something like this:
![image](https://user-images.githubusercontent.com/13847095/39545833-ab9ed302-4e52-11e8-8144-2d715fe27c68.png)

**Comment by loriF** [comment]
I like that, with a slight mod so the acronym is provided explicitly with the text below the buttons: 
"Or have a look at the Long Term Support (LTS) schedule".

**Comment by ghost** [comment]
LGTM
