### ISSUE TITLE
Downloading Node.JS 10.0.0 for Linux on nodejs.org returns 404

### ISSUE THREAD

**Issue by BlueSlimee** [nodejs/nodejs.org#1645]
* **URL**: https://nodejs.org/dist/v10.0.0/node-v10.0.0-linux-x86.tar.xz
* **Browser version**: Chrome Beta 67.0.3396.29
* **Operating system**: Android

When you enter on https://nodejs.org/dist/v10.0.0/node-v10.0.0-linux-x86.tar.xz you get a 404 error.

**Comment by vsemozhetbyt** [comment]
See https://github.com/nodejs/node/issues/20416
