### ISSUE TITLE
version 10.x do not provide linux-x86 binary download?

### ISSUE THREAD

**Issue by bertlea** [nodejs/nodejs.org#1649]
Cannot find the linux-x86 binary download for version 10.   No longer supported?

**Comment by mhdawson** [comment]
See the discussion here: https://github.com/nodejs/build/issues/885

The short answer is that 32 bit was dropped for Node 10.

**Comment by bertlea** [comment]
@mhdawson Thank you for the confirmation.  It is a pity, because I am using Raspberry Pi Desktop (Debian) which only offers 32-bit version.
