### ISSUE TITLE
List N-API version in index.tab and on the release overview page

### ISSUE THREAD

**Issue by kkaefer** [nodejs/nodejs.org#1653]
The overview page at https://nodejs.org/en/download/releases/ and the parseable index at https://nodejs.org/dist/index.tab currently list the ABI version. However, they don't yet list the N-API version. While that version hopefully won't change anytime soon, it'd be cool to have it there in order to future-proof N-API modules and build scripts.

**Comment by mhdawson** [comment]
We'll have to think about what it would make sense to report.  We do have a number that we increase when methods are added, but version X is still compatible with version Y provided that X>=Y

**Comment by kkaefer** [comment]
Yeah... I tried to figure out what the difference between `NAPI_VERSION` and `NAPI_MODULE_VERSION` is, but was unable to understand that the difference between those is.

**Comment by Trott** [comment]
@nodejs/n-api Any thoughts on this? This has been inactive for over a year. It would be good to get consensus on whether or not this should be done.

**Comment by ovflowd** [comment]
Closing as obsolete. It might still be relevant, but it's been a long while since anyone gave a link into this.
