### ISSUE TITLE
Add Annual Survey Web Report

### ISSUE THREAD

**Issue by gtewallace** [nodejs/nodejs.org#1654]
* **URL**:
* **Browser version**:
* **Operating system**:

Hi all,

The Node Foundation has created an HTML version of the Annual Node.js User Survey report and we'd like to host it here.

We think it makes sense since we will also make the data (PII removed) available for download for others in the community to perform their own analysis. We also have some nice executive summary powerpoint slides we can place here for others to use.

There's one aspect of the report that needs to be updated - we have a click to tweet button under every chart and we'd need to update the URL path in the tweets to match the eventual path of the report here on github.

Our goal is to have the report go live on May 31.

I look forward to everyone's thoughts.

Thanks!

**Comment by bnb** [comment]
@gtewallace if there's a standalone HTML version of the report, it hopefully shouldn't be too difficult PR it into this repository and get it published on the site.

@fhemberger @mhdawson @MylesBorins do y'all think we could help @gtewallace with this?

**Comment by gtewallace** [comment]
thanks @bnb 

It's self contained - I have already tested publishing it as a GHP - we had it up in a matter of minutes in a test repo. That gives me confidence it *should* be relatively straightforward.

@fhemberger @mhdawson @MylesBorins I look forward to your thoughts.

Greg

**Comment by mhdawson** [comment]
+1 from me.  @fhemberger any concerns?

**Comment by fhemberger** [comment]
No, we could add all the html under `/user-survey-report` (=`locale/en/user-survey-report` in this repo.

@gtewallace Are you fine with submitting a Pull Request? Otherwise just send me a mail with the zipped report files, and I'll add it to the website.

**Comment by gtewallace** [comment]
great news! thanks all!

@fhemberger  Just to confirm, the path will be: https://nodejs.org/en/user-survey-report

Is that right?

If so, my colleague @alexcontini will update the HTML file with the new path and I will open a PR with all the assets.

Thanks again!

Greg

**Comment by fhemberger** [comment]
We might need to adjust the HTML a bit to fit into the website design properly, but we can help you with that once you've submitted the PR.

**Comment by gtewallace** [comment]
@fhemberger awesome - that would be great. Can we keep the page private or unpublished until May 31? 

@alexcontini - can you please go ahead and update the links in the tweet buttons with this path: https://nodejs.org/en/user-survey-report

 Then I'll open the PR. 

Thanks!

Greg

**Comment by fhemberger** [comment]
@gtewallace What's in the GitHub repo is public. But if @alexcontini prepares everything locally and submits the PR on 31st, we're good.

**Comment by mhdawson** [comment]
@fhemberger would it make sense to add the year to the path?  ie something like /user-survey-report-2018, with possibly the link /user-survey-report pointing to the latest version.  I expect that we'll be adding one each year going forward.

**Comment by bnb** [comment]
@mhdawson this is what we did for [Node by Numbers](https://nodesource.com/node-by-numbers) at NodeSource, and it does indeed seem to be the best path.

**Comment by bnb** [comment]
correction: We did routing on sub-paths. So /node-by-numbers and /node-by-numbers/2016

**Comment by gtewallace** [comment]
@fhemberger Hi!

On second thought, is it ok if I give you a zip with all the web report assets? 

LMK if that's OK and what's the best way.

Thanks!!

**Comment by fhemberger** [comment]
@gtewallace I'll have a look at it and get back to you.

**Comment by gtewallace** [comment]
Sounds good, thanks!

**Comment by gtewallace** [comment]
Hi everyone!! Is it possible to get the GA code added to the survey page/pages? 

thanks again!

Greg

**Comment by fhemberger** [comment]
@gtewallace Sure: https://github.com/nodejs/nodejs.org/pull/1688
