### ISSUE TITLE
Missing link for Node 6.x EN docs in Previous Releases

### ISSUE THREAD

**Issue by MikeyBurkman** [nodejs/nodejs.org#1656]
URL: https://nodejs.org/en/docs/
Problem: It has links for all previous versions, except for Node 6 for some reason.

Looks like we could just add the link to the 6.x docs here:
https://github.com/nodejs/nodejs.org/blob/master/locale/en/docs/index.md#looking-for-api-docs-of-previous-releases
The 6.x docs do exist: https://nodejs.org/docs/latest-v6.x/api/

I can write a PR for this, just wanted to check first to see if there was maybe a reason for this missing link, or if it was just an oversight.

**Comment by WaleedAshraf** [comment]
@MikeyBurkman 
Good catch. I'm not sure if it's missing for reason but we can add it.
9.x is also missing: https://nodejs.org/docs/latest-v9.x/api/

I see, 8.11.2 (LTS) and 10.1.0 (Latest) are available through side nav. So we don't need to add those.
