### ISSUE TITLE
Possible inclusion of "Priority Document" on the website

### ISSUE THREAD

**Issue by detrohutt** [nodejs/nodejs.org#1659]
There's an initiative for a priority/wishlist document I'm trying to get going with the help of @mhdawson and we're hoping for some input on whether the website may be the appropriate location for such a document.

I outlined my initial vision of the document in [nodejs/mentorship #38](https://github.com/nodejs/mentorship/issues/38) and have had further discussions to refine the idea in some meetings with WG's and individuals.

The short version of our current idea is a "Wishlist" document where WG's/Strategic Initiatives could request to have items added that they would like worked on but don't currently have the resources to implement. Existing contributors, newcomers through the upcoming nodejs/mentorship program, etc. could then be directed to this document and if they find any of the items of interest, they can volunteer to help out on those items. So it's kind of a way to direct volunteers to specific areas of need which both interest them and would be especially useful to the ecosystem.

Does this seem like something that could live on the nodejs.org website?

**Comment by ovflowd** [comment]
Closing as this is obsolete.
