### ISSUE TITLE
Download for Mac OS X 64 not working

### ISSUE THREAD

**Issue by hyun3010** [nodejs/nodejs.org#166]
The download button on the Nodejs website (https://nodejs.org/en/) is not working. It leads to a 404 Page could not be found error. I do not know if this is only for Macs, or for other computers.

**Comment by rvagg** [comment]
working on it, the new site thinks 4.0.0 is the latest but it's atually 4.1.0, it'll be fixed in a minute

**Comment by rvagg** [comment]
fixed
