### ISSUE TITLE
&& displayed as &amp;&amp;

### ISSUE THREAD

**Issue by 0mp** [nodejs/nodejs.org#1660]
* **URL**: 
 * en: https://nodejs.org/en/download/package-manager/#freebsd
 * uk: https://nodejs.org/uk/download/package-manager/#freebsd

I guess that it could be caused by the fact that those code blocks use sh instead of bash for syntax coloring.

**Comment by WaleedAshraf** [comment]
Yes, I think it's happening when website applies styling on GitHub markdown file.
Are you going to open a PR?
