### ISSUE TITLE
NPM version in Latest Current Version

### ISSUE THREAD

**Issue by NekoGuy** [nodejs/nodejs.org#1665]
* **URL**: https://nodejs.org/en/download/current/
* **Browser version**: Google Chrome x64 v67
* **Operating system**: Windows 10 x64

At the top of the download page is written that "Latest Current Version: 10.2.1 (includes npm 5.6.0)" but when I installed it and used command "npm version" it says:
{ npm: **'6.1.0'**,
  ares: '1.14.0',
  cldr: '33.0',
  http_parser: '2.8.0',
  icu: '61.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.29.0',
  node: '10.2.1',
  openssl: '1.1.0h',
  tz: '2018c',
  unicode: '10.0',
  uv: '1.20.3',
  v8: '6.6.346.32-node.8',
  zlib: '1.2.11' }

**Comment by ghost** [comment]
This also happens in the LTS version:

![errorversion](https://user-images.githubusercontent.com/40081831/43988109-1e86db46-9d61-11e8-874c-48e71e0c164d.PNG)

And actually it is:
![errorversion2](https://user-images.githubusercontent.com/40081831/43988114-424bd554-9d61-11e8-9c6e-20166c9703b8.PNG)

**Comment by MylesBorins** [comment]
Can you run `which npm`?

The 8.x line currently still ships with npm 5.6.0

Perhaps you installed a more recent version on your system?

**Comment by ghost** [comment]
No. I've just installed node (if you see my screenshot above, it's 8.11.3).

Here's the screenshot of my control panel: 

![cpd](https://user-images.githubusercontent.com/40081831/43988886-95f88106-9d71-11e8-9110-489aa481a3e1.PNG)

And there's only one Node on my PC. My operation is Windows 8.1 (x86). So `which npm` may be Linux command?

PS：I just uninstalled and re-installed it, but nope:(

**Comment by ghost** [comment]
I did some experiments on Nodejs 10.8.0, there still exists the problem?

The step is:
Uninstalled Nodejs 8.11.3, and then installed the 10.8.0 (it SHOULD include npm 6.2.0). 

Now the result is:
![cpd](https://user-images.githubusercontent.com/40081831/43988961-a1ee8efe-9d73-11e8-9e07-2b68dea6f5a6.PNG)

**Comment by MylesBorins** [comment]
This seems like it is likely something with your system

Here is where the npm package.json is in the 10.8.0 release, as you can see it is explicitly 6.2.0. We never shipped 6.1.0

https://github.com/nodejs/node/blob/89f483b5c18590235ad55d55842b5a2a0c9fa89c/deps/npm/package.json#L2

Here is fresh install of v10.8.0 on my system where you can clearly see it ships with 6.2.0

<img width="672" alt="screen shot 2018-08-11 at 11 47 31 am" src="https://user-images.githubusercontent.com/498775/43993498-693ac45e-9d5c-11e8-8aae-ac10e35d629d.png">

edit: here is the link to the package.json is 8.11.3, where it can be seen that the npm being shipped is 5.6.0

https://github.com/nodejs/node/blob/90ada2627995cf1216366c94fb6c5fc472834954/deps/npm/package.json#L2

The fact that both versions on your system are using 6.1.0, a version of npm never shipped in a version of node, leads me to believe something on your system is causing this inconsistency

**Comment by Gerriko** [comment]
I'm also have an npm version issue. If I uninstall nodejs it correctly says that npm does not exist. If I then install the latest nodejs it keeps the npm version at 5.4.1. How do I resolve this?

**Comment by LinusU** [comment]
> If I uninstall nodejs it correctly says that npm does not exist.

Npm needs Node.js to run, are you sure that the error isn't that `node` doesn't exist? 🤔

**Comment by Gerriko** [comment]
> Npm needs Node.js to run, are you sure that the error isn't that node doesn't exist? 🤔

LOL. That is a valid observation.
