### ISSUE TITLE
doc: backpressuring in streams guide

### ISSUE THREAD

**Issue by Bamieh** [nodejs/nodejs.org#1668]
In the [backpressuring-in-streams](https://github.com/nodejs/nodejs.org/blob/master/locale/en/docs/guides/backpressuring-in-streams.md#the-problem-with-data-handling) guide, this line of text should be updated:

> [pump](https://github.com/mafintosh/pump) is a utility tool that would properly destroy all the streams in a pipeline if one of them fails or closes, and is a must have in this case!

As of node 10, [pipeline](https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback) is introduced to solve this issue, so there is no need to reference an external utility any more 🎉 . I believe the guide should reflect on this new feature providing a small code snippet along with a link to the docs.

```
const pipeline = util.promisify(stream.pipeline);

async function run() {
  await pipeline(
    fs.createReadStream('archive.tar'),
    zlib.createGzip(),
    fs.createWriteStream('archive.tar.gz')
  );
  console.log('Pipeline succeeded');
}
```

I am willing to submit a PR if I am on the right track.

Cheers!

**Comment by ghost** [comment]
@Bamieh：Thanks and I've included the submit. Feel free to submit your ideas.
