### ISSUE TITLE
Possible encoding issue on Node.js Survey mini-site

### ISSUE THREAD

**Issue by thom4parisot** [nodejs/nodejs.org#1671]
* **URL**: https://nodejs.org/en/user-survey-report/
* **Browser version**: Firefox
* **Operating system**: macOS

I noticed some glitchy characters at the very beginning of the survey homepage.

<img width="952" alt="image" src="https://user-images.githubusercontent.com/138627/40773400-12f0c188-64c3-11e8-9c80-6f79ce48a40e.png">

**Comment by fhemberger** [comment]
Fixed in 092334ad89a97ea40d0721387aa4a270528dec44, thanks for noticing!
