### ISSUE TITLE
tabs not working on user-survey-report

### ISSUE THREAD

**Issue by WaleedAshraf** [nodejs/nodejs.org#1672]
tabs are not working on user-survey-report web page.

<img width="1049" alt="screen shot 2018-05-31 at 2 07 31 pm" src="https://user-images.githubusercontent.com/8335457/40773414-44248212-64dc-11e8-9529-9653e4858dc2.png">

* **URL**: https://nodejs.org/en/user-survey-report/#profile2
* **Browser version**: Chrome
* **Operating system**: macOS

cc: @gtewallace

**Comment by gtewallace** [comment]
thank you @WaleedAshraf 

I noticed this also, and the Correlated Technologies graph is also not showing for me.

cc @alexcontini

**Comment by WaleedAshraf** [comment]
Fixed by @fhemberger 👍  here: https://github.com/nodejs/nodejs.org/commit/a558c672300346a117b1be26d1acac5a6b5eb0cc
