### ISSUE TITLE
Website link for /security returns 404 

### ISSUE THREAD

**Issue by lirantal** [nodejs/nodejs.org#1677]
Browsing https://nodejs.org/security shows a 404 while an explicit forward slash visit to https://nodejs.org/security/ works fine.

Can we fix it?

* **URL**: https://nodejs.org/security
* **Browser version**: Chrome Version 66.0.3359.181
* **Operating system**: MacOS

**Comment by fhemberger** [comment]
So do all the pages, as they implicitly resolve to `/{path}/index.html`.

**Comment by lirantal** [comment]
Not exactly.
For example, these redirect fine to their actual pages:
* https://nodejs.org/about
* https://nodejs.org/blog

https://nodejs.org/security doesn't automatically redirect.

**Comment by drzippie** [comment]
The valid URL is https://nodejs.org/{lang_code}/security/   

https://nodejs.org/en/security/
https://nodejs.org/ja/security/
https://nodejs.org/es/security/

https://nodejs.org/security/ or https://nodejs.org/security  always returns 404

The last versión (development) works:

```
curl -I http://localhost:8080/security
```
HTTP/1.1 302 Found
**location: en/security**
Date: Mon, 09 Jul 2018 12:04:18 GMT
Connection: keep-alive

**Comment by lirantal** [comment]
Not sure if you are supporting the bug or not :-)

What I'm saying is, just like browsing `https://nodejs.org/about/` redirects to `https://nodejs.org/en/about/` I would expect the same behavior for the security resource

**Comment by fhemberger** [comment]
This dates back to the old Node.js website (before having multiple languages), therefore the redirects exist. But we could add them for all top level pages, just to be sure.

**Comment by pierreneter** [comment]
so, do we need to redirect for `/security`?

**Comment by fhemberger** [comment]
No, not really. `https://nodejs.org/security/` is not an official link, same as `https://nodejs.org/get-involved/`. So both are not redirected to `/en/`.

All other redirects only exist to cover the legacy version of `nodejs.org` and `iojs.org` (so everything before 2015).

Closing.
