### ISSUE TITLE
color for <code> inside <a> isn't readable when hovered

### ISSUE THREAD

**Issue by bogas04** [nodejs/nodejs.org#168]
Commit hexes [here](https://nodejs.org/en/blog/release/v4.1.0/) aren't readable
![screen shot 2015-09-17 at 10 38 51 pm](https://cloud.githubusercontent.com/assets/6177621/9940399/51178ffe-5d8d-11e5-9276-26f5b6fb053d.png)
We can fix it by 

``` css
a:hover 
    code
        color #CC2828
```

![screen shot 2015-09-17 at 10 40 31 pm](https://cloud.githubusercontent.com/assets/6177621/9940414/699a594e-5d8d-11e5-9069-843ad4949207.png)

**Comment by fhemberger** [comment]
Fixed in #170
