### ISSUE TITLE
[Localization] Wrong Chinese usage of `其他`

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#1685]
![wrongchinesecharacter](https://user-images.githubusercontent.com/40081831/41215061-0a88c5ba-6d81-11e8-8beb-1b3584a76da4.PNG)

On the [home page of Nodejs in Chinese](https://nodejs.org/zh-cn/), there's a wrong translation of '其他'. **We should use '其它'instead** because '它' means `things without lives`. Compared with this, "他" is `He ` in English, usually means some male person.

**Comment by fengmk2** [comment]
@Maledong welcome to help us fix it by a pr.

**Comment by ghost** [comment]
@fengmk2 ：
Yes. I tend to follow a strict workflow：
1）Create an issue first to report to all of you.
2）If you think necessary, I'll fix it when free. Otherwises close this.

**Comment by ghost** [comment]
@fhemberger ：
Any other plans to localize the other pages?
If you have such plans, you can make a report about your plans and I'll do that when free.

**Comment by laosb** [comment]
Surely we accept translation contributions for other pages! But before you contribute, I remembered there is already a pending PR doing this. Do you mind check it out?

**Comment by ghost** [comment]
@laosb ：Which PR？
It seems I didn't find that in the `Pull Requests` before submitting it...

**Comment by laosb** [comment]
@Malegong IIt seems that the author of #1590 is willing to translate all other pages. You can try contacting him. Thanks for being willing to contribute!

**Comment by ghost** [comment]
@laosb ：Thanks for guiding me and linking my change there. And there's no conflicts between his changes and mine. So maybe there's a merge.

**Comment by lepture** [comment]
「其他」并没有错，「它」是后来的“新造字”，用来指代 it，正如「她」也是新造字，用来指代 she。这就导致现代人认为「他」仅仅表示 he 了。

但是并不是这样的，「他」是泛用字，表示非第一人称非第二人称。正如我们不用「其她」，我们也不应该用「其它」，事实上「其它」是一种误用，没有所谓有生命没生命。

1. https://www.moedict.tw/%E5%85%B6%E4%BB%96

**Comment by lepture** [comment]
FYI: http://old.pep.com.cn/xiaoyu/jiaoshi/tbjx/xy_jcdy/xydy7/201008/t20100818_663715.htm
