### ISSUE TITLE
Duplicate latest version of RPM Repository for fc26 i386 

### ISSUE THREAD

**Issue by luminoso** [nodejs/nodejs.org#1687]
It looks like that Fedora 26 i386 repo has a duplicate entry for the lastest nodejs release.

This instructs wrongly the dnf to install an older version instead of the latest.

### A) Example for the f26 i386 repo
URL: https://rpm.nodesource.com/pub_8.x/fc/26/i386/

```
$ dnf repoquery  --repofrompath=nodee,https://rpm.nodesource.com/pub_8.x/fc/26/i386/ --repoid=nodee --latest 1
Added nodee repo from https://rpm.nodesource.com/pub_8.x/fc/26/i386/
Last metadata expiration check: 0:04:20 ago on seg 11 jun 2018 10:59:48 WEST.
nodejs-2:8.11.2-1nodesource.i386
nodejs-2:8.4.0-1nodesource.fc26.i686
nodejs-debuginfo-2:8.4.0-1nodesource.fc26.i686
nodejs-devel-2:8.11.2-1nodesource.i386
nodejs-devel-2:8.4.0-1nodesource.fc26.i686
nodejs-docs-2:8.11.2-1nodesource.noarch
```

DNF will try to install _nodejs-2:8.4.0-1nodesource.fc26.i686_ instead of _nodejs-2:8.11.2-1nodesource.i386_ . DNF installs 8.4.0 wrongly.

### B) Example for the f26 x86_64 repo
URL: https://rpm.nodesource.com/pub_8.x/fc/26/x86_64/

```
$ dnf repoquery  --repofrompath=nodee,https://rpm.nodesource.com/pub_8.x/fc/26/x86_64 --repoid=nodee --latest 1
Added nodee repo from https://rpm.nodesource.com/pub_8.x/fc/26/x86_64   
Last metadata expiration check: 0:00:00 ago on seg 11 jun 2018 11:16:22 WEST.
nodejs-2:8.11.2-1nodesource.x86_64
nodejs-debuginfo-2:8.4.0-1nodesource.fc26.x86_64
nodejs-devel-2:8.11.2-1nodesource.x86_64
nodejs-docs-2:8.11.2-1nodesource.noarch
nodesource-release-0:fc26-1.noarch
```
In this case, also for f26 but different architeture there is no confusion with nodejs release since there's only _nodejs-2:8.11.2-1nodesource.x86_64_ release. DNF installs version 8.11 correctly. 

Workaround is to instruct dnf f26 i386 to install a specific version (in this case 8.11) but I suppose that isn't suppose, since all other repos behave like example **B)**

**Comment by fhemberger** [comment]
Hi, the RPM repository is provided by NodeSource, not by the website team.

@bnb @rvagg Could you please look into it?

**Comment by bnb** [comment]
Reached out internally at NodeSource to @chrislea to see what the issue is 👍

**Comment by chrislea** [comment]
There's no version of the newest Node.js releases for FC26 in the NodeSource repositories, because FC26 is EOL, so we're not pushing anything new out for that distribution.

https://fedoraproject.org/wiki/End_of_life
