### ISSUE TITLE
checksums

### ISSUE THREAD

**Issue by dheles** [nodejs/nodejs.org#171]
Checksums listed on the v4.1.0 announcement page ( https://nodejs.org/en/blog/release/v4.1.0/ ) are listed as "Hash: SHA512" but are actually SHA256 ( as per https://nodejs.org/dist/v4.1.0/SHASUMS256.txt). Checking them as 512 yields a different result and thus, confusion.

**Comment by rvagg** [comment]
512 is the GPG signing hash, not the file hash

**Comment by fhemberger** [comment]
@rvagg As this is not the first time this question comes up, is there a way to express this better in the release post?

e.g:
Shasums (GPG signing hash: SHA512, file hash: SHA256):
(block of shasums)

**Comment by fhemberger** [comment]
Hijacking this issue: @phillipj, I'd like to make a little change to the release posts and script:

**Before**

![](https://cloud.githubusercontent.com/assets/153481/9952374/2acfdb10-5dd5-11e5-8a09-ca87d44e5d37.png)

**After**

![bildschirmfoto 2015-09-18 um 07 00 27](https://cloud.githubusercontent.com/assets/153481/9952377/337aa7f4-5dd5-11e5-9224-3ea3c1d3dd30.png)

**Comment by phillipj** [comment]
@fhemberger :+1:
