### ISSUE TITLE
Add new contributors (June 2018)

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs.org#1714]
```
nodejs/nodejs.org committers since 2018-03-06, which aren't contributors yet:

* osk2 (osk2)
* Maledong
* bjb568
* sonicdoe (Jakob Krigovsky)
* willin (Willin Wang)
* dca (Dca)
* expitly
* ErnestoSalazar
* 0mp (Mateusz Piotrowski)
* MikeyBurkman (Michael Burkman)
* mattc41190 (Matthew Cale)
* Neil188 (Neil Lupton)
* TheNuclearCat (Marc Maurer)
* dmcghan (Dan McGhan)
* drzippie (Antonio Cortes (DrZippie))
* pidofme (Mingyang Li)
* reedloden (Reed Loden)
* ryzokuken (Ujjwal Sharma)
* cassidyjames (Cassidy James Blaede)
* MarcinHoppe (Marcin Hoppe)
```

/cc @bnb @Trott @MylesBorins

**Comment by fhemberger** [comment]
Could one of the GitHub org owners please add the new contributors?
I don't have sufficient rights for this.

/cc @bnb @Trott @MylesBorins @Fishrock123 @mhdawson

**Comment by Trott** [comment]
> Could one of the GitHub org owners please add the new contributors?
> I don't have sufficient rights for this.
> 
> /cc @bnb @Trott @MylesBorins @Fishrock123 @mhdawson

Just in case anyone is wondering about the details here: While @fhemberger is a Maintainer for `@nodejs/website`, that only provides the permissions to add existing org members to the team. I'm guessing most or all of these folks are not org members (but they will be once they are added to the team!).

**Comment by Trott** [comment]
@fhemberger Just to make sure I understand the request correctly: You want all these people added to the `@nodejs/website` team? Is that correct?

**Comment by fhemberger** [comment]
@Trott Yes, you're right, please add them to `@nodejs/website`.

Already added a feature request to automate this through a GitHub bot:
https://github.com/nodejs/bot-love/issues/1

**Comment by Trott** [comment]
OK, all done!

**Comment by fhemberger** [comment]
@Trott Woohoo, thanks!
