### ISSUE TITLE
very messed up formatting on 2011 blog page listing

### ISSUE THREAD

**Issue by Trott** [nodejs/nodejs.org#1717]
* **URL**: https://nodejs.org/en/blog/year-2011/
* **Browser version**: Chrome 67
* **Operating system**: macOS

<img width="1273" alt="screen shot 2018-07-07 at 5 00 17 pm" src="https://user-images.githubusercontent.com/718899/42415556-43da195a-8207-11e8-902c-4c7b28b60325.png">

**Comment by fhemberger** [comment]
Fixed in `ecfdb0a`.
