### ISSUE TITLE
Document supported versions + LTS releases on webiste

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs.org#174]
We should put a short description and the LTS graphic somewhere on the website.
How about using https://nodejs.org/en/about/releases/ for this?

(ref https://github.com/nodejs/nodejs.org/issues/74)

**Comment by phillipj** [comment]
Linking this with #200

**Comment by stevemao** [comment]
Is this problem solved @fhemberger ?

**Comment by stevemao** [comment]
answering myself: looks like this issue is stale.

**Comment by fhemberger** [comment]
@stevemao As we now have Stable/LTS everywhere on the site, we're good.
