### ISSUE TITLE
Quote doesn't look well

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#1741]
Hi all:

Review of the nodejs.org, look at this: https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/.

Now you'll see this:
![capture](https://user-images.githubusercontent.com/40081831/42745853-7d902d5e-8907-11e8-800e-5d3653dfde0e.PNG)

This pharagraph in blue doesn't look well, Are you sure to make it like this? Should any changes apply on that style?

**Comment by fhemberger** [comment]
I think we can remove the block quote here. Thoughts @nodejs/website?

**Comment by ghost** [comment]
PS：I've removed that and this is the style here on my local machine. Waiting for your response of good ideas :)

![good](https://user-images.githubusercontent.com/40081831/42746062-a352e5bc-8908-11e8-8e6a-78ed3e05bbdf.PNG)

**Comment by pierreneter** [comment]
I think this `blockquote` can be styled like this:

<img width="1079" alt="screen shot 2018-07-16 at 2 01 21 pm" src="https://user-images.githubusercontent.com/12815768/42746189-c2678e06-8900-11e8-8574-f36a44b4b31d.png">

**Comment by ghost** [comment]
@pierreneter：How do you cope with that? The original codes are using `>` as blackquotes. And it seems well in VS but not well in the real browser...?
![image](https://user-images.githubusercontent.com/40081831/42746740-ea9ed9be-890b-11e8-967a-8c24760993f4.png)
