### ISSUE TITLE
Update to Node.js Newsletter

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs.org#1745]
Nothing urgent, but I noticed on the home tab that it states Node.js Everywhere is a weekly newsletter, but we've changed it to monthly. I don't think I have access to the home tab to make this fix. Happy to follow someone's directions on this, but don't want to mess anything up.

Thanks in advance for any help here :)

**Comment by rbfriedman** [comment]
Can I assign this to myself? I am a new contributor to the project

**Comment by fhemberger** [comment]
@rbfriedman Hi, this is already addressed in #1747, we are just waiting for an Arabic translation.
