### ISSUE TITLE
Different kinds of nodejs for different kinds of languages for `ca` and `en` or other pages?

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#1746]
If you take a close look at `ca`, there are some pages missing in `en`, so which is right?
Take this as an example:
We don't have **Comunitat Brasileira de Node.js(http://nodebr.com/).**

@nodejs/nodejs-tw：
And in `ca` page（https://nodejs.org/ca/get-involved/）, we have a TW page:

![tw](https://user-images.githubusercontent.com/40081831/43239496-08fa8898-90c5-11e8-8924-7ee6ca287d3f.PNG)

But in other language pages we don't have this, take `en` as an example:
![nothave](https://user-images.githubusercontent.com/40081831/43239539-2c3f50ae-90c5-11e8-97bb-9f3ec1e5ef1a.PNG)

So should I help to add this website to other language pages or remove this from `ca`?

/cc：@nodejs/localization

**Comment by fhemberger** [comment]
@Maledong `nodejs.tw` is a dead link and was removed from the other languages a while back. Must have re-appeared by accident.

The Brazilian page seems to be more a general blog about Node.js with the last entry dated November 17, 2016. I think we can remove it as well.

**Comment by Maledong** [comment]
Well, I'll help to remove them, thanks!

**Comment by ghost** [comment]
Thanks all, this is fixed by https://github.com/nodejs/nodejs.org/pull/1748
