### ISSUE TITLE
"Do Not Track" is enabled since IE9, it has nothing to do with the platform?!

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#1754]
For `dnt_helper.js` in `node.org`, I've noticed there's a snippet of codes to tell whether the user has enabled `dnt tracker` or not, some of them are (take key parts):

function _dntEnabled(dnt, userAgent) {

    'use strict';

    // for old version of IE we need to use the msDoNotTrack property of navigator
    // on newer versions, and newer platforms, this is doNotTrack but, on the window object
    // Safari also exposes the property on the window object.
    var dntStatus = dnt || navigator.doNotTrack || window.doNotTrack || navigator.msDoNotTrack;
    var ua = userAgent || navigator.userAgent;

    // List of Windows versions known to not implement DNT according to the standard.
    var anomalousWinVersions = ['Windows NT 6.1', 'Windows NT 6.2', 'Windows NT 6.3'];
    .....

    // With old versions of IE, DNT did not exist so we simply return false;
    ......
    } else if (isIE && platform && anomalousWinVersions.indexOf(platform.toString()) !== -1) {
        // default is on, which does not honor the specification
        dntStatus = 'Unspecified';
    .....
    return dntStatus === 'Enabled';
}

It seems that since IE9, we've got "Do Not Track Me" function. And in IE 11, it'd be 'Windows NT 6.3'. So I suspect whether it has nothing to do with the 'platform'.

Now take IE 9 as an example:

![ie_protection](https://user-images.githubusercontent.com/40081831/43352558-ddf0139a-9257-11e8-9e7d-1922f03c87bb.png)
![ie_protection2](https://user-images.githubusercontent.com/40081831/43352559-df6c015c-9257-11e8-90a1-4c5d6fdffb2a.png)

As for IE 11, we've automatically enabled this here: 
https://support.microsoft.com/en-us/help/17288/windows-internet-explorer-11-use-do-not-track

![image](https://user-images.githubusercontent.com/40081831/43353314-bbe16410-9267-11e8-8a7d-50c9d3a951ff.png)

I'm not sure whether this is a bug in the codes, but IE9 (since) has really started this function. I suggest we should take the IE version (>=9) as a level to check whether we've supported `dnt` or not?

What do you think of this?

PS：Checked all the browsers, the result of `dnt` is:

![default](https://user-images.githubusercontent.com/40081831/43352633-f9aafa86-9258-11e8-8224-a29540e63ad7.PNG)

For borwser dns support info, plz see: https://testdrive-archive.azurewebsites.net/Browser/DoNotTrack/Default.html

**Comment by Maledong** [comment]
@phillipj：Since you've written the codes 2 years ago, maybe this should be changed according to the real IE's version (>= IE9, we have dnt, otherwises we don't have that function)? 

Just for confirmation, thanks first.

**Comment by ghost** [comment]
No problem, I misunderstood what the codes mean：You wanna set when automatically DNT = 1, ignore it. I closed this.
