### ISSUE TITLE
How to contribute with translations

### ISSUE THREAD

**Issue by xela92** [nodejs/nodejs.org#1760]
Hi there, 

I wanted to help translating the website in Italian, i pulled the project and started translating but I can't understand how's the procedure to send translations back to the team. 

Can you please help me understand?

Thank you

**Comment by fhemberger** [comment]
Hi Alex,

there's a team @nodejs/nodejs-it which worked on the Italian translation so far.
They have a [separate repo](https://github.com/nodejs/nodejs-it) for discussing translation topics, but I don't know if the team is currently active at all. But team membership is not required for submitting any translations.

We're super happy that you want to contribute! The "process" is basically that you fork this repo, pick a page from `locale/en` you'd like to work on and submit a pull request. Afterwards, at least one member of @nodejs/nodejs-it (or any other person which is proficient in Italian) will review the PR and give some feedback on the translation. Once it's approved (getting a green checkmark), we'll merge it into master. That's all. 😀 

If you have any further questions, I'm happy to help!

**Comment by xela92** [comment]
Thanks for your help Frederic 👍 
I submitted a pull request, I saw the page about nodejs-it but it seems really inactive.
Later on in August I will submit all the pages to complete the IT translation (hopefully, if the team approves) 😄 

Thank you again!
