### ISSUE TITLE
release-post.js script should ignore 32-bit binaries for intel and sunos

### ISSUE THREAD

**Issue by rvagg** [nodejs/nodejs.org#1769]
I'd fix this but I'm currently doing releases and am likely to be too exhausted at the end to get around to this.

./scripts/release-post.js needs to not put "Coming soon" for 32-bit binaries for Linux x86 or "sunos" x86 for Node 10+, they're deprecated. But it should still do it for 6 & 8. I think the best way might be to put metadata in scripts/helpers/downloads.js to indicate this and filter them out when we're doing a v10 release.

**Comment by Maledong** [comment]
Hi：
What about trying this, if you agree with this, I'll try to submit a PR for download.js：

```javascript
module.exports = (version) => {
  let downloads = latestDownloads
  if (semver.satisfies(version, '< 1.0.0')) {
    downloads = legacyDownloads
  } else if (semver.satisfies(version, '< 8.0.0')) {
    downloads = postMergeDownloads
  } else if (semver.satisfies(version, '> 10.0.0')) {
    downloads = postMergeDownloads.filter(value =>
      !value.title.startsWith('Linux 32-bit') &&
      !value.title.startsWith('SunOS 32-bit'))
  }
  return downloads.map((item) => resolveUrl(item, version))
}
```

PS：Since your origin codes will check whether the version is <8.0.0 and then <1.0.0. Then it will download different links of files. I've optimized them.

Feel free to suggest :)

**Comment by ghost** [comment]
Well, this issue is fixed and landed here: https://github.com/nodejs/nodejs.org/commit/f0818db4c8dd29df9a640ff31ea172b81a864ffd

So I closed this and for any other problems, please feel free to re-open.
Thanks anyway!
