### ISSUE TITLE
Update homepage with Interactive rebrand

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs.org#1776]
We recently rebranded JS Interactive to Node+JS Interactive to reflect both of our communities in the conference title. Wondering if we could update the banner on the website with this new change? Let me know what you might need here to make this happen, and thank you in advance for helping me out with this!

**Comment by fhemberger** [comment]
@ZibbyKeaton Can you send me the PSD file of the new banner so I can adapt it?

**Comment by ZibbyKeaton** [comment]
GitHub doesn't support the PSD file type @fhemberger. Should I send it to you in email or what's the best way to get this to you?

**Comment by fhemberger** [comment]
@ZibbyKeaton Can you share it on a Google Drive or something similar and send me the link: `mail` `@` `frederic-hemberger.de`?

**Comment by ZibbyKeaton** [comment]
Just sent, let me know if you received this :)
