### ISSUE TITLE
The title `collab-submit` itself is missing with translations

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#1778]
In `site.json`, suddenly I found that the `collab-submit`'s tranlation itself is missing. So we should need to make up for that :)

![image](https://user-images.githubusercontent.com/40081831/44624536-5af8bb80-a923-11e8-9435-f2aeb87cf0d9.png)

Ref:  https://github.com/nodejs/nodejs.org/pull/1777/commits/ba462845320ee37d64d7e86c69a59570f996a038#diff-44845960569e9ce53bd39cf9aadc07b2

/cc：
@nodejs/nodejs-tw 
@nodejs/nodejs-fr 
@nodejs/nodejs-es 
@Tsuna-mi

**Comment by fhemberger** [comment]
Fixed, closing.
