### ISSUE TITLE
Link to EventMachine is broken

### ISSUE THREAD

**Issue by kzvi** [nodejs/nodejs.org#1779]
* **URL**: https://nodejs.org/en/about/
* **Browser version**: safari
* **Operating system**: osx

There is a link on https://nodejs.org/en/about/ titled "Event Machine" which links to `rubyeventmachine.com`, but there is nothing at that website related to programming.

**Comment by fhemberger** [comment]
Hmm, looks like someone forgot to pay for their domain. ;)
We should link to https://github.com/eventmachine/eventmachine instead.

Thanks for reporting!

**Comment by willin** [comment]
@sodabrew please notice that your domain has already expired

**Comment by sodabrew** [comment]
Unfortunately that happened. Please do update your link to GitHub directly.
