### ISSUE TITLE
PSA: API documentation linking to source

### ISSUE THREAD

**Issue by refack** [nodejs/nodejs.org#1785]
Original issue: https://github.com/nodejs/node/issues/22393
First implementation: https://github.com/nodejs/node/pull/22405
Example: https://nodejs.org/download/nightly/v11.0.0-nightly2018083060465700ed/docs/api/buffer.html#buffer_class_method_buffer_alloc_size_fill_encoding
![image](https://user-images.githubusercontent.com/96947/44863074-2437e380-ac4a-11e8-8a2e-e9a517b883a2.png)

/CC @nodejs/website-redesign

**Comment by refack** [comment]
H/T: @rubys

**Comment by fhemberger** [comment]
Thanks for the update!

Closing, because there's nothing left to do on the website.
