### ISSUE TITLE
member list not found

### ISSUE THREAD

**Issue by ZYSzys** [nodejs/nodejs.org#1789]
The [member list](https://github.com/orgs/nodejs/teams/website/members) link on README.md is 404 not found.
* **URL**:https://github.com/nodejs/nodejs.org#website-working-group-members
* **Browser version**: Safari
* **Operating system**:macOS 

Is it private or doesn't exist ?
If it is private, isn't it unnecessary to show this in README while other users can't visit ?

**Comment by amandeepmittal** [comment]
The link you commented is a bit incorrect. Here is the correct link https://github.com/nodejs/nodejs.org/#website-working-group-members

**Comment by fhemberger** [comment]
Hmm, looks like group listings are now private on GitHub. 🤔

**Comment by ZYSzys** [comment]
So do we need to remove it or do something ...?

**Comment by fhemberger** [comment]
Yeah, we should probably remove it …
