### ISSUE TITLE
Mention Node.JS Docker Image as an official distribution

### ISSUE THREAD

**Issue by Starefossen** [nodejs/nodejs.org#179]
Opening a discussion on how to get the official Docker Image for Node.JS mentioned, preferably under the download section, on the nodejs.org website. The Docker Image for Node.JS maintained by @nodejs/docker Working Group and is considered an official distribution of Node.JS.

**Relevant Literature:**
- https://github.com/nodejs/docker-iojs/blob/master/README.md#how-to-use-this-image
- https://strongloop.com/strongblog/containerizing-node-js-apps-with-docker-and-strongloop/
- http://blog.codefresh.io/up-and-running-with-io-js-and-docker/

**Comment by fhemberger** [comment]
I would say: Let's link the official Docker image in Downloads, put the how-to articles you mentioned under Docs.

**Comment by rvagg** [comment]
yeah, nice, perhaps just link to https://hub.docker.com/_/node/, although I have the following concerns:
1. that doc needs updating, it's very 0.10-focused, only mentions 4.0.0, not 4.1.0 and still links to the old docker-node repo location.
2. docker images aren't updated automatically on release, it takes a PR, merge (and push to hub?) which afaik takes at least a day, so I'm not sure links from the download page would be accurate when we have new releases. Perhaps we can find a way to reduce the time gap?

**Comment by Starefossen** [comment]
Good points @rvagg!

I'll make sure the Docker image docs gets updated asap. Regarding the push to Docker Hub we can automate pretty much everything from our end when a new release is cut, but it ultimately has to go through a PR to the official registry - which has to be approved manually.

**Comment by chorrell** [comment]
RE: The PR to the official registry

Maybe it's time to talk to Docker about seeing if we can automate that process?

**Comment by mikeal** [comment]
What the state of this?

**Comment by Starefossen** [comment]
Sorry for the delay on this one, I have been working on getting some of the issues mentioned here solved.
- [x] Updated Docker Image examples to use Node.js v4 (docker-library/docs#374)
- [x] Updated Docker Image repo links to new repo (docker-library/docs#374)
- [x] Updated README for nodejs/docker-node repo (nodejs/docker-node#53)

Should I propose a PR this repo to try to get this onto the downloads page?
