### ISSUE TITLE
Local Building is broken

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#1806]
Now up to the latest version of Nodejs's org source code (Mine is at 68939e09ad1c98926ab892fcd864ccd036a37ca5). I suddenly found that I cannot use `npm run build` to build a native local running website to have a view……:(

And it used to be well...

Have you found this bug yet?

![2](https://user-images.githubusercontent.com/40081831/45470381-2fb5ff00-b760-11e8-8cd2-7595fe669eaf.PNG)

/cc: @nodejs/website

**Comment by fhemberger** [comment]
Hmm, works for me: Latest node.js 10.10.0 (macOS), clean `npm install`, `68939e0` (master). What version of Node are you using?

**Comment by ghost** [comment]
Node v8.11.4, thanks @fhemberger.

![2](https://user-images.githubusercontent.com/40081831/45470727-69d3d080-b761-11e8-8415-a53615d93510.PNG)

PS：I've removed node_module and use `npm i`, but the failure still occurs.... :(

**Comment by Maledong** [comment]
PS：For v8.12.0, everything goes right. Now I'm using this version. Perhaps this is due to compatible problem?!

**Comment by ghost** [comment]
@fhemberger：For v8.12.0, everything goes right. Now I'm using this version. Perhaps this is due to compatible problem?!
![2](https://user-images.githubusercontent.com/40081831/45471516-e5cf1800-b763-11e8-973b-62b07095219e.PNG)

**Comment by AyushG3112** [comment]
Working with me on Node v8.11.4 on top of master.

**Comment by osk2** [comment]
I saw `ECONNRESET` in error message. It may be caused by temporary network problem?

**Comment by ghost** [comment]
@osk2：Not sure, but everything goes well with me on Node 8.12.0 :)
Nothing but just leave it as an issue if anyone else finds this. Maybe after upgrade to the latest version of Nodejs everything goes well with me soon, strangely speaking! Hahaha……
