### ISSUE TITLE
Should the "Don't Block the Event Loop" guide be updated to reflect the `worker_threads` module?

### ISSUE THREAD

**Issue by AyushG3112** [nodejs/nodejs.org#1808]
Should the [Don't Block the Event Loop](https://nodejs.org/en/docs/guides/dont-block-the-event-loop/) guide be updated to reflect the `worker_threads` module as a way to offload blocking work to a worker as a way to, well, not block the event loop?

**Comment by AlexandroMunera** [comment]
I tried the link but 404

**Comment by AugustinMauroy** [comment]
the document concerned is no longer in the codebase.
