### ISSUE TITLE
Update NearForm logo

### ISSUE THREAD

**Issue by jasnell** [nodejs/nodejs.org#1809]
NesrForm have recently updated our logo. The logo on the website foundation members page needs to be updated. There are two options, each given below.

![nf_shared_brand_assets_logo_horizontal_positive](https://user-images.githubusercontent.com/439929/45549310-ad910d80-b827-11e8-896c-79a5342a0757.png)
![nf_shared_brand_assets_logo_horizontal_reverse](https://user-images.githubusercontent.com/439929/45549323-b1bd2b00-b827-11e8-9ffe-02eba966a464.png)

**Comment by fhemberger** [comment]
@jasnell Pages about Foundation membership are not handled through this repo any longer. We also don't have access to the Foundation website's admin interface. Maybe @ZibbyKeaton or @gtewallace can help.

**Comment by jasnell** [comment]
Yep, that I knew, but it's not obvious where to go :)

**Comment by ZibbyKeaton** [comment]
@jasnell we updated it on the NF website. If you have requests on NF website, feel free to send to Greg and me directly via email or ask NearForm marketing team to send. Like the new logo :)

**Comment by fhemberger** [comment]
Thanks @ZibbyKeaton! Closing.
