### ISSUE TITLE
Adding collaborators

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#181]
We should create a list of proposed people to add as collaborators and potentially even a few to add as Working Group members. I'd like to see this project move to more of an "OPEN Open Source" contribution model and we've had a ton of people show up recently and do great work.

We may also want to schedule a WG meeting soon.

**Comment by fhemberger** [comment]
Looking at `git shortlog -s -n` with contributions > 1:

```
   175  Frederic Hemberger
    43  Mikeal Rogers
    20  Phillip Johnsen
    19  Rod Vagg
    13  Sean Ouimet
     8  Jeremiah Senkpiel
     7  Divjot Singh
     5  Austin Winstanley
     5  Ben Noordhuis
     5  Evan Lucas
     4  &! (bitandbang)
     4  Thomas Jensen
     4  MassimilianoMura
     3  Rich Trott
     3  Yosuke Furukawa
     3  Max Ogden
     2  paulgrock
     2  andygout
     2  Chayoung You
     2  Francisco Baio Dias
     2  Elin
     2  Trent Oswald
     2  Steven Sinatra
     2  Steve Mao
     2  rnsloan
```

**Comment by mikeal** [comment]
In core we consider people with only a single commit as well. If it's more than a trivial change we onboard them as a committer.

**Comment by mikeal** [comment]
Also, this might be a little more useful since it's got people's GitHub usernames https://github.com/nodejs/new.nodejs.org/graphs/contributors

**Comment by mikeal** [comment]
Ok, I'm not sure if we need any "onboarding" here, the website is pretty easy to contribute to and the guidelines are written up.

Any objection to adding:
- @bogas04 
- @AustinWinstanley 
- @evanlucas 
- @JungMinu
- @Trott
- @tjconcept
- @thefourtheye
- @yosuke-furukawa
- @MassimilianoMura
- @maxogden
- @yous
- @xicombd
- @andygout
- @mrkiffie
- @rnsloan
- @diagramatics
- @stevemao
- @PatrickHeneise
- @paulgrock
- @srl295
- @lpinca
- @bentinata
- @hoxoa
- @Delapouite
- @s3ththompson
- @narqo
- @csabapalfi
- @marocchino
- @targos
- @silverwind
- @simonmcmanus
- @brycebaril 
- @elinnet
- @wonderdogone
- @fabiosantoscode

**Comment by silverwind** [comment]
Happy to join :+1:

**Comment by stevemao** [comment]
I'm quite happy if I can help :+1:

**Comment by Delapouite** [comment]
Would be my pleasure to contribute again.

**Comment by thefourtheye** [comment]
I would love that :)

**Comment by JungMinu** [comment]
Happy to join :smile: Thanks

**Comment by s3ththompson** [comment]
:+1:

**Comment by fabiosantoscode** [comment]
+1

**Comment by rnsloan** [comment]
:+1:

**Comment by csabapalfi** [comment]
:+1:

**Comment by fbaiodias** [comment]
:+1:

**Comment by mrkiffie** [comment]
:+1:

**Comment by PatrickHeneise** [comment]
Thanks

**Comment by elinnet** [comment]
[image: :+1:]

**Comment by lpinca** [comment]
I'm happy to help.

**Comment by diagramatics** [comment]
:+1:

**Comment by paulgrock** [comment]
I'd love to help.

**Comment by evanlucas** [comment]
Thanks! I'm open to joining :]

**Comment by mikeal** [comment]
@fhemberger waiting to get a nod from you before I add everyone :)

**Comment by srl295** [comment]
Thanks for readding me! +1

**Comment by fhemberger** [comment]
@mikeal I still feel a bit uncertain giving so many people commit rights to master (not because of any of the contributors, I simply don't have any experience with this kind of setup). Is it possible to set up some kind of GitHub workflow? (e.g. changes need to be introduced as PR and need another person to merge them.)

With the next step of adding all translators to the website repo as well, we would have more than 50 people. What do you think?

**Comment by mikeal** [comment]
@fhemberger ah, I had assumed that we brought over the contribution policy from core but it looks like we are missing it :)

The policy for core is that nobody can merge their own commit, everything is a PR :) I'll send a PR to our README for that.

**Comment by thefourtheye** [comment]
@fhemberger Ah, I agree. Too many cooks spoil the broth :D I contribute (though I check most of the PRs) only time to time. So, I would like to opt-out.

**Comment by fhemberger** [comment]
@mikeal Great, thanks.

**Comment by bogas04** [comment]
Awesome news!
Glad to be part of the project.
Thanks a lot.

## 

Divjot Singh http://bogas04.github.io/
Computer Engineering Undergraduate
Netaji Subhas Institute of Technology,
University of New Delhi

**Comment by mikeal** [comment]
Ok, https://github.com/nodejs/new.nodejs.org/pull/224 this is based on the governance proposal I put up yesterday. Rather than a "TC" model we have an "admin group" which is elected by the full WG. The obvious candidates at this time would be the top 4 or 5 contributors, but we'll need to do that election shortly after we add all these members :)

**Comment by AustinWinstanley** [comment]
Thanks! I'm definitely open to helping more.

**Comment by phillipj** [comment]
Great @mikeal! Very happy to get more people on board :)

**Comment by bnb** [comment]
As there are going to be so many new contributors, do you think we can step up our work on the site? It would be super awesome if we can get some mini-projects going, such as bringing iojs.org localization back to Node, learner structure for creating/finding Node.js content (this one is important to me, I'd be happy to spearhead it), user collaboration infrastructure, and a mentorship program (can work closely with Evangelism)?

If we have the hands to create more value through integrating projects like these into the site, we should _absolutely_ do it. There were many problems with the old Node site, and we have a chance to change that on the new Node site. 

If you'd like, I can create another issue for this once the members are approved.

**Comment by mikeal** [comment]
@bnb you're in the thread about Localization, we need some docs there. Once we have the docs we need to start promoting it.

The other big project will be the knowledge base but there's a limited amount of contributions we can take there until we solve the copyright issues.

Other than that, we have lots of style, usability, and content improvements in nearly all sections.

**Comment by mikeal** [comment]
Ok
- New contributing/governance is merged.
- Website WG team switched from repo "admin" to "write" access.
- Everyone noted earlier in this thread has been added/invited to the Website WG team.

I'll be kicking off another thread for Admin Group elections.
