### ISSUE TITLE
Should microtask queue explanation live in existing event loop docs?

### ISSUE THREAD

**Issue by jeromecovington** [nodejs/nodejs.org#1813]
Does it seem like there should be a bit more attention given to the microtask queue in the docs?

If so, should it be a brief addendum to the existing [event loop docs](https://github.com/nodejs/nodejs.org/blob/master/locale/en/docs/guides/event-loop-timers-and-nexttick.md) or should it get its own place?

Little discussion here already: https://github.com/nodejs/promises-debugging/issues/14

**Comment by ovflowd** [comment]
Closing as this is obsolete.
