### ISSUE TITLE
release-post.js script should ignore PPC BE 64-bit Binary

### ISSUE THREAD

**Issue by targos** [nodejs/nodejs.org#1815]
Similar to https://github.com/nodejs/nodejs.org/issues/1769

PPC BE is not supported above Node 8: https://github.com/nodejs/build/blob/060809a571c133da35051136023ec19006a275a7/jenkins/scripts/VersionSelectorScript.groovy#L49-L50

**Comment by mhdawson** [comment]
I assume it still needs to support PPC BE for 6.x releases, right?

**Comment by targos** [comment]
> I assume it still needs to support PPC BE for 6.x releases, right?

Yes

**Comment by ghost** [comment]
Fixed at https://github.com/nodejs/nodejs.org/pull/1819.
