### ISSUE TITLE
[macOS 10.14] pkg installer is stuck 

### ISSUE THREAD

**Issue by webpty** [nodejs/nodejs.org#1823]
Posting here as this is not an issue with node.js itself

* **URL**: downloads
* **Browser version**: Chrome Version 70.0.3538.22 (Official Build) beta (64-bit)
* **Operating system**: macOS Mojave 10.14 (18A391)
* **Downloaded file**: `node-v10.11.0.pkg`

Attempting to update node after  ##OS update, and I'm stuck on this screen of the installer:
![node-mojave](https://user-images.githubusercontent.com/11739306/46043216-0f316180-c0dd-11e8-8647-b1848f4bce01.png)

The `Install` button is dead at this point. It turns blue when I click, but nothing happens.

**Comment by webpty** [comment]
after attempting the install with `brew` command line, i got this message:
![screen shot 2018-09-25 at 4 17 42 pm](https://user-images.githubusercontent.com/11739306/46043831-a4812580-c0de-11e8-966b-c9ae7a2996e9.png)
So the package was installed but the process was not finished.
I followed the indications, and now have 10.11 installed.
I'm not sure it's an issue with the package with this OS version, or an issue with the OS at this point.

**Comment by fhemberger** [comment]
> Posting here as this is not an issue with node.js itself

The Node.js installer is part of [nodejs/node](https://github.com/nodejs/node), please open an issue there.
Closing, because it's not an issue with the website itself.
