### ISSUE TITLE
Do we need a document-abandoned request for `nodejs/iojs.org` in `GOVERNANCE.md`？

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#1829]
Hello all：

According to https://iojs.org/en/, it seems that we WON'T put any releases in IO.js now. So：

1）Is this repository JUST for a historical one？
2）Do we need to remove or add comments saying this website is NO LONGER used because it's merged since v4 of Nodejs in `GOVERNANCE.md`？

![image](https://user-images.githubusercontent.com/40081831/46577909-1ed97000-ca24-11e8-9064-58e3d3489683.png)

/cc: @nodejs/documentation

**Comment by fhemberger** [comment]
iojs.org is going to be removed anyway:
https://github.com/nodejs/iojs.org/issues/432

**Comment by Maledong** [comment]
Thanks :)

**Comment by a0viedo** [comment]
maybe it's something that can be revisited in the following contributor summit @bnb @jasnell @Trott

**Comment by fhemberger** [comment]
- The iojs.org website is now redirecting to nodejs.org
- Links to downloads/docs are still active
- iojs.org repo is archived

PR: #1909
