### ISSUE TITLE
/download/package-manager page will get outdated.

### ISSUE THREAD

**Issue by mAPBhlJ** [nodejs/nodejs.org#1831]
I was installing NodeJS through the installation instructions on the following page:
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

However, it does not list Ubuntu 18.04 as supported.
Though, when checking the #Node.js freenode web IRC, they've pointed me to the website:

https://github.com/nodesource/distributions/blob/master/README.md

Where it does show Ubuntu 18.04, so I believe it actually is supported.

---

This may be confusing to new people.
And the "supported versions" are documented on multiple places, making it possible for them to get desynchronised (as in this example).

---

I feel that the page should be updated to list 18.04 and/or possibly should refer to the git readme for a list of supported distributions, rather than having it double-documented.

**Comment by fhemberger** [comment]
Fixed in #1832.
