### ISSUE TITLE
How can integrate PHP API in node js ?

### ISSUE THREAD

**Issue by patelvanita360** [nodejs/nodejs.org#1842]
Can any send me example code for how to integrate PHP API in node js ?

**Comment by aks-** [comment]
@patelvanita360 what do you mean by integrating php api in node? like being able to use php library in node? or being able to call api endpoints using node?

**Comment by fhemberger** [comment]
Also, this is not a topic for the Node.js website.
Could you please open a new issue with more context in https://github.com/nodejs/help/issues

Closing.

**Comment by patelvanita360** [comment]
Able to call api in node js.
