### ISSUE TITLE
Take down Node+JS Interactive banner - highlight release changes?

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs.org#1843]
Node+JS Interactive is officially over, so we can take the banner down for the homepage :) Thank you for letting us post about it on the website!

One additional thought:

Our website gets a ton of traffic, and I think it's a great way to reach folks that might not connect with us on social or GitHub. Do we want to link to our release update once we have it up or is there another major CTA that we want to push this month that will be beneficial to a large amount of Node.js users (tooling, enterprise, etc)? 

I can bring this topic up in the next CommComm meeting as well if that's the best forum for this question.

**Comment by fhemberger** [comment]
Banner has been taken down, download links for new release are on the homepage.
