### ISSUE TITLE
In french nodejs website node v10 unavailable

### ISSUE THREAD

**Issue by doom-fr** [nodejs/nodejs.org#1847]
* **URL**: https://nodejs.org/fr/download/current/
* **Browser version**: Version 69.0.3497.100 (Build officiel) (64 bits)
* **Operating system**: Windows 10

In french website, in download page, current version tab can't be activate (if you click on "actuelle", "LTS" remains active).
And so, only node v8 is downloadable.

On the main page it works, but I wan't to download linux version from windows so it won't works.

In english version, all seems to be OK.

D.

**Comment by fhemberger** [comment]
Thanks, found the issue. This will be fixed shortly.
