### ISSUE TITLE
Nominating @ZYSzys as a collaborator

### ISSUE THREAD

**Issue by ZYSzys** [nodejs/nodejs.org#1867]
As a Node.js enthusiast❤️, I'd like to nominate myself as a Collaborator with several commits and consistent engagement in `nodejs.org`.
And I'd love to contribute to this repo again in the future when needed.

Commits: https://github.com/nodejs/nodejs.org/commits?author=ZYSzys
Comments: https://github.com/nodejs/nodejs.org/search?q=commenter%3AZYSzys&type=Issues

**Comment by fhemberger** [comment]
Haha, no need to do that. We regularly add contributors to the Node.js org. But as it's a manual process at the moment, we do it in batches. (We have to come up with something better.) So please, bear with me for just a little longer. 🙏

So thank you very much for all your contributions, you really helped us a lot!

**Comment by ZYSzys** [comment]
Aha, I'm a bit of excited and can't wait to be a part of nodejs org.😎

Waiting for your invitation~~~👻.

**Comment by fhemberger** [comment]
See #1872
