### ISSUE TITLE
Node LTS ENOENT: no such file or directory 32 bits Lubuntu

### ISSUE THREAD

**Issue by rednaxe7** [nodejs/nodejs.org#1870]

**Comment by fhemberger** [comment]
Uhmm … could you please be a bit more specific where you got this message and/or provide an URL?

**Comment by rednaxe7** [comment]
Yes, the url: https://nodejs.org/dist/v10.13.0/node-v10.13.0-linux-x86.tar.xz

I want to know if they will not give more support? to 32 bits?

Thank you

**Comment by fhemberger** [comment]
Node.js dropped Linux 32bit support in 10.x:
https://github.com/nodejs/build/issues/885

Needs to be fixed on the website.

**Comment by fhemberger** [comment]
Ref: #1873
