### ISSUE TITLE
Add new contributors (October 2018)

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs.org#1872]
@bnb @Trott @MylesBorins

```
nodejs/nodejs.org committers since 2018-07-01, which aren't contributors yet:

* ZYSzys (ZYSzys)
* academo (Esteban Beltran)
* e-jigsaw (jigsaw)
* suensummit (Summit Suen)
* flowkraD (Prateek Nayak)
* Ginden (Michał Wadas)
* petetnt (Pete Nykänen)
* tehkaiyu (Kaiyu Hsu)
* pboi20 (Patrick Boivin)
* trevorah (Andy Trevorah)
* chakravarthysm (Chakravarthy S M)
* paranoidjk (paranoidjk)
* richardlau (Richard Lau)
* tombusby (Tom Busby)
* nickmccurdy (Nick McCurdy)
* belhassen07 (Belhassen Chelbi)
* taggon (Taegon Kim)
```

Also, please add @AliSawari, @m-esm, @armanatory and @anio to `@nodejs/nodejs-fa`.

Thanks everyone for your contributions!

**Comment by Trott** [comment]
All done. (@anio was already a member of `@nodejs/nodejs-fa`.)

**Comment by fhemberger** [comment]
Awesome, thanks a lot!

I wish there was a way we could automate this process, so I don't have to bother you all the time.

**Comment by Trott** [comment]
@fhemberger You are a Maintainer of the team and should be able to do this yourself, actually. If it's not working or if you're not sure of the process, let's chat in IRC or email and figure it out.

**Comment by nickserv** [comment]
Thank you for the invite!

In the future it may be more convenient to remove the code block formatting, it disables GitHub's mention feature which automatically sends notifications.

**Comment by fhemberger** [comment]
@Trott As a maintainer, I can only invite users to the team if they are already a member of the org. But I can't add them to the org itself, only org admins can do that

**Comment by Trott** [comment]
> As a maintainer, I can only invite users to the team if they are already a member of the org. But I can't add them to the org itself, only org admins can do that

Oh, that's right! We go through this every time, don't we? :-D I always forget...

FWIW, a few of the people above were already members so you could have added them, I suppose. But most were not...

**Comment by fhemberger** [comment]
@Trott Yes indeed. :D

Would be nice if we could automate this. Could we use a bot or something that adds new contributors e.g. once a month?

How do other teams of the org handle the onboarding of new members?

**Comment by Trott** [comment]
> Would be nice if we could automate this. Could we use a bot or something that adds new contributors e.g. once a month?

/ping @nodejs/automation @nodejs/github-bot 

> How do other teams of the org handle the onboarding of new members?

No other team has this team's combination of large number of members and permissive rules for being added. So it's not an issue for other teams, I don't think.

**Comment by phillipj** [comment]
Making the bot add people automatically once a month surely sounds feasible. It's a Node.js process running reacting to incoming webhooks, and adding a scheduled job to that code base shouldn't be a problem IMO.

The biggest challenge is inviting people to the org as you mention. Currently the bot does not have privileges to do so. There has been discussions on providing such privileges but IIRC there has been several concerns raised about the security implications, which I've understood as the main reason we havent done so yet.

Might be worthwhile triggering those discussions again though. Maybe there's ways around what was raised back then that makes it less off a concern now.

**Comment by JasonEtco** [comment]
Hey folks - I'm not sure what the historical reasoning is for a monthly cadence, but if you were interested in adding all new PR authors to the Org _when_ the PR is merged, there's a Probot app that already exists: https://probot.github.io/apps/invite-contributors. You'd want to either install this GitHub App, or deploy your own instance of it. I think some of y'all are familiar with Probot, but if not feel free to ping me.

**Comment by bnb** [comment]
@Trott @fhemberger any objections to installing the app for this repo?

**Comment by Trott** [comment]
> @Trott @fhemberger any objections to installing the app for this repo?

Probably depends on what privileges it needs and whether it needs them on this repo only or for the org. I'm generally positive if it's for the repo only, and generally a bit reluctant if it's for the whole org.

**Comment by fhemberger** [comment]
@JasonEtco The only historical reasoning is that it was a manual step (until now) to determine new contributors and invite them. Therefore in the past it was only done rarely, so I tried to do do it at least quarterly.

So yes, if the privileges are not an issue, I'm in favor for using the bot instead!

**Comment by fhemberger** [comment]
@Trott Okay, who can help us set up the Probot app on this repo?

**Comment by JasonEtco** [comment]
FYI, here are the permissions its requesting:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/10660468/48051194-70cffb80-e172-11e8-8d54-865431dca523.png">

My impression is that most of those permission requests are unnecessary, and if that's a problem then we could build the app ourselves (it should be fairly straightforward and this existing app is [open source](https://github.com/erickzhao/invite-contributors)) and then deploy it. That's more of a time-investment of course. (I'm not volunteering, just laying out some options 😬)

**Comment by Trott** [comment]
> @Trott Okay, who can help us set up the Probot app on this repo?

@fhemberger I'm not sure there are clear guidelines, but probably the best thing to do is open an issue in the nodejs/admin repo explaining what and why.
