### ISSUE TITLE
doc: Can't find information about LTS releases.

### ISSUE THREAD

**Issue by kpm** [nodejs/nodejs.org#1889]
Hi,

I haven't been able to find info about LTS releases.  If I go to https://nodejs.org/en/about/releases/
, the page doesn't mention LTS at all.  If I go to the main docs at https://nodejs.org/en/docs/ , there's no search facility, and a quick explore through some links doesn't lead to any info I can find about LTS releases.

Sorry if I missed something obvious, I'm new to node.  I'd like to know when the next LTS release is planned and what version number it would be, or at least some page that has info that describes the LTS for nodejs.

Thanks.

**Comment by fhemberger** [comment]
@Trott We could link to `schedule.png` and produce a table right from `schedule.json`. See also https://github.com/nodejs/Release/pull/380
