### ISSUE TITLE
Node.js requires gnupg package to be installed in order to install 

### ISSUE THREAD

**Issue by davidcamarena** [nodejs/nodejs.org#1905]
Hi noders, 

I've just attempted to install node.js into a container running the "php:7" official PHP docker image, which is Debian based. 

The official node.js docs state that in order to install Node.js and npm into a Debian based distro you must use the official binaries and redirects you to the official github page with the README.md:

https://github.com/nodesource/distributions/blob/master/README.md

File has the following instructions to install node.js and npm. In my case it was Node 10.x for Debian.

> Node.js v10.x: 
> ...
> **# Using Debian, as root**
> **curl -sL https://deb.nodesource.com/setup_10.x | bash -**
> **apt-get install -y nodejs**

Using these steps only the installation was **unsuccessful**, and although I've finally solved this issue already I thought this additional information would be useful for others so I decided to share it and help others avoid this.

After a second run I noticed that the error message mentioned that package **gnupg** was missing (NOT installed ) in the docker image, not something you'd expect in a full-featured Debian distro, but definitely something that can happen on a more restricted and basic docker container.

And this package is *required* for the node.js installation to be successful.

So, solution was pretty simple finally, once known:

	$ sudo apt-get install -y gnupg

Just install the package first *before* the former official instructions for node.js install. It will fix the issue and allow you to finally install node.js and npm successfully in your container.

I thought that it would be useful to report and share this for your consideration to be added as a required "previous step" in the installation docs ("make sure gnupg package is installed" et-al), I hope it may save some unproductive hours to the people that is trying to install nodejs and npm in that kind of environments, just like I was.

Thank you,

David

**Comment by Trott** [comment]
This is presumably in reference to https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages. 

Are the NodeSource binaries actually "official"?  Should the text be changed from "Official Node.js binary distributions are provided by NodeSource." to "Node.js binary distributions are provided by NodeSource."?

/ping @nodejs/release

**Comment by davidcamarena** [comment]
I read about the snap packages, but if I read it properly the method given in the NodeSource README.md is indeed an alternate, unrelated installation method to snap afaik.

**Comment by sam-github** [comment]
This is unrelated to snap, its using debian PPAs.

I believe there is a typo in the subject, I think "gnupg" is meant where "phppg" was written.

The `setup_10.x` script has no direct use of gnupg, but it doesn't really surprise me `apt-key add` would call gnupg. What does surprise me is that if gnupg is a dependency used by the apt command, it isn't installed. Is it possible that the docker image somehow stripped a "recommended" dependency of "apt-key" on "gnupg"?

**Comment by davidcamarena** [comment]
Yep, I meant "gnupg", that's right, thank you.

And I don't disregard it, you may be right and it might be only an image-specific issue, but I think it's worth to document it so it can help another people with the same issue to solve it and succeed installing node.js.

**Comment by rvagg** [comment]
Not something I've run in to and I've done a lot of work on and with those repos and those scripts. As @sam-github metioned, `apt-key` is the only logical path to gnupg and it comes from the add-apt-key package which directly depends on `gnupg`. So my question would be, why is `apt-key` available on your system and not `gnupg`? That seems impossible unless you have a funky `apt-key` command on there. Seems like a bug with the container more than anything else.

**Comment by rvagg** [comment]
OK, I figured it out. `php:7` is based on `debian:stretch-slim` and the Debian slim images strip out `gnupg` from the standard base package list. `apt-key` is actually in the `apt` package. On Ubuntu, `add-apt-key` is a meta package that depends on both `apt` and `gnupg` to make sure `apt-key add` works. On Debian, there's no such package and I guess you're just supposed to know.

I've updated the install scripts to check for `gnupg`, and there's a PR waiting for review and deploy @ https://github.com/nodesource/distributions/pull/758, discussion should move over to there since this isn't an issue for the nodejs org.

**Comment by davidcamarena** [comment]
Hi,

Thank you very much @rvagg, I really appreciate your persistence and fixes for this, also the detailed explanation, now I understand better. 

And I'm sorry I didn't knew so much about Node projects, now I know I'd better had to report this to NodeSource directly, but anyways I'm happy that the NodeSource install scripts get fixed, I'm sure it will help others and make it Node more enjoyable and easy to deploy.

David

**Comment by gkrizek** [comment]
nodesource/distributions#758 has been merged and this is fixed in the NodeSource Debian repositories.
