### ISSUE TITLE
NodeJS download is flagged as "dangerous" by chromium on linux

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#1925]
* **URL**:https://nodejs.org/en/
* **Browser version**:Version 68.0.3440.106 (Official Build) Built on Ubuntu , running on
* **Operating system**: LinuxMint 18.3 (64-bit)

I tried to download NodeJS 10.14.1 LTS on chromium for linux, and Chromium blocks the file, flagging it as "dangerous". When I try to unblock it, it warns me that the site may be hacked.  Is the site actually hacked

**Comment by Maledong** [comment]
@turbobuilt：No. Everything seems fine with me.

Can you offer more info about "dangerous" things by clicking the Chromium "Details" button, maybe there're some things checked by Chrome and reguarded as "dangerous" things? Or reported by mistake……ect?

All in all, your screenshot and details of "dangerous" are welcomed to paste here for us to know more :)

**Comment by ghost** [comment]
@turbobuilt：No. Everything seems fine with me.
I'm using **Chrome, Version 71.0.3578.98 (Official Build) (64-bit)**.

**Comment by ghost** [comment]
But your situation seems very strange, so I'll call some group else to see what's happening……?
@nodejs/release.

PS：If possible, your screenshot and logs (if you have), please submit them :)

**Comment by fhemberger** [comment]
As this issue has been inactive for a month, I'm closing it.
Feel free to re-open if the problem still occurs.
