### ISSUE TITLE
No installation instructions for Linux downloads?

### ISSUE THREAD

**Issue by knipknap** [nodejs/nodejs.org#1926]
Are there any installation instructions for Linux for when you download the packages from nodejs.org? The only instructions I found are here:

https://nodejs.org/en/download/package-manager/

But those don't seem to relate to the downloads offered on nodejs.org.

**Comment by fhemberger** [comment]
It's a tarball file. Download and extract to `/usr` or `/usr/local`, depending on your preferences.

Details: https://github.com/nodejs/help/wiki/Installation

**Comment by knipknap** [comment]
That's what I have been looking for, Thanks! It would be helpful if that were linked on the website.
