### ISSUE TITLE
I am not able to understand the Node.Js architecture in context of event loop.

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#1936]
I am not able to understand the Node.Js architecture in context of event loop inspite of following the official docs. Can anyone please share the resources?

**Comment by ZYSzys** [comment]
Ah, maybe `event loop` is indeed bit of intricate.😅

IMHO, there are plenty of resources about event loop in the internet right ?

Here may be one of them: [message-queue-and-event-loop](https://github.com/leonardomso/33-js-concepts#9-message-queue-and-event-loop)

**Comment by stevemao** [comment]
Questions should asked https://github.com/nodejs/help

**Comment by ghost** [comment]
@akshayarise ：StackOverFlow is always your best friend when asking questions of knowledge.
https://stackoverflow.com/questions/tagged/node.js

**Comment by ZYSzys** [comment]
It seems that there are enough reply for you @akshayarise , closing it.

**Comment by ghost** [comment]
Hi,

sure



*Thanks & Regards,*
*Akshay Kumar*
*(Node.Js Developer)*
GitHub <https://github.com/akshayarise> CodeChef
<https://www.codechef.com/users/akshaycool> Twitter
<https://twitter.com/akshayarise> LinkedIn
<https://www.linkedin.com/in/akshay-kumar-93841654>
