### ISSUE TITLE
irc: bad link sending to porn site, maybe domain changed ownership

### ISSUE THREAD

**Issue by june07** [nodejs/nodejs.org#1939]
Whilst trying to use IRC today I ran across this in the #node-dev channel.  The banner gives a link to http://nodeirc.info (see attachment)... but I don't think that is Node.js material.

![screenshot 80](https://user-images.githubusercontent.com/11353590/49887521-6f3cc780-fdf1-11e8-98c8-56e950d4b500.png)

Domain history shows that the domain was used before for Node.js so not sure what happened:
https://web.archive.org/web/20180809005727/http://nodeirc.info/

Similar PR opened in node codebase https://github.com/nodejs/node/pull/24967. 

I think this change needs to be made to the Freenode account...

**Comment by richardlau** [comment]
cc @ljharb @MylesBorins since you are the current ops in #node-dev.

**Comment by richardlau** [comment]
> Domain history shows that the domain was used before for Node.js so not sure what happened:
> https://web.archive.org/web/20180809005727/http://nodeirc.info/

The archived version of the pages link to https://github.com/williamkapke/nodeirc/issues so also cc @williamkapke

**Comment by ljharb** [comment]
Already updated in #node.js; just did it in #node-dev.

**Comment by stevemao** [comment]
Seems like link is removed on node.js. Can we close this issue?

**Comment by fhemberger** [comment]
Checked, link has been deleted on both channels. Closing.

**Comment by ljharb** [comment]
It’d be great to get the same info rehosted somewhere else tho.
