### ISSUE TITLE
pt-br: Missing pages not falling back to english version

### ISSUE THREAD

**Issue by Drieger** [nodejs/nodejs.org#1952]
* **URL**: https://nodejs.org/pt-br/about/
* **Browser Version**: Google Chrome - Version 71.0.3578.98 (Official Build) (64-bit)
* **Operational System**: Linux Ubuntu 16.04

A new version of pt-br translation was recently added https://github.com/nodejs/nodejs.org/pull/1947, but the links to pages other than Home are returning 404 instead of falling back to the English version. Testing it locally it seems to work correctly.

![image](https://user-images.githubusercontent.com/1836388/50215435-242f3100-036a-11e9-86f0-0bb3901c9a12.png)

I'm not sure if we should include all folders/files to the `pt-br`, or if it should get these from the `en` if it does not exist in the specific language. If the first option is the correct I can open a new PR copying these files.

**Comment by fhemberger** [comment]
@Drieger Thanks for pointing this out. The fallback to English is configured in the 'build' repository, I already submitted a PR.

**Comment by Drieger** [comment]
Thanks, @fhemberger :smile:

**Comment by glaucia86** [comment]
@Drieger during this wkd I will translate the others pages. Thanks for report! :)
