### ISSUE TITLE
Translation to Arabic. In progress

### ISSUE THREAD

**Issue by celyes** [nodejs/nodejs.org#1967]
Hello everyone.
I would like to inform everyone that we've started the translation for nodejs.org website to Arabic at the repo nodejs.ar , InterstellarClub organization

@InterstellarClub/nodejs.ar

Any help is most welcome.

@celyes , @Aissaoui-ahmed, @InterstellarClub

**Comment by ouadie-lahdioui** [comment]
Hi guys, 

Very good idea. I'll be interested to help on it.

Are you in slack ? I juste create the channel #arabic feel free to join.

**Comment by celyes** [comment]
@ouadie-lahdioui 
great! I'll talk to my teammates to divide the tasks so we can work faster.
We'll keep in touch :)

**Comment by ghost** [comment]
@Trott：Kindly add him to the @nodejs/nodejs-ar for translation discussion :)

**Comment by celyes** [comment]
> @Trott：Kindly add him to the @nodejs/nodejs-ar for translation discussion :)

404: Not found.

**Comment by Trott** [comment]
> @Trott：Kindly add him to the @nodejs/nodejs-ar for translation discussion :)

I'm not on the TSC at the moment so I should not be handling team additions/removals. (That will hopefully change shortly.)

Localization teams are the purview of @nodejs/community-committee as I understand it, so maybe the chair of CommComm can handle this if there's no other process involved? /ping @amiller-gh
