### ISSUE TITLE
docs: Wrong spelling in 'writeUint16LE'

### ISSUE THREAD

**Issue by liuzeyafzy** [nodejs/nodejs.org#197]
There is a wrong spelling in  'writeUint16LE'. It makes me who is a newbie confused.
page: 'api/buffer.html'

```
b.writeUint16LE(0x90ab, 0);
```

The function should be 'writeUInt16LE'.

**Comment by evanlucas** [comment]
This documentation is actually stored in https://github.com/nodejs/node/blob/master/doc/api/buffer.markdown. Would you be interested in opening a pull request to fix that? I went ahead and opened an issue at https://github.com/nodejs/node/issues/3223
