### ISSUE TITLE
Translation to arabic: RTL style issue

### ISSUE THREAD

**Issue by Aissaoui-Ahmed** [nodejs/nodejs.org#1970]
I have an issue with the website when translating to a language written from RTL
and i tried a workaround that worked perfectly, but it adds so many lines of code to the styling file ... is it ok to use this as a final [solution ](https://github.com/InterstellarClub/nodejs.ar/blob/b6c3f8400e0bcae35007cb7c7aa780ce8de9cd6c/layouts/css/styles.styl#L25)?

@nodejs/nodejs-ar , @celyes , @InterstellarClub

**Comment by fhemberger** [comment]
Nooo, please don't do this. 😁
We already have the RTL flag, so `html[dir="rtl"]` is sufficient.
See: https://nodejs.org/ar/

Please also don't simply duplicate **all** the CSS, when you just want to change three lines of code.

What you want is:

```stylus
html
  // all the regular styles
  ...

html[dir="rtl"]
    .has-side-nav
      aside
        float right

      article
        margin-right 220px

    @media screen and (max-width: 480px)
      .has-side-nav
        article
          margin-right 0px
```

**Comment by celyes** [comment]
Thank you so much, @fhemberger .
your code works just perfectly.
note that i added this line to the article element:
```stylus 

margin-left: 0;

```
so the margin left is set to 0 when the website language is a written from RTL , so the final code to add is like this:
```stylus

html[dir="rtl"]
    .has-side-nav
      aside
        float right

      article
        margin-right 220px
        margin-left 0

    @media screen and (max-width: 480px)
      .has-side-nav
        article
          margin-right 0px

```

**Comment by Aissaoui-Ahmed** [comment]
thank you @fhemberger
