### ISSUE TITLE
Links to third-party content on nodejs.org – what should be included?

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs.org#1971]
Extracted from #1923: We're were already discussing more broadly in #1932, #1963, #1964 and #1965 what kind of third party content should be collected on the Node.js website at all (also making sure that it doesn't mean this content is promoted/endorsed by the Node.js Foundation in any way).

/cc'ing @Trott (who rose two of the issues mentioned above) and @amiller-gh (as this is also relevant for @nodejs/website-redesign).

**Comment by aymen94** [comment]
I think to should include on Node.js website every free no profit content.

**Comment by Trott** [comment]
> I think to should include on Node.js website every free no profit content.

I think you're saying to include any content if it is free and not-for-profit. If so, I disagree strongly. There is plenty of free non-profit content that is also of extremely low quality. This approach would serve the content-providers, but that's not who we should be serving. We should be serving users.

**Comment by aymen94** [comment]
> > I think to should include on Node.js website every free no profit content.
> 
> I think you're saying to include any content if it is free and not-for-profit. If so, I disagree strongly. There is plenty of free non-profit content that is also of extremely low quality. This approach would serve the content-providers, but that's not who we should be serving. We should be serving users.

Obviously, the content must be approved by the Node.js Foundation.
It must be free and accessible to anyone

**Comment by ovflowd** [comment]
Closing as a stale issue. If any parties still feel that this subject is relevant, please feel free to reopen the issue 🙇
