### ISSUE TITLE
Correction in template code.

### ISSUE THREAD

**Issue by AnkitRawat805** [nodejs/nodejs.org#1978]
res.statusCode is not valid. instead of res.status

at line number 7 https://nodejs.org/en/about/

**Comment by ZYSzys** [comment]
Hi, if I understand correctly, `res.statusCode` is valid, there isn't the API called `res.status`.
You can see here: https://nodejs.org/dist/latest-v11.x/docs/api/http.html#http_response_statuscode

**Comment by fhemberger** [comment]
`res.status()` only exists in Express, we're using Node's `http` module, where the property is called `res.statusCode`.
