### ISSUE TITLE
Nightly code coverage url is linking to homepage

### ISSUE THREAD

**Issue by jeromecovington** [nodejs/nodejs.org#1983]
* **URL**: https://coverage.nodejs.org/en/
* **Browser version**: Chrome - Version 70.0.3538.110 (Official Build) (64-bit)
* **Operating system**: MacOS - Version 10.12.6

https://coverage.nodejs.org/en/ is loading the same url as https://nodejs.org/en/

It's entirely possible that the nightly coverage reports have moved, and I just don't know where to find them.

It should be noted though that https://coverage.nodejs.org is still linked from https://www.nodetodo.org/next-steps/

**Comment by vsemozhetbyt** [comment]
Maybe this is somehow connected: https://github.com/nodejs/build/issues/1659

**Comment by rvagg** [comment]
https://coverage.nodejs.org/ working again now that nodejs/build#1659 is being resolved (no `/en/` btw).
