### ISSUE TITLE
404: Page could not be found

### ISSUE THREAD

**Issue by coxato** [nodejs/nodejs.org#1984]
* **url: https://nodejs.org/dist/v10.15.0/node-v10.15.0-linux-x86.tar.xz**:
* **browser: chromium 71.0.3578.98 (Build oficial) Built on Ubuntu**:
* **OS: kubuntu**:

hi, the page https://nodejs.org/dist/v10.15.0/node-v10.15.0-linux-x86.tar.xz is not available
I try to update nodejs in my 32-bits pc with kubuntu but not working

the command: `sudo n stable` not working, and show this error `Error: invalid version 11.6.0`
I think it's because the page in nodejs.org is not found

**Comment by fhemberger** [comment]
We dropped 32bit support for Linux binaries starting v10.0.0:
https://github.com/nodejs/build/issues/885

Sorry, you have to compile it yourself from source:
https://nodejs.org/dist/v10.15.0/node-v10.15.0.tar.gz

**Comment by coxato** [comment]
thanks
