### ISSUE TITLE
 SunOS Binaries 32-bit not found

### ISSUE THREAD

**Issue by ZYSzys** [nodejs/nodejs.org#1985]
* **URL**: https://nodejs.org/en/download/
* **Browser version**: *
* **Operating system**: *

On the Additional Platforms section of download page, when click SunOS Binaries 32-bit version, it showed 404 and said `ENOENT: no such file or directory`

![screen shot 2019-01-15 at 6 52 47 pm](https://user-images.githubusercontent.com/23313266/51176049-e8e73a00-18f6-11e9-8c6c-083d2b54b8d1.png)

Link: https://nodejs.org/dist/v10.15.0/node-v10.15.0-sunos-x86.tar.xz
Refs: almost same as #1984

**Comment by ZYSzys** [comment]
If this Node.js version is no longer supported, maybe we should drop this part down from the download page.

**Comment by rvagg** [comment]
:thumbsup: it was dropped for Node 10.
