### ISSUE TITLE
"SunOS" should be "SmartOS" in downloads page.

### ISSUE THREAD

**Issue by Alhadis** [nodejs/nodejs.org#1987]
"SunOS" is misleading, because it could be taken to mean *"any OS derived from SunOS"*, which includes Oracle Solaris. Node.js's binaries (naturally) don't run on Solaris 11.3+, nor will they compile.

Updating that wording could save the next poor fool who lost 2 hours of his life debugging before noticing that only SmartOS is listed in the [supported platforms](https://github.com/nodejs/node/blob/master/BUILDING.md#supported-platforms-1) table. :-)

**Comment by fhemberger** [comment]
/cc @nodejs/build 

All binaries are still labeled `sunos`.

**Comment by rvagg** [comment]
`sunos` is in the tarball name for historical reasons .. we did discuss changing that once but it never happened. It's one of those things that are difficult to do without breaking workflows for many people. We also have zero plans to ship real Solaris builds fwiw.

I'm +1 on changing the wording on the website if we have it anywhere.

**Comment by richardlau** [comment]
> 
> 
> `sunos` is in the tarball name for historical reasons .. we did discuss changing that once but it never happened. 

For reference: https://github.com/nodejs/build/issues/500
