### ISSUE TITLE
Nightly coverage report outdated

### ISSUE THREAD

**Issue by jeromecovington** [nodejs/nodejs.org#1988]
* **URL**: https://coverage.nodejs.org/
* **Browser version**: Chrome - Version 70.0.3538.110 (Official Build) (64-bit)
* **Operating system**: MacOS - Version 10.12.6

At https://coverage.nodejs.org/ I am only seeing coverage up to January 10, 2019 (it's January 16 as of this writing).

**Comment by mhdawson** [comment]
I see the same thing.  There have been a few issues with machines on which the coverage job runs, and it may also be a change that landed as well.  Hoping to look at that later today.

**Comment by mhdawson** [comment]
We also had some unrelated issues with the main node.js site hosting but until we get the jobs generating the updates working again there is no evidence there is a problem on that side.

**Comment by mhdawson** [comment]
One related issue: https://github.com/nodejs/node/pull/25543.  There is still something else going on with the main job but we need 25543 landed as at least part of getting the coverage jobs going again.

**Comment by mhdawson** [comment]
nodejs/node#25543 is now landed and coverage job is now working again and should run nightly, but now need to see if the issues with the main site have affected the replication of the data.

**Comment by mhdawson** [comment]
I think main site looks good.  We should see updates to the coverage data going forward.

@jeromecovington, please confirm you think things are ok again and then close.

**Comment by jeromecovington** [comment]
URL shows updated coverage (with a week missing). Thanks!
