### ISSUE TITLE
Web Survey Report 2018 "Correlated Technologies" section broken

### ISSUE THREAD

**Issue by watson** [nodejs/nodejs.org#1997]
The [Correlated Technologies](https://nodejs.org/en/user-survey-report/#Correlated-Technologies) section on the latest Web Survey Report is broken in Chrome.

This is what the graph looks like:

![image](https://user-images.githubusercontent.com/10602/51526800-6d741400-1e33-11e9-82e8-1504ab36eb7f.png)

Just a big blank white space and a lot of text all on top of each other.

**Comment by fhemberger** [comment]
Hmm, works for me: Chrome/Mac 71.0.3578.98
Which Chrome version/OS are you using?
Are you blocking iframes (e.g. running an ad blocker)? 

![](https://user-images.githubusercontent.com/153481/51706840-f0f25880-201f-11e9-98a7-406c8d49fc92.png)

**Comment by fhemberger** [comment]
@watson Can you provide more information?

**Comment by fhemberger** [comment]
Closing this for now, feel free to reopen if the problem still persists.
