### ISSUE TITLE
Prepare for v4 LTS and v5

### ISSUE THREAD

**Issue by rvagg** [nodejs/nodejs.org#200]
From https://github.com/nodejs/node/issues/3000 where this question is something to be resolved by the @nodejs/website WG:
- [x] How do publicise and promote LTS lines? Does @nodejs/website have ideas on how to make this happen when we have something called "LTS" and then start to get new "Stable" releases with a `5` at the front? Ideally, users will be self-selecting and would end up with the kind of release suited to them, perhaps we need to outline on the front page of the website and/or on the download page why you would choose LTS over Stable?

Until the first item in the list @ https://github.com/nodejs/node/issues/3000 is resolved I think you need to be prepared for the following scenarios:
1. a v5 and a v4 LTS: this will be the eventual situation no matter what but this is a possible scenario from **next week** onward
2. a v4 LTS _only_: do you do anything special for this or just treat it as yet another v4? It's possible we have this scenario **next week**

Also, we probably should have wording for what LTS actually means, to put _somewhere_, feel free to kick that over to @nodejs/lts and make them do it if you want, either open a new issue and describe exactly what you need or add it in https://github.com/nodejs/LTS/issues/43.

**Comment by phillipj** [comment]
Will there be changes to https://nodejs.org/dist/index.json?

**Comment by Fishrock123** [comment]
cc @nodejs/evangelism 

@mikeal can we bring anyone from foundation-level marketing in to discuss this?

**Comment by rvagg** [comment]
@phillipj perhaps a `lts` column/field in index.json and index.tab would be good, it could include the codename for lts releases

**Comment by phillipj** [comment]
@rvagg sounds like a good plan. I'll could do some tests with that in mind for scenario 1, probably in the weekend / early next week.

For scenario 2, as long as file structures on /dist/ stays the same and we find it in index.json, no changes would be needed for us. Although adding some hard coded LTS strings around could be helpful to emphasize it, e.g. `Current version: v4.x.x LTS` on the frontpage

**Comment by bnb** [comment]
From an Evangelism perspective, there shouldn't be much of a problem. Weekly or twice-weekly tweets, as well as listing of updates in blog posts, are easy. However, will we be attempting to pull people in to either using or contributing to LTS? Will it have independent contributors, outside of core?

**Comment by phillipj** [comment]
Alright, to get the ball rolling I'll post some screenshots with some minimal changes necessary to host _two_ release lines at the same time. All kind of feedback is much appreciated!

I'm thinking we should keep it as simple as possible to download the version of node most devs will use, which I've been told is `stable`, soon to be v5.

On the frontpage an LTS-link could been added beneath the big green download button, sending users directly to e.g. https://nodejs.org/dist/v4.2.1/. 

![screen shot 2015-10-15 at 21 19 42](https://cloud.githubusercontent.com/assets/1231635/10525570/c2808778-7385-11e5-9981-045c40c5e992.png)

As for the download page, a couple of links could be added to do some JS toggling of the URLs in the download matrix. An explanation of what LTS is and its pros/cons should also be added, either as a new section on the download page, or a completely new page which explains the release lines in great detail with content provided by @nodejs/lts as mentioned in https://github.com/nodejs/LTS/issues/44.

![screen shot 2015-10-15 at 21 39 14](https://cloud.githubusercontent.com/assets/1231635/10525576/c78239d8-7385-11e5-80ec-05511653c5a1.png)

Any thoughts?

**Comment by jasnell** [comment]
I would much rather see the two releases side by side with clearly marked
download buttons for each rather than having LTS behind some easily
overlooked small link text.

**Comment by mhdawson** [comment]
Yes, my first preference is that if you don't choose carefully you end up with the LTS release.  ie unless you know what you are doing and know that you want the latest/greatest you end up with an LTS release.

**Comment by phillipj** [comment]
> I would much rather see the two releases side by side with clearly marked
> download buttons for each rather than having LTS behind some easily
> overlooked small link text.

Understandable. I appreciate when website are focused on the most important part(s) which should be relevant for the majority of users. On the other side, we cant really predict what our users really want before seeing the download figures, although we'll ofc influence those numbers by just having one button from the get go.

**Comment by srl295** [comment]
Could there be something user focused like: "looking for updated solid and
stable? → LTS • want to try out the latest features? → latest"

So try to switch based on the users self identification.

**Comment by phillipj** [comment]
Thanks for your input so far! A couple of new screenshots:

#### 1) Two green buttons side by side

<img width="456" alt="skjermbilde 2015-10-18 kl 22 09 47" src="https://github-cloud.s3.amazonaws.com/assets/1231635/10566394/6f22ed10-75e6-11e5-8ab7-ce65632165e8.png">

#### 2) User oriented texts w/links

<img width="495" alt="skjermbilde 2015-10-18 kl 22 15 10" src="https://github-cloud.s3.amazonaws.com/assets/1231635/10566395/74165b72-75e6-11e5-8ba9-ddd44c258372.png">

If I misunderstood your thoughts @jasnell @srl295, just say the word and I'll happily do some changes.

Anyone got a favorite amongst those two alternatives?

**Comment by fhemberger** [comment]
I prefer the first one. People tend to skip reading the "small print", so IMHO it's better to have some big shiny buttons in this case.

**Comment by evanlucas** [comment]
+1 to the first one. I like it a lot.

**Comment by stevemao** [comment]
+1 to big buttons

**Comment by Fishrock123** [comment]
+1 Buttons, can we maybe get some hover text?

**Comment by Fishrock123** [comment]
Also, maybe we should have some slightly different coloring associated with them.

**Comment by mhdawson** [comment]
How about moving some of the text from 2 into the buttons ?  Maybe the "Solid and Stable"
 for LTS and " Latest features" for Stable

**Comment by phillipj** [comment]
![screen shot 2015-10-19 at 19 02 23](https://cloud.githubusercontent.com/assets/1231635/10584737/fb5f73fe-7693-11e5-855a-76bec0dbb5fe.png)

Would that cover your needs for some hover text @Fishrock123?

**Comment by Fishrock123** [comment]
Maybe. But we need to change it from having a `stable` in each.

Perhaps we should have the lts description be how many months it's supported?

**Comment by Fishrock123** [comment]
(the stable branch is **stable**)

**Comment by mhdawson** [comment]
Possibly "Solid and Supported" for  LTS ?

**Comment by Fishrock123** [comment]
Again, the stable branch is most definitely supported. :)

I think we need wording about the longevity of the LTS's support, not about it's supposed stability compared to the stable.

**Comment by phillipj** [comment]
> I think we need wording about the longevity of the LTS's support, not about it's supposed stability compared to the stable.

Sounds like something @nodejs/lts could help us with.

**Comment by rvagg** [comment]
How about:

LTS: "Mature and Dependable"
Stable: "Active Development", or "Latest Features" is fine too.

**Comment by wonderdogone** [comment]
Sometimes these things have a small but colorful "button'/link below that sais something like
"trying to decide which version you need?" 
that takes them to a place where they can understand the difference between the two and choose wisely. I don't like the idea of them navigating to another page for this but maybe simply a little drop down model(or whatever those are called) that explains in a few lines.

**Comment by phillipj** [comment]
Went with "Mature and Dependable" and "Latest Features" for LTS and Stable respectively in #260.

These taglines and other methods of explaining LTS/Stable differences should be discussed and iterated on going forward. As the v5 release is getting dangerously close (I assume), I think its time to merge the proposed changes ASAP, to ensure users of node.js **can** download these different versions as soon as they're available.

**Comment by srl295** [comment]
@phillipj  / all - should there a link to some text such as https://github.com/nodejs/LTS/  if users need more help? I'm seeing lots of confusion on twitter :(   Maybe "Unsure of which version?" 

Examples:
- Tomcat: [Which version?](https://tomcat.apache.org/whichversion.html)
- Python: [Wondering which version to use? Here’s more about the difference between Python 2 and 3.](https://wiki.python.org/moin/Python2orPython3)

**Comment by phillipj** [comment]
> should there a link to some text such as https://github.com/nodejs/LTS/ if users need more help?

Yes, it would be great if we could do a better job helping people choose version! Might be worth trying to resurrect the stale discussion in https://github.com/nodejs/LTS/issues/44.
