### ISSUE TITLE
Getting started guide would benefit from hint what to do after "Hello world example"

### ISSUE THREAD

**Issue by matkoniecz** [nodejs/nodejs.org#2011]
https://nodejs.org/en/docs/guides/getting-started-guide/ is nice but some kind of "Next"/"see Foobar" 

Currently there is no hint what would be a good next example to see as a beginner.

**Comment by fhemberger** [comment]
Each of the guides address very specific (advanced) topics. So having a "path" to follow doesn't make much sense.

But we are working on that for the upcoming website redesign, including a broad section of beginner friendly topics. You can already find some content here: https://github.com/nodejs/website-redesign/tree/master/documentation
