### ISSUE TITLE
Is it necessary to translate 'node-meetsup' and 'node-speakers'?

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#2022]
@nodejs/localization：I wonder whether it's necessary to translations for the two files ( 'node-meetsup' and 'node-speakers') ? 

In my mind, this is a sample submitted content so I don't think it necessary to do translations, because we submit them in English and keep alphabetically. On the other hand, it's rapidly increasing with more and more people.

![image](https://user-images.githubusercontent.com/40081831/52054141-7df45f00-2596-11e9-82e9-c7bf0144f7ac.png)

What I did now is to just translate the titles in 'site.json'. So what do you think of this?

**Comment by fhemberger** [comment]
I think that's fine for now. 👍
