### ISSUE TITLE
Docs css-style suggestion

### ISSUE THREAD

**Issue by VijitCoder** [nodejs/nodejs.org#203]
Current documentation is hard to read. Inserts of code are merging with plain text. I suggest change the style (see shots below). I just remove font-size and made that css description:

```
p tt, p code, li code {
    color: #040404;
    font-style: italic;
}
```

Оf course, you can change some more :)
## ![shot_before](https://cloud.githubusercontent.com/assets/8523131/10196609/336fdb3a-67ad-11e5-937f-14b2bf1a8ef0.jpg)

---
### suggest

![shot_after](https://cloud.githubusercontent.com/assets/8523131/10196610/33720914-67ad-11e5-91e4-f57427f562cd.jpg)

**Comment by inooid** [comment]
I would suggest treating it as code, going for a more code-like approach:

``` css
    font-size: 0.8em;
    color: #E54305;
    background-color: #f2f5f0;
    padding: 4px;
```

### My suggestion:

![asdf](https://cldup.com/MVFljwmewM-2000x2000.png)

**Comment by mikeal** [comment]
+1

**Comment by Qard** [comment]
I don't really like the italic thing. If anything, that disassociates it with being code, in my mind. I like the second suggestion. Keeping a basic, monospace look, but with some highlighting would be good. A subtle background-color box might work too.

**Comment by bnb** [comment]
+1 to @inooid. Would green be a better choice, given the branding?

**Comment by zlatanvasovic** [comment]
Is there still the issue with readability? The design has improved a lot since September 2015.

**Comment by VijitCoder** [comment]
Now it's pretty good, imho. Thanks.
