### ISSUE TITLE
Adding a Node.js Conferences section

### ISSUE THREAD

**Issue by lirantal** [nodejs/nodejs.org#2031]
In addition to keeping track of community Meetup events, should we also keep track of Node.js-related conferences?

**Comment by lirantal** [comment]
Happy to create a quick PR listing some of the Node.js events I'm aware of if there's interest in having this extra page on the website

**Comment by leannevau** [comment]
+1

**Comment by ZYSzys** [comment]
Close due to #2047 was merged.
