### ISSUE TITLE
Does 'banner' really need translation?

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#2035]
Hi all:

I notice that since we've forcely defined the banner's Text as the fixed English string in our build.js:

```js
 loadVersions((err, versions) => {
    const source = {
      project: {
       ……
        banner: {
          visible: true,
          text: 'November 2018 security releases available, upgrade now',
          link: '/en/blog/vulnerability/november-2018-security-releases/'
        }
       ……
    }
```
And then in the template, we'll check whether the 'project.banner.text' has value or not? If yes, directly use banner's text, otherwises use 'label.banner'：
```html
 {{#if project.banner.visible}}
          <p class="home-version home-version-banner">
            <a href="{{ project.banner.link }}">{{#if project.banner.text}}{{{ project.banner.text }}}{{else}}{{{ labels.banner }}}{{/if}}</a>
          </p>
        {{/if}}
```
However in the recent months for upgration, it doesn't seem we directly use 'label.banner' but directly use 'project.banner.text', something like this following (For test only at local place)：

![image](https://user-images.githubusercontent.com/40081831/52402100-581f0b00-2afe-11e9-93fb-6bc786de217a.png)

On the other hand, since we cannot forsee when we will publish a new Important relase.... So do we really need this translation for banner? There're two ways:

**1) Remove the tranlation defined in the all kinds of languages' index page of 'label.banner', but just keep the English notification.**

**2) Remove the 'project.banner.text' and use the localization defined in the all kinds of languages.**

Which seems better?

**Comment by fhemberger** [comment]
So far, we avoided translation here on purpose. This banner is only used for important updates like security fixes, which need to be put out fast. 

Also, messages might differ, depending on the kind of security issue, so we can't wait until the message gets translated into every language.

(label.banner is still a relic of previous translation efforts)

**Comment by ghost** [comment]
>Also, messages might differ, depending on the kind of security issue, so we can't wait until the message gets translated into every language.

Yes, that's the reason why I say that there's no need of translation but just use the project.label.text. So no need to do translations IMO. But I just wait for others' opinions on this, thanks @fhemberger.
