### ISSUE TITLE
Adding write access for related Working Groups

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#205]
We are now reviewing a lot more content and it seems silly that the Website WG is the only ones with access to do it.

I suggest adding @nodejs/evangelism and @nodejs/documentation to this repo with write access (not admin) and note in the README that these WGs can commit content but should still wait for a Website WG contributor to commit code and template changes.

**Comment by fhemberger** [comment]
:+1: 

On the other hand, we have some issues her and also in the old nodejs/iojs repos about docs, but I seem unable to find the current repository to turn them into PRs. It would be super helpful to talk to someone from @nodejs/documentation to sort this out. /cc @phillipj

**Comment by phillipj** [comment]
Yupp, getting some insights into where docs are generated would be awesome! Tried pinging folks in #121 without much luck.

**Comment by bnb** [comment]
+1. Anybody else have feedback on this? If you have the time, leave a comment, no matter your opinion, so we can know the proposal is reaching you!

**Comment by mikeal** [comment]
Oh ya, I did this :) evangelism and documentation have write access :)
