### ISSUE TITLE
Unstable build advertised as latest?

### ISSUE THREAD

**Issue by ronaldpetty** [nodejs/nodejs.org#207]
Hello,

I noticed the current version of Node.js is 4.1.1.  On the front page of the website it says proudly:

Current Version: v4.1.1 (coming from Chrome on Mac)

That might be true, but does it make since to show an unstable release as the latest?  I could be old school and behind the times, but isn't the latest stable 4.0.z?  Shouldn't the front page show the stable build and force adventurous types to dig for the unstable?

Regards.

Ron

**Comment by rvagg** [comment]
Node isn't following the odd/even thing anymore, just pure semver. 4.1.1 is the latest and greatest and you should be using it in preference to 4.0.0. The 1 in the middle means that there were some feature additions and sometimes these will be fairly minor. Have a look at the changelog for items marked SEMVER-MINOR.

See https://medium.com/@nodesource/node-js-is-semver-8b3938ae8d24 for details.

**Comment by ronaldpetty** [comment]
Thank you rvagg.  I was led down this path because nvm showed 4.1.1 as unstable.  After updating nvm it is no longer unstable but showing stable.

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.28.0/install.sh | bash
source ~/.bash_profile

nvm list
       v0.10.38
->       v4.0.0
         v4.1.1
default -> 4.0 (-> v4.0.0)
node -> stable (-> v4.1.1) (default)
stable -> 4.1 (-> v4.1.1) (default)
iojs -> N/A (default)
