### ISSUE TITLE
2018 user-survey-report display issues

### ISSUE THREAD

**Issue by me-rina** [nodejs/nodejs.org#2095]
Windows 10 1809 build 17763.316; screen resolution 1366x768
Tested in browsers:
- Firefox Dev 66.0b8 private, ad-block plus
- Firefox 65.0.1 private, no ad-block
- Chrome 72.0.3626.109 private, no ad-block
- IE 11 11.316.17763.0 
- Edge 44.17763.1.0

Related issues #1997 and #1672 did not match this problem. 

Issues:

- If browser not full screen, text does not fit the browser window and there is no horizontal scroll bar
- side nav bar doesn't play nice with main content

screen shots from firefox 65

window width 1216: 

![image](https://user-images.githubusercontent.com/10367744/53032804-94773300-343d-11e9-83dc-446138d16637.png)

window width: 1366 (full screen):
![image](https://user-images.githubusercontent.com/10367744/53037197-8d552280-3447-11e9-8707-f1a39addf353.png)

Page load takes 10+ seconds in firefox.

**Comment by fhemberger** [comment]
Hi, sorry for that. This page has not been build by the website team, so we have some problems ironing out the glitches.

The long page load is because of the d3 visualization inside the iframe. 😞 
We have to come up with a way to fix this …

**Comment by me-rina** [comment]
No worries, and thanks. I wish I could help, but CSS is my bete noire. Add responsive and cross-browser and bootstrap and I'm practically catatonic! I'll close this because changing the browser zoom level mitigates the problem. Thanks again.
