### ISSUE TITLE
Update Security Policy

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#21]
We now have the security policy on the front page of nodejs.org (once we're ready to deploy the new website).

If there are any changes to be made to this policy please update https://github.com/nodejs/new.nodejs.org/blob/master/locale/en/security.md

@rvagg 
@nodejs/security
@evilpacket
@nodejs/tsc

**Comment by evilpacket** [comment]
This is super great! Thanks for letting us know.

**Comment by fhemberger** [comment]
Add notice, which legacy versions of Node.js receive security fixes, see:
https://github.com/nodejs/nodejs.org/issues/74
