### ISSUE TITLE
Use bot for dependency management

### ISSUE THREAD

**Issue by aymen94** [nodejs/nodejs.org#2113]
Many repos have management of automatic dependence,
Why not use a bot like:
[dependabot](https://dependabot.com/) or others.

otherwise, we have to do it manually.
#2112 

what do you think?
@nodejs/website

**Comment by JustinBeckwith** [comment]
FWIW, we use [renovate](https://renovatebot.com) in the google npm modules and love it.

**Comment by ZYSzys** [comment]
I’m +1 on renovate.

**Comment by fhemberger** [comment]
I've only been using greenkeeper so far, but I'm fine with everything that works.

It highly depends on the rights needed for the bot, as this is a security concern for the entire node.js github org. **So this must be approved by the org admins.**
(This has also been the reason so far that we still do this manually.)

**Comment by silverwind** [comment]
There is a non-zero risk that a dependency includes breaking changes in minor and patch releases. For that reason, I personally prefer to audit every dependency update manually. Tools like [updates](https://github.com/silverwind/updates) make this process simple and fast.

**Comment by bnb** [comment]
FWIW, I'm hugely in favor of Greenkeeper. I've used it personally, and the maintainers are long-standing (trusted?) members of the Node.js community.

Regardless of the tool we choose, this kind of automation is _a security feature_. It helps keep dependencies updated, which reduces the surface area that is available to attackers + reduces the burden on maintainers of code to resolve security issues that are introduced via stale dependencies.

**Comment by aymen94** [comment]
@bnb I thinks we should use it on many repos of the organization.
So we'll add it?

**Comment by zeke** [comment]
I've used Greenkeeper, Renovate, and Dependabot. My favorite is Dependabot, because it has lots of controls for things like automatically merging PRs that pass checks, or auto-merging a specific set of whitelisted (trusted) modules.

**Comment by XhmikosR** [comment]
I think we should move with dependabot. But before that we should definitely enable automated security fixes in the repo: https://help.github.com/en/articles/configuring-automated-security-fixes

**Comment by Trott** [comment]
> I think we should move with dependabot. But before that we should definitely enable automated security fixes in the repo: https://help.github.com/en/articles/configuring-automated-security-fixes

Automated security fixes are turned on for the repository (as of a few days ago, I think). IIUC, GitHub purchased dependabot and that's how automated security fixes are done. So I guess this can be closed?

**Comment by XhmikosR** [comment]
Nope, one still needs to add the dependabot app for normal dependency
updates and configure it optionally

**Comment by aymen94** [comment]
I think it has to be added **dependabot** or similar because is also configurable etc...

**Comment by XhmikosR** [comment]
Closing this since dependabot appears to be enabled now. 🎉
