### ISSUE TITLE
Text image is broken on mobile devices

### ISSUE THREAD

**Issue by WofWca** [nodejs/nodejs.org#2125]
* **URL**: https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick
* **Browser version**: Chrome x64 72.0.3626.119
* **Operating system**: Windows 10

Text image is broken on mobile devices.

![image](https://user-images.githubusercontent.com/39462442/53620425-e2561d00-3c2d-11e9-8f87-cf552eae0872.png)

Can be patched with CSS `white-space: pre;`:

![image](https://user-images.githubusercontent.com/39462442/53621002-087cbc80-3c30-11e9-8a9d-6db53f7375ef.png)

**Comment by ZYSzys** [comment]
@WofWca Thank you for your feedback. PR welcome :)

**Comment by ghost** [comment]
Chrome：70.0.3538.25，
Win10, x86, 
The page on my PC is, even if I use "white-space":"pre"
![pre](https://user-images.githubusercontent.com/40081831/53854446-78aa8a00-4004-11e9-8522-f02a5e451eb8.PNG)

**Comment by ItsClickspeed** [comment]
That's Strange!
![GabrielGodpro101's Advatar Sword](https://user-images.githubusercontent.com/48134914/54998700-2cb88880-4fa5-11e9-88ed-b1c5fbaea134.jpg)
❗

**Comment by AdityaSrivast** [comment]
@ZYSzys @WofWca Can I work on this issue, please?

**Comment by ItsClickspeed** [comment]
Of course!
=)
