### ISSUE TITLE
Library used to create Timeline view on Releases page

### ISSUE THREAD

**Issue by mattbhealy** [nodejs/nodejs.org#2159]
Looking to create a timeline similar to the one on the releases page:  https://nodejs.org/en/about/releases/

Can anyone point to me to what tech/library was used to create that?

Thanks!

**Comment by richardlau** [comment]
> 
> 
> Looking to create a timeline similar to the one on the releases page: https://nodejs.org/en/about/releases/
> 
> Can anyone point to me to what tech/library was used to create that?
> 
> Thanks!

It's a combination of https://github.com/nodejs/Release/blob/master/schedule.json and https://www.npmjs.com/package/lts.
