### ISSUE TITLE
Offline package installing or solution for ntml auth.

### ISSUE THREAD

**Issue by pedritin** [nodejs/nodejs.org#216]
I'm getting <b>Cache Access Denied</b> from my proxy when I try to get the package from http://registry.npmjs.com. I spoke with my domain admins and they say I can't do that because of domain policy. I don't know what to do cause I'm beginning and also I'm cuban and there's a lot of things that my proxy doesn't allow me to do. Please help!!

**Comment by mikeal** [comment]
This should be logged against npm, not against the Node.js website :)
