### ISSUE TITLE
Don't show download link for node.js >= v10 x86 linux

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/nodejs.org#2173]
* **URL**: https://nodejs.org/en/
* **Browser version**: n/a
* **Operating system**: Linux

See https://github.com/nodejs/node/issues/27113 - x86 binaries for Linux are no longer provided as of Node.js v10.0.0. The download.js script does not currently take that into account.

**Comment by Maledong** [comment]
@bnoordhuis：This should have been fixed at https://github.com/nodejs/nodejs.org/issues/1769.

And you cannot see the link you've mentioned in the live website：
![image](https://user-images.githubusercontent.com/40081831/55716593-f1e53480-5a29-11e9-8165-fe0af884dca9.png), from https://nodejs.org/dist/v10.15.3/.

Correct me if I take you wrong ;)

**Comment by Maledong** [comment]
@bnoordhuis & @DebasisBehera123 ：This should have been fixed at https://github.com/nodejs/nodejs.org/issues/1769.

And you cannot see the link you've mentioned in the live website：
![image](https://user-images.githubusercontent.com/40081831/55716593-f1e53480-5a29-11e9-8165-fe0af884dca9.png), from https://nodejs.org/dist/v10.15.3/.

Correct me if I take you wrong, and please give us the screenshot where you've found the link :)

**Comment by fhemberger** [comment]
@Maledong See #2174.

**Comment by fhemberger** [comment]
@bnoordhuis should be fixed with the latest update. Can you please again?

**Comment by bnoordhuis** [comment]
It looks fixed to me. Should I close this out or do you?

**Comment by ghost** [comment]
Thanks all, I'll help to close it, and if there's anything wrong, this can be re-opened :)
