### ISSUE TITLE
Home page links are wrong

### ISSUE THREAD

**Issue by onrweb** [nodejs/nodejs.org#2200]
Maybe I'm missing something, But..
Is it possible that the **10.15.3 LTS** is the one with the **Latest Features**
And the **11.14.0 Current** is the one **Recommended For Most Users**?

Looks like you've got it in reverse on:
https://nodejs.org/en/

**Comment by fhemberger** [comment]
No, version **v10** with long term support is recommended for most users, **v11** is "bleeding edge" (but also stable) with the newest features.
