### ISSUE TITLE
ARMv6 for 12.0.0 missing

### ISSUE THREAD

**Issue by mlibby** [nodejs/nodejs.org#2204]
https://nodejs.org/en/download/current/

Current Tab selected
Linux Binaries (ARM) row - ARMv6 link (https://nodejs.org/dist/v12.0.0/node-v12.0.0-linux-armv6l.tar.xz)

Expected tarball, got 404.

**Comment by fhemberger** [comment]
Hi, sometimes builds for certain platforms can take some time. To be sure, better have a look at the release notes: https://nodejs.org/en/blog/release/v12.0.0/

> ARMv6 32-bit Binary: Coming soon
> ARMv7 32-bit Binary: https://nodejs.org/dist/v12.0.0/node-v12.0.0-linux-armv7l.tar.xz

The links on the download page are auto generated from file names and the current version number, so an occasional 404 can happen. Sorry for that!

**Comment by richardlau** [comment]
See https://github.com/nodejs/build/issues/1677#issuecomment-486204349.

**Comment by mlibby** [comment]
Thanks to both of you. Very informative.
