### ISSUE TITLE
About "TL;DR" in the article as the title

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#2210]
Just a question about this fixed phrase at (https://github.com/nodejs/nodejs.org/blob/master/locale/en/docs/guides/dont-block-the-event-loop.md#tl-dr), because this phrase explains the process of Nodejs in the event and how to improve the speed of Nodejs' work.

I don't know why "TL;DR" for this phrase?  Why does it mean "Too Long Didn't Read"？

So IMO the title should be something like **"What to notice for improvement of efficiency for Nodejs in the event loop?"**

**Comment by ghost** [comment]
@nodejs/website：What do you think of this？

**Comment by davisjam** [comment]
An alternative title might be "Executive summary" or "Abstract" or similar.

**Comment by Trott** [comment]
Yeah, it basically means "Summary".
