### ISSUE TITLE
The "What are callbacks?" post has a broken link

### ISSUE THREAD

**Issue by oomengoo** [nodejs/nodejs.org#2211]
The "[What are callbacks?](https://nodejs.org/en/knowledge/getting-started/control-flow/what-are-callbacks/)" documentation has a link to "[What are the error conventions?](https://nodejs.org/articles/errors/what-are-the-error-conventions)" which is broken.  It should link to this [here](https://nodejs.org/en/knowledge/errors/what-are-the-error-conventions/) instead.

**Comment by ghost** [comment]
@oomengoo: Thanks for catching it, and here's the fixture, you can have a review :)
