### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#222]
just like the old iojs website was, shouldn't this website be (eventually) localized? forgive me if I missed something really obvious here, just thought I'd bring it up

**Comment by fhemberger** [comment]
That was the plan, yes. We wanted to wait until the English version was complete, which is the case now.

**Comment by bnb** [comment]
+1. We need to start rolling out information about localization and how to handle it. @mikeal You were the key player in setting up the io.js localization - do you have any input on how we should start from here?

**Comment by mikeal** [comment]
We need documentation on where to start localizing, how to build, etc. We can pull inspiration from the io.js site.

**Comment by mikeal** [comment]
Oh, and those docs should land in the README.

**Comment by ghost** [comment]
Opened a PR for adding localization instructions/config: #242

**Comment by fhemberger** [comment]
#242 is merged. Can we close this now or do you want to keep this issue for further discussion/planning?

**Comment by ghost** [comment]
Ideally, every translation WG should open an issue now, right? How about we ping them?

**Comment by bnb** [comment]
@sup A collaborator can ping all their teams in the org. @fhemberger You have my +1. Do we need more +1s for this? If not, feel free to do it - I can do it if you'd like, too.

**Comment by fhemberger** [comment]
I wrote a little script to add all localization team members from "nodejs/iojs-*" to the new team "nodejs/localization". It's way easier to mention everybody now.

**Comment by fhemberger** [comment]
@mikeal I also wrote a little script to rename the iojs-\* teams to nodejs-*. I can't run it myself, as I'm not organization administrator: https://gist.github.com/fhemberger/bea66aedbdba7a441ea4
Maybe this helps.

**Comment by sotayamashita** [comment]
@fhemberger Its issue is too old so I think it should be closed.
