### ISSUE TITLE
 Collab Summit Berlin 2019 is less than a month away, let's register ✍️ 

### ISSUE THREAD

**Issue by keywordnew** [nodejs/nodejs.org#2221]
This Collab Summit will be held before JSConfEU at the [Marriott Courtyard Berlin City Centre](https://www.marriott.com/hotels/travel/bermt-courtyard-berlin-city-center/?scid=bb1a189a-fec3-4d19-a255-54ba596febe2
).

The registration link is: https://www.eventbrite.com/e/openjs-collaborator-summit-tickets-55985971548 and the password is: collabsummit.

To get your visa for this event: Email visainfo@nodejs.org and cc ladyleet@nodejs.org after registration!

Call for Papers now open: https://github.com/nodejs/summit/issues/new/choose

Volunteers: We will work publicly on the agenda: if you are interested, we meet every week. Follow along or join us! nodejs/summit#135

Ref: nodejs/summit#152

_Y'all are amazing and it would be great to meet in-person ✨_

**Comment by alexandrtovmach** [comment]
The event has already passed, good to close the issue
