### ISSUE TITLE
Automated publishing to Medium

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#223]
Medium just released an API https://medium.com/the-story/taking-medium-to-the-next-level-cb7f223fad86 

It would be great if we could cross post all new blog content to Medium :)

-Mikeal

**Comment by bnb** [comment]
Obviously Medium provides an audience that's looking for content, but are there any drawbacks to it? For example, SEO, getting flagged as duplicate content by services, and so on?

**Comment by fhemberger** [comment]
As long as we can provide a canonical URL for Medium, this should be fine.

**Comment by mikeal** [comment]
We have pretty good metrics on both Medium and our own blog. Both get good traction, even when something is effectively on both. IMO we should post to Medium but only promote the link to _our_ blog on twitter and other social channels (which should also be automated).

**Comment by bnb** [comment]
Okay, I get it. +1 for this.

**Comment by raphaelokon** [comment]
Hey. Is this considered fixed then? I would like to tackle this one.

**Comment by fhemberger** [comment]
@raphaelokon This issue is still open, it would be great if you could look into it.

[FYI] Node.js on Medium: https://medium.com/@nodejs/latest

**Comment by raphaelokon** [comment]
@fhemberger Thanks. I just see that the posts on `https://nodejs.org/en/blog/`are not par with those on Medium. What is the proposed process for cross-channel publishing? Does the content strategy also include publishing security related news on Medium?

@mikeal I agree with that … social channels should only get the link to the blog post – `https://nodejs.org/en/blog/name-of-post`. The promotion of links could be automated though (I guess that is one of the things we are aiming for?) … so whenever someone publishes a Node.js blog post it gets mirrored to Medium and a link is posted to the defined social channels is dispatched.

**Comment by raphaelokon** [comment]
Worth reading … https://help.medium.com/hc/en-us/articles/217991468-Duplicate-Content-and-SEO

**Comment by karanjthakkar** [comment]
@mikeal @bnb Is this issue still valid or has this been sorted?

**Comment by fhemberger** [comment]
I'm closing this issue. On Medium, posts are written by the Node.js Foundation with a different focus than announcing releases (like on the blog here). So I don't think it makes sense to sync posts as they address different target groups.
