### ISSUE TITLE
Latest release post not showing up on the blog

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/nodejs.org#2239]
The latest release post somehow did not get published on the blog :disappointed:.

(https://nodejs.org/en/blog/release/v12.3.1/ does not exist)

**Comment by richardlau** [comment]
If the update is based on GitHub webhooks/notifications there is an ongoing issue: https://www.githubstatus.com/

![image](https://user-images.githubusercontent.com/5445507/58199152-c5c6ff80-7cc7-11e9-8cc5-f2eab4c4dd36.png)

**Comment by BridgeAR** [comment]
I guess that might be the reason.

**Comment by richardlau** [comment]
Looks like it’s there now.
