### ISSUE TITLE
Provide recordings of previous Code+Learn events 

### ISSUE THREAD

**Issue by merrisco** [nodejs/nodejs.org#2250]
As someone who is new to the Node project I found myself searching for a walk-through/guide that would help me become more involved with this project and understand the code base better. I found the Code+Learn page which talked about events that allowed new users to get started with Node.js core contributions. 

Currently the web page lists the next event on June 21st and 22nd. I assume that many of these event cover the same material for new users and thought that it would be useful if there were links to recordings of previous events that had taken place. 

By providing these links, new users would not have to wait for an upcoming event (which in this case is 2 weeks away) and would increase the accessibility to this information.  Additionally this may help to expend future events, since much of basic information would already be available and would allow for these event to go more in depth on newer topics. 

I would suggest having a simple link that directed users to these recording directly from the Learn+Code web page.

**Comment by Trott** [comment]
Recordings of Code + Learn events generally won't help. They're not traditional classes. There's not a walk-through. It's a few hours of people working individually, asking the person next to them for help, or asking mentors for help. For a step-by-step guide, try https://contributetonode.org/getting-started.

**Comment by alexandrtovmach** [comment]
Issue should be closed, I think
