### ISSUE TITLE
404 error with "Edit on Github" link on https://nodejs.org/ko/get-involved/

### ISSUE THREAD

**Issue by 2kindsofcs** [nodejs/nodejs.org#2251]
* **URL**: https://nodejs.org/ko/get-involved/
* **Browser version**: - 
* **Operating system**: -

"Edit on Github" throws 404 error page. it is linked to the page: https://github.com/nodejs/nodejs.org/edit/master/locale/ko/get-involved/index.md  

it looks like the url has to be modified. 
![screenshot-nodejs](https://user-images.githubusercontent.com/42531877/59162909-0e8a0f80-8b34-11e9-9076-a72fa9a1d541.png)

**Comment by alexandrtovmach** [comment]
Unfortunately, this file has no exist, and in that case you have 404. Seems like this page still not translated by @nodejs/nodejs-ko team.

**Comment by alexandrtovmach** [comment]
@nodejs/nodejs-ko could you add this page and all other still not translated pages from English template
