### ISSUE TITLE
Colaborator addition - Portuguese Brazil translation

### ISSUE THREAD

**Issue by khaosdoctor** [nodejs/nodejs.org#2257]
Hello, I'm currently with @glaucia86 and @Drieger maintaining the [NodeJS docs translation issue](https://github.com/nodejs/nodejs-pt/issues/80) however I do not have any permissions to edit either the issue or to accept PRs.

I wanted to ask if is it possible to add me as a colaborator or member to the org so I can help them a bit more :)

**Comment by glaucia86** [comment]
> Hello, I'm currently with @glaucia86 and @Drieger maintaining the [NodeJS docs translation issue](https://github.com/nodejs/nodejs-pt/issues/80) however I do not have any permissions to edit either the issue or to accept PRs.
> 
> I wanted to ask if is it possible to add me as a colaborator or member to the org so I can help them a bit more :)

@MylesBorins could see about it?

**Comment by glaucia86** [comment]
cc: @fhemberger

**Comment by fhemberger** [comment]
+1 from my side

**Comment by khaosdoctor** [comment]
Thanks! There are a few people asking to help there, I created a comment answer with our outdated data until now, and I'm updating that comment. So when and if I get the permission I update the whole issue 😄

**Comment by glaucia86** [comment]
cc: @Maledong @Trott hi!

The entire Brazilian Community decided to open an issue to assist in the translation Nodejs.org to pt-br.
@khaosdoctor  is one of the people I know and he would love to help with this **[ISSUE](https://github.com/nodejs/nodejs-pt/issues/80)**.
Would you approve him as a member of Nodejs.org to help us all in this **[ISSUE](https://github.com/nodejs/nodejs-pt/issues/80)**?

**Comment by Trott** [comment]
> cc: @Maledong @Trott hi!
> 
> The entire Brazilian Community decided to open an issue to assist in the translation Nodejs.org to pt-br.
> @khaosdoctor is one of the people I know and he would love to help with this **[ISSUE](https://github.com/nodejs/nodejs-pt/issues/80)**.
> Would you approve him as a member of Nodejs.org to help us all in this **[ISSUE](https://github.com/nodejs/nodejs-pt/issues/80)**?

Sure. They've now been sent an invitation to join `@nodejs/nodejs-pt`. Once they accept, they'll be added to that team. I'll close this out, but if they need to be added elsewhere, let me know!

(For being added to `@nodejs/website`, I'll wait for an explicit request from @fhemberger as they seem to be the one paying the most attention to that need over the last several years.)
