### ISSUE TITLE
Backpressure docs link to unhelpful wikipedia article

### ISSUE THREAD

**Issue by tlubz** [nodejs/nodejs.org#2265]
On https://nodejs.org/en/docs/guides/backpressuring-in-streams/, the linked Wikipedia article for the "backpressure" links no longer resolves to an article about backpressure as applies to data processing, but rather backpressure in fluid dynamics. Looks like someone removed the section on data processing from the Wikipedia page, since it apparently violated Wikipedia guidelines.

Perhaps a new more authoritative source could be linked.

**Comment by alexandrtovmach** [comment]
@tlubz Thanks for your attention and help
