### ISSUE TITLE
Help me to re-add my to the Collabrator, please

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#2273]
Hello all:

I was "Maledong" before.

Haven't seen you for ages, because there's something wrong with my mobile phone, and I had to reset it by clearing it all, and then I forgot to do backups for my Recovery codes, for the abandon wall of Two-Factor, I couldn't log in successfully. I now unlinked my account for a new one here, please re-add my to the collabrator of Nodejs.org.

Sorry for inconvenience...If added, please close it directly :)

**Comment by ZYSzys** [comment]
Maybe /cc @fhemberger

**Comment by fhemberger** [comment]
Sorry, I can't add people to the org, but @Trott or @MylesBorins can.

**Comment by MylesBorins** [comment]
Done
