### ISSUE TITLE
Wrong Chinese translation

### ISSUE THREAD

**Issue by Clark-G** [nodejs/nodejs.org#2275]
![image](https://user-images.githubusercontent.com/16334815/59827417-39ae0380-936b-11e9-98d4-569c7113d0f9.png)
There is an error about the Chinese translation of the first sentence in [this page](https://nodejs.org/zh-cn/docs/es6/), the translation "Node.js 不是为 V8 引擎构建的。" , is just opposite meaning of the original sentence, I think the correct translation should be "Node.js是针对V8引擎构建的". @nodejs/node-cn

**Comment by ZYSzys** [comment]
@Clark-G Thanks for pointing this out. Are you willing to make a PR to correct this ? Or we'll correct this later.

**Comment by Clark-G** [comment]
> @Clark-G Thanks for pointing this out. Are you willing to make a PR to correct this ? Or we'll correct this later.

Yes, I'm willing to, it will be my first PR on github😁

**Comment by ZYSzys** [comment]
Closed via #2276.
