### ISSUE TITLE
Local domains that redirect to nodejs.org

### ISSUE THREAD

**Issue by marvinschopf** [nodejs/nodejs.org#2277]
Hello,

I am the proud owner of the domain holdirno.de (which means getno.de in German) and would now put the same landingpage as on node.js.org (Issue #2253) there. Am I allowed to do that? 😁 

Thank you very much,
MarvMan

**Comment by Trott** [comment]
> Hello,
> 
> I am the proud owner of the domain holdirno.de (which means getno.de in German) and would now put the same landingpage as on node.js.org (Issue #2253) there. Am I allowed to do that? 😁
> 
> Thank you very much,
> MarvMan

Barring alterations that would be considered misuse of the Node.js trademark, I don't think we could or would do much to stop anybody from hosting that content at another domain name.

Here's the trademark guidelines in case it's relevant, but I imagine if you're not altering the logo, it's probably not an issue. https://nodejs.org/static/documents/trademark-policy.pdf

**Comment by marvinschopf** [comment]
> > Hello,
> > I am the proud owner of the domain holdirno.de (which means getno.de in German) and would now put the same landingpage as on node.js.org (Issue #2253) there. Am I allowed to do that? 😁
> > Thank you very much,
> > MarvMan
> 
> Barring alterations that would be considered misuse of the Node.js trademark, I don't think we could or would do much to stop anybody from hosting that content at another domain name.
> 
> Here's the trademark guidelines in case it's relevant, but I imagine if you're not altering the logo, it's probably not an issue. https://nodejs.org/static/documents/trademark-policy.pdf

Okay, thanks a lot. :)
