### ISSUE TITLE
Remove dead links from knowledge/other-resources

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs.org#2278]
Let's remove at least the two dead links in all languages.
Not sure on how the other content is still relevant today.

- [Nodejitsu Blog](http://blog.nodejitsu.com) → gone
- [How To Node](http://howtonode.org) → last update: 03/2016 
- [The Node Beginner Book](http://nodebeginner.org/) → ebook
- [Node.js Guide](http://nodeguide.com/) → gone
- [Node Tuts](http://nodetuts.com/) → last update: 04/2016 

Thoughts?

**Comment by Trott** [comment]
I'd be OK removing the page entirely, but certainly 💯 on removing the links that do not work.

**Comment by fhemberger** [comment]
+1 for removing the page entirely.

**Comment by khaosdoctor** [comment]
I'm kinda confused, which parts of the docs are to be removed? Can you please update me on this so I can remove from our translation efforts? (https://github.com/nodejs/nodejs-pt/issues/80)

**Comment by Trott** [comment]
> I'm kinda confused, which parts of the docs are to be removed? Can you please update me on this so I can remove from our translation efforts? ([nodejs/nodejs-pt#80](https://github.com/nodejs/nodejs-pt/issues/80))

We're talking about removing `locale/XX/knowledge/other-resources/` (where XX is the language code, like `en` for English and `ar` for Arabic). That directory currently only contains a single file.

**Comment by khaosdoctor** [comment]
Oh ok! Then I'll remove this whole section out of the issue so people don't get confused :)

---

One more question here. There's a PR for section 5.11 (https://github.com/nodejs/nodejs.org/pull/2281) which has been closed due to not translating knowledge. Is that part also covered in this discussion?

**Comment by alexandrtovmach** [comment]
Removed this page for all locales in PR. Please check
