### ISSUE TITLE
Website Admin WG Elections

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#228]
Now that the WG is quite large it's time to elect the admin group.

I'd like to nominate the top 4 contributors (based on GitHub "contributions" tab):
- @fhemberger 
- @mikeal 
- @rvagg 
- @phillipj 

Now, this is solely based on _this_ repo so if this misses people who have been engaged in building a lot of the content on the other resources that were migrated please nominate additional people to the group.

Nearly all work in this repo is accomplished without the admin group, the Website WG creates and merges most content. The admin group only resolves disputes and has the right to merge their own work (usually for administrative purposes). For more info https://github.com/nodejs/new.nodejs.org/blob/master/CONTRIBUTING.md

**Comment by phillipj** [comment]
I'd be more than happy to join! :) I'll definitely be watching and contributing going forward, although I cant promise to be just as responsive, as I've had more spare time than usual the last two months.

**Comment by Trott** [comment]
Is there a lot of docs stuff that's going to move to this repo? Might it make sense to consider a docs representative? @chrisdickinson or someone else in that WG?

**Comment by bnb** [comment]
+1 to all those. Also, I think @therebelrobot has demonstrated that he is capable of aiding in the type of decisions that the Admin group would be making.

**Comment by mikeal** [comment]
Ah yes, @therebelrobot is a contributor who contributed heavily to prior repositories and didn't show up in the top list for _this_ repo. Any objections to @therebelrobot being added to the Admin WG?

**Comment by bnb** [comment]
We should set a time frame for this, so we can roll it out. Close and add proposed admins (with support) on Friday? Or sooner?

**Comment by rvagg** [comment]
fwiw I only want to be able to have the ability to merge my stuff for releases, other than that I'd go through the standard process and prefer more active WG members to merge my PRs

**Comment by phillipj** [comment]
Is there still need for an admin group, if so are we waiting for more supporting votes or is it good to go?

**Comment by mikeal** [comment]
Closing, we got this in. if you want to nominate anyone else please create a new PR.
