### ISSUE TITLE
Use `Code owner` in Pull Request for translations

### ISSUE THREAD

**Issue by TiagoDanin** [nodejs/nodejs.org#2280]
# Suggestion
Use [`Code owner`](https://help.github.com/en/articles/about-code-owners) in Pull Request for translations and enabled [`Require review from Code Owners`](https://help.github.com/en/articles/enabling-required-reviews-for-pull-requests).

## Reason
Improves translation feedback.
This will be of great help to https://github.com/nodejs/nodejs-pt/issues/80#issuecomment-500569698.

## Example (Code Owner File)
```
# Locale - Team
locale/pt-br/* @nodejs/nodejs-pt
locale/fr/* @nodejs/nodejs-fr
# ... #
```

**Comment by AbdoliMR** [comment]
@TiagoDanin I can do it.

**Comment by okuryu** [comment]
https://github.com/nodejs/nodejs.org/pull/2710 will probably resolve this issue.
