### ISSUE TITLE
Russian localization team

### ISSUE THREAD

**Issue by alexandrtovmach** [nodejs/nodejs.org#2284]
I've made full translation of the website by my own and already merged it to master using direct PR #2243 

I'm happy to help with translation, but I need some help with process understanding and managing. Currently, official Russian [nodejs/nodejs-ru](https://github.com/nodejs/nodejs-ru) community is archived.

If it's possible I'd happy to be a contributor and/or owner of the [nodejs/nodejs-ru](https://github.com/nodejs/nodejs-ru) repository, to continue active localization process of Node.js

_P.S._ We've tried to ping old contributors of **nodejs-ru** community in PR discussion, but no luck.

**Comment by Trott** [comment]
@nodejs/community-committee I forget who is in charge of the internationalization effort right now or if there is a better team to @-mention than CommComm, but any help/guidance here would be greatly appreciated.

**Comment by amiller-gh** [comment]
✨Summoning @nodejs/i18n and @obensource ✨

**Comment by alexandrtovmach** [comment]
Ping @nodejs/i18n, @obensource

**Comment by Trott** [comment]
Someone more knowledgable, please correct me if I'm wrong, but my understanding is: The nodejs-ru repository wouldn't be the right place anymore. Translations can be PR'ed directly into this repository and/or there's CrowdIn which I admit I don't fully understand so someone else please explain. (Like, is that useful for translating the docs only? Or the website? Or both? Or something else?)

In the meantime, I'll add @alexandrtovmach to the @nodejs/nodejs-ru team so they can be part of the group pinged in case others submit Russian translations. I'll also add them to the Website team.

**Comment by alexandrtovmach** [comment]
@Trott Thanks for support and help. On CrowdIn we able to translate docs only, so basically need to understand the process of website translating.
