### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by yvele** [nodejs/nodejs.org#2289]
Looks like the Website is down 🤔 

https://www.isitdownrightnow.com/nodejs.org.html

![image](https://user-images.githubusercontent.com/4225430/60013750-85b8bb00-967f-11e9-8b44-b400fb7cc585.png)

**Comment by hugovk** [comment]
And it's back!

https://nodejs.org/en/

**Comment by reegnz** [comment]
Aaaaand it's gone again.

**Comment by moritzvieli** [comment]
Down for me as well. I'm also unable to install node locally, because the server is not reachable.

**Comment by moritzvieli** [comment]
...up again.

**Comment by erayalakese** [comment]
https://www.isitdownrightnow.com is down, too 🤣

**Comment by reegnz** [comment]
Could we get a postmortem on what happened?
A bunch of tools rely on that URL, and to me that screams that nodejs.org artifacts are not spread out on a CDN.
Maybe get a deal with a CDN like CloudFlare.

OR worse case scenario: It is behind a CDN and the CDN died!

**Comment by richardlau** [comment]
So https://www.isitdownrightnow.com/nodejs.org.html reports the site as down for everyone but it is working for me at work here in the UK (but there are reports in https://github.com/nodejs/node/issues/28403 that it's down for other users in the UK).

cc @nodejs/build-infra (?)

**Comment by richardlau** [comment]
From #general on Slack:
> Matt Cowley [12:24 PM]
> Just as an fyi, if you can’t access the site currently it is due to a rather significant network failure that Cloudflare has: https://www.cloudflarestatus.com/incidents/46z55mdhg0t5

**Comment by ghost** [comment]
Well, that sucks. Fallback CDN?

**Comment by ihsancemil** [comment]
https://nodejs.org/en/ works fine in Turkey. However https://nodejs.org/dist/v10.16.0/node-v10.16.0-x64.msi is still down so that I cannot download nodejs 👎

**Comment by ghost** [comment]
looks like an issue with ipv6

  curl -v https://nodejs.org/
     Trying 104.20.22.46...
   TCP_NODELAY set
     Trying 2606:4700:10::6814:172e...
   TCP_NODELAY set
   Immediate connect fail for 2606:4700:10::6814:172e: Network is unreachable
     Trying 2606:4700:10::6814:162e...
   TCP_NODELAY set
   Immediate connect fail for 2606:4700:10::6814:162e: Network is unreachable 

this instance does not have ipv6

**Comment by yvele** [comment]
Looks like other Websites are down or slow... Cloudflare? 🤔 

Edit: Yep https://www.cloudflarestatus.com/

![image](https://user-images.githubusercontent.com/4225430/60016176-b1d73a80-9685-11e9-9372-da1ef43b85bc.png)

**Comment by jrishabh55** [comment]
Cloudflare works for me but not nodejs, Netlify builds are broken we well

**Comment by richardlau** [comment]
There's http://unencrypted.nodejs.org as a fallback mirror.

**Comment by alexandrtovmach** [comment]
Website is down for me. Ukraine

**Comment by ericmdantas** [comment]
Down for me too. It looks like it could be related to Cloudflare's issues?

> Route Leak Impacting Cloudflare
> https://www.cloudflarestatus.com/incidents/46z55mdhg0t5

**Comment by benoitmugnier** [comment]
Not working for me too in Switzerland.

**Comment by gudvinga** [comment]
Not working for me too in Belarus.

**Comment by HaeSungDev** [comment]
Not working for me too in Korea

**Comment by CreatiCoding** [comment]
still to me...

**Comment by bnb** [comment]
This looks like a global outage. We are aware of this, and are doing what we can to resolve it as soon as possible ❤️

**Comment by elacalle** [comment]
Not working for me too in Congo

**Comment by rvagg** [comment]
Servers are healthy and CF is even reporting our load balancer origins as green. We're going to have to wait this one out, along with all the other sites impacted, sorry.

**Comment by gtzinos** [comment]
https://www.cloudflarestatus.com/

**Comment by rjurado01** [comment]
![image](https://user-images.githubusercontent.com/1703608/60018554-fd8ce280-968b-11e9-8d5f-53e4832e5f20.png)

@cloudflarestatus.com

**Comment by rvagg** [comment]
We're back up and other sites that were down seem to be responding again now. I think this can be closed.

**Comment by zawias-piwik-pro** [comment]
What's adviced to avoid such issues (not being able to download node binary) in the future? Is  http://unencrypted.nodejs.org  recommended fallback?

**Comment by bnb** [comment]
@rvagg I'll lock to collaborators for now – the site came back up for a minute earlier so perhaps it's good to leave it open for a bit just to ensure that it's actually resolved.

**Comment by bnb** [comment]
@rvagg still getting 500 errors on some servers – CloudFlare issue is still opened. Seems to be dependent upon what edge nodes you're hitting.

**Comment by bnb** [comment]
Going to unlock given that context.

**Comment by meoti** [comment]
up and running

**Comment by moritzgloeckl** [comment]
We're still having some issues on the Azure DevOps Build Pipeline, due to Node.js not downloading.

```
[section]******************************************************************************
[section]Starting: Install Node 10.14.1
[section]******************************************************************************
==============================================================================
Task         : Node.js Tool Installer
Description  : Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH.
Version      : 0.149.0
Author       : Microsoft Corporation
Help         : 
==============================================================================
Downloading: https://nodejs.org/dist/v10.14.1/node-v10.14.1-linux-x64.tar.gz
```

It's basically stuck at this.

**Comment by lszomoru** [comment]
@moritzgloeckl, based on the Cloudflare status it looks like the issue has been resolved. Could you please re-queue your Azure DevOps build? Thank you!

**Comment by martinwoodward** [comment]
Azure Pipelines able to run Node builds for me now that the [CloudFlare status](https://www.cloudflarestatus.com/incidents/46z55mdhg0t5) showing good.   Thanks everyone!

**Comment by moritzgloeckl** [comment]
@lszomoru @martinwoodward 

Can confirm, no issues on our side anymore. Thank you so much for looking into and fixing this.

**Comment by bnb** [comment]
If we go ~30 minutes from this comment without additional issues I'm happy to lock and close.

**Comment by jbergstroem** [comment]
> Well, that sucks. Fallback CDN?

Global network issues, not just Cloudflare. Relevant hacker news thread here: https://news.ycombinator.com/item?id=20262214
