### ISSUE TITLE
Links on "The built-in globals in Node.js" page are 404

### ISSUE THREAD

**Issue by cioffi42** [nodejs/nodejs.org#2322]
* **URL**: https://nodejs.org/en/knowledge/getting-started/globals-in-node-js/

all of the 'Read More' links and the 'Node REPL' link on this page are 404

**Comment by godcrampy** [comment]
I am willing to contribute to this issue. Is making apt changes to [this file](https://github.com/nodejs/nodejs.org/blob/master/locale/en/knowledge/getting-started/globals-in-node-js.md) enough?

**Comment by godcrampy** [comment]
Made all the required changes and fixed a few markdown errors for en, uk, ru, fa and pt-br docs.

**Comment by alexandrtovmach** [comment]
@godcrampy Thanks for contribution, great job 👍
