### ISSUE TITLE
Link is missing in about page

### ISSUE THREAD

**Issue by berdal84** [nodejs/nodejs.org#2328]
There is a strange text in the page https://nodejs.org/fr/about/ : 

"(...) Il instaure la **[boucle événementielle][]** (en) en tant que composant (...) "

Maybe a missing link.

**Comment by Trott** [comment]
@nodejs/nodejs-fr

**Comment by cedced19** [comment]
Yes it should be something like `[boucle événementielle](https://nodejs.org/fr/docs/guides/event-loop-timers-and-nexttick/)`

**Comment by cedced19** [comment]
I'll submit a PR.
