### ISSUE TITLE
AR : Bug in debugging-getting-started.md

### ISSUE THREAD

**Issue by 3imed-jaberi** [nodejs/nodejs.org#2332]
* **URL**: https://nodejs.org/ar/docs/guides/debugging-getting-started/
* **Browser version**: 75.0.3770.100 (Build officiel) (64 bits)
* **Operating system**: Windows 10

This page doesn't display well .. There is something wrong and I'm will sent a [PR](https://github.com/nodejs/nodejs.org/pull/2333) #2333 for fix that .. 
![bug-demo](https://user-images.githubusercontent.com/43971542/61171613-7e981500-a57a-11e9-8104-541606f2660a.png)

**Comment by celyes** [comment]
Have a look at #2333

**Comment by Aissaoui-Ahmed** [comment]
already merged
