### ISSUE TITLE
Log of unstable tests

### ISSUE THREAD

**Issue by phillipj** [nodejs/nodejs.org#234]
We're having some issues with unstable and flaky test runs on Travis. To list incidents and not forget about them, please add a comment with the name of the test of you experience it when creating PRs / merging to master.

**Comment by phillipj** [comment]
`anchorMarkdownHeadings/makes pretty slugs` when opening PR with unrelated changes #231. Fixed after two Travis restarts.

**Comment by mrkiffie** [comment]
Do we have any more details of the `anchorMarkdownHeadings/makes pretty slugs` test failure or steps to replicate?

**Comment by phillipj** [comment]
The short answer is no. Wasnt able to re-produce it locally, nor see anything unusual in the Travis logs.

**Comment by fhemberger** [comment]
Can we increase the timeout for those tests (`t.timeoutAfter(ms)`) and see if the situation improves? Default seems to be 500ms, maybe Travis takes sometimes just a tad longer?

**Comment by phillipj** [comment]
TBH I would like to see timeouts occur, before trying to increase the test timeouts. The regex code related to making these slugs should _really_ not use more than 500ms.

Very sorry I didnt copy the Travis output when it was failing :disappointed:

@fhemberger I've seen you commenting some PRs with "ignore the errors, Travis is drunk". Do you remember which tests were failing in those cases?

**Comment by stevemao** [comment]
I have some experience with unknown travis fails with some bigger project (https://github.com/ajoslin/conventional-changelog/commit/40ab546af99b230d1ec0a43e86605ee7786e9dcf and https://github.com/ajoslin/conventional-changelog/commit/104b3aae5d65e2fc73b7cbee48ff5f56050a50e8). I believe it might be travis own problem. Timeout might not be the issue (I've increased twice). The worse part is the error message doesn't tell much and it's hard to replicate :(

**Comment by phillipj** [comment]
Closing this for now, lets open it again if unstable tests starts showing again.
