### ISSUE TITLE
AR : Missing part in about/releases.md 

### ISSUE THREAD

**Issue by 3imed-jaberi** [nodejs/nodejs.org#2345]
* **URL**: https://nodejs.org/ar/about/releases/
* **Browser version**: 75.0.3770.100 (Build officiel) (64 bits)
* **Operating system**: Windows 10

There is a missing part of the page compared to [the original page](https://nodejs.org/en/about/releases/) ..

![image](https://user-images.githubusercontent.com/43971542/61580442-b4a53e00-ab12-11e9-8a11-c7a027f444f5.png)

**Comment by Aissaoui-Ahmed** [comment]
check this #2346 !
