### ISSUE TITLE
AR : translate  "schedule" !

### ISSUE THREAD

**Issue by MessaoudiHoussam** [nodejs/nodejs.org#2348]
*  URL : https://nodejs.org/ar/
* Browser version : Chrome 75.0.3770.142 (Official Build) (64-bit)
* OS windows 10 

![Untitled](https://user-images.githubusercontent.com/46626754/61594585-539a6a80-abe5-11e9-8e41-6a4964749feb.png)

translate this term or not !

**Comment by Aissaoui-Ahmed** [comment]
check #2346 !
