### ISSUE TITLE
404 errors on latest tar files

### ISSUE THREAD

**Issue by bw-theo-omtzigt** [nodejs/nodejs.org#235]
I am suddenly getting 404 errors on: 

https://nodejs.org/dist/latest/node-v4.1.2-linux-x64.tar.gz

**Comment by bw-theo-omtzigt** [comment]
Ah, because they just got updated to node-v4.2.0-linux-x64.tar.gz

mmmm, how do I deal with that in an automated setting?

**Comment by rvagg** [comment]
@bw-theo-omtzigt if this is from an automated process, don't use `latest`, query http://nodejs.org/download/release/index.json or http://nodejs.org/download/release/index.tab first and then jump directly to the file you want.
