### ISSUE TITLE
Add an lts download link in the dist

### ISSUE THREAD

**Issue by damccorm** [nodejs/nodejs.org#2351]
It would be nice if http://nodejs.org/dist/ contained an `lts/` directory. The scenario I'm after is I want to automate the downloading of the LTS version and would like to (a) avoid hardcoding in dates, (b) avoid having to manually update the LTS when a new version is introduced, and (c) having to parse a page to find the current LTS version. Also open to other ways to do this if I'm missing something!

**Comment by richardlau** [comment]
For reference, previous discussion: https://github.com/nodejs/node/issues/11173

The tool that creates the links is https://github.com/nodejs/nodejs-latest-linker

**Comment by damccorm** [comment]
Oh, sorry - missed that issue or I would've linked. Happy to move this discussion wherever its best - do you think that's https://github.com/nodejs/nodejs-latest-linker?
