### ISSUE TITLE
Join Request 

### ISSUE THREAD

**Issue by 3imed-jaberi** [nodejs/nodejs.org#2357]
I'm creating this issue because i'm interested in contributing to Node.js.
I have seen the degree of progress in the Arabic content .. I wanted to enrich this content and develop it with the current team .. You can see my recent contributions and I am really looking forward to more ..

Therefore , i ask you to invite me in these three teams ( collaborator ) :
- nodejs.org
- nodejs-ar
- i18n

Thank you everyone for your efforts in this great work.

**Comment by 3imed-jaberi** [comment]
@bnb , @Trott  , @MaledongGit , @mhdawson  ..

**Comment by Trott** [comment]
@3imed-jaberi I've added you to the `@nodejs/website` team which gives you write access to this repository.

**Comment by Trott** [comment]
@amiller-gh @bnb @obensource @richardlitt @zeke See above for request to join `@nodejs/i18n`. I'm not sure why they're asking for that particular group or what the process is for onboarding someone, but maybe you can point them to a link or something?

**Comment by Trott** [comment]
I think they just want repository access, not to be added to the i18n team specifically. There's probably no action to be taken there, to be honest.

I did take the liberty of adding them to the `nodejs-ar` team. There was only one other member and the associated repository is utterly inactive.

**Comment by Trott** [comment]
Closing as I don't think there's further action to take here.

**Comment by RichardLitt** [comment]
Thanks, @Trott

**Comment by 3imed-jaberi** [comment]
I will assist in all projects without exception ..
I applied to join these groups in an attempt to develop Arabic content for Node.js.

Thanks @Trott
