### ISSUE TITLE
Front page confusion

### ISSUE THREAD

**Issue by mscdex** [nodejs/nodejs.org#236]
With the release of 4.2.0, the front page of nodejs.org now shows:

Current Version: v4.2.0
Important [security release](https://nodejs.org/en/blog/release/v4.1.2/), please update now!

within the same green box. However the 'security release' link links to the 4.1.2 release blog entry, which is confusing since it makes it seem like 4.2.0 is a security release.

**Comment by mikeal** [comment]
We can probably remove this whole banner now.

**Comment by phillipj** [comment]
@jasnell just changed the banner text to include LTS and link to the release blog post instead with f0c4fcd787d5412e28b24801ff65
