### ISSUE TITLE
Enable repo option for the branches to be up to date before merging

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/nodejs.org#2425]

**Comment by XhmikosR** [comment]
Friendly bump. We might as well require Travis CI to pass too.

**Comment by Trott** [comment]
I'm not sure I understand the option you're speaking of....

**Comment by XhmikosR** [comment]
@Trott you need to go into settings -> branches and choose protect master. There you will see a lot of of options including this.

I would require Travis to pass for sure personally, too.

**Comment by Trott** [comment]
> @Trott you need to go into settings -> branches and choose protect master. There you will see a lot of of options including this.

Ah, I see. Documentation for anyone else who needs it: https://help.github.com/en/articles/defining-the-mergeability-of-pull-requests

**Comment by Trott** [comment]
@nodejs/website Thoughts?

**Comment by ZYSzys** [comment]
TBH, I'm kind of -1 on this, we will need to click `Update branch` almost every time when we are ready to merge PRs, it's a bit annoying.

Maybe see https://github.com/nodejs/nodejs.dev/issues/160.

**Comment by alexandrtovmach** [comment]
@XhmikosR What is the benefits of this?

**Comment by XhmikosR** [comment]
Annoying as it may be, but there's no other way than having stuff land that will break CI.

Also, I assume that currently the master branch isn't even protected, which is bad.

This is the de facto, at least for me:

1. the main branch is protected, nothing can land without CI passing, branch up to date and approvals
2. when I requested about the up to date option, I assumed the master branch would already be protected. This is more serious IMO
3. an example why we need branches to be up to date: we change the lint options on master, yet a PR is behind it. We'll see the failures after the merge without the option enabled

**Comment by alexandrtovmach** [comment]
I agree with you about protecting `master` branch, but I still can't understand the benefits of your request?

@Trott Could you doublecheck protecting branch?

**Comment by Trott** [comment]
> @Trott Could you doublecheck protecting branch?

We currently don't have any branch protection rules.

**Comment by XhmikosR** [comment]
Like I explained above, the benefit is that we will catch and issues before they land on master.

Now, we can't know beforehand if something will break the build, because if a PR branch is behind, it'll stay behind until it's merged.

**Comment by alexandrtovmach** [comment]
So we need turn on Travis CI checks of PR's and add rule to not allow merge it if something failed. I think it works better than "update branch" functionality

**Comment by XhmikosR** [comment]
Again, you can't know that way if something **will** break the master unless the option for the branches to be up to date is enabled.

**Comment by alexandrtovmach** [comment]
@Trott I think that's not a critical thing, because just collaborators has access to force push into `master`. But it's easy and good to add this rules. Who has permissions to repo settings?

**Comment by alexandrtovmach** [comment]
@XhmikosR Branch for the PR should be based on target branch (in our case it's `master`), and before making a PR ― developer should merge `target->current` to resolve conflicts etc. Then, on each PR, Travis run all the tests and if something failed ― nothing will go to the `master`.

**Comment by XhmikosR** [comment]
When there's no conflict, no one merges manually. I know I don't.

Hence why the button is useful.

**Comment by alexandrtovmach** [comment]
09:00
`feature-branch` created based on `master`

09:30
added new linter rules to `master`

10:00
`feature-branch` haven't conflicts and without merging `master` -> `feature-branch` created PR `feature-branch` -> `master`

10:01
passed Travis CI checks without new linter rules from 09:30 in `master`

10:02
PR merged


I think this scenario is edge case, and adding one annoying button to avoid just this it's not very profitable. Any suggestions from other developers?

**Comment by XhmikosR** [comment]
It's not a time issue. We have PRs open for weeks or months.

Seriously, I don't see how you don't see the usefulness of this. It's just a button to press which does not take a lot of time and ensures everything is in order **before** merging anything.

**Comment by Trott** [comment]
> Who has permissions to repo settings?

Anyone on the TSC (which would include me) and a few other people for various reasons, but basically I can do it if there's consensus.

**Comment by Trott** [comment]
I've protected the master branch on this repo. If that doesn't cause any issues in the next several days, we can look at doing more.

**Comment by XhmikosR** [comment]
@Trott I think everything is good, can you enable the option for branches to be up to date too?

**Comment by XhmikosR** [comment]
Oh, and require CI to pass if you haven't done it already.

**Comment by Trott** [comment]
Done and done. If it causes problems, we can always turn it off, of course.
