### ISSUE TITLE
is npm gzip script still useful?

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/nodejs.org#2429]
Being that now Cloudflare is used, which means we have Brotli compression available, is the npm gzip script still useful and/or used at all in practice?

https://github.com/nodejs/nodejs.org/blob/229e9f07febf2f877b8a2a2a4bbdc5500f12b1b9/package.json#L11

Actually judging from the response headers, it seems Brotli isn't enabled on Cloudflare. Any special reason for not doing this and getting rid of the whole gzip script and serving precompressed files?

**Comment by Trott** [comment]
@nodejs/build

**Comment by Trott** [comment]
> @nodejs/build

I know most people in build don't deal with the website infra, but I know *some* of them do. (@rvagg, I think?)

**Comment by rvagg** [comment]
> it seems Brotli isn't enabled on Cloudflare

because new shiny things get overlooked

I've turned it on. Give it a test and if it's working then I guess you can remove the "gzip" target. Remember to remove it from the "deploy" target too.

**Comment by XhmikosR** [comment]
Looks good so far, not a huge gain but I guess that's normal since you were using gzip level 9 before. The diff is 1.29KB.

I'd say someone monitors how things will go on the server side with load etc, since files aren't cache-busted and I don't know what the cache ratio is. If all is well, we drop the script and leave Brotli on.
