### ISSUE TITLE
releases rss feed filtering

### ISSUE THREAD

**Issue by shirbr510** [nodejs/nodejs.org#2434]
I have a slack bot that responds to rss from this feed https://nodejs.org/en/feed/releases.xml

the problem with this feed is that the feed is becoming cluttered with minor and patch release posts

can I somehow filter only on major releases?

I assume it is impossible due to the fact it's an xml file, but maybe there's a server in the middle that can accept a query 😄

**Comment by XhmikosR** [comment]
This is generated via 2 metalsmith plugins so you get what it is :)

**Comment by shirbr510** [comment]
well, I can see how it is used but it still doesn't answer my question

assuming you add an additional type called `majorReleases` to all the major releases articles, you could create an additional feed that will be used only for major releases without damaging the existing feeds 💯 

I hope you get what it is 😉

**Comment by ovflowd** [comment]
Extra keys such as `majorReleases` are not part of the RSS specification. You should be able to filter major/release versions by simply checking the version numbers and filtering on your side.

I'm closing this as not planned as we don't intend to break the RSS spec. Feel free to come with suggestions and reopen this issue. We use the `feed` npm package.
