### ISSUE TITLE
Web Server not bound to IPv6 address

### ISSUE THREAD

**Issue by thedufer** [nodejs/nodejs.org#244]
nodejs.org is advertising both IPv4 and IPv6 addresses:

```
> dig nodejs.org AAAA
...
nodejs.org.     235 IN  AAAA    2400:cb00:2048:1::6814:162e
nodejs.org.     235 IN  AAAA    2400:cb00:2048:1::6814:172e
```

```
> dig nodejs.org A
...
nodejs.org.     203 IN  A   104.20.23.46
nodejs.org.     203 IN  A   104.20.22.46
```

However, connections to the IPv6 addresses simply hang until the client times out.  This means that remote `nvm` commands, when `curl` chooses to try v6, take a minimum of 2 minutes.  This is true of the newest `nvm` (0.29.0).

**Comment by rvagg** [comment]
could you try again please @thedufer, they _should_ be good to go now

**Comment by thedufer** [comment]
I'm seeing the same issue.  After a curl, it just hangs trying to connect:

```
> curl -vvv -6 http://nodejs.org/dist/
* Adding handle: conn: 0x7fbaca804400
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fbaca804400) send_pipe: 1, recv_pipe: 0
* About to connect() to nodejs.org port 80 (#0)
*   Trying 2400:cb00:2048:1::6814:162e...
```

Eventually it just times out.

Both http and https work with the `-4` flag and time out with the `-6` flag.

**Comment by fhemberger** [comment]
Fails directly for me (http and https), `-4` works fine:

```
curl -vvv -6 http://nodejs.org/dist/
* Adding handle: conn: 0x7fea32806a00
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fea32806a00) send_pipe: 1, recv_pipe: 0
* About to connect() to nodejs.org port 80 (#0)
*   Trying 2400:cb00:2048:1::6814:172e...
* Failed to connect to 2400:cb00:2048:1::6814:172e: No route to host
*   Trying 2400:cb00:2048:1::6814:162e...
* Failed to connect to 2400:cb00:2048:1::6814:162e: No route to host
* couldn't connect to host at nodejs.org:80
* Closing connection 0
curl: (7) Failed to connect to 2400:cb00:2048:1::6814:172e: No route to host
```

curl 7.30.0 (x86_64-apple-darwin13.0) libcurl/7.30.0 SecureTransport zlib/1.2.5

**Comment by silverwind** [comment]
Works for me

```
$ curl -vvv -6 http://nodejs.org/dist/
* About to connect() to nodejs.org port 80 (#0)
*   Trying 2400:cb00:2048:1::6814:162e...
* connected
* Connected to nodejs.org (2400:cb00:2048:1::6814:162e) port 80 (#0)
> GET /dist/ HTTP/1.1
> User-Agent: curl/7.26.0
> Host: nodejs.org
> Accept: */*
>
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Date: Fri, 16 Oct 2015 17:45:15 GMT
...
```

curl 7.26.0 (x86_64-pc-linux-gnu) libcurl/7.26.0 OpenSSL/1.0.1e zlib/1.2.7 libidn/1.25 libssh2/1.4.2 librtmp/2.3

**Comment by fhemberger** [comment]
Ah, sorry. Works for me as well, IPv6 was disabled on my local router. :sweat:

**Comment by fhemberger** [comment]
@thedufer Can you please check if the problem is fixed for you, so we can close this issue?

**Comment by thedufer** [comment]
Sorry for the slow response.  Yeah, it looks better now.  I think my most recent comment was after running while I was on a VPN that doesn't play nicely with IPv6, so that may have been a false negative.
