### ISSUE TITLE
The Development get-involved guide needs to be updated

### ISSUE THREAD

**Issue by GlenTiki** [nodejs/nodejs.org#245]
From here onwards: https://github.com/nodejs/new.nodejs.org/blob/master/locale/en/get-involved/development.md#about-this-document

**Comment by fhemberger** [comment]
@mikeal Hmm, would it be enough to remove the entire "Repository Reconciliation Plan" section and the last paragraph [here](https://github.com/nodejs/new.nodejs.org/blob/master/locale/en/get-involved/development.md#release-process-and-branching-model)?

**Comment by bnb** [comment]
@fhemberger +1. Two more things to consider, though: Is the stability policy up to date? And do we still need the transitions of io.js working groups? +1/-1 on these and I'll fix them, as well as any other changes that are submitted.

**Comment by mikeal** [comment]
yup, we should remove that.

**Comment by bnb** [comment]
@mikeal comments on other suggested/questioned removals?

**Comment by fhemberger** [comment]
Also: What about the open questions and notes at the end of the document? At least the last paragraph has to be rephrased/removed:

> _Within io.js_, the Binary Abstraction Layer of choice is currently NAN. Several of the Node.js contributors are not yet sure if NAN is the right choice. This will need to be decided at some point. _For now, I've abstracted the abstraction layer in this document._

**Comment by fhemberger** [comment]
I created a [new branch](https://github.com/nodejs/new.nodejs.org/tree/get-involved) with an updated version of this document: https://github.com/nodejs/new.nodejs.org/commit/6b2708bba5712caf8035b31d89906631b692bf8c.

@bnb @mikeal Can you please review the changes and add further updates?

**Comment by fhemberger** [comment]
Updated the guide, closing this. If there are further changes required, please open a PR.
