### ISSUE TITLE
Supported Browsers

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/nodejs.org#2464]
As things are right now, I can't find what the supported browsers are.

I think we should first start by adding a .browserslistrc file in the repo root, which will be used by autoprefixer.

There's also some ancient code like a `document.querySelectorAll` polyfill https://github.com/nodejs/nodejs.org/blob/e8e7d3192c418282626083189463cdcfc3370947/static/js/download.js#L5-L28

which I'm pretty confident we can get rid of nowadays.

**Comment by silverwind** [comment]
> adding a .browserslistrc

I'd add it to `package.json` instead. I think that is the preferred method nowadays.

**Comment by XhmikosR** [comment]
I'd say both are fine, but keep in mind that with the package.json solution we hit [a pretty nasty bug](https://github.com/twbs/bootstrap/issues/26876) in the past. Personally, I just use a `.browserslistrc` file.

**Comment by silverwind** [comment]
Fine with me either way.

**Comment by XhmikosR** [comment]
Closing this since #2602 has landed
