### ISSUE TITLE
Advertising package

### ISSUE THREAD

**Issue by traverseda** [nodejs/nodejs.org#2477]
It looks like this project depends on https://github.com/feross/funding, a project intended to show advertising in a projects build log.

It's my understanding that right now there aren't any advertising messages actually showing, but if you're uncomfortable with the possibility of advertisements in build logs that's something you might want to look into.

**Comment by richardlau** [comment]
This came in as part of the update for standard to 14 (https://github.com/nodejs/nodejs.org/pull/2451). See https://github.com/standard/standard/issues/1381.

**Comment by Trott** [comment]
Note that this does not effect end users of the site. For that matter the package does nothing at this point and will do nothing in the future as the terminal-ad thing is basically abandoned. 

The dependency seems likely to be removed in a subsequent version of `standard`.

I don't think there's much reason to leave this open. However, if someone wants to open a pull request to eliminate it, any conversation can continue in the pull request. (Or for that matter, it can continue here. Comments on closed issues are certainly permitted.)
