### ISSUE TITLE
doc：How to replace old URLs in the history blog?

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#2491]
I notice that there're many old URLs that don't exist, but consider these are of old history blogs, we shouldn't change them to modify the historic tracks, and there're still some other URLs we cannot find real links of them.

e.g:

1. Not exist: http://events.linuxfoundation.org/events/node-interactive, change to 'https://events.linuxfoundation.org/events/nodejs-interactive-2019/', it won't jump automatically.
![image](https://user-images.githubusercontent.com/52018749/64217729-18cc6780-cef1-11e9-910b-c6021f510271.png)

2. Doesn't exist: http://sphinx.sg/? what to do for 'locale\en\blog\announcements\appdynamics-newrelic-opbeat-sphinx.md'.
![image](https://user-images.githubusercontent.com/52018749/64217746-2550c000-cef1-11e9-8d34-d798fce29d4f.png)

3. Fixture of 'http://events.linuxfoundation.org/events/node-interactive-europe' and 'http://events.linuxfoundation.org/events/node-interactive', they no longer exist, what to do now for 'locale\en\blog\announcements\cars-dynatrace.md'.

4. Maintance of 'http://openinterconnect.org/' not found in 'locale\en\blog\announcements\foundation-advances-growth.md', keep it?
![image](https://user-images.githubusercontent.com/52018749/64217694-faff0280-cef0-11e9-90a1-ad6a5fda6410.png)

Any other ideas or suggestions?

**Comment by ghost** [comment]
@nodejs/documentation

**Comment by XhmikosR** [comment]
@MaledongGit this is a duplicate of #2424. Please move the discussion there.

I plan to automate this eventually, see my comments in that issue.
