### ISSUE TITLE
False canonical link on your pages

### ISSUE THREAD

**Issue by rokaslit6** [nodejs/nodejs.org#2494]
* **URL**: https://nodejs.org/en/blog/ (your docs, download & other pages are affected)
* **Browser version**: Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)
* **Operating system**: macOS Mojave Version 10.14.5 (18F132)

Hi,

I have noticed that a lot of pages on node.js website have a canonical link https://nodejs.org/en/false/. This link is a 404 page.

Issue is that your organic traffic is tanking on numerous pages throughout the Node.js website that has this false canonical set.

This can mainly be seen on your /guides/ directory:
<img width="717" alt="Screen Shot 2019-09-04 at 11 13 58 AM" src="https://user-images.githubusercontent.com/30793715/64237575-47ecd400-cf05-11e9-99c0-ae0b5a063ab5.png">

I'm reporting this as a bug because I haven't thought of any reason to canonicalize your pages like this that would yield positive results.

**Comment by XhmikosR** [comment]
Locally, with `npm start` or `npm run build`, the generated HTML files don't have the issue.

I believe it's a regression in the slashes patch. I'll make a PR and remove the process.platform check.
