### ISSUE TITLE
Remove English commented out code from translations

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/nodejs.org#2510]
It seems it's common practice. We need another way for translators to follow the English files and know up to where they have translated. Maybe a simple HTML comment with the hash and then they can compare after that and see the diff.

Right now, many translations follow this practice which results in ~2x lines. All this does not come for free and it's bloating the codebase IMO.

Also, there's #2450.

**Comment by grodd** [comment]
Hey! Can you tell me more about this issue?

**Comment by nschonni** [comment]
EX: English text is copied into the translated documents like

https://github.com/nodejs/nodejs.org/blame/347682b75702a51d515b307aabd1e4766df55978/locale/ko/about/index.md#L9-L18

So if the English is updated, these are actually out of sync.

**Comment by ghost** [comment]
@XhmikosR and @nschonni, I know this so far, it seems this is Korean and Japanese's habit. So we don't need to worry about them.
But in order to be fair, I'd invite @nodejs/nodejs-ko and @nodejs/nodejs-ja to have a discussion about it. If they don't agree with your ideas, I have to close your issue.

**Comment by yous** [comment]
Commenting the corresponding commit hash of English file may work. But transition will take time as it requires re-sync of all translation files. I personally don't have objections to having process transition. But I have to listen how @nodejs/nodejs-ko think.

**Comment by XhmikosR** [comment]
It's also a habit in pt_BR, at least in some files.

**Comment by alexandrtovmach** [comment]
We decided to go with CrowdIn approach here https://github.com/nodejs/i18n/issues/72 and I'm now working on configuring it, so this issue will be fixed in near future.

**Comment by XhmikosR** [comment]
@nschonni I haven't followed the translations on his repo so if this is sorted or if it will be sorted, feel free to close this issue.

**Comment by nschonni** [comment]
Crowdin is hooked up now, but it's not really used. Primarily the changes comes as PRs to the repo

**Comment by ovflowd** [comment]
Closing this as the next.js migration removed the commented out english sources.
