### ISSUE TITLE
Lint inline Markdown JS

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/nodejs.org#2524]
This will ensure consistency. We should try doing this after #2523 and use the same config as upstream.

**Comment by nschonni** [comment]
Looks like it can be done with the markdown plugin https://github.com/eslint/eslint-plugin-markdown
I tried it with a --fix locally, but didn't PR anything since I find the "standard" config kind of makes a mess of the code

**Comment by XhmikosR** [comment]
Yup, this should go after #2523

**Comment by carterbancroft** [comment]
What's the status of this issue, is it still something that needs to be worked on?

If so, can you share an example or two of what needs linting?

**Comment by XhmikosR** [comment]
IMO yeah. Every .md file needs to be linted.

**Comment by carterbancroft** [comment]
Roger. I'm new here and just trying to get more context so please bear with me.

So, is there no linting on markdown files at all right now? From the code (and your PR here: https://github.com/nodejs/nodejs.org/pull/2557/files) it looks like there are markdown linting rules in place and linting scripts in package.json. Is this not happening?

Or, is it just the inline javascript within .md files that needs linting? If so any chance you could link me to a specific code block of something that needs linting as an example.

**Comment by XhmikosR** [comment]
This is issue is for linting JS code in the markdown files. You can search the locale files for the following:

```
```js
#or
```javascript
```

There are hundreds of instances. Ideally we should use the same linting used in the main repo so that we are consistent, so this might need to be done along with #2523

**Comment by carterbancroft** [comment]
OK gotcha, thanks.

So am I understanding correctly that there are still more linting rules from the node repo that should be implemented in this repo? I made the (probably faulty) assumption that this was the last step since this is the only remaining issue referenced in https://github.com/nodejs/nodejs.org/issues/2523. The rest are merged PRs.

**Comment by XhmikosR** [comment]
TBH, I'm not aware of the internals in the upstream repo. I know they use eslint while here we use standard, which is also using eslint under the hood.

**Comment by carterbancroft** [comment]
I see, so it sounds like https://github.com/nodejs/nodejs.org/issues/2523 should be figured out before there's any movement on this one. Maybe I should move conversation over there to try to get some context on that?

**Comment by XhmikosR** [comment]
Not sure which one should be tackled first.

/CC @Trott @MylesBorins

**Comment by Trott** [comment]
I don't know that it matters which one is done first, although I guess I'd default to doing #2523 first.

**Comment by carterbancroft** [comment]
Thanks, and just to clarify, this issue and https://github.com/nodejs/nodejs.org/issues/2523 won't be made moot with the website redesign, yeah?

**Comment by Trott** [comment]
> Thanks, and just to clarify, this issue and #2523 won't be made moot with the website redesign, yeah?

They might be, but to be honest, it's not clear to me that @nodejs/website-redesign  hasn't completely stalled. It might be unlikely to ever complete. Judging from https://github.com/nodejs/nodejs.dev/tree/master/meetings, they haven't had a meeting in almost six months.

(If that initiative is still going, great! But if not, my favored Plan B would be to iterate on this site and ditch the idea of a full-blown redesign and re-launch. No opposition to a full redesign. But I don't want something that's not going to happen to end up discouraging work here that could be valuable.)

**Comment by carterbancroft** [comment]
Roger that, that makes sense. I don't have much context context here so I appreciate the extra explanation :)

**Comment by XhmikosR** [comment]
This was fixed by @nschonni's #4287
