### ISSUE TITLE
Localisation support for anchor links in headings

### ISSUE THREAD

**Issue by mrkiffie** [nodejs/nodejs.org#258]
The current implementation to that resolved #52 only supports generating fragment identifiers that use the basic alphanumeric character range. With the current efforts of localisation, I've been thinking that better support for non-latin based scripts will be needed.

I've been wondering it extending it to support transliteration would be a sufficient solution?

I'm willing to work on extending the current implementation if it is something we need.

**Comment by fhemberger** [comment]
Closing this for now. Thanks for your offer, but so far we had no complaints from translation teams about that.
