### ISSUE TITLE
Web page broken link (404 error).

### ISSUE THREAD

**Issue by rafialhamd** [nodejs/nodejs.org#2603]
Web page:
[https://nodejs.org/en/knowledge/advanced/streams/what-are-streams/](https://nodejs.org/en/knowledge/advanced/streams/what-are-streams/)

The above page contains the below link that results in 404 page.
[pipe](https://nodejs.org/how-to-use-stream-pipe)

**Comment by XhmikosR** [comment]
Should think link to `/en/docs/guides/backpressuring-in-streams/`?

Or `/en/knowledge/advanced/streams/how-to-use-stream-pipe/`?

**Comment by XhmikosR** [comment]
NVM I'll make a PR
