### ISSUE TITLE
Web page broken link (404 error) ../what-is-try-catch/

### ISSUE THREAD

**Issue by rafialhamd** [nodejs/nodejs.org#2613]
Web page:
[https://nodejs.org/en/knowledge/errors/what-is-try-catch/](https://nodejs.org/en/knowledge/errors/what-is-try-catch/)

The above page contains the below link that results in 404 page.
[standard](https://nodejs.org/what-are-the-error-conventions)

**Comment by XhmikosR** [comment]
@rafialhamd No need to make a new issue, please close this and keep #2603 
All of those are fixed in #2604

**Comment by rafialhamd** [comment]
@XhmikosR Closed 'this' issue, as suggested.
