### ISSUE TITLE
Thanking contributors

### ISSUE THREAD

**Issue by Trott** [nodejs/nodejs.org#2632]
symfony.com has a box at the bottom of their main page titled "They Help Us Make Symfony" that thanks an apparently-random contributor. We should totally do something like this IMO.

<img width="1294" alt="Screen Shot 2019-09-30 at 1 45 28 PM" src="https://user-images.githubusercontent.com/718899/65917361-0af0f180-e38c-11e9-87c3-17a65f5dc277.png">

**Comment by jrjohnson** [comment]
That's my face! Which I bring up because there is some magic here in that it thanks you specifically if it knows who you are. If not, then it's random. Both of which I think you should steal (borrow).

**Comment by KeziahMoselle** [comment]
Can I work on this please ?

**Comment by Trott** [comment]
> Can I work on this please ?

No need to ask! Go for it!

**Comment by KeziahMoselle** [comment]
Thank you !
Is there anything I need to know first ?

**Comment by Trott** [comment]
> Thank you !
> Is there anything I need to know first ?

Yes. You can start with the README file.

**Comment by KeziahMoselle** [comment]
I mean, for the design and the location of the card (in the footer I guess ?)
Edit: I saw there was a contributor-list package in `/scripts/contributor-list` should I use it ? (I don't think so, but asking anyway) 😄

**Comment by Trott** [comment]
> I mean, for the design and the location of the card (in the footer I guess ?)
> Edit: I saw there was a contributor-list package in `/scripts/contributor-list` should I use it ? (I don't think so, but asking anyway) 😄

I don't have any good insight on how best to implement this, I'm sorry to say. I'd say look at what's there and try to comply with existing style.

**Comment by KeziahMoselle** [comment]
No problem ! Thank you

**Comment by Trott** [comment]
I'm going to remove the good-first-issue label here because there's a very active draft PR at https://github.com/nodejs/nodejs.org/pull/2635 to implement this.
