### ISSUE TITLE
aarch64 distribution missing?

### ISSUE THREAD

**Issue by jean** [nodejs/nodejs.org#2661]
Trying to install in [Termux](termux.com):

```
$ curl -sL install-node.now.sh/lts | bash
  Configuration
> Version:  v10.16.3 (resolved from lts)
> Prefix:   /data/data/com.termux/files/usr
> Platform: linux
> Arch:     aarch64

> Tarball URL: https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-aarch64.tar.gz
? Install Node.js v10.16.3 to /data/data/com.termux/files/usr? [yN] y
> Installing Node.js, please wait…
x Command failed (exit code 22): curl --silent --fail https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-aarch64.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

That returns a `404`. 

(Node is also available via `pkg install node` in Termux, but I guess the install script should also be working.)

**Comment by Trott** [comment]
@nodejs/build Should I transfer this issue to the build repo?

**Comment by richardlau** [comment]
It's more likely an issue for https://github.com/zeit/install-node. AFAIK we call "aarch64" "arm64" so the correct URL should probably be https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-arm64.tar.gz.

**Comment by rvagg** [comment]
https://github.com/zeit/install-node/blob/8714cc5d0331c909161c28abeeb1c86311281440/install.sh#L117-L121

not supported by them, but you could PR with:

```
    elif [ "${arch}" = "aarch64" ]; then
      arch=arm64
```

and it should be supported.

this issue can be closed.
