### ISSUE TITLE
Link is bad, update related files

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#2668]
The link `https://github.com/nodejs/community-committee/blob/master/GOVERNANCE.md` cannot be opened in all the languages at 'locale\\{some language folder}\about\community.md'. So How to change this?

@nodejs/website , An English change is enough, and we can continue to translate them into our languages.

![image](https://user-images.githubusercontent.com/52018749/66697601-b180af00-ed09-11e9-936b-166275cbf505.png)

**Comment by XhmikosR** [comment]
@MaledongGit No need to make a new issue for each 404 :)

I have all of these in #2424
