### ISSUE TITLE
Enable "Protected branches"?

### ISSUE THREAD

**Issue by stevemao** [nodejs/nodejs.org#267]
Since we have so many collaborators that have push access to this repo, can we enable protected branches for some branches to disable force pushing, prevent branches from being deleted, and require status checks before merging? Also as we need to create pull requests instead of pushing to the main branches directly, etc..., this partially helps to enforce everyone following the governance.

**Comment by mikeal** [comment]
Have we ever broken something by not having this?

**Comment by stevemao** [comment]
I don't think so. I think its a general good practice to enforce this anyway?

**Comment by evanlucas** [comment]
I'm not sure this is necessary...we don't have this on https://github.com/nodejs/node do we?

**Comment by stevemao** [comment]
This is relatively new so not many repos are doing it now.

**Comment by fhemberger** [comment]
Well, it would go along with our [contribution guidelines](https://github.com/nodejs/new.nodejs.org/blob/master/CONTRIBUTING.md#accepting-modifications):

> All modifications to the Node.js code and documentation should be performed via GitHub pull requests. Only the Website Admin group can merge their own work and should do so with great care.

Might be worth a shot, I haven't tested this feature in detail yet.

**Comment by stevemao** [comment]
I believe this is necessary for all nodejs projects. @nodejs/tsc @nodejs/collaborators

**Comment by Fishrock123** [comment]
-1 (At least for for `nodejs/node`)

It's git, there's nothing to loose. Many of us have full up-to-date copies.

`nodejs/node` master is purposefully force-pushed to correct meta-data and other problems here and there, though there is a "within 10-minutes" [rule](https://github.com/nodejs/node/blob/master/COLLABORATOR_GUIDE.md#i-just-made-a-mistake). This has been done on many occasions.

Moreover, it should definitely not be asserted as necessary. Force pushing exists for a reason.

**Comment by Fishrock123** [comment]
Keep in mind that force-pushing is _required_ to update Pull Requests, so people should have some understanding of it.

**Comment by mikeal** [comment]
> I believe this is necessary for all nodejs projects.

The only repo we auto-deploy is the website which is some justification for turning on additional restrictions although I don't think it's a good idea to add any potential barriers to contribution to solve problems we haven't actually experienced yet.

**Comment by stevemao** [comment]
@Fishrock123 sorry I didn't see "within 10-minutes" rule before (it's not mentioned in this repo). I would think node would forbid force push at all. If force pushing is required in the workflow then just ignore me :)

**Comment by jasnell** [comment]
Yeah, definitely -1 on this.

**Comment by trevnorris** [comment]
It's not just a -1, it's a technical infeasibility. Release branches are regularly rebased. If this were to happen then either 1) these branches would have to live on an individual's repo or 2) a new branch would have to be created with the rebased commits.

**Comment by silverwind** [comment]
Also -1 from me. Disabling force-push is a hinderance in the rare case it is needed.

[Here's](https://github.com/nodejs/node/blob/master/COLLABORATOR_GUIDE.md#i-just-made-a-mistake) the info on the 10 min rule.

**Comment by srl295** [comment]
-1 also. Not a good idea, not necessary with git. [background on protected branches](https://github.com/blog/2051-protected-branches-and-required-status-checks) .   

Following rules of governance is good though, so I appreciate the thought. There are too many exceptional cases, though.
