### ISSUE TITLE
Replace `request` with another package?

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/nodejs.org#2689]
We use request in two places, one is download.js which will be removed in #2688 and the other one is in https://github.com/nodejs/nodejs.org/blob/master/scripts/release-post.js.

Note that this won't remove any deps, since request is a node-sass dependency.

**Comment by MrBenJ** [comment]
Hey there @XhmikosR! I think I can help out with this. 

Would you be open to using something like `isomorphic-fetch` ? This is similar (if not the same) as fetch on the web. https://www.npmjs.com/package/isomorphic-fetch

It's also promised based as per the `release-post.js` script you've got there. 

Let me know if you feel this approach is OK, and I'll go ahead and get started :)

**Comment by XhmikosR** [comment]
Whatever does the job and is not the request package should be better nowadays :) Personally I was thinking about [got](https://www.npmjs.com/package/got), but I don't mind as long as it works.

Do note that this script isn't tested on CI.

**Comment by MrBenJ** [comment]
Sounds good! I'm going to go ahead and get started. PR incoming and I'll make sure you are a reviewer :)

**Comment by MrBenJ** [comment]
@XhmikosR - PR created :). I used got. Super cool stuff! 

I ran this script locally and saw it was making all the requests successfully. Hopefully this works out for you and the rest of the awesome nodejs team. Let me know if you need me to change anything up!

**Comment by nschonni** [comment]
Doesn't matter for this project, but the reason why swapping from `request` isn't always a good idea (even if it is frozen) is that most of the other libraries have issues with proxies.

**Comment by silverwind** [comment]
`got` will never support proxies so I would never consider using it. I like to use `make-fetch-happen` which comes with built-in proxy from environment support and it's also what `npm` uses.

**Comment by MrBenJ** [comment]
@alexanderchoi ? Wanna help out?
