### ISSUE TITLE
Completion persian language

### ISSUE THREAD

**Issue by mognia** [nodejs/nodejs.org#2696]
there is some pages in nodejs.org that did not translated in persian and also needs some fonts and typing issues

i can translate whole website to persian and complete all persian (farsi) pages and i could use "iranSans" font to persian texts if you want!

may i fork the project and start PR?

**Comment by Trott** [comment]
Current website translations for Farsi are in https://github.com/nodejs/nodejs.org/tree/master/locale/fa. Pull requests containing updates, additions, and corrections would be very much welcome.

Translations of docs happen within CrowdIn. I'm not sure what the status of Farsi translations there are, but hopefully someone on @nodejs/nodejs-fa or @nodejs/i18n can let us all know.

**Comment by mognia** [comment]
ok im going to start Completion farsi language
 after that we can decide to choose a font family for farsi alphabets

**Comment by m-esm** [comment]
I think "about" and "get involved" are pages that need most contribution

**Comment by AliSawari** [comment]
Unfortunately, Only some sections like "Security" and "About" have been translated to Persian.
I'm glad that you offered to complete the translations. I hope there will be contributions and help from other members of the team as well. Godspeed :sparkles:

**Comment by ovflowd** [comment]
Closing as translations are now done on Crowdin and anyone is free to contribute with translations there.
