### ISSUE TITLE
Current behind LTS by one Minor

### ISSUE THREAD

**Issue by tlhunter** [nodejs/nodejs.org#2706]
* **URL**: https://nodejs.org/en/ https://nodejs.org/de/
* **Browser version**: Firefox Current
* **Operating system**: Any

I'm not sure what the expected behavior is when a new LTS is cut and there's no odd version available. I think in the past the Current link has disappeared entirely.

![20191021082259](https://user-images.githubusercontent.com/551402/67219074-43f51280-f3dc-11e9-9190-547ece2b7121.png)

**Comment by richardlau** [comment]
This should be fixed tomorrow when 13.0.0 is released. We brought forward the 12.13.0 release by a day to avoid having them go out on the same day.

**Comment by nschonni** [comment]
Fixed by #2707
