### ISSUE TITLE
my npm(6.4.1) can not run on my windows 10 laptop in china mainland

### ISSUE THREAD

**Issue by pw007** [nodejs/nodejs.org#2708]
when I ran npm install in by customized UI source folder, error message popped up as:npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wdy_s\AppData\Roaming\npm-cache\_logs\2019-10-22T00_12_30_650Z-debug.log
[2019-10-22T00_12_30_650Z-debug.log](https://github.com/nodejs/nodejs.org/files/3753430/2019-10-22T00_12_30_650Z-debug.log)

**Comment by nschonni** [comment]
> npm ERR! This is an error with npm itself. Please report this error at:
> npm ERR! https://npm.community

As the message says, this isn't something with Node (or this website repo)
