### ISSUE TITLE
Blog entry code blocks are unreadable

### ISSUE THREAD

**Issue by platy** [nodejs/nodejs.org#272]
The text colour and background colour seem to be the same making the code unreadable.
https://nodejs.org/en/blog/uncategorized/profiling-node-js/
Checked on FF and Safari

**Comment by mrkiffie** [comment]
Here is another example of a non code preformatted tag
https://nodejs.org/en/blog/uncategorized/ldapjs-a-reprise-of-ldap/

**Comment by fhemberger** [comment]
Thanks, these were old blog posts, so they used different a code formatting structure.

**Comment by mrkiffie** [comment]
cool, do you think there is any value in going through those old blog posts to add code tags with prism classes?

**Comment by fhemberger** [comment]
@mrkiffie I just pushed a CSS fix, should be online soon (may take a while due to cloudfront asset caching).

**Comment by mrkiffie** [comment]
ok, I'll close the PR I opened for that same style fix.

**Comment by platy** [comment]
Much better, thanks!
