### ISSUE TITLE
Troubles with downloading nodejs archives

### ISSUE THREAD

**Issue by OriginalEXE** [nodejs/nodejs.org#2720]
* **URL**: https://nodejs.org/dist/v11.12.0/node-v11.12.0.tar.xz
* **Browser version**: Google Chrome 78.0.x
* **Operating system**: Ubuntu 18.04.3

Hello good people :wave: 

It seems like there are currently some problems with downloading the packages archives from the nodejs.org dist folder.

Specific archive in question is this one: https://nodejs.org/dist/v11.12.0/node-v11.12.0-linux-x64.tar.xz

The reason I raised the issue is that the same problem is happening in our Travis builds and so builds are failing. This also probably means that it's not an issue on my specific local network.

Not sure if something else would be helpful to note, let me know if I can help test something.

Thanks!

**Comment by bvitale** [comment]
I'm seeing this too, albeit intermittently, and for a different archive
https://nodejs.org/dist/v4.8.3/node-v4.8.3-linux-x64.tar.xz

**Comment by bazzas** [comment]
Got the same issue:
**URL**: https://nodejs.org/dist/v8.16.2/node-v8.16.2-linux-x64.tar.gz

**Comment by jaypeeZero** [comment]
Also failing our builds for https://nodejs.org/dist/v12.4.0/node-v12.4.0-linux-x64.tar.gz

**Comment by Rusox89** [comment]
For us is 10.16.3 via nodeenv.

```
nodeenv /home/admin/nenv --node=10.16.3 --npm=6.9.0 --prebuilt
* Install node (10.16.3Traceback (most recent call last):
  File "/usr/bin/nodeenv", line 9, in <module>
    load_entry_point('nodeenv==0.13.4', 'console_scripts', 'nodeenv')()
  File "/usr/lib/python3/dist-packages/nodeenv.py", line 890, in main
    create_environment(env_dir, opt)
  File "/usr/lib/python3/dist-packages/nodeenv.py", line 731, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/usr/lib/python3/dist-packages/nodeenv.py", line 600, in install_node
    download_node(node_url, src_dir, env_dir, opt)
  File "/usr/lib/python3/dist-packages/nodeenv.py", line 490, in download_node
    tar_contents = io.BytesIO(urlopen(node_url).read())
  File "/usr/lib/python3.5/http/client.py", line 461, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.5/http/client.py", line 609, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(16972253 bytes read, 3182957 more expected)
```

**Comment by Dr4K4n** [comment]
Having the issue with node-v12.10.0-linux-x64.tar.gz.
My Gitlab CI builds are failing with following error (java maven-frontend-plugin):
```
[INFO] Unpacking /root/.m2/repository/com/github/eirslett/node/12.10.0/node-12.10.0-linux-x64.tar.gz into /builds/stefan/insurancedb/src/frontend/node/tmp
[ERROR] The archive file /root/.m2/repository/com/github/eirslett/node/12.10.0/node-12.10.0-linux-x64.tar.gz is corrupted and will be deleted. Please try the build again.
```

When I try on my local machine with wget, the download is very slow...

**Comment by iffa** [comment]
Also seeing this, attempting to download https://nodejs.org/dist/v10.15.2/node-v10.15.2-linux-x64.tar.gz in an Azure DevOps build pipeline.

**Comment by OriginalEXE** [comment]
The issue seems to be resolved for now, at least on our side.

**Comment by edwardloveall** [comment]
This has also resolved for me.

**Comment by nschonni** [comment]
Looks like this is getting tracked by the OPs folks over on https://github.com/nodejs/build/issues/1993

**Comment by OriginalEXE** [comment]
Looks like it's happening again
