### ISSUE TITLE
1st Child_process run a file that itself runs another 2nd child_process. I get Error: listen EADDRINUSE: address already in use :::3002

### ISSUE THREAD

**Issue by JavierPons** [nodejs/nodejs.org#2753]
Node v12.8.0
Mocha 6.1.4
macOS Catalina v10.15

Error: listen EADDRINUSE: address already in use :::3002
    at Server.setupListenHandle [as _listen2] (net.js:1228:14)
    at listenInCluster (net.js:1276:12)
    at Server.listen (net.js:1364:7)

Im running a child_process(1st) in my app that runs a file with mocha that itself start a testing process and other child_process(2nd) and create something.   (That part of testing-creating (2nd process) it has been tested and works well, it takes about 2 min to solve all process, that is fine) So It should not be a problem with it. 
When I run the 1st process in few seconds shows this error Error: listen EADDRINUSE: address already in use :::3002: 
I have been reading and testing. What I understood is that the port is used maybe for 1st process_child?  or how there are several processes going on it gives error? other?

The 2nd process have to test 4 parts. It takes 2 min to create and test it and then show the data. So 1st child_process should be takes around 2 min too,  not so fast as now.

What can I do to solve this? Any help or explanation is welcome.  Before hands thanks for take your time with this issue.
I hope it is a bit clear what I mean.

**Comment by nschonni** [comment]
Hi, this is the issue tracker for the the Node website. Try https://github.com/nodejs/node

**Comment by JavierPons** [comment]
Ok, I find it. Nothing of killing processes.  It was running two different app.js at same time.  I gave the correct /path. and that was.
