### ISSUE TITLE
Autogenerate docs/index.html versions

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/nodejs.org#2759]
Currently this is done manually, but it would be nice if this was done automatically on build time.

**Comment by Trott** [comment]
IIUC, the idea is that changes like https://github.com/nodejs/nodejs.org/pull/2758 would be automated rather than PR'ed in manually by individuals. If so, 👍.

**Comment by YuuyaSatsuki** [comment]
> IIUC, the idea is that changes like #2758 would be automated rather than PR'ed in manually by individuals. If so, 👍.

**Comment by AbdoliMR** [comment]
Dear @XhmikosR can I do it?

**Comment by DantrazTrev** [comment]
Is this issue still open ?

**Comment by ovflowd** [comment]
Closing as the manual Component will be removed soon with the port of the `nodejs.dev` codebase.
