### ISSUE TITLE
Remove source/schedule.json?

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/nodejs.org#2767]
@Trott @rvagg since the deployment command always runs this, is there any reason for us to keep the file in the repository?

**Comment by Trott** [comment]
I suppose not, but I'd defer to @rvagg on that for sure.

**Comment by rvagg** [comment]
sounds fine to me, I think it's always been redundant but maybe helpful for local installs/testing?

**Comment by XhmikosR** [comment]
Hmm true. If we remove it it will require to grab the schedule for local development. It's OK if it's documented, I guess.

We could even add it in a `prestart` script maybe?

**Comment by XhmikosR** [comment]
@Trott similarly I see source/versions.json is outdated because it's generated on build time too.

I made a patch for schedule.json, but perhaps we should tackle both?

**Comment by ovflowd** [comment]
Closing as not relevant anymore. (File was removed already)
