### ISSUE TITLE
what-is-npm page has broken link to search.npmjs.org

### ISSUE THREAD

**Issue by fdavis99** [nodejs/nodejs.org#2782]
* **URL**:https://nodejs.org/en/knowledge/getting-started/npm/what-is-npm/
* **Browser version**:Chrome Version 78.0.3904.87 (Official Build) (64-bit)
* **Operating system**:Windows 10

https://nodejs.org/en/knowledge/getting-started/npm/what-is-npm/ The first paragraph contains a broken link to http://search.npmjs.org/ (result: "search.npmjs.org’s server IP address could not be found.")

The correct URL is https://npmjs.org, or https://www.npmjs.com/search?q=npm which shows an overview of all packages and some useful filters.

![nodejs org_what-is-npm](https://user-images.githubusercontent.com/5132443/69071854-ac91d800-09f8-11ea-91e7-d69e8d982632.png)

**Comment by Trott** [comment]
Aside: I wonder if anyone on @nodejs/npm might want to edit that page. For example, I believe the official line now is that `npm` does *not* stand for `Node.js Package Manager` so maybe that should be removed?

**Comment by Trott** [comment]
An alternative: Remove that page entirely. Anywhere it's linked can be linked to an appropriate page on npmjs.org where it is more likely to stay up-to-date.

**Comment by mikemimik** [comment]
Yeah I believe the link should jut be `npmjs.com`. Rather than what is currently there.

**Comment by fdavis99** [comment]
Google npm node.js; the 4th result is what-is-npm.

It's linked on https://nodejs.org/en/knowledge/

**Comment by Trott** [comment]
Getting even more ambitious, we could replace the entire knowledge base (which does not get frequent scrutiny or updates) with a link to the more recent https://nodejs.dev/. (Related: https://github.com/nodejs/nodejs.org/pull/2101)

**Comment by Trott** [comment]
@fdavis99 If you'd like to see a quick fix to this, you can open a pull request updating `locale/en/knowledge/getting-started/npm/what-is-npm.md`. (By the way, it looks like Brazilian Portugese translation at `locale/pt-br/knowledge/getting-started/npm/what-is-npm.md` may have the correct URL already?)

**Comment by Trott** [comment]
> @fdavis99 If you'd like to see a quick fix to this, you can open a pull request updating `locale/en/knowledge/getting-started/npm/what-is-npm.md`. (By the way, it looks like Brazilian Portugese translation at `locale/pt-br/knowledge/getting-started/npm/what-is-npm.md` may have the correct URL already?)

Er, that applies to anyone else who wants it, of course.

**Comment by fdavis99** [comment]
I haven't done anything like that before, not too comfortable jumping into
a project where I have no history. But thanks for the suggestion.
