### ISSUE TITLE
The date in change log for 13.2.0 is wrong

### ISSUE THREAD

**Issue by bertlea** [nodejs/nodejs.org#2796]
* **URL**: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V13.md#13.2.0
* **Browser version**: Chrome
* **Operating system**: Windows 7

The change log for v13.2.0 is showing "2019-21-19, Version 13.2.0 (Current), @MylesBorins".  The date is wrong.

**Comment by MylesBorins** [comment]
This has been fixed upstream

**Comment by MylesBorins** [comment]
https://github.com/nodejs/node/commit/f6de66ee711a4159355dfc05a3f5eadb3f1b8cc2
