### ISSUE TITLE
Add OpenJS Foundation logo

### ISSUE THREAD

**Issue by mcollina** [nodejs/nodejs.org#2805]
As part of https://github.com/openjs-foundation/project-onboarding/issues/1, we need to add the OpenJS Foundation logo to our website. 

The artwork are available at https://github.com/openjs-foundation/artwork/tree/master/openjs_foundation

**Comment by nschonni** [comment]
Is this something like how Linux Foundation banner is in the footer, or something else?

**Comment by mcollina** [comment]
I think we can remove the Linux Foundation collaborative process banner. Moreover, we should update the reference from the Node.js Foundation to the OpenJS Foundation.
Il 29 nov 2019, 21:59 +0100, Nick Schonning <notifications@github.com>, ha scritto:
