### ISSUE TITLE
"Ó revise la Agenda de LTS" Error ortográfico

### ISSUE THREAD

**Issue by rafo0183** [nodejs/nodejs.org#2836]
![image](https://user-images.githubusercontent.com/31549640/70999219-b4a46c80-20b7-11ea-9ff1-aaed1ada37ee.png)

En la página principal de nodejs.org traducido al español, la frase: 

> Ó revise la Agenda de LTS

Se encuentra con dos errores ortográfico. Debido a que la "Ó" debe escribirse como "O" (sin tilde) y la palabra "Agenda" debe ser con minúscula:

" **O** revise la **a**genda de LTS "

**Comment by nschonni** [comment]
Ping @nodejs/nodejs-es

**Comment by vrunoa** [comment]
@rafo0183 I'll create a PR for changing the "Ó to "O", I think we should keep "Agenda de LTS".
