### ISSUE TITLE
Minor bug in the example from 'Inheriting from EventEmitter' section

### ISSUE THREAD

**Issue by ManasJayanth** [nodejs/nodejs.org#285]
[Inheriting from EventEmitter](https://nodejs.org/api/events.html#events_inheriting_from_eventemitter) section requires `events` and incorrectly assigns to EventEmitter object.

```
const EventEmitter = require('events');
```

It should be

```
const EventEmitter = require('events').EventEmitter;
```

Even while [introducing EventEmitter class](https://nodejs.org/api/events.html#events_class_events_eventemitter), it mentions `var EventEmitter = require('events');` which should have been `var EventEmitter = require('events').EventEmitter;`

Run the code otherwise complains `TypeError: Object prototype may only be an Object or null`, which is understandable as object returned by simply requiring `events` does not have `prototype` property.

**Comment by evanlucas** [comment]
`const EventEmitter = require('events')` is actually the correct way of doing this now in v4.x

Refs: https://github.com/nodejs/node/pull/3509
