### ISSUE TITLE
Many links on the website are absolute instead of relative

### ISSUE THREAD

**Issue by sxa** [nodejs/nodejs.org#2865]
I had a quick look through the issues and couldn't see anything relating to this, but is there a reason why many of the links on the website explicitly include `https://nodejs.org` as a prefix? This makes it harder to test changes locally as you can't click on things on the main page without it going through to the main nodejs.org, not your local one.

I'm happy to take a look at changing this, but wanted to float the idea first in case there was a good reason why it was done like this.

**Comment by Trott** [comment]
> I'm happy to take a look at changing this, but wanted to float the idea first in case there was a good reason why it was done like this.

I'm unaware of any reason this can't be changed to relative paths. (You might discover the reason when you try, but I can't think of anything.)

**Comment by nschonni** [comment]
I think the only part you might run into issues with is the API docs and "dist", since those are pulled in from the Node as part of the deploy process

**Comment by XhmikosR** [comment]
There's a reason for the absolute part. So that the link checker works.

**Comment by XhmikosR** [comment]
I need specific examples as to what "fails". The idea is that every page/file that exists locally, shouldn't use the full URL so that it works locally properly and also the link checker works.

**Comment by sxa** [comment]
As an example - the LTS link:
![image](https://user-images.githubusercontent.com/6487691/71625703-206ef500-2be1-11ea-98b1-e44c4c8ac454.png)
The "Other downloads" link also goes straight to node.js org despite there being a local version (which was the specific one that tripped me up while testing a change)

**Comment by XhmikosR** [comment]
Yeah, those should be relative. Patches welcome, just don't forget translations too.
