### ISSUE TITLE
Recommended way to file docs issue forms a circularity

### ISSUE THREAD

**Issue by DerekNonGeneric** [nodejs/nodejs.org#2866]
This issue is related to user journey.

- The currently recommended way of filing a documentation-related issue is confusing.
- There is no documentation-related issue template.

## Circularity confusion

The [core repo suggests](https://github.com/nodejs/node/issues/new/choose) filing an issue in the Node.js website repo (this one).

> 🌐 Found a problem with nodejs.org?
> Please file an issue in the Node.js website repo.

[This repo suggests](https://github.com/nodejs/nodejs.org/issues/new/choose) filing an issue in the main Node.js repo (core).

> 📗 Node.js API Docs
> Please open an issue in the main Node.js repo, prefixed with "doc".

These instructions seem wrong and this is probably unintended.

## Missing issue template

If the intended way of filing documentation-related issues is in the core repo with the issue title prefixed with "doc", there should probably be an issue template for this. There's a frontmatter field named `title` that can pre-fill the issue's title field with `doc: `  for people.

---

I'm not sure if issues are being triaged during the holidays, but this could be medium to high priority item from a documentation perspective.

/cc @nodejs/documentation

**Comment by DerekNonGeneric** [comment]
- [x] I would like to work on this issue and submit a pull request.

Keep me posted on whether anyone would be available to review it.

**Comment by sam-github** [comment]
> Found a problem with nodejs.org?

^-- should say ".... outside of the docs"

> Node.js API Docs
> Please open an issue in the main Node.js repo, prefixed with "doc".

This is correct.

Lots of people are around.
