### ISSUE TITLE
Unable to download on MacOS Catalina ( version 10.15.2)

### ISSUE THREAD

**Issue by BrandonJGomez** [nodejs/nodejs.org#2889]
* **URL**:
* **Browser version**:
* **Operating system**:

Newest Mac Computer with current version:
MAC OS CATALINA (version 10.15.2)

SCREENSHOT ( not sure it will come thru)
<img width="526" alt="Screen Shot 2020-01-09 at 6 49 19 PM" src="https://user-images.githubusercontent.com/59710314/72121738-c07afb80-3310-11ea-83ad-8785f48df24f.png">

FOR MOST USERS VERSION
“node-v12.14.1.pkg” can’t be opened because Apple cannot check it for malicious software.  This software needs to be updated. Contact the developer for more information.

MOST RECENT VERSION
“node-v13.6.0.pkg” can’t be opened because Apple cannot check it for malicious software  .This software needs to be updated. Contact the developer for more information.

**Comment by richardlau** [comment]
This is being tracked in https://github.com/nodejs/node/issues/29216.
