### ISSUE TITLE
Local build is failing

### ISSUE THREAD

**Issue by leo** [nodejs/nodejs.org#29]
What am I doing wrong? I've ...
1. ... cloned this repo
2. ... executed `npm install` and `npm run serve` within it
## 

And [this](https://gist.github.com/leo/6de9f4857e203d60aaea) & [this](https://gist.github.com/leo/bc4621e1e5d47e5596cb) is all I got.

**Comment by fhemberger** [comment]
Okay, I haven't tested the build on iojs v3, but I can reproduce the second issue.

**Comment by fhemberger** [comment]
Hmm, I have installed iojs v3.0.0, removed `node_modules` and `npm install` works for me.
The issue you had with `npm run build` should be fixed with the latest commit.

**Comment by leo** [comment]
Works fine now, thanks! :blush:
