### ISSUE TITLE
Unblock translation process

### ISSUE THREAD

**Issue by alexandrtovmach** [nodejs/nodejs.org#2906]
@nodejs/website @nodejs/i18n
We need to unblock translation process here https://github.com/nodejs/i18n/issues/72. For that I need github **personal access token** generated under nodejs organization with next scopes:
![image](https://user-images.githubusercontent.com/28801003/72880957-8cd4a400-3d08-11ea-844c-399fcc579689.png)

Token will be used here:
![image](https://user-images.githubusercontent.com/28801003/72881337-43388900-3d09-11ea-84c7-243087b9474c.png)

Please help me with that

**Comment by Trott** [comment]
@nodejs/i18n: Should this be added to the @nodejs/tsc agenda so we can get this resolved one way or the other? Or is there still some work and/or data-gathering that needs to happen?

**Comment by bnb** [comment]
@trott is the TSC the proper body to decide this? i18n is technically a CommComm initiative. Not sure if there’s historical blocking of this from the TSC.

My assumption would be requests like this would be an admin issue. Is that accurate?

**Comment by jasnell** [comment]
i18n was transitioned to commcomm but if commcomm isn't making progress with it, it could be transitioned back

**Comment by obensource** [comment]
@Trott @bnb @jasnell we just started picking up progress again this past week ([had a WG meeting on Friday](https://www.youtube.com/watch?v=qlW40Ehk8aU)), and have generated action items including this. We need to repeat similar steps to [this](https://github.com/nodejs/build/issues/1220#issuecomment-379916791) in order to set this up. I took this as an action item this week, since we're planning on picking up the pace and meeting weekly.

👉 [Here's the recap](https://docs.google.com/document/d/1pV7NpXE429qw_T7BL6TZGVkL9Pyn9UkJ1_67hzvFtvs/edit?usp=sharing).

**Comment by bnb** [comment]
> i18n was transitioned to commcomm but if commcomm isn't making progress with it, it could be transitioned back

If there are folks who are willing to work on it, it shouldn’t matter where it lives - not sure how progress is associated with CommComm or TSC ownership. I would hope such a line in the sand does not exist ❤️

**Comment by obensource** [comment]
@bnb same here. Also i18n itself isn't so cut and dry already. There is diversity in the WG that spans between both TSC-oriented and CommComm-oriented work (which we [reassessed and reasserted at length during our last meeting](https://www.youtube.com/watch?v=qlW40Ehk8aU#t=19m3s)), and it is niche enough that it's within the best interest of the WG to maintain that diversity to mutually support each end (akin to a relationship between delegates and invited experts).

The work that @srl295 is doing to support Globalization in the runtime, alongside the work that @zeke, @richardlitt, myself and others have done to set up translation infrastructure is all good – I believe the hangup has been that I and the working group haven't done enough to foster reciprocity for maintainers so bottlenecks like this don't happen (as well as new contributors, and translators). That work is pretty much top priority on the agenda from our last meeting, and it really doesn't matter where the help comes from, or which top level committee contributors represent. We just want to see the hangups alleviated and progress made on an effort with so much potential to make node more accessible to an increasingly larger global audience. 👍

**Comment by Trott** [comment]
@bnb I suggested TSC because that's where integration requests usually get held up based on security concerns etc. But yes, the admin repo would be a fine place to take it instead. Maybe even add labels to get it on both TSC and CommComm agendas if necessary.

**Comment by obensource** [comment]
@Trott @bnb @jasnell apologies if I misread the context of this thread (re my last/long-winded comment).

**Comment by jasnell** [comment]
I was just responding to whether things could be taken back to the tsc if necessary :) As the one who initially proposed moving i18n under commcomm I'm more than happy to see it thrive there!

**Comment by zeke** [comment]
Hey @alexandrtovmach I finally managed to get my PGP setup working again (gory details at https://github.com/nodejs-private/secrets/pull/87#issuecomment-597173069) and I now have access to the @nodejs-crowdin GitHub user again, so I can generate a new personal access token to re-enable the Crowdin integration.

I see two projects when I log into Crowdin using GitHub SSO as @nodejs-crowdin:

- https://crowdin.com/project/nodejs
- https://crowdin.com/project/nodejs-website

Can you remind me which of these projects needs a new token?

Here's a link I can use to generate the token, once I know which project to apply it to: https://github.com/settings/tokens/new?scopes=repo,user,admin:repo_hook&description=Crowdin%20integration

**Comment by nschonni** [comment]
I believe it should be `nodejs-website`. The regular `nodejs` should be the existing API docs from nodejs/node.
It looks like the API docs also got pushed to `nodejs-website`, which isn't correct.

**Comment by zeke** [comment]
Added a new token! Details here: https://github.com/nodejs/i18n/issues/223#issuecomment-598830317

**Comment by nschonni** [comment]
Re-opening since that isn't the right project, and the content that the node-website is still pointing to the API docs, not this repo

**Comment by RichardLitt** [comment]
@nschonni Thanks for being on top of this! Apologies.

**Comment by zeke** [comment]
Thanks for pointing that out. Fixed in https://github.com/nodejs/i18n/issues/72#issuecomment-598920261

**Comment by alexandrtovmach** [comment]
@zeke Thanks for amazing news and sorry for delay

**Comment by alexandrtovmach** [comment]
BTW: I haven't access to https://github.com/nodejs-private/secrets/pull/87#issuecomment-597173069, probably you can write guide somewhere else? Gist, wiki?
