### ISSUE TITLE
Cannot Open Node.js file to install

### ISSUE THREAD

**Issue by JMAC21** [nodejs/nodejs.org#2956]
* **URL**: https://nodejs.org/en/download/current/
* **Browser version**: Chrome Version 79.0.3945.130 
* **Operating system**: Mac OS Catalina

Downloaded current version of Node.js to install but upon attempt to open received this message:
'“node-v13.8.0 (2).pkg” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.'

**Comment by nschonni** [comment]
Thanks, this is being tracked over on https://github.com/nodejs/node/issues/29216
