### ISSUE TITLE
No LTS shown on main page

### ISSUE THREAD

**Issue by rvagg** [nodejs/nodejs.org#298]
Re #261 /cc @phillipj 

![screen shot 2015-10-30 at 8 15 50 am](https://cloud.githubusercontent.com/assets/495647/10832266/833bc60e-7ede-11e5-9490-beac8b30eeaf.png)

This is pretty urgent, would someone mind figuring out how to make v4.2.1 show as LTS?

**Comment by mikeal** [comment]
@rvagg looking through the code it checks if the version definition has {lts: true} which I believe comes from the build system.

**Comment by phillipj** [comment]
I'm on it

**Comment by rvagg** [comment]
thanks @phillipj, just push straight to master when you have something (IMO)

**Comment by mikeal** [comment]
nm, looks like the version def has {lts:false} so it's in the helper.

**Comment by phillipj** [comment]
Sorry about that, a unit test will follow shortly ;)

**Comment by mikeal** [comment]
looks like it got hot fixed :)

**Comment by rvagg** [comment]
good work @phillipj, looks great!

**Comment by jasnell** [comment]
+1

**Comment by stevemao** [comment]
LOL that was quick!!! I was wondering why and 10 mins later this was fixed :)
