### ISSUE TITLE
Decide on what to do with Node version in dockerization guide.

### ISSUE THREAD

**Issue by mkrawczuk** [nodejs/nodejs.org#2988]
* **URL:** https://nodejs.org/en/docs/guides/nodejs-docker-webapp/ (and all translations)

Currently, an old version of LTS Node is mentioned in the guide. A fix has been proposed in PR #2953, and shortly after, #2983 followed. I'm opening this issue to avoid splitting the discussion between these two PRs.

The former lets the maintainers forget about manual version bumping which may be a source of inaccuracies (as proven in PR description), but may cause problems to the users, since the version is variable and changes with new Node releases.

The latter is safer for the users, but may again cause inaccuracies, also requires manual version bump with every LTS release. It also requires to add another point to an already long list in the release process.

I would personally go with the former. Only advantage of #2983 over #2953 is that it might protect the user from some discrepancies in case of a new Node LTS release. However I believe that problems emering from such discrepancies are very improbable. Additionally, even the best guide will not prevent from misuse of software.

**Comment by richardlau** [comment]
> Currently, an old version of LTS Node is mentioned in the guide.  

The current text uses Node.js 10 and that’s still in support until next year (April 2021). Doing nothing for now and leaving the text as-is is an option.

**Comment by mkrawczuk** [comment]
The text explicitly recommends the latest LTS version (12), while the text inconsequently mentions versions 8 and 10. Please see the PRs.

**Comment by mhdawson** [comment]
I'd be ok with leaving the doc as is, but then adding a line somewhere that says something like this: "we recommend the latest lts version which was 10 at the time this guide was written. Please use the latest lts version instead of 10 as shown in the examples"

**Comment by ovflowd** [comment]
Closing as it seems the parties are fine with the current content. And the guide was updated.
