### ISSUE TITLE
Is there an official installation guide ?

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#2990]
I want to install nodejs on centos 7, but I didn't find the installation guide on the official website. If there is one on the official website, please tell me where it is. If not, I hope the official website can organize and put an installation guide. (I just want to see the official installation guide, thanks.)

**Comment by nschonni** [comment]
There is https://nodejs.dev/how-to-install-nodejs/ on the dev site, but I'm note sure if i'm missing an article over here that i'm not remembering

**Comment by ghost** [comment]
Thank you. For convenience, https://nodejs.dev/how-to-install-nodejs/ recommends using a package manager for nodejs installation. Maybe I can use _nvm_ to install nodejs on centos system, and here is a link that I got from the link above: https://nodejs.org/en/download/package-manager/, hope this will be useful. Thanks again.
