### ISSUE TITLE
 Windows download link is shown on top if Google Chrome UA string will be fixed.

### ISSUE THREAD

**Issue by yosuke-furukawa** [nodejs/nodejs.org#2995]
![image](https://user-images.githubusercontent.com/555645/75653368-ce118980-5ca0-11ea-80bf-366bd43777f9.png)
Chrome UA string will be fixed in soon. https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/-2JIRNMWJ7s/yHe4tQNLCgAJ

According to the link, September 2020, Chrome 85 will fix and unify all UserAgent strings.
If the UA is fixed, we could see the windows download link on top.

we need to change the download link algorithm. 

* **URL**:
nodejs.org

* **Browser version**:

Chrome Canary 82.0.4074.0

* **Operating system**:

N/A

**Comment by nschonni** [comment]
I'll just add that it wasn't particularly well received when presented to the other vendors https://github.com/w3ctag/design-reviews/issues/467 even though they claim in the Google group that they have support

**Comment by nschonni** [comment]
Also from that thread
> Hey all!
>
> As this intent relies on UA Client Hints and as the UA-CH intent is on hold due to great feedback on the proposal, I wanted to update this thread regarding timelines.
Originally, we planned to ship UA-CH for M81, but as feedback resulted in proposal changes, that didn't happen.
> I'm currently focused on specifying and implementing those changes and then shipping UA-CH. The timelines for this intent are likely to be derived from the time in which that UA-CH would actually ship. 
> As a result, the timelines mentioned in the OP are likely to slip as well. I'll update this thread once we have line of sight as to what those new timelines would be.
>
> Cheers :)
> Yoav

**Comment by ovflowd** [comment]
I assume this is fixed by now.
