### ISSUE TITLE
Setup GitHub Action to deploy site

### ISSUE THREAD

**Issue by nschonni** [nodejs/nodejs.org#3018]
@XhmikosR want to draft up a GitHub Action for this? If I can encrypt and store a secret that has an SSH key then we could isolate it to a single user account on the server and push content up directly. It'll need to be two step - 1) rsync content and 2) run an ssh command on the server to queue an invalidation of our cloudflare cached content. As long as we have strong assurance of the secret content not getting leaked then it could be a good way of pulling back control of this process into this repo rather than relying so much on build-infra to support when things go wrong.

_Originally posted by @rvagg in https://github.com/nodejs/nodejs.org/pull/3014#issuecomment-598510676_

**Comment by nschonni** [comment]
Just pulling the conversation out so it's a little more obvious if someone goes looking.

For the SSH key, it seems like GitHub supports it through Deploy Keys that are repo specific https://developer.github.com/v3/guides/managing-deploy-keys/

**Comment by ovflowd** [comment]
I've made a GitHub action for GitHub Pages, but needs to be updated with `basePath`, working on a PR now, but this can be closed already.
