### ISSUE TITLE
Requesting access for @nodejs-crowdin GitHub user to integrate with Crowdin

### ISSUE THREAD

**Issue by zeke** [nodejs/nodejs.org#3031]
@nodejs-crowdin is the GitHub user we use to integrate Crowdin with the nodejs/i18n GitHub repository. We'd also like to be able to integrate Crowdin with this repo (nodejs/nodejs.org).

Is someone on the @nodejs/website or @nodejs/website-redesign team able to grant @nodejs-crowdin admin access to this repo?

The scopes required by the Crowdin-GitHub integration are these:  https://github.com/settings/tokens/new?scopes=repo,user,admin:repo_hook

See also https://github.com/nodejs/i18n/issues/248

cc @nodejs/i18n

**Comment by alexandrtovmach** [comment]
@nodejs/website ping

**Comment by nschonni** [comment]
@Trott do you have the ability to do this? Or is it something that should get raised formally on nodejs/admin?

**Comment by Trott** [comment]
Done. Sorry about the delay.

**Comment by zeke** [comment]
Thanks @Trott!

Invitation accepted:

<img width="1036" alt="Screen Shot 2020-03-29 at 6 47 20 PM" src="https://user-images.githubusercontent.com/2289/77874520-048be700-7202-11ea-92b2-3d1084d38488.png">

**Comment by alexandrtovmach** [comment]
@zeke Did you have a chance to integrate https://github.com/nodejs/nodejs.org with crowdin?

**Comment by zeke** [comment]
@alexandrtovmach  to which Crowdin project should this repo be connected?

**Comment by nschonni** [comment]
https://crowdin.com/project/nodejs-website

**Comment by nschonni** [comment]
not sure if it makes sense to rename it to `nodejs-website-org` like the other having "dev" at the end

**Comment by alexandrtovmach** [comment]
@zeke, as @nschonni said it should be `nodejs-website` project

**Comment by zeke** [comment]
Done!

![Screen Shot 2020-03-30 at 2 19 40 PM](https://user-images.githubusercontent.com/2289/77963045-88d97b00-7291-11ea-92db-f90611824947.png)
