### ISSUE TITLE
Typo in end of life dates

### ISSUE THREAD

**Issue by tuckmeng** [nodejs/nodejs.org#3051]
Under https://nodejs.org/en/about/releases/, the end of life date for v13 is 2020-06-01 which is earlier than end of life for earlier versions. A typo in the year?

**Comment by richardlau** [comment]
No, the dates are (at this point in time) correct. Odd numbered release lines (e.g. v13) do not become Long Term Support (LTS) release lines so have a much shorter life than the even numbered major release lines.
