### ISSUE TITLE
Updates for translations

### ISSUE THREAD

**Issue by alexandrtovmach** [nodejs/nodejs.org#3057]
We finally have progress with configuring localization process for nodejs.org. That's also affected to the code, build scripts that we already have.

- [ ] update markdown linter to lint only original locale `/en`
- [ ] update development build script to use specific locales to speed up local bootstraping
- [x] update guides for translators to use Crowdin in current repo (#3061, #3062 )

@nodejs/website 
@nodejs/i18n 
@nodejs/i18n-api

**Comment by okuryu** [comment]
I think we need to sync existing translations in this repo to Crowdin. Is the first sync going to be done automatically?

**Comment by alexandrtovmach** [comment]
@okuryu it's already done, you can check here https://crowdin.com/project/nodejs-website

**Comment by nschonni** [comment]
The remark-lint shouldn't be disabled on translations. It's already been catching things like broken reference links in translation PRs

**Comment by alexandrtovmach** [comment]
@nschonni Makes sense, so let's postpone this changes for a week or so, until we complete with transitioning localization process from GitHub to Crowdin:
1. Need to resolve all exist PRs with translations (merge or close)
2. Actualize localization guides in current repo and in all locale team repos

After that we should turn off `remark-lint` for translated content, as not required, in case that Crowdin handle it.

**Comment by nschonni** [comment]
Crowdin doesn't handle it though, and actually reformats the files so that they no longer follow the nodejs Markdown format styleguide

**Comment by alexandrtovmach** [comment]
@nschonni Would you like to join our weekly meeting to discuss?
https://github.com/nodejs/i18n/issues/267

**Comment by Trott** [comment]
If there are changes that can be made to [remark-preset-lint-node](https://github.com/nodejs/remark-preset-lint-node) such that it will reduce friction with Crowdin results, I'm definitely open to making those changes. Of course, they'll have to be balanced against issues of churn in the existing docs and website. But I'm certainly open to the idea that the rules can be more lax or otherwise different if it makes these integrations easier.

**Comment by ovflowd** [comment]
Closing this as the i18n package pretty much got abandoned and we settled into using Crowdin.
