### ISSUE TITLE
Display links to both Stable and LTS API on /docs

### ISSUE THREAD

**Issue by shelleyp** [nodejs/nodejs.org#307]
Please re-open #305 The fix detailed in #306 is not sufficient.

Providing new links in the top-most menu in the front page is a start, but not sufficient. 

You have a main Docs page that needs to reference both API docs. Suggestion:

https://cloud.githubusercontent.com/assets/1231635/10846610/3ebb85cc-7f11-11e5-95a5-9d277b47bedf.png

You have a main API link that's been heavily distributed throughout the web, which now has to somehow provide equal access to both the v4 and v5 APIs. 

https://nodejs.org/api/

Update: sorry, still getting used to new terminology. We need links to LTS and Stable version (not two stable versions) in front page, Docs page, and API page.

**Comment by dominykas** [comment]
And even this might not be enough - it will be really tricky to find the switch once you're deep inside the docs. Right now, a google search for "node url" will lead you to https://nodejs.org/api/url.html - this page needs to have some easy switch between the LTS and non-LTS version of docs or maybe even a cross-link switch to ANY version for _this_ particular page.

**Comment by mikeal** [comment]
This is actually two different issues, and pull requests, at lease. Could you reduce the scope of this issue to adding on the main docs page and open a new issue for the /api

Additionally we may want an issue to include a link in automated releases posts and another for including a link on the download page for each release.

**Comment by shelleyp** [comment]
I'll leave this as the modify /docs issue, leave #305 for the front page, and then add a third issue for /api.

**Comment by phillipj** [comment]
Linking this with #324

**Comment by phillipj** [comment]
Fixed in 3855521
