### ISSUE TITLE
sm_code_getglobalpreloadcode_code_hook missing brackets

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#3070]
https://nodejs.org/dist/latest-v13.x/docs/api/esm.html#esm_code_getglobalpreloadcode_code_hook
current:
```js
const require = createRequire(process.cwd + '/<preload>');
```
should be 
```js
const require = createRequire(process.cwd() + '/<preload>');
```

**Comment by nschonni** [comment]
Thanks, it's confusing, but that content is actually in the https://github.com/nodejs/node repo. Do you want to open an issue or [PR](https://github.com/nodejs/node/edit/master/doc/api/esm.md) there? I don't have the ability to transfer you issue myself.

**Comment by ghost** [comment]
https://github.com/nodejs/node/pull/32657

**Comment by nschonni** [comment]
Thanks @sla100 I think the docs will get updated after it lands, and the next time v13 is released
