### ISSUE TITLE
Download Speed

### ISSUE THREAD

**Issue by GautDlpr** [nodejs/nodejs.org#3097]
* **URL**:https://nodejs.org/dist/v12.16.2/node-v12.16.2-x64.msi
* **Browser version**:Google Chrome Version 80.0.3987.163
* **Operating system**: Windows 10

Hey
I'm not an expert, but wtf 40 min for downloading 18 mo :
Something went wrong and it's not me

This massage must be useless but you had to say it

Have a nice easter day !
GautDlpr

**Comment by gekim** [comment]
20 seconds here on a 20Mb DSL line.
Points to something between you and the download site.

**Comment by Trott** [comment]
Took seconds over here. I'm going to close this because there's nothing in here that's action-able and it is unlikely to be an issue with nodejs.org. Feel free to re-open if there's anything credible that suggests otherwise.
