### ISSUE TITLE
The Node 12.16.3 release post didn't go live

### ISSUE THREAD

**Issue by cjihrig** [nodejs/nodejs.org#3143]
* **URL**: missing
* **Browser version**: All
* **Operating system**: All

It looks like the 12.16.3 release blog post (https://github.com/nodejs/node/pull/33009) never got published to the site.

**Comment by cjihrig** [comment]
cc: @nodejs/build

**Comment by nschonni** [comment]
Someone with access might need to restart the hooks https://github.com/nodejs/build/issues/2123#issuecomment-570987532 or it's the delay in the CDN purge https://github.com/nodejs/nodejs.org/pull/3129#issuecomment-617438032

**Comment by rvagg** [comment]
I can't actually fully explain this, everything seems to be running properly on our end.

I ran it manually on the sever (`build-site.sh`) but it said that the HEAD commit was the HEAD-1 commit (https://github.com/nodejs/nodejs.org/commit/9b23caac1d7d62087160db3d2bdf38223264899b) and built from that.

Here's a tail of a grep of 'HEAD is now at' from github-webhook.log that shows something similar:

```
stderr: HEAD is now at 9b4c4a4... build(deps): bump sass from 1.26.3 to 1.26.5
stdout: HEAD is now at 9b4c4a4 build(deps): bump sass from 1.26.3 to 1.26.5
stderr: HEAD is now at 9b4c4a4... build(deps): bump sass from 1.26.3 to 1.26.5
stdout: HEAD is now at 9b4c4a4 build(deps): bump sass from 1.26.3 to 1.26.5
stderr: HEAD is now at 7095061... [PT-BR]: translate about resources to pt-br (#3125)
stdout: HEAD is now at 7095061 [PT-BR]: translate about resources to pt-br (#3125)
stderr: HEAD is now at 7095061... [PT-BR]: translate about resources to pt-br (#3125)
stdout: HEAD is now at 7095061 [PT-BR]: translate about resources to pt-br (#3125)
stderr: HEAD is now at f9939e0... build(deps): bump fibers from 4.0.2 to 5.0.0 (#3134)
stdout: HEAD is now at f9939e0 build(deps): bump fibers from 4.0.2 to 5.0.0 (#3134)
stderr: HEAD is now at f9939e0... build(deps): bump fibers from 4.0.2 to 5.0.0 (#3134)
stdout: HEAD is now at f9939e0 build(deps): bump fibers from 4.0.2 to 5.0.0 (#3134)
stderr: HEAD is now at 9b23caa... build(deps-dev): bump chokidar from 3.3.1 to 3.4.0 (#3140)
stdout: HEAD is now at 9b23caa build(deps-dev): bump chokidar from 3.3.1 to 3.4.0 (#3140)
stderr: HEAD is now at 9b23caa... build(deps-dev): bump chokidar from 3.3.1 to 3.4.0 (#3140)
```

I've run it a second time and it's picked up the proper HEAD now.

The script does a full reset and fetch to get the latest HEAD: https://github.com/nodejs/build/blob/master/ansible/www-standalone/resources/scripts/build-site.sh#L32-L35

```
git reset --hard
git clean -fdx
git fetch origin
git checkout origin/master
```

so I'm lost beyond that, perhaps GitHub is having a problem?

It's live now: https://nodejs.org/en/blog/release/v12.16.3/

**Comment by cjihrig** [comment]
Thanks Rod. I'll close this issue. If anyone wants to reopen it for some type of postmortem, feel free.
