### ISSUE TITLE
Non-translated pages in translated directories taking over search results

### ISSUE THREAD

**Issue by bnb** [nodejs/nodejs.org#3149]
Looking for a reference to the New Buffer depreciation, I searched for "node js new buffer deprecated" on Google, and this was the first result:

![image](https://user-images.githubusercontent.com/502396/80730495-a8093980-8ad7-11ea-9e90-b429f65b4627.png)

Going to the page, however, I realized that this was a "translated" version of the page: 

![image](https://user-images.githubusercontent.com/502396/80730557-b9eadc80-8ad7-11ea-870d-77f6d10b7223.png)

Unfortunately, it seems that this page itself is not actually translated and is taking over the search results. Whether you're looking for it in english or the translated version, this is a super not good user experience since the page is in the translated layout but the content itself isn't actually translated.

I feel like there needs to be some kind of solution here since this brings up a few different problems. Potential solutions:
- Don't publish pages that aren't translated
- Set canonical URL on all translated pages to the english version
- Detect browser language and have an overlay that recommends going to the browser language's version of the page.

**Comment by nschonni** [comment]
@alexandrtovmach I think you were going to enable the setting so that untranslated pages weren't pushed from Crowdin till they started to be translated

**Comment by nschonni** [comment]
Ping @alexandrtovmach do you have a way of fixing this on the Crowdin side before I manually nuke all these untranslated pages that were added?

**Comment by thomscoder** [comment]
was this bug solved?

**Comment by bnb** [comment]
probably not

**Comment by ovflowd** [comment]
I am closing this, as this doesn't happen anymore.
