### ISSUE TITLE
doc: refer to not-up-to-date website: six-speed

### ISSUE THREAD

**Issue by aghArdeshir** [nodejs/nodejs.org#3176]
https://nodejs.org/en/docs/es6/

In the link above there is a refrence to websit: six-speed. About performance of EcmaScript features. The website is so outdated.

**Comment by aghArdeshir** [comment]
![Screenshot_20200515-152241_Firefox](https://user-images.githubusercontent.com/5755214/82043446-20a4f400-969b-11ea-9882-a0f7ca5a8666.jpg)

**Comment by Trott** [comment]
I suspect the ES6 page should be removed entirely. It was a big and important thing when io.js forked and shortly after the merge back with Node.js. But it has been some time since it's been worth such a big call out, I think. Anyway, I'll open PR to remove the six-speed stuff. Thanks!
