### ISSUE TITLE
Update/remove Foundation Timeline

### ISSUE THREAD

**Issue by bnb** [nodejs/nodejs.org#318]
Was just looking over the site and noticed that there was a timeline for the foundation at [foundation/index.md](https://github.com/nodejs/new.nodejs.org/blob/master/locale/en/foundation/index.md). 

We are well past that time frame, so this section needs to be updated to reflect whatever the current state is (I don't know anything about the state of this).

// cc @nodejs/roadmap

**Comment by mikeal** [comment]
it can be removed.
