### ISSUE TITLE
Dockerized nodejs.org

### ISSUE THREAD

**Issue by MrSlimCoder** [nodejs/nodejs.org#3183]
Hi i was interested in dockerized node.org.

**Comment by awerlang** [comment]
Have you seen the official nodejs images ([1]), as linked in the website ([2])?

[1]: https://hub.docker.com/_/node/
[2]: https://nodejs.org/en/download/

**Comment by MrSlimCoder** [comment]
> Have you seen the official nodejs images ([1](https://hub.docker.com/_/node/)), as linked in the website ([2](https://nodejs.org/en/download/))?

Nope currently node.org is not dockerized.

**Comment by nschonni** [comment]
Thanks, that's not used by the current deployment infrastructure, so it's not needed
