### ISSUE TITLE
Should we tell dependabot to chill out?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/nodejs.org#3207]
Refs: https://github.com/nodejs/nodejs.dev/issues/668

Nodejs.dev was getting ALOT of noise from dependabot. We ended up changing the settings to only notify us for security related issues and auto land semver-patch

Should we replicate these settings here?

![Screen Shot 2020-05-05 at 11 37 04 AM](https://user-images.githubusercontent.com/498775/81085535-555bc300-8ec5-11ea-95ba-b5981746a9e6.png)

**Comment by XhmikosR** [comment]
The only change I'd make is switch to weekly or monthly checks.

Having security only should be like not having it enabled, since automated security fixes already do the same.
