### ISSUE TITLE
More descriptive buttons for LTS and Stable in the download tab.

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#321]
We should have more descriptive tabs, similar to what we have on the front page, for the corner LTS and Stable tabs.

**Comment by rnsloan** [comment]
Like this?: 

![screen](https://cloud.githubusercontent.com/assets/2513462/11019395/8d54b0aa-864b-11e5-92e0-520e47beabf2.png)

**Comment by fhemberger** [comment]
I think the labels should stand out more like tabs, so it's really clear on what page you're on and what you are about to download. Just bold text isn't enough.

**Comment by mikeal** [comment]
I think that copy contains pretty much everything we want in the tab, but yes, a tab that stands out a bit more would be great.

**Comment by bnb** [comment]
+1 to @fhemberger. How about putting a toggle on the far left, with one half with a bright green background (same as platform logos) and the other half as background-transparent? Top could be LTS, bottom could be stable, and there would be enough room for the subtitles.

**Comment by rnsloan** [comment]
@bnb sorry I do not quite follow, when I think of a toggle I think of something like this:

![toggle](https://cloud.githubusercontent.com/assets/2513462/4368265/b808a7d0-42e9-11e4-8bf6-a9fae68131a0.png)

Could you give the most basic mock-up of your idea? Can just be boxes and lines. Otherwise I will keep things where they are and do something like this:

![tabs](https://cloud.githubusercontent.com/assets/2513462/11061506/c1c6ce66-87fb-11e5-9ace-562f3fc7dd47.png)

**Comment by bnb** [comment]
![lts-stable](https://cloud.githubusercontent.com/assets/502396/11073450/abfbf590-87b8-11e5-9694-0ae6aa1fd996.png)
That's what I was going for.

**Comment by bnb** [comment]
![lts-stable](https://cloud.githubusercontent.com/assets/502396/11073468/c8148fbc-87b8-11e5-8c3c-a50c7621d3a4.png)

This is essentially what I meant.

**Comment by fhemberger** [comment]
@bnb Unfortunately, this layout wouldn't fit for a tablet/mobile view of the page. But yes, I like the idea. Maybe you can put this on a horizontal axis somewhere?

**Comment by rnsloan** [comment]
We could move it above

![top](https://cloud.githubusercontent.com/assets/2513462/11090584/27a7f3a6-88c7-11e5-8b19-7fb0b58372fb.png)

---

Or decrease the width of the windows, osx, source links

![side](https://cloud.githubusercontent.com/assets/2513462/11090534/b119d7ae-88c6-11e5-8cdf-7c7fda489b7e.png)

**Comment by mikeal** [comment]
I like it!

**Comment by Fishrock123** [comment]
Some things:

Should we really be defaulting to LTS?

`Tested and Secure` has the same problem as `stable` for LTS. Stable is very well tested. It is arguably also even more secure than LTS. I think we should keep with terms like `mature`, `dependable`, `predictable`, etc.

**Comment by Fishrock123** [comment]
+1 to having larger buttons though, I missed those before!

**Comment by fhemberger** [comment]
Nice, I like how this is evolving! :+1:

**Comment by phillipj** [comment]
+1 to your second option @rnsloan. Moving the version choice nearer the actual download links, looks like a much better approach than links in the page header.

**Comment by bnb** [comment]
Also +1 to @rnsloan's second option.
