### ISSUE TITLE
v4 vs v5 page

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#322]
We need a page on the website that explains the difference between the release lines and why we have them.

**Comment by phillipj** [comment]
Might be worth trying to resurrect the stale discussion in nodejs/LTS#44.

**Comment by mikeal** [comment]
Sure, but it's not _just_ about LTS, it's also about what v5 is and why people should run it.

**Comment by fhemberger** [comment]
@mikeal Is this issue still relevant? Or do we need a v4 vs v5 vs v6 page soon? 😃

**Comment by MylesBorins** [comment]
It would only be v4 vs v6. 5 is eol after this month
