### ISSUE TITLE
Revert site index page

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#3223]
Hi!

Why did you change nodejs site index page? It brings a lot of problems with documentation page searching with downloading page searching and others pages.

We are developers. Nobody cares about your skin color or your nationality or something else. The only measure is your code skills.

So why are you bringing problems to the place where they never occurred?
If you want to support something create special page for this, create bright notification with link to special page. But don't make site navigation problems such now please.

I hope I didn’t offend anyone. Just code is out of world problems. Thank you!

**Comment by Jisagi** [comment]
I strongly agree on what was said so far. Bringing attention to (important) topics is good, but in which location and how is the question. Without google or other site indexer, it's impossible to find a download link to any version of nodejs. The only way is to find the single blog post link and from there go to downloads, but good luck finding that at the bottom of the page in the middle of a text with other links in it.
Yes, it's the node-teams choice to bring whatever topic they want to the attention of the public but please don't hurt yourself by literally blocking out those who came for nodejs.

**Comment by jasnell** [comment]
The website changes have the full support of the nodejs/tsc and nodejs/community-committee and will remain for a period of time.

Node.js downloads are easily found https://nodejs.org/download/ and https://nodejs.org/dist
