### ISSUE TITLE
Node website hacked

### ISSUE THREAD

**Issue by chaimochs** [nodejs/nodejs.org#3225]
Was the nodejs website hacked by BLM?

**Comment by sxa** [comment]
Despite how it may initially appear it has not been hacked - this was a deliberate decision by the Node.js community as per https://github.com/nodejs/nodejs.org/pull/3202

**Comment by sxa** [comment]
@jasnell Would it be worth leaving one of these open and/or pinned to attempt to stop duplicates being opened?

**Comment by jasnell** [comment]
I would close the issues but have someone from the project open a new pinned and locked issue.. it's not going to stop duplicates from being opened, unfortunately.
