### ISSUE TITLE
Anonymous feedback regarding the #BlackLivesMatter site

### ISSUE THREAD

**Issue by benjamingr** [nodejs/nodejs.org#3226]
Hey,

I have received feedback from a third party who wished to stay anonymous regarding the new website being very US-centric in nature.

I am honestly not sure if police brutality towards people of color is a bigger problem in the US (I personally felt a lot more racism in the US walking around with friends who were not white than anywhere else I ever visited).

Would it be possible to add some other non-us examples? Namely I can only speak of my locale [this would probably be the Israeli equivalent](https://en.wikipedia.org/wiki/July_2019_Ethiopian_Jews_protest_in_Israel) - namely one name (Solomon Teka).

**Comment by jasnell** [comment]
A pull request with a concrete suggestion would likely be the best approach.

**Comment by Jolly-Pirate** [comment]
NodeJS, Github is not an outlet for American politics. It's an international community, so leave your domestic problems out of it and stick to coding.

**Comment by DaniilVysotskiy** [comment]
Seriously, stop mixing professional life with social/political life.

**Comment by rusekr** [comment]
Here in Russia all lives are always mattered.

**Comment by vampig** [comment]
Meanwile in Russia every life matters.

**Comment by pro-nasa** [comment]
@jasnell you're an idiot

#alllivesmatter

**Comment by pro-nasa** [comment]
@jasnell and you support crimes

George floyd was a criminal and a social margin. Now everyone makes him a hero

**Comment by Lukortech** [comment]
Is it Node.js priority now to answer all things that matter? Would it be appreciated if I made a PR asking to remember all the gay people stoned to death in certain countries? Why does it matter for people in Ukraine that USA has problems with corruption and racism? Maybe NODE.js mainapge should be a news page from now on, then?

**Comment by rusekr** [comment]
Use https://nodejs.org/ru/ (just not "/en/" page). It is more adequate.

**Comment by benjamingr** [comment]
Hey, this was addressed in the PR and discussion - so I am going to close this - thanks :]

**Comment by Lukortech** [comment]
@benjamingr which PR, if you'd be so kind?

**Comment by benjamingr** [comment]
https://github.com/nodejs/nodejs.org/pull/3228

**Comment by benjamingr** [comment]
Preface: I don't speak for Node.js in the following comment, nor am I speaking in my capacity as a collaborator or moderation team member - I only speak for myself and from my own anecdotal experience.

As a side note - the easiest way to get a say regarding what Node.js does or doesn't do is to get involved. If any one of the hundreds of members (or tens of leadership body members) objected to the PR to the website - it would be blocked and discussed. Every one of the project org members either didn't care enough or was supportive.

Getting involved is [relatively simple](https://nodejs.org/en/get-involved/) and there are many areas to get involved in (code, commcomm and various other areas of the project).

One of the main goals of the website change was to encourage people from systematically oppressed communities to participate in Node.js and to commit to helping them with mentorship.

Node.js is a private entity composed of multiple people working together building software. So to clarify:

> Would it be appreciated if I made a PR asking to remember all the gay people stoned to death in certain countries?

If you contributed to the project a bunch and then put in the actual work to make that change and other members thought that it was in good faith and you convinced other members it's a big problem - then _probably_. Most issues in blocked are blocked on people actually doing the work and pulling through.

Systematic racism and police brutality towards African Americans is a problem some project members feel very strongly about and other project members in good faith would like to support that community (and those other members). Node.js is effectively just a bunch of humans working on software together - not a government.

--- 

To clarify: I am personally quite ignorant on the issues of systematic racism in the US, I don't live in the US, I am not a member of an affected community and while I work with non-white folk all the time: I don't pretend to understand their issues very well (I read like.. 2 books). Being a project member usually means (if things are well)  a form of trust (in this case in the people promoting this like Tierney and Myles). Being able to trust the project and the people acting in good faith helps the project a lot - and the project being supportive and doing a good thing to promote dirersity is pretty great. Node.js taking active action to get more collaborators from that population is something I am proud the project is doing.

**Comment by Lonniebiz** [comment]
I can't believe the board members of this organization would allow the promotion of **any cause** outside of javascript, node.js, and open source software.

I think the best way to avoid police brutality is to being respectful, polite and cooperative when dealing with police officers. My philosophy is similar to that of [Chris Rock](https://www.youtube.com/watch?v=uj0mtxXEGE8). But, do you really care what I think? Of course not.

That's the same way I feel when I see a programming framework trying to promote causes outside of their role. Know your role, and make internal policies to not have opinions outside of that role. This is not the place for that type of thing and I wanted to at least voice my opinion. I'm sure I'm not alone.
