### ISSUE TITLE
Main page docs link

### ISSUE THREAD

**Issue by bzoz** [nodejs/nodejs.org#3231]
The documentation link on the main page points to https://nodejs.org/docs/:
![image](https://user-images.githubusercontent.com/17704638/83888812-a3751800-a74a-11ea-822e-7043e4ffcc5f.png)

it should probably point to https://nodejs.org/en/docs/

**Comment by addaleax** [comment]
Or https://nodejs.org/api/?

**Comment by bzoz** [comment]
I would go with https://nodejs.org/en/docs/, so it has the links to both current and LTS docs.

**Comment by bzoz** [comment]
Fixed in https://github.com/nodejs/nodejs.org/commit/f913c0260055ccb73ede17f685a8282da6c52045
