### ISSUE TITLE
White lives dont matter?

### ISSUE THREAD

**Issue by egoroof** [nodejs/nodejs.org#3232]
Your tag on the main doc page is `BlackLivesMatter` which stands for racism. Why only black? White men lives don't matter?

oh wait, I've just came to the nodejs documentation. Why do you makes me bad? There are lot of violence and in this world not just black one.

Oh what about animals murder? Did you watch the film Earthlings (2005)? You think this is not such important as blm?

Maybe you just getting hyped on it?

THERE ARE LOTS of problems in this world.

Why do you decide that developers should suffer from it? Oh, you are the owners of the site, thats why.

p.s. thanks for nodejs anyway :)

**Comment by codebytere** [comment]
The website changes have the full support of the nodejs/tsc and nodejs/community-committee and will remain for a period of time. 

The issue adding the site and banner was open for a few days and did not receive any objections so it was added. This is an action done in good faith by the project. Node.js downloads are easily found https://nodejs.org/download/ and https://nodejs.org/dist .
