### ISSUE TITLE
node.js website and BLM content

### ISSUE THREAD

**Issue by markusdresch** [nodejs/nodejs.org#3237]
i just tried to enter the node.js website, but it's full with some #BLM stuff and names.  the download links etc are still available via google.

**Comment by markusdresch** [comment]
ok, so this is on purpose... https://github.com/nodejs/nodejs.org/issues/3229

can users who are not citicens of the USA and do feel uncomfortable about having politics shoved down their throat in their daily work get a different landing page? i do know that there are riots over there and stuff, that's all in the newspapers. but i am very disturbed about this popping out in tools commonly used all over the world with no political association whatsoever.

**Comment by Trott** [comment]
@markusdresch For what it's worth, the German language pages do not have this content. (I'm mentioning it only because GitHub says you're in Austria.) https://nodejs.org/de/

**Comment by markusdresch** [comment]
ah ok. i always use english operating systems, didn't notice. thanks.

**Comment by fristys** [comment]
> @markusdresch For what it's worth, the German language pages do not have this content. (I'm mentioning it only because GitHub says you're in Austria.) https://nodejs.org/de/

What if I want to read the site in English and am not from the US? It's only the most spoken language on the planet... I just don't understand why politics has to be brought into everything, even work

**Comment by Trott** [comment]
> What if I want to read the site in English and am not from the US? 

Not sure if the question is entirely rhetorical, but in case a practical answer helps: There are three links at the bottom of the page to get people to the English website. In addition, you can also go to a path that you know doesn't exist (or guess a path that you think exists) and the 404 page has a top nav that is the same as always and can be used to get to downloads, docs, etc.

**Comment by JJPandari** [comment]
I was going to troll a slight little bit by opening a new issue against the changes to the website, but somehow I'm keep a bit decency and commenting here...

**So my thought is**, do you node.js collaborators think open source belongs to the whole mankind? If so, why mess its website with an issue only related to the U.S.?

You political correctnessts may then say that I'm cold blooded and cares nothing about people's rights. But I do, I do feel sorry for Goerge Floyd and the trouble his incident has brought to people in U.S.. That doesn't mean we should mention this everywhere. That's like asking everyone to stop going to their jobs and speak for Floyd whole day. Oh we are far from doing this when we are only putting such content on an unrelated OSS's website? Careful, we are not far actually.

As mentioned by others above, you may then argue that such content is only on english version of the website. But `use english with node.js === people in U.S.`? I don't think so.

---

And the pinned issue says,

> If you wish to provide feedback on the site changes, please do not open an issue here. Rather, you may send an email to report@nodejs.org or to any Node.js TSC / Community Committee member.

It's the right thing to do to keep issues clean, but why do you forget about clean when it comes to the website? Smart people like you collaborators shouldn't do so.
