### ISSUE TITLE
Version download metrics are all wonky

### ISSUE THREAD

**Issue by achingbrain** [nodejs/nodejs.org#3244]
The download metrics at https://nodejs.org/metrics/ take a massive downward leap on Nov 5th 2019 and then again at the beginning of April this year.  Since they're generated from the logs I'm guessing a CDN was deployed or similar?

They are useful to gauge the adoption of various node versions - is there a different place these stats are presented?

**Comment by richardlau** [comment]
It's a known issue. See also https://github.com/nodejs/TSC/issues/794 and https://github.com/nodejs/build/pull/2025.

**Comment by achingbrain** [comment]
Great, as long as someone's aware.
