### ISSUE TITLE
Remove Black Lives Matter!

### ISSUE THREAD

**Issue by calidion** [nodejs/nodejs.org#3260]
don't use nodejs official web site for political propagation

**Comment by nalaveras** [comment]
**ALL LIVES MATTER YOU IDIOTS!**

**Comment by MylesBorins** [comment]
We will not be removing the banner at this time.

**Comment by calidion** [comment]
Then add Yellow Lives Matter && White Lives Matter && All Lives Matter.
Don't be racist by only picking black!
The black should not be a privileged race!
