### ISSUE TITLE
#AllLivesMatter

### ISSUE THREAD

**Issue by maxdygaf** [nodejs/nodejs.org#3274]
* **URL**:  mental science 
* **Browser version**:  mind-set
* **Operating system**:  Mind

Probably you wanted to say that **all lives matter**. When someone says  that anyone's live matter emphasising differences he lows down the value of the lives of the other groups of people. 
So #AllLivesMatter  would be closer to everyone.

**Comment by addaleax** [comment]
See https://github.com/nodejs/nodejs.org/issues/3229.
