### ISSUE TITLE
Document the dependency on ICU in the online documentation

### ISSUE THREAD

**Issue by dilyanpalauzov** [nodejs/nodejs.org#3275]
NodeJS can be built with bundled ICU or `--with-intl=system-icu`.

Document the dependency on ICU at https://nodejs.org/en/docs/meta/topics/dependencies/

**Comment by AugustinMauroy** [comment]
This page help you ?

https://nodejs.org/dist/latest-v18.x/docs/api/intl.html

**Comment by dilyanpalauzov** [comment]
Since ICU is dependency, it shall be documented at https://nodejs.org/en/docs/meta/topics/dependencies/ .  There I want to find all information for buidling NodeJS.

**Comment by AugustinMauroy** [comment]
humm ok I can't help you more.
Sorry

**Comment by ovflowd** [comment]
@dilyanpalauzov feel free to make a PR to update this page https://nodejs.org/en/docs/meta/topics/dependencies/

Or someone from @nodejs/collaborators that have better understanding of what each dependency does. @nodejs/single-executable also for adding the documentation on our SEA dependencies :)

**Comment by anonrig** [comment]
We need to also mention Ada and simdutf in this page.

**Comment by bmuenzenmeyer** [comment]
closing this. https://github.com/nodejs/nodejs.org/pull/5480 resolved the problem by linking to an up to date source over in the nodejs/node repo
