### ISSUE TITLE
Document the dependency on libbrotli in the online documentation

### ISSUE THREAD

**Issue by dilyanpalauzov** [nodejs/nodejs.org#3276]
NodeJS can be built with bundled libbrotly or with `--shared-brotli`.

Document the dependency on libbrotli at https://nodejs.org/en/docs/meta/topics/dependencies/ .

**Comment by nschonni** [comment]
@Trott why did you transfer the issue over here? That page is part of the docs in the node repo

**Comment by Trott** [comment]
> @Trott why did you transfer the issue over here? That page is part of the docs in the node repo

It's in this repo: https://github.com/nodejs/nodejs.org/blob/d0be2aeef14e089b5afbc0bceb6b7cf9bf578c46/locale/en/docs/meta/topics/dependencies.md

**Comment by nschonni** [comment]
👍 thanks, I was mixing up the `api` and `docs` folders

**Comment by MylesBorins** [comment]
There's actually quite a few dependencies we are missing there. I think we might want to just remove this.

Thoughts?

**Comment by Trott** [comment]
> There's actually quite a few dependencies we are missing there. I think we might want to just remove this.
> 
> Thoughts?

+1. It's hard to know what the purpose of this page is. None of these are dependencies you need to install to run Node.js. So this is more appropriately in the build docs in the main repo. And if we update it, it will just go out of date again.

**Comment by bmuenzenmeyer** [comment]
closing this. https://github.com/nodejs/nodejs.org/pull/5480 resolved the problem by linking to an up to date source over the the nodejs/node repo
