### ISSUE TITLE
BLM # in the way of my apt-get link

### ISSUE THREAD

**Issue by nerdlabs001** [nodejs/nodejs.org#3287]
* **https://nodejs.org/en/**:
* **chrome**:
* **lunbuntu**:

the blm# is covering where the apt-get line should be to download

**Comment by nerdlabs001** [comment]
got it somewhere else

**Comment by nschonni** [comment]
FYI, the pages with those lines is https://nodejs.org/en/download/package-manager/, it isn't covering an apt-get line
