### ISSUE TITLE
Typo on #1 blog post outlining processing argv

### ISSUE THREAD

**Issue by niftylettuce** [nodejs/nodejs.org#3294]
https://nodejs.org/en/knowledge/command-line/how-to-parse-command-line-arguments/

The example console output here should have `'five'`, but it ends at `'four'` instead.

![Screen Shot 2020-07-02 at 4 03 05 AM](https://user-images.githubusercontent.com/523141/86339252-f9898e00-bc18-11ea-9dd2-2f8a5a43aad7.png)

**Comment by Trott** [comment]
The docs are correct as they stand now. For `five` to be included, it would need to be added to the command line. It's not there in the last example, so it's not in the corresponding output.

**Comment by Trott** [comment]
(It is confusing that the first example includes `five` and the last one doesn't, so maybe they should be updated to have the same inputs and therefore the same outputs..)
