### ISSUE TITLE
How can i include my organisation name in Node.js website list of companies using their technology?

### ISSUE THREAD

**Issue by VuppalaMahesh** [nodejs/nodejs.org#3302]
This issue is regarding help:

Hi all. Hope everyone is doing good. The help which I need is, We use Node.js in our Project and I want to include my organization in Node.js website list of companies who are using their technology. Just want to know if Node.js is allowing that way. If yes, Please let me know how to that. Below is the sample link of Elixir Technology using companies list in there website:
https://elixir-companies.com/en/companies

**Comment by nschonni** [comment]
It looks like there was discussion around including a sponsors page in https://github.com/nodejs/nodejs.org/issues/1257, but there isn't a page for companies that are using Node
