### ISSUE TITLE
Political Interference

### ISSUE THREAD

**Issue by DayStar24** [nodejs/nodejs.org#3313]

**Comment by nschonni** [comment]
Closing, see https://github.com/nodejs/nodejs.org/issues/3229

**Comment by DayStar24** [comment]
Be aware that the BLM/Antifa political movement espouses the tactics of Kristallnacht. Is this what Node wants to affiliate itself with? Very unusual and disturbing.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
