### ISSUE TITLE
4.2.2 Argon MSI for 64 bit contains faulty npm version

### ISSUE THREAD

**Issue by dotnetCarpenter** [nodejs/nodejs.org#332]
When I download [the `.msi` installer](https://nodejs.org/dist/v4.2.2/node-v4.2.2-x64.msi) from the nodejs front-page, I get `npm` version 2.12.0 which has a [known issue with calling process.getuid on windows](https://github.com/npm/npm/issues/8771#issuecomment-117339976). This virtually makes `npm` useless hence making the _Argon_ release useless on windows.

On the [Argon changelog](https://github.com/nodejs/node/blob/v4.2.2/CHANGELOG.md#2015-10-07-version-420-argon-lts-jasnell) it says:

> npm: Upgraded to npm 2.14.7 from 2.14.4, see release notes for full details (Kat Marchán) #3299

Which leads me to believe that the [node-v4.2.2-x64.msi](https://nodejs.org/dist/v4.2.2/node-v4.2.2-x64.msi) itself is packaged wrong.

Step to reproduce
1) Download [v4.2.2 LTS](https://nodejs.org/dist/v4.2.2/node-v4.2.2-x64.msi)
2) Install
3) node -v v4.2.2 npm -v 2.12.0
4) npm outdated -g
5)

```
PS C:\Windows\system32> npm outdated -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dotnet\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "outdated" "-g"
npm ERR! node v4.2.2
npm ERR! npm  v2.12.0

npm ERR! process.getuid is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dotnet\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "outdated" "-g"
npm ERR! node v4.2.2
npm ERR! npm  v2.12.0
```

**Comment by dotnetCarpenter** [comment]
Same issue with [v5.0.0 Stable](https://nodejs.org/dist/v5.0.0/node-v5.0.0-x64.msi)
node -v `v5.0.0`
npm -v `2.12.0`

**Comment by dotnetCarpenter** [comment]
Hmm.. scratch the last comment. After uninstalling nodejs v4.2.2 and installing nodejs v5.0.0 with the `.msi` I get:
`npm -v 2.12.0` `npm uninstall npm` `npm -v 3.3.6` not sure how that works.

**Comment by stevemao** [comment]
npm3 should come with node5 by default

**Comment by dotnetCarpenter** [comment]
Is it the `.msi` uninstaller that doesn't uninstall npm then?

**Comment by lpinca** [comment]
@dotnetCarpenter this issue tracker is for problems and disccussions related to the Node.js website.
You should post this on https://github.com/nodejs/node.

**Comment by bnb** [comment]
@dotnetCarpenter Yes, this repo is for the development of the site. As @lpinca said, the packaging of Node is not covered in this repository. Create an issue at https://github.com/nodejs/node to get proper support.
