### ISSUE TITLE
Stay out of politics.

### ISSUE THREAD

**Issue by dinther** [nodejs/nodejs.org#3320]
Remove #BlackLivesMatter from your web-site. I find it offensive. I am white and my life matters too.
![ITS_OK_TO_HAVE_SKIN](https://user-images.githubusercontent.com/1192916/88498012-1184df80-d016-11ea-8ef2-3d88e6bd09cf.png)

**Comment by Trott** [comment]
Closing. Ref: https://github.com/nodejs/nodejs.org/issues/3229

> If you wish to provide feedback on the site changes, please do not open an issue here. Rather, you may send an email to report@nodejs.org or to any Node.js TSC / Community Committee member.
