### ISSUE TITLE
Variables such as username seem to be cached globally

### ISSUE THREAD

**Issue by Varun-garg** [nodejs/nodejs.org#3327]
* **https://nodejs.org/, https://nodejs.org/en/about/releases/ , other pages**:
* **chrome (84)**:
* **Arch Linux (rolling)**:

Please check footers of attached in the mail, as much as I would like to I haven't committed to nodejs yet :p 

![Screenshot from 2020-08-06 21-47-37](https://user-images.githubusercontent.com/5960246/89556280-bed5cf80-d82e-11ea-91d2-b1137bcc2239.png)

![Screenshot from 2020-08-06 21-44-08](https://user-images.githubusercontent.com/5960246/89556250-b7162b00-d82e-11ea-8734-cee5e295590f.png)

**Comment by ahtee** [comment]
Not exactly sure what the issue is here, could you explain further? I don't understand the relation between the title and the issue description here.
