### ISSUE TITLE
Event Loop guide article improvement

### ISSUE THREAD

**Issue by IbrahimMohammed47** [nodejs/nodejs.org#3345]
I think the part about pending callbacks and poll phases is quite ambiguous in [this article](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#pending-callbacks), 
I had confusion between these 2 phases, I read many articles and watched many videos but almost all of them contradict or give wrong information about these 2 event loop phases in particular, or sometimes they deal with it as one phase. 
After reading nodejs [guide](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#pending-callbacks), and libuv [design overview](http://docs.libuv.org/en/v1.x/design.html#the-i-o-loop), I came to a conclusion about the distinction between these 2 phases, and I want to make sure if I got that right, and whether the current guide needs more elaboration.
Here is what I understood:
Most of the I/O related callbacks are executed in this poll phase. However, some other callbacks (like TCP error handling callback) will be deferred by re-queueing them to the queue of 'pending callbacks` phase which will be responsible for executing them in the next iteration of the event loop.

**Comment by ovflowd** [comment]
Closing as no action was done. Author is free to reopen if intend to work on this.
