### ISSUE TITLE
Update Apache Workbench with an alternative in Profiling document

### ISSUE THREAD

**Issue by skbr1234** [nodejs/nodejs.org#3348]
* **URL**: https://nodejs.org/en/docs/guides/simple-profiling/
* **Browser version**: Chrome Version 84.0.4147.135 (Official Build) (64-bit)
* **Operating system**: Windows 10

The Apache workbench Node module is dead and is incompatible with the latest Node version. Please update it with an alternative in your profiling advisory document.

**Comment by ovflowd** [comment]
This issue is irrelevant now as the content got updated.
