### ISSUE TITLE
Missing info and circular links for Getting Started

### ISSUE THREAD

**Issue by joyously** [nodejs/nodejs.org#3353]
> We have a special help section for general questions about Node.js:
https://github.com/nodejs/help/issues/

You should link to this somewhere where people will see it!!! But this issue is about the site.

There is a circular set of links for Getting Started, and no real information for a new user.
I finally got Node installed by following instructions buried in the wiki: https://github.com/nodejs/help/wiki/Installation
I don't remember how I got there, but it wasn't easy.
I later was trying to figure out how to run things, and found https://nodejs.dev/learn/how-to-install-nodejs which would not have helped me at all. Why is this even published?

The thing I can't seem to find anywhere is how to run stuff. I can type `node -v` like the installation instructions say, and it works, but when do I need to use the `node` executable? All the things I find online have instructions like
> `npm install ghost-cli@latest -g`
> Once installed, you can always run `ghost help` to see a list of available commands.

or 
> `npm install -g @sanity/cli && sanity init`

Even though the `npm` command worked*, the subsequent command does not.
None of the docs say to start up node, except the really bad example on https://nodejs.org/en/docs/guides/getting-started-guide/
I say it's a bad example because it's useless and doesn't address the majority that just want to use node, not write code.

So, this issue is about the circular, unhelpful Getting Started links.
The [Guides](https://nodejs.org/en/docs/guides/) Getting Started link goes to https://nodejs.org/en/docs/guides/getting-started-guide/
https://nodejs.org/en/docs/guides/getting-started-guide/ has very little on it, and at the bottom:
> Refer to the [Introduction to Node.js](https://nodejs.dev/) for a more comprehensive guide to getting started with Node.js.

This is a top-level page, and has no guides and nothing about getting started. There is a link for [Learn Node](https://nodejs.dev/learn) (not what I want) and one for Read documentation. At the bottom, the Get Started link takes me to the same place as Learn Node. The Read documentation link is for the package manager.

--------------

*Let me just say that I followed the installation instructions that said to use `sudo` to install and to make the symbolic links, and then when I copy the `npm` commands, they don't work without `sudo`. So there's a disconnect between install and all the examples out on the 'net.

**Comment by ovflowd** [comment]
The Getting Started page got updated, and this is probably not relevant anymore. Author is free to reopen this issue if still relevant.
