### ISSUE TITLE
The banner for the security release next week is not showing up

### ISSUE THREAD

**Issue by mhdawson** [nodejs/nodejs.org#3360]
* **URL**: all
* **Browser version**: all 
* **Operating system**: all

There should be a banner active for the security release next week, however, it is not showing up...

**Comment by richardlau** [comment]
@mhdawson I think we need to flip a value for visibility: https://github.com/nodejs/nodejs.org/pull/3359#pullrequestreview-484412042

**Comment by richardlau** [comment]
Opened https://github.com/nodejs/nodejs.org/pull/3361
