### ISSUE TITLE
Clear install information on the nodejs home page

### ISSUE THREAD

**Issue by xdhmoore** [nodejs/nodejs.org#3362]
I installed on macOS using the Node installer and then after [hitting permissions problems](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) the first time I used `npm install -g` I wasted a bunch of time figuring out how to remove system level node and use a virtual environment instead. I think it would be helpful if the information available [here](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm) was clear on the https://nodejs.org homepage, specifically the recommendation not to use the installer. Right now the nodejs home page kindof leads you down the wrong path since the installers are featured prominently and there are no visible installation instructions.

**Comment by benhalverson** [comment]
https://nodejs.dev has clearer instructions. TLDR: use nvm to install if you are on macOS 
Similar instructions can also be found here. https://nodejs.org/en/download/package-manager/#nvm

**Comment by xdhmoore** [comment]
Thanks, yes after my turnaround I successfully followed the instructions at https://docs.npmjs.com/downloading-and-installing-node-js-and-npm using nvm.
