### ISSUE TITLE
"How to access query string parameters" describes how to use deprecated API

### ISSUE THREAD

**Issue by mbelsky** [nodejs/nodejs.org#3396]
Hi,

I've tried to find how to work with search params in nodejs and google shown me [How to access query string parameters](https://nodejs.org/en/knowledge/HTTP/clients/how-to-access-query-string-parameters/)

This article describes how to use `url.parse`, however this API marked as deprecated in [nodejs docs](https://nodejs.org/dist/latest-v12.x/docs/api/url.html#url_legacy_url_api).

What do you think about marking this article as outdated or removing from search engines (if its possible)?

Actualizing this article looks like the best solution, but I'm not sure is there human resources for doing that.

**Comment by AugustinMauroy** [comment]
Knowledge section was remove. Thanks for your issue.
