### ISSUE TITLE
 How long will you continue?

### ISSUE THREAD

**Issue by ippei0605** [nodejs/nodejs.org#3401]
Black Lives Matter

**Comment by DerekNonGeneric** [comment]
That information is available in https://github.com/nodejs/nodejs.org/commit/d29ad75d0ef679a7186c48efc892fa2513fe0343 (days to weeks since 23 days ago), which means that it should be gone before the end of the month, but ultimately it's a @nodejs/tsc decision.

**Comment by MylesBorins** [comment]
I'm closing this issue. We do not have any consensus yet or timeline on removing the banner

**Comment by Trott** [comment]
> but ultimately it's a @nodejs/tsc decision.

...and also @nodejs/community-committee. So TSC and CommComm jointly.

**Comment by DerekNonGeneric** [comment]
> it should be gone before the end of the month

My math was wrong, which I apolagize for, but at least you know what _my_ expectations were.

**Comment by DerekNonGeneric** [comment]
Sorry, but very simply put: it's a TSC decision. That's the answer here. Whether or not my estimation is accurate is beside the point.
