### ISSUE TITLE
I wish to submit guest post on 'test automation'

### ISSUE THREAD

**Issue by caralsusi** [nodejs/nodejs.org#343]
Hi,

I would like to publish guest post on 'test automation' on the website. Is it something you accept ? 

Who should i contact for that?

Thanks

Danial

**Comment by bnb** [comment]
Head over to [nodejs/evangelism](https://github.com/nodejs/evangelism). They handle content creation, and will be the ones that would accept a guest post. No system for guest posts has been established yet, so you'll have to work with them to see if it's possible.

**Comment by mikeal** [comment]
I think it's fine to submit this here, we can pull in the evangelism team via the mention that @bnb just did.

A lot of this stuff stretches both evangelism and documentation so it's better to just deal with them here.

**Comment by mikeal** [comment]
I don't think we'll do "guest posts" in the traditional sense. Any contributor can write content for the blog so long as it's about the project and the community. The issue I see with a post on something like "test automation" is that it's a bit subjective so it would be difficult to write a post in which it didn't look like the project was endorsing a particular opinion.

**Comment by phillipj** [comment]
Closing this as it seems the question has been answered.
