### ISSUE TITLE
Lacking description of some API documentation functions

### ISSUE THREAD

**Issue by lionG** [nodejs/nodejs.org#348]
Some API functions in the Node.js documentation page (mostly at the beginning of the 'fs' module) lack enough description. Please help.

**Comment by thefourtheye** [comment]
@lionG Can you please be a little specific? It would be really helpful if we get to know the functions for which you are seeking better explanations.

**Comment by bnb** [comment]
@thefourtheye Are you looking to provide help for him or are you looking to update the docs for clarity. If the latter, I can go through and compile a list of parts of the docs that don't have sufficient explanation for newcomers. The docs were the biggest sticking point for me, so this topic is important to me.

**Comment by thefourtheye** [comment]
@bnb The latter. It would help broader audience, I believe.

**Comment by bnb** [comment]
@thefourtheye I will try to work on this over the next week or so. Any specific criteria you have in mind? I think I've got it mostly covered.

**Comment by lionG** [comment]
@bnb Many thanks that will be very helpful. @thefourtheye thanks as well we need this. Ill try and start on the 'fs' module section. My issue is there is no detail of what the functions do, what their callback arguments or return values are, and what the functions input arguments stand for as well.

Also please note that I didn't include "overloaded" versions of some function like 'fs.fchown' of 'fs.chown', or synchronous versions of any function.  

Here is a small list:
[fs.rename, fs.ftruncate, fs.truncate, fs.chown, fs.lchown, fs.chmod, fs.link, fs.readlink, fs.unlink, fs.realpath, fs.rmdir, fs.close]

Regards.

**Comment by thefourtheye** [comment]
@lionG I think it will be better if you brought this up in the main repo as well. It will get lot of attention and we ll get more opinions and help.

**Comment by lionG** [comment]
@thefourtheye thanks. However im not entirely sure what the main repo is... please explain.

**Comment by thefourtheye** [comment]
@lionG Oops, I am sorry. I forgot to provide the link. Here it is https://github.com/nodejs/node

**Comment by phillipj** [comment]
Closing this issue, the discussion should proceed in the main repo.
