### ISSUE TITLE
Please keep politics and ideologies away from products and or services

### ISSUE THREAD

**Issue by jonathanmeibergen** [nodejs/nodejs.org#3488]
* **URL**:
* **Browser version**:
* **Operating system**:

Altough i understand it comes from a good place, it's inappropriate to add politics and or ideologies into products and or services.
So the #BlackLivesMatter is better left out (or any other well intended endorsements in any case) of Node.js. Good intentions are assumed by default and they dont need to be verbose when products or services are offered.

Since i don't want to hide behind anonymity
jonathanmeibergen@icloud.com

**Comment by Trott** [comment]
Thanks for the comments. I'm going to lock/close this and refer people to https://github.com/nodejs/nodejs.org/issues/3229. In particular:

> If you wish to provide feedback on the site changes, please do not open an issue here. Rather, you may send an email to report@nodejs.org or to any Node.js TSC / Community Committee member.
