### ISSUE TITLE
Add Slovak locale to Crowdin

### ISSUE THREAD

**Issue by kasicka** [nodejs/nodejs.org#3505]
Can I get Slovak locale added to Crowdin? I am not confident enough with my knowledge of Czech language to contribute to that locale, but I am sure Slovak translation would help Czech speakers as well.

**Comment by nschonni** [comment]
Ping @nodejs/crowdin-managers

**Comment by kasicka** [comment]
Ping? @nodejs/crowdin-managers

**Comment by alexandrtovmach** [comment]
Hello,
Sorry for delay, I lost notification...
Here we go: https://crowdin.com/project/nodejs-website/sk
Thanks for contributing! :+1:

**Comment by alexandrtovmach** [comment]
I can't find your profile on Crowdin, so let me know your username or simply go to:
https://crowdin.com/project/nodejs-website/invite?d=p6653605351793a3e5o4a323r4f3f3
(link to sign up as Slovak translator for `nodejs-website`)
