### ISSUE TITLE
add dark theme

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nodejs/nodejs.org#3507]
Please consider https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by kitarp29** [comment]
Hi @vitaly-zdanevich 
Is this issue still open?
I would love to work on it.
Please assign me this issue.

**Comment by vitaly-zdanevich** [comment]
I am not the administrator, I cannot assign issues.

And firstly we should approve this feature before implementation.

**Comment by NriotHrreion** [comment]
Humm.. I've create a new PR for the dark theme.

**Comment by ghost** [comment]
@vitaly-zdanevich: This's been finished at #4139 , any comments?

**Comment by vitaly-zdanevich** [comment]
I see it still white

![Screenshot_2021-10-03-04-00-54-999_mark.via.gp.jpg](https://user-images.githubusercontent.com/3514015/135735865-d5571401-d54a-47f2-8411-6d825b6e0fa4.jpg)

**Comment by ghost** [comment]
@vitaly-zdanevich: At https://github.com/nodejs/nodejs.org/pull/4139, plz click this link.
This is still in PR waiting for Approving.

**Comment by NriotHrreion** [comment]
The PR has been approved. Can it be merged now? @MaledongGit

**Comment by ghost** [comment]
@NriotHrreion: This's been merged, and I close this issue. For any other issues, welcome to re-open or create a new one.
