### ISSUE TITLE
建议内嵌SQLITEWIN下太难安装了

### ISSUE THREAD

**Issue by neechange** [nodejs/nodejs.org#352]
建议核心模块加入Sqlite3

**Comment by bnb** [comment]
Can you repeat yourself in English? Very few, if any, contributors here speak your language.

**Comment by Fishrock123** [comment]
cc @nodejs/nodejs-cn?

**Comment by JacksonTian** [comment]
@Fishrock123 it can be closed.

**Comment by JacksonTian** [comment]
@neechange This issue list is wrong place to report this question. The sqllite3 install issue under Windows should report at sqllite3's issue list, Not any 3rd C++ addon module should be provided by node core.

**Comment by jiangzhuo** [comment]
你可以试试jxcore  http://jxcore.com/docs/ 或者自己fork修改一份
U can try jxcore,which have sqlite3 built-in or U can just fork nodejs and make your sqlite version
