### ISSUE TITLE
Are you guys going to talk about the White lives that have been reaped by Police Brutality?

### ISSUE THREAD

**Issue by AlphaDio** [nodejs/nodejs.org#3534]
That's a nice list of Black lives that have been reaped by Police Brutality and Injustice you have there.

Are you going to also feature a list of all the people of other ethnicities that have been unjustly killed by a police officer who was high on power?

I can show you the video of a young white man begging for 30 mins while aimed at by a police officer who spent that time abusing him and humiliating him until he finally shot him.

Did the life of that guy mattered?

**Comment by nickserv** [comment]
#3229
