### ISSUE TITLE
"#BlackLivesMatter" covers opened language menu on mobile

### ISSUE THREAD

**Issue by manupik** [nodejs/nodejs.org#3535]
* **URL**: nodejs.org/en
* **Browser version**: Chrome
* **Operating system**: Android

On mobile, when opening the language menu, the "#BlackLivesMatter" banner stays on top and it covers some of the languages.

**Comment by nschonni** [comment]
Thanks, I also see this on Firefox for Android

**Comment by sumukhah** [comment]
Working on the issue.
