### ISSUE TITLE
adding collaborators, Nov 2015

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#354]
Here's a list of recent contributors who are not yet collaborators. If there are no objections I'll be adding them to the Website WG.
- @sup [commits](https://github.com/nodejs/new.nodejs.org/commits?author=sup) 
- @kohei-takata [commits](https://github.com/nodejs/new.nodejs.org/commits?author=kohei-takata)
- @ZibbyKeaton [commits](https://github.com/nodejs/new.nodejs.org/commits?author=ZibbyKeaton) 
- @e-jigsaw [commits](https://github.com/nodejs/new.nodejs.org/commits?author=e-jigsaw) 
- @jorangreef [commits](https://github.com/nodejs/new.nodejs.org/commits?author=jorangreef) 
- @matthewloring [commits](https://github.com/nodejs/new.nodejs.org/commits?author=matthewloring) 
- @nstanard [commits](https://github.com/nodejs/new.nodejs.org/commits?author=nstanard) 
- @woodyrew [commits](https://github.com/nodejs/new.nodejs.org/commits?author=woodyrew) 
- @anseljh [commits](https://github.com/nodejs/new.nodejs.org/commits?author=anseljh) 
- @thephpjedi [commits](https://github.com/nodejs/new.nodejs.org/commits?author=thephpjedi) 
- @xcatliu [commits](https://github.com/nodejs/new.nodejs.org/commits?author=xcatliu) 
- @Starefossen [commits](https://github.com/nodejs/new.nodejs.org/commits?author=Starefossen) 
- @isaacs [commits](https://github.com/nodejs/new.nodejs.org/commits?author=isaacs)

**Comment by stevemao** [comment]
I have no objections. I'm just wondering how many collaborators you need here?

**Comment by mikeal** [comment]
> I'm just wondering how many collaborators you need here?

There's no real answer to this other than "more" while contributions are growing. Collaborators help with the sizable review load as we continue to gain more contributions (and we're not even near where we were on iojs.org for localizations yet).

**Comment by bnb** [comment]
+1 to this. However, we need to be 100% sure they know the general rules - more specifically the merging/PR rules. In the past it's only been a few contributors added, and the older contributors were able to confirm over Issues. I'm sure you have opinions/thoughts on this, @mikeal?

**Comment by evanlucas** [comment]
Do we want to go as far as having an onboarding?

**Comment by bnb** [comment]
There's an upside and a downside to it.

Upside is that everybody knows what's going on, and there will be as few mistakes as possible. 

Downside is that we have to put effort into it. That sounds extremely lazy, but it's the most simple way to describe it. We may not have enough/willing/able people to be able to onboard, and it will limit the rate at which we can accept new collaborators a lot.

**Comment by ghost** [comment]
@bnb as for general rules - do you mean the contents of CONTRIBUTING.md?

**Comment by anseljh** [comment]
I contributed exactly 2 bytes, so feel free to defer any onboarding or other work for me! :+1:

**Comment by bnb** [comment]
@sup Yes.

**Comment by bnb** [comment]
@sup As well as GOVERNANCE.md

**Comment by ghost** [comment]
@bnb i see, thanks (as though, the GOVERNANCE.md is a bit outdated, isn't it?)

**Comment by phillipj** [comment]
Nice @mikeal :+1:

**Comment by ghost** [comment]
any progress on this? haven't heard from it in a while

**Comment by bnb** [comment]
@sup I would add you, but I'm not a team maintainer (just checked). @fhemberger @snostorm or @therebelrobot, as well as @mikeal and maybe a few other Org owners can add you. I'd say we've got the +1 for at least @sup, and if anyone else from the list above expresses interest soon, we can add them too.

**Comment by matthewloring** [comment]
@bnb I would be happy to become a collaborator as well.

**Comment by bnb** [comment]
@matthewloring Okay, just need another WG member to +1 you and you're set.

**Comment by evanlucas** [comment]
I'm not a WG member, but +1 to @matthewloring

**Comment by xcatliu** [comment]
@bnb I'm ready to contribute to the website with you 😀

**Comment by fhemberger** [comment]
@bnb Sorry, I've been quite busy lately, so I wasn't able to follow all the contributions which happened in the meantime. That's why I won't participate in the voting as well. Please just let me know who wants to become a contributor and got a +1, and I'll be happy to add them.

**Comment by kohei-takata** [comment]
@bnb I want to be a collaborator!

**Comment by ghost** [comment]
@fhemberger me, I suppose then

**Comment by fhemberger** [comment]
@sup Just added you.

**Comment by ghost** [comment]
@fhemberger thanks!

**Comment by Starefossen** [comment]
I am already a part of Docker and Build working groups, so I probably don't need to become a collaborator here as well. I would like to contribute with more Docker stuff to the website however.

**Comment by phillipj** [comment]
@fhemberger these three was mentioned and has expressed they want to be collaborators, could you add them aswell? ..and close the issue afterwards :)

@matthewloring @kohei-takata @xcatliu

**Comment by fhemberger** [comment]
Unfortunately, GitHub has changed their user role management. Only **organization owners** can send invitations for new members to join (I can only add existing org members to the website team).

@Fishrock123 You're listed as owner, can you please add the new members?

**Comment by Fishrock123** [comment]
@fhemberger Invited all 3.

**Comment by phillipj** [comment]
Closing this since the rest didn't respond.
