### ISSUE TITLE
Travis PR integration broken

### ISSUE THREAD

**Issue by phillipj** [nodejs/nodejs.org#355]
Seems there's an issue with the Travis integration in the newest PRs. Travis still picks up the [commits and run builds](https://travis-ci.org/nodejs/new.nodejs.org/builds), but it's not visible inline in the PRs :(

Examples: https://github.com/nodejs/new.nodejs.org/pull/349, https://github.com/nodejs/new.nodejs.org/pull/350, https://github.com/nodejs/new.nodejs.org/pull/351, https://github.com/nodejs/new.nodejs.org/pull/353
Compared to: https://github.com/nodejs/new.nodejs.org/pull/313, https://github.com/nodejs/new.nodejs.org/pull/334 which has Travis checks inline.

I can contact Travis about the issue, but I'll like to know the Travis webhook status from our perspective first, but I dont have sufficient repo access. Could some of the repo owners please check `Settings -> Webhooks & Services`?

/cc @mikeal @rvagg

**Comment by lpinca** [comment]
Unrelated but I also wonder if greenkeeper bot is working. `node-version-data` has been updated to version `1.0.1` but we didn't receive a pr yet.

**Comment by mikeal** [comment]
I see one webhook to a random IP address and another to greenkeeper, so maybe it got turned off?

**Comment by phillipj** [comment]
Hmmm.. Not part of the `Settings -> Webhooks & Services -> Services` list either @mikeal?

Pretty sure @rvagg has said we've got a webhook setup too autodeploy the site, that might be the random IP.

**Comment by mikeal** [comment]
oh, that is there :) it say travis is working and is wired up to @rvagg's account.

**Comment by phillipj** [comment]
Thanks! I'm in contact with Travis support about this now.

**Comment by BanzaiMan** [comment]
Hello there! The integration seems to be off because we lost some crucial data about this repository while syncing. Could an admin of this repository (is it you, @mikeal?) log out and back in to https://travis-ci.org, and resync data to see if that fixes the issue?

**Comment by phillipj** [comment]
@BanzaiMan I just removed the old Travis service link, hooked up with @rvagg's account, then created a new link with my account. Unfortunately didn't work. Travis doesn't know about this repo https://travis-ci.org/nodejs/nodejs.org, even though we have had 3 commits since the Travis service links was altered. 

And it still looks like the old service link is active somehow, as new commits are getting built: https://travis-ci.org/nodejs/new.nodejs.org.

As the nodejs organization don't allow private access to third-party applications, I'm assuming re-sync on http://travis-ci.org/profile isn't possible?

**Comment by rvagg** [comment]
I believe greenkeeper is broken for the same reason as travis, we've disabled third-party app integrations—I'm not sure what the context of this was, I guess security, but it should still be possible to do it with personal authentication tokens. I've tried putting mine back into this repo (sorry @philipj, I nuked yours before I realised what it was and that may explain why it hasn't worked properly) but I'm not sure if works or not. Feel free to remove mine and try again with another one if this is the case.

**Comment by phillipj** [comment]
Np, though the issue remains after you linked it back to your account @rvagg. The old Travis service link still picks up the commits/branches. Tested it by pushing a new test branch: https://travis-ci.org/nodejs/new.nodejs.org/builds/92936211

https://travis-ci.org/nodejs/nodejs.org still isn't found or created obviously :(

@BanzaiMan are you able to delete the old Travis link (new.nodejs.org) which seems to be active somehow?

**Comment by phillipj** [comment]
Still haven't found a solution on this. Have been in contact with three helpful Travis support employees, without luck. Their conclusion is we have to provide org wide 3rd party access to their app. Manually adding a webhook on our side isn't possible either.

@mikeal rumours has it you have some ideas around this?

**Comment by phillipj** [comment]
Ping @mikeal

**Comment by Fishrock123** [comment]
I had to temporarily turn on Travis access to cancel some stuck builds from `readable-stream`, so I think builds might be re-enabled here?

It seems travis only gives you auth if it has private data access for some reason or other. (Maybe it needs that to view members or teams?)

**Comment by phillipj** [comment]
Yupp, Travis builds branches but sadly doesn't integrate build status on PRs :(

One reply I got from Travis support might shed some light on why 3d party access is needed:

> At the moment our GitHub synchronization is based on the /user/repos payload (https://api.github.com/users/rvagg/repos). We use this to determine user permissions on repoositories (these are visible when authenticated). We need to know about at least one user with write permissions.
> 
> I'll talk to the rest of the team to see if there's any way for us to get this working without 3rd party access globally turned on. However, I'm pretty sure our OAuth application needs to be granted access (e.g. see https://help.github.com/articles/approving-third-party-applications-for-your-organization/) in order for us to have any kind of write access (setting build status information etc).

..we never found a solution around it.

**Comment by phillipj** [comment]
So when Travis can't help us, we've got to fix it ourselfs, right?

I just created [nodejs-github-bot](https://github.com/nodejs-github-bot) to help us get integrated build status from Travis, in the form of comments seen in https://github.com/nodejs/nodejs.org/pull/539#issuecomment-189016995. It starts polling Travis as soon as a new PR opens. Haven't implemented PR updates yet. We'll have to see how useful this gets in the future, but pretty confident it could do some good.

Closing this issue for now.

**Comment by stevemao** [comment]
Just out of curiosity, @phillipj is the script of the bot open source?

**Comment by phillipj** [comment]
Absolutely @stevemao! Its in a throw-it-together state atm, I'll push it up after cleaning it up :)

**Comment by phillipj** [comment]
@stevemao https://github.com/nodejs-github-bot/bot

**Comment by stevemao** [comment]
Looks good @phillipj :)

**Comment by stevemao** [comment]
Hi @phillipj , I received an email saying org let travis access our private data. But I still can't see status on our new PR?

**Comment by Fishrock123** [comment]
@stevemao I'm not sure why you got that email, but I enabled and disabled it to let citgm get Travis builds.

We aren't going to let Travis have full time private access. Sorry. This is a problem on travis' end but they don't seem to have any interest fixing it.

**Comment by stevemao** [comment]
No worries @Fishrock123 , 
I think everyone in the org got the email.
Why don't we do the same with this repo then?

**Comment by phillipj** [comment]
@stevemao this repo has a Travis partially turned on :) Read more about it in  https://github.com/nodejs/citgm/issues/102

**Comment by MylesBorins** [comment]
@Fishrock123 I think the entire org got that email when you flipped the bit

**Comment by Fishrock123** [comment]
Eh, oh well.
