### ISSUE TITLE
cnodejs website shutdown

### ISSUE THREAD

**Issue by himself65** [nodejs/nodejs.org#3556]
For some reason, http://cnodejs.org/ has shut down for a few months.

**Comment by nschonni** [comment]
Should it be removed from the community page? I think that's the only relation it has to this site

**Comment by MrSlimCoder** [comment]
Guy's why this website is down?

**Comment by himself65** [comment]
@slimcoders 

previously there're ads about the proxy server(to bypass the GFW), and the server of the website is in CN mainland. So they banned the site.

currently, the server of the site is outside now
