### ISSUE TITLE
Paris 

### ISSUE THREAD

**Issue by Knighton910** [nodejs/nodejs.org#359]
Hey guys, I know I'm a few days late, but i think it would look nice, if node.org had a little paris icon showing some sort of support of paris. 

hopefully an icon like this or something similar. 
![890200](https://cloud.githubusercontent.com/assets/1773260/11171132/04e0e502-8b9d-11e5-8f9d-901f11786361.jpeg)

Let me know what you think @mikeal

**Comment by rvagg** [comment]
I love the sentiment here but the prospect of having to discuss and find the line of what causes we want to support and the causes that are _out of scope_ or too trivial for us makes me very concerned. It's not that I don't want us to support causes, it's just that we are such a culturally diverse organisation that finding shared values is extremely difficult and discussions about individual words can get overheated.

So unfortunately I have to be -1 on nodejs.org being used to support causes. We have enough pain and division to deal with already without adding on the potential for more.

**Comment by jasnell** [comment]
I agree with @rvagg

**Comment by Knighton910** [comment]
Okay, fair enough & thanks for taking the time out for a proper response.

**Comment by jasnell** [comment]
@kelthenoble ... definitely appreciate the sentiment tho.

**Comment by Knighton910** [comment]
No worries man @jasnell

**Comment by stevemao** [comment]
I'm closing this now but feel free to reopen :)
