### ISSUE TITLE
Link from releases.md to a machine-readable version

### ISSUE THREAD

**Issue by fulldecent** [nodejs/nodejs.org#3591]
Currently the page https://nodejs.org/en/about/releases/ provides a human-readable list of supported Node.js versions. That's great.

Please link directly from that page to a machine-readable version of the same information.

---

P.S. I am working on GitHub Actions for building Node.js projects. Having this information will be helpful for me because then GitHub Actions can stay up-to-date and support continuous integration workflows always including new supported versions of Node.js.

---

P.P.S. I hate projects that say "we require Node.js v10, it's still supported, and when enough people complain we'll start thinking about v11 [sic]"

**Comment by rodion-arr** [comment]
Hey @fulldecent, does this link fits your needs?
https://nodejs.org/dist/index.json

**Comment by fulldecent** [comment]
Thank you, this is related. But it does not show which releases are supported.

**Comment by richardlau** [comment]
The canonical source of truth for releases is the Release WG (https://github.com/nodejs/Release). A machine readable format can be found in https://github.com/nodejs/Release/blob/master/schedule.json and is what is used to build https://nodejs.org/en/about/releases/ (see https://github.com/nodejs/nodejs.org/blob/master/scripts/helpers/release-schedule.js).

I believe the Package Maintenance Group (https://github.com/nodejs/package-maintenance) were looking at things like tools/guidelines for CI such as GitHub Actions. https://github.com/pkgjs/nv, for example, provides a Node.js API.

**Comment by ovflowd** [comment]
Closing as there are already machine readable formats.
