### ISSUE TITLE
Is `if (err) { return callback(err); }` just a shorthand for `if (err) { callback(err); return; }`

### ISSUE THREAD

**Issue by ugultopu** [nodejs/nodejs.org#3594]
In the article [What are callbacks?], we have the following code snippet:

```javascript
function processData (callback) {
  fetchData(function (err, data) {
    if (err) {
      console.log("An error has occurred. Abort everything!");
      return callback(err);
    }
    data += 1;
    callback(data);
  });
}
```

Now, if I understand correctly, `fetchData` is an asynchronous function. And `function (err, data) {// Function body}` is the callback that's passed to `fetchData`. `fetchData` will call this callback whenever the data is available, or whenever an error occurs while fetching the data.

My question is, in the callback, in the case of an error, why are we returning a value (in this case, `return callback(err);`)? If I understand correctly, the callback will be called by `fetchData`. Hence, anything returned from the callback will actually be returned _back_ to the body of the `fetchData` function. What can `fetchData` do with anything that we return to it?

In order words, my understanding is that `fetchData` calls our callback (the function that we pass to `fetchData`) because it is done with its operations (that is, it fetched the data) and now it wants to give the control to us, to our code, along with the data that it has fetched. But when there is an error, we call our main callback with the error, and whichever result that it generates, we _pass it back_ to `fetchData` (because we `return callback(err);`). I don't understand what can `fetchData` possibly do with the value that we return back to it. Is there an error recovery mechanism? If so, how does it work? What kind of data are we supposed to _return (back)_ to `fetchData` for such error recovery to happen. I don't understand.

Hence, my thought was that `return callback(err);` is just a shorthand for `callback(err); return;`. Is that correct?

[What are callbacks?]: https://nodejs.org/en/knowledge/getting-started/control-flow/what-are-callbacks/

**Comment by ugultopu** [comment]
In other words, if the callback used if-else, instead of just if, then it wouldn't need to use `return callback(err);` right? Then the code would have just been:

```javascript
function processData (callback) {
  fetchData(function (err, data) {
    if (err) {
      console.log("An error has occurred. Abort everything!");
      callback(err);
    } else {
      data += 1;
      callback(data);
    }
  });
}
```

Is this correct?

**Comment by Trott** [comment]
`return callback(err)` is idiomatic in Node.js. It makes it clear that we're dealing with error handling but that the happy path is the rest of the code. It avoids the happy path from being tucked away in an else block. I'm not saying these are or aren't good reasons for the idiom--just that it happens to be the idiom and that's why the docs do that.

**Comment by Trott** [comment]
For what it's worth, I do find your suggestion harder to read. Where's the happy path? It's not clear. And if the function were longer, it wouldn't be clear whether or not more code runs after the callback if there's an error. With the existing code, it's clear that it doesn't.

**Comment by Trott** [comment]
> Hence, my thought was that `return callback(err);` is just a shorthand for `callback(err); return;`. Is that correct?

Yes. (However the first resembles the idiom in Node.js and the second resembles the idiom of Python.)
