### ISSUE TITLE
Bootstrap/Font Awesome?

### ISSUE THREAD

**Issue by AustinWinstanley** [nodejs/nodejs.org#36]
Is this project going to use Bootstrap at all for things like a mobile menu and standardized component styling? 

What about Font Awesome for download icons, content icons, etc.?

**Comment by fhemberger** [comment]
> Is this project going to use Bootstrap at all for things like a mobile menu and standardized component styling?
No, we won't.

> What about Font Awesome for download icons, content icons, etc.?
I'm not aware that we need a lot of icons right now. When we need some, we'll use SVG images instead of icon fonts for performance and optimized mobile display.

**Comment by AustinWinstanley** [comment]
Ok, was just curious as I was working on the site
