### ISSUE TITLE
Incorrect npm version information on download page

### ISSUE THREAD

**Issue by pspletinckx** [nodejs/nodejs.org#3602]
https://nodejs.org/en/download/current/
Google Chrome Version 87.0.4280.88 (64-bits)
Windows 10

The current version download page claims:
"Latest Current Version: 15.5.0 (includes npm 7.3.0)"

But the release ships with npm 6.2.0

**Comment by nschonni** [comment]
No, it's correct https://github.com/nodejs/node/tree/master/deps/npm
Maybe you have an older NPM version that you installed yourself

**Comment by pspletinckx** [comment]
Yes you are correct. 
I was executing ./npm --version in the the extracted zip package of 15.5.0
somehow this still outputted the version found in ~\AppData\Roaming\npm (6.2.0)
Version is indeed 7.3.0

Thanks for clarifying!
