### ISSUE TITLE
doc: no document page about Atomics API

### ISSUE THREAD

**Issue by yuanchieh-cheng** [nodejs/nodejs.org#3610]
I didn't found any documentation about the Atomics API but only on MDN.  
Did I miss something or where the doc exists ?

Thanks.

**Comment by Trott** [comment]
> I didn't found any documentation about the Atomics API but only on MDN.
> Did I miss something or where the doc exists ?

MDN would be the right place. We generally don't document language features like Atomics, Promises, or TypedArrays. These things are usually better and more accurately documented in places like MDN.

I'm going to close this, but feel free to comment and/or re-open if there's more to be said!
