### ISSUE TITLE
Add "Edit on GitHub" link to pages

### ISSUE THREAD

**Issue by Starefossen** [nodejs/nodejs.org#363]
I think it would be very nice, and a lot easier for people to contribute with improvements to the website, by having an "Edit on GitHub" link on all pages that can be edited.

Many Open Source projects hosted on GitHub have this:
- [Polymer](https://www.polymer-project.org/1.0/docs/devguide/feature-overview.html) `Edit on GitHub`
- [Angular](https://docs.angularjs.org/guide/introduction) `Improve this Doc` 
- [Ember](http://guides.emberjs.com/v2.2.0/) ✏️

**Comment by fhemberger** [comment]
Good idea. A PR would be very welcome.

**Comment by mikeal** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by hoxoa** [comment]
Will take a look at this.

Any preferences for wording? And do you want only a text or a icon or both?

**Comment by fhemberger** [comment]
I like "Edit on GitHub". It shows directly, where it will take you and that you require a GitHub account to edit the page. All other links on the website are text links, so we should keep it that way.

**Comment by bnb** [comment]
+1 to "Edit on GitHub" and taking directly into edit mode. If edit mode isn't possible, taking them directly to the file they're looking at would be next-best. 

You'll have to write a script to convert the URL to the current page in the repo. Or you could do something with templating by adding a variable or iterating on an existing one.

**Comment by fhemberger** [comment]
We already store the locale and the path, but you can't use
`https://github.com/nodejs/nodejs.org/blob/master/locale/{{site.locale}}//{{ path }}.md` all the time, for example:
- `nodejs.org/en/security/` → `/en/security.md`
- `nodejs.org/en/downloads/` → `/en/downloads/index.md`

**Comment by Starefossen** [comment]
I arrived at the same conclusion when I dug down into it.

**Comment by fhemberger** [comment]
Hmm, maybe we can get the original filename from Metalsmith during page generation …

**Comment by vadimdemedes** [comment]
Submitted a PR #400 to fix this issue, let me know what you think.

**Comment by Starefossen** [comment]
Just out of curiosity, have you noticed any difference since introducing the "Edit" link? Too early to tell maybe :confused:
