### ISSUE TITLE
Discrepancy in advertised 14.x LTS versions (14.15.0 vs 14.15.4)

### ISSUE THREAD

**Issue by thbar** [nodejs/nodejs.org#3634]
If one looks at https://nodejs.org, the advertised LTS version is "14.15.4 LTS".

On the other hand, querying the registry via the API here :

`curl https://registry.npmjs.org/-/package/node/dist-tags | jq .`

will show LTS as `14.15.0`:

```json
{
  "latest": "15.4.0",
  "lts": "14.15.0", <-here->
  "v6-lts": "6.17.1",
  "v8-lts": "8.16.2",
  "v4-lts": "4.9.1",
  "v10-latest": "10.18.0",
  "v8-latest": "8.17.0",
  "v11-latest": "11.15.0",
  "v10-lts": "10.23.0",
  "v12-latest": "12.14.0",
  "v12-lts": "12.20.0",
  "old": "10.21.0",
  "v14-lts": "14.15.2"
}
```

The versions displayed at https://www.npmjs.com/package/node show the same numbers:

![CleanShot 2021-01-11 at 21 30 47@2x](https://user-images.githubusercontent.com/10141/104234854-567dc080-5454-11eb-9cb0-30031da1ccc7.png)

Is it expected?

I was using the registry API to compare versions in the past (with 12.x) and I don't remember seeing this type of differences.

Thanks!

**Comment by richardlau** [comment]
You'll have to ask the maintainers of the [`node` package](https://www.npmjs.com/package/node) on npm -- it's not managed by this project.

**Comment by thbar** [comment]
@richardlau thanks for the clarification! I'll ask over there.
