### ISSUE TITLE
[Info] OpenJS - upcoming conference news

### ISSUE THREAD

**Issue by jorydotcom** [nodejs/nodejs.org#3652]
Wanted to share this FYI out to the Node.js community to let ya’ll know that the OpenJS Foundation has opened its [call for speakers](https://openjsf.org/announcement/2021/01/11/openjs-world-2021-save-the-date/) for the upcoming virtual OpenJS World event on 9 June 2021. We would love to make sure the project is well represented in the conference content! If anyone is interested and has more questions, wants help writing an abstract, or wants to get involved with the CFP Reviews, email me at jory @ thestoryofjory dot com or ping me in Slack.

We’d also love your help getting the word out about the event - if you’d be up to putting a link or banner on the project website, tweeting from your project account, etc. we would be very grateful!

**Comment by MrJithil** [comment]
Hi @jorydotcom 

I registered for OpenJS World 2021, and the registration details showing the event date as 02 June 2021. So, could you please reverify whether it's on 9th June or 2nd June?

Evidence:
![image](https://user-images.githubusercontent.com/26359740/118539481-182f3f80-b76d-11eb-90d3-be2056104253.png)

![image](https://user-images.githubusercontent.com/26359740/118539704-5d537180-b76d-11eb-8bbd-53b9630865ed.png)

**Comment by jaas666** [comment]
This relates to last year's event. Can we close the issue or is there a particular reason we are keeping it open?
