### ISSUE TITLE
Nodejs 5.1.0 Error in mac os x el capitan

### ISSUE THREAD

**Issue by isathish** [nodejs/nodejs.org#369]
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'npm-autoinit/autoinit'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12

npm ERR! Callback called more than once.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/isathish/npm-debug.log

**Comment by stevemao** [comment]
Looks like this is an npm issue not the website. Try running 'npm install' to install your deps before running your command. If still fails, make sure your deps are installed properly.

**Comment by ghost** [comment]
also, if you have any further issues, report the bug at https://github.com/npm/npm/issues. this is just the nodejs website, not even nodejs itself :smile:
