### ISSUE TITLE
Remove hashtag #blackLivesMatter or change it to #AllLivesMatter. 

### ISSUE THREAD

**Issue by DomeQdev** [nodejs/nodejs.org#3729]
Don't trust posts like this: [#AllLivesMatter hashtag is racist, critics say (USA TODAY)](https://eu.usatoday.com/story/news/nation-now/2016/07/13/why-saying-all-lives-matter-opposite-black-lives-matter/87025190/).

Like, you can challenge or kill white without protests, but if black, no... 

Thanks :D

**Comment by Trott** [comment]
https://github.com/nodejs/nodejs.org/issues/3229
