### ISSUE TITLE
could dependabot be disabled on forks?

### ISSUE THREAD

**Issue by targos** [nodejs/nodejs.org#3748]
Since I forked this repository, I'm getting dependabot pull requests on my fork, which is very annoying: https://github.com/targos/nodejs.org/pulls
Is it possible to only enable it for the main repository?

**Comment by nschonni** [comment]
No, its something that's currently missing from a GitHub perspective. When the .yaml file exists, it currently creates them in forks

**Comment by targos** [comment]
I don't understand, because the GitHub's documentation says it has to be explicitly enabled in forks: https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-version-updates-on-forks

I suppose I can delete the file to disable it on my side?

**Comment by XhmikosR** [comment]
@targos yup, you need to delete the file since there's no way to do this any other way yet.

**Comment by asciimike** [comment]
Dependabot PM here,

Version updates should be disabled on forks by default, but there's a gnarly edge case that sometimes happens here. Deleting and re-forking should solve it, though admittedly it's not the best experience.

We're tracking this issue internally and hopefully can resolve it soon!

**Comment by targos** [comment]
I recreated my fork. Thanks for the workaround!
