### ISSUE TITLE
Grammatical error in privacy.md doc

### ISSUE THREAD

**Issue by av1shek** [nodejs/nodejs.org#3752]
There is a grammatical error in privacy.md. ```Below, we provide a brief summary these activities.``` it should be "Below, we provide a brief summary  **of** these activities."

Screenshot
![img1](https://user-images.githubusercontent.com/59140024/110217106-5809b900-7ed8-11eb-81f5-16478a61234c.png)

**Comment by MrJithil** [comment]
@av1shek Can we close this issue?

**Comment by av1shek** [comment]
@MrJithil I thought it is already closed along with my PR.
