### ISSUE TITLE
Bash script on downloads page uses a command that is not installed on Mac

### ISSUE THREAD

**Issue by focarroll** [nodejs/nodejs.org#3758]
* **URL**: [https://nodejs.org/en/download/package-manager/#macos](https://nodejs.org/en/download/package-manager/#macos)
* **Browser version**: Google Chrome 88.0.4324.192
* **Operating system**: Mac OSX 10.15.7

By going to [the link above](https://nodejs.org/en/download/package-manager/#macos), you can see the following code:

```bash
curl "https://nodejs.org/dist/latest/node-${VERSION:-$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-(.*)\.pkg</a>.*|\1|p')}.pkg"
```

This bash script uses the command `wget`. However, Mac OS does not come with `wget`, meaning that this cannot be used.

**Comment by focarroll** [comment]
After some trial and error, I've found a possible solution for Mac users:

```bash
curl -O "https://nodejs.org/dist/latest/$(curl -s https://nodejs.org/dist/latest/ | grep "pkg" | cut -d'"' -f 2)"
```

**Comment by aldarmak** [comment]
Thanks a lot sir

**Comment by MrJithil** [comment]
Can I update it? @aldarmak

**Comment by zelma83** [comment]
"https://nodejs.org/dist/latest/node-${VERSION:-$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-(.*)\.pkg</a>.*|\1|p')}.pkg" > "$HOME/Downloads/node-latest.pkg" && sudo installer -store -pkg "$HOME/Downloads/node-latest.pkg" -target "/"

**Comment by mwenku** [comment]
is this issue still open ?

**Comment by AugustinMauroy** [comment]
the command don't refers to the issue is no longer present on the site, so you need to check whether it's still relevant.

EDIT:
`wget` still not on macOS. And command still have `wget`

**Comment by focarroll** [comment]
Finally
