### ISSUE TITLE
Investigate issues with greenkeeper bot

### ISSUE THREAD

**Issue by lpinca** [nodejs/nodejs.org#377]
@phillipj has already created this issue https://github.com/greenkeeperio/greenkeeper/issues/68.

If anyone has a clue on why the bot is not working, please share.

This is the list of dependencies to update:

```
Package              Current  Wanted  Latest  Location
chokidar               1.2.0   1.2.0   1.3.0  nodejs.org
handlebars             4.0.4   4.0.4   4.0.5  nodejs.org
metalsmith-metadata    0.0.2   0.0.2   0.0.3  nodejs.org
nock                  2.18.2  2.18.2   3.3.0  nodejs.org
node-version-data      1.0.0   1.0.0   1.0.1  nodejs.org
semver                 5.0.3   5.0.3   5.1.0  nodejs.org
```

**Comment by phillipj** [comment]
Just noticed there's an error on our side of the greenkeeper webhook. It says it got a 400 status last time it tried to contact greenkeeper. I'll try to sync and/or re-enable greenkeeper as soon as I've got the time.

**Comment by christophwitzko** [comment]
Hi @lpinca,
Hi @phillipj,

renaming the repository from `new.nodejs.org` to `nodejs.org` might caused the problem.
You can fix that issue by running `greenkeeper sync`.

Have a great day,
Christoph

**Comment by phillipj** [comment]
Thanks for answering @christophwitzko!

Just tried `$ greenkeeper sync` but it didn't have any effect as far as I can see, the webhook link in this repo's settings are still in a bad state. Also tried `$ greenkeeper enable` which ended in this message:

``` bash
→ greenkeeper enable
🌴  info enable The GitHub slug is: nodejs/nodejs.org
🌴  ERR! enable Couldn’t enable a project with this slug.
🌴  ERR! enable If you want to try your free private repo make sure to grant the necessary rights by running $ greenkeeper login --force --private
🌴  ERR! enable You have to have a plan for more than one private repo. To verify run $ greenkeeper whoami
🌴  ERR! enable If you have just recently created this repo try running $ greenkeeper sync
🌴  ERR! enable You need admin access to a repo to enable it.
🌴  ERR! enable If you think this error really shouldn’t appear let us look into it with $ greenkeeper support
```

Do you know if greenkeeper requires private access to the nodejs github organization? If so we're in bad luck, because we dont allow that kind of permission to any third-party app.

**Comment by christophwitzko** [comment]
Hey @phillipj,

thanks for trying. No, Greenkeeper does not require private access. At the moment it looks like Greenkeeper has even no public access to the `nodejs` organization from your account. Can you revoke access for Greenkeeper application [here](https://github.com/settings/applications), then run `greenkeeper login --force` and grant access to the `nodejs` organization.

Thank you for your patience,
Christoph

**Comment by phillipj** [comment]
@christophwitzko I revoked it, and logged in again as you described. When looking at the greenkeeper settings, the only option I have next to the nodejs org is "request access". Pressing that button warns me  it will request org owners for private access. No point going further that way, as nodejs org owners won't allow that anyway..

**Comment by mikeal** [comment]
Ya, we need to configure the repo with a push url, we can't grant org wide priviledges to apps.

**Comment by stevemao** [comment]
Since we've disabled third-party app integrations, we can't use greenkeeper any more :( should we close this issue?

**Comment by mikeal** [comment]
I just got a ping from @janl letting me know that they have a greenkeeper enterprise that might work for us on this. I'll work with Jan and the build team to get something in place.

**Comment by fhemberger** [comment]
@mikeal @janl Any news on this? Or can this issue be closed?

**Comment by janl** [comment]
sorry for letting this drop. We’re still happy to help. GK2 uses GH Apps (neé Integrations) and is available in the Marketplace with an Open Source plan. Feel free to give that a spin and let me know if anything doesn't work for you. — if you need support for private repos, give me a shout.
