### ISSUE TITLE
Make release blog post script compatible with v0.12.x releases

### ISSUE THREAD

**Issue by phillipj** [nodejs/nodejs.org#380]
As noted by @rvagg while creating the release notes for v0.12.8 in https://github.com/nodejs/nodejs.org/pull/379, the `./scripts/release-post.js` script which usually creates these blog posts, isn't compatible with v0.12.x releases. Since v0.12 is still supported and will get important fixes, the release blog post script should be able to handle these versions aswell.

Trying to run the script for v0.12.8 quickly reveals atleast one thing needs fixing:

``` bash
# delete existing blog post first, it will fail if it already exists
→ rm locale/en/blog/release/v0.12.8.md
→ ./scripts/release-post.js 0.12.8
Some error occured here! Error: Invalid status code (!= 200) while retrieving https://raw.githubusercontent.com/nodejs/node/v0.12.8/CHANGELOG.md: 404
    at ClientRequest.<anonymous> (/nodejs.org/scripts/release-post.js:46:23)
    at ClientRequest.g (events.js:260:16)
...
```

**Comment by rvagg** [comment]
It goes further than just the name, it's also the contents—the titles aren't the same format as they are now on `master` and we don't Markdown the commits list (nor do we have anything but the commits list).

We could change some of that though, I've been thinking of at least changing the titles so they match, the rest is more difficult without doing the full Markdown conversion of `ChangeLog` -> `CHANGELOG.md` like we did back in io.js.
