### ISSUE TITLE
"404 Page Not Found" Cannot work properly when we don't have a language

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#3802]
Now for the Nodejs page, if we have a language that doesn't exist, a 404 page will be shown.
E.g: https://nodejs.org/cn

However, if you see the page, everything doesn't seem work properly (Language Icon cannot be clicked to choose a language, "Contributor" is still running....), ect.

![image](https://user-images.githubusercontent.com/52018749/115014627-29bec680-9ee5-11eb-8db5-757d615d29f6.png)

IMO: I tend to say that this is a bug, and we should redirect the current user to the default (English) page, something like "
https://nodejs.org/en/404", and this will make everything work properly. It'd be better if we can keep the wrong URL but still make them work properly (or something we can use like https://nodejs.org/en/404?from=https://nodejs.org/cn)?

Not sure whether we have a Ngnix group to fix it by redirecting the user to the correct 404 page with related language...For I later noticed that we have multi-language 404 page...?

PS: If we have the language but with a wrong part back, something like (https://nodejs.org/zh-cn/wrongLink), this is fine：
![image](https://user-images.githubusercontent.com/52018749/115016607-dd28ba80-9ee7-11eb-9142-67ccb9dc1ab1.png)

What do you think of this?

**Comment by MaledongGit** [comment]
Not sure whether we have a Ngnix group to fix it by redirecting the user to the correct 404 page with related language...For I later noticed that we have multi-language 404 page...?

PS: If we have the language but with a wrong part back, something like (https://nodejs.org/zh-cn/wrongLink), this is fine.

**Comment by nschonni** [comment]
Might be a duplicate of https://github.com/nodejs/nodejs.org/issues/2984, but there is more details here

**Comment by ghost** [comment]
Thank you @nschonni to notify me on another issue related to this，sorry for the late response because of busy work.

Ping @nodejs/build ，maybe two senarios should be included after reading the issues：

1. https://nodejs.org/wronglang
2. https://nodejs.org/rightlang/wronglocation

**Comment by MrJithil** [comment]
@MaledongGit For a part of the statements, "language icon will not work properly", I added a fix for that. #3823 

Could you please elaborate specifically what are the other areas which not working while accessing a invalid locale. 

I think, we can work together to rectify all these issues.

**Comment by ghost** [comment]
> @MaledongGit For a part of the statements, "language icon will not work properly", I added a fix for that. #3823
> 
> Could you please elaborate specifically what are the other areas which not working while accessing a invalid locale.
> 
> I think, we can work together to rectify all these issues.

Thank you.
Just as what I said in my 1st post：Contributor block cannot work, either.
