### ISSUE TITLE
Website doesn't mention v16.0.0 current

### ISSUE THREAD

**Issue by targos** [nodejs/nodejs.org#3810]
https://direct.nodejs.org/en/

Is there something to do?

/cc @nodejs/releasers

**Comment by targos** [comment]
The blog post at https://nodejs.medium.com/node-js-16-available-now-7f5099a97e70 links to https://nodejs.org/en/download/current/ which is still rendered with v15.14.0.

**Comment by nschonni** [comment]
![image](https://user-images.githubusercontent.com/1297909/115431721-9e3e8180-a1d3-11eb-8c04-2eade100a1f4.png)
It takes time for the site to build out after the PR was merged

**Comment by nschonni** [comment]
PS: Note sure what the "direct" subdomain is used for

**Comment by targos** [comment]
> It takes time for the site to build out after the PR was merged

Sorry, I thought that the build was finished because the blog post was there.

> PS: Note sure what the "direct" subdomain is used for

I use that subdomain to make sure it's not related to Cloudflare's cache.

**Comment by nschonni** [comment]
No worries, I never remember where that webhook status log URL is either 😄 

> I use that subdomain to make sure it's not related to Cloudflare's cache.

Neat, thanks!
