### ISSUE TITLE
Missing link for Apple Silicon (arm64) on download page

### ISSUE THREAD

**Issue by targos** [nodejs/nodejs.org#3811]
Starting with v16.0.0, we have official Apple Silicon tarballs.
It should be available on https://nodejs.org/en/download/current/

**Comment by richardlau** [comment]
https://github.com/nodejs/nodejs.org/blob/master/layouts/partials/primary-download-matrix.hbs is the relevant template, but some care will need to be taken to not insert the Apple Silicon tarball for the LTS release.

**Comment by MrJithil** [comment]
@targos @richardlau Could you please confirm the download URL for Silicon Tarball? 
https://nodejs.org/dist/latest-v16.x/node-v16.0.0-darwin-arm64.tar.gz

**Comment by targos** [comment]
That's the right URL
