### ISSUE TITLE
Request to be a proofreader

### ISSUE THREAD

**Issue by Kajachuan** [nodejs/nodejs.org#3816]
Hi everyone. I have been translating the nodejs-website to Spanish language. I noticed that this project has 42% of translated words but only 5% of approved words. I would like to help to review the Spanish translations to increase the percentage of approved words.

I currently have about 12000 words translated in this project in Crowdin and I attach a screenshot to prove it.

![image](https://user-images.githubusercontent.com/20827737/115937066-4a4ec980-a46d-11eb-91f3-96bc16f66a28.png)

Thanks and greetings.

@nodejs/nodejs-es
@nodejs/crowdin-managers-website

**Comment by Trott** [comment]
@nodejs/nodejs-es 
@nodejs/crowdin-managers-website

Hi! Are you asking for something to happen on Crowdin? Or asking to be added to @nodejs/nodejs-es? Or something else?

**Comment by Kajachuan** [comment]
Hi. I am requesting to be a proofreader in Crowdin. Is this the right repository or should I ask for it in another one? 
Thanks.

**Comment by alexandrtovmach** [comment]
@Kajachuan Thanks for your effort, and yeah, sorry for delay. It's because your mentions doesn't works =| (thanks @Trott for proper one 😉)

Checked your contributions and added you proofreader access in "nodejs-website" and "api-docs" projects

**Comment by Trott** [comment]
Sounds like this can be closed, but if I"m wrong, please comment or re-open.
