### ISSUE TITLE
To semicolon or not to semicolon

### ISSUE THREAD

**Issue by liquidmetalrob** [nodejs/nodejs.org#3826]
Hey Node,
I thought you didn't believe in trailing semicolons.
No semicolons: https://nodejs.dev/learn/reading-files-with-nodejs
Yes semicolons: https://nodejs.org/en/docs/guides/getting-started-guide/
Which is it?

**Comment by nschonni** [comment]
`nodejs.dev` is a different repo. In terms of the style, there isn't one currently as there is no in-line linting, as being tracked in https://github.com/nodejs/nodejs.org/issues/2523
