### ISSUE TITLE
Add an embedding API for Node.js

### ISSUE THREAD

**Issue by irbull** [nodejs/nodejs.org#384]
To enable Node to be embedded into other applications, I would like to propose some new API. In particular, once the platform, isolate and context has been created, a callback would be useful to allow embedders to inject custom code before node begins processing.

I would be happy to put a pull request together with some ideas if this would help.

Does anyone have thoughts on this, or maybe something already exists.

**Comment by ghost** [comment]
i think you're in the wrong repository :) probably what you're looking for is [nodejs/node](https://github.com/nodejs/node)

**Comment by Fishrock123** [comment]
@irbull Could you check if the `-r` / `--require` command line flag does what you are asking for? :D

**Comment by irbull** [comment]
@sup Opps... sorry, I hit the wrong repo. @Fishrock123 Thanks for the tip, I'll take a look.
