### ISSUE TITLE
Get nodejs.dev and nodejs.org folks talking somehow

### ISSUE THREAD

**Issue by Trott** [nodejs/nodejs.org#3851]
The current website is in the nodejs.org repository (this repository).

The website in the nodejs.dev repository is, or at least was at some point, intended as a redesign to eventually replace the content at nodejs.org. I honestly don't know if that's still a thing or if it is now intended to be a forever-parallel site hosted at nodejs.dev.

Regardless, there seems to be little overlap between the folks who work on the two sites and I suspect there's not much direct communication going on. That seems bad. 

So, in the hopes of getting a productive dialogue and maybe even some cross-team collaboration (and maybe even some folks working actively on both teams rather than just one or the other), I'm opening this issue here and pinging @nodejs/nodejs-dev.

Not sure what to talk about? Here are some ideas:

* What are the nodejs.dev plans? Is there a timeline? How aware have nodejs.org folks been about those plans?
* Where has communication been happening? Should it be happening differently?
* Are there things that should happen going forward to take proactive steps against surprises and/or looming turf disputes?
* General introductions! "Hi, my name is ABC and I've been working on accessibility issues on the nodejs.example.org website."

**Comment by Trott** [comment]
> The current website is in the nodejs.org repository (this repository).
> 
> The website in the nodejs.dev repository is, or at least was at some point, intended as a redesign to eventually replace the content at nodejs.org. I honestly don't know if that's still a thing or if it is now intended to be a forever-parallel site hosted at nodejs.dev.
> 
> Regardless, there seems to be little overlap between the folks who work on the two sites and I suspect there's not much direct communication going on. That seems bad.
> 
> So, in the hopes of getting a productive dialogue and maybe even some cross-team collaboration (and maybe even some folks working actively on both teams rather than just one or the other), I'm opening this issue here and pinging @nodejs/nodejs.dev.
> 
> Not sure what to talk about? Here are some ideas:
> 
> * What are the nodejs.dev plans? Is there a timeline? How aware have nodejs.org folks been about those plans?
> * Where has communication been happening? Should it be happening differently?
> * Are there things that should happen going forward to take proactive steps against surprises and/or looming turf disputes?
> * General introductions! "Hi, my name is ABC and I've been working on accessibility issues on the nodejs.example.org website."

My attempt to ping @nodejs/nodejs-dev failed because I had a typo, so I'm doing it in this comment instead.

**Comment by Trott** [comment]
Hi! I'm Rich! I've worked a bit on both sites, but haven't been working on nodejs.dev in a long time. My involvement in nodejs.org has been light of late, but I do a lot of work on nodejs docs in the main repo, including fixing up accessibility issues and assuring that our text conforms to our style guide. So I do significant work on the *content* of the sites that way.

**Comment by Trott** [comment]
Hi! I'm Rich! I've worked a bit on both sites, but haven't been working on nodejs.dev in a long time. My involvement in nodejs.org has been light of late, but I do a lot of work on nodejs docs in the main repo, including fixing up accessibility issues and assuring that our text conforms to our style guide. So I do significant work on the *content* of the sites that way.

**Comment by benhalverson** [comment]
👋🏻  I'm Ben I work on nodejs.dev. I've been on the team for about a year and 5 months now. I've heavily contributed to the current [nodejs.dev](nodejs.dev) homepage and [downloads](nodejs.dev/download) page among other things...
A few weeks ago @joesepi and I went though and created a projects view to see what is missing between the nodejs.org and nodejs.dev for feature parity. You can see it [here](https://github.com/nodejs/nodejs.dev/projects/10) 

We also have labeled issues that are marked as [mvp](https://github.com/nodejs/nodejs.dev/issues?q=is%3Aissue+is%3Aopen+label%3AMVP) 

The general chat about website redesign stuff is in the [openjs slack](https://slack.openjsf.org/) in the channel #nodejs-website-redsign and github issues / PR's

**Comment by Trott** [comment]
Thanks, @benhalverson! 

Reading Ben's answer, I realized I asked a bunch of questions about nodejs.dev but I assumed (perhaps incorrectly, hence this comment) that everyone would know that there are no plans/roadmap/timeline/etc. for nodejs.org. People work on what interests them. But if there's going to be a merge or a replacement of nodejs.org with nodejs.dev, it's probably a good idea to get a bit more organized, at least for a period of time.

**Comment by joesepi** [comment]
Hey @Trott and @benhalverson and others. Joe Sepi here chiming in. I help with nodejs.dev now and again, usually from more of a project management standpoint but never with enough time and focus to really be super effective. However, I'm trying to give the effort more of my attention recently (starting last week?) to really help the project achieve its goals.

I'm hoping in the coming weeks, we will have more to show and more of a roadmap of sorts.

Itd be great to get the two teams together in the near future and discuss status and path forward. 

Cheers!

**Comment by ovflowd** [comment]
Closing this as pretty much we addressed these points and finally the codebases are getting "merged" with each other.
