### ISSUE TITLE
Outdated info on Node.js awareness of package.json fields

### ISSUE THREAD

**Issue by ekuusela** [nodejs/nodejs.org#3862]
* **URL**: https://nodejs.org/en/knowledge/getting-started/npm/what-is-the-file-package-json/
* **Browser version**: any
* **Operating system**: any

The "What is the file `package.json`?" article says that Node.js itself is only aware of two fields in the `package.json`: `name` and `version`. But this is outdated and also not very clear how exactly those fields are relevant.

The info here seems to be up-to-date and mentions also `type`, `exports` and `imports` as used by the Node.js runtime: https://nodejs.org/api/packages.html#packages_node_js_package_json_field_definitions

**Comment by AugustinMauroy** [comment]
Knowledge was remove. thanks for your issue
