### ISSUE TITLE
Past events or otherwise problematic events on map

### ISSUE THREAD

**Issue by Trott** [nodejs/nodejs.org#387]
The map for the San Francisco area, for example, has a pin for Nodeconf Adventure north of SF. Following the link will have you ending up at a 404 page.  :-/

(That said, the map is still cool!!!!)

**Comment by mikeal** [comment]
I fixed the link for nodeconf adventure. Please open another issue for any specific problems with the data from meetup.com.

**Comment by Trott** [comment]
I'm not sure the fix in 17d015d is a complete fix. Someone looking at the map is almost certainly looking for upcoming events, not past events... It will be very frustrating to have to click on every thing to try to find events that aren't in the past...  It will also be very frustrating to be a repeat user of the map and have to click on stuff to see if it's changed (or not) from a past event to an upcoming event.

**Comment by mikeal** [comment]
NodeConf Adventure is yearly, it is both a past and future event :)

**Comment by Trott** [comment]
Sure, but the site currently has details for the past event. Until it's updated for the future event, the link/map-point will probably frustrate and puzzle users. (Especially frustrating is that the year is not listed with the dates so there's no immediate indication that it's a past event.)

**Comment by Trott** [comment]
This is not specific to the NodeConf link, of course. At this time, Portland NodeSchool, SF NodeSchool, and many (most?) of the meetups do not have upcoming events scheduled. The map may be frustrating for many users.

**Comment by Trott** [comment]
(All that said, it is a really great idea and I hope it gets constant tweaks to make it better and better all the time. And yeah, I know...I should dive in a tweak it myself...)

**Comment by mikeal** [comment]
So, I don't think the primary utility is to find an upcoming event so much as it is to figure out where the local community endpoints are. To the end most of the active ones make a lot of sense, even some of the inactive ones have value, the only thing I'd like to get rid of are events that, for some reason, tag themselves Node.js but have nothing to do with Node.js.

**Comment by Trott** [comment]
In that case, maybe this is just a feature request for some color coding or something. Like, I think color coding "has an upcoming event scheduled" vs. "no upcoming events scheduled" is going to be at least as useful to the average user than color coding a meetup vs. a NodeSchool vs. a conference.

Of course, it may not be feasible due to API limitations or whatever... :-/

**Comment by mikeal** [comment]
NodeSchool has variations in color for groups with upcoming events. My concern for this page though is that we don't yet have a way to regularly run and update this data so if we end up running less than once every few weeks we won't be up to date enough to really tell if a monthly meetup have something "upcoming" or not :(

**Comment by Trott** [comment]
Perhaps one other thing to consider: The link you click to get to the map says "Events". It's fair to imagine that people who click that link will assume the map is of upcoming events and not a community map or something. I don't know that there's a better place for the map or a way to set the expectation differently. But you know...something to think about anyway.

**Comment by mikeal** [comment]
I feel the same way, I just can't think of a better tab name :)
