### ISSUE TITLE
package-manager docs doesn't have any reference about the `nvs`

### ISSUE THREAD

**Issue by MrJithil** [nodejs/nodejs.org#3873]
The package-manager API docs don't contain any details about the `nvs`. As per the `OpenJS Node.js Services Developer (JSNSD)` certification training, we recommend the devs to use `nvs` to install `NodeJS` in windows machine as the `nvm` not available from Windows. But, we missed adding it to the official documentation here [https://nodejs.org/en/download/package-manager](https://nodejs.org/en/download/package-manager/)

Reference: [NODE.JS SERVICES DEVELOPMENT (LFW212)](https://training.linuxfoundation.org/training/node-js-services-development-lfw212/)

**Comment by MrJithil** [comment]
Working on it.

**Comment by Trott** [comment]
@nodejs/version-management

**Comment by ljharb** [comment]
`nvm` is quite available on windows; sounds like the OpenJS certification training needs updating.

**Comment by MrJithil** [comment]
> `nvm` is quite available on windows; it sounds like the OpenJS certification training needs updating.

You are right in few cases. But, that statement is not fully true. The docs of `nvm` say that "**_nvm also support Windows in some cases. It should work through WSL (Windows Subsystem for Linux) depending on the version of WSL. It should also work with GitBash (MSYS) or Cygwin. Otherwise, for Windows, a few alternatives exist, which are neither supported nor developed by us:_**"

So, we can not edit the certification course with something like the above.

**Comment by ljharb** [comment]
@MrJithil indeed there’s caveats, but let’s chat in the OpenJS foundation slack about updating the certification training so it’s accurate.

**Comment by MrJithil** [comment]
Code changes merged
