### ISSUE TITLE
nodejs.org/locale/es/about/index.md url Blocking vs Non-Blocking doesnt exists

### ISSUE THREAD

**Issue by InigoRomero** [nodejs/nodejs.org#3875]
* ** https://nodejs.org/es/about/**:
* **Brave  V1.24.85 (May 13, 2021)**:
* **Windows 10**:

The url https://github.com/nodejs/node/blob/master/doc/topics/blocking-vs-non-blocking.md doesnt exists and is in the about node page

**Comment by Trott** [comment]
It should be updated to point to https://nodejs.org/es/docs/guides/blocking-vs-non-blocking/. Are you interested in opening a pull request for it?

**Comment by InigoRomero** [comment]
Yes! I do

**Comment by XhmikosR** [comment]
@Trott can this can be closed since #3882 has landed?
