### ISSUE TITLE
Translate to Uzbek

### ISSUE THREAD

**Issue by niyozbek** [nodejs/nodejs.org#3908]
Uzbek is my native language, and I would like to contribute by translating it.

**Comment by nschonni** [comment]
Ping @nodejs/crowdin-managers

**Comment by niyozbek** [comment]
> Ping @nodejs/crowdin-managers

hi,
is it okay to contribute? I'm waiting for an approval

**Comment by aeshakhzod** [comment]
@niyozbek good idea! just PR your commit =)

**Comment by niyozbek** [comment]
Can't find my locale on Crowdin. Crowdin managers did not add Uzbek language to the website.
