### ISSUE TITLE
Browser Detection Notification

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#3960]
Now Nodejs.org official site has been open and support some very old (they are all tired) browsers for a long time for some users to download/watch...ect. Is it a necesary because some companies such as Microsoft, which doesn't support them totally?

So my idea is to give them a tip, something like "Your browser is out of service, please upgrade to the latest version....."(sometimes like GitHub), and for now I don't want to change any js codes (still support the tired browsers but just to be compatible).

**Comment by pawan43563** [comment]
I would love to contribute. can you assign me ?

**Comment by NriotHrreion** [comment]
@MaledongGit: I've submitted my code. Can you come and have a review?

**Comment by ovflowd** [comment]
Closing this as not relevant, as the legacyMain javascript script is going to be removed soon.
