### ISSUE TITLE
Automate the announcement banners

### ISSUE THREAD

**Issue by benhalverson** [nodejs/nodejs.org#3961]
In the nodejs.dev repo I opened an issue to automate the showing or hiding of the banner announcements based on data from this repo. see https://github.com/nodejs/nodejs.dev/issues/1502#issuecomment-872201961

Any thoughts on this?

**Comment by XhmikosR** [comment]
Definitely in favor of this. The more automated things, the better. 👍

**Comment by benhalverson** [comment]
This is done now.
