### ISSUE TITLE
Native support for windows-1251 char encoding

### ISSUE THREAD

**Issue by azev** [nodejs/nodejs.org#3966]
Hi, I'd like to request NodeJS to **natively** support [windows-1251](https://en.wikipedia.org/wiki/Windows-1251) characters encoding.

I can't parse html pages encoded in `windows-1251` (web scraping) because there are no available packages that will work correctly on that conversion properly.

For example, if I have a binary buffer and try `.toString('utf8')` it will work as expected if the data encoded is in `utf8`. But if the string is `windows-1251` encoded the result string will have `???` for russian characters instead.

Related: https://stackoverflow.com/questions/68218368/

**Comment by XhmikosR** [comment]
This is unrelated to this repo, though. You should make an issue in https://github.com/nodejs/node/issues
