### ISSUE TITLE
List of Companies Using Node.js

### ISSUE THREAD

**Issue by nelsonic** [nodejs/nodejs.org#399]
The list of organisations that use Node.js _used_ to be available at: https://nodejs.org/industry/ but currently is a `404`:
![nodejs-website-companies-using-node-404](https://cloud.githubusercontent.com/assets/194400/11536011/671ba634-990e-11e5-84ec-c6ec1f115f67.png)

**Comment by ghost** [comment]
to be honest i don't think that that page is necessary anymore since so many companies/orgs have adopted node that it would be impossible to list all. i mean, everyone knows about node nowadays, we don't have to list people who use it

**Comment by nelsonic** [comment]
@sup sure, _everyone_ is using node these days, but the 404 error _could_ be avoided or re-directed to a more friendly page. I will update my page to no longer link to: https://nodejs.org/industry/ ... thanks!

**Comment by ghost** [comment]
oh, sure. didn't realize you meant that :smile:
