### ISSUE TITLE
Logo usage examples

### ISSUE THREAD

**Issue by circularchaos** [nodejs/nodejs.org#3994]
Hey guys, in the resources page it doesn't mention the usage of the primary pattern. However it is in the docs (https://nodejs.org/en/about/resources/). To confirm, can we use the primary pattern and the JS hexagon by itself or should we only use the whole nodejs logo?

![image](https://user-images.githubusercontent.com/6093036/126619692-b01e77c4-1561-4e60-8a28-a97173bca821.png)
![image](https://user-images.githubusercontent.com/6093036/126619742-a4f128ce-1711-4526-836a-b3dfb4b76cd7.png)

**Comment by Trott** [comment]
@brianwarner Would you be the person who can answer this question? If not, would you be able to point us to the right person?

**Comment by brianwarner** [comment]
Yep, I can answer that. I just looked back to the original agreements that permit OpenJS Foundation to use the Node.js marks, and the JS hexagon is included. Both are fine to use on nodejs.org.

**Comment by circularchaos** [comment]
Great, thanks so much guys!
