### ISSUE TITLE
Translation for Tamil

### ISSUE THREAD

**Issue by code-reaper08** [nodejs/nodejs.org#4003]
## Hello crowdin-managers @obensource @alexandrtovmach 👋
I am planning to do translations for the `Tamil` language, But, I couldn't find my native language `Tamil` [here](https://crowdin.com/project/nodejs-website). It would be nice if it gets added to the list.

And also one more thing about **localization group**, There is a localization group for `Tamil` and it is not maintained and the last commit dates back to **2015**( I know localization groups are not necessary to get involved in the translation process, but it would be great to work as a community.) I am planning to get things super active,  regarding the translation work for `Tamil` and [nodejs-ta](https://github.com/nodejs/nodejs-ta) will help get people to collaborate and to make the translation process quick.

Please guide me on what to do regarding the localization group, and also adding `Tamil` to the locale list in crowdin.

Thanks in advance and hoping for a positive reply 😄

**Comment by AugustinMauroy** [comment]
Kolikor vem, Crowdin ne deluje, vendar lahko pogledate tukaj za prevajanje NodeJS.org (obstaja tudi nodejs.dev, ki ima prevajalski sistem, vendar nodejs dokumentacija ne)
https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md

**Comment by ovflowd** [comment]
Hey @code-reaper08 the i18n group is not as active as you could imagine, right now. Yet, you're completely up to you to just make spontaneous contributions 🎉 

Sadly, as you can see from [this](https://github.com/nodejs/admin/issues/711) issue we're struggling with getting admin access within Crowdin to get that Language added.

Yet, you honestly don't need Crowdin to create Tamil translations. You can just create a `/ta/` folder within the locale folder and copy everything from the `en` folder and start with the translations. (Don't forget to update the `site.json` file!)

**Comment by chinnadurai** [comment]
Hey, Anyone there to support me for tamil language translation for nodejs.org website? I have forked main branch and made necessary changes. If anyone  join with me, then that would be helpful.

**Comment by ovflowd** [comment]
Hey, @chinnadurai please read our `TRANSLATION.md`, all translations are done via Crowdin.

**Comment by ovflowd** [comment]
Closing as all translation efforts are now on Crowdin and discussions should be done there.
