### ISSUE TITLE
Docker tutorial: Name of app exemplified in 'docker build' should be 'docker_web_app' (NOT 'node-web-app') 

### ISSUE THREAD

**Issue by solid-tester** [nodejs/nodejs.org#4018]
* **URL**:  https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

In the above Docker tutorial provided by Node.js: 

The name of the app exemplified in the 'docker build' command (from [Building your image](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/#building-your-image)) 
should be 'docker_web_app' (as per the package.json file exemplified in [Create the Node.js app](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/#create-the-node-js-app))
and NOT 'node-web-app' as actually written in the 'docker build' command.

**Comment by poo17nam** [comment]
docker build command takes the name of the image and that name can be anything you like. It should not necessarily be the name of the project. It also takes path of the Dockerfile which has the details of where to pick the code from for building the image.
Hope it clarifies your concern. If yes, please mark this issue as closed.

**Comment by AugustinMauroy** [comment]
The guides are no longer present on the site, so I close this issue.

[commit or content has been removed](https://github.com/nodejs/nodejs.org/commit/c72dc046dffda7d8b056623602c80bac3dd6a8f4)
