### ISSUE TITLE
Seems like the types for readdirSync is incorrect

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#4036]
When using:

````
const files = fs.readdirSync(path.join(__dirname, 'path/to/dir', {
  withFileTypes: true,
}))
````

You get an error with typescript:

````
Argument of type '{ withFileTypes: boolean; }' is not assignable to parameter of type 'string'.
````

I think the function is likely working, however the types are incorrect (perhaps @types/node I'm not sure), which makes my typescript break on trying to compile this using the above.  

Something like:

````
const readdirSync(path: string, options: string | object)...
````

Probably needs to be added to types.

**Comment by Trott** [comment]
This is the repo for the Node.js website. Try https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node. Good luck.
