### ISSUE TITLE
node-inspector iinstallation problem

### ISSUE THREAD

**Issue by tankdeper** [nodejs/nodejs.org#406]
when l enter "sudo npm install -g node-inspector", it hints :
*\* sudo npm install -g node-inspector
loadRequestedDeps → netwo ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
^Ctank@joseph:~/Desktop/node-v5.1.1$ sudo npm install -g node-inspector
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN lifecycle v8-debug@0.6.1~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.6.1 node -e 'process.exit(0)' /usr/local/lib/node_modules/.staging/v8-debug-d56ef3c156d39eeb44cda4964e0a85c5
npm WARN lifecycle v8-profiler@5.3.2~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.3.2   /usr/local/lib/node_modules/.staging/v8-profiler-700a09d0cc4475efe8f794ecb7f798e3
/usr/local/bin/node-inspector -> /usr/local/lib/node_modules/node-inspector/bin/inspector.js
/usr/local/bin/node-debug -> /usr/local/lib/node_modules/node-inspector/bin/node-debug.js

> bufferutil@1.2.1 install /usr/local/lib/node_modules/node-inspector/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/tank/.node-gyp/5.1.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-inspector/node_modules/bufferutil/.node-gyp"
make: Entering directory `/usr/local/lib/node_modules/node-inspector/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory`/usr/local/lib/node_modules/node-inspector/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /usr/local/lib/node_modules/node-inspector/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/tank/.node-gyp/5.1.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-inspector/node_modules/utf-8-validate/.node-gyp"
make: Entering directory `/usr/local/lib/node_modules/node-inspector/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory`/usr/local/lib/node_modules/node-inspector/node_modules/utf-8-validate/build'

> v8-debug@0.6.1 install /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/tank/.node-gyp/5.1.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/.node-gyp"**
what's it?

**Comment by evanlucas** [comment]
Closing as this is not a website issue

**Comment by ghost** [comment]
@tankdeper please report your issue here: https://github.com/node-inspector/node-inspector/issues/new

**Comment by tankdeper** [comment]
@sup sorry, l will change it.
