### ISSUE TITLE
Footer not working with narrow viewport

### ISSUE THREAD

**Issue by Trott** [nodejs/nodejs.org#4060]
> This is broken on mobile...

@XhmikosR It looks like the footer can be wider than the viewport and (in a sufficiently narrow viewport such as on a mobile device) there's no way to scroll right to see the links on the right hand side of the footer.

Is that what you're talking about? Is there something more as well that I'm missing?

_Originally posted by @Trott in https://github.com/nodejs/nodejs.org/issues/4044#issuecomment-901910394_

**Comment by XhmikosR** [comment]
Yeah, that's the issue. If we had a proper column system we could just use a row with 2 columns which would stack up on mobile only.

I haven't looked at what we have now available to use, but the current way is wrong, for sure.

**Comment by anshul2807** [comment]
I'm new to this community. And I want to handle this issue...can I ??

**Comment by ghost** [comment]
@Trott and @XhmikosR: Since now don't have a column system (something like bootstrap), I have to adjust the width accroding to Google's chorm's Mobile width by using "media"  as a quick fix.

**Comment by ghost** [comment]
@anshul2807: Welcome your suggestion to this issue.

**Comment by pawan43563** [comment]
We can add a single column where in upper side openjs logo than the part which are not visible on smaller viewport and than copyright message that would be nice. I would love to contribute. can i handle this issue?
