### ISSUE TITLE
Default-to-English-when-translation-is-absent gets weird when language is RTL

### ISSUE THREAD

**Issue by Trott** [nodejs/nodejs.org#4063]
* **URL**: https://nodejs.org/ar/docs/guides/blocking-vs-non-blocking/
* **Browser version**: n/a
* **Operating system**: n/a

If you go to (for example) the Arabic URL for a page that hasn't yet been translated to Arabic, the English language version is displayed, which is certainly better than displaying nothing and seems like desirable behavior. However, in RTL languages like Arabic, the English text displays RTL, which is probably not what we want. (Although if someone who is a native speaker of a RTL language tells me that this rendering makes it easier to understand, then that's good enough for me.)

Notice that the text is right justified and that terminating punctuation appears at the start of each sentence rather than at the end.

![image](https://user-images.githubusercontent.com/718899/130389384-cd15843d-c800-40eb-8e67-a11f0d4234f1.png)

**Comment by thomscoder** [comment]
I worked on it on #4336
