### ISSUE TITLE
API documentation search

### ISSUE THREAD

**Issue by WillAvudim** [nodejs/nodejs.org#4064]
Would it be possible to implement search functionality in the API documentation section, https://nodejs.org/dist/latest-v14.x/docs/api/ ?

For example, if I want to quickly find the description for the "?.inspect" method, right now I have to 

1. Google for "site:https://nodejs.org/dist/latest-v14.x/docs/api inspect".
2. Curse that it can't find "a damn thing."
3. Navigate to https://nodejs.org/dist/latest-v14.x/docs/api manually.
4. Scroll the left sidebar haphazardly all the way down, clicking random modules from time to time until I arrive at the util (I deal with multiple APIs: web, .NET, C++, so it sometimes feels frustratingly fuzzy what is it exactly I'm looking for this time).
5. Then proceed through all the methods exported by the util module to find the method I want.

For comparison, MDN has solid search functionality, see the textbox in the right top corner - https://developer.mozilla.org/en-US/docs/Web/Guide#apis

**Comment by Trott** [comment]
@nodejs/nodejs-dev Is this something that has been implemented or is expected to be implemented on nodejs.dev?

**Comment by benhalverson** [comment]
Yes I'm working on an implementation [here]( https://github.com/nodejs/nodejs.dev/pull/1677)
Demo https://staging.nodejs.dev/1677/
It currently only searches /learn content

**Comment by absd1478** [comment]
s

**Comment by mhdawson** [comment]
I'll +1 that I've wished I could search the API documentation more easily. I resorted to cloning from github and then using grep a few times.

**Comment by DerekNonGeneric** [comment]
+1

**Comment by benhalverson** [comment]
I could use some code reviews on my pr. https://github.com/nodejs/nodejs.dev/pull/1677

**Comment by benhalverson** [comment]
Search exists now on https://nodejs.dev. It searches the core docs and the /learn content 🎉

**Comment by lobsterkatie** [comment]
Awesome! Thanks, @benhalverson!

**Comment by WillAvudim** [comment]
It looks and feels great! Thank you for working on this!

**Comment by italojs** [comment]
Amazing work!
but just to know, why not in https://nodejs.org/en/docs/ too instead of only in nodejs.dev?

**Comment by benhalverson** [comment]
It’s the same content on both.

**Comment by ovflowd** [comment]
As @benhalverson is the same content on both, but, we're working into transferring the structure, layout and contents from nodejs.dev into nodejs.org :)

**Comment by ovflowd** [comment]
Closing as this is going to be done soon by the Metadata Docs Proposal + migration of stuff from nodejs.dev to here.
