### ISSUE TITLE
Why not build a Chinese website?

### ISSUE THREAD

**Issue by medns** [nodejs/nodejs.org#407]
I want to build one.
It can provide localized news, conference, etc

**Comment by mikeal** [comment]
the site supports localization, all the markdown content can be localized and you can even add localization specific templates and css (but you don't have to).

@nodejs/nodejs-cn

**Comment by ghost** [comment]
please refer to [the translation document](https://github.com/nodejs/nodejs.org/blob/master/TRANSLATION.md). as @mikeal mentioned, you probably want to join the [chinese working group](https://github.com/nodejs/nodejs-zh-CN). normally you just need to ask nicely, so create an issue in their repo and start translating!
