### ISSUE TITLE
Improve the download page's "Signed SHASUMS for release files (How to verify)" links

### ISSUE THREAD

**Issue by adufourcq** [nodejs/nodejs.org#4111]
On the download page (https://nodejs.org/en/download/), there is two links, grouped together, related to the verification of the binary files: "Signed SHASUMS for release files" and "How to verify"

While the purpose of these two links is related, they are not directly related. The "How to verify" link explains how to verify the checksum of the downloadable files and how to verify the SHASUMS256.txt file's signature, but it never talks about the SHASUMS256.txt.asc file.

My suggestions are the following:
- uncoupled those links
- change the name of the "How to verify" link to something like "How to verify the checksum of the downloaded files with the SHASUMS256.txt file"
- add download links to the SHASUMS256.txt and SHASUMS256.txt.sig files (i know that we can download them with the instructions in the README file or following the "All download options" link, but it would simplify the process)
- Add an explanation (a link to a new section of the README file?) of how to deal with the SHASUMS256.txt.asc file, with a link named something like "How to verify the checksum of the downloaded files with the SHASUMS256.txt.asc file"
- change the "Signed SHASUMS for release files" with an equivalent of the SHASUMS256.txt and SHASUMS256.txt.sig download links

Instructions on how to verify the checksum on Windows would also be great.

I can participate in changes to the website through a pull request if you think these changes (or others) make sense.

**Comment by Pandademic** [comment]
@adufourcq , I agree with you. It looks like one link. 
Maybe put it on a new line like so:
```html
<a href="">Signed SHAsum</a>
<br>
<a href="">How to verify a SHAsum</a>
```
