### ISSUE TITLE
Translation for Indonesia (needs remake)

### ISSUE THREAD

**Issue by ray-1337** [nodejs/nodejs.org#4138]
Hey guys, I have a plan to do translations for `Indonesia` language. I've [seen it](https://github.com/nodejs/nodejs-id) before, but it looks like abandoned.

I appreciate any feedback/reply in here :)

**Comment by nschonni** [comment]
Ping @nodejs/nodejs-id

**Comment by Mednoob** [comment]
I don't think the Indonesian NodeJS team (@nodejs/nodejs-id) is still around. Could NodeJS Crowdin Managers add Indonesian locale to Crowdin so that the community can start translating it instead?

**Comment by ovflowd** [comment]
Closing as all translation efforts are now on Crowdin and discussions should be done there.
