### ISSUE TITLE
redirecting to home page

### ISSUE THREAD

**Issue by fxkamalasawara** [nodejs/nodejs.org#415]
Hello Guys,

I was reading nodejs tutorial on some website where they told that we can find all the modules of nodejs and can search for them on 

https://search.nodejs.org 

but when ever i try to open the link it redirects me to home page i.e https://nodejs.org

**Comment by ghost** [comment]
hey @fxkamalasawara, the tutorial you read might have been outdated. you can find a list of all modules for node.js on https://www.npmjs.com/.

or if you're looking for the modules that are shipped with node, such as `fs`, you can consult the API documentation here: https://nodejs.org/dist/latest-v5.x/docs/api/fs.html (this one is for `fs`)

let me know if anything is unclear!

**Comment by stevemao** [comment]
Should we remove this subdomain then?

**Comment by ghost** [comment]
yup, probably

**Comment by stevemao** [comment]
@fxkamalasawara just out of interest, can you link us the tutorial you were reading? Thanks.

**Comment by fxkamalasawara** [comment]
Hey @sup thanks for the links

**Comment by fxkamalasawara** [comment]
@stevemao 
I was consulting https://nodejs.org/dist/latest-v5.x/docs/api/ docs majorly, but sometimes i read a few things from  http://www.tutorialspoint.com/nodejs/nodejs_npm.htm.

Here in the first paragraph you will find. this 
"Online repositories for node.js packages/modules which are searchable on search.nodejs.org"

Thanks.

**Comment by ghost** [comment]
@fxkamalasawara it looks like the link in the article/tutorial is wrong. the search site is definitely http://npmjs.com

**Comment by ghost** [comment]
i don't really know though. paging @nodejs/npm for help

**Comment by othiym23** [comment]
I'm pretty sure `search.nodejs.org` was never a thing, and I just landed a change in `npm@3.5.3` and `npm@2.14.15` (LTS) that removes references to the long-gone `search,npmjs.org` from npm's docs.

**Comment by Fishrock123** [comment]
> I'm pretty sure `search.nodejs.org` was never a thing

same, I can't recall that ever existing.

**Comment by stevemao** [comment]
Any update on removing the sub domain?

**Comment by fhemberger** [comment]
@stevemao The subdomain doesn't exist, everything `*.nodejs.org` is redirected to `nodejs.org`.
(see [nginx config](https://raw.githubusercontent.com/nodejs/build/master/setup/www/resources/config/nodejs.org).)

Closing this.

**Comment by stevemao** [comment]
:+1:
