### ISSUE TITLE
Font problem in the latest chrome version

### ISSUE THREAD

**Issue by NriotHrreion** [nodejs/nodejs.org#4160]
In the latest chrome version, the font family of texts in `<code>` element is a little bit strange.
I think it necessary to change to another better one.

![image](https://user-images.githubusercontent.com/50199130/136659674-a9cbe6e7-1f14-4029-a083-d422ddc0309a.png)
![image](https://user-images.githubusercontent.com/50199130/136659712-c5502dfd-ed75-454d-85cc-e521f791949d.png)

This is my chrome version:

![image](https://user-images.githubusercontent.com/50199130/136659738-f817fdbd-46db-4824-a726-774339ab1036.png)

**Comment by U-C-S** [comment]
Seems Normal `monospace` font in my Chrome Dev 96.0.4662.6 and Windows 11

![image](https://user-images.githubusercontent.com/50218121/136828811-7f5e098d-1537-47d0-b478-e16d77ea9393.png)
