### ISSUE TITLE
Icons misPositioning and background color doesn't match what we see in doc

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#4166]
1. In the light mode for Node.js org, the background color is still dark. But in the doc, the color seems light-gray more:

【About of Node.js org】
![About](https://user-images.githubusercontent.com/52018749/136678356-34e457f5-548b-44df-933e-ec0869446d76.JPG)

【In the doc】
![Doc](https://user-images.githubusercontent.com/52018749/136678379-e025d6ad-a1a4-4c5b-8616-4cdc23bbfb8b.JPG)

2. When the window is smaller, the language icon and the dark/light switcher will override the menu:

https://user-images.githubusercontent.com/52018749/136678389-7d32af57-f3f3-409c-994a-4a49add56094.mp4

**Comment by Trott** [comment]
Hi, @MaledongGit. What you wrote here about the background color is correct, of course. In addition, I was talking about the highlight colors, which are also different. In the about section, `const` is a different color than in the docs, for example. Same for `require`. And so on.

**Comment by ghost** [comment]
@Trott: That's because in Node.js org, we use something like:

```
```javascript
```
However in Node, we use:

```
```cjs
```

Maybe this will be wholly replaced.

**Comment by ghost** [comment]
There're still some problems needing discussions:

1. The background color is somehow using "cjs", however it seems we CANNOT directly use it in the Node.js org (there'll be an error thrown out because prismjs doesn't support it for now). I don't know where to find "prism-cjs.js"?

2. When the browser's window width's getting smaller and smaller but the nav menu doesn't change to a new line, how to cope with it? Put it directly under the menu or ……?

![image](https://user-images.githubusercontent.com/52018749/136686666-df51ec4d-ce03-43ab-a027-ea6064bf34d3.png)

**Comment by NriotHrreion** [comment]
> There're still some problems needing discussions:
> 
> 1. The background color is somehow using "cjs", however it seems we CANNOT directly use it in the Node.js org (there'll be an error thrown out because prismjs doesn't support it for now). I don't know where to find "prism-cjs.js"?
> 2. When the browser's window width's getting smaller and smaller but the nav menu doesn't change to a new line, how to cope with it? Put it directly under the menu or ……?
> 
> ![image](https://user-images.githubusercontent.com/52018749/136686666-df51ec4d-ce03-43ab-a027-ea6064bf34d3.png)

This is what I think:

![image](https://user-images.githubusercontent.com/50199130/136809718-94556b16-f01e-460c-9cc0-e599e529ac40.png)

I just did some simple modifies in devtools. And I didn't modify the source code.

**Comment by gumbol** [comment]
> There're still some problems needing discussions:
> 
>     1. The background color is somehow using "cjs", however it seems we CANNOT directly use it in the Node.js org (there'll be an error thrown out because prismjs doesn't support it for now). I don't know where to find "prism-cjs.js"?
> 
>     2. When the browser's window width's getting smaller and smaller but the nav menu doesn't change to a new line, how to cope with it? Put it directly under the menu or ……?
> 
> 
> ![image](https://user-images.githubusercontent.com/52018749/136686666-df51ec4d-ce03-43ab-a027-ea6064bf34d3.png)

since its not part of the main menu i think its better to have it above the menu. left or right corner.

**Comment by thomscoder** [comment]
Hello, I worked on the icons misPositioning issue -> #4350  
Hope it fixes the problem

**Comment by thomscoder** [comment]
Both issues seem to have been successfully merged!
