### ISSUE TITLE
Flash of Incorrect Theme when Dark Theme is chosen

### ISSUE THREAD

**Issue by U-C-S** [nodejs/nodejs.org#4167]
When reloading a page or Navigating across the site with Dark Theme on, There's a slight Flash of Light Theme. 

Probably, due to HTML and CSS being loaded first and later, JavaScript code that changes the theme. To Fix it, Might want to make sure the JS code is loaded before CSS.

**Comment by U-C-S** [comment]
It can already be observed in this GIF from the Dark Mode PR: https://github.com/nodejs/nodejs.org/pull/4139#pullrequestreview-769533552

**Comment by NriotHrreion** [comment]
I've fixed this problem and committed.

**Comment by NriotHrreion** [comment]
> I've fixed this problem and committed.

@U-C-S: The PR has been merged.
