### ISSUE TITLE
Release Schedule table is very unpleasant and hard to read

### ISSUE THREAD

**Issue by akamfoad** [nodejs/nodejs.org#4180]
* **URL**: https://nodejs.org/en/about/releases/
* **Browser version**: Firefox 93
* **Operating system**: Ubuntu 20.04

Hi, I visited the Node.js website and found out some redesigns have taken place and the dark mode is much better, though when I visited [Release Schedule](https://nodejs.org/en/about/releases/) page I saw that the table is very unpleasant and hard to read the content, looks like it uses some white color depending odd/even rules, which is a great thing to do to improve table readability, but the colors are not fit to be together, I think we can do better in terms of colors and make it better, here is a screenshot of the table:

![image](https://user-images.githubusercontent.com/41629832/137478596-63ecdc1a-2a68-44da-9335-7c05a632db3a.png)

> PS: I will be more than happy to help fix this issue, please let me know if you have any preference regarding the table design or appearance as there is a `redesign` taking place, otherwise I can work on it on my own.

**Comment by gumbol** [comment]
would you elaborate on why that is the case?
From a document design ive seen several word processing software that include similar color combos for tables.

**Comment by akamfoad** [comment]
@gumbol 

Sure,there is many ways to pick colours to create a UI in combination of them, and when those colours are an extreme/fair opposite of each other, they are very good to make Text and Icons visible and etc.
But using these colours as Background for sections near each other, makes the visual shift extreme, and it's unpleasant for users to read, especially in dark mode, these cases sometimes made for colour schemes like **High Contrast** but obviously it isn't the case with this website in both dark/light mode. This table's row colours is a good example of that.
So it's a good idea to pick colours for different rows that looks like smooth change in the visual appearance, so for example having different shades of same colour could be a better choice like having _black_ and _darkblue_ and so forth. You may get a better picture looking at this colour palettes for example:
https://colorhunt.co/

**Comment by Trott** [comment]
For comparison, here is the less jarring light mode  rendering:

![image](https://user-images.githubusercontent.com/718899/137951867-78d34ffe-3a49-4257-b928-5186b44c1d02.png)

**Comment by Trott** [comment]
We need to update the colors of the tables in dark mode regardless of aesthetics etc. because the color contrast between the green text and the white background fails accessibility standard WCAG AA.

**Comment by akamfoad** [comment]
I was experimenting with some colours and styles when I opened the issue. I came up with this changes you may find useful

**Dark Mode**:

![image](https://user-images.githubusercontent.com/41629832/137972314-7e42e5c3-a7d1-4314-8f51-ef571fa64984.png)


---

**Light Mode**:
 
![image](https://user-images.githubusercontent.com/41629832/137972362-6064d549-74b3-47a6-9868-a83c013e4e97.png)

**Comment by Trott** [comment]
> I was experimenting with some colours and styles when I opened the issue. I came up with this changes you may find useful

@akamfoad Is this a change you can submit as a PR? Or was this something you messed around with in development tools but not in the actual CSS files? A PR would be great, if it's not a lot of trouble.

**Comment by akamfoad** [comment]
@Trott 
Actually those screenshots where from the website that I did some changes to, locally.

Sure will open a PR for it soon.
