### ISSUE TITLE
"Previous Release" page shows number of modules as hex value

### ISSUE THREAD

**Issue by charleswhchan** [nodejs/nodejs.org#419]
See: https://nodejs.org/en/download/releases/

Was looking to download an older node version v0.10.x and noticed the modules column sometime uses hex values (0x000A, 0x000B, 0x00C); while most of the time the number is an integer. It minor, but strange.

Looking at the code, I think the hex values comes from versions.son (https://github.com/nodejs/nodejs.org/blob/965d4cab3256bc3cb6ba435758695b415643f2c8/source/versions.json). I would be happy to update if this is in fact an error. :smiley:

**Comment by rvagg** [comment]
that number is an internal C++ variable called `NODE_MODULE_VERSION` which is used when loading native add-ons, it checks that the compiled number matches the internal number before accepting them. It used to be stored as hex and now it's just an integer. The numbers there are correct.

However, this issue raises the point that the interpretation of the column name is "number of modules" as it is now, perhaps we should change it to `NODE_MODULE_VERSION` to avoid this. There was a discussion on this earlier on, I can't recall the issue, however.

**Comment by charleswhchan** [comment]
@rvagg: Thanks for the clarificiation.

As the column is currently named "Modules", it definitely creates confusion for someone new to node. I agree we should rename it to something more appropriate. :+1:

**Comment by fhemberger** [comment]
Closing this for now, the PR should fix that.

**Comment by charleswhchan** [comment]
Thanks @fhemberger :+1:
