### ISSUE TITLE
When viewing the release page in dark mode, the text is unreadable.

### ISSUE THREAD

**Issue by mochi-sann** [nodejs/nodejs.org#4210]
<img width="1195" alt="screenshot 2021-10-27 14 51 12" src="https://user-images.githubusercontent.com/44772513/139007742-eee04622-b26c-494e-b9c1-9609f7ebac99.png">

When I open https://nodejs.org/en/download/releases/ and look at it in dark mode, I can't read the version name and other information in white, as shown in the image.

* **URL**: https://nodejs.org/en/download/releases/
* **Browser version**:  Google Chrome | 95.0.4638.54 (Official Build) （x86_64）
* **Operating system**: Mac OS

**Comment by DerekNonGeneric** [comment]
I can confirm that it is indeed an unintentional bug and an accessibility concern at that. It was introduced in https://github.com/nodejs/nodejs.org/pull/4200, which was merged only a few hours ago. Unless someone beats me to it, I think this should be pretty simple to handle and should have a patch for the fix shortly.

Thanks for the report!
