### ISSUE TITLE
Node 14 download is not working

### ISSUE THREAD

**Issue by Spomsoree** [nodejs/nodejs.org#4227]
Node 14 cannot be downloaded from the following URL:

* https://nodejs.org/dist/v14.18.1/node-v14.18.1-darwin-arm64.tar.xz

nvm is trying to download node from this url, could be an issue on their side, but it worked a few days ago for me.

Edit: I've notices that nvm builds node itself if the download is not working, so I'm unsure if it worked a few days ago.

**Comment by kanongil** [comment]
I don't think there has ever been `darwin-arm64` download links for the v14 releases. Given that V8 v8.4 requires backported patches to support for that architecture, I think it makes sense to not do any official builds.

**Comment by Spomsoree** [comment]
I see.

The nvm command did build it successfully now, so I guess this is not an issue.
