### ISSUE TITLE
The <input> inside the releases table overflowed.

### ISSUE THREAD

**Issue by 18202409203** [nodejs/nodejs.org#4235]
* **URL**: https://nodejs.org/en/download/releases/
* **Browser version**: Chrome / Firefox
* **Operating system**: Ubuntu 16

The `<input>` inside the table overflowed.

![chrome](https://user-images.githubusercontent.com/30512639/140892218-afdfdb8b-37dd-49af-a268-323d4b3bbe9b.png)

I think it should be `box-sizing: border-box;`

**Comment by tymnim** [comment]
The issue seems to be in `static/js/fancyTable.min.js`. I am not sure if there's a non-minified file of this.

if `("<input>",{placeholder:r.inputPlaceholder,style:"width:100%;"+r.inputStyle})` replaced by `("<input>",{placeholder:r.inputPlaceholder,style:"width:100%;box-sizing:border-box;"+r.inputStyle})`, it should work. I hope someone can apply this change.

**Comment by thomscoder** [comment]
I have worked on it and pull requested. Hope it fixes the issue

**Comment by Trott** [comment]
> The issue seems to be in `static/js/fancyTable.min.js`. I am not sure if there's a non-minified file of this.

It looks like that file was added by @MaledongGit in 6eba6d1b912ca902aa70b02f51bf6cd2abc7fdce without any approval by other contributors. Hopefully they can indicate where the unminified code can be found, etc.

**Comment by Trott** [comment]
> It looks like that file was added by @MaledongGit in [6eba6d1](https://github.com/nodejs/nodejs.org/commit/6eba6d1b912ca902aa70b02f51bf6cd2abc7fdce) without any approval by other contributors. Hopefully they can indicate where the unminified code can be found, etc.

(The search feature is a nice improvement, I think, so I'm surprised someone didn't 👍  that PR at some point!)

**Comment by Trott** [comment]
> It looks like that file was added by @MaledongGit in [6eba6d1](https://github.com/nodejs/nodejs.org/commit/6eba6d1b912ca902aa70b02f51bf6cd2abc7fdce) without any approval by other contributors. Hopefully they can indicate where the unminified code can be found, etc.

Looks like the unminified source would be in https://github.com/myspace-nu/jquery.fancyTable.

**Comment by thomscoder** [comment]
I have worked on this. This issue is currently in PR

**Comment by nschonni** [comment]
Looks like the latest fancy tables version has fixed it 
![image](https://user-images.githubusercontent.com/1297909/141872063-a9772397-94cf-4878-8b07-be93a5451772.png)
