### ISSUE TITLE
Missing 64-bit MSI installer for 17.1.0

### ISSUE THREAD

**Issue by nzdudeinsydney** [nodejs/nodejs.org#4240]
Link to 64-bit MSI on https://nodejs.org/en/download/current/ page results in:

404: Page could not be found
ENOENT: no such file or directory

**Comment by nschonni** [comment]
https://nodejs.org/dist/v17.1.0/node-v17.1.0-x64.msi works right now, so might have just been a timing issue while the CDN populated

**Comment by nzdudeinsydney** [comment]
Aaah.. still not yet working for me (Australia).  Went down other download options and got the same.  I'll just wait, unless there's an option somewhere to select a different mirror.

**Comment by nzdudeinsydney** [comment]
Works for me today.  Thanks!
