### ISSUE TITLE
Dark theme OpenJS Foundation

### ISSUE THREAD

**Issue by thomscoder** [nodejs/nodejs.org#4244]
When clicking from dark theme nodejs.org on the certifcation section, the openjsf page opens up it's kinda uncomfortable for it to be bright.
I think it would be good to have a sort of theme synchronization between the https://nodejs.org and the https://openjsf.org websites

<img width="1091" alt="Immagine 2021-11-11 123405" src="https://user-images.githubusercontent.com/78874117/141291323-508d3718-d736-44d7-813e-6f36cd0ca8d4.png">

<img width="1135" alt="Immagine 2021-11-11 123338" src="https://user-images.githubusercontent.com/78874117/141291335-5a2519ab-ec00-4d9b-a9aa-0f09d1a3d769.png">

**Comment by nschonni** [comment]
That is a totally different org. You might be able to find the project in https://github.com/openjs-foundation, but nothing the people that maintain this repo can do
