### ISSUE TITLE
Bring back the #BlackLivesMatter on Nodejs.org

### ISSUE THREAD

**Issue by LocalCodes** [nodejs/nodejs.org#4263]
I request that the #BlackLivesMatter header be added back.

**Comment by benjamingr** [comment]
Hey @LocalCodes ,

Thanks for opening this issue!

I am responding as a project member and moderator - not as "the project". Please take everything I say with the appropriate amount of salt :)

Note the BLM page is still available at https://nodejs.org/en/black-lives-matter/ 

For BLM related requests - please contact blacklivesmatter@nodejs.org where parties involved in initiatives relating to BLM can easily be reached (I don't suspect they monitor the website repo regularly).

In addition, if you would like to volunteer (e.g. mentoring developers in areas most affected by systematic racism) or have suggestions for people we can help get involved in the project to improve representation/involvements please reach out to blacklivesmatter@nodejs.org .

I am happy to see others who care about making a positive change interested in helping. Please also feel free to reach out to me personally at benjamingr@gmail.com .

There is a lot of areas to help in and most are waiting for people to pick them up.

(I personally support BLM but not the banner - though my personal thoughts on how to help aren't the issue there)

**Comment by benjamingr** [comment]
I am going to go ahead (as a moderator) and (cautiously) close and lock this issue to avoid the sort of (typically not great) discussion this sort of issue.

Please reach out to the people involved (specifically with BLM at blacklivesmatter@nodejs.org, moderation is at report@nodejs.org and me personally at benjamingr@gmail.com) so we can figure out how to help.

(Of course - if another moderator or TSC member feels differently feel free to reopen/comment/direct discussion elsewhere).
