### ISSUE TITLE
against es6 in documentation

### ISSUE THREAD

**Issue by forgotPassword** [nodejs/nodejs.org#431]
i don't know if it was decided/voted or not, but i am against es6 features in documentation or code examples.
the docs and examples should be as simple as possible, and now even the classic createServer example ('about' page) has const, arrow functions, and template strings.

before you could just say 'copy this example, see how easy it is to create a server in node?', now you also have to explain what all those special signs and characters are.

**Comment by stevemao** [comment]
I believe these examples are in the docs of nodejs that support them. If you switch to an older version they shouldn't be there.

**Comment by ghost** [comment]
thing is, the latest releases all support most ES6 features out of the box. even the LTS does that, so it's officially encouraged.
but what we might be able to do is add a link to an ES6 introduction under the code example on the about page in case someone is confused

but what @stevemao says does apply, the pre-4.x docs are still in ES5

**Comment by wonderdogone** [comment]
I think it's good to push ES6 unless it's a feature set that is outside of Node internally. For example some ES6 that needs to be transpiled by external tool like babel should not be in docs because then you have to explain that workflow.

**Comment by stevemao** [comment]
> but what we might be able to do is add a link to an ES6 introduction under the code example on the about page in case someone is confused

I don't think this is necessary. We already have docs about features in es2015. If we add a link to all the pages that have es2015 code it would be too noisy. Not to mention that there are many people already using es2015 and a there are a lot of material about es2015 online.

Closing this now. @forgotPassword if you find anything that does not work against the corresponding node version out of the box please fire a bug :) thanks.

**Comment by rvagg** [comment]
Thanks for the link @stevemao, I knew there was an issue in here about this recently that I couldn't find. 

Folks in here, please see #467 for _possible_ way forward. Only discussion at this stage.
