### ISSUE TITLE
Translation for Telugu

### ISSUE THREAD

**Issue by Naidu-Saikiran** [nodejs/nodejs.org#4329]
Hey guys, please add **telugu** translation to the documentation so that learning  from nodejs documentation is easy for **telugu** developers who are not able to understand proper english

**Comment by Naidu-Saikiran** [comment]
please add ### telugu locale so that interested developers will start documenting in Telugu. Even I am interested to translate to Telugu

**Comment by AugustinMauroy** [comment]
If you don't know it yet but the doc doesn't have a translation system.
But there is a discussion for that which is open. If you are interested you can vote for 
https://github.com/nodejs/node/discussions/43513

**Comment by ovflowd** [comment]
Hey @Saikirannaidu225 give a read here: https://github.com/nodejs/nodejs.org/issues/4003#issuecomment-1219596920

**Comment by ovflowd** [comment]
Closing as all translation efforts are now on Crowdin and discussions should be done there.
