### ISSUE TITLE
The First issues

### ISSUE THREAD

**Issue by grateyinger** [nodejs/nodejs.org#438]
i will learn Node.Js forever
please supervise me
come on
site:https://nqdeng.github.io/7-days-nodejs/#1.4.1
site:https://nodejs.org/en/

**Comment by jasnell** [comment]
@grateyinger ... for those just getting started with Node.js, the best place to start is with resources such as http://nodeschool.io or http://stackoverflow.com. General questions about Node.js can also be directed at the http://github.com/nodejs/help repository issue tracker. This particular repository is used to track technical issues and development of Node itself and is not the right place to post questions about getting started.

**Comment by bobborn** [comment]
I teach you.
