### ISSUE TITLE
doc command for Fedora installation with different version seem to be wrong

### ISSUE THREAD

**Issue by option-greek** [nodejs/nodejs.org#4392]
- **URL**: https://nodejs.org/en/download/package-manager/#centos-fedora-and-red-hat-enterprise-linux
- **Browser version**: Firefox
- **Operating system**: Fedora

To install nodejs version 12 on fedora, the page says to run:

`dnf module install nodejs:12`

If I try the same with versions 14 or 16, dnf  throws an error saying:

`No default profiles for module nodejs:14. Available profiles: default, development, minimal`

The correct command that worked as referenced on this website (https://linuxconfig.org/how-to-install-node-js-on-redhat-8-linux)  is:

`dnf module install nodejs:16/default`

**Comment by richardlau** [comment]
There’s an open PR, https://github.com/nodejs/nodejs.org/pull/4279, although there appears to be an inconsistency on Fedora when compared to CentOS/RHEL.

**Comment by option-greek** [comment]
I guess its because some one stopped marking the default profiles for  fedora starting with release 14 of NodeJS. I'm not sure that particular lack of default profile marking is on NodeJS side or Fedora side and where to correct it. 

But as it stands, installing NodeJS > 12 is broken on Fedora currently with the default instructions provided on nodejs.org. May be this can be left as a note  on the website to prevent needless googling ? (it works from 12-16 so there is no loss of function when explicitely specifying the profile name). 

Since the behavior is different in CentOS/RHEL and looks like CentOS is dead/dying (with stream being the replacement), splitting Fedora's documentation in nodejs.org website will be nice.

**Comment by kasicka** [comment]
@option-greek Thanks for bringing this up, we'll try to fix this in Fedora and then I'll review the current documentation.

**Comment by kasicka** [comment]
Update: defaults were fixed/changed to `common`, I'll get back to this issue when the changes show up in repos for F34 and F35.

**Comment by mhdawson** [comment]
Looks like some of the updates are in F35

```shell 
[root@2d21e2dd9e4a /]# dnf module list nodejs
Fedora 35 - x86_64                                                                                              16 MB/s |  79 MB     00:05    
Fedora 35 openh264 (From Cisco) - x86_64                                                                       3.4 kB/s | 2.5 kB     00:00    
Fedora Modular 35 - x86_64                                                                                     3.6 MB/s | 3.3 MB     00:00    
Fedora 35 - x86_64 - Updates                                                                                   9.8 MB/s |  28 MB     00:02    
Fedora Modular 35 - x86_64 - Updates                                                                           3.7 MB/s | 2.8 MB     00:00    
Fedora Modular 35 - x86_64
Name                       Stream                     Profiles                                            Summary                              
nodejs                     12                         default, development, minimal                       Javascript runtime                   
nodejs                     14                         default, development, minimal                       Javascript runtime                   
nodejs                     15                         default, development, minimal                       Javascript runtime                   
nodejs                     16                         default, development, minimal                       Javascript runtime                   

Fedora Modular 35 - x86_64 - Updates
Name                       Stream                     Profiles                                            Summary                              
nodejs                     12                         default, development, minimal                       Javascript runtime                   
nodejs                     14                         common [d], development, minimal                    Javascript runtime                   
nodejs                     15                         default, development, minimal                       Javascript runtime                   
nodejs                     16                         common [d], development, minimal                    Javascript runtime                   

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled
```

**Comment by mhdawson** [comment]
This has been fixed for 14 and 16 and 12 goes EOL next month so I think we can close this issue.

@option-greek is that ok with you?

**Comment by option-greek** [comment]
Sure @mhdawson! 
Thanks everyone for fixing the underlying issue.

**Comment by mhdawson** [comment]
@option-greek thanks for confirming, closing.
