### ISSUE TITLE
Better Get Involved page

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#443]
The current page isn't too great.

Could use more calls to action and should link to various contribution policies for parts of the project that have a lower barrier to entry like the website.

**Comment by Knighton910** [comment]
:+1:

**Comment by fbaiodias** [comment]
I also feel like the [learning section](https://nodejs.org/en/get-involved/#learning) should be more proeminent on the website. 
If a new comer visits [nodejs.org](https://nodejs.org) there's no "Get started" at first sight, so maybe we could add a link to the menu bar or event a section to the home page?

**Comment by mikeal** [comment]
We should call out the `help` repo as the default place to ask any question if you can't figure out where or how you should participate.

**Comment by Knighton910** [comment]
seconded  `help repo`

**Comment by kahwee** [comment]
Django folks have a good start page that we can take cues from -- https://www.djangoproject.com/start/

**Comment by Coder206** [comment]
Maybe something like this: http://whatcanidoformozilla.org/

**Comment by Trott** [comment]
@nodejs/website-redesign Any chance this content got a significant overhaul in the redesign? If so, any chance we can port it to the current site?

**Comment by ovflowd** [comment]
Closing as the pages from nodejs.org are going to be replaced by the ones of nodejs.dev. If after the migration issues are still found, please feel free to reopen this issue.
