### ISSUE TITLE
Profiling Guide Requires Updates

### ISSUE THREAD

**Issue by Trott** [nodejs/nodejs.org#447]
In light of https://github.com/nodejs/node/pull/3032, there is some stuff in the [simple profiling guide](https://github.com/nodejs/nodejs.org/blob/030e1dd985654c1daa3d619d68b1b637116c7fb0/locale/en/docs/guides/simple-profiling.md) that can be simplified. Maybe @matthewloring can indicate what needs to change? It might just be the part about making sure to use the same version of tick-processor as came with the source and how to fire up the tick processor? Not sure anything else...

**Comment by matthewloring** [comment]
@Trott Thank you for noticing this. I'll submit a PR with updates now that the tick processor is bundled with the node binary.

**Comment by srlowe** [comment]
The page is still referring to the v8 profiling tools in the source code (which I believe are no longer included).

**Comment by matthewloring** [comment]
Good catch. Actually, the integration of the `--prof-process` flag into the LTS branch means we should remove all mention of scripts from the guide.
