### ISSUE TITLE
Font change?

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#45]
I noticed the font has changed from the old nodejs.org. Was this intentional or just an oversight?

**Comment by fhemberger** [comment]
Nope, the TypeKit snippet is not added yet. Unless you have Source Sans installed on your machine, you will see Arial as fallback font.

**Comment by mikeal** [comment]
I see, adding the Google Font for this instead, it loads a lot more liberally than typekit.

**Comment by mikeal** [comment]
fixed.
