### ISSUE TITLE
Fix filter

### ISSUE THREAD

**Issue by yjy4321** [nodejs/nodejs.org#4524]
Filter for this table is not working on Chrome, Firefox, and Edge.
https://nodejs.org/en/download/releases/
![Annotation 2022-04-04 093707](https://user-images.githubusercontent.com/47332567/161590881-87919011-0c87-4576-90c6-4ecfbe9f00ee.jpg)

**Comment by Trott** [comment]
Fixed by https://github.com/nodejs/nodejs.org/pull/4529
