### ISSUE TITLE
Add Student Discount Code to Individual Membership

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs.org#454]
I noticed that we do not have the student discount code on our individual membership page or the individual membership blog. The code is NodeStudentN10HM. Could someone add it in when they have a moment? We'll be promoting this a lot on social, so want to make sure it's easy to find.

**Comment by rnsloan** [comment]
@ZibbyKeaton is this satisfactory: https://github.com/nodejs/nodejs.org/pull/462 ?

**Comment by ZibbyKeaton** [comment]
@rnsloan 👌
