### ISSUE TITLE
The Node.js website does not display Chinese in simplified Chinese mode（主页中文简体，不显示中文）

### ISSUE THREAD

**Issue by master-genius** [nodejs/nodejs.org#4552]
@nodejs/node-cn

当我访问 https://nodejs.org/zh-cn ，主页不显示中文，而是英文主页。

**Comment by nschonni** [comment]
![image](https://user-images.githubusercontent.com/1297909/163903998-660f4e50-2adb-4931-866d-1c6d46a05df0.png)
Appears to be translated OK. I think there are probably spots that still need translation, but going to close this
