### ISSUE TITLE
Icons are slightly off-color

### ISSUE THREAD

**Issue by silverwind** [nodejs/nodejs.org#458]
[favicon.ico](https://nodejs.org/static/favicon.ico) uses `#7ebf42` while the link color on the site `#80bd01`. They are supposed to match, right?

**Comment by iancrowther** [comment]
Good eye

**Comment by phillipj** [comment]
> They are supposed to match, right?

It would surprise me if it was made so deliberately. Good catch :+1:

**Comment by stevemao** [comment]
There might be other inconsistent colours. #367

**Comment by silverwind** [comment]
This should only affect `apple-touch-icon.png` and `favicon.ico` from the looks of it, a simple hue-rotate could suffice. I'm not really adept in Photoshop, so if someone could take over this, I'd be grateful :)

**Comment by fhemberger** [comment]
BTW: Is there an exact definition of the node.js green? Some sort of brand guideline? When I started the new website, I used the tone from the SVG version of the logo. Icons were taken from the original website as well.

So if it hasn't been done already, it would be good to define the "official" colors somewhere, also as reference for future design updates, prints, stickers, etc.

/cc @mikeal

**Comment by stevemao** [comment]
Hi @fhemberger , it'll depend on https://github.com/nodejs/evangelism/issues/179

**Comment by fhemberger** [comment]
@stevemao I'm talking about the current status, not future iterations (as there also is no time table defined yet). We could need a clear definition now, as other node-related projects, conferences, etc. may use the color scheme as well.

**Comment by bentinata** [comment]
Like [Ubuntu's Design Guideline](http://design.ubuntu.com/brand/colour-palette)? (I'm not affiliated with Canonical or others. It's because their color guides are nice.)

We can do like:  
- `#83cd29` ![](http://placehold.it/10/83cd29/83cd29) Main Green  
- `#404137` ![](http://placehold.it/10/404137/404137) Gray  
- `#309045` ![](http://placehold.it/10/309045/309045) Foundation Green (optional)
- Could add JS yellow, or Foundation blue.

I'm not sure about Joyent related things. Until this day I'm still sticking to [official guide](https://nodejs.org/static/documents/foundation-visual-guidelines.pdf). It says we must not change the color.

**Comment by fhemberger** [comment]
@bentinata Yes, exactly. This looks really great.

Regarding Joyent's "visual guidelines": I don't think a low res, low quality JPG embedded in a Word file, converted to PDF can seriously be used as any sort of color guideline. It would help to get the exact info from Joyent (or the designer of the logo) themselves.

**Comment by silverwind** [comment]
Here's a screenshot from that design guide:

![design-guide](https://cloud.githubusercontent.com/assets/115237/12280915/fc262134-b991-11e5-842f-d5f8dfe53eb3.png)

Looks like it's something approximately to `#8cc84c` on `o` there, but JPG compression messed with heavily with that color, and the `js` part is a whole different shade. Not really a source we can work with.

**Comment by Fishrock123** [comment]
@mikeal Are you able to dig up a PDF or psd guidelines document, if one exists? (Or even point us to who to ask?)

**Comment by silverwind** [comment]
Accessibility (#501) dictates that we use a darker green on he links and buttons if we are to keep the white background. With a dark background there would of course be no concern, and we could make those colors match.
