### ISSUE TITLE
Release page

### ISSUE THREAD

**Issue by MuratovBektur** [nodejs/nodejs.org#4603]
- **URL**: https://nodejs.org/en/about/releases/
- **Browser version**: Chrome 101
- **Operating system**: Android 

Plz update release picture

**Comment by Trott** [comment]
That image is loaded from https://github.com/nodejs/Release/blob/main/schedule.svg. @nodejs/release Is there a documented procedure for updating the image? I imagine we'd ideally like to remove 12.x from the image and show the end date for 18.x maintenance.

**Comment by BethGriggs** [comment]
We have [some guidances/commands](https://github.com/nodejs/Release/blob/main/doc/release-guide.md#updating-the-schedulesvg). It can be a bit fiddly to make it render nicely.

**Comment by targos** [comment]
https://github.com/nodejs/Release/pull/748
