### ISSUE TITLE
Table on Releases page out of viewport on iOS

### ISSUE THREAD

**Issue by hughrawlinson** [nodejs/nodejs.org#4628]
- **URL**: https://nodejs.org/en/about/releases/
- **Browser version**: Firefox Daylight 100.1
- **Operating system**: iPhone 12, iOS 15.5

I went to check the end of maintenance dates on the releases page of the site while on my phone, and realized that I couldn't because of the table. The screenshot below shows the issue. It's not possible to scroll right to view the maintenance end date column because of the viewport.

I think this could be solved by wrapping the table in an element with overflow-x true.

![image](https://user-images.githubusercontent.com/829836/171342146-18ad0856-941d-44e4-aa43-c97284bbc375.png)

**Comment by StephNathai** [comment]
Hi @hughrawlinson, will you be working on this? Would love to take a stab at it if not.

**Comment by hughrawlinson** [comment]
@StephNathai feel free! 🙂

**Comment by hughrawlinson** [comment]
Thank you @StephNathai!! 😄
