### ISSUE TITLE
Update the year on the footer

### ISSUE THREAD

**Issue by arturoromeroslc** [nodejs/nodejs.org#464]
This one is a simple update to te website's footer. 

The edit will be changing ©2015 to ©2016.

**Comment by Knighton910** [comment]
You didn't want to do a pull request & go about it that way? If not I'll handle it.

**Comment by arturoromeroslc** [comment]
I will work on the pull request now, thanks.

**Comment by Knighton910** [comment]
No worries :)

**Comment by Knighton910** [comment]
:+1: @stevemao

**Comment by arturoromeroslc** [comment]
Pull request is open.  https://github.com/nodejs/nodejs.org/pull/465

**Comment by arturoromeroslc** [comment]
Pull request merged. Thank you @kelthenoble

**Comment by Knighton910** [comment]
Anytime man :100:
