### ISSUE TITLE
Problem on the access to the category "knowledge" more easily.

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/nodejs.org#4665]
# Problem on the access to the category "knowledge" more easily.
At the moment, it is impossible to access the "knowledge" category from the nodejs.org site.
But it is accessible by typing "nodejs knowledge" in a search engine.

I think it is not complicated to add. But you have to find the right place.

**Comment by Trott** [comment]
The knowledge base is very problematic. The usual cause is that much of it has not received substantial updates in 7+ years. 

Looking at the first few articles in the knowledge base, none of them should be recommended.

"How can I secure my code?" is astonishingly incomplete. People should be referred to more comprehensive guides on Node.js security instead.

"How to access query string parameters" tells people to use `url.parse()` and does not even mention the WHATWG standard `URL` API.

And so on. We have started replacing these articles with pointers to canonical resources. See, for an example, https://nodejs.org/en/knowledge/javascript-conventions/what-is-json/.  We should continue doing so in my opinion. Not linking to them is (IMO) a feature and not a bug.
