### ISSUE TITLE
Unable to access workflow page

### ISSUE THREAD

**Issue by sumitsharma0999** [nodejs/nodejs.org#468]
URL: http://nodejs.org/documentation/workflow/

![image](https://cloud.githubusercontent.com/assets/1701967/12324710/9da4ab08-baea-11e5-801b-75a9211e338c.png)

**Comment by ghost** [comment]
for me, it redirects to https://nodejs.org/en/docs/. paging @phillipj, do you know where this is supposed to lead?

**Comment by stevemao** [comment]
It redirects for me too.

**Comment by ghost** [comment]
@sumitsharma0999 from where did you get to that URL?

**Comment by phillipj** [comment]
> for me, it redirects to https://nodejs.org/en/docs/

Yupp, that's deliberate by the following [nginx rules](https://github.com/nodejs/build/blob/master/setup/www/resources/config/nodejs.org).

The workflow URL in question is mentioned in TJ's next-chapter blog post: https://nodejs.org/en/blog/community/next-chapter/ which is available in the old nodejs.org-archived repo: https://github.com/nodejs/nodejs.org-archive/blob/master/doc/contribute/code_contributions/workflow.md

As good as that workflow documentation is, it doesn't apply anymore AFAIK. Today's equivalent would probably be https://github.com/nodejs/node/blob/master/CONTRIBUTING.md

**Comment by sumitsharma0999** [comment]
For me also, it redirects now to https://nodejs.org/en/docs/ - this looks like a temporary issue.

Regarding the source of URL, I was browisng through https://nodejs.org and I am unable to the recall where exactly the link was. But I am pretty sure it was either on the home page or atmost 1 level down. I tried to find the link now, but was unable to find it.

**Comment by rnsloan** [comment]
Should the nginx redirect be changed to the document that has superseded the old workflow document https://github.com/nodejs/dev-policy

**Comment by phillipj** [comment]
> Should the nginx redirect be changed to the document that has superseded the old workflow document https://github.com/nodejs/dev-policy

Maybe... I was hesitant to reference it since it hasn't been updated in 8 months and it still says draft in the repo title. Any thoughts from @nodejs/documentation?

**Comment by fhemberger** [comment]
@phillipj New Development Policy can be found here: https://nodejs.org/en/get-involved/development/

**Comment by phillipj** [comment]
@fhemberger great! Does that mean we should ignore [nodejs/dev-policy](https://github.com/nodejs/dev-policy) for now, and change URLs of the three "Node.js Development Policy" links [on the contribute page](https://nodejs.org/en/get-involved/contribute/)?

**Comment by jasnell** [comment]
https://github.com/nodejs/dev-policy should likely be folded in to https://github.com/nodejs/node somehow and used as the official source for what gets published to https://nodejs.org/en/get-involved/development/. /cc @nodejs/ctc

**Comment by Fishrock123** [comment]
Agreed, it's just a bunch of work no-one has done yet.

**Comment by fhemberger** [comment]
https://github.com/nodejs/dev-policy is completely outdated, not sure if it still makes sense to merge it into the main repo. For changes to https://nodejs.org/en/get-involved/development/, please open a new PR.

Closing this, as the original issue has been solved.
