### ISSUE TITLE
Changelog links point to the old branch (master) instead of main, causing a redirect and blue banner

### ISSUE THREAD

**Issue by Schweinepriester** [nodejs/nodejs.org#4688]
- **URL**: https://nodejs.org/
- **Browser version**: Any
- **Operating system**: Any

![image](https://user-images.githubusercontent.com/2644614/176305535-d50736bf-01c5-46bf-a592-c817fb316ef0.png)

Both those links

- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#16.15.1
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V18.md#18.4.0

then require a redirect and trigger the distracting blue banner, for example:

![image](https://user-images.githubusercontent.com/2644614/176305777-827a5fe7-f7ce-4333-9074-103eeef4026c.png)

Looking at https://github.com/nodejs/nodejs.org/blob/main/layouts/index.hbs the props seem to be

- `{{changeloglink project.latestVersions.lts.node}}`
- `{{changeloglink project.latestVersions.current.node}}`

but I haven't found their source, otherwise I probably would have sent a PR 0:-)

**Comment by nschonni** [comment]
Probably coming from https://github.com/nodejs/nodejs.org/blob/c1703267c30d2bfc19da5708afcb7169ef1a31c6/scripts/helpers/changeloglink.js#L9

**Comment by nschonni** [comment]
I didn't realize that they had changed the default branch, so it's probably worth doing a larger cleanup

**Comment by ghost** [comment]
A large update for these links.....

**Comment by ghost** [comment]
@Schweinepriester: This is fixed at #4692 , I'll close it and for other problems, you can re-open it and feedback.
