### ISSUE TITLE
Automated release posts

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#47]
So, we have the releases .json file from build, if we also got the latest Changelog.md we could automatically generate the release blog posts rather than the manual ones we currently have which are quite a pain in the ass.

**Comment by phillipj** [comment]
From [v0.12.7 release post](https://github.com/nodejs/new.nodejs.org/blob/master/locale/en/blog/release/v0.12.7.md), is the summary written by hand while creating the post or could it be fetched somewhere?

Could @nodejs/build provide shasums?

**Comment by phillipj** [comment]
Nevermind the shasums. I found what I needed here https://nodejs.org/dist/v0.12.7/SHASUMS.txt.asc

**Comment by phillipj** [comment]
First version of a script addressing this just got merged into node-4.0-release branch with fd14e76. It's long from finished, thoughts about improving `./scripts/release-post.js` are more than welcome by creating new issues / PRs.
