### ISSUE TITLE
Request to undeprecate util.is* functions

### ISSUE THREAD

**Issue by WillAvudim** [nodejs/nodejs.org#4702]
I'd like to request to undeprecate all util.is* functions currently marked for deprecation, and keep them intact in all future versions of Node.js.

Reasons:
1. util.is* functions (util.isObject, util.isNumber, util.isRegExp) are immensely useful and used throughout the codebase of pretty much every node.js app.

2. They are succinct and help to avoid unnecessary cognitive load, while the suggested alternatives are verbose and difficult to remember, and write correctly every single time.

Take for example util.isObject and compare the function isObject:

```
if (isObject(functionThatReturnsObject(param1, param2)) { ... }
```

vs what the documentation suggests I'd have to write instead:

```
if (functionThatReturnsObject(param1, param2) !== null && typeof functionThatReturnsObject(param1, param2) === 'object') { ... }
```

Do you really think that the second fragment is more obvious to any software engineer out there?

3. The alternative implementation, e.g. lodash, is less efficient since it has to handle many corner cases not applicable to node.js.  And lodash detects node.js and uses util.is* functions underneath for efficiency, e.g.  https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/lodash.js#L452

4. They have great typescript annotations already written and maintained.

**Comment by ghost** [comment]
This discussion can be moved to node.js instead of here for more notifications :)

**Comment by WillAvudim** [comment]
Oh, you're right, my apologies. Filed as https://github.com/nodejs/node/issues/43715. Closing this one.
