### ISSUE TITLE
Order of versions in Index of /docs/

### ISSUE THREAD

**Issue by stevemao** [nodejs/nodejs.org#471]
https://nodejs.org/docs/

Currently the order is in alphabetical. Would be better if it was in reverse chronological order.

**Comment by lpinca** [comment]
I guess this is how directory listing works in nginx, I don't know if it can be configured to order the output.

**Comment by lpinca** [comment]
https://www.nginx.com/resources/wiki/modules/fancy_index/

**Comment by xcatliu** [comment]
Nginx autoindex options listed here: http://nginx.org/en/docs/http/ngx_http_autoindex_module.html

**Comment by xcatliu** [comment]
Nginx `autoindex` options listed here:
http://nginx.org/en/docs/http/ngx_http_autoindex_module.html

**Comment by phillipj** [comment]
This is the [nodejs.org nginx config](https://raw.githubusercontent.com/nodejs/build/master/setup/www/resources/config/nodejs.org) for /docs ATM:

```
location /docs {
    alias /home/dist/nodejs/docs/;
    autoindex on;
    default_type text/html;

    location ~ \.json$ {
        add_header access-control-allow-origin *;
    }
}
```

> Nginx autoindex options listed here:
> http://nginx.org/en/docs/http/ngx_http_autoindex_module.html

Doesn't look like autoindex has an option for sort ordering, but fancy_index does as of v0.3.3 obviously.

@nodejs/build would it be possible to install the fancy_index module for nginx?

**Comment by rvagg** [comment]
I've been tempted to do this to change the way we list filenames that get too long and are replaced with ellipses which frustrate me no end. However, the security implications of adding fancyindex have made me -1 on doing so at this point. It's an unofficial module, and not likely very widely used, we wouldn't get regular security updates to it via the normal system update system and it's just another potential vector for attack.

The ordering the the same for /dist/, we have the `latest` symlinks at the top. I'm -1 on doing anything about this, if we need a proper fancy index then let's build one as part of the site so it actually looks nice and is integrated with the rest of nodejs.org.

**Comment by stevemao** [comment]
ping @nodejs/build @jbergstroem :)

**Comment by jbergstroem** [comment]
Agree with @rvagg here; there's no real good way of maintaining nginx 3rd party modules from the current standpoint. Next nginx stable release will support a 3rd party module system that doesn't have to be compiled as part of the binary which likely makes this much easier but ultimately (also) think that building it as part of the website is likely a better solution.

**Comment by fhemberger** [comment]
Closing this for now. We might reconsider this issue, once the new nginx module is available and has been thoroughly tested.
