### ISSUE TITLE
Got error code 404 from the server.

### ISSUE THREAD

**Issue by VeresAndrei** [nodejs/nodejs.org#4711]
- **URL**: https://nodejs.org/dist/v14.15.0/node-v14.15.0-darwin-arm64.tar.gz 
- **Browser version**: Chrome - Version 103.0.5060.114 (Official Build) (arm64)
- **Operating system**: macOS

Hello!

I have at work a project in which we are using node v14.15.0,  it has something like this in pom.

<executions>
<execution>
<id>install node and npm</id>
<goals>
<goal>install-node-and-npm</goal>
</goals>
<configuration>
<nodeVersion>v14.15.0</nodeVersion>
<npmVersion>6.14.8</npmVersion>
</configuration>
</execution>
<execution>

Each time I run clean install + npm I receive -> Got error code 404 from the server.
From what I saw -> https://nodejs.org/dist/v14.15.0/node-v14.15.0-darwin-arm64.tar.gz  was removed from the website. Can someone tell me please why? And from where can I download this version?

Thank you,
Andrei

**Comment by richardlau** [comment]
It hasn't been removed -- it never existed in the first place. We only started producing Apple silicon (M1/arm64) builds from Node.js 16 onwards https://nodejs.org/en/blog/release/v16.0.0/.

**Comment by richardlau** [comment]
Your options would be to either run the x64 macOS binary (https://nodejs.org/dist/v14.15.0/node-v14.15.0-darwin-x64.tar.gz) with Rosetta 2 or use Node.js 16.

**Comment by VeresAndrei** [comment]
Strange, because I have worked on this project several times and no issue was encountered until I have changed the node version on my PC for another project. Now I have put back the initial version and is not working anymore.

Thanks for the quick response!
