### ISSUE TITLE
Error while installing node js on my late macbook pro 2011

### ISSUE THREAD

**Issue by Aashraw** [nodejs/nodejs.org#4718]
![Screen Shot 2022-07-14 at 10 11 02 AM](https://user-images.githubusercontent.com/98750715/178900712-54eb4b5f-0aba-49c4-96ca-7df260378ca6.png)
![Screen Shot 2022-07-14 at 10 11 21 AM](https://user-images.githubusercontent.com/98750715/178900726-d8ca9bb5-250b-4099-95d3-f951672c2b01.png)

- **URL**:
- **Browser version**:
- **Operating system**:

**Comment by MaledongGit** [comment]
Maybe this issue can be removed to Node.js (https://github.com/nodejs/node/issues).

**Comment by MaledongGit** [comment]
@Aashraw : Maybe this issue can be removed to Node.js (https://github.com/nodejs/node/issues).

I'll close this issue, for any other related problems about this website, you can re-open it and let's continue.

**Comment by Aashraw** [comment]
> @Aashraw : Maybe this issue can be removed to Node.js (https://github.com/nodejs/node/issues).
> 
> I'll close this issue, for any other related problems about this website, you can re-open it and let's continue.

I can't seem to find solution for my issue
