### ISSUE TITLE
add inclusivity working group to list of working group on `about/working-groups`

### ISSUE THREAD

**Issue by ashleygwilliams** [nodejs/nodejs.org#472]
it is not listed. 
<img width="769" alt="screen shot 2016-01-19 at 8 34 49 am" src="https://cloud.githubusercontent.com/assets/1163554/12419984/884227c2-be87-11e5-99c7-b2aa90d29b90.png">

PR incoming

**Comment by ghost** [comment]
perhaps add that the inclusivity WG is chartered directly under the TSC

**Comment by fhemberger** [comment]
Inclusivity WG can be found here: https://nodejs.org/en/about/working-groups/#current-top-level-working-groups
