### ISSUE TITLE
nodejs connection refused

### ISSUE THREAD

**Issue by sbavi2** [nodejs/nodejs.org#474]
I have 2 different nodejs runtime installed on my dev server. 0.10.x and 0.12.x. The load balancer routes the traffic to port 3443 on 0.10.x (https). The request handler looks for a particular uri context pattern and if matched then it routes to 0.12.x node by using traditional http.request on port 4443. So in essence the server 0.10.x acts as a proxy to 0.12.x node.

Issue: Intermittently the API requests fails when tried from browser / REst client (get connection refused). But the same works when tried for the second time.

**Comment by stevemao** [comment]
This is the website issue tracker.
Please go to https://github.com/nodejs/node/issues/new
