### ISSUE TITLE
turkish translation: unarchive the repo

### ISSUE THREAD

**Issue by salihdev0** [nodejs/nodejs.org#4749]
Hey `@nodejs/nodejs-tr` contributors, it looks like this team hasn't been down for a long time. Please unarchive the repo and let's restart work. I can use most of my free time here. Waiting for your reply.

Best,

**Comment by Trott** [comment]
> Please unarchive the repo

Translation work for most of the website should come in the form of pull requests to the files in https://github.com/nodejs/nodejs.org/tree/main/locale/tr.

For the API docs, use CrowdIn: https://crowdin.com/project/nodejs
