### ISSUE TITLE
es: URL not found

### ISSUE THREAD

**Issue by victorarley** [nodejs/nodejs.org#4753]
### URL:

https://nodejs.org/es/about/

### Browser Name:

Chrome

### Browser Version:

103.0.5060.134

### Operation System:

Windows 10 Enterprise 21H2

### How to reproduce the issue:

This URL not found
https://github.com/nodejs/node/blob/main/doc/topics/blocking-vs-non-blocking.md

![image](https://user-images.githubusercontent.com/26607585/181996984-194e78a2-80f1-4e4b-a8fd-f5750941f2c4.png)

**Comment by ghost** [comment]
Not only this bug but also this:
![1659258634487](https://user-images.githubusercontent.com/52018749/182019278-1cb54fc1-763e-4597-92db-d3df1fb3aa97.png)

PS: The quickest way to fix it is to copy the related URLs from English version to the Spanish one, and change 'en' to 'es' in its md files, However I'm not sure whether there are any changes not synced with the English version in its context.

Ping @nodejs/nodejs-es : Anyone can help to check the URLs and the content synced with the English version?
