### ISSUE TITLE
GIthub does not render the too-long changelog of Nodejs 18.9.0

### ISSUE THREAD

**Issue by dilyanpalauzov** [nodejs/nodejs.org#4816]
### URL:

https://nodejs.org/en/

### Browser Name:

Irrelevant

### Browser Version:

Irrelevant

### Operation System:

Irrelevant

### How to reproduce the issue:

At https://nodejs.org/en/ is written “Nodejs 18.9.0 Currenlt Changelog*.  The Changelog is a hyperlink to https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.9.0 .  Github does not render the final address, stating “This blob took too long to generate.

But you can view the [raw file](https://github.com/nodejs/node/raw/main/doc/changelogs/CHANGELOG_V18.md).”

**Comment by nschonni** [comment]
FYI @nodejs/releasers 
Don't think there is anything we can do with the github limitation though

**Comment by RafaelGSS** [comment]
I think we'll need to change it to the GitHub changelog. Example: https://github.com/nodejs/node/releases/tag/v18.9.0

**Comment by targos** [comment]
> I think we'll need to change it to the GitHub changelog. Example: https://github.com/nodejs/node/releases/tag/v18.9.0

There's another limitation on this. I had to truncate https://github.com/nodejs/node/releases/tag/v16.17.0 because the number of characters is limited.

**Comment by RafaelGSS** [comment]
Wouldn't `<details>` solve it?

<details>
<summary>Commits</summary>

* Full list of commits...
</details>

**Comment by targos** [comment]
No. There's at least a client-side check that just prevents from entering more characters:
![image](https://user-images.githubusercontent.com/2352663/189706201-f65f0c84-7f4b-4a48-8091-f42ab6f2f65a.png)

**Comment by ovflowd** [comment]
As many mentioned before, this seems to be a GitHub limitation. Also this issue does not belong to this repository as the changelog is on `nodejs/node`.

Closing the issue.
