### ISSUE TITLE
Releases page returns 404

### ISSUE THREAD

**Issue by char0n** [nodejs/nodejs.org#4824]
### URL:

https://nodejs.org/en/about/releases/

### Browser Name:

Chrome

### Browser Version:

103

### Operation System:

Linux Mint 20.3

### How to reproduce the issue:

The web page is returning 404.  I could find alternative source of the info that was provided on the website here: https://github.com/nodejs/Release

**Comment by nschonni** [comment]
It was removed in https://github.com/nodejs/nodejs.org/pull/4821 before the redirect could land in https://github.com/nodejs/build/pull/3033

**Comment by MaryGao** [comment]
@nschonni Thanks for the update! I'd like to confirm with two items:

- Is the 404 error temporary or permanent for page https://nodejs.org/en/about/releases/? 
- Any alternative source page in nodejs.org website?

**Comment by nschonni** [comment]
The removal has been reverted for now till the redirect is put into place. The PR was just merged to early, but those pages will eventually have a server redirect first deployed, then the removals will be redone
