### ISSUE TITLE
docs link error

### ISSUE THREAD

**Issue by c608345** [nodejs/nodejs.org#4831]
### URL:

https://nodejs.org/en/docs/guides/

### Browser Name:

chrome

### Browser Version:

100

### Operation System:

windows

### How to reproduce the issue:

Page not found   Introduction to Node.js   https://nodejs.dev/learn, correct link is  https://nodejs.dev/en/learn

**Comment by Aman-0604** [comment]
@c608345 I have opened a pull request for the same few moments ago where I updated all the links related to this topic.
I found 24 such links in 12 files.

**Comment by c608345** [comment]
Thank you for your fix.
