### ISSUE TITLE
2022-09-22 The time in the september 2022securityreleases may be wrong🤔

### ISSUE THREAD

**Issue by pwnfox** [nodejs/nodejs.org#4837]
### URL:

https://nodejs.org/en/blog/vulnerability/september-2022-security-releases/

### Browser Name:

Chrome

### Browser Version:

107.0.5304.10

### Operation System:

Windows 10、21H2、19044.1826

### How to reproduce the issue:

It should be September 22, not July 22
![image](https://user-images.githubusercontent.com/111500026/191878533-109708dd-8b70-426e-84e0-0e777a90c281.png)

**Comment by ovflowd** [comment]
I don't see anything wrong, but @vdeturckheim just to double check, is that sub heading intentional?

**Comment by richardlau** [comment]
Thanks. Fixed in https://github.com/nodejs/nodejs.org/pull/4838.

**Comment by vdeturckheim** [comment]
Thanks!
