### ISSUE TITLE
VM util.inspect context tutorial contains error

### ISSUE THREAD

**Issue by kweng2** [nodejs/nodejs.org#484]
When inspecting a context that was run in a context, should not be using sandbox to inspect

[Imgur](http://i.imgur.com/DOeESRz.png?1)

**Comment by lpinca** [comment]
It's not exactly an error. In that case `sandbox === context`.
Are you suggesting to change it as follow?

``` js
console.log(util.inspect(context));
```

**Comment by wonderdogone** [comment]
I dont see how this is an error?

**Comment by fhemberger** [comment]
Closing this for now, please feel free to reopen it with additional details.
