### ISSUE TITLE
Add a banner for supporting Iranian protests

### ISSUE THREAD

**Issue by vader-sama** [nodejs/nodejs.org#4853]
Hi
I know this is off-topic but I've seen many websites have done the same for **Black lives matter** movement.
Iranians are fighting for freedom and human rights and we as developers at least can spread their voice across the globe 🕊️

**Comment by alirezanqp** [comment]
Thank you for supporting the people of Iran.
@RafaelGSS @targos @nschonni @Trott @ljharb @richardlau @joesepi @benhalverson

**Comment by Trott** [comment]
Thanks for the request. Unfortunately, I'm going to close (and lock) this issue. The TSC is unlikely to endorse doing this for the same reasons we quickly reverted a banner in https://github.com/nodejs/nodejs.org/pull/4467#issue-1158498159. I also suspect the OpenJS Foundation would have the same approach, for better or worse. @rginn @nodejs/tsc
