### ISSUE TITLE
where is the configuration documentation 

### ISSUE THREAD

**Issue by cafutor** [nodejs/nodejs.org#486]

**Comment by xcatliu** [comment]
What do you mean by configuration documentation?
Perhaps you should read [CONTRIBUTING](https://github.com/nodejs/nodejs.org/blob/master/CONTRIBUTING.md) first

**Comment by stevemao** [comment]
What is the issue here?

@cafutor if you wanna ask a question, please open an issue at https://github.com/nodejs/help or stackoverflow. This is the issue tracker for the nodejs website only. Thanks.
