### ISSUE TITLE
Remove code+learn 

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/nodejs.org#4874]
### Enter your suggestions in details:

Remove code+ learn page
This work is in progress on nodejs.dev

**Comment by nschonni** [comment]
Not sure what this is tracking, I don't think this repo ever had this content to remove

**Comment by Trott** [comment]
> Not sure what this is tracking, I don't think this repo ever had this content to remove

This: https://github.com/nodejs/nodejs.org/blob/bbe4dddb0926a62356aaab2b0b5ca7dd77fd776b/locale/en/get-involved/code-and-learn.md

**Comment by nschonni** [comment]
Thanks, I wasn't seeing staring at the site nav 😆 , I see it's here https://nodejs.org/en/get-involved/code-and-learn/

**Comment by HassanBahati** [comment]
@AugustinMauroy @Trott @nschonni does this mean we need to remove this file [https://github.com/nodejs/nodejs.org/blob/bbe4dddb0926a62356aaab2b0b5ca7dd77fd776b/locale/en/get-involved/code-and-learn.md](https://github.com/nodejs/nodejs.org/blob/bbe4dddb0926a62356aaab2b0b5ca7dd77fd776b/locale/en/get-involved/code-and-learn.md) that renders as [https://nodejs.org/en/get-involved/code-and-learn/](https://nodejs.org/en/get-involved/code-and-learn/) ?

**Comment by nschonni** [comment]
Yes, plus the translated files, and check for any links to the page

**Comment by HassanBahati** [comment]
> Yes, plus the translated files, and check for any links to the page

okay. let me get started with working on this

**Comment by HassanBahati** [comment]
> Yes, plus the translated files, and check for any links to the page

@nschonni please find the submitted pull request at #4883
