### ISSUE TITLE
About page link

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/nodejs.org#4875]
### Enter your suggestions in details:

In https://nodejs.org/en/about/
We have an link [Blocking vs. Non-Blocking](https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/).
so I propose to redirect to nodejs.dev

**Comment by Trott** [comment]
We should remove the link from that guide. It is out of place there.

**Comment by AugustinMauroy** [comment]
> We should remove the link from that guide. It is out of place there.

I propose more simply, that when you click or connect to `about`. We are redirected to https://nodejs.dev/en/about/

**Comment by Trott** [comment]
> > We should remove the link from that guide. It is out of place there.
> 
> I propose more simply, that when you click or connect to `about`. We are redirected to https://nodejs.dev/en/about/

Why?

**Comment by AugustinMauroy** [comment]
instead of deleting we can redirect. This is less "direct".

**Comment by ovflowd** [comment]
It doesn't make sense to redirect nodejs.org to nodejs.dev...

**Comment by HassanBahati** [comment]
> We should remove the link from that guide. It is out of place there.

under that [section of the about page](https://nodejs.org/en/about/) we talk about handling connections concurrently, and [blocking](https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/) entails making execution of additional JavaScript in the Node.js process to wait until a non-JavaScript operation completes. 

@Trott, I seek to understand why you would say it is misplaced.

**Comment by HassanBahati** [comment]
@Trott @ovflowd @AugustinMauroy, can I take on the implementation of this issue...

**Comment by ovflowd** [comment]
Depends? What do you want to do? I’m not sure there’s yet a clear decision of what should be done here

**Comment by HassanBahati** [comment]
> 

Okay please, let me hold we until we arrive at a comprehensive way forward

**Comment by Trott** [comment]
> > 
> 
> Okay please, let me hold we until we arrive at a comprehensive way forward

Sorry, no [cookie-licking](https://www.redhat.com/en/blog/dont-lick-cookie).

**Comment by Trott** [comment]
> Sorry, no [cookie-licking](https://www.redhat.com/en/blog/dont-lick-cookie).

If you'd like to get right to work, thoughl, I'd support both of these things:

* Remove the About link from the bottom of https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/ and all translations of that page.
* Remove superfluous About content from the About page on nodejs.dev. It should at *least* be reduced to what we have on nodejs.org. All the stuff about cluster module and Twisted is outdated and/or out of place there. It should be removed.

**Comment by ovflowd** [comment]
> All the stuff about cluster module and Twisted is outdated and/or out of place there. It should be removed.

Could you pinpoint which paragraphs need to be removed from both places? 👀

**Comment by Trott** [comment]
> Could you pinpoint which paragraphs need to be removed from both places? 👀

Whoops, I thought we had already removed a bunch of that text from nodejs.org, but I am wrong wrong wrong. It's all still there.

So, OK, as a starter, this sentence should be rewritten or removed in my opinion:

> Almost no function in Node.js directly performs I/O, so the process never blocks except when the I/O is performed using synchronous methods of Node.js standard library. 

This seems superfluous to me:

> Node.js is similar in design to, and influenced by, systems like Ruby's [Event Machine](https://github.com/eventmachine/eventmachine) and Python's [Twisted](https://twistedmatrix.com/trac/). Node.js takes the event model a bit further.

But if it's removed, then "It" in the next sentence needs to be changed to "Node.js". And later material in the paragraph needs to be rewritten or removed because it refers back to the mention of Ruby in the first sentence, etc.

Some basic editing: Sometimes "event loop" has a hyphen in the text and sometimes not. (It should probably never have a hyphen in my opinion, except in some unusual cases.)

The whole page, from the sample code to the text, implies that Node.js is very HTTP-focused. There's some truth to that, but also, not really. So I wouldn't mind this paragraph being removed.

> HTTP is a first-class citizen in Node.js, designed with streaming and low latency in mind. This makes Node.js well suited for the foundation of a web library or framework.

So that's my opinion based on just a few minutes of review. What do you think?

**Comment by HassanBahati** [comment]
> > Sorry, no [cookie-licking](https://www.redhat.com/en/blog/dont-lick-cookie).
> 
> If you'd like to get right to work, thoughl, I'd support both of these things:
> 
> * Remove the About link from the bottom of https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/ and all translations of that page.
> * Remove superfluous About content from the About page on nodejs.dev. It should at _least_ be reduced to what we have on nodejs.org. All the stuff about cluster module and Twisted is outdated and/or out of place there. It should be removed.

@Trott am getting started right away on these tasks.

**Comment by HassanBahati** [comment]
> > > Sorry, no [cookie-licking](https://www.redhat.com/en/blog/dont-lick-cookie).
> > 
> > 
> > If you'd like to get right to work, thoughl, I'd support both of these things:
> > 
> > * Remove the About link from the bottom of https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/ and all translations of that page.
> > * Remove superfluous About content from the About page on nodejs.dev. It should at _least_ be reduced to what we have on nodejs.org. All the stuff about cluster module and Twisted is outdated and/or out of place there. It should be removed.
> 
> @Trott am getting started right away on these tasks.

@Trott i have opened a [pull request](https://github.com/nodejs/nodejs.org/pull/4881) please review.

**Comment by HassanBahati** [comment]
> 

@Trott @ovflowd do we need to remove the about link from bottom of [https://nodejs.dev/en/learn/overview-of-blocking-vs-non-blocking/](https://nodejs.dev/en/learn/overview-of-blocking-vs-non-blocking/) on the [website redesign](https://nodejs.dev/en/) similarly to how we have removed it from  [ https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/]( https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/)

**Comment by ovflowd** [comment]
@HassanBahati I completely missed your comment, yes, we could remove it :)

**Comment by HassanBahati** [comment]
> @HassanBahati I completely missed your comment, yes, we could remove it :)

here is a pr for it [https://github.com/nodejs/nodejs.dev/pull/3110](https://github.com/nodejs/nodejs.dev/pull/3110)
