### ISSUE TITLE
V19 banner isn't in SVG

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/nodejs.org#4891]
### URL:

https://nodejs.org/en/

### propose

I propose to put it in svg because at the moment it is very pixelated. This will have the effect of making the web page of nodejs.org and .dev more pretty and clean

**Comment by nschonni** [comment]
@Trott don't know if you made the original one, or it came from someone at the foundation

**Comment by Trott** [comment]
> @Trott don't know if you made the original one, or it came from someone at the foundation

It came from the foundation. We could see about getting an SVG version, but I'm going to guess that the turnaround time on that would take us near or past the time next week when the banner is scheduled to come down.
