### ISSUE TITLE
LTS Roadmap on website

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#493]
We've been getting questions about LTS a lot and it would be good to have it one the website rather than just in the README on the LTS repo.

@nodejs/documentation 

For reference:

![screen shot 2016-01-29 at 12 44 22 pm](https://cloud.githubusercontent.com/assets/579/12683554/ba04b088-c66e-11e5-928a-87c913960833.png)

**Comment by eljefedelrodeodeljefe** [comment]
The easiest I can come up with immediately would be... (Link to: https://raw.githubusercontent.com/nodejs/LTS/master/schedule.png)

![node_js](https://cloud.githubusercontent.com/assets/3899684/12684312/8a350a56-c6be-11e5-900a-3a20f4954894.png)

**Comment by gtewallace** [comment]
+1 thanks @eljefedelrodeodeljefe

**Comment by mikeal** [comment]
I think we need more that just the graphic, the graphic is great but a lot of the context for what LTS is we need text for.

**Comment by eljefedelrodeodeljefe** [comment]
Should we make it incremental? ...have the above not and create some whole subpage? This would probably take way bigger effort, since I wouldn't just append `LTS` to the navbar.

**Comment by mikeal** [comment]
Ya, you're right, getting _something_ up soon is best, I'm just wondering if we should link to the whole README or just to the graphic?

**Comment by eljefedelrodeodeljefe** [comment]
If we could have an anchor on the readme above the image that should be fine. I'll open a pull request for the above and on the readme.

**Comment by MylesBorins** [comment]
Long term I think having some sort of interactive info graphic that is accurate as of the current time would be very useful

**Comment by eljefedelrodeodeljefe** [comment]
The interim change would be ready.

**Comment by Trott** [comment]
There is now a link to the LTS schedule on the front page. I think this can be closed as stale/inactive/done-ish. Feel free to re-open if you think I'm wrong.
