### ISSUE TITLE
Link address in hidden texts on crowdin sould be translatable for anchor links

### ISSUE THREAD

**Issue by albu77** [nodejs/nodejs.org#4946]
### Enter your issue on localizations here:

1. French translation but should be the same for every locale
2. When a link refer to an anchor inside the document :
  there should be a Link address in the hidden text where we can put the translated text for the anchor. 
For example in issues.md there are : 
![image](https://user-images.githubusercontent.com/624802/202860411-5403775c-a2a7-4d9e-947b-a9ddb0f98f2c.png)
 BUT these hidden texts are not translatable so as they stay in english the links don't work

**Comment by AugustinMauroy** [comment]
I don't really understand what are you ref?

**Comment by ovflowd** [comment]
Closing as all translation efforts are now on Crowdin and discussions should be done there.
