### ISSUE TITLE
Mistype in docs 

### ISSUE THREAD

**Issue by NikIvan** [nodejs/nodejs.org#496]
[Docs  -> Assertion Testing -> assert.notDeepEqual](https://nodejs.org/dist/latest-v4.x/docs/api/assert.html#assert_assert_notdeepequal_actual_expected_message)

Function calls in examples are **`assert.deepEqual()`**, not **`assert.notDeepEqual()`**.
Results seems to be correct.
True for v4 & v5.
Thanks.

**Comment by stevemao** [comment]
Good catch @NikIvan , PR welcome :)

**Comment by JungMinu** [comment]
I'll handle this issue :)

**Comment by lpinca** [comment]
Closing, thank you.

**Comment by stevemao** [comment]
@NikIvan for future reference, the docs are maintained @ https://github.com/nodejs/node/tree/master/doc/api, you're more than welcome to submit a pull request to fix or improve docs when you see something in need

https://github.com/nodejs/nodejs.org/issues/503#issuecomment-178964591
