### ISSUE TITLE
Add Belarusian language to the list of supported translations o  crowdin

### ISSUE THREAD

**Issue by zubialevich** [nodejs/nodejs.org#5000]
### Enter your issue on localizations here:

1. Node localization team
2. Can you add Belarusian language to the list of supported languages on the crowding platform, so we can start translation?

**Comment by ovflowd** [comment]
@zubialevich if you request to be added to the team on Crowdin, I can add the language for you :)

**Comment by ovflowd** [comment]
But I would recommend not to work on translations for now, *as* the repository is entering on a content freeze, as we're migrating to a different infrastructure.

**Comment by ovflowd** [comment]
FYII @zubialevich was added to the list of translators on Crowdin and the language was also added..
