### ISSUE TITLE
404 error for all knowlege pages

### ISSUE THREAD

**Issue by jcubic** [nodejs/nodejs.org#5009]
### URL:

https://nodejs.org/en/knowledge/HTTP/servers/how-to-serve-static-files/

### Browser Name:

Chrome

### Browser Version:

108

### Operation System:

Fedora GNU/Linux

### How to reproduce the issue:

1. Search "nodejs serve static files"
2. Open the first result in Google
3. Got error `ENOENT: no such file or directory`

**Comment by AugustinMauroy** [comment]
The knowledge has been removed. But there is the learn section of the website redesign that will arrive. After why google continues to display this link, I have no idea.

**Comment by jcubic** [comment]
Then you should somehow remove it from Google. You can do that with Google Search Console. Making the page return 404 will not remove it from search results.

Or maybe find a similar page that can be redirected. Even a 301 redirect to the home page is better than the 404 page that is indexed.

How long ago it was removed?

**Comment by AugustinMauroy** [comment]
This was removed two days ago

**Comment by jcubic** [comment]
Oh, ok. If all /knowledge pages was removed I think that 301 redirect to the home page (or an alternative page with similar tutorials) would be the best solution here.

Adding a redirect the website will benefit from the links to the old URLs from the SEO perspective.

**Comment by nschonni** [comment]
Yeah, that was discussed https://github.com/nodejs/nodejs.org/pull/4999#pullrequestreview-1239683673 but looks like it landed without resolving that

**Comment by ovflowd** [comment]
> Then you should somehow remove it from Google. You can do that with Google Search Console. Making the page return 404 will not remove it from search results.

We don't have Search Console, as we don't even do indexing. In our case, Google uses "robots" to index our pages. It should update by itself over the time.

> Or maybe find a similar page that can be redirected. Even a 301 redirect to the home page is better than the 404 page that is indexed.

I don't see much difference between redirecting to home or showing the 404 page. In both scenarios, the user will not receive the content they originally "requested" for. The 404 page explicitly tells them that content is not available anymore.

**Comment by ovflowd** [comment]
But point taken, I think our 404 page should have a better message, to be honest.

**Comment by jcubic** [comment]
There may be no difference to users when they visit 404 but it will be important for Google and SEO. People may link to that knowledge article if you return 404 you just lost the value of that link. You may don't care, but you just lost the opportunity to improve the visibility of the page in Google.

**Comment by ovflowd** [comment]
> There may be no difference to users when they visit 404 but it will be important for Google and SEO. 

By redirecting to the home page, Google will keep the SEO entry for that page. It is essential (IMHO) that Google knows that this page doesn't exist so it is able to remove it from the index.

> People may link to that knowledge article if you return 404 you just lost the value of that link.

The link has no value already.

> You may don't care, but you just lost the opportunity to improve the visibility of the page in Google.

Bold assumption from your side. We don't want to index unexisting pages. We shouldn't care about their indexing score; we're not trying to marketize or be the \# 1 ranked page. 

I rather have other websites that actually provide meaningful results (like actual pages that can provide help to the person making this search) be ranked higher than increase our own search index for a result that will not help the user.

**Comment by khadeshyam** [comment]
I am getting the same issue on Chrome , Firefox , Brave and Edge

**Comment by ovflowd** [comment]
I'm closing this issue as it was already explained the outcome.
