### ISSUE TITLE
Windows download incorrectly selects 32bit on 64bit machine

### ISSUE THREAD

**Issue by styfle** [nodejs/nodejs.org#5028]
### URL:

https://nodejs.org/en/

### Browser Name:

Edge

### Browser Version:

109.0.1518.55 (Official build) (64-bit)

### Operation System:

Windows 11 Pro Insider Preview 22H2 25276.1000

### How to reproduce the issue:

1. Visit https://nodejs.dev/en/
2. Click "Download Node (LTS)"

It incorrectly downloaded 32 bit version https://nodejs.org/dist/v18.13.0/node-v18.13.0-x86.msi

I expected the 64 bit version.

**Comment by nschonni** [comment]
This doesn't happen on .org on either Firefox or Edge
![image](https://user-images.githubusercontent.com/1297909/213760964-09364115-f047-41b6-ad50-13c2031e70dc.png)
Your issue the the `.dev` site is valid though

**Comment by styfle** [comment]
I created PR #5025 which has a lot more context and discussion.

**Comment by ghost** [comment]
@styfle : I've submitted the changes, and if this solves your problem, please close it or feel free to discuss with us :)

**Comment by ovflowd** [comment]
I think we can close this for now.
