### ISSUE TITLE
In API, reference to non-existent function hash.final()

### ISSUE THREAD

**Issue by shelleyp** [nodejs/nodejs.org#503]
In API documentation at https://nodejs.org/api/crypto.html#crypto_class_hash a reference to a non-existent API function, hash.final(). It should be hash.digest().

**Comment by JungMinu** [comment]
I'll take care of this :)

**Comment by rvagg** [comment]
@shelleyp for future reference, the docs are maintained @ https://github.com/nodejs/node/tree/master/doc/api, you're more than welcome to submit a pull request to fix or improve docs when you see something in need.

**Comment by stevemao** [comment]
Closing as PR is raised nodejs/node#5050
