### ISSUE TITLE
Broken links for 0.12.8 and 0.12.9 changelogs

### ISSUE THREAD

**Issue by borisovg** [nodejs/nodejs.org#504]
On this page: https://nodejs.org/en/download/releases/

404 for links:
- https://github.com/nodejs/node-v0.x-archive/blob/v0.12.9/ChangeLog
- https://github.com/nodejs/node-v0.x-archive/blob/v0.12.8/ChangeLog

**Comment by MylesBorins** [comment]
@rvagg

**Comment by Fishrock123** [comment]
Those appear to be the two 0.12 releases so far made off of the nodejs/node repo. No releases are done from the archive anymore.

There's probably a regex wrong somewhere.

**Comment by Fishrock123** [comment]
Working on a fix.
