### ISSUE TITLE
The documentation on streams is not very good.

### ISSUE THREAD

**Issue by gdennie** [nodejs/nodejs.org#506]
For example, the following:

```
Class: stream.Transform#

Transform streams are Duplex streams where the output is in some way computed from the input. They implement both the Readable and Writable interfaces.

Examples of Transform streams include:

zlib streams
crypto streams
```

To state that `the output is in some way computed from the input` as a distinguishing characteristics of Transform streams necessitating Duplex functionality is not helpful since all streams would necessarily seem to calculate their outputs from their inputs.

**Comment by stevemao** [comment]
The stream documentation in general has a lot of problems. see https://github.com/nodejs/readable-stream/issues/181

**Comment by Knighton910** [comment]
Like @stevemao has referenced, we're having issues with `streams documentation` right now. But we are working on that. This `Docs Issue` is a priority for us, so we'll have it fixed soon. :100:

**Comment by stevemao** [comment]
Closing as the issue is already posted in relevant repos. This one doesn't belong here.
