### ISSUE TITLE
SHASUMS256.txt for v15.14.0 is empty

### ISSUE THREAD

**Issue by SoleilAtZaber** [nodejs/nodejs.org#5065]
### URL:

https://nodejs.org/download/release/v15.14.0/SHASUMS256.txt

### Browser Name:

curl

### Browser Version:

7.68

### Operation System:

Ubuntu, Windows 10

### How to reproduce the issue:

https://nodejs.org/download/release/v15.14.0/SHASUMS256.txt shows a non-zero file size in the directory listing but every download attempt yields zero bytes and HTTP status 200 (OK).

The other shasum files in the same directory download with content, as does this file in the v15.13.0 directory.

This is causing an automated install to fail in a gyp task somewhere inside:
   { curl -sL https://deb.nodesource.com/setup_15.x | bash - ; } && apt-get install -y nodejs

I've tried downloading the file manually on four different platforms and three browsers/tools and it's always a successful download of zero bytes.

**Comment by nschonni** [comment]
@nodejs/build @nodejs/releasers guessing this should get transferred to the build repo

**Comment by BethGriggs** [comment]
This seems to be another occurrence of https://github.com/nodejs/build/issues/3194 as https://direct.nodejs.org/download/release/v15.14.0/SHASUMS256.txt exists. I think we'll need someone from @nodejs/build-infra to queue a CDN purge.

**Comment by rvagg** [comment]
purgeificated, file is now there

**Comment by SoleilAtZaber** [comment]
Confirmed. Thanks for the quick response!
