### ISSUE TITLE
Articles in blog RSS feeds missing `/en/` in URL and point to non-existent pages

### ISSUE THREAD

**Issue by Conduitry** [nodejs/nodejs.org#5080]
### URL:

https://nodejs.org/en/feed/blog.xml

### Browser Name:

n/a

### Browser Version:

n/a

### Operation System:

n/a

### How to reproduce the issue:

1. I opened one of the blog RSS feeds (https://nodejs.org/en/feed/blog.xml https://nodejs.org/en/feed/releases.xml https://nodejs.org/en/feed/vulnerability.xml).
2. I clicked on one of the links in them.
3. I got a 404.

The feeds contain URLs like https://nodejs.org/blog/release/v18.15.0 while the proper URLs for these blog posts are of the form https://nodejs.org/en/blog/release/v18.15.0

**Comment by tniessen** [comment]
cc @ovflowd

**Comment by ovflowd** [comment]
Thanks! This should easily be fixable, gonna work on this tomorrow 🙏
