### ISSUE TITLE
"Previous Releases" page broken (outgoing links result in 404)

### ISSUE THREAD

**Issue by tniessen** [nodejs/nodejs.org#5081]
### URL:

https://nodejs.org/en/download/releases/

### How to reproduce the issue:

The page only shows certain releases now (compared to the full list before), which might be fine.

But all outgoing "Releases" links result in status code 404, which is not fine. Somehow, all these links point to `iojs.org` now.

Likely due to #4991, cc @ovflowd.

**Comment by ovflowd** [comment]
Thanks, @tniessen very interesting and probably a little typo I did somewhere. I appreciate the quick bug hunting!

**Comment by ovflowd** [comment]
And yes, we're showing only a few releases, as we didn't want to include sole hacky pagination script.

This likely will become obsolete as in the future the Previous Release will look like the new nodejs.dev Previous Releases page 👀

**Comment by ovflowd** [comment]
Fixed by #5083
