### ISSUE TITLE
Download buttons on home page open NGINX file viewer

### ISSUE THREAD

**Issue by mikeesto** [nodejs/nodejs.org#5082]
### URL:

https://nodejs.org/en/

### Browser Name:

Chrome

### Browser Version:

v110

### Operation System:

MacOS

### How to reproduce the issue:

On the home page, clicking on the download buttons for LTS or Current opens the NGINX (?) file viewer instead of downloading the file for my operating system.

<img width="834" alt="Screen Shot 2023-03-09 at 9 44 56 am" src="https://user-images.githubusercontent.com/21051488/223878726-8ff27fd1-eab4-4b23-bf05-f5354b6215e0.png">

**Comment by ovflowd** [comment]
This is really odd. And it’s supposed to be working. Thank you for reporting, @mikeesto.

If you’d like to work on this issue that’d be great! Otherwise I can look into it first thing tomorrow :)

**Comment by mikeesto** [comment]
I've had a very quick look and it actually works as intended when I'm running it locally, so I'm not sure what is going on tbh

**Comment by Trott** [comment]
If I don't click on a button and instead copy the link and paste it into the URL bar on the browser, it works as expected. This is really odd. Maybe @richardlau might have some idea what's going on here?

**Comment by Trott** [comment]
If instead of clicking the button, I right click and open in a new tab, it also works as expected!

**Comment by richardlau** [comment]
If I look at the page source I see this
![image](https://user-images.githubusercontent.com/5445507/223903033-2b2e20a9-cfe2-4bb0-b14f-8a628326d334.png)
i.e. the href is pointing to https://nodejs.org/dist/v18.15.0/ despite my browser suggesting the link would open https://nodejs.org/dist/v18.15.0/node-v18.15.0-x64.msi when I hover my mouse over the button 🤷

**Comment by mikeesto** [comment]
Very odd. I tried deploying a copy of this repo to Vercel and it works fine there - the href source code looks correct too

**Comment by yamitsushi** [comment]
the link somehow directs to `https://nodejs.org/dist/v18.15.0node-v18.15.0-x64.msi`
it should be `https://nodejs.org/dist/v18.15.0/node-v18.15.0-x64.msi`

see the missing '/' on the link

**Comment by richardlau** [comment]
FWIW If I remove the circled event listeners, left clicking on the link downloads the msi file.
![image](https://user-images.githubusercontent.com/5445507/223925471-4149a1b7-846b-4a6b-86f4-ec3e1713b531.png)

**Comment by ovflowd** [comment]
If I recall correctly our legacy scripts detect the OS and basically formulate the download link, they then inject via DOM the new link, which is probably conflicting with React or Next.js. The idea in the future of course is to get rid of that vanilla JS file once we start migrating to the new layout.

I'll check if for now there's any workaround we can do to fix this, as I feel these event listeners come from the `next/link` component.
