### ISSUE TITLE
Syntax highlighting lost on navigation

### ISSUE THREAD

**Issue by stefee** [nodejs/nodejs.org#5084]
### URL:

https://nodejs.org/en/about/

### Browser Name:

Mobile Safari

### Browser Version:

iOS 16.3.1

### Operation System:

iOS

### How to reproduce the issue:

1. Go to Node.js site
2. Go to About
3. See syntax highlighting
4. Go to Governance
5. Go to About
6. See no more syntax highlighting

https://twitter.com/absentmindedbi/status/1633774264770781185

**Comment by AugustinMauroy** [comment]
We can use nodejs.dev component.
What do you thinks @ovflowd ? 🤔

**Comment by ovflowd** [comment]
No, @AugustinMauroy, a bug fix should not introduce a new feature. Not even sure what component you're talking about.

**Comment by AugustinMauroy** [comment]
Ok Thanks for your answer! 

> Sorry for the issue
