### ISSUE TITLE
Nodejs installer downloads(mac, windows) are broken from browsers and automated build servers 

### ISSUE THREAD

**Issue by Soulskater** [nodejs/nodejs.org#5089]
### URL:

https://nodejs.org/dist/v16.14.0/node-v16.14.0-x86.msi

### Browser Name:

Chrome

### Browser Version:

latest

### Operation System:

MacOS 13.0.1

### How to reproduce the issue:

1. Try to download for example https://nodejs.org/dist/v16.14.0/node-v16.14.0-x86.msi
2. I expected to download the installer but i got 500 internal server error

**Comment by rodion-arr** [comment]
Duplicate of #4495

**Comment by ovflowd** [comment]
Closing as a duplicate.
