### ISSUE TITLE
layout gets messed up at some viewport sizes

### ISSUE THREAD

**Issue by Trott** [nodejs/nodejs.org#5096]
### URL:

https://nodejs.org/en/

### Browser Name:

Chrome

### Browser Version:

110.0.5481.100

### Operation System:

macOS Ventura 13.2.1

### How to reproduce the issue:

Upper left logo and the horizontal nav conflict  when the viewport is around 680 pixels wide or so. There's a similar problem with the icons on the upper left.

<img width="684" alt="image" src="https://user-images.githubusercontent.com/718899/224055077-b6697918-94de-4fc6-b078-fc78f9d35600.png">

**Comment by AugustinMauroy** [comment]
It must be from before the migration when I modified the header

**Comment by Trott** [comment]
Still happening but differently/only with the stuff at the end of the header. Note the dark mode/light mode switcher and the translation picker in this screenshot: 
<img width="501" alt="image" src="https://user-images.githubusercontent.com/718899/227786050-1ba7ffbf-b61c-40dd-9785-5b8d04816ab4.png">

**Comment by rodion-arr** [comment]
I can take it if nobody's working on it already. Looks like we have a fixed nav height and it is not correct for smaller screens

**Comment by ovflowd** [comment]
Feel free to work on that.
