### ISSUE TITLE
Scroll to top is required, especially for long pages like contribute/development

### ISSUE THREAD

**Issue by bogas04** [nodejs/nodejs.org#51]
Title says it all. I'm ready to take it up.

**Comment by fhemberger** [comment]
Just go ahead and send a PR. We'll review the change and give you feedback. ;)

**Comment by bogas04** [comment]
@fhemberger Please have a look : https://github.com/nodejs/new.nodejs.org/pull/54

**Comment by fhemberger** [comment]
Will do, closing this.
