### ISSUE TITLE
Nodejs download page is acting weird

### ISSUE THREAD

**Issue by zhaoqiu-china** [nodejs/nodejs.org#5102]
### What steps will reproduce the bug?

1. go to https://nodejs.org/en/download/
2. click "Current"
3. click Windows Installer. (My pc os is win10-x64 and "Windows Installer" has a href linkd "https://nodejs.org/dist/v19.7.0/node-v19.7.0-x64.msi")
4. I expect that x64.msi will be downloaded, however it's x86.msi

### What do you see instead?

![image](https://user-images.githubusercontent.com/51221150/224460697-aa1aa405-d684-4a9a-88cf-638d35593717.png)

**Comment by ghost** [comment]
Not only for Current，But LTS  as well has the issue in the download page
Link to x64 but download for x86....

**Comment by ghost** [comment]
![1678592034670](https://user-images.githubusercontent.com/52018749/224522715-bf03ed55-0ea6-4c21-ba27-9eedad91e1ac.png)

The reason may be the "x86" is fixed in the download link....And it is dynamically changed by js behind. However due to some reason it changes but in fact it isn't....I'll investigate why and fix the bug

**Comment by ovflowd** [comment]
@MaledongGit, your PR does not fix the issue. The issue is actually about the OS detection we have. We cannot reliably detect if the Windows OS is x64 or x86, and that's what needs to be fixed.

**Comment by ovflowd** [comment]
The actual PR fixing this issue is https://github.com/nodejs/nodejs.org/pull/5025

**Comment by ovflowd** [comment]
> The reason may be the "x86" is fixed in the download link....And it is dynamically changed by js behind. However due to some reason it changes but in fact it isn't....I'll investigate why and fix the bug

It is changing it, just changing it incorrectly. We assess the platform architecture by looking up the user agent and some meta info. In some browsers, we don't assess that reliably.

@zhaoqiu-china, on your screenshot, the Error attached in the console has nothing to do with the download issue. It is just the behaviour of `next/link` trying to prefetch that URL; I will change that component not to use `next/link` :)

**Comment by ovflowd** [comment]
For reference: This is fixed by #5025 and #5106

**Comment by SpeedyCodeYT** [comment]
I just changed my laptop and was installing node js. Found out that my laptop is based n x64 after this was working out. also, none of my favorite games work properly. Please hit me up for any contributions needed please. i need them for my job interview.

**Comment by ovflowd** [comment]
@SpeedyCodeYT, what are you even talking about? 😅

**Comment by ghost** [comment]
> > The reason may be the "x86" is fixed in the download link....And it is dynamically changed by js behind. However due to some reason it changes but in fact it isn't....I'll investigate why and fix the bug
> 
> It is changing it, just changing it incorrectly. We assess the platform architecture by looking up the user agent and some meta info. In some browsers, we don't assess that reliably.
> 
> @zhaoqiu-china, on your screenshot, the Error attached in the console has nothing to do with the download issue. It is just the behaviour of `next/link` trying to prefetch that URL; I will change that component not to use `next/link` :)

Got it, I found it later. 
Thanks for your guidance and I've removed my PR here.

**Comment by ovflowd** [comment]
@MaledongGit no worries! I appreciate your help and intentions. I hope my explanations on your PR made sense ;)

**Comment by ghost** [comment]
Hi @zhaoqiu-china：

This bug should be fixed now, could you please check and close the issue?

**Comment by zhaoqiu-china** [comment]
> Hi @zhaoqiu-china：
> 
> This bug should be fixed now, could you please check and close the issue?

Ok, thanks for your efforts!
