### ISSUE TITLE
Broken CSS and JS on nodejs.org

### ISSUE THREAD

**Issue by andersk** [nodejs/nodejs.org#5118]
### URL:

https://nodejs.org/en/

### Browser Name:

Firefox, Chromium

### Browser Version:

111.0b8, 111.0.5563.64

### Operating System:

NixOS 23.05

### How to reproduce the issue:

Visit https://nodejs.org. These CSS and JS files give 404 errors, so the page renders with all styles missing:

https://nodejs.org/_next/static/css/544619d424f2e805.css
https://nodejs.org/_next/static/chunks/main-24e77ca272e5424e.js
https://nodejs.org/_next/static/chunks/pages/_app-af30cbda94c3e1fd.js
https://nodejs.org/_next/static/chunks/pages/en-5ce35ca30e7fbbdd.js
https://nodejs.org/_next/static/fBjW_rjdLqVB074q9yXRA/_buildManifest.js
https://nodejs.org/_next/static/fBjW_rjdLqVB074q9yXRA/_ssgManifest.js

![Screenshot from 2023-03-13 13-01-12](https://user-images.githubusercontent.com/26471/224819085-45b4cd4f-a42f-41db-873b-b51a76bb9f40.png)

**Comment by anonrig** [comment]
Due to:

```
Refused to execute https://nodejs.org/_next/static/fBjW_rjdLqVB074q9yXRA/_ssgManifest.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.
```

**Comment by andersk** [comment]
The server is serving an HTML 404 error at these URLs—the root problem is that they’re 404ing, not that they’re HTML.

**Comment by ovflowd** [comment]
@andersk could you please hard-refresh the page (invalidate the cache). You might have opened the website exactly when it was being re-uploaded/cache-invalidated. Somehow your HTML is cached because these assets do not exist anymore.

It might be an issue due to the aggressive caching that Cloudflare is doing.

**Comment by andersk** [comment]
I’ve done many Shift+reloads over the last hour—still seeing the same issue in multiple browsers and even on my phone.

**Comment by andersk** [comment]
I tried connecting from multiple locations using a VPN:

* New York City: always broken
* San Jose: always broken
* Houston: works on half of reloads, broken on half of reloads

**Comment by ovflowd** [comment]
Seems that Cloudflare is force caching on their side, we can try a manual purge. This probably happened because the cache invalidation on CF happened at the same time a build was being deployed.

**Comment by ovflowd** [comment]
Cache finally got invalidated. @andersk could you check?

**Comment by andersk** [comment]
It’s still broken on some reloads.

```console
$ curl -s 'https://nodejs.org/en/' | grep -o '<script src="[^"]*_ssgManifest\.js"[^>]*>'
<script src="/_next/static/O71PQ_afrf8cngNPTsMGe/_ssgManifest.js" defer="">
$ curl -s 'https://nodejs.org/en/' | grep -o '<script src="[^"]*_ssgManifest\.js"[^>]*>'
<script src="/_next/static/8u3fXbkprqfjs4RJ9uG9G/_ssgManifest.js" defer="">
$ curl -s 'https://nodejs.org/en/' | grep -o '<script src="[^"]*_ssgManifest\.js"[^>]*>'
<script src="/_next/static/O71PQ_afrf8cngNPTsMGe/_ssgManifest.js" defer="">
$ curl -s 'https://nodejs.org/en/' | grep -o '<script src="[^"]*_ssgManifest\.js"[^>]*>'
<script src="/_next/static/O71PQ_afrf8cngNPTsMGe/_ssgManifest.js" defer="">
$ curl -s 'https://nodejs.org/en/' | grep -o '<script src="[^"]*_ssgManifest\.js"[^>]*>'
<script src="/_next/static/O71PQ_afrf8cngNPTsMGe/_ssgManifest.js" defer="">
$ curl -s 'https://nodejs.org/en/' | grep -o '<script src="[^"]*_ssgManifest\.js"[^>]*>'
<script src="/_next/static/8u3fXbkprqfjs4RJ9uG9G/_ssgManifest.js" defer="">
$ curl -s 'https://nodejs.org/en/' | grep -o '<script src="[^"]*_ssgManifest\.js"[^>]*>'
<script src="/_next/static/O71PQ_afrf8cngNPTsMGe/_ssgManifest.js" defer="">
$ curl -s 'https://nodejs.org/en/' | grep -o '<script src="[^"]*_ssgManifest\.js"[^>]*>'
<script src="/_next/static/8u3fXbkprqfjs4RJ9uG9G/_ssgManifest.js" defer="">
$ curl -s 'https://nodejs.org/en/' | grep -o '<script src="[^"]*_ssgManifest\.js"[^>]*>'
<script src="/_next/static/O71PQ_afrf8cngNPTsMGe/_ssgManifest.js" defer="">
```

The `8u3fXbkprqfjs4RJ9uG9G` URL works, the `O71PQ_afrf8cngNPTsMGe` URL 404s.

**Comment by nschonni** [comment]
I was seeing the earlier issue after hard refresh, but hard refreshing now is showing it for me

**Comment by ovflowd** [comment]
It feels like, indeed, a caching problem, to be honest. This might have no real solution for the time being. As we might need to either a) reassess our current cloudflare caching or b) wait for adopting vercel and use their own cache strategies
