### ISSUE TITLE
404 Page doesn't show in the same

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#5124]
### URL:

https://nodejs.org

### Browser Name:

N/A

### Browser Version:

N/A

### Operation System:

N/A

### How to reproduce the issue:

# Senarios:

## Senario 1：Customized a wrong URL under the base language code 'en'：

1. Open "https://nodejs.org/en/"
2. Customized a wrong URL (e.g: https://nodejs.org/en/dd), the 404 page will be something like this:

![image](https://user-images.githubusercontent.com/52018749/224876517-3aa15dcb-8f58-4b74-be8c-26097603afa5.png)

3. In fact, the expected one should be the localized 404 page:
![image](https://user-images.githubusercontent.com/52018749/224876664-343e4777-4eec-4457-be4c-0b42b2ab3556.png)

---
## Senario 2：Customized a wrong URL directly with another language：

1. Open "https://nodejs.org/{other existing language code}/wrongURL" [Take "https://nodejs.org/zh-cn/ccc" as an example]:
![image](https://user-images.githubusercontent.com/52018749/224877268-de0037b5-c00c-4f19-96f7-03a48dd81094.png)

2. In fact, the expected one should be the localized 404 page:
![image](https://user-images.githubusercontent.com/52018749/224877450-80b26c6e-3caf-4c84-9849-d97e5d0b6dfd.png)

---

## Senario 3：Customized a wrong URL with an unknown language code：
The effects should be the same as what we see in senario 1, take "https://nodejs.org/unknowLngCode/" as an example.

# Reasons:

1. It seems we're lacking the customized error handling for 404 pages in union (Maybe in _error.js?)
2. Maybe we should also cope with Ngnix route?

**Comment by ghost** [comment]
In the previous version of Node.js org, it seems we've processed with these problems. But for the new version....:(

Extended Questions：Should we handle customized error page rendering such as for 400/500 at least instead of using the inner next.js one?

**Comment by AugustinMauroy** [comment]
I had an idea.
An thing like this:

```jsx
// pages/404.tsx
import Link from 'next/link'
import { FormattedMessage } from 'react-intl'
export default Custom404(){
    return (
        <div>
            <h1><FormattedMessage id='component.error.title'/></h1>
            <p><FormattedMessage id='component.error.description'/></p>
            <Link><FormattedMessage id='component.error.link'/></Link>
        </div>
    );
}
```

**Comment by ghost** [comment]
> I had an idea. An thing like this:
> 
> ```js
> // pages/404.tsx
> import Link from 'next/link'
> import { FormattedMessage } from 'react-intl'
> export default Custom404(){
>     return (
>         <div>
>             <h1><FormattedMessage id='component.error.title'/></h1>
>             <p><FormattedMessage id='component.error.description'/></p>
>             <Link><FormattedMessage id='component.error.link'/></Link>
>         </div>
>     );
> }
> ```

Thanks you @AugustinMauroy.

I see, however this just outputting a fixed template page without referring the existing 404 page instead. What I want may be the existing 404 pages of diff localized languages.

And what's more: The runtime between local and server of Node.js org is quite diff:
1. For the local, maybe we can use something like "_error.js" or something to handle such errors.
2. For the server-side, maybe we don't need coding but just by Ngnix with some simple configurations?

What do you think of this? Which is better or any other better suggestions?
Waiting for more discussions :)

**Comment by ovflowd** [comment]
Why are we spending efforts updating/adding description messages to a 404 page? Folks, let's please work on higher priorities. This really feels unnecessary, in my opinion.

**Comment by ovflowd** [comment]
> In fact, the expected one should be the localized 404 page:

This is not how the 404 page "should look". Just because the old 404 page looked like that, doesn't mean the current needs to look the same.

Not to mention, that we're going very soon to change all layouts, so I don't see any point updating the current 404 page that will anyways be removed.

**Comment by AugustinMauroy** [comment]
I follow you Claudio I just say “they are an possibility”

**Comment by ghost** [comment]
> Not to mention, that we're going very soon to change all layouts, so I don't see any point updating the current 404 page that will anyways be removed.

All the layouts are soon changed? 
Any plans in details?

**Comment by ovflowd** [comment]
> All the layouts are soon changed?
Any plans in details?

It'd be great if you listened more closely to what've been planning for the last few months 😅  (Not sure how you missed all the threads and slack conversations), but anyhow, I made a discussion thread here https://github.com/nodejs/nodejs.org/discussions/5131

Closing this as not planned for now, but definitely something worth to revisit once we start working on thew new 404 page :)
