### ISSUE TITLE
"md" extension name is missing in some links

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#5126]
### URL:

https://nodejs.org/en/docs/guides/diagnostics-flamegraph/

### Browser Name:

N/A

### Browser Version:

N/A

### Operation System:

N/A

### How to reproduce the issue:

# Senarios:
1. Open the link above.
2. Click the underlined part:
![网页捕获_14-3-2023_141452_nodejs org](https://user-images.githubusercontent.com/52018749/224912113-b383b6d6-ec9f-4d0f-9d1b-dd2702584ff6.jpeg)
3. 404 Page not Found

# Reason:
The extension name ".md" is missing, actually it exists at: https://github.com/davidmarkclements/0x/blob/master/docs/production-servers.md

# Solution:
To make the link seperated from the contents of the md file and put them together in the last lines.

**Comment by AugustinMauroy** [comment]
We can close this issue !
