### ISSUE TITLE
[Question] Why there is that gradient background at the bottom of the sidebar?

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#513]
![](https://cloud.githubusercontent.com/assets/2175645/12899736/8cba2752-cebb-11e5-85cf-23993209f3bc.png)

I'm sorry, but it looks so ugly...
- Safari latest version (I think it's 9) (OS X El Capitan)
- Scrollbars are shown when scrolled.
- https://nodejs.org/dist/latest-v5.x/docs/api/
- On Google Chrome (Windows 7) the gradient is on top of the scrollbars.

**Comment by leo** [comment]
I don't like it either, but it probably indicates that there are other API categories below the visible ones.

**Comment by r-52** [comment]
@dkfiresky https://github.com/nodejs/node/pull/4748 describes your problem and a fix for it. If I use Safari with El Cap and the latest docs I can't see a gradient. 
The commit landed in the 4.x staging, but I believe there was no release between the landing of the commit and now.
/cc @silverwind

**Comment by silverwind** [comment]
The bugged gradient on Safari was fixed in https://github.com/nodejs/node/pull/4748 and the fix has been released with the 5.6.0 docs a few hours ago, so you should see it working as intended now:

![gradient](https://cloud.githubusercontent.com/assets/115237/12928933/8ea90b04-cf70-11e5-9119-c7fe4df64b6d.png)

The purpose is simply to indicate the scrollability of the sidebar, which might not be obvious because scrollbars are hidden.

**Comment by silverwind** [comment]
> On Google Chrome (Windows 7) the gradient is on top of the scrollbars.

I wasn't seeing this, could you check if it's still an issue right now?

**Comment by stevemao** [comment]
@silverwind I confirm it is on https://nodejs.org/dist/latest-v4.x/docs/api/
But not on https://nodejs.org/dist/latest-v5.x/docs/api/ anymore.
I'm on Windows 7 Chrome, oh it is on bottom not top.

**Comment by stevemao** [comment]
![node js 4 3 0 docs](https://cloud.githubusercontent.com/assets/6316590/12933964/4d92dd60-cfdf-11e5-8f2a-23ef844df481.png)

**Comment by silverwind** [comment]
@stevemao that's because the backport of https://github.com/nodejs/node/pull/4748 hasn't been released yet. It's a bit unfortunate, but we have to wait for the next LTS release for the 4.x docs.

**Comment by ghost** [comment]
Why simply showing scrollbars is not enough for indication of more content in the sidebar? It looks like overkill for me. Also the text color almost matches the gradient color (as posted in original screenshot) which makes text unreadable.

**Comment by silverwind** [comment]
> Why simply showing scrollbars is not enough for indication of more content in the sidebar?

I was going for a more "modern" style, and I think it looks cleaner without a scrollbar.

> Also the text color almost matches the gradient color (as posted in original screenshot) which makes text unreadable.

The rendering in your original screenshot was a bug. Chrome, Firefox and IE didn't show it, and I learned my lesson for not testing Safari :)

**Comment by ghost** [comment]
@silverwind

> I was going for a more "modern" style, and I think it looks cleaner without a scrollbar.

Now we got another bug. If you want to scroll on the sidebar only, it scrolls all content and after content is scrolled top till the end, sidebar starts scrolling. Same happening when you scroll bottom.
Here is a video:
![node_doc_issue](https://cloud.githubusercontent.com/assets/2175645/12959058/64fd2f10-d03d-11e5-8e55-bc0e479d55ae.gif)

As shown on the video, I'm scrolling on the sidebar side.

**Comment by silverwind** [comment]
@dkfiresky that behaviour is very browser-specific (Chromes does bubble the scroll event when the limit is reached, Firefox does not) from what I've tested, but I assume improvements can be made to have make it behave more like http://devdocs.io/node/ for example.

**Comment by silverwind** [comment]
I'm working on the scrolling issues and other misc things on the API docs's CSS.

**Comment by ghost** [comment]
@silverwind

>  http://devdocs.io/node/

They got nice scrolling, and I think they somehow prevent scrolling on areas which are not under the mouse cursor.

**Comment by silverwind** [comment]
@dkfiresky yes, I already figured out how they do it, took me some time though :wink: 

See https://github.com/nodejs/node/pull/5198 for my propsed changes.

**Comment by ghost** [comment]
Well done, @silverwind :+1:

I will close this issue as soon as your pull request will be merged.

**Comment by stevemao** [comment]
I really think `doc/api_assets` should be managed here in this repo. I know this was brought a long time ago and requires build scripts changes so yeah :)

**Comment by silverwind** [comment]
Yeah that'd be my preference as well for faster propagation of stuff like this. On the other hand, it's kind of nice that each API release has its own standalone package of docs.

**Comment by ghost** [comment]
I close this issue now, as my questions were resolved. Thanks everyone for participation.
