### ISSUE TITLE
All page title is "<title>Node.js</title>"

### ISSUE THREAD

**Issue by azu** [nodejs/nodejs.org#5141]
### URL:

https://nodejs.org/en/blog/release/v19.8.0

### Browser Name:

Chrome

### Browser Version:

111.0.5563.64

### Operating System:

macOS

### How to reproduce the issue:

1. Visit <https://nodejs.org/en/blog/release/v19.8.0>
2. See `<title>` and get "Node.js" instead of "Node v19.8.0 (Current)"

Now, Almost page title is "Node.js".

https://nodejs.org/en/
https://nodejs.org/en/about/
https://nodejs.org/en/download/
https://nodejs.org/en/docs/
https://nodejs.org/en/get-involved/
https://nodejs.org/en/blog/

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/19714/225314850-17449c95-f209-4d55-9f46-a87d2d03d48d.png">

**Comment by ovflowd** [comment]
This is not a bug. https://github.com/nodejs/nodejs.org/blob/main/components/HtmlHead.tsx#L19, it is expected to all pages to just have Node.js as title. If you want that to change, please submit a feature request.

**Comment by azu** [comment]
Fmm, Previously Node.js blog use article title. 
I think it is regression bug.
https://github.com/nodejs/nodejs.org/blob/3196bc8fbf68790dd48c4dd8292c0ddca10e932d/components/HtmlHead.tsx#L33
`og:title` use `pageTitle`.

https://www.google.co.jp/search?q=site:nodejs.org/en/blog/
https://web.archive.org/web/20230301001519/https://nodejs.org/en/

Previous

- "Node.js": https://web.archive.org/web/20230301001519/https://nodejs.org/en/
- "About | Node.js": https://web.archive.org/web/20230301130646/https://nodejs.org/en/about/
- "Node.js": https://web.archive.org/web/20230307165509/https://nodejs.org/en/blog/
- "Node v14.21.3 (LTS) | Node.js": https://web.archive.org/web/20230307132832/https://nodejs.org/en/blog/release/v14.21.3/

Probably
```
{pageTitle ? `${pageTitle} | ${siteConfig.title}` : siteConfig.title}
```

**Comment by qnighy** [comment]
Original implementation before https://github.com/nodejs/nodejs.org/pull/4991 seems to have been: https://github.com/nodejs/nodejs.org/blob/5f9862c5963a64d5887ac7925296d9769a070c96/layouts/partials/html-head.hbs#L3

**Comment by ovflowd** [comment]
I wouldn't consider that a bug, but indeed a regression. Spot on! Let me reopen this issue :)

**Comment by ovflowd** [comment]
Working on a PR. Hold tight fellas!

**Comment by azu** [comment]
@ovflowd Thanks!

Opps, I create same PR 
https://github.com/nodejs/nodejs.org/pull/5142
