### ISSUE TITLE
Formatting for release blog post downloads

### ISSUE THREAD

**Issue by richardlau** [nodejs/nodejs.org#5146]
### URL:

https://nodejs.org/en/blog/release/v19.8.1

### Browser Name:

Edge

### Browser Version:

110.0.1587.57

### Operating System:

Windows 10 Version 20H2 (Build 19042.2604)

### How to reproduce the issue:

Go to any release blog post, e.g. https://nodejs.org/en/blog/release/v19.8.1

The list of downloads has lost the line breaks:

![image](https://user-images.githubusercontent.com/5445507/225404699-7f019d9f-9944-4b62-9d97-ef543ebf128a.png)

Each entry (`<description>: <url>`) should be on its own line.

The markdown source has `<br />` tags after each entry (e.g. https://github.com/nodejs/nodejs.org/pull/5145/).

**Comment by richardlau** [comment]
Courtesy of Wayback Machine, this is what the downloads should look like (from an earlier blog post as the site was at the beginning of the month: http://web.archive.org/web/20230225150042/https://nodejs.org/en/blog/release/v19.7.0/)

![image](https://user-images.githubusercontent.com/5445507/225407019-33369f27-1482-4017-a744-34fc9164d50e.png)

**Comment by nschonni** [comment]
There is definitely something broken in the rendering. I'm wondering if a better fix would be to convert the old ones + the template to use a list for this part of the release post

**Comment by richardlau** [comment]
The source markdown's `<br />` tags are generated from https://github.com/nodejs/nodejs.org/blob/main/scripts/release-post/template.hbs.

**Comment by ovflowd** [comment]
This seems to be an issue caused due to `<br />` not being valid CommonMark. (or at least not part of the specification, meaning, it is ignored).
