### ISSUE TITLE
404 response for various Node.js downloads and pages

### ISSUE THREAD

**Issue by twyatt** [nodejs/nodejs.org#5149]
### URL:

https://nodejs.org/dist/v16.13.0/

### Browser Name:

Chrome

### Browser Version:

110.0.5481.177

### Operating System:

MacOS 12.5.1

### How to reproduce the issue:

1. Attempt to click link to download `node-v16.13.0-darwin-x64.tar.gz` from https://nodejs.org/dist/v16.13.0/
2. Expected to download file
3. Instead, get a 404 page

## Using Chome

https://user-images.githubusercontent.com/98017/225445904-84ed37a3-1702-49cd-ac4c-ff2e4b0ec383.mov

## Using command line

```
$ wget https://nodejs.org/dist/v16.13.0/node-v16.13.0-darwin-x64.tar.gz

--2023-03-15 14:19:10--  https://nodejs.org/dist/v16.13.0/node-v16.13.0-darwin-x64.tar.gz
Resolving nodejs.org (nodejs.org)... 104.20.23.46, 104.20.22.46
Connecting to nodejs.org (nodejs.org)|104.20.23.46|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-03-15 14:19:10 ERROR 404: Not Found.
```

**Comment by keithlayne** [comment]
I only tried one download, but it was a 404 as well. But https://status.nodejs.org/ is all green so I must be HTTPing wrong. 😛

**Comment by keithlayne** [comment]
More seriously, it's the gzip files that seem broken so far. The "download now" link for me (linux x64) uses the xz file...and that link works. Too bad the asdf plugin for node wants the gz version. (Probably should be using xz anyway)

**Comment by nschonni** [comment]
@ovflowd The 404 is returning the new 404 page rather than the old nginx one, so I'm not sure if the new build isn't passing through a request correctly

/cc @nodejs/build

**Comment by ovflowd** [comment]
The only file that is giving 404 is `https://nodejs.org/dist/v16.13.0/node-v16.13.0-darwin-x64.tar.gz` so far. I've tried all other files of that directory and they're working.

> The 404 is returning the new 404 page rather than the old nginx one, so I'm not sure if the new build isn't passing through a request correctly

Afaik we were always for every 404 within the server returning the Website 404. The only change we made was to also add the 404 to non-https requests.

**Comment by ovflowd** [comment]
> More seriously, it's the gzip files that seem broken so far. The "download now" link for me (linux x64) uses the xz file...and that link works. Too bad the asdf plugin for node wants the gz version. (Probably should be using xz anyway)

@keithlayne actually no, only one file is 404'ing. All other `gz` files are working.

**Comment by ovflowd** [comment]
@nodejs/build can we check why only `https://nodejs.org/dist/v16.13.0/node-v16.13.0-darwin-x64.tar.gz` this file is somehow 404'ing?

**Comment by blimmer** [comment]
I noticed that https://nodejs.org/dist/v18.13.0/node-v18.13.0-linux-arm64.tar.xz is 404ing

but these versions around it are not:
- https://nodejs.org/dist/v18.12.0/node-v18.12.0-linux-arm64.tar.xz
- https://nodejs.org/dist/v18.14.0/node-v18.14.0-linux-arm64.tar.xz
- https://nodejs.org/dist/v18.15.0/node-v18.15.0-linux-arm64.tar.xz

**Comment by keithlayne** [comment]
@ovflowd I was here becasue of this:

```
 ❯❯❯ asdf install nodejs 18.15.0
Trying to update node-build... ok
Downloading node-v18.15.0-linux-x64.tar.gz...
-> https://nodejs.org/dist/v18.15.0/node-v18.15.0-linux-x64.tar.gz
error: failed to download node-v18.15.0-linux-x64.tar.gz
-> https://nodejs.org/dist/v18.15.0/node-v18.15.0-linux-x64.tar.gz
error: failed to download node-v18.15.0-linux-x64.tar.gz

BUILD FAILED (Pop 22.04 using node-build 4.9.83-92-g23a7606c)

Binary installation failed; try compiling from source with `--compile` flag
```

So there are more problems than that one file.

**Comment by ovflowd** [comment]
@keithlayne this seems to be a CloudFlare cache issue. You can check by accessing https://direct.nodejs.org/dist/v16.13.0/ which is the direct connection to our server, and all the links there work normally.

I know this doesn't solve your issue, but I'm checking with the team what are our options.

**Comment by keithlayne** [comment]
...and that file just started serving, in the last 15 seconds.

**Comment by ovflowd** [comment]
I can also check that this is being served directly within CloudFlare with `curl -v`

```
❯ curl -v https://nodejs.org/dist/v16.13.0/node-v16.13.0-darwin-x64.tar.gz
*   Trying 104.20.22.46:443...
* Connected to nodejs.org (104.20.22.46) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
```

As `104.20.22.46` is a CloudFlare IP Address.

**Comment by ovflowd** [comment]
> https://nodejs.org/dist/v18.13.0/node-v18.13.0-linux-arm64.tar.xz

https://direct.nodejs.org/dist/v18.13.0/node-v18.13.0-linux-arm64.tar.xz seems to be working fine. So double-down a CloudFlare cache issue.

**Comment by keithlayne** [comment]
@ovflowd That is really good info, thank you! Looks like I can use that url to solve my current pain. Once I started poking around I was starting to see some CF cache headers. 

For anyone else who may run into this:

```sh
NODEJS_ORG_MIRROR=https://direct.nodejs.org/dist/ asdf install nodejs x.y.z
```

seems to work - but let's be responsible, node uses a CDN for a reason.

**Comment by ovflowd** [comment]
Please just a friendly reminder, avoid using direct.nodejs.org when possible. Our server sadly was not designed to handle the load that the web usually does to download Node.js 😅 

> seems to work - but let's be responsible, node uses a CDN for a reason.

Exactly! Thank you for your understanding 🙇

**Comment by twyatt** [comment]
Thank you for the quick response!
At least for me, the Issue appears to have been resolved (I'm now able to download the file I originally reported an issue with).

**Comment by flash1293** [comment]
Seeing similar errors:

  > Could not find org.nodejs:node:18.14.2.
    Searched in the following locations:
      - https://nodejs.org/dist/v18.14.2/node-v18.14.2-linux-x64.tar.gz

**Comment by rwaite-addland** [comment]
This also seems to be affecting the azure devops NodeTool task:

![image](https://user-images.githubusercontent.com/72087742/225607217-a4bf35ed-be77-4674-9745-6429cc75834d.png)

**Comment by ovflowd** [comment]
FYI, we're still monitoring and working on solutions here.

**Comment by cduboc91** [comment]
I have the same problem with [https://nodejs.org/dist/v16.14.0/node-v16.14.0-linux-x64.tar.gz]

**Comment by jbuettnerbild** [comment]
... and with https://nodejs.org/dist/v14.21.3/node-v14.21.3-linux-arm64.tar.gz

**Comment by ovflowd** [comment]
The download issue should be recovering now and stable. Please let us know if you still see the issue.

**Comment by jfirebaugh** [comment]
Still seeing this for https://nodejs.org/dist/v16.17.1/node-v16.17.1-linux-x64.tar.xz.

**Comment by smocherla-brex** [comment]
We're still seeing elevated error rates in the last half-hour till now for https://nodejs.org/dist/v16.6.2/node-v16.6.2-linux-x64.tar.xz

**Comment by cduboc91** [comment]
The issue is not resolved for https://nodejs.org/dist/v16.14.0/node-v16.14.0-linux-x64.tar.gz

**Comment by BioCarmen** [comment]
Still see errors for https://nodejs.org/dist/v16.18.1/node-v16.18.1-linux-x64.tar.gz

**Comment by joshua-isaac** [comment]
getting 404 for [https://nodejs.org/dist/v18.15.0/node-v18.15.0.pkg](https://nodejs.org/dist/v18.15.0/node-v18.15.0.pkg)

**Comment by ovflowd** [comment]
We're still investigating this together with CloudFlare, still monitoring.

**Comment by dgmouris** [comment]
Also getting an error from the download page (https://nodejs.org/en/download)

https://nodejs.org/dist/v18.15.0/node-v18.15.0-x64.msi is throwing a 404

Thanks for looking into this :)

**Comment by Gorcyn** [comment]
Also getting 404 for:
- https://nodejs.org/dist/v14.16.0/node-v14.16.0-linux-x64.tar.gz
- https://nodejs.org/dist/v14.16.0/win-x64/node.exe

**Comment by jhenthorn** [comment]
I'm still getting errors for: https://nodejs.org/dist/v14.19.1/node-v14.19.1.tar.xz

**Comment by pauserratgutierrez** [comment]
I'm not able to install it: https://nodejs.org/dist/v18.15.0/node-v18.15.0-x64.msi
![image](https://user-images.githubusercontent.com/73240206/225707275-6db262ac-1f4a-4a17-ac6f-485ed89f907c.png)

**Comment by dave-pike** [comment]
I'm having the same issues with node-v16.15.0-linux-x64.tar.gz

![image](https://user-images.githubusercontent.com/8517839/225720902-ec50320c-1416-43ae-b1c6-3bb2db4c0c89.png)

**Comment by Trott** [comment]
Locking to avoid more people chiming in about having the same issue. Investigation is ongoing, lots of chatter in the nodejs-build channel on the OpenJS Slack if you want to follow along, or keep checking status.nodejs.org for updates, or keep checking this issue for updates. Thanks.

**Comment by Trott** [comment]
Unlocking tentatively. New information welcome. "I'm experiencing this issue too"-type posts are less helpful at this time. We are aware that a *lot* of people are experiencing this issue. Thanks.

**Comment by mviencek** [comment]
we are experiencing this with -> https://nodejs.org/dist/v14.19.0/node-v14.19.0-linux-x64.tar.gz

**Comment by nschonni** [comment]
Might be worth updating the title and pinning this issue for now. Feel free to hide this comment if that's done

**Comment by mviencek** [comment]
https://nodejs.org/dist/v14.19.0/node-v14.19.0-linux-x64.tar.gz errors out with a 404

**Comment by mviencek** [comment]
> https://nodejs.org/dist/v14.19.0/node-v14.19.0-linux-x64.tar.gz errors out with a 404
nvm.  i am able to download now

**Comment by tniessen** [comment]
Cloudflare cached some incorrect 404 responses from our origin server in different physical locations. I've manually purged cached 404s for some popular downloads in all physical locations, but there might still be some 404 responses for certain files in certain locations. We expect these to be resolved soon.

**Comment by ttaylor29** [comment]
Our azure dev ops pipeline is working with version: 18.7.0! Thanks!

**Comment by walec51** [comment]
https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-x64.tar.gz <- still cannot be downloaded

you can download everything fom https://nodejs.org/dist/v10.16.3/ but the link above

**Comment by SiWhite** [comment]
As per @walec51 above, we are getting a 404 for: https://nodejs.org/dist/v12.18.4/node-v12.18.4-linux-x64.tar.xz  while all other files at https://nodejs.org/dist/v12.18.4/ are available

**Comment by tniessen** [comment]
@walec51 @SiWhite I have purged the cache for those files in all physical locations. (But don't actually use those versions, they have long reached end-of-life status and are unsupported. Even 14.x reaches end-of-life next month.)

As I said in [my previous comment](https://github.com/nodejs/nodejs.org/issues/5149#issuecomment-1472659075), some rarely used files, especially those belonging to outdated and unsupported Node.js versions, may be unavailable in some physical locations for a few hours.

**Comment by ovflowd** [comment]
Hey, y'all, as of now, we've done the last fixes that should have handled this incident. We're posting updates on our Status page, and we're going to follow up with a post-mortem afterwards. Thank you!

**Comment by ashsearle** [comment]
Have you changed behaviour of nodejs.org/dist to rate limit and return 403 response code off the back of this incident?  (Asking as our CI system is failing due to 403s, not 404s).

Note: 403 response code received for HEAD request.

**Comment by ovflowd** [comment]
I don't think we support HEAD requests for nodejs.org/dist. (Correct me if I'm wrong, @nodejs/build)

**Comment by ashsearle** [comment]
In case of confusion: I meant a HEAD request for a full URL to a specific .tar.gz.  AFAIK nothing in our CI system has changed (across multiple different projects)

**Comment by nschonni** [comment]
Is this from Artifactory? There is some filtering being put int place because of problems from a lot of misconfigured instances https://github.com/nodejs/build/issues/3223

**Comment by ghost** [comment]
I'm seeing 403s using Gradle (via faking an Ivy repo) both on CI and on my local development machine trying to hit nodejs.org/dist, and 404s from our Artifactory proxy.

**Comment by marclefrancois** [comment]
+1 for the gradle problem reported by @tridium-gward

**Comment by ashsearle** [comment]
> Is this from Artifactory? There is some filtering being put int place because of problems from a lot of misconfigured instances [nodejs/build#3223](https://github.com/nodejs/build/issues/3223)

Our case was from Gradle too (specifically `gradle-node-plugin`, but I'm guessing the only significance is the plugin leads to a HEAD request, not just a GET.)

**Comment by ovflowd** [comment]
We've just fixed the issue by deploying a new CF Firewall rule.

**Comment by petty** [comment]
I'm still seeing failed builds with respect to Ivy: 
```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':project-theme-default:nodeSetup'.
> Could not resolve all files for configuration ':project-theme-default:detachedConfiguration1'.
   > Could not resolve org.nodejs:node:16.19.1.
     Required by:
         project :project-theme-default
      > Could not resolve org.nodejs:node:16.19.1.
         > Could not get resource 'https://nodejs.org/dist/v16.19.1/ivy.xml'.
            > Could not GET 'https://nodejs.org/dist/v16.19.1/ivy.xml'. Received status code 403 from server: Forbidden


```

**Comment by nschonni** [comment]
> https://nodejs.org/dist/v16.19.1/ivy.xml

That's a file that has never existed on the Node.js servers. Suggest you open up an issue on the Ivy plugin, as that would be an issue for their plugin

**Comment by ghost** [comment]
@petty Are you creating your own Ivy repo? If so you need to ensure it's configured to only look for artifacts and not metadata (see metadataSources below):

```kotlin
    repositories {
      val nodeRemote = ivy {
        name = "NodeRemote"
        setUrl("https://nodejs.org/dist")
        patternLayout {
          artifact("/[revision]/[module]-[revision](-[classifier])(.[ext])")
        }
        metadataSources {
          // This isn't _actually_ an Ivy repo, so it has no metadata
          artifact()
        }
      }
      // Ensure the repo is a) only used to resolve org.nodejs and b) no other repos can provide
      // any org.nodejs artifacts
      exclusiveContent {
        forRepositories(nodeRemote)
        filter {
          includeGroup("org.nodejs")
        }
      }
    }
```

**Comment by tomzi8571** [comment]
Also got the same problem since 17.3.2023:
FAILURE: Build failed with an exception.

```
* What went wrong:
Execution failed for task ':nodeSetup'.
> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Could not resolve org.nodejs:node:12.22.6.
     Required by:
         project :
      > Could not resolve org.nodejs:node:12.22.6.
         > Could not get resource 'https://nodejs.org/dist/v12.22.6/ivy.xml'.
            > Could not GET 'https://nodejs.org/dist/v12.22.6/ivy.xml'. Received status code 403 from server: Forbidden

```

But also https://nodejs.org/dist/v12.22.6/ returns 500

**Comment by ovflowd** [comment]
@tomzi8571 as explained by @tridium-gward this is not an issue from our side. This file never existed and with the updated configuration it should now be properly handling the requests. So you have a misconfigured setup of your "Ivy"

**Comment by petty** [comment]
> @tomzi8571 as explained by @tridium-gward this is not an issue from our side. This file never existed and with the updated configuration it should now be properly handling the requests. So you have a misconfigured setup of your "Ivy"

Ok, but this configuration hasn't changed in years ... and this also broke Friday ...

**Comment by nschonni** [comment]
As a result of triaging this issue, additional blocking rules were setup in https://github.com/nodejs/build/issues/3223. This never worked, but previously didn't hard block as before @petty. This was always a misconfiguration, and won't be rolled back

**Comment by tniessen** [comment]
To add to @nschonni's explanation, this route likely returned 404 before, and your tooling might have silently ignored that particular error code. The new firewall configuration blocks requests from some misconfigured Artifactory/Gradle setups that would otherwise cause unnecessary load on our infrastructure, resulting in status code 403.

**Comment by petty** [comment]
Ok, all good ... I just needed a newer version of the Gradle Node plugin (specifically moving from 1.3.0 to 1.5.3).

```
-    id 'com.github.node-gradle.node' version '1.3.0'
+    id 'com.github.node-gradle.node' version '1.5.3'

**Comment by cjiga** [comment]
The same problem with version: v10.15.3

`What went wrong:
Execution failed for task ':carelogic-webapp:nodeSetup'.
> Could not resolve all dependencies for configuration 'detachedConfiguration1'.
   > Could not resolve org.nodejs:node:10.15.3.
     Required by:
         com.qualifacts.carelogic:carelogic-webapp:276.01
      > Could not GET 'https://nodejs.org/dist/v10.15.3/ivy.xml'. Received status code 403 from server: Forbidden`

**Comment by ovflowd** [comment]
@cjiga please, read prior comments before posting here.

**I'm locking this issue to avoid duplicated comments and pings to the people here.**
