### ISSUE TITLE
Stable Node.js ARMv6 download link missing.

### ISSUE THREAD

**Issue by zen-crab** [nodejs/nodejs.org#515]
Page: [https://nodejs.org/en/download/stable/](https://nodejs.org/en/download/stable/)

Clicking "ARMv6" results in a 404.

[https://nodejs.org/dist/v5.6.0/node-v5.6.0-linux-armv6l.tar.xz](https://nodejs.org/dist/v5.6.0/node-v5.6.0-linux-armv6l.tar.xz)

**Comment by wonderdogone** [comment]
Yea it looks like those builds are literally missing. I filed an issue with the build group to see if maybe they just did not make it over or at least we can see if they built successfully already.

https://github.com/nodejs/build/issues/326

**Comment by rvagg** [comment]
Yeah, armv6l binaries are waiting in staging, must have not quite been finished when 5.6.0 was released (which we do allow to happen occasionally). This'll have to wait until @jasnell is awake and able to promote the builds, they can only be promoted and signed by the individual doing the release.

In the meantime, you can fetch the exact binaries from Jenkins which makes its own copies during build: https://ci.nodejs.org/job/iojs+release/389/nodes=pi1-raspbian-wheezy/

**Comment by wonderdogone** [comment]
Once these get promoted the website links will work so I will wait a few hours (until I wake back up for real) and if we still have not seen them promoted I can consider pr to update the website links to be direct to jenkins. I just dont want to do it now if it's going to be all fixed in the morning and avoid the revert back again.

**Comment by rvagg** [comment]
It's 2am for James, so give him a bit of time.

**Comment by jasnell** [comment]
Promoted! Sorry for the delay. Had been planning to get it done last night but I succumbed to the cold medicine and crashed early.

**Comment by jasnell** [comment]
(I'll update the blog posts a bit later this morning)

**Comment by wonderdogone** [comment]
Awesome. It's all working now

**Comment by rvagg** [comment]
@jasnell I have done exactly the same thing with these builds in the past, on multiple occasions, sans the cold medicine. "I'll do that later when it builds" then I get a ping on GitHub or Twitter or email from a user who can't find them. Given this pattern and the fact that the downloads page doesn't care whether they exist or not but still links to them I think we might need to enshrine in the release process that you have to wait for armv6l to finish.

**Comment by jasnell** [comment]
I think that would be a good idea.

**Comment by wonderdogone** [comment]
you mean wait for armv6l to release officially or announce on website? Maybe thats the same thing?

**Comment by wonderdogone** [comment]
but yes I agree with you @jasnell

**Comment by jasnell** [comment]
Wait for the arm release builds to complete before promoting and
announcing, so it's done all at once.

**Comment by wonderdogone** [comment]
i mean really whats the process of letting the website "people" know that an update is ready and to be posted? It seems really manual to me.  Maybe if thought about we could make it so that when Jenkins actually finishes all builds it creates a github issue/email/whatever or something via api to alert web teams to update?

**Comment by jasnell** [comment]
Yes, it is very manual right now. Some sort of notification would be very
good, I think.

**Comment by wonderdogone** [comment]
probably  should do another thread to keep discussion but maybe a "status" page that feeds/api from jenkins? Im just not sure how the details of the Jenkins workflow. Assuming the builds are scripted to create a new directory in /dist, possibly we can fire of a trigger from jenkins with each new build that allows said status page to be monitored for releases?
