### ISSUE TITLE
node.lib download links for v19.8.1 (win-x86 and win-x64) are broken

### ISSUE THREAD

**Issue by tdcosta100** [nodejs/nodejs.org#5150]
### URL:

https://nodejs.org/download/release/v19.8.1/win-x64/node.lib

### Browser Name:

Microsoft Edge

### Browser Version:

110.0.1587.69

### Operating System:

Windows 11, 22H2, 22621.1413

### How to reproduce the issue:

1. What I did: tried to download node.lib, both [win-x86](https://nodejs.org/download/release/v19.8.1/win-x86/node.lib) and [win-x64](https://nodejs.org/download/release/v19.8.1/win-x64/node.lib) versions
1. What I expected to happen: download these files
1. What I actually got: an error 404 page

Screenshots:

1. When I'm at https://nodejs.org/download/release/v19.8.1/win-x86/
![image](https://user-images.githubusercontent.com/708549/225523903-38f29b66-8ebd-408f-b850-fc26d23ac8af.png)

1. When I click in `node.lib` link:
![image](https://user-images.githubusercontent.com/708549/225523995-7e120e95-eaae-4077-a07c-ae7ef9782342.png)

1. When I'm at https://nodejs.org/download/release/v19.8.1/win-x64/
![image](https://user-images.githubusercontent.com/708549/225524039-856ae159-69c1-4b7d-b9ae-9410a79589a0.png)

1. Whem I click in `node.lib` link:
![image](https://user-images.githubusercontent.com/708549/225524089-ce90896e-2d20-4c6a-a542-26ad31e75a5d.png)

**Comment by ghost** [comment]
PS：Wired！I cannot reproduce this issue yet.
I'm with the latest version of Windows 10, with the latest version of Edge.

Similar to https://github.com/nodejs/nodejs.org/issues/5149.

**Comment by ghost** [comment]
@tdcosta100 : What about directly clicking the link —— https://nodejs.org/download/release/v19.8.1/win-x64/node.lib

I started to download the file on my PC. So you'are still having 404?

**Comment by ovflowd** [comment]
Closing as duplicate of #5149

**Comment by tdcosta100** [comment]
It's working now, thanks!
