### ISSUE TITLE
Download v18.15.tar.xz fails

### ISSUE THREAD

**Issue by iwanttobefreak** [nodejs/nodejs.org#5151]
### URL:

https://nodejs.org/download/release/v18.15.0/node-v18.15.0-linux-x64.tar.xz

### Browser Name:

curl

### Browser Version:

7.88.1

### Operating System:

debian

### How to reproduce the issue:

curl https://nodejs.org/download/release/v18.15.0/node-v18.15.0-linux-x64.tar.xz

**Comment by ghost** [comment]
Similar to : https://github.com/nodejs/nodejs.org/issues/5149

**Comment by ovflowd** [comment]
Duplicate of #5149
