### ISSUE TITLE
Node some Previous Releases files have disappeared

### ISSUE THREAD

**Issue by georgina1278** [nodejs/nodejs.org#5152]
### URL:

https://nodejs.org/dist/v16.14.0/node.exe

### Browser Name:

Chrome

### Browser Version:

111.0.5563.65

### Operating System:

Windows 10

### How to reproduce the issue:

I went to the following URLs and 404 error was throw:
https://nodejs.org/dist/v16.14.0/win-x64/node.exe
https://nodejs.org/dist/v16.14.0/node.exe

Yesterday all went well.

Thanks

**Comment by ovflowd** [comment]
Duplicate of #5149
