### ISSUE TITLE
Broken "announcements" links

### ISSUE THREAD

**Issue by siimots** [nodejs/nodejs.org#5156]
### URL:

https://nodejs.org/en/blog/year-2022/

### Browser Name:

MS Edge

### Browser Version:

111.0.1661.41

### Operating System:

Windows 10

### How to reproduce the issue:

Browse blog post links:
https://nodejs.org/en/blog/year-2022/

Most links work, but all links with "Announcements" are broken and result 404:
https://nodejs.org/en/blog/Announcements/nodejs16-eol/
https://nodejs.org/en/blog/Announcements/v19-release-announce/

Some links can be fixed lowercase "announcements", but not all.
https://nodejs.org/en/blog/announcements/v19-release-announce/ -> OK
https://nodejs.org/en/blog/announcements/nodejs16-eol/ -> Broken

**Comment by ovflowd** [comment]
@siimots the links are working here for me.

**Comment by siimots** [comment]
![image](https://user-images.githubusercontent.com/7014925/225651572-4c650649-c4e6-4052-8519-d9d4e1aa9376.png)

**Comment by siimots** [comment]
Tried in incognito also:
![image](https://user-images.githubusercontent.com/7014925/225653131-19132035-4db4-4ac7-8079-0ed671b5584c.png)


Very strange.
CDN or nginx problem?

Lowercase "announcements" is now broken also, which worked fine 1 hour ago.
https://nodejs.org/en/blog/announcements/v19-release-announce/

**Comment by ovflowd** [comment]
You have an uppercase "a" on your "announcements". But yes, right now we're diagnosing some nginx shit.

**Comment by siimots** [comment]
Everybody has uppercase "a" on "announcements".
![image](https://user-images.githubusercontent.com/7014925/225662939-081be9ab-ec35-4252-949d-193f7d2d28d9.png)

**Comment by ovflowd** [comment]
> Everybody has uppercase "a" on "announcements".

Uh, that's weird. Gonna make a PR.

**Comment by ovflowd** [comment]
Fixed by #5158

**Comment by siimots** [comment]
Thank you for quick fix!
