### ISSUE TITLE
`dist/v14.18.3/node-v14.18.3-linux-x64.tar.gz` is inaccessible

### ISSUE THREAD

**Issue by HappyRashair** [nodejs/nodejs.org#5157]
### URL:

https://nodejs.org/dist/v14.18.3/node-v14.18.3-linux-x64.tar.gz

### Browser Name:

Chrome

### Browser Version:

 111.0.5563.65

### Operating System:

Windows 11 22H2 22621.1413

### How to reproduce the issue:

When loading https://nodejs.org/dist/v14.18.3/node-v14.18.3-linux-x64.tar.gz, the file is inaccessible (404 status). 
This breaks our Docker build pipeline and it was working yesterday.

**Comment by ovflowd** [comment]
Duplicate of #5149
