### ISSUE TITLE
The selected main menu's arrow style is somehow missing/occuring

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#5160]
### URL:

https://nodejs.org/en

### Browser Name:

N/A

### Browser Version:

N/A

### Operating System:

N/A

### How to reproduce the issue:

1. Open the website.
2. Click any menu item such as "Home", "Doc", nothing appears:
![1679118872865](https://user-images.githubusercontent.com/52018749/226087873-08c4359a-be07-4b83-ae6c-959409e4e778.png)

3. However, when you click the sub navigator menu items (at left), sometimes the selected main menu will show an arrow (notice the red-circled part):
![1679118931561](https://user-images.githubusercontent.com/52018749/226087900-c5c7a9e6-04be-4259-ba28-ddaad12ad4d8.png)

Notice:
a. This arrow WON'T APPEAR when clicking the main menu item directly.
b. For some special cases such as "About", and click "About" at left, nothing appears.

**Comment by ovflowd** [comment]
This is a new bug introduced with the removal of trailing slashes. Will work on it.
