### ISSUE TITLE
Redirect Loop when going to https://nodejs.org/

### ISSUE THREAD

**Issue by mtaul-RGA** [nodejs/nodejs.org#5163]
### URL:

https://nodejs.org/

### Browser Name:

Chrome 

### Browser Version:

111.0.5563.64

### Operating System:

Mac Ventura 13.2.1

### How to reproduce the issue:

When navigating to https://nodejs.org/ I get stuck in a redirect loop between https://nodejs.org/en/ and https://nodejs.org/en. Accessing pages such as https://nodejs.org/en/download works as expected.

**Comment by mtaul-RGA** [comment]
could this possible be related to the following commit?
https://github.com/nodejs/nodejs.org/commit/c852a0cb333109acabe03867bb7af64ffb5d2178

**Comment by ovflowd** [comment]
You might have a cached version of the website. No, that commit has nothing to do with your issue, and doesn't change anything related to `/en`. 

Redirects are done by NGINX, not this repository.
