### ISSUE TITLE
Common problems with Indonesian localization

### ISSUE THREAD

**Issue by Mr7Gabriel** [nodejs/nodejs.org#5174]
### Enter your issue on localizations here:

As I thought, this is not a bug but because the Indonesian text is too long, it can change the appearance and move the location of an object on the homepage. Do have any suggestions or anything other than shortening sentences?

https://nodejs.org/id

![Cuplikan layar 2023-03-21 193204](https://user-images.githubusercontent.com/52824834/226584693-d65f8c87-e9c8-4122-9c75-36261ba325e0.png)

**Comment by ovflowd** [comment]
The same happens with the French localization. Don't worry about that for now; we will switch layouts soon.

But if I could give a tip, I'd recommend trying to use abbreviations whenever possible.

**Comment by AugustinMauroy** [comment]
Another tip is to look at the synonyms. That's what I do for French.

**Comment by Mr7Gabriel** [comment]
> Another tip is to look at the synonyms. That's what I do for French.

Ah yeah. That's a great idea
