### ISSUE TITLE
403 forbidden download nodejs distribution request 

### ISSUE THREAD

**Issue by bruceman** [nodejs/nodejs.org#5176]
### URL:

https://nodejs.org/dist

### Browser Name:

Chrome

### Browser Version:

110

### Operating System:

MacOS

### How to reproduce the issue:

Hi team, 
We use [gradle-node-plugin](https://github.com/srs/gradle-node-plugin/tree/v1.2.0) to build our js project , it will download the Nodejs distribution package from official website : https://nodejs.org/dist, but recently we found some build failed due to 403 error when download NodeJS package.
Is there any stable issue on official website ?
If no, do we have any download limit restriction ?

thanks for your support.

**Comment by nschonni** [comment]
https://github.com/nodejs/nodejs.org/issues/5149#issuecomment-1476537829

**Comment by ovflowd** [comment]
And also https://github.com/nodejs/build/issues/3223

**Comment by ovflowd** [comment]
Closing as duplicate.

**Comment by deepy** [comment]
@bruceman see https://github.com/srs/gradle-node-plugin/issues/315 for more details, you're using an unmaintained project which was replaced by https://github.com/node-gradle/gradle-node-plugin/ in 2018
