### ISSUE TITLE
Downloads not working

### ISSUE THREAD

**Issue by Mattabat** [nodejs/nodejs.org#518]
Tried download Node.Js the regular links and the dir. Neither will download. Downloads get to say .5 of around 10mbs, then stop... Had a friend a few states away try it same thing.

**Comment by evanlucas** [comment]
Which links in particular are you trying to download that are failing?

**Comment by Mattabat** [comment]
um node.js  from the main download page
tried both v4 and 5.60  the lts and stable tried both
neither work

**Comment by MylesBorins** [comment]
I just was able to successfully download the v5.6 installer. This is odd

/cc @nodejs/build

**Comment by Mattabat** [comment]
Ya duno i can download everything else from any other sitee fine up to a few gigs in 10-20 mins but not a 10 mb download from here, really strange.

**Comment by ghost** [comment]
@Mattabat just to make sure, can you try to download from https://nodejs.org/dist/v5.6.0/ and see if the issue persists?

**Comment by Mattabat** [comment]
ya we did

**Comment by Mattabat** [comment]
so appears to be a comcast outage in a lot of place i'm to assume maybe related to that just weird i can download like 1%  at a time and then it stops

**Comment by MylesBorins** [comment]
I'm going to close for now as it appears to not be related to the project. Feel free to keep the conversation going
