### ISSUE TITLE
Unable to get to nodejs.org

### ISSUE THREAD

**Issue by HaroonSaid** [nodejs/nodejs.org#5184]
### URL:

https://nodejs.org/dist/v14.21.2/node-v14.21.2-linux-x64.tar.xz

### Browser Name:

N/A

### Browser Version:

n.a

### Operating System:

linux

### How to reproduce the issue:

We use AWS Codebuild to download the tar files and are seeing errors downloading nodejs 

```
Container] 2023/03/23 16:35:51 Running command if [ -f .nvmrc ]; then ver=$(cat .nvmrc \| sed 's/.*gallium/16.19.0/g'); n $ver; else n ${NODE_VERSION}; fi;
| installing : node-v14.21.2
| mkdir : /usr/local/n/versions/node/14.21.2
| fetch : https://nodejs.org/dist/v14.21.2/node-v14.21.2-linux-x64.tar.xz
 | curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
 | xz: (stdin): Unexpected end of input
 | tar: Unexpected EOF in archive
 | tar: Unexpected EOF in archive
 | tar: Error is not recoverable: exiting now
 |  
| Error: failed to download archive for 14.21.2
```

**Comment by stari4ek** [comment]
I am seeing other error, when trying to download nodejs signature from CircleCI:
```
+ curl -fsSLO 'https://nodejs.org/dist/v16.15.1/{SHASUMS256.txt,SHASUMS256.txt.sig}'
curl: (22) The requested URL returned error: 525
```

Works well when called from local machine.

**UPDATED:**
re-running from CircleCI UI same job - passed well (no 525)

**Comment by MattIPv4** [comment]
@ovflowd I suspect this is more of the same -- I really think bumping the ulimit on the NGINX boxes is probably the next step? And fixing the way cache purges happen? Beyond that, having two (or more) NGINX boxes in active rotation to spread the load?

**Comment by ovflowd** [comment]
Yes, I agree with you. But someone from @nodejs/build needs to increase that limit, as both of us have no access here 🤔

**Comment by MattIPv4** [comment]
I would also be curious to know if `worker_rlimit_nofile` is set anywhere in the NGINX config on the box -- I don't see it in the repo, but I'm not sure the parent NGINX config that loads everything is there at all.

**Comment by targos** [comment]
> Yes, I agree with you. But someone from @nodejs/build needs to increase that limit, as both of us have no access here 🤔

This would have to be done somewhere in the ansible config via a PR

**Comment by targos** [comment]
> I would also be curious to know if `worker_rlimit_nofile` is set anywhere in the NGINX config on the box -- I don't see it in the repo, but I'm not sure the parent NGINX config that loads everything is there at all.

`grep -r worker_rlimit_nofile /etc/nginx/` prints nothing

**Comment by MattIPv4** [comment]
Just noting there was also a user in the Cloudflare Discord noting they'd got a 502 back from a Node.js 16 download this morning.

**Comment by ovflowd** [comment]
I'm closing this as wontfix for now. @MattIPv4 could you open an issue on build regarding this setting and the ulimit stuff?
