### ISSUE TITLE
Migrate `CommonComponents` from `nodejs.dev`

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5193]
To kick off the migration of Components from the `nodejs.dev` repository, we should start migrating the [`CommonComponents`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents) from the `nodejs.dev` repository.

This issue will keep track of these components and their development progress. ~Remember that https://github.com/nodejs/nodejs.org/issues/5191 should be done first, as we want to migrate Components and add Storybooks for them.~

### The Migration of each Component

- Each Component should go under `components/Common` folder on this repository
- Each Component has its sub-folder (e.g., `components/Common/Banner`)
- The folder structure should pretty much be the same (CSS components, React, and sub-components), but feel free to make changes if you see deemed
- Please add some if the Component does not have unit tests already. At least to ensure the Component is rendering. If the Component has states/CTAs (Buttons/Triggers), please cover them too.
- The Storybook of each component should allow interaction with all possible states of the Component
- If the Component depends on Hooks, please migrate them too, with the following caveat:
  - If that component only uses the Hook, move it to the same folder of the Component
  - Otherwise, migrate it to the `hooks` folder of the repository.
- If the Component has a Gatsby-specific logic (e.g. `Dark Theme Switcher`), if it is straightforward enough (e.g. a dark theme switcher plugin for Next.js or it is simple enough to code by ourselves, e.g. a Hook that we manage together with a React Provider) then feel free to do it.
  - Otherwise, if you have questions, please ask them on this Issue or your Draft PR for the Component.

## List of Components to Migrate

- [x] [`AnimatedPlaceholder`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents/AnimatedPlaceholder) @HinataKah0
- [x] [`Banner`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents/Banner) @manishprivet
- [x] [`DarkModeToggle`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents/DarkModeToggle) @shanpriyan
- [x] [`Dropdown`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents/Dropdown) @ktssr
- [x] [`LanguageSelector`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents/LanguageSelector) @ktssr
- [x] [`RandomContributor`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents/RandomContributor) @ovflowd
- [x] [`SectionTitle`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents/SectionTitle) @araujogui
- [x] [`ShellBox`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents/ShellBox) @AugustinMauroy

### Components **not** to migrate

- [Hero](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents/Hero)
  - The Hero Component will be directly part of the Home-page Layout and will be migrated afterwards once we start designing the Home Layout (It will reside under `components/Home`)
- [SearchBar](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents/SearchBar)
  - The Search Bar component is complex and requires first content-indexing, which probably requires SSR. Nevertheless, a dedicated issue will be opened for the component so that research and development might be completed.
- [SEO](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents/SEO)
  - The SEO component is obsolete and does not require a counterpart here as we already have a replacement.

**Comment by AugustinMauroy** [comment]
Can I Take random Contributor ?

**Comment by ovflowd** [comment]
You can, but I also wanted to work on that, mostly because I want to simplify the monster logic from https://github.com/nodejs/nodejs.dev/blob/main/src/hooks/useNodeJsContributorsApi.tsx#L147.

**Comment by AugustinMauroy** [comment]
Oh ok do it claudio . I will do Shellbox.

**Comment by shanpriyan** [comment]
I will start with `DarkModeToggle`

**Comment by ovflowd** [comment]
Friendly reminder that https://github.com/nodejs/nodejs.org/issues/5191 needs to be done first.

**Comment by harshitphoenix** [comment]
I will be working on Dropdown component

**Comment by manishprivet** [comment]
I can work on the `Banner` component here

**Comment by araujogui** [comment]
I'll work on `SectionTitle` component

**Comment by ovflowd** [comment]
Hey @manishprivet @shanpriyan @harshitphoenix @AugustinMauroy any updates on the development of your components?

**Comment by AugustinMauroy** [comment]
Problem with global CSS (old css) and module css.

**Comment by ovflowd** [comment]
> Problem with global CSS (old css) and module CSS.

CSS modules should be working out of the box. What issues are you facing?

**Comment by shanpriyan** [comment]
@ovflowd working on it

**Comment by manishprivet** [comment]
I'm working on it as well

**Comment by ktssr** [comment]
Are there any components that are not being worked on available for me to pick?

**Comment by harshitphoenix** [comment]
> Hey @manishprivet @shanpriyan @harshitphoenix @AugustinMauroy any updates on the development of your components?

I am working on it as well.

**Comment by manishprivet** [comment]
@ktssr I believe `LanguageSelector` hasn't been picked up yet

**Comment by ktssr** [comment]
> @ktssr I believe `LanguageSelector` hasn't been picked up yet

But I see the language selector in the header after setting up the project.
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/31731919/230020247-015d667d-c2c4-484c-90b7-bdcd6a9e024b.png">

**Comment by ovflowd** [comment]
@ktssr I believe you're mistaking things. The current nodejs.org website that you see is the legacy one :)

This Issue is about working on the migration of new components from nodejs.dev, please read https://github.com/nodejs/nodejs.org/discussions/5131 first.

**Comment by rodion-arr** [comment]
@ovflowd, could you please update in the top post who is working on what component? It will be much easier to see grouped info there rather that scanning through comments

**Comment by ktssr** [comment]
Thank you, @ovflowd, for pointing out that I was on the wrong branch. I realized I should have checked out major/website-redesign instead of staying on the main branch.

**Comment by ovflowd** [comment]
@ktssr sure, but it's important to mention the `major/website-redesign` still contains the old components that will eventually be removed. The plan right now is to only add the new components within the codebase with their unit tests and storybooks, since they will not be embedded anywhere for now.

**Comment by ovflowd** [comment]
> @ovflowd, could you please update in the top post who is working on what component? It will be much easier to see grouped info there rather that scanning through comments

I'm usually not much keen on assigning tasks to named people as it discourages other people to tackle them. It's common for people to say they're working in smth and then abandon it. But let make an exception based on good faith here.

**Comment by ktssr** [comment]
I got it, @ovflowd  I'll take charge of the LanguageSelector component.

**Comment by HinataKah0** [comment]
If no one is working on `AnimatedPlaceholder`, I'll be happy to help (I have some free time later this week). 😄 

Edit:
Just read this [comment](https://github.com/nodejs/nodejs.org/issues/5193#issuecomment-1497175600), please feel free to tackle it as well if you have done the PR.

**Comment by ovflowd** [comment]
@HinataKah0 no worries, you can work on the Component :)

**Comment by ktssr** [comment]
I seem to be having difficulty locating the language selector within Figma Designs. Would anyone be able to assist me in identifying the appropriate icon for a redesign?

**Comment by ovflowd** [comment]
@ktssr the component already exists. You don't need to make a new one. Please read the migration guides (description of this issue).

You only ned to migrate the existing code from the `nodejs.dev` repository into here. All details are explained above 👀

**Comment by ovflowd** [comment]
Note that migrating might also include the need of adding packages that existed from `nodejs.dev` such for icons, and also migrating hooks and other components. But that's all described on the issue description!

**Comment by ktssr** [comment]
@ovflowd. I understand that the existing code needs to be migrated. I just want to confirm that the icon used in the old website will remain the same in the new one. Thanks for the confirmation

**Comment by ovflowd** [comment]
@ktssr, the icon to be used is the icon used on nodejs.dev. The nodejs.org website should eventually have a 1:1 match of that design. But if you're in doubt, opening a draft PR asking that there rather than here would be better. Otherwise, this issue gets too polluted 🙇 

Of course, you're free to make CSS tweaks, functionality tweaks or even propose a different icon, which we can review altogether. You can even propose a different icon library (if they provide all the icons we need)

**Comment by ovflowd** [comment]
@araujogui can you make a simple PR adding https://storybook.js.org/addons/storybook-addon-sass-postcss to the Storybook Addons? Basically each PR is implementing it, and it feels like this should have been done on the Storybook PR. Thank you 🙇

**Comment by araujogui** [comment]
> @araujogui can you make a simple PR adding https://storybook.js.org/addons/storybook-addon-sass-postcss to the Storybook Addons? Basically each PR is implementing it, and it feels like this should have been done on the Storybook PR. Thank you 🙇

I did some local tests, without `storybook-addon-sass-postcss`, and it is working as expected, sass modules works [out of the box](https://github.com/storybookjs/storybook/blob/next/code/frameworks/nextjs/README.md#csssassscss-modules). However, CSS classes names must be camel case.

**Comment by ovflowd** [comment]
Hey, y'all 👋 let's remove the addon from the PRs then (cc @AugustinMauroy @manishprivet @shanpriyan)

**Comment by AugustinMauroy** [comment]
> Hey, y'all 👋 let's remove the addon from the PRs then

Why ?

**Comment by ovflowd** [comment]
> > Hey, y'all 👋 let's remove the addon from the PRs then
> 
> Why ?

Because we don't sem to need this addon. As @araujogui explained Sass works out of the box on Storybook. The addon is probably needed for the snake_case/kebab-case conversion to camelCase, which we don't need if we simply rename the CSS class names (I assume)

**Comment by ovflowd** [comment]
Hey, @ktssr did you have any progress on your component? 👀 eager to see what you have done!! :D

**Comment by ktssr** [comment]
> Hey, @ktssr did you have any progress on your component? 👀 eager to see what you have done!! :D

Will raise PR in couple of hours

**Comment by ktssr** [comment]
> > Hey, @ktssr did you have any progress on your component? 👀 eager to see what you have done!! :D
> 
> Will raise PR in couple of hours

I was occupied with other priorities hence could not raise PR. I will raise it some time tomorrow

**Comment by ovflowd** [comment]
All fine, no rush!

**Comment by ktssr** [comment]
> All fine, no rush!

Raised the pr
https://github.com/nodejs/nodejs.org/pull/5266
