### ISSUE TITLE
index_md anchor links (# appearing onhover on headings in nodejs.org) are missing. 

### ISSUE THREAD

**Issue by bogas04** [nodejs/nodejs.org#52]
These anchor links are neat way of referring to a section of a page on social networks/forums. They are missing on new.nodejs.org 

Screenshot from nodejs.org:

![screen shot 2015-08-27 at 9 28 14 pm](https://cloud.githubusercontent.com/assets/6177621/9525617/9080e24e-4d02-11e5-8230-f19f67fbb3c4.png)

**Comment by fabiosantoscode** [comment]
Expect a solution soon, gonna work on this.

**Comment by phillipj** [comment]
Fixed with 294af4f
