### ISSUE TITLE
Search Functionality on the Website

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5204]
The `nodejs.dev` repository currently supports indexing and search of its content through a [`SearchBar`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents/SearchBar) Component.

This repository does not support indexing its content simply because no code was written. The [Nextra Docs Theme](https://nextra.site/docs/docs-theme) supports it through [FlexSearch](https://github.com/nextapps-de/flexsearch), and it has been done through [this](https://github.com/shuding/nextra/blob/main/packages/nextra-theme-docs/src/components/flexsearch.tsx) component.

As I recall, the maintainer of Nextra (@shuding) wanted to get rid of Flexsearch and adopt [Orama](https://github.com/oramasearch/orama), which honestly sounds super elegant.

We could integrate Orama on our current stack as a replacement for `flexsearch`.

### A few things to keep in mind

- Orama uses in-memory databases
- The indexing of the database should be done during build-time
- We should limit what we want to index, to begin with.

## Implementing Search functionality with Orama.

To get started, we need to understand how Orama works and leverage its API (https://docs.oramasearch.com/usage/create) to tokenise what we want users to be able to search through the website.

- Data is gathered during build-time and should leverage raw Markdown content (before tokenisation). We should be able to get the raw text of each page through Nextra's API
- Nextra also provides the entire tree of each document, including its Headings. We should also leverage that.
- Orama Search is Language-based, which is fantastic because it allows linguistic analysation of the content. For the first version, we should only support English stemming/tokenisation.
- We should heavily limit what sort of content we want to index. For starters, blog posts should not be indexed at all.
- All remaining Frontmatter properties of each document should be added to the search result, as we want to build a visually exciting search context. (E.g. if the content is a guide, have a "guide" label).

### Defining the Data Schema

As the first part of the work, the schema of what we want to be stored by the in-memory store needs to be decided; For example, should we store a whole raw (with stripped HTML tags and trimmed) version of each page? Or should we only tokenise all the headings? Would that be good enough for you?

The remainder of the fields are likely obvious; we should select a handful of Frontmatter properties we want to index, such as title, headings, layout name, filename, etc.

### Creating a Script

**The build-time script should do a few things:**

- Iterate through all content we want to be searchable, ingesting it.
- Produce an output JSON file that can be used both by Client-Side Rendering and Server-Side Rendering
  - The JSON file would reside around `public/search.json`

### Consuming the data

- The consuming of the data should be asynchronous and lazy, done by a React Hook
- The Hook creates the schema and consumes the JSON file through [`SWR`](https://swr.vercel.app/)
  - SWR can both be used on an SSR/CSR fashion
  - The data is built during the Component Mount and is indexed asynchronously
  - This benefits from Next.js's Single-Page Application
- The Hook returns a function that allows the data to be searched through
- The Hook could also read/tap into i18n data to understand in which language it should present the content

### Creating the `SearchBar` Component

Once the Hook is done, we can tap into it and migrate the [`SearchBar`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents/SearchBar) Component and replace all Gatsby-specific bindings.

**Comment by micheleriva** [comment]
Hi @ovflowd, Orama creator here 🙂 

If you're willing to use Nextra for the nodejs.org website, I already have the search component ready with Orama.

Otherwise, I'll do my best to support you while creating the search feature for this website. I was already planning to propose this with my former team at NearForm (@shogunpanda, @RafaelGSS, @marco-ippolito, they're all Node.js core contributors), and we all contributed to Orama, so there's a lot of know-how already around it!

Please let me know how you'd like to proceed. I'd be humbled to help you with this!

**Comment by ShogunPanda** [comment]
Orama co-founder here! :)
@ovflowd, this is just over-amazing. As Michele said, let me know how can I help you here so we can land this :)

**Comment by ovflowd** [comment]
Hey, @micheleriva, we're using Nextra already 👀 how can we integrate Orama? :D

**Comment by ShogunPanda** [comment]
@ovflowd 

Orama docs are based on NExtra.
You can see them in action at: https://docs.oramasearch.com
The related source code is here: https://github.com/oramasearch/orama/tree/main/packages/docs

**Comment by ovflowd** [comment]
I see, thanks @ShogunPanda! I'd like to point out we use a complete custom Nextra theme, not their default docs theme.

I'm going to give a 👀 to the code on oramasearch docs soon :)

**Comment by micheleriva** [comment]
@ovflowd the Orama docs search component has been made by me in like 3hrs, so it's not the best implementation you will find 😄 but I can allocate more time to build a general purpose, multi-language component for Nextra and then open a PR to it (cc. @shuding wdyt?)

As an alternative, I can open an issue here and have one or more colleagues working on it for the nodejs.org website specifically. Nextra makes things incredibly simple for developers when it comes to implementing search, so I guess we can make it in a few days!

**Comment by ovflowd** [comment]
Hey, @micheleriva, thanks for the insights! Honestly speaking it'd be amazing if you could make a generally purpose plugin for Nextra, as this would give back to the outer community 🙇 

And then, if you'd like, you could implement it over here. I could go over the details with you :)

(This issue should pretty much describe most of the details, but It'd be more than happy to chat over Slack 🙇)

**Comment by micheleriva** [comment]
> Hey, @micheleriva, thanks for the insights! Honestly speaking it'd be amazing if you could make a generally purpose plugin for Nextra, as this would give back to the outer community 🙇

totally agree, I'm on it!

**Comment by micheleriva** [comment]
Hi folks, quick update: the plugin is in the work as an officially Orama-supported plugin. I don't have an ETA for it to be ready yet, but please let me know if you need it soon, so I can allocate someone's time to help me speed this up.

https://github.com/oramasearch/orama/pull/344

**Comment by ovflowd** [comment]
Update: The folks from Orama are doing some really good stuff with their Nextra integration. Had the pleasure of meeting @ShogunPanda and @micheleriva at the NodeCongress Conference, and I'm really excited about this!

**Comment by ematipico** [comment]
Hey, I'd like to help on this one if possible. Is there an opportunity?

**Comment by ovflowd** [comment]
@ematipico there's a PR open already :)
