### ISSUE TITLE
Yellow text on white background is hard to read

### ISSUE THREAD

**Issue by laggingreflex** [nodejs/nodejs.org#522]
The strong yellow #a2bd01 link text color on white background is a little difficult on the eyes

![](http://i.imgur.com/2EuXOoP.png)

It might work better with a dark background:

![](http://i.imgur.com/UuKc1pZ.png)

**Comment by stevemao** [comment]
I didn't notice that :open_mouth: I thought it was green colour :confused:

**Comment by fhemberger** [comment]
@stevemao It _is_ green. ;) But yes, it hasn't a good contrast ratio, we should pick a different color.

**Comment by kahwee** [comment]
I'm sorry you're having difficulty with reading the documentation. I didn't find `#a2bd01` (yellow) in our documentation CSS. The closest I can find is `#80BD01`.

Related to #501

**Comment by laggingreflex** [comment]
Yup, it seems I got the color wrong but that's the exact same issue, thanks for pointing out. Closing this one then.
