### ISSUE TITLE
Download link currently hardcodes x86 for Windows

### ISSUE THREAD

**Issue by magcius** [nodejs/nodejs.org#5221]
### URL:

https://nodejs.dev/en/download/

### Browser Name:

Firefox

### Browser Version:

111.0.1 (64-bit)

### Operating System:

Windows 10 64-bit

### How to reproduce the issue:

https://github.com/nodejs/nodejs.org/blob/43eedbcc8cecb13a2ad8c4af7eecb452c14a09e5/components/Downloads/PrimaryDownloadMatrix.tsx#L56-L72

This currently hardcodes Windows x86. I would expect to download an x64 build of nodejs when browsing from a 64-bit version of Windows.

**Comment by ovflowd** [comment]
> This currently hardcodes Windows x86. I would expect to download an x64 build of nodejs when browsing from a 64-bit version of Windows.

That's incorrect. Yes, the React template hardcodes to x86, but we override that from [here](https://github.com/nodejs/nodejs.org/blob/main/public/static/js/legacyMain.js#L83).

Closing this issue as "won't fix". Feel free to reopen if the issue you're reporting is something else.

**Comment by nschonni** [comment]
@ovflowd this wasn't fixed in this repo, so it's something that needs to be looked at if you're implementing the components in `.org`

**Comment by ovflowd** [comment]
@nschonni, sorry, what issue are we talking about? Because I clearly remember to have implemented the Windows 11 high-entropy values [here](https://github.com/nodejs/nodejs.org/blob/main/public/static/js/legacyMain.js#L113) and we still have all the other fallback methods.

(Also the user seems to be using Windows 10 and Firefox, which should still have the other methods working at hand).

**Comment by nschonni** [comment]
Yes, the methods for the fallback work in the `.org` repo work, as pointed out in this issue, the methods in this repo do not work with Firefox

**Comment by ovflowd** [comment]
I'm not sure that's what the issue is describing, Nick. It is just saying the author thinks the code hardcodes to x86. At least I've tested Firefox on Windows and worked for me. Can you replicate the issue?

**Comment by nschonni** [comment]
Yes 
![image](https://user-images.githubusercontent.com/1297909/229632392-1e5c9155-a575-464e-963d-d24b95bc9719.png)

**Comment by ovflowd** [comment]
Nick, could you do me a favour? (If you don't mind)

What `navigator.oscpu` results on Firefox console? And what's your full user agent?

**Comment by nschonni** [comment]
`navigator.oscpu`: "Windows NT 10.0; Win64; x64" , although it's actually on Win 11
`navigator.userAgent`: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0"

**Comment by ovflowd** [comment]
Gotcha, thank you! Last debugging step, does `navigator.cpuClass` result in anything?

**Comment by ovflowd** [comment]
Because (for me at least) it is showing to download x64 (it even has a match via user agent) hence I'm not understanding why it is not working for you 🤔

**Comment by nschonni** [comment]
`navigator.cpuClass`: undefined

**Comment by ovflowd** [comment]
Still scratching my head, but will investigate deeper later. Feel free also to investigate, and play around with the code. I know you're not on the Website team anymore, but any help is definitely welcome here 🙇

**Comment by nschonni** [comment]
There was also some digging in https://github.com/nodejs/nodejs.dev/issues/3162

**Comment by magcius** [comment]
Looking at what code is loaded on nodejs.dev from Firefox, it doesn't appear like that code is used at all. I also note that it's called legacyMain.js, and that's also the filename I see loaded on nodejs.org.

The code I see loaded on nodejs.dev appears to match this code: https://github.com/nodejs/nodejs.dev/blob/889076fc0dcc22afb3417841e2a87956b5459b95/src/util/downloadUrlByOS.ts

But that repo is archived, and I can't find an equivalent in this repo?

**Comment by ovflowd** [comment]
@magcius I'm not sure why you're referring to the nodejs.dev codebase here. These are completely different websites.

But now that you mentioned, @nschonni the screenshot you attached is from nodejs.dev and I just realised that @magcius is reporting the download page of nodejs.dev but showing a nodejs.org component.

Just to make it clear, @magcius the nodejs.dev website is a completely different codebase from this repository.

I'm closing this issue as this doesn't happen on nodejs.org and nodejs.dev is archived.

**Comment by magcius** [comment]
I thought this was the place to report nodejs.dev issues, as the original repo was archived. Is nodejs.dev is not meant to be used? If so, maybe it should be taken down, or a banner should be placed to inform people it's unmaintained?

I apologize for my misleading code snippet.

**Comment by ovflowd** [comment]
> I thought this was the place to report nodejs.dev issues, as the original repo was archived. Is nodejs.dev is not meant to be used?

Nope, not the place. If nodejs.dev got archived, it got archived :)

> or a banner should be placed to inform people it's unmaintained?

There is a banner on the README.md, did you miss it? Please read the README banner, and I guess you'll understand better what's next :)

![image](https://user-images.githubusercontent.com/12037269/229732685-eec7d7ab-1895-49b9-b31d-6b3c39887655.png)

**Comment by nschonni** [comment]
@ovflowd it's just something to watch as you port the code from `.dev` into this repo, as the current setup in this repo works, but the `.dev` doesn't

**Comment by magcius** [comment]
> There is a banner on the README.md, did you miss it? Please read the README banner, and I guess you'll understand better what's next :)

I meant on https://nodejs.dev itself, if it's not meant to be used. I was redirected there from a Google search where nodejs.dev came up before nodejs.org

**Comment by ovflowd** [comment]
> @ovflowd it's just something to watch as you port the code from .dev into this repo, as the current setup in this repo works, but the .dev doesn't

Indeed, I will definitely once I/we port this part of the Components. 

> I meant on [nodejs.dev](https://nodejs.dev/) itself, if it's not meant to be used. I was redirected there from a Google search where nodejs.dev came up before nodejs.org

You can use the Website, using the website is fine. It will just not be updated and in the future nodejs.dev will redirect to nodejs.org once we complete the migration. It's all documented :)
