### ISSUE TITLE
Suggesion. Please register "node dot js" domain name.

### ISSUE THREAD

**Issue by maewnamcom** [nodejs/nodejs.org#523]
For easy to type in address bar 
Please register node.js domain name

**Comment by Trott** [comment]
`.js` is not currently a valid TLD so it is not possible to register a `.js` domain name.

**Comment by stevemao** [comment]
@aekseed did you mean node.js.com?

there is no `.js` domain as far as i know

**Comment by silverwind** [comment]
Not possible, read up on https://github.com/ozten/TLD.js/issues/8 :wink:
