### ISSUE TITLE
A section of the guide Don't Block the Event Loop (or the Worker Pool) is not displayed correctly

### ISSUE THREAD

**Issue by coder-hxl** [nodejs/nodejs.org#5230]
### URL:

https://nodejs.org/zh-cn/docs/guides/dont-block-the-event-loop#%E5%A6%82%E4%BD%95%E8%BF%9B%E8%A1%8C%E4%BB%BB%E5%8A%A1%E5%88%86%E6%B5%81

### Browser Name:

Google Chrome

### Browser Version:

111.0.5563.147

### Operating System:

Windows 10

### How to reproduce the issue:

A section of the guide Don't Block the Event Loop (or the Worker Pool) is not displayed correctly.

Screenshots:

![](https://raw.githubusercontent.com/coder-hxl/nodejs-issues-picture-bed/main/Snipaste_2023-04-04_16-58-24.png)

**Comment by AugustinMauroy** [comment]
I don't understand our problem. quand you give me more information.

**Comment by coder-hxl** [comment]
@AugustinMauroy This part of the content is not displayed properly

**Comment by ghost** [comment]
@coder-hxl ：Many many thanks for your PR of this issue, it's because sometimes when I import the translated file into Crowdin and it doesn't match the actual pharagraph that has caused this problem. Luckily this problem can be fixed through Crowdin's editor.

Now it's totally fixed.

**Comment by coder-hxl** [comment]
@MaledongGit Thanks for the fix.
