### ISSUE TITLE
Migrate `ArticleComponents` from `nodejs.dev`

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5242]
Continuing the migration of components from `nodejs.dev` that we started [here](https://github.com/nodejs/nodejs.org/issues/5193), we should start migrating the [`ArticleComponents`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/ArticleComponents) from the `nodejs.dev` repository.

This issue will keep track of these components and their development progress.

### The Migration of each Component

- Each Component should go under `components/Article` folder on this repository
- Each Component has its sub-folder (e.g., `components/Article/Banner`)
- The folder structure should pretty much be the same (CSS components, React, and sub-components), but feel free to make changes if you see deemed
- Please add some if the Component still needs to get unit tests. At least to ensure the Component is rendering. If the Component has states/CTAs (Buttons/Triggers), please cover them too.
- The Storybook of each component should allow interaction with all possible states of the Component
- If the Component depends on Hooks, please migrate them too, with the following caveat:
  - If that component only uses the Hook, move it to the same folder of the Component
  - Otherwise, migrate it to the `hooks` folder of the repository.
- If the Component has a Gatsby-specific logic (e.g. `Dark Theme Switcher`), if it is straightforward enough (e.g. a dark theme switcher plugin for Next.js or it is simple enough to code by ourselves, e.g. a Hook that we manage together with a React Provider) then feel free to do it.
  - Otherwise, if you have questions, please ask them on this Issue or your Draft PR for the Component.

## List of Components to Migrate

- [x] [`Alert`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/ArticleComponents/Alert) @araujogui 
- [x] [`AuthorList`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/ArticleComponents/AuthorList) @shanpriyan 
- [x] [`BlockQuote`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/ArticleComponents/BlockQuote) @araujogui
- [x] [`Codebox`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/ArticleComponents/Codebox) @araujogui 
- [x] [`DataTag`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/ArticleComponents/DataTag) @Olaleye-Blessing 
- [x] [`EditLink`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/ArticleComponents/EditLink) @HinataKah0

### Components to **avoid** migration for now

**Note.:** If you feel adventurous and want to migrate these components, feel free, as existing logic exists within our current Website codebase. But please keep in mind these require an understanding of Nextra and the current structure of the website (such as how we generate pagination, how we generate ToC and how we generate a list of blog posts)

- [x] [Pagination](https://github.com/nodejs/nodejs.dev/tree/main/src/components/ArticleComponents/Pagination) @ktssr 
  - The Pagination Component uses metadata specific to Gatsby's pagination system. This Component should be done later, with the same design and as much of a similar codebase as possible, but using Nextra's Pagination System (or the one we created for the current blog system).
  - This Component isn't a Pagination Component, and should be named as `PreviousNextLink`
  - This Component should be placed on `components/Learn`
  - This Component should probably have a different type definition for its Previous/Next Links instead of the current Gatsby-specific type
- [ ] [TableOfContents](https://github.com/nodejs/nodejs.dev/tree/main/src/components/ArticleComponents/TableOfContents)
  - The Table of Contents Component uses metadata specific to Gatsby's TOC system. This Component should be done later, with the same design and as much of a similar codebase as possible, but using Nextra's ToC System (Comes from Graymatter)
- [ ] [RecentPosts](https://github.com/nodejs/nodejs.dev/tree/main/src/components/ArticleComponents/RecentPosts)
  - The Recent Posts Component uses metadata specific to Gatsby. This Component should be done later, with the same design and as much of a similar codebase as possible, but using our own Blog Metadata System.

**Comment by araujogui** [comment]
I'll work on `Alert` component!

**Comment by AugustinMauroy** [comment]
I would like work on code box. 
And I want update it to fix:

<img height="450" alt="Screenshot 2021-09-17 at 11 52 05 AM" src="https://user-images.githubusercontent.com/97875033/230793485-b1d90891-6b25-4f39-8756-f03cc983ef75.jpg">

And put select lang in strong.

**Comment by ovflowd** [comment]
Sorry, @AugustinMauroy can you please finish one PR at time? Your current ShellBox PR is still in a draft state, so please finish it first before volunteering for another component. Thank you!

**Comment by AugustinMauroy** [comment]
@ovflowd  it's finish I await your review 😄.

**Comment by shanpriyan** [comment]
I will work on `AuthorList`

**Comment by HinataKah0** [comment]
I would like to work on `EditLink` since my PR is waiting to be merged :smile:

Since I'll need `@fortawesome`, do I need to submit another fast tracked PR to install it? Or can I do it in my migration PR?

**Comment by ovflowd** [comment]
You can do it on your PR. You can also use something different from FortAwesome, maybe that is more FOSS-friendly. We did have to use two different icon libraries on nodejs.dev, but we could simply use different icons/different library.

**Comment by araujogui** [comment]
Hey, working on `BlockQuote` component.

**Comment by ovflowd** [comment]
@HinataKah0 I guess it's fine to keep using FortAwesome if all the free icons are enough.

**Comment by Olaleye-Blessing** [comment]
I would like to work on `DataTag` component,

**Comment by ovflowd** [comment]
@HinataKah0 fyi I guess we're switching to `react-icons` to keep one package :)

**Comment by araujogui** [comment]
Hey, I would like to work on `Codebox` component.

**Comment by ovflowd** [comment]
Just a FYI @araujogui. I personally feel that the ShellBox and CodeBox component can be merged into one. And simply have different flavours/layouts. Feel free to experiment with that.

**Comment by ovflowd** [comment]
FYI: If anybody wants to volunteer for the `Pagination`, `TableOfContents` and `RecentPosts` components, feel free to tackle them :) (If you feel confident enough)

**Comment by ktssr** [comment]
@ovflowd  I can pick Pagination

**Comment by ovflowd** [comment]
Hey @ktssr that's great. I'd say that the Pagination Component from `Article` is more like a `PreviousNextLink` Component. Let me add instructions on the issue description.

**Comment by AugustinMauroy** [comment]
I'm working on [TableOfContents](https://github.com/nodejs/nodejs.dev/tree/main/src/components/ArticleComponents/TableOfContents).

**Comment by ovflowd** [comment]
Hey y'all, the Author Component seems to be broken. Can anybody give a look into it? https://nodejs-org-stories-r8m4tjtra-openjs.vercel.app/?path=/story/article-authorlist-author--default

Also, @araujogui or @AugustinMauroy the Codebox component got merged but I wanted a few changes:

- The copy button colour should be the same from the Shellbox one
- Can we make the buttons from Codebox to have same padding and float like the one from Shellbox 
  ![image](https://github.com/nodejs/nodejs.org/assets/12037269/cd32422b-1b24-42e6-88fe-9cbf7e881251)
- The padding-bottom? of the Codebox diverges from the Shellbox one, can we make them have the same padding?

Now, @AugustinMauroy the Shellbox copy button doesn't show the `cursor: pointer` when hovering it, can you fix that?

**Comment by AugustinMauroy** [comment]
Shellbox part will fix on installTabs

**Comment by araujogui** [comment]
> Hey y'all, the Author Component seems to be broken. Can anybody give a look into it? https://nodejs-org-stories-r8m4tjtra-openjs.vercel.app/?path=/story/article-authorlist-author--default
> 
> Also, @araujogui or @AugustinMauroy the Codebox component got merged but I wanted a few changes:
> 
> * The copy button colour should be the same from the Shellbox one
> * Can we make the buttons from Codebox to have same padding and float like the one from Shellbox
>   ![image](https://user-images.githubusercontent.com/12037269/239382729-cd32422b-1b24-42e6-88fe-9cbf7e881251.png)
> * The padding-bottom? of the Codebox diverges from the Shellbox one, can we make them have the same padding?
> 
> Now, @AugustinMauroy the Shellbox copy button doesn't show the `cursor: pointer` when hovering it, can you fix that?

Sure, working on Codebox changes
