### ISSUE TITLE
Downloadable new logo

### ISSUE THREAD

**Issue by okuryu** [nodejs/nodejs.org#526]
The new logo has been shipped in nodejs.org by #521, but I can't find the downloadable new logo assets.

https://nodejs.org/en/about/resources/

**Comment by mikeal** [comment]
I have a series of images but I don't have time to put together a page for them right now. If anyone wants to pick this up I can send you the images.

**Comment by kahwee** [comment]
Sure I can do it. Send them to my GitHub email.

**Comment by eljefedelrodeodeljefe** [comment]
@kahwee some stuff is here https://drive.google.com/folderview?id=0B2SAGsHi4DjIcHB0cTZZcXFZNG8&usp=sharing

**Comment by mikeal** [comment]
@kahwee sent to your email :)

**Comment by fhemberger** [comment]
Oh great, finally some brand logo and color guidelines! :100: :tada:

**Comment by silverwind** [comment]
The RGB values for colors on that document are off for 357-c and 360-c, but I found this:

http://rgb.to/pantone/357-c
http://rgb.to/pantone/7741-c
http://rgb.to/pantone/360-c

**Comment by gtewallace** [comment]
@silverwind thanks you very much. I've shared this with the designer so we can get the document updated

**Comment by kahwee** [comment]
I added in the logos in PR #533 

By the way, are we still having the hexagonal logo in https://nodejs.org/en/about/resources/ It's the one that just writes JS.

The visual guidelines to due for an update as well: https://nodejs.org/static/documents/foundation-visual-guidelines.pdf

@gtewallace Can we get this from the designer?

**Comment by mikeal** [comment]
A few thing, one is that in _our_ use we're going with the new hexagon but we probably don't want to encourage other's to use it because it isn't independently trademarked the like hexa-js is. We can probably just remove it from the old site.

**Comment by gtewallace** [comment]
@silverwind This PDF has the correct RGB codes. I think you already figured it out, but for anyone else who needs/wants it, here's the brand reference. Thanks again for catching that.
[NodeJS_NewLogo_v2.pdf](https://github.com/nodejs/nodejs.org/files/155257/NodeJS_NewLogo_v2.pdf)

@kahwee yes - they are working on the new visual guidelines and it should be available next week. As soon as I get it I'll post it here and submit a PR to add it to the site

**Comment by silverwind** [comment]
@gtewallace colors are looking good now, thanks!

**Comment by gtewallace** [comment]
hi everyone - attached here is the brand guidelines doc.
[NodeJS_BrandGuide_2.pdf](https://github.com/nodejs/nodejs.org/files/159368/NodeJS_BrandGuide_2.pdf)

**Comment by silverwind** [comment]
@gtewallace can you possibly provide the logo in vector format? Would be great for the homepage.

**Comment by mikeal** [comment]
I have a zip file with a bunch of the noted variants in different formats.
