### ISSUE TITLE
Windows ARM64 installer and binaries download buttons in new layout

### ISSUE THREAD

**Issue by StefanStojanovic** [nodejs/nodejs.org#5273]
### Enter your suggestions in details:

As discussed in https://github.com/nodejs/nodejs.org/pull/5264, the downloads page layout is planned to change shortly. When that happens, it is necessary to keep the changes from the referenced PR - Windows ARM64 download buttons for Node.js v19.9.0 and bove.

Since I added this change to the current version, I can implement it in the new one if needed.

**Comment by ovflowd** [comment]
Closing as solved.
