### ISSUE TITLE
Evangelism: Weekly Update for February 23 ~

### ISSUE THREAD

**Issue by JungMinu** [nodejs/nodejs.org#529]
Let's write down for next week :gift:
As @Trott mentioned in https://github.com/nodejs/nodejs.org/pull/525, I will gather items for Weekly Update in this repo

> I wonder if these would get more visibility if the issue to gather items for these things would be opened in this repo rather than (or in addition to?) the evangelism repo

**Comment by stevemao** [comment]
@JungMinu You could ping us in evangelism repo if you don't wanna duplicate the items.
