### ISSUE TITLE
Translation errors: `setEffite` and `setFidate `

### ISSUE THREAD

**Issue by nnsay** [nodejs/nodejs.org#5295]
### URL:

https://nodejs.org/zh-cn/docs/guides/event-loop-timers-and-nexttick

### Browser Name:

Microsoft Edge

### Browser Version:

112.0.1722.39 

### Operating System:

macOS Ventura 13.3.1

### How to reproduce the issue:

The `setEffite` and `setFidate ` is error.  Translation errors should be corrected on crowdin.

![image](https://user-images.githubusercontent.com/14331919/232950604-f7a167e0-3b76-44f9-846a-698ff3814772.png)

**Comment by ghost** [comment]
@nnsay ：Thank you and this has been fixed in the Crowdin within 24-hour sync. And I'll notify you later :)

**Comment by AugustinMauroy** [comment]
@MaledongGit now it's fix ?

**Comment by ghost** [comment]
Yes it's fixed and it seems I've waited for a long time to sync with Crowdin :)
