### ISSUE TITLE
Broken link to "Node.js Contribution Guidelines" in Contributing page

### ISSUE THREAD

**Issue by bicccio** [nodejs/nodejs.org#5296]
### URL:

https://nodejs.org/en/get-involved/contribute

### Browser Name:

Chrome

### Browser Version:

112.0.5615.137

### Operating System:

MacOS Monterey 12.2

### How to reproduce the issue:

1. if I go to the https://nodejs.org/en/get-involved/contribute page and then click on the "Node.js Contribution Guidelines" link
2. I expect to see the Node.js Contribution Guidelines page
3. I see the GitHub 404 page

The actual link is https://github.com/nodejs/node/blob/main/CONTRIBUTING#pull-requests,
it should be https://github.com/nodejs/node/blob/main/CONTRIBUTING.md#pull-requests

**Comment by shanpriyan** [comment]
@bicccio I'm unable to reproduce the issue, Also the actual link is https://github.com/nodejs/node/blob/main/CONTRIBUTING.md#pull-requests and not https://github.com/nodejs/node/blob/main/CONTRIBUTING#pull-requests

**Comment by bicccio** [comment]
you have to go to https://nodejs.org/en/get-involved/contribute 
and click the link from there 

<img width="778" alt="Schermata 2023-04-20 alle 17 17 20" src="https://user-images.githubusercontent.com/274233/233411462-e67dc469-2284-41d0-9f52-c4d8cff3d1c2.png">

It seems to be removing the .md
