### ISSUE TITLE
Width of <aside> on /foundation is too small, rendering poor hovering effect for long titles.

### ISSUE THREAD

**Issue by bogas04** [nodejs/nodejs.org#53]
Width of the sidebar on /foundation page is too small to accommodate long titles such as "Technical Steering Committee" in one line. We should either 
- use abbreviation (TS Committee)
- or adjust the width of &lt;aside&gt; i.e. adjust the decided grid layout
- or consider smaller font-size *

However former solution seems to be more aesthetically pleasing.

*_nodejs.org uses font-size of 14px while new.nodejs.org using 20px/1.5 (on my 13" MBA)_
![screen shot 2015-08-27 at 9 15 38 pm](https://cloud.githubusercontent.com/assets/6177621/9525704/06cc4600-4d03-11e5-9ab1-04fc4c1db649.png)

**Comment by mikeal** [comment]
Maybe rename just to "Technical" and then we can use the page to layout all the technical governance stuff, starting with the TSC?

**Comment by fhemberger** [comment]
Okay, did a quick fix for this (changed title to "Technical Governance" and slightly increased the width). This will probably become an issue again during i18n.
