### ISSUE TITLE
Migrate `Header` and `Footer` Components

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5304]
Continuing the migration of components from `nodejs.dev` that we started [here](https://github.com/nodejs/nodejs.org/issues/5193), we want to migrate the `Header` and `Footer` Components.

This issue will keep track of these components and their development progress.

### The Migration of each Component

- Each Component should go under `components` folder on this repository
- Each Component has its sub-folder (e.g., `components/NewHeader`)
- The folder structure should pretty much be the same (CSS components, React, and sub-components), but feel free to make changes if you see deemed
- Please add some if the Component still needs to get unit tests. At least to ensure the Component is rendering. If the Component has states/CTAs (Buttons/Triggers), please cover them too.
- The Storybook of each component should allow interaction with all possible states of the Component
- If the Component depends on Hooks, please migrate them too, with the following caveat:
  - If that component only uses the Hook, move it to the same folder of the Component
  - Otherwise, migrate it to the `hooks` folder of the repository.
- If the Component has a Gatsby-specific logic (e.g. `Dark Theme Switcher`), if it is straightforward enough (e.g. a dark theme switcher plugin for Next.js or it is simple enough to code by ourselves, e.g. a Hook that we manage together with a React Provider) then feel free to do it.
  - Otherwise, if you have questions, please ask them on this Issue or your Draft PR for the Component.

## List of Components to Migrate

- [x] [`Footer`](https://github.com/nodejs/nodejs.dev/tree/main/src/sections/Footer)
  - This Component should be named `NewFooter` @AugustinMauroy 
- [x] [`Header`](https://github.com/nodejs/nodejs.dev/tree/main/src/sections/Header)
  - This Component should be named `NewHeader` @u-rogel

**Comment by AugustinMauroy** [comment]
I'm taking this issue . (if it's ok)

**Comment by ovflowd** [comment]
Can you choose one component? (As we want to have one per time)

**Comment by AugustinMauroy** [comment]
i prefer footer

**Comment by AugustinMauroy** [comment]
About footer I just have to migrate code or I have to implement-it ?

**Comment by u-rogel** [comment]
I will look into the Header component

**Comment by ovflowd** [comment]
@AugustinMauroy, you should migrate not reimplement it, if possible :) (We want to have the same design and feature-set, as otherwise it could take more time to get an approval)

**Comment by AugustinMauroy** [comment]
So I just create the component and create the stories

**Comment by u-rogel** [comment]
@ovflowd hi, I started to work on converting `<Header />` to the new codebase but came across compiling issue. Also when switching back to the `major/website-redesign` branch, runnning again `npm ci` then `npm run serve` I get issues.
Have you seen this error before?
<img width="705" alt="Screenshot 2023-04-23 at 12 48 02" src="https://user-images.githubusercontent.com/18611576/233835622-a1a52315-65b7-4e9a-8461-9624b9281021.png">

**Comment by AugustinMauroy** [comment]
It's common error with nextjs and `NODE_ENV`.
Personally it appears randomly.

**Comment by ovflowd** [comment]
> hi, I started to work on converting <Header /> to the new codebase but came across compiling issue. Also when switching back to the major/website-redesign branch, runnning again npm ci then npm run serve I get issues.
Have you seen this error before?

This sounds a Next.js cache issue. I'd delete the `.next` and `node_modules/.cache` folders :)

**Comment by u-rogel** [comment]
> 
> This sounds a Next.js cache issue. I'd delete the `.next` and `node_modules/.cache` folders :)

@ovflowd Did so and still getting it. Can you think of any other command expect to `npm ci` & `npm run serve` I need to run in order to get it up and running?

**Comment by ovflowd** [comment]
I honestly don't know why you're facing this. I will investigate 😅

What Node.js version you're using and which OS? Will try to replicate this issue.

**Comment by u-rogel** [comment]
Using macOS 13.0.1
Node v18.16.0

**Comment by ovflowd** [comment]
@u-rogel I've spotted a weird misconfiguration on package.json, and fixed it :) (It was related to `NODE_ENV`)

**Comment by u-rogel** [comment]
@ovflowd any idea how to fix it or will you push a fix to it?

**Comment by ovflowd** [comment]
@u-rogel I pushed a fix already to the major/website-redesign branch :)

**Comment by u-rogel** [comment]
Cool, now it works!

**Comment by ashutosh887** [comment]
@ovflowd I would like to take either of header/footer

**Comment by ovflowd** [comment]
Hey there 👋 as shown above these two also got worked on already (checkboxes marked), another issue I forgot to close 🙈😅

But thanks for the interest! I'm actually going to open a few more issue that need work 👀 haven't had time yet 🫠
