### ISSUE TITLE
Add `MUI` Config and Theme Provider

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5306]
As we're currently using `react-icons` with `MUI/Icons` (Material UI) Icons, we should adopt the `ThemeConfig` to tell these Icons what their default sizes are. This can be found [here](https://github.com/nodejs/nodejs.dev/blob/main/src/layouts/default.tsx#L19) and migrated under the `App` Component (`pages/_app.mdx`).

The success criteria of this Issue is that the Storybooks have the Icons with the correct sizes.

**Comment by ovflowd** [comment]
@Harkunwar would you mind working on this one? Should be really straightforward

**Comment by Harkunwar** [comment]
@ovflowd Sure, I can take a stab at this.

**Comment by ashutosh887** [comment]
@ovflowd 
Please let me work on this issue

**Comment by ovflowd** [comment]
Hey there, I forgot to close this issue. This was already worked on 🙃

**Comment by ovflowd** [comment]
Hey there, I forgot to close this issue. This was already worked on 🙃

**Comment by ashutosh887** [comment]
I saw that. Thanks for the update @ovflowd 

Can you please suggest me some issues to work on Sir

**Comment by ovflowd** [comment]
I can try later this week, as I'm sadly busy. I apologise!

I need to open some new issues that are more complex and etc, but this week I'll definitely have updates on what can be worked on :)

**Comment by ashutosh887** [comment]
Sure Thanks
I'll wait to hear back from you @ovflowd
