### ISSUE TITLE
Add `framer-motion` to the dependency list

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5307]
We use `framer-motion` on `nodejs.dev` as seen [here](https://github.com/nodejs/nodejs.dev/blob/main/src/layouts/default.tsx#L50). This issue success criteria is to simply add `framer-motion` as a dependency and the Provider on `pages/_app.mdx`

**Comment by JatinSharma32** [comment]
Working on it

**Comment by JatinSharma32** [comment]
Check out this [PR](https://github.com/nodejs/nodejs.org/pull/5318)
