### ISSUE TITLE
Migrate of `BlogCard`, `NodeFeature`, and `Hero` from `nodejs.dev`

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5308]
Continuing the migration of components from `nodejs.dev` that we started [here](https://github.com/nodejs/nodejs.org/issues/5193), we want to migrate a few other small Components that are used in a few pages but that don't really belong anywhere right now.

This issue will keep track of these components and their development progress.

### The Migration of each Component

- Each Component has its sub-folder (e.g., `components/Banner`)
- The folder structure should pretty much be the same (CSS components, React, and sub-components), but feel free to make changes if you see deemed
- Please add some if the Component still needs to get unit tests. At least to ensure the Component is rendering. If the Component has states/CTAs (Buttons/Triggers), please cover them too.
- The Storybook of each component should allow interaction with all possible states of the Component
- If the Component depends on Hooks, please migrate them too, with the following caveat:
  - If that component only uses the Hook, move it to the same folder of the Component
  - Otherwise, migrate it to the `hooks` folder of the repository.
- If the Component has a Gatsby-specific logic (e.g. `Dark Theme Switcher`), if it is straightforward enough (e.g. a dark theme switcher plugin for Next.js or it is simple enough to code by ourselves, e.g. a Hook that we manage together with a React Provider) then feel free to do it.
  - Otherwise, if you have questions, please ask them on this Issue or your Draft PR for the Component.

## List of Components to Migrate

- [x] [`NodeFeature`](https://github.com/nodejs/nodejs.dev/blob/main/src/pages/index.tsx#L48) @AugustinMauroy 
  - This Component should go under `components/Home`
- [x] [`BlogCard`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/BlogComponents/BlogCard) @Harkunwar
  - This Component should go under `components/Blog`
- [ ] [`Hero`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents/Hero) @ktssr 
  - This Component should be placed within `components/Home`
  - The `NodeReleasesData` type should be changed to the existing types we have for Node Release Data
  - Note to check if [this](https://github.com/nodejs/nodejs.dev/issues/3162) issue still happens
  - This Component requires https://github.com/nodejs/nodejs.org/issues/5310 to be done first

**Comment by Harkunwar** [comment]
I'll start work on migrating the BlogCard component.

**Comment by ktssr** [comment]
Will pick Hero component

**Comment by AugustinMauroy** [comment]
Hey folks !
Can I take node feat ?

**Comment by ovflowd** [comment]
Sure thing. But there are still open topics on the ShellBox one... But feel free to tackle Node Feat :)

**Comment by AugustinMauroy** [comment]
@ovflowd I have corrected with the feedback. Unless there is an error in understanding 😄

**Comment by AugustinMauroy** [comment]
Should I put my component in `home/NodeFeat.tsx` or in `home/nodefeat/index.tsx` ?

**Comment by ovflowd** [comment]
`components/Home/NodeFeature/index.tsx`

**Comment by ovflowd** [comment]
### ⚠️ Important Update

Due to [this update](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6533998), we're halting all Component development for now until further notice, as the design will significantly diverge, and we do not want to spend time writing Components we don't even know if a counterpart should exist.

Please follow [this discussion](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6533998) as we're going to update as soon as we have final designs and a plan for what should be done. Designs and further information will be shared soon.

**Comment by ovflowd** [comment]
We're closing this issue for the time-being as we're going either to update these issues if needed or create new ones for the development of the new design.
