### ISSUE TITLE
Nominate @HinataKah0 to the Website Team

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5343]
Hinata has been contributing actively to the migration of components from the `nodejs.dev` repository. They have been able to address review comments and points mostly autonomously and have proven they have the foundations for web development. They can grow very quickly in their knowledge.

I've had ease communicating with Hinata; they have what we need to keep things going with the Node.js Website. Whilst I'm not sure yet about Hinata's expertisé with more complex topics of Web Development, I do believe that she can give solid contributions for the tasks in hand.

As I believe that adding members to the current Website Team that have shown interest in actively contributing to this repository, that are also knowledgeable enough with web development and can communicate well and understand (and learn) the inner processes of an open source project are vital to keeping this repository healthy, I do think as Hinata as a good candidate to the team.

[Pull requests and issues opened throughout the Node.js organization](https://github.com/search?q=author:HinataKah0+org:nodejs)
[Comments on pull requests and issues throughout the Node.js organization](https://github.com/search?q=commenter:HinataKah0+org:nodejs)
Reviews on pull requests in the [nodejs/nodejs.org](https://github.com/nodejs/nodejs.org/pulls?q=reviewed-by%3AHinataKah0+sort%3Aupdated-desc) repository
Comments on pull requests and issues in the [nodejs/nodejs.org](https://github.com/nodejs/nodejs.org/issues?q=commenter%3AHinataKah0+sort%3Aupdated-desc) repository

cc @HinataKah0

**Comment by ovflowd** [comment]
@nodejs/website @nodejs/build, please give a +1 for strong agree or -1 for strong disagree. No reactions will be considered neutral opinions.

The outcome of the nomination happens after 72 hours have passed.

**Comment by HinataKah0** [comment]
Thank you for the nomination Claudio!

Many people that I have collaborated with have been very warm and kind, thank you! I've learnt a lot and I really appreciate it. I'll be happy to join the website team if I may.

Although I haven't had many hours in FE development yet, I'll be happy to learn more along the road. 😄

**Comment by shanpriyan** [comment]
**+1**  from my side , you have made nice contributions 🚀

**Comment by manishprivet** [comment]
+1 from my side as well 🚀

**Comment by ovflowd** [comment]
@Trott could you send an invite for them to the org?

**Comment by Trott** [comment]
> @Trott could you send an invite for them to the org?

Sent.
