### ISSUE TITLE
The Dropdown Component should handle clicks outside

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5348]
Currently, the Dropdown component doesn't handle clicks outside of the Component.

We should create a generic Hook, such as `useClickOutside` or something that can trigger a callback once or something of the sort.

Then we can incorporate this Hook into the Dropdown Component. This would be useful for closing the Dropdown when clicking outside of the Dropdown.

This work should be done within the `major/website-redesign` branch.

**Comment by AugustinMauroy** [comment]
I will work.

**Comment by AugustinMauroy** [comment]
We can close !
