### ISSUE TITLE
Adding Ashley Williams and Feross Aboukhadijeh to Board Page

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs.org#535]
I just noticed that Ashley and Feross were not on our list of  Board of Directors page. Here: https://nodejs.org/en/foundation/board/. Could we get the two of them added in there. Thanks in advance for help here :)

**Comment by mikeal** [comment]
They have to be officially admitted by a vote of the current board in Monday's meeting. It's just a formality but we should just hold off until Monday afternoon.

**Comment by mikeal** [comment]
BTW, this was all certified on the meeting on Monday so we should get this up :)

**Comment by williamkapke** [comment]
Where are the board meeting notices posted? Are the minutes posted?

**Comment by williamkapke** [comment]
@mikeal your PR #561 makes this closable. I'm still curious about my question above though ;)

**Comment by lpinca** [comment]
Fixed by #561 as @williamkapke said.
