### ISSUE TITLE
Consolidate Node Releases Data Logic

### ISSUE THREAD

**Issue by HinataKah0** [nodejs/nodejs.org#5350]
Design:
1. In Build time, generate a static JSON file containing all Node releases (filtered & destructured `nodevu`'s outputs which will greatly reduced the generated JSON file size).
2. In Client side, fetch the generated static JSON file using `useSWR` hook, do formatting & time sensitive logic (e.g. computing the release status).
3. Then, the ready-to-consume data is passed through the component tree using Context & Provider.
4. Implement `WithNodeRelease` component which acts as a guard (not to render a component if can't find a specific Node release, e.g. LTS or Current).

Legacy `useNodeData` hook will be removed and legacy usages in nodejs.org will be updated.

References:
- https://github.com/nodejs/nodejs.org/issues/5303#issuecomment-1536120437

**Comment by ovflowd** [comment]
@HinataKah0 I guess in this case we should **not** migrate, but simply outsource what we have on the download-releases layout on nodejs.org into a dedicated React Provider as I mentioned.. 🤔

**Comment by HinataKah0** [comment]
Done! 🚀
