### ISSUE TITLE
Problem with Next.js Actions cache?

### ISSUE THREAD

**Issue by targos** [nodejs/nodejs.org#5353]
See https://github.com/nodejs/nodejs.org/pull/5352
No cache was found on Windows (but it was found on Linux): https://github.com/nodejs/nodejs.org/actions/runs/4873873254/jobs/8694059608

**Comment by targos** [comment]
That said, it doesn't seem like the cache helps a lot. My PR only added a page, but the build took 3m35s on Linux with cache and 3m50s on Windows without cache.

**Comment by AugustinMauroy** [comment]
don't worry on redesign branch we use turbo and it's great

**Comment by ovflowd** [comment]
@targos I guess even by restoring the cache, Next.js did not use that cache (for some reason). But yes, on the `major/website-redesign` we made a lot of changes that should speed up the build process.

Also the cache is done by a combination of branch-name, package-lock and other factors.

**Comment by AugustinMauroy** [comment]
@targos We just update CI normally it's good
