### ISSUE TITLE
Ivy.xml removed from nodejs.org/dist/v16.14.0/ folder

### ISSUE THREAD

**Issue by clanceyp** [nodejs/nodejs.org#5357]
### URL:

https://nodejs.org/dist/v16.14.0/ivy.xml

### Browser Name:

Chrome

### Browser Version:

112.0.5615.137

### Operating System:

Mac 13.3

### How to reproduce the issue:

I'm getting a 404 when requesting https://nodejs.org/dist/v16.14.0/ivy.xml has this been removed recently? 

<img width="852" alt="image" src="https://user-images.githubusercontent.com/889590/236240200-4fbc88ba-7115-4347-81de-606cbaa7ce28.png">

**Comment by ovflowd** [comment]
This is not a bug on our side. This file never existed. 

Please read: https://github.com/srs/gradle-node-plugin/issues/292

For context: We changed how we handle requests to not existing files coming from "bots/crawlers" so now you're getting a 403.

**Comment by clanceyp** [comment]
Ok thanks

**Comment by clanceyp** [comment]
In case anyone stumbles on this ticket and is using moowork plugin. 
This helped me, add a 'distBaseUrl' prop like this...
```
'com.moowork.node', {
        node {
            distBaseUrl = 'https://direct.nodejs.org/dist/'
            ...
        }
    }
```
ref from https://github.com/nodejs/nodejs.org/issues/5149#issuecomment-1470896878

**Comment by richardlau** [comment]
> In case anyone stumbles on this ticket and is using moowork plugin. This helped me, add a 'distBaseUrl' prop like this...
> 
> ```
> 'com.moowork.node', {
>         node {
>             distBaseUrl = 'https://direct.nodejs.org/dist/'
>             ...
>         }
>     }
> ```
> 
> ref from [#5149 (comment)](https://github.com/nodejs/nodejs.org/issues/5149#issuecomment-1470896878)

Please do not use direct.nodejs.org. It bypasses our CloudFlare CDN and puts additional strain on our server. Use https://nodejs.org/dist/.
