### ISSUE TITLE
broken link to pkgsrc

### ISSUE THREAD

**Issue by jdx** [nodejs/nodejs.org#5390]
### URL:

https://nodejs.org/en/download/package-manager

### Browser Name:

chrome

### Browser Version:

N/A

### Operating System:

N/A

### How to reproduce the issue:

this page links to https://pkgsrc.joyent.com/install-on-osx/ which is a 404. I'm not sure what the right link should be.

**Comment by AugustinMauroy** [comment]
new link is https://pkgsrc.joyent.com/install-on-macos/
link change from joyent

**Comment by ljharb** [comment]
Has anyone notified joyent to add a redirect? Links should never break.

**Comment by AugustinMauroy** [comment]
I don't know how to contact joyen.
If you have one contact let's do it.

**Comment by ovflowd** [comment]
@ljharb yeah, if you know somebody from Joyent, that'd be great :)

**Comment by ljharb** [comment]
Unfortunately i don’t :-/

**Comment by richardlau** [comment]
> Has anyone notified joyent to add a redirect? Links should never break.

The new link https://pkgsrc.joyent.com/install-on-macos/ points to https://github.com/TritonDataCenter/pkgsrc/ as its "GitHub" link.
