### ISSUE TITLE
Winding down the old layouts/old codebase in favour of the Website Redesign

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5403]
With the continuous work into making the Website Redesign happen (https://github.com/nodejs/nodejs.org/discussions/5131), this issue describes what will happen once we finish migrating all existing Components.

### Migrating Layouts from `nodejs.dev`

Once we've finished migrating all necessary components and have all the logic planned, it will be time to start migrating layouts.

- Differently from `nodejs.dev`, the layouts here work differently and are "invoked" by each page's Frontmatter.
- Once we start migrating the new pages, they will potentially all use `.mdx` instead of plain `.md`.
- Layouts on `nodejs.dev` are overcomplicated; on this repository, we want to simplify them and break them down into different layouts.
  - For example, Learn, Blog, and regular Pages shared the same Layout on `nodejs.dev`, whilst we want to make one layout for each one.
- Initially, all the old Layouts will be placed within `layouts/old/`

### Migrating Pages from `nodejs.dev`

On `nodejs.dev`, pages reside on `src/pages` and their content on `src/content`; on this repository, both the page and the content will stay on `pages` and be a `.mdx` file.

- Frontmatter will be used for determining the layout and page title and possibly extra options
- MDX will be used for pages that need extra Components or content to be wrapped somehow
- Some pages on `nodejs.dev` use complex wrapping functions and GraphQL, whereas on this repository, we want to simplify this.
- Initially all the new pages will be placed within `pages/new/`

### Removing Old Content

Once the pages were migrated and we had satisfactory results (Components and Layouts being tweaked), we will start removing the old content:

- All old Components
- All old Hooks, Utilities and Scripts
- All old styles
- All old Layouts
- All old pages

### Final touches

The final touches include making code adjustments, documentation updates and migrating pages.

- The `_app.mdx` component needs to be updated, including removing old fonts and styles
- The pages from `pages/new` are going to be placed directly within the `pages/` folder
- Documentation regarding Translation, Contributing, and others need to be updated
- Probably a few packages can be removed

**Comment by ovflowd** [comment]
Also the following NPM packages will be removed once we get rid of the old stuff:

- `highlight.js`
- `strftime`
- `remark-gfm`

**Comment by mertcanaltin** [comment]
can i work on it? @ovflowd

**Comment by AugustinMauroy** [comment]
@mertcanaltinHere's what it says in the description of the issue
_"this issue describes what will happen once we finish migrating all existing Components."_

**Comment by ovflowd** [comment]
Hey @mertcanaltin this is a meta issue, there's no actionable directly from this issue :)

(Exactly as @AugustinMauroy mentioned above!)

**Comment by mertcanaltin** [comment]
I understood thank you 😭

**Comment by ovflowd** [comment]
@mertcanaltin I've updated some issues adding more stuff that can be worked on :)

**Comment by ovflowd** [comment]
Closing this for now, in favor of https://github.com/nodejs/nodejs.org/discussions/5131
