### ISSUE TITLE
Mention what version of npm node ships with on downloads page/release notes

### ISSUE THREAD

**Issue by toddbluhm** [nodejs/nodejs.org#541]
Would it be possible to also include what default version of npm Node ships with on the downloads page...or even in the release notes (maybe its already in the release notes and I have missed it?).

**Comment by kahwee** [comment]
The `npm` change is in the CHANGELOG.md. For example: https://github.com/nodejs/node/blob/v5.6.0/CHANGELOG.md

It doesn't change in v5.7.0 so no mention is made.

**Comment by toddbluhm** [comment]
I see that. I just didn't go back far enough.

**Comment by rvagg** [comment]
it's all here too https://nodejs.org/en/download/releases/
