### ISSUE TITLE
have recurrent banner

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/nodejs.org#5412]
### Enter your suggestions in details:

If you don't know, the first version of nodejs was released on May 27, 2009.
We tweet every year to celebrate. We also have an event on our calendar (nodejs.org/calendar). But on the website we have nothing

That's why I'm proposing to have recurring events displayed on the site banner. To display nodejs birthday.
If no image was add it's just display an message

The second idea is to replace the leaves (website redesign) with confetti and add the message below the `InstallTabs` component.

The idea of making a toast isn't bad, but it has to be pop-up-free. 

Give me your opinion

**Comment by Trott** [comment]
Every feature we add is something someone has to maintain. I'd prefer to only include things that we really need. I won't stop somebody from adding something like this, but I would discourage it.

**Comment by AugustinMauroy** [comment]
The general idea is that it's automatic, so as soon as the code is done, banners or other items will appear without any action from anyone, but won't take over a release announcement.

**Comment by ovflowd** [comment]
For me, this is kind of a -1, like when we had a Konami code easter egg on the Website Redesign. It's nice but not worth the effort and feels slightly odd. Plus, it requires maintenance, even if it's "automatic/scheduled", there's no code in the world that doesn't need maintenance 😅 

And I rather have the Foundation handle the Node.js birthday than us. Of course, I'm open to suggestions, and maybe the image itself can be changed every year if we only adopt a banner. But then, other things are at play, such as, what if we have another banner simultaneously? Wouldn't the automatic banner then become a little bit problematical?

**Comment by AugustinMauroy** [comment]
> Wouldn't the automatic banner then become a little bit problematical?

Release will take over the birthday.

> Konami code easter egg

it's different here it's not an easter egg because it gives information. Of course it's fun thing but there are difference

**Comment by ovflowd** [comment]
I'm not talking about the usability but the technical aspect of it.

**Comment by Trott** [comment]
I don't think we should do this at this time. I'm going to close this because we have plenty of other work to do right now. We can always re-open at a later date. Thanks for the suggestion.
