### ISSUE TITLE
Mixed Contribution Guidelines with Collaborator Guide

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5413]
Right now the [Collaborator Guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#translating-pages) has duplication or mixed content with the [Contribution Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md)

For example, the Collaborator Guide has a "Code Editing" section referring to Adding new Pages and Translations, yet, the Contribution Guide has sections for "Creating Components", "Adding Storybooks," and "Creating Unit Tests". (https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#creating-components)

Since the CONTRIBUTING.md is also a top-level bylaw document for the Website Team, we should move all these "collaborating"-specific snippets and sections from CONTRIBUTING.md to COLLABORATOR_GUIDE.

And the Collaborator Guide should be mentioned at the top of the CONTRIBUTING guidelines as the reference for standards for making code changes.

cc @nodejs/website

**Comment by Ve33y** [comment]
I can help with this one ☝️
