### ISSUE TITLE
Implement types for JSON files

### ISSUE THREAD

**Issue by HinataKah0** [nodejs/nodejs.org#5418]
TODO: Write details

- [ ] site.json
- [ ] navigation.json

References:
- https://github.com/nodejs/nodejs.org/pull/5365#discussion_r1210474995

**Comment by ashutosh887** [comment]
I would like to work on this @ovflowd @HinataKah0

**Comment by ovflowd** [comment]
Feel free to work on this :)

**Comment by ashutosh887** [comment]
Sure @ovflowd ... Please assign 
Also where can I discuss about issues with you Sir if I face any difficulty?

**Comment by ovflowd** [comment]
We don't assign issues here. I've answered you on another comment how to reach us out :)

**Comment by ashutosh887** [comment]
Yes Thanks for that @ovflowd

**Comment by HinataKah0** [comment]
I haven't really checked (I am using GitHub search since I am not in front of my laptop) but...

It seems that `site.json` already has the types defined, see [this](https://github.com/nodejs/nodejs.org/blob/main/types/config.ts#L16).
Can't find any [usage](https://github.com/search?q=repo%3Anodejs%2Fnodejs.org+site.json&type=code) after latest changes...

For `navigation.json`, I only found this [usage](https://github.com/nodejs/nodejs.org/blob/2dc6293afd856663f5608940da2f8e645b464c98/components/Blog/BlogCard/index.tsx#L4) which is not using the correct type. I rmb we have [`useNavigation`](https://github.com/nodejs/nodejs.org/blob/2dc6293afd856663f5608940da2f8e645b464c98/hooks/useNavigation.tsx#L16) hook, can we use it instead?

Edit:
It seems after the latest changes, this issue is already out of date... 🤔

**Comment by ovflowd** [comment]
Closing this issue as out of date :)
