### ISSUE TITLE
Migrate Complex components from `nodejs.dev`

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5427]
With the recent progress in the development of the Website Redesign component migration, we have a few components that are more complex and require some special attention/individual understanding of how they should be migrated. 

This is mostly due to them being specifically wired for Gatsby/GraphQL logic or specific logic of the `nodejs.dev` repository. This also means that once we start migrating them we want to revise their logic, props, functionality and design to ensure they still make sense.

### The Migration of each Component

- Each Component should go under `components/` folder on this repository
- Each Component has its sub-folder (e.g., `components/Common/Banner`)
- The folder structure should pretty much be the same (CSS components, React, and sub-components), but feel free to make changes if you see deemed
- Please add some if the Component does not have unit tests already. At least to ensure the Component is rendering. If the Component has states/CTAs (Buttons/Triggers), please cover them too.
- The Storybook of each component should allow interaction with all possible states of the Component
- If the Component depends on Hooks, please migrate them too, with the following caveat:
  - If that component only uses the Hook, move it to the same folder of the Component
  - Otherwise, migrate it to the `hooks` folder of the repository.
- If the Component has a Gatsby-specific logic (e.g. `Dark Theme Switcher`), if it is straightforward enough (e.g. a dark theme switcher plugin for Next.js or it is simple enough to code by ourselves, e.g. a Hook that we manage together with a React Provider) then feel free to do it.
  - Otherwise, if you have questions, please ask them on this Issue or your Draft PR for the Component.

## List of Components to Migrate

- [ ] [`RandomContributor`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/CommonComponents/RandomContributor)
  - This Component should be placed under `components/Common`
- [ ] [`TableOfContents`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/ArticleComponents/TableOfContents) @AugustinMauroy 
  - The Table of Contents Component uses metadata specific to Gatsby's TOC system. This Component should be done later, with the same design and as much of a similar codebase as possible, but using Nextra's ToC System (Comes from Graymatter)
  - This Component should be placed under `components/Article`
- [ ] [`RecentPosts`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/ArticleComponents/RecentPosts)
  - The Recent Posts Component uses metadata specific to Gatsby. This Component should be done later, with the same design and as much of a similar codebase as possible, but using our own Blog Metadata System.
  - This Component should be placed under `components/Blog`
- [ ] [`VersionSelector`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/ApiComponents/Components/VersionSelector)
  - This uses specific logic of the temporary API Docs Tooling System, and we're still determining how we will proceed with the new API Docs and what we provide or not. You can work on this Component, but I'd recommend not to.
  - This Component should be placed under `components/Api`

**Comment by AugustinMauroy** [comment]
I have already work on table of content and it's use Nextra toc feat.

**Comment by ovflowd** [comment]
Do you mean you have an open PR for it?

**Comment by AugustinMauroy** [comment]
Yeah a "long time" ago

**Comment by ovflowd** [comment]
Oh yeah I see it 🙈

**Comment by ktssr** [comment]
I can take care of Hero component once the fixture is ready

**Comment by bmuenzenmeyer** [comment]
I'd like to try my hand at this work. Can I take `RandomContributor`?

**Comment by ovflowd** [comment]
Afaik, @Harkunwar was working on that, so I'd ask first if he's fine with you working on it.

Note that the current state of the Hook from nodejs.dev requires a lot of refactoring as it was messy not-optimised.

**Comment by ovflowd** [comment]
FYI @ktssr the fixture is ready already.

**Comment by ktssr** [comment]
@ovflowd  working on merge issues. Will raise PR once done

**Comment by Nirajn2311** [comment]
I'd like to work on `VersionSelector` component. Can I take it up?

**Comment by ovflowd** [comment]
### ⚠️ Important Update

Due to [this update](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6533998), we're halting all Component development for now until further notice, as the design will significantly diverge, and we do not want to spend time writing Components we don't even know if a counterpart should exist.

Please follow [this discussion](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6533998) as we're going to update as soon as we have final designs and a plan for what should be done. Designs and further information will be shared soon.

**Comment by ovflowd** [comment]
I'm closing this issue as these Components will not be migrated at all.
