### ISSUE TITLE
Migrate `NavigationComponents` from `nodejs.dev`

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5428]
Continuing the migration of components from `nodejs.dev` that we started [here](https://github.com/nodejs/nodejs.org/issues/5193), we should start migrating the [`NavigationComponents`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/NavigationComponents) and [`navigations`](https://github.com/nodejs/nodejs.dev/tree/main/src/navigations) from the `nodejs.dev` repository.

This issue will keep track of these components and their development progress.

### The Migration of each Component

- Each Component should go under `components/Navigation` folder on this repository
- Each Component has its sub-folder (e.g., `components/Navigation/Something`)
- The folder structure should pretty much be the same (CSS components, React, and sub-components), but feel free to make changes if you see deemed
- Please add some if the Component still needs to get unit tests. At least to ensure the Component is rendering. If the Component has states/CTAs (Buttons/Triggers), please cover them too.
- The Storybook of each component should allow interaction with all possible states of the Component
- If the Component depends on Hooks, please migrate them too, with the following caveat:
  - If that component only uses the Hook, move it to the same folder of the Component
  - Otherwise, migrate it to the `hooks` folder of the repository.
- If the Component has a Gatsby-specific logic (e.g. `Dark Theme Switcher`), if it is straightforward enough (e.g. a dark theme switcher plugin for Next.js or it is simple enough to code by ourselves, e.g. a Hook that we manage together with a React Provider) then feel free to do it.
  - Otherwise, if you have questions, please ask them on this Issue or your Draft PR for the Component.

## Navigation System

The Navigation system is done on `nodejs.dev` was done in a certain abstract manner. Yet it has a lot of Gatsby-specific types and logic and the components were done to "work" with the dynamic nature of Gatsby and GraphQL. **This is not what we want here.**

The whole navigation of our Website is static and done [here](https://github.com/nodejs/nodejs.org/blob/main/navigation.json).

We want to introduce a Navigation System that supports our static featurette and can still have different styles.

### How the migration should work

- We want to have base Navigation styles and base Navigation Components (Such as a NavigationItem, NavigationSection and others) that can be extended (either via SCSS or [Emotion](https://emotion.sh/docs/introduction).
- We want the navigation itself to be fully static on `navigation.json`
- The structure and types on `navigation.json` need to be updated to support the future use cases and current legacy-code
- We will have different kinds of navigation:
  - `header` for header navigation (the redesigned `NewHeader` needs to be updated to support that)
  - `footer` for footer navigation (the redesigned `NewFooter` needs to be updated to support that)
  - `learn` for learn sidebar navigation
  - `sidebar` for regular sidebar navigation
  - `api` for API pages sidebar navigation
  - `blog` for Blog Navigation. This is the only dynamic one that comes from Nextra `getStaticProps` and is not defined on `navigation.json`.
- The different sort of navigations have different layouts that should be used to extend the base Navigation Components.

### What this means for `nodejs.dev` components?

The components on `NavigationComponents` will probably need to be worked from scratch, where very little will be reused (besides styles and general DOM/Element structure)

### How are we going to coordinate the prerequisites for the Navigation components?

All new logic, types and requirements and technical discussion should be done in this issue so that all interested contributors can be on par.

## List of Components to Migrate

- [ ] [`Navigation`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/NavigationComponents/Navigation) @AugustinMauroy 
- [ ] [`NavigationItem`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/NavigationComponents/NavigationItem)
- [ ] [`NavigationSection`](https://github.com/nodejs/nodejs.dev/tree/main/src/components/NavigationComponents/NavigationSection)
- [ ] [`ApiNavigation`](https://github.com/nodejs/nodejs.dev/blob/main/src/navigations/api.tsx)
  - This component should reside on `navigations/ApiNavigation/`
- [ ] [`SidebarNavigation`](https://github.com/nodejs/nodejs.dev/blob/main/src/navigations/about.tsx)
  - This component should reside on `navigations/SidebarNavigation/`
- [ ] [`LearnNavigation`](https://github.com/nodejs/nodejs.dev/blob/main/src/navigations/learn.tsx)
  - This component should reside on `navigations/LearnNavigation/`
- [ ] [`BlogNavigation`](https://github.com/nodejs/nodejs.dev/blob/main/src/navigations/blog.tsx)
  - This component should reside on `navigations/BlogNavigation/`

**Comment by ashutosh887** [comment]
The plan and layout looks good to me
I'd like to be a part of this migration and contribute as much as possible @ovflowd 

Please keep me on loop

**Comment by AugustinMauroy** [comment]
@ashutosh887 You can take one component to work on. Don't take an component already taken by someone.
Fo example:
Hey !
Can I work on Navigation ? But where should I put ?  _that real proposition_

**Comment by ovflowd** [comment]
@ashutosh887 feel free to grab any component you want to work on :)

But I would heavily recommend that y'all first discuss the migration here before making a PR. @AugustinMauroy I saw you made a PR already, but it has the same props/structure of the existing Navigation Component. I would (as I mentioned before) recommend that we discuss the structure (type) of a Navigation Item, Navigation Section and Navigation itself beforehand here 😄

**Comment by AugustinMauroy** [comment]
Yup you have true big part but the component I had work it's an container for nav.

**Comment by AugustinMauroy** [comment]
FYI: I'm looking deeply about navigation.

*  [NavigationItem](https://github.com/nodejs/nodejs.dev/tree/main/src/components/NavigationComponents/NavigationItem) is just a styled Link so If someone want to work on.
* [NavigationSection](https://github.com/nodejs/nodejs.dev/tree/main/src/components/NavigationComponents/NavigationSection) is also a "container" so an other people can work on
* About Learn nav. I'm not fan about yml metadata for ordering. We should use frontmatter but it could be a problem if the FrontMatter is translated on crowdin.
* And about section on blog I thinks yml is also bad idea but any idea for that.
* Navigation API depend of metadata-docs-proposal. So we shouldn't work on.

**Comment by ovflowd** [comment]
> About Learn nav. I'm not fan about yml metadata for ordering. We should use frontmatter but it could be a problem if the FrontMatter is translated on crowdin.

The learn navigation should be inside `navigation.json` as I mentioned and the order would be given from the file. It could also be YAML.

IMHO it doesn't make sense to put the order on Frontmatter, it would also be pretty impractical.

**Comment by ovflowd** [comment]
> Navigation API depend of metadata-docs-proposal. So we shouldn't work on.

Not really. We can still code the API Navigation Components even if they're not going to be used. We can always estipulate how the data would look like.

**Comment by AugustinMauroy** [comment]
> The learn navigation should be inside navigation.json as I mentioned and the order would be given from the file. It could also be YAML.

IMHO: Yaml is better for new comer

**Comment by ovflowd** [comment]
Yes, but I don't recall it being natively able to be imported by TypeScript. We need a specific loader to be able to load YAML and that loader would be a WebPack loader.

So yes, the YAML convention could sound friendlier in certain ways, but it's too much of a burden to be adopted.

**Comment by AugustinMauroy** [comment]
That true and what do you thinks about using an `navigation.ts` and for API we will generate JSON or other file but this metadata will not touch by humane.

```ts
type about = {
XXX
}

export const aboutNav: about = {
XXX
}
```

**Comment by ovflowd** [comment]
I'm sorry, I have no idea what you're referring to 😅

**Comment by AugustinMauroy** [comment]
I just propose we can change `navigation.json` -> `navigation.ts`.

And we'll have:
* typing for security + ide helping (so good for new comer)
* Having a constant for navigation

**Comment by ovflowd** [comment]
Why do we need typing on a navigation file? I'm not inclined in making a TypeScript file just for a bunch of navigation entries. This has worked well (the JSON) for years, and I've never seen (on my time here) anybody complaining about it 🤔

**Comment by AugustinMauroy** [comment]
Typescript just allows us to have types, so we get an error during the build if someone makes a mistake in the navigation file.

**Comment by ovflowd** [comment]
This is not the sort of file that changes often. And mistakes will be noted on PRs. The structure of the navigation itself is simple enough.

And I rather have a no-code approach. JSON in this case is still simpler. I don't see a benefit of having types here, as during the import the IDE's will already complain if the structure of the JSON file differs from the types we create on our types folder.

So if the JSON import has a diverging type (which is implicitly generated by `ts-server`) then the IDE will complain anyways.

There's no point on making this file TypeScript.

**Comment by araujogui** [comment]
Hey, working on `NavigationItem` component

**Comment by ovflowd** [comment]
### ⚠️ Important Update

Due to [this update](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6533998), we're halting all Component development for now until further notice, as the design will significantly diverge, and we do not want to spend time writing Components we don't even know if a counterpart should exist.

Please follow [this discussion](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6533998) as we're going to update as soon as we have final designs and a plan for what should be done. Designs and further information will be shared soon.

**Comment by ovflowd** [comment]
This issue is going to be closed as the Navigation Components will be completely new.
