### ISSUE TITLE
Migrate the `Default` Layout from `nodejs.dev`

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5429]
Continuing the migration of components from `nodejs.dev` that we started [here](https://github.com/nodejs/nodejs.org/issues/5193), the `default` layout including.

This issue will be used to track the migration of the `Default` layout. Also, note that I want this issue to be available for newcomers and not existing contributors if possible!

### Migrating the `Default` layout

- The layout should reside on `layouts/NewDefault/index.tsx` with styles on `index.module.scss` of the same folder.
- The Layout should extend the `DefaultLayout` (like how we do with other legacy layouts, one layout extending another)
- The Layout should extend the `nodejs.dev` DefaultLayout and support a (Header, Footer, Container with default paddings and `children`).

**Comment by ashutosh887** [comment]
@ovflowd 
I Just saw that #5429 is a blocker for #5430 
If you suggest, I'd like to work on this first and take up #5430 after this!

Please assign the issue to me

**Comment by ovflowd** [comment]
Sure, feel free to start working on this issue! Just a heads-up that we never assign issues to people on the issue itself, but feel free to work on it!

**Comment by ovflowd** [comment]
@ashutosh887 let me know if you're working on this :)

**Comment by ashutosh887** [comment]
Sure I'll go ahead with #5429 first
Any communication channel where I can discuss and update you on the progress?

**Comment by AugustinMauroy** [comment]
We have a slack channel in OpenJs foundation slack.

[OpenJS foundation slack](https://slack.openjsf.org/) #nodejs-website

**Comment by ashutosh887** [comment]
Thanks @AugustinMauroy 
I've Joined it

**Comment by ovflowd** [comment]
Closing as this Layout will not be used anymore.
