### ISSUE TITLE
Nominate @araujogui to the Website Team

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5439]
Guilherme has contributed to the Website Redesign Initiative since around August/September 2022 (He started contributing to `nodejs.dev` and now here). With some slow but steady contributions and he's picking up the pace with even better contributions. 

I know Guilherme for a long time, and he has shown a strong interest in open source. His strong team working skills and communication skills make him a strong candidate for the team.

Not to mention he has real-world Frontend Development knowledge, even tho he is more on the junior side, he has shown the ability to learn from mistakes and be able to independently find solutions without guidance and iterate on feedback.

As I believe that adding members to the current Website Team that have shown interest in actively contributing to this repository, that are also knowledgeable enough with web development and can communicate well and understand (and learn) the inner processes of an open source project are vital to keeping this repository healthy, I do think as Guilherme as an excellent candidate to the team.

[Pull requests opened throughout the Node.js organization](https://github.com/search?q=author%3Aaraujogui+org%3Anodejs&type=pullrequests)
[Comments on pull requests throughout the Node.js organization](https://github.com/search?q=commenter%3Aaraujogui+org%3Anodejs&type=pullrequests)
[Comments on issues throughout the Node.js organization](https://github.com/search?q=commenter%3Aaraujogui+org%3Anodejs&type=issues)
Comments on pull requests and issues in the [nodejs/nodejs.org](https://github.com/nodejs/nodejs.org/issues?q=commenter%3Aaraujogui+sort%3Aupdated-desc+) repository

cc @araujogui 
cc @nodejs/website

**Comment by araujogui** [comment]
Thank you for the nomination @ovflowd!

Over the past few months, I have gained invaluable knowledge and experience from working with the team. I am genuinely excited about the opportunity to become a part of the team and make significant contributions.

**Comment by mikeesto** [comment]
+1

**Comment by HinataKah0** [comment]
+1 Guilherme has done great things. I'll be really happy for him joining.
Contributing to OSS is like a marathon, steady contributions over time is what we need. ❤️

**Comment by ovflowd** [comment]
Exactly as @HinataKah0 mentioned. That's the spirit!

**Comment by manishprivet** [comment]
+1

**Comment by ovflowd** [comment]
FYI @manishprivet and @mikeesto your comments were automatically flagged somehow as spam, maybe because of the character count 🤔

**Comment by ovflowd** [comment]
FYI inviting @araujogui to the Node.js org and to the team.

**Comment by ashutosh887** [comment]
@ovflowd @mikeesto @HinataKah0 @manishprivet 

I'm also interested to be a part of this team... Please guide me how can I pick some tasks and get involved
I've previously contributed on OSS projects as well

**Comment by ovflowd** [comment]
> I'm also interested to be a part of this team... Please guide me how can I pick some tasks and get involved
I've previously contributed on OSS projects as well

Hey there, we're updating the contributing guidelines to make it clearer who is eligible to join and how.

But to be fair and set some expectations for you, the Website Team is also possibly going to go through some changes, but in general having steady contributions for a few months and proven understanding of web development are the requirements. Thanks!

**Comment by ovflowd** [comment]
Also, welcome to the team, @araujogui
