### ISSUE TITLE
WGET command results in error 404: Not Found

### ISSUE THREAD

**Issue by quattroman** [nodejs/nodejs.org#544]
Hi, 

I am trying to get node JS installed on my Raspberry Pi 2 (running raspbian).  Unfortunately when I run the following;

https://nodejs.org/dist/v5.7.0/node-v5.7.0-linux-armv7l.tar.gz does not work. (5.7.0 being the latest)

The Pi connects to the nodejs.org website, sends the HTTP request, awaits response and then fails ….404 not found.

Can you help please.

Thanks

Peter

**Comment by ghost** [comment]
hi peter, in what browser are you querying the website?

**Comment by quattroman** [comment]
using the terminal application on a Raspberry Pi 2; so typing sudo wget..............

**Comment by ghost** [comment]
@quattroman ah sorry, didn't catch that. doing `sudo wget https://nodejs.org/dist/v5.7.0/node-v5.7.0-linux-armv7l.tar.gz` works for me.

can you try downloading it with `curl`? run `sudo curl -O https://nodejs.org/dist/v5.7.0/node-v5.7.0-linux-armv7l.tar.gz` and it should (hopefully) download the file.

**Comment by silverwind** [comment]
@quattroman can you post your wget output?

**Comment by phillipj** [comment]
Closing this as reporter stopped responding, and there hasn't been similar reports lately.
