### ISSUE TITLE
docs: Contribution Guide clarification

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5440]
I was reading how to become more involved in the website team, and noticed that https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#becoming-a-collaborator mentions:

> A Pull Request must be opened on the @nodejs/nodejs.org README file adding the new collaborator to the list (note the order of names)

No such list exists, but nominations for new members do occur via issue. 

Can we clarify the pathway to @nodejs/website membership? I'd be happy to PR what the outcome of the discussion is.

**Comment by AugustinMauroy** [comment]
List isn't created true. it's an artifact from nodejs.dev. I mean in nodejs.dev we had a list and on nodejs.org there't list.
Personally I thinks we should add a list.
The latest arrivals have been nominated by an Issue.

**Comment by ovflowd** [comment]
> No such list exists, but nominations for new members do occur via issue.

We never updated the README.md with such list. Which is something we should do. And I probably just forgot due to all the other work... I can work on that 😅

**Comment by ovflowd** [comment]
I've made a PR updating the guidelines for becoming a Collaborator and etc https://github.com/nodejs/nodejs.org/pull/5441
