### ISSUE TITLE
Add support to `lint-staged` on Husky

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5451]
### Enter your suggestions in details:

Since we introduced `husky` for resetting some generated files on each `pre-commit` I also would recommend that we add `lint-staged`.

`lint-staged` would automatically run our `npm run format` only on files that were changed, meaning this would always lint files before commits, avoiding formatting errors and preventing PRs from failing due to formatting or linting errors.

**Comment by bmuenzenmeyer** [comment]
I can work on this
