### ISSUE TITLE
All feeds could not be found

### ISSUE THREAD

**Issue by tgfjt** [nodejs/nodejs.org#5456]
### URL:

https://nodejs.org/en

### Browser Name:

Chrome

### Browser Version:

114.0.5735.133

### Operating System:

macOS 13.4

### How to reproduce the issue:

1. Open https://nodejs.org/en and check the feeds:
    - https://nodejs.org/en/feed/blog.xml
    - https://nodejs.org/en/feed/releases.xml
    - https://nodejs.org/en/feed/vulnerability.xml
2. These feeds could be found
3. These feeds could not be found
4. 

<img width="754" alt="image" src="https://github.com/nodejs/nodejs.org/assets/2628239/95af38cd-d30b-4999-bd47-d24f604e1016">

**Comment by bmuenzenmeyer** [comment]
possible duplicate of comments made within #5132

**Comment by ovflowd** [comment]
Closing as duplicate. Will investigate
