### ISSUE TITLE
Investigate all prettier logic running through eslint

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5466]
https://github.com/prettier/eslint-plugin-prettier

We should be able to integrate prettier fully into eslint. Since all prettier changes are auto-fixable, they jive nicely with eslint's `--fix` capabilities.  I've seen this work on smaller codebases, but this issue serves to discuss the approach and research how we could adapt it to al already crowded eslint config.

_Originally posted by @bmuenzenmeyer in https://github.com/nodejs/nodejs.org/issues/5463#issuecomment-1616774249_

> This change and other recent ones make me wonder if we can integrate prettier fully into eslint via [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier).  I'll open an issue

**Comment by bmuenzenmeyer** [comment]
@ovflowd [suggests this might not be a good practice](https://github.com/nodejs/nodejs.org/pull/5463#issuecomment-1616774456)

That's the first I've heard of that, so will do some research. 

Edit: A quick read of their docs states that if you have styling needs that conflict with prettier, this could be a deal-breaker. I am not aware of any, but am still spinning up on the codebase.

**Comment by ovflowd** [comment]
Also, @bmuenzenmeyer (https://prettier.io/docs/en/integrating-with-linters.html) here they also state on the "Notes" that using linters to run prettier defeats the point of prettier not being invasive, etc.

But again, I'm fine either way, whatever simplifies our tooling and processes, to be honest.

**Comment by bmuenzenmeyer** [comment]
That's a great read! Appreciate you finding that 🙏 

My main goals are usually to 1. be obvious and 2. reduce complexity. Point 2 gets a bit convoluted depending on your perspective.... so let's keep our current strategy for now knowing we can always revisit if people continue to trip up on one over the other.

And TIL about yet another tool in https://github.com/prettier/prettier-eslint
