### ISSUE TITLE
Get rid of the 2018 User Survey Report HTML pages

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5470]
The 2018 User Survey Report (https://github.com/nodejs/nodejs.org/tree/main/public/en/user-survey-report) has been stored within this repository for a long time.

Yet, it is a fully static page that should only be a PDF. I would argue that we should only store the PDF and redirect the https://nodejs.org/en/user-surver-report/ to that PDF. Note that right now, that page is not even working because of infinite 301 redirects.

The whole folder is massive and has too many assets that I would be happy to eliminate. Only keeping the PDF is enough.

cc @nodejs/build (since we would like to make this redirect at CF level probably)

**Comment by Trott** [comment]
I'd be OK with redirecting to a PDF. Not great for accessibility, but also we don't have infinite volunteer resources to maintain low-use info that is many years old.

**Comment by ovflowd** [comment]
Yea, I’d also add that the more time goes by, less relevant the report becomes. So possibly even less people accessing it.

**Comment by ovflowd** [comment]
I also have no idea how accessible the current page for the report is, not sure if screen readers can read PDF nowadays

**Comment by targos** [comment]
The page you linked returns 404 for me

**Comment by ovflowd** [comment]
Sorry, I wrote a typo. The correct link is https://nodejs.org/en/user-survey-report, but that is given infinite reports.

So the only working link is https://nodejs.org/en/user-survey-report/index.html

**Comment by targos** [comment]
The report says it's the third annual survey. Where are the other ones?
It's been 5 years, I think we can remove it altogether (or replace with pdf)

**Comment by ovflowd** [comment]
> The report says it's the third annual survey. Where are the other ones?

I don't know, that's the only one we have within this repository.

> It's been 5 years, I think we can remove it altogether (or replace with pdf)

I'm fine either way. I wonder if the TSC would like to have a say here?

**Comment by ovflowd** [comment]
I'm okay with completely removing the report. Any objections? (I can keep the PDF file on public folder, and ask build WG to make a redirect on Cloudflare)
