### ISSUE TITLE
Package Download failed

### ISSUE THREAD

**Issue by florian-asche** [nodejs/nodejs.org#5472]
### URL:

https://nodejs.org/dist/v19.8.1/node-v19.8.1-linux-x64.tar.gz

### Browser Name:

Firefox

### Browser Version:

115.0

### Operating System:

Linux, Ubuntu

### How to reproduce the issue:

Hi,

in our Gitlab Pipeline, in various computers from various location in germany, it is not possible, to download the nodejs file https://nodejs.org/dist/v19.8.1/node-v19.8.1-linux-x64.tar.gz. 

The download speed is very low, about 200kb and after some time the download failed.

Regards, Florian

**Comment by ovflowd** [comment]
Please consider searching similar issues, before opening a tad new one :)

- https://github.com/nodejs/nodejs.org/issues/4495
- https://github.com/nodejs/nodejs.org/issues/5149

But yes, we're investigating this.
