### ISSUE TITLE
NodeJS v18 not available via DNF Module

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#5483]
### URL:

https://nodejs.org/en/download/package-manager#centos,-fedora-and-red-hat-enterprise-linux

### Browser Name:

Vivaldi

### Browser Version:

6.1.3035.111

### Operating System:

Fedora Workstation 38

### How to reproduce the issue:

Back in November, I've made a change to the documentation to update the example for installing NodeJS on CentOS/Fedora/RHEL, by changing the version number shown from 12 to 18.
You can see that here: https://github.com/nodejs/nodejs.org/pull/4952

However, today, I noticed that v18 nor newer versions of NodeJS like v20 aren't available anymore through this method. 
By running `dnf module list nodejs`, we can see that only v16 is available. 

Why is it that newer versions aren't available?

**Comment by ovflowd** [comment]
This is the wrong repository to ask why specific versions of Node.js are not available on `dnf`.

I'm not sure who's responsible for distributing Node.js on Fedora (https://developer.fedoraproject.org/tech/languages/nodejs/modules.html, from here it looks like some people from RedHat?)

You might want to ask this again on `nodejs/node` repository. Here we only maintain the website.

**Comment by ghost** [comment]
I'll around there, thanks!
