### ISSUE TITLE
Replace relative imports to `@`

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5484]
Our current `tsconfig` allows all files compiled via TypeScript to use `@` to indicate the `root` folder.

This allows us to replace long relative imports such as `import something from '../../../../big-path/something';` to simply `import something from '@/big-path/something';`

This PR is about updating all these relative paths with `@` by doing the work manually or having an ESLint rule from `.ts/.tsx` files to suggest that and fix that automatically.

**Comment by adnan-abdullah1** [comment]
Hi if i could work on this issue

**Comment by ovflowd** [comment]
Sure, feel free to :)
