### ISSUE TITLE
Add Lighthouse-CI

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5492]
Add the Lighthouse CI GitHub action

https://github.com/GoogleChrome/lighthouse-ci

We want to be more intentional about the impact development does to real-user metrics, and choose to accept any changes over time to a baseline.

This is somewhat broken out of a conversation within #5489

**Comment by Chandupuram** [comment]
Hi @bmuenzenmeyer Can I pick this issue and start working on it?

**Comment by bmuenzenmeyer** [comment]
sure thing, let me know if you have any questions

**Comment by gaurav15gkgk** [comment]
Hey @bmuenzenmeyer, Can I pick this feature request and work on it?

**Comment by bmuenzenmeyer** [comment]
> Hey @bmuenzenmeyer, Can I pick this feature request and work on it?

@gaurav15gkgk no, sorry. @Chandupuram asked first. You are welcome to review other pull requests or pick up something else

**Comment by Chandupuram** [comment]
@bmuenzenmeyer 
ERROR:
23 Unable to automatically determine the location of static site files.
24 Use the CLI flag --collect.staticDistDir or a lighthouserc config file to tell Lighthouse CI where your HTML files are located.
I'm facing this error. Can u point me to the directory where we can find the static html files in our repo?

**Comment by bmuenzenmeyer** [comment]
can you follow this guide with success? it's for Next.js apps https://dev.to/joerismits/ensure-your-nextjs-apps-performance-is-top-notch-with-lighthouse-ci-and-github-actions-4ne8

**Comment by Chandupuram** [comment]
After trying the method posted in the blog I'm getting this error message
 "runtimeError": {
    "code": "ERRORED_DOCUMENT_REQUEST",
    "message": "Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 404)"
  },
  "runWarnings": [
    "Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 404)"
  ],
But when I start my local the URL is working and the same url is not working for Lighthouse CI I tried various ways but of no use Can u help me on this

**Comment by bmuenzenmeyer** [comment]
https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#startserverreadypattern should be defaulting to `listen|ready`, which the site outputs on `npm run serve`

You can see a non-GitHub action example here too https://github.com/leanazulyoro/next-lhci-example/blob/develop/lighthouserc.json#L7-L8 -  though we'd want a different ServerCommand.

I'd recommend looking at the official docs at https://github.com/GoogleChrome/lighthouse-ci/tree/main - this has to be a pretty paved path.

**Comment by Chandupuram** [comment]
Thanks that did help me. Can u tell me what are the assertions that we need and the values for those metrics to pass the checks?

**Comment by bmuenzenmeyer** [comment]
I don't have a lot of opinions at to what the numbers should be, without knowing their current values. 

I took a peak at https://vercel.nodejs.org/en lighthouse run

![image](https://github.com/nodejs/nodejs.org/assets/298435/971377e7-368b-4bf6-9a70-0c1c2553861c)

If it were me, I'd take these numbers, add 10%, and make that the assertion barrier

**Comment by bmuenzenmeyer** [comment]
@Chandupuram how is progress on this?

**Comment by Chandupuram** [comment]
@bmuenzenmeyer I will be creating the PR today or tomorrow for this. The entire development is done

**Comment by Chandupuram** [comment]
@bmuenzenmeyer refer to that PR and create a secret with variable name as LIGHTHOUSE_APP_TOKEN by using the github Lighthouse app.

**Comment by bmuenzenmeyer** [comment]
@ovflowd if this was a task you wanted to take on you certainly can. My bandwidth has mostly been devoted to the website redesign issues as of late. if you can wait a bit longer i'd be happy to work toward landing...but it just might be a bit
