### ISSUE TITLE
Lookalike warnings in Chrome when trying to access storybook previews

### ISSUE THREAD

**Issue by mikeesto** [nodejs/nodejs.org#5498]
When I try to access a storybook preview, for example: https://nodejs-org-stories-d9fzb0ffq-openjs.vercel.app/  I now get a warning in Chrome.

<img width="730" alt="Screen Shot 2023-07-11 at 1 17 30 pm" src="https://github.com/nodejs/nodejs.org/assets/21051488/e261368f-01fa-4086-bc4e-affb1c53ac5c">

I've only started getting this message today. I'm not sure if something has changed recently, either on Chrome or our preview URL. I'm assuming this is being triggered by the `nodejs-org` part of the URL. I can just click 'ignore'. It isn't a major issue. But I thought I'd raise it here in case others are experiencing it too.

**Comment by bmuenzenmeyer** [comment]
Seeing this too the past couple days. 

Chrome Version 114.0.5735.199 (Official Build) (64-bit)

Wondering if we can close this in the same spirit of 
https://github.com/nodejs/nodejs.org/issues/5453 - a documented environmental quirk

**Comment by vats147** [comment]
It is now accessible you can close issue

**Comment by ovflowd** [comment]
> I've only started getting this message today. I'm not sure if something has changed recently, either on Chrome or our preview URL. I'm assuming this is being triggered by the nodejs-org part of the URL. I can just click 'ignore'. It isn't a major issue. But I thought I'd raise it here in case others are experiencing it too.

I think that this issue will always happen. Pretty much I think it's a newly released Chrome-feature that tries to identify scam links.
