### ISSUE TITLE
Reduce amount of web fonts included (page performance!)

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs.org#55]
I just noticed we include **all** font styles of Source Sans Pro, which has a heavy impact on page performance:

`<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900,900italic" rel="stylesheet" type="text/css">`

At the moment we use the widths 300 (default text), 500 (headlines), and 700 (for bold). Maybe we could get rid of the latter as well.

**Comment by mikeal** [comment]
I use 400 on the front page as well. The bolds and italics could be used by any markdown page in whatever weight we’ve set that to by default as well. I’m all for trimming it down I’m not just 100% sure all the weights and combos we’re using right now.

**Comment by ShashankaNataraj** [comment]
Just observed this when I viewed source. Was about to report an issue on this and stumbled on this one :)

**Comment by fhemberger** [comment]
We already removed the 200, 600 and 900 widths, and font caching is addressed in #69. I didn't have enough time to test it before launch.

**Comment by ShashankaNataraj** [comment]
Ah, ok.

**Comment by fhemberger** [comment]
This will be fixed by #98.
