### ISSUE TITLE
Enable Git LFS on the repository

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5501]
For a long period, we have had a lot of assets on our repository, (including the Survey Report) but we never used Git LFS.

By using Git LFS we can reduce the overall repository size, and commit-to-commit size.

I'm making a PR already, but wanted to open an issue to keep track of this, and allow discussions to happen.

**Comment by richardlau** [comment]
We don't have git-lfs available via apt on the www server and I'm reluctant to install via a third party repository on a key bit of infrastructure. We do need to update the www server to a newer OS, but that's [not a quick job](https://github.com/nodejs/build/issues/2625#issuecomment-822364531) -- we'd either be looking at scheduled downtime or creating a replacement server from scratch.

**Comment by ovflowd** [comment]
Interesting. So there's no easy solution for this out there? I can close the PR, but `git lfs` definitely would be a nice thing to have.
