### ISSUE TITLE
Improvement: Banner

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5510]
### The Issue

The current design of Banners (https://nodejs-org-stories-2alntbb1b-openjs.vercel.app/?path=/story/common-banner--with-text) does not respect the Designs imposed on Figma (https://www.figma.com/file/lOxAGGg5KXb6nwie7zXkz6/NJ---Design-System?type=design&node-id=1338-13441&mode=design&t=MBnZiC9gdl8p1uCT-4)

#### Current

![image](https://github.com/nodejs/nodejs.org/assets/12037269/24300d24-74da-46e2-aff7-93fd561d6b5d)

#### Expected

![image](https://github.com/nodejs/nodejs.org/assets/12037269/5d39da7c-906c-4ac3-a9a5-fd456d84a74e)

### The Solution

Redesign the Banner to look like the Expected design, such as:

- Always fills 100% of the width
- The design above is when the Banner has text and a link (not HTML banners)
- HTML banners should render whatever HTML it is imposed.
  - Note that on this case, differently from text banners that have no margin after the header, the HTML banners should have some margin, have a max-width and align in the center.

**Comment by BahugunaSaumya** [comment]
Hey, I am looking for my first open source contribution, can you assign this to me? 

If yes, from what I've understood, you want to change the Button(in the main index.tsx / index.module.scss file) for Banner with text to have the style in Figma ?


I apologize if I am wrong

Thanks and regards,

Saumya Bahuguna

**Comment by ovflowd** [comment]
Sure, go ahead :)

**Comment by ashutosh887** [comment]
@ovflowd Should I try this if not resolved?

**Comment by ashutosh887** [comment]
If not, please consider redirecting me to some other high priority issue

**Comment by ovflowd** [comment]
@ashutosh887 this is already being worked on... Please read previous comments before.

Edit: Actually this even got merged already.
