### ISSUE TITLE
Flaky Test on `Codebox` for Storybook

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#5526]
### The Issue

The Codebox component currently holds a flaky test that often passes and often does not. It also causes PRs that run `test:storybook:snapshot` often to update this flaky Storybook test with unrelated changes.

#### Cause

This is mainly caused due to `Prismsjs` being client-side and modifying the DOM-tree on-the-fly for the Codebox. This is the current approach instead of running Prismjs, setting the content on a state, and then injecting through a `dangerouslyInnerHtml` React option.

The new approach does indeed modify the contents, and it is a side-effect out of the bounds of React.

### Solution

Since this change on the DOM-tree is caused by Prismjs, we can wait for the `tabindex` field to be present. (Wait until `pre[tabindex="0"]` renders)

**Comment by bmuenzenmeyer** [comment]
another thought would be if a snapshot test asserting on the output of a library is even a good idea. their tests should be asserting that behavior, not ours

**Comment by ovflowd** [comment]
> another thought would be if a snapshot test asserting on the output of a library is even a good idea. their tests should be asserting that behavior, not ours

Hmm, could you elaborate? Not sure if I got what you mean here.
