### ISSUE TITLE
Feedbacks on Vercel migration

### ISSUE THREAD

**Issue by mcollina** [nodejs/nodejs.org#5528]
__i18n is different__, https://vercel.nodejs.org redirects me https://vercel.nodejs.org/it. https://nodejs.org/ redirects me to https://nodejs.org/en.

__The default size of text is different__

nodejs.org
<img width="1798" alt="Screenshot 2023-07-17 at 18 39 49" src="https://github.com/nodejs/nodejs.org/assets/52195/e9cf57bf-8035-47da-a80b-ea7b181549e2">

verce.nodejs.org
<img width="1800" alt="Screenshot 2023-07-17 at 18 40 05" src="https://github.com/nodejs/nodejs.org/assets/52195/c245cf57-ba21-4574-8652-f80876112fe4">

**Comment by ovflowd** [comment]
> The default size of text is different

It seems on the second screenshot you have zoom applied? Text should be the same on both as it is the same Framework 🤔 

> i18n is different, [vercel.nodejs.org](https://vercel.nodejs.org/) redirects me [vercel.nodejs.org/it](https://vercel.nodejs.org/it). [nodejs.org](https://nodejs.org/) redirects me to [nodejs.org/en](https://nodejs.org/en).

Afaik it is reading your browser primary locale!

**Comment by mcollina** [comment]
> It seems on the second screenshot you have zoom applied? Text should be the same on both as it is the same Framework 🤔

Unfortunately no :(

> Afaik it is reading your browser primary locale!

It's incorrect, because all my language is English on my machine. My primary

**Comment by ovflowd** [comment]
> Unfortunately no :(

![image](https://github.com/nodejs/nodejs.org/assets/12037269/4810703e-451a-4b4e-a0ee-5ec19603dec6)

🤔  (I took this from your screenshot)

**Comment by ovflowd** [comment]
> It's incorrect, because all my language is English on my machine. My primary

I'll give an 👀 on that!

**Comment by ovflowd** [comment]
FYI the language detection comes from this middleware: https://github.com/nodejs/nodejs.org/blob/main/middlewares/detectLanguage.ts

**Comment by mcollina** [comment]
Found it, it was a hidden setting.

**Comment by ovflowd** [comment]
> Found it, it was a hidden setting.

For i18n?

**Comment by ovflowd** [comment]
Closing this issue then!
