### ISSUE TITLE
Getting 500 error when agents attempted to download nodejs v14.17.4

### ISSUE THREAD

**Issue by deschandhok24** [nodejs/nodejs.org#5537]
### URL:

https://nodejs.org/dist/v14.17.4/node-v14.17.4-win-x64.7z

### Browser Name:

N/A

### Browser Version:

N/A

### Operating System:

Microsoft Windows Server Operating System(Server 2022) vNext

### How to reproduce the issue:

1. what I did?
Currently we have multiple agents running our automated test pipeline in parallel. In turn, our agents running in parallel attempted to download nodejs v14.17.4 given by the url https://nodejs.org/dist/v14.17.4/node-v14.17.4-win-x64.7z

2. What I expected to happen?
The download to complete successfully as it has done hundreds of times before for all agents

3. What I actually got?
I expected the download to complete successfully but off the 6 agents running in parallel it failed to download nodejs v14.17.4 successfully for 3 of them. This occurred on Monday July 17th, 2023 at approximately 11:00AM est. Each of the 3 agents received a 500 error as shown below:

Locations of the failing agents downloading the version were US, UK, and Canada.

Agent1:
"Failed to download "8b319a6a-8ecd-4025-ab91-6104193d5e36" from "https://nodejs.org/dist/v14.17.4/node-v14.17.4-win-x64.7z". Code(500) Message(Internal Server Error)" 

Agent2:
Failed to download "8b319a6a-8ecd-4025-ab91-6104193d5e36" from "https://nodejs.org/dist/v14.17.4/node-v14.17.4-win-x64.7z". Code(500) Message(Internal Server Error)

Agent3:
Failed to download "3a51b709-df63-47f7-b0b5-7b90b2921d98" from "https://nodejs.org/dist/v14.17.4/node-v14.17.4-win-x64.7z". Code(500) Message(Internal Server Error)

4. Other information

We run these automated tests every hour with the 6 agents (6 downloads of nodejs v14.17.4 occurs every hour) and it hasnt happened before or hasnt happened after. Was there a blimp/transient that everyone is aware off or was it something else?

**Comment by ovflowd** [comment]
There's a pinned issue precisely about this, please search for existing issues before opening a new one. Thank you!

https://github.com/nodejs/nodejs.org/issues/4495
