### ISSUE TITLE
Storybook test for Codebox component sometimes times out on Windows

### ISSUE THREAD

**Issue by mikeesto** [nodejs/nodejs.org#5538]
### URL:

N/A

### Browser Name:

N/A

### Browser Version:

N/A

### Operating System:

Windows

### How to reproduce the issue:

Unfortunately this one might be hard to replicate as it doesn't happen consistently. I've only seen it happen when the tests are run on Windows. Stack trace below:

```
FAIL components/Article/Codebox/__tests__/index.test.tsx (20.287 s)
    ● Codebox component (one lang) › should copy content
  
      thrown: "Exceeded timeout of 5000 ms for a test.
      Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."
  
        37 |   const code = 'const a = 1;';
        38 |
      > 39 |   it('should copy content', async () => {
           |   ^
        40 |     const user = userEvent.setup();
        41 |
        42 |     const { container } = render(
  
        at it (components/Article/Codebox/__tests__/index.test.tsx:39:3)
        at Object.describe (components/Article/Codebox/__tests__/index.test.tsx:36:1)
```

**Comment by ovflowd** [comment]
Usually, the timeout happens because the Storybook Component build failed or got stuck. A way to test this is that instead of running `test:storybook` run `storybook` to open Storybook and see if it usually builds.

Then you run `npx test-storybook` (which is the actual testing package) and see what happens.

I also find it hard to be a "Windows" problem, as we run these same tests on every PR on our CI running Windows 🤔

**Comment by mikeesto** [comment]
> I also find it hard to be a "Windows" problem, as we run these same tests on every PR on our CI running Windows 🤔

Sorry, I could have been clearer. I don't develop on Windows. I've been sometimes seeing this issue in CI running on Windows - but it's very sporadic. Perhaps you are right though and it's just oddly getting stuck now and then.

**Comment by ovflowd** [comment]
> Sorry, I could have been clearer. I don't develop on Windows. I've been sometimes seeing this issue in CI running on Windows - but it's very sporadic. Perhaps you are right though and it's just oddly getting stuck now and then.

When this issue happens it might be as I mentioned due to the Component failing to compile, has the Ubuntu pipeline not failed either for the same commit?

**Comment by ovflowd** [comment]
Cause I haven't seen this happening... yet

**Comment by mikeesto** [comment]
I haven't seen this in a while, and no one else is reporting so will close.
