### ISSUE TITLE
Add new eslint rule typescript-plugin/recommended

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5541]
Broken out of #5531
Requires #5540

Add `typescript-plugin/recommended` to our eslint configuration as an override applied to all `.tsx` files
Resolve all lint issues

**Comment by omlondhe** [comment]
I can do this one, may I work on this issue?

**Comment by bmuenzenmeyer** [comment]
you may, but we are waiting on #5540 to merge first, so sit tight

**Comment by omlondhe** [comment]
> you may, but we are waiting on #5540 to merge first, so sit tight

Okay!

**Comment by ovflowd** [comment]
#5540 got merged :)

**Comment by omlondhe** [comment]
Thank you for the update @ovflowd !
Forking this repository to solve this issue.

**Comment by omlondhe** [comment]
I have to just add

```typescript
{
    file: [*/*.tsx],
    extends: ["plugin:typescript-plugin/recommended"]
}
```

to .eslintrc, right?

**Comment by ovflowd** [comment]
Not really, you should update the existing override rule we have on `.eslintrc` and add the extends entry there.

**Comment by omlondhe** [comment]
> typescript-plugin/recommended

<img width="633" alt="Screenshot 2023-07-27 at 17 02 27" src="https://github.com/nodejs/nodejs.org/assets/61611599/f31289a4-1592-4e07-8df8-92255db441d9">

Like this, right?

**Comment by ovflowd** [comment]
Sure, but could you please try things on your own and open a PR? I'm not here to guide you step-by-step; autonomy is essential in open source.

So I recommend reading the issue description, ensuring we're on the same page, and opening a PR. Reviews can always happen there. This change is simple enough that you could just try a PR and then I could review and say if it's good or not 😅

**Comment by bmuenzenmeyer** [comment]
as with what @ovflowd said, experimentation is key. also, as a hint, some of the rules we have directly specified are perhaps not needed once the recommended set is implemented as a default. so peek at https://typescript-eslint.io/rules/?supported-rules=recommended to see if we can remove those two explicit rules

**Comment by ovflowd** [comment]
Take @bmuenzenmeyer’s words! 😄

**Comment by omlondhe** [comment]
Okay, got it.
Thank you!

It's my first time working with .eslint configurations, I'll go through the documentation and raise a PR.
