### ISSUE TITLE
Windows anchor links don't work correctly on download/package-manager

### ISSUE THREAD

**Issue by docwhat** [nodejs/nodejs.org#5542]
### URL:

https://nodejs.org/en/download/package-manager

### Browser Name:

Firefox

### Browser Version:

115.0.2 (64-bit)

### Operating System:

Windows 11, 22H2

### How to reproduce the issue:

- I clicked on the table of contents "Windows" link; Nothing happened.

There are two bugs here:

1. The ToC "Windows" link goes to the anchor `windows-1` instead of the `<h2>` "Windows" anchor.
2. There are two anchors with the `id` "windows".  The first is in "nvs" -> "windows" and the second is "windows".

I don't know what flavor of markdown is being used, so I didn't submit a PR.  A previous MD engine apparently automatically appended numbers to the end.

**Comment by ovflowd** [comment]
Interesting, and indeed a bug, seems like we're not calculating repeated ToC's

> I don't know what flavor of markdown is being used, so I didn't submit a PR. A previous MD engine apparently automatically appended numbers to the end.

We're manually doing this with MDX by using https://github.com/nodejs/nodejs.org/blob/main/components/AnchoredHeading.tsx which only has its own context. We could create a "global" context (for the current page being rendered) but that's hacky.

I'm not sure why this was done, but presuming that MDX is not passing an ID here? We probably could use a Remark plugin tho. Feel free to open a PR that can take advantage of a Remark Plugin that adds these `ids` and then we could update this Component.

Then if the plugin itself doesn't fix that, you can add custom heading-ids to the Markdown heading.

**Comment by sohan2410** [comment]
Well this isn't working for 

- centos-fedora-and-red-hat-enterprise-linux
- windows
- z/OS

@docwhat @ovflowd can I work on this issue?
