### ISSUE TITLE
RSS feed links to vercel.app domain

### ISSUE THREAD

**Issue by trogau** [nodejs/nodejs.org#5574]
### URL:

https://nodejs.org/en/feed/vulnerability.xml

### Browser Name:

Firefox

### Browser Version:

115.0.3

### Operating System:

Windows 10

### How to reproduce the issue:

The RSS feed at https://nodejs.org/en/feed/vulnerability.xml currently does not link directly to nodejs.org but instead a specific Vercel domain - here's a snippet from the start of the feed as it stands right now: 

```
<channel>
<title>Node.js Blog: Vulnerability Reports</title>
<link>
https://nodejs-jqm8ptz6n-openjs.vercel.app/en/feed/vulnerability.xml
</link>
<description>
</description>
<lastBuildDate>Sun, 30 Jul 2023 21:40:50 GMT</lastBuildDate>
<docs>https://validator.w3.org/feed/docs/rss2.html</docs>
<generator>https://github.com/jpmonette/feed</generator>
<language>en</language>
<item>
<title>Tuesday June 20 2023 Security Releases</title>
<link>
https://nodejs-jqm8ptz6n-openjs.vercel.app/en/blog/vulnerability/june-2023-security-releases
</link>
<guid>/blog/vulnerability/june-2023-security-releases</guid>
<pubDate>Tue, 20 Jun 2023 14:30:00 GMT</pubDate>
</item>
```

Noticed this as my reader (Feedly) weirdly put up June's security release notice today. Old stored links in Feedly refer to nodejs.org as expected.

**Comment by ovflowd** [comment]
Noticed. Will investigate. We get the deployment URL directly from Vercel, so funny that it does not use the assigned domain as Public URLs on Production.

It could also be a temporary bug in one deployment. I'll keep an eye, and monitor. The fix is simple if actions are needed. (Override the Env variable)

**Comment by ovflowd** [comment]
I've redeployed with a cache purge. This should have been fixed now.

Thanks for reporting!

**Comment by MattIPv4** [comment]
👀 https://nodejs.org/en/feed/blog.xml very much still contains Vercel URLs

**Comment by ovflowd** [comment]
This was fixed at the moment I wrote it was fixed.

I don’t understand why it came back. Genuinely curious 🤔

**Comment by MattIPv4** [comment]
Is it worth just setting a custom `NEXT_PUBLIC_VERCEL_URL` for production, or changing the order in https://github.com/nodejs/nodejs.org/blob/main/next.constants.mjs so that the custom `NEXT_PUBLIC_BASE_URL` is preferred if set?

**Comment by ovflowd** [comment]
Feel free to make a PR 😀 

That could be the fix! But I also wonder if the Serverless Functions have their own env variables, hence why my change didn’t take effect? Let’s see 👀

**Comment by ovflowd** [comment]
This got permanently fixed with https://github.com/nodejs/nodejs.org/pull/5599 and the PR adopted your suggestion, @MattIPv4
