### ISSUE TITLE
Changelog links are broken

### ISSUE THREAD

**Issue by kanongil** [nodejs/nodejs.org#5576]
### URL:

https://nodejs.org/en

### Browser Name:

Any

### Browser Version:

N/A

### Operating System:

N/A

### How to reproduce the issue:

1. Click "Changelog" under "18.17.0 LTS"

**Comment by kanongil** [comment]
Github provides two different responses, depending on when I click it.

### This page is taking too long to load
<img width="614" alt="Screenshot 2023-07-31 at 09 49 46" src="https://github.com/nodejs/nodejs.org/assets/753512/c09035fc-cb20-4b94-9e3b-2ad5eb0348b0">

### This blob took too long to generate
<img width="763" alt="Screenshot 2023-07-31 at 09 50 12" src="https://github.com/nodejs/nodejs.org/assets/753512/8acb4606-eec5-4fe7-9a6f-a695d9fb6156">

**Comment by egoroof** [comment]
https://github.com/nodejs/node/issues/48833

**Comment by ovflowd** [comment]
Changelog Links are not broken. It's just that GitHub can't render such a big Markdown document. That's a GitHub issue.
