### ISSUE TITLE
Layout breaking for Resources page on Firefox 

### ISSUE THREAD

**Issue by jeanlucaslima** [nodejs/nodejs.org#558]
The page [Logos and Graphics](https://nodejs.org/en/about/resources/) layout is breaking on Firefox 44.0.2 Linux Ubuntu. Screenshot:

![nodejsresources](https://cloud.githubusercontent.com/assets/1311402/13575825/2fd4c4c8-e461-11e5-8a43-d8b0810b2232.png)

**Comment by fhemberger** [comment]
Same on Firefox (Mac).

``` css
.logos img { width: 100% }
```

fixed it.

**Comment by jeanlucaslima** [comment]
Thanks @fhemberger :+1:
