### ISSUE TITLE
Dist Is 404ing

### ISSUE THREAD

**Issue by GenericProgramer** [nodejs/nodejs.org#5603]
### URL:

https://nodejs.org/dist

### Browser Name:

Brave Browser

### Browser Version:

Version 1.51.118 Chromium: 113.0.5672.126 (Official Build) (arm64)

### Operating System:

Mac Ventura 13.5 (22G74)

### How to reproduce the issue:

I visited https://nodejs.org/dist and got a 404
I tried looking at wayback machine and it was a valid path

**Comment by GenericProgramer** [comment]
Resolved now it seems.

**Comment by ovflowd** [comment]
nodejs.org/dist will give you a 404. You need to open nodejs.org/dist/
