### ISSUE TITLE
Big green download button on nodejs.org from Linux/x64 gives source archive

### ISSUE THREAD

**Issue by sxa** [nodejs/nodejs.org#5610]
### URL:

https://nodejs.org

### Browser Name:

Firefox

### Browser Version:

101.0

### Operating System:

Fedora Silverblue 37

### How to reproduce the issue:

Go to nodejs.org and try to click the download button for 18 or 20. The URLs point to the source archive e.g. https://nodejs.org/dist/v18.17.0/node-v18.17.0.tar.gz at present, instead of the node-v18.17.0-linux-x64.tar.xz build that I would expect. From the screnshot you can see that it has correctly detected what platform I'm using.

![image](https://github.com/nodejs/nodejs.org/assets/6487691/ad569523-b142-4c33-8f74-5a658d081ac0)

**Comment by ovflowd** [comment]
I can confirm this is a regression, the current https://github.com/nodejs/nodejs.org/blob/main/util/downloadUrlByOS.ts provides `.tar.gz` instead of `.tar.xz`

@sxa feel free to update this file. This should fix your issue afaik. (Opening a PR also deploys a preview where you can check this indeed fixes the issue)

**Comment by sxa** [comment]
I'll give it a try - thanks for the pointer to where it might be. Since we generally have both tar.gz and tar.xz in the download site I'd have though the current code would have still been able to point ot the gz version.

**Comment by ovflowd** [comment]
> I'll give it a try - thanks for the pointer to where it might be. Since we generally have both tar.gz and tar.xz in the download site I'd have though the current code would have still been able to point ot the gz version.

Yup on the "All Downloads" page you can still download the `.gz` even if you do this change. This file is pretty much used for the automatic OS detection on the Home page.

**Comment by sxa** [comment]
It looks like there isn't an easy way to have the architecture detection in that piece of code, so it may require more work to do anything other than hard code for x64 as a 'quick fix'.

It looks like the label on the web page puts 'Linux (x64)' for all Linux variants based on https://github.com/nodejs/nodejs.org/blob/562ed48c4c4f1fe6921a1327bff795f0b0a2eced/layouts/IndexLayout.tsx#L17

I'll initially hard code it to linux/x64 and see if that works before we look at whether we can enhance it - even if that's in place as a first phase it'l lbe better than what we have at present ';-)

**Comment by ovflowd** [comment]
> I'll initially hard code it to linux/x64 and see if that works before we look at whether we can enhance it - even if that's in place as a first phase it'l lbe better than what we have at present ';-)

That's fine for now. The whole Website and its components and content will be changing soon, so this part will be overhauled very soon. The hot-fix for now at least solves the Linux x64 issue.
