### ISSUE TITLE
`https://nodejs.org/en/docs/inspector` returns 404

### ISSUE THREAD

**Issue by LiviaMedeiros** [nodejs/nodejs.org#5624]
### URL:

https://nodejs.org/en/docs/inspector

### Browser Name:

curl

### Browser Version:

8.2.1

### Operating System:

Gentoo 17.1

### How to reproduce the issue:

This address is hardcoded in https://github.com/nodejs/node/blob/48c613e5a755ee29a0287582147c421561a1f204/src/inspector_socket_server.cc#L251 and there are tests relying on its content

**Comment by ovflowd** [comment]
Can this hardcoded thing be removed? This page is honestly going to be removed soon, alongside all the guide pages, with the content refresh.

**Comment by LiviaMedeiros** [comment]
It is shown when `node` is launched with `--inspect` argument, e.g.
```console
$ node --inspect -e "console.log(123)"
Debugger listening on ws://127.0.0.1:9229/0f2c936f-b1cd-4ac9-aab3-f63b0f33d55e
For help, see: https://nodejs.org/en/docs/inspector
123
>
```
Related: https://github.com/nodejs/node/pull/11207, https://github.com/nodejs/nodejs.org/pull/1216

I guess it might be still useful, so if there will be any alternative hint to provide to users, we can replace it with new link.
Having https://nodejs.org/en/docs/inspector as `301` redirect would also be helpful for users who have outdated version.

**Comment by ovflowd** [comment]
I mean, I don't mind adding a redirect for now, but I wonder how useful it is. Also, how outdated the /docs/inspector guide is.

All these old guides are going to be removed in a few months, so I would argue it's better to redirect people to API docs (https://nodejs.org/api/cli.html#--inspecthostport) for example.

I'm fine making the redirect going over the API docs, it's just that this "Guide" page from nodejs.org is going to be eventually removed.

**Comment by LiviaMedeiros** [comment]
No idea how useful it is, opened PR in `node` so it can be discussed there. 😅

AFAICT so far, it was added to point specifically on guide that covers nuances and caveats, so right now pointing on https://nodejs.org/en/docs/guides/debugging-getting-started might be better than on API docs.

**Comment by ovflowd** [comment]
I appreciate the effort, @LiviaMedeiros! But I feel that fixing the current redirect is a better approach, so people also using older versions of Node do not get affected.

The point that we **need discuss** is as this page will get removed, to where should we redirect, and/or if we should simply add this page to the new "Learn Pages".

cc @Trott (As you have some of the context regarding deprecating Guides in favour of the Learn pages)

**Comment by ovflowd** [comment]
The 404 is fixed, but waiting for @Trott for an opinion

**Comment by Trott** [comment]
> The 404 is fixed, but waiting for @Trott for an opinion

I don't honestly have an opinion but I will form one if required to do so to move things forward.

**Comment by ovflowd** [comment]
@Trott do you know anyone that would have an opinion on this? I just want an experienced opinion from someone else, so I can not too hardly stay attached on my opinion 😅

**Comment by richardlau** [comment]
> @Trott do you know anyone that would have an opinion on this? I just want an experienced opinion from someone else, so I can not too hardly stay attached on my opinion 😅

cc @nodejs/diagnostics
