### ISSUE TITLE
Improve Search Results

### ISSUE THREAD

**Issue by bnb** [nodejs/nodejs.org#5627]
### Enter your suggestions in details:

Non-trivially often, I find that top search results on Google.com are random localized versions rather than the English version I'm looking for. I do _often_ get the right page, but sometimes it's really frustrating to have to figure out how to get the correct page in my language.

I do also worry about the impact of pages with very similar titles getting flagged as SEO juicing, but that might be a step beyond what's necessary to look at now.

I'm sure there are very well established guidelines for how to manage localized content and SEO, and my _guess_ is that we're not doing those but I'm not actually certain what they are - I do know quite a bit about SEO but I've never dealt with localization before.

**Comment by bnb** [comment]
A similar but distinct issue is searching for an API method but getting a random version's page rather than the latest version. Happy to create another issue for that if it'd be helpful, but it's also consistently a pain.

**Comment by ovflowd** [comment]
> Non-trivially often, I find that top search results on Google.com are random localized versions rather than the English version I'm looking for. I do often get the right page, but sometimes it's really frustrating to have to figure out how to get the correct page in my language.

I feel we can add weights on the sitemap? Add a higher weight to the English sources?

> I'm sure there are very well established guidelines for how to manage localized content and SEO, and my guess is that we're not doing those but I'm not actually certain what they are - I do know quite a bit about SEO but I've never dealt with localization before.

Sadly I have very little SEO knowledge nowadays.

**Comment by ovflowd** [comment]
> A similar but distinct issue is searching for an API method but getting a random version's page rather than the latest version. Happy to create another issue for that if it'd be helpful, but it's also consistently a pain.

That is sadly not something we can do within this repository 😢 (Or at least not easily without scrap the directory listing of /api/ somehow)

**Comment by MattIPv4** [comment]
> I feel we can add weights on the sitemap? Add a higher weight to the English sources?

All the localized pages (including English) should have hreflang meta tags linking to all the different versions, and Google should just figure it out for you iirc.

https://developers.google.com/search/docs/specialty/international/localized-versions

**Comment by MattIPv4** [comment]
> A similar but distinct issue is searching for an API method but getting a random version's page rather than the latest version. Happy to create another issue for that if it'd be helpful, but it's also consistently a pain.

In theory, I think this would be properly be solved by all the older API version docs having canonical meta tags that link to the most recent version -- essentially, telling Google that the older versions of the docs are exactly that, an older version of the same thing, so Google will list the newest version instead.

**Comment by ovflowd** [comment]
> > I feel we can add weights on the sitemap? Add a higher weight to the English sources?
> 
> All the localized pages (including English) should have hreflang meta tags linking to all the different versions, and Google should just figure it out for you iirc.
> 
> [developers.google.com/search/docs/specialty/international/localized-versions](https://developers.google.com/search/docs/specialty/international/localized-versions)

Aware of that, but Next.js doesn't provide an easy way to set attributes on the `html` tag. Otherwise I would have done already (ltr, lang and hreflang attributes).

I can still investigate in a way of doing so, but I can't promise it'll be clean.

**Comment by MattIPv4** [comment]
hreflang doesn't need to be on the HTML tag, it can just be a meta tag in the head that is an alternate link with the hreflang. As long as all the versions link to all the other versions, I think Google will be able to figure it out.

**Comment by ovflowd** [comment]
> hreflang doesn't need to be on the HTML tag, it can just be a meta tag in the head that is an alternate link with the hreflang. As long as all the versions link to all the other versions, I think Google will be able to figure it out.

Gosh, sorry. I mistook `html lang` with `alternate hreflang`, you're right.

**Comment by ovflowd** [comment]
@MattIPv4 PR: https://github.com/nodejs/nodejs.org/pull/5638
