### ISSUE TITLE
nodejs.org returning 404 for every page

### ISSUE THREAD

**Issue by mmarchini** [nodejs/nodejs.org#5628]
nodejs.org is returning 404 on every page. Tested on multiple devices, different browsers and different internet connections.

![Screenshot 2023-08-10 at 2 07 28 PM](https://github.com/nodejs/build/assets/4048656/5e5ca09e-8d4a-4807-8820-8cbc27ec61ac)

**Comment by ovflowd** [comment]
Possibly a regression coming from: https://github.com/nodejs/nodejs.org/commit/1fbd908497ece0c5b08c7cc8f7494d7a12e7001f#diff-11949fb16a64da6db0d3c419ec485bee0d013cd028132a8a4dc5631169f59578R118

**Comment by ovflowd** [comment]
Pushed a hot-fix https://github.com/nodejs/nodejs.org/commit/8644e36dd508b8d79fe2641f3ca9ccf40315ef82

**Comment by ovflowd** [comment]
@mmarchini can you ack bug is fixed on your side?

**Comment by mmarchini** [comment]
Yes it's fixed, thank you for the quick turnaround!
