### ISSUE TITLE
IRC logging has stopped

### ISSUE THREAD

**Issue by williamkapke** [nodejs/nodejs.org#563]
[The #nodejs logs have stopped recording](http://logs.nodejs.org/node.js/index) as of 2016-02-17.

Last I remember, I think @piscisaureus was the one to kick the machine to get it going again. lol. That was aloooong time ago. I have no idea who deals with that now.

Also: I only posted this here because `logs` is a subdomain of nodejs.org- I'm not sure where else this would go.

**Comment by Fishrock123** [comment]
Hmmm, I still see the `{slurp-nodejs}` bot in #node-dev, but not in #nodejs. cc @jasnell could you give Bert a bit of a poke to get it up again?

**Comment by piscisaureus** [comment]
The logging has stopped because some bright light decided to ban the bot from #node.js. I don't really look at this particular IRC channel, that's why I didn't catch it earlier.

If you want to the logging to continue, talk to a channel op and get the bot unbanned, _then_ talk to me again and I'll make the bot rejoin.

Here's the bot's output (if it helps debugging):

```
slurp@slurp:~/slurp$ node server.js 
Creating IRC client for {slurp-libuv}@irc.freenode.net
Creating IRC client for {slurp}@irc.freenode.net
Creating IRC client for {slurp-nodejs}@irc.freenode.net
Creating IRC client for {slurp-sl}@irc.freenode.net
Starting backup (server restart)
Server started
[master 7a210af] Automatic backup (server restart)
 Author: Slurp <slurp@piscisaureus.no.de>
 15 files changed, 101 insertions(+)
 create mode 100644 iriscouch/2016-03-09.txt
Counting objects: 65, done.
Compressing objects: 100% (32/32), done.
Writing objects: 100% (32/32), 46.03 KiB | 0 bytes/s, done.
Total 32 (delta 25), reused 0 (delta 0)
To git@github.com:piscisaureus/slurp-logs
   6d9c77f..7a210af  master -> master
Backup successful, scheduling next backup
IRC error: { prefix: 'orwell.freenode.net',
  server: 'orwell.freenode.net',
  command: 'err_bannedfromchan',
  rawCommand: '474',
  commandType: 'error',
  args: 
   [ '{slurp-nodejs}',
     '#node.js',
     'Cannot join channel (+b) - you are banned' ] }
IRC error: { prefix: 'orwell.freenode.net',
  server: 'orwell.freenode.net',
  command: 'err_bannedfromchan',
  rawCommand: '474',
  commandType: 'error',
  args: 
   [ '{slurp-nodejs}',
     '#node.js',
     'Cannot join channel (+b) - you are banned' ] }
IRC error: { prefix: 'orwell.freenode.net',
  server: 'orwell.freenode.net',
  command: 'err_bannedfromchan',
  rawCommand: '474',
  commandType: 'error',
  args: 
   [ '{slurp-nodejs}',
     '#node.js',
     'Cannot join channel (+b) - you are banned' ] }
```

And `ifconfig`:

```
eth0      Link encap:Ethernet  HWaddr 04:01:2a:9f:26:01  
          inet addr:107.170.199.52  Bcast:107.170.207.255  Mask:255.255.240.0
          inet6 addr: fe80::601:2aff:fe9f:2601/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:84966890 errors:0 dropped:0 overruns:0 frame:0
          TX packets:97682460 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:6979431610 (6.9 GB)  TX bytes:252761721381 (252.7 GB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:62 errors:0 dropped:0 overruns:0 frame:0
          TX packets:62 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:13316 (13.3 KB)  TX bytes:13316 (13.3 KB)
```

**Comment by ljharb** [comment]
@piscisaureus I'm the bright light that banned the bot, not realizing it was the official logging bot (we've had a rash of not-explicitly-allowed logging bots lately). It's now unbanned - please do make sure it always uses the authed nickserv account too (which it wasn't at the time I banned it, making it appear all the more suspicious).

**Comment by piscisaureus** [comment]
Ok, the bot is back: http://logs.libuv.org/node.js/latest.

Note that although the bot uses a few different nicknames (`{slurp}`, `{slurp-nodejs}`), it always authenticates itself to nickserv, with login `slurp`.

**Comment by piscisaureus** [comment]
@ljharb Just curious - what's the point of banning "unofficial" log bots? As long as they're quiet and don't engage in excessive join/part traffic, I don't see any harm in having them around.

**Comment by williamkapke** [comment]
It has continued to keep running now - mission accomplished :+1: 

Thanks all.

**Comment by williamkapke** [comment]
Oops- that last issue didn't show until after I closed. Sorry @piscisaureus didn't mean to cut you off with your question to @ljharb

**Comment by ljharb** [comment]
@piscisaureus for one, it's against freenode policy for a bot to log content without explicit permission of the channel owner.

**Comment by williamkapke** [comment]
Logs appear to have been doing fine for awhile now. Closing.
