### ISSUE TITLE
Increasing the OpenSSF Scorecard results

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/nodejs.org#5659]
### Enter your suggestions in details:

The @nodejs/security team is running an initiative to improve the OpenSSF Scorecard results at organization level (https://github.com/nodejs/security-wg/issues/859). In the last security team meeting we had discussed about the current scoring for the `nodejs/nodejs.org` repository. Seems like there is a [decrease of -1.7 points](https://github.com/nodejs/security-wg/issues/1079) since the last review (2 weeks ago)

> | Repository | Commit | Score | Score Delta | Report | StepSecurity | 
> | -- | -- | -- | -- | -- | -- |
> | [nodejs/nodejs.org](https://github.com/nodejs/nodejs.org) | [1fbd908](https://github.com/nodejs/nodejs.org/commit/1fbd908497ece0c5b08c7cc8f7494d7a12e7001f) | 6.4 | -1.7 / [Details](https://kooltheba.github.io/openssf-scorecard-api-visualizer/#/projects/github.com/nodejs/nodejs.org/compare/708111a7e1cb7b26d8112c7238fd73574fa5ddc8/1fbd908497ece0c5b08c7cc8f7494d7a12e7001f) | [View](https://kooltheba.github.io/openssf-scorecard-api-visualizer/#/projects/github.com/nodejs/nodejs.org/commit/1fbd908497ece0c5b08c7cc8f7494d7a12e7001f) | [Fix it](https://app.stepsecurity.io/securerepo?repo=nodejs/nodejs.org) |

In [this recorded video](https://www.youtube.com/live/7MGcnoZW_cE?feature=share&t=309) you can see the analysis from the team _(relevant from 05:08 to 14:53)_. Also the [relevant notes](https://github.com/nodejs/security-wg/blob/main/meetings/2023-08-17.md?plain=1#L27) from the meeting. 

Here are the highlighted parts from the [Delta Analysis](https://kooltheba.github.io/openssf-scorecard-api-visualizer/#/projects/github.com/nodejs/nodejs.org/compare/708111a7e1cb7b26d8112c7238fd73574fa5ddc8/1fbd908497ece0c5b08c7cc8f7494d7a12e7001f):

**Code-Review**

Determines if the project requires human code review before pull requests (aka merge requests) are merged
- Reasoning: found 11 unreviewed changesets out of 23 -- score normalized to 5
- Previous revision reasoning: found 5 unreviewed changesets out of 30 -- score normalized to 8
- [Documentation](https://github.com/ossf/scorecard/blob/7ed886f1bd917d19cb9d6ce6c10e80e81fa31c39/docs/checks.md#code-review)

**Dangerous-Workflow**

Determines if the project's github action workflows avoid dangerous patterns

```
Warn: untrusted code checkout '${{ github.event.pull_request.base.ref }}': .github/workflows/pull-request-target.yml:38
Warn: untrusted code checkout '${{ github.event.pull_request.base.ref }}': .github/workflows/pull-request-target.yml:82
Warn: untrusted code checkout '${{ github.event.pull_request.base.ref }}': .github/workflows/pull-request-target.yml:125
```
- [Code reference](https://github.com/nodejs/nodejs.org/blob/main/.github/workflows/pull-request-target.yml)
- [Documentation](https://github.com/ossf/scorecard/blob/7ed886f1bd917d19cb9d6ce6c10e80e81fa31c39/docs/checks.md#dangerous-workflow)

### Next steps
- [x] Open PRs with some quick win improvements (Codeql, deps reviwew...) @UlisesGascon 
  - [x] #5660
  - [x] #5661
  - [x] #5662
  - [ ] #5663
- [ ] Discuss about the relevant things that came out from the delta analysis.

**Comment by ovflowd** [comment]
I kinda disagree with the reasoning imposed here. Yes, we are checking out code, but supposedly only the "base" refs for a given PR, which usually mean that the base branch of this repository is used.

Also I wonder if on forks it would checkout the base ref of the fork or our repository.

Anyhow, I need to understand the reasoning why checking out the base branch ref is unsafe, as it is actually the recommended approach by GitHub to stay safe.

**Comment by ovflowd** [comment]
@UlisesGascon scores went up to 8.6 :)

So... closing as the scores went up 🎉
