### ISSUE TITLE
Can't make v5.8.0 release post

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/nodejs.org#566]
```
Jeremiah@Jeremiahs-MacBook-Pro ~/D/nodejs.org> node scripts/release-post.js
Some error occured here! Error: Couldn't find @author of 5.8.0 release :(
    at findAuthorLogin (/Users/Jeremiah/Documents/nodejs.org/scripts/release-post.js:162:48)
    at /Users/Jeremiah/Documents/nodejs.org/scripts/release-post.js:98:24
    at process._tickCallback (node.js:406:9)
```

cc @TheAlphaNerd I don't see any v4.4.0 blog, did you have the same issue?

**Comment by Fishrock123** [comment]
Nvm, looks like I had a period instead of a comma in the message. Not much i can do about that since it's already tagged, but I also don;t think it warrants updating the regex except locally to make this one. Closing.

**Comment by MylesBorins** [comment]
@Fishrock123 I was waiting until this morning to release the post

edit: and it is done :smile:
