### ISSUE TITLE
Node v19.7.0 linux x64 - 500 Internal Server Error

### ISSUE THREAD

**Issue by pedrofsantoscom** [nodejs/nodejs.org#5666]
### URL:

https://nodejs.org/dist/v19.7.0/node-v19.7.0-linux-x64.tar.gz

### Browser Name:

Chrome

### Browser Version:

115.0.5790.170

### Operating System:

macOS 12.6.8

### How to reproduce the issue:

1. https://nodejs.org/dist/v19.7.0/node-v19.7.0-linux-x64.tar.gz
2. 
<img width="1457" alt="image" src="https://github.com/nodejs/nodejs.org/assets/2325978/029c29a9-aded-4c70-9512-73519e840dbf">

**Comment by mariusglauer** [comment]
Confirming that we have similar HTTP issues right now with nodejs.org

**Comment by pedrofsantoscom** [comment]
this one https://nodejs.org/dist/v19.7.0/node-v19.7.0-linux-x64.tar.gz seems to be working now

**Comment by blimmer** [comment]
Seeing this on our CI builds as well:

> Downloading https://nodejs.org/dist/v18.13.0/node-v18.13.0-linux-arm64.tar.xz...
> ####                                                                       6.1%curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)

**Comment by javifraile** [comment]
We have this error right now too with this version of Node
https://nodejs.org/dist/v16.7.0/node-v16.7.0-linux-x64.tar.gz

**Comment by ovflowd** [comment]
Duplicate of https://github.com/nodejs/nodejs.org/issues/4495
