### ISSUE TITLE
Delete NodeFeatures Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5684]
The NodeFeatures component is not being ported to the new website design.

Remove all references to it within the current codebase. This includes:

- [ ] all files within [components/Home/NodeFeatures ](https://github.com/nodejs/nodejs.org/tree/main/components/Home/NodeFeatures )
   - [ ] if this is the last work within a higher directory, delete that too
   - [ ] perform a global search for the component. If found elsewhere, remove its usage
- [ ] all references to the component within [internationalization files](https://github.com/nodejs/nodejs.org/tree/main/i18n/locales).
   - [ ] look for `components.home.nodeFeatures.*` keys within `i18n/locales/{locale}.json` files
   - [ ] ensure these files remain valid JSON by being mindful of commas when deleting lines

As with all contributions, run local commands to ensure the deletion was cleanly executed:
- [ ] `npx turbo lint`
- [ ] `npx turbo format`
- [ ] `npx turbo test`
- [ ] `npx turbo build`
- [ ] `npx turbo serve`

**Comment by AugustinMauroy** [comment]
Can I work on it ?

**Comment by ovflowd** [comment]
> Can I work on it ?

Definitely! No need to ask :) all these issues are ready to be worked on!
