### ISSUE TITLE
Add Tailwind and configure base tokens

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5686]
We’re going to adopt[ Tailwind ](https://tailwindcss.com/)CSS as a base design system. This will be useful for font-sizes, spacing, border-radius and pretty much crafting any component.

## Setup

Add tailwind as a dev dependency

```
npm install -D tailwindcss
```

Create a TypeScript file at the root of the project, `tailwind.config.ts`

```ts
import type { Config } from 'tailwindcss'

export default {
  content: [],
  theme: {
    extend: {},
  },
  plugins: [],
} satisfies Config
```

## Color

[Color configuration](https://tailwindcss.com/docs/customizing-colors#using-custom-colors) should come from the [Figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=469-11941&mode=design&t=or2YQ9xeYbw47kZf-4). 

![image](https://github.com/bmuenzenmeyer/nodejs.org/assets/298435/f877edbf-31bf-45c8-90d3-ab51c889a35d)

In order we will have these base color families:
- Green
- Neutral
- Danger
- Warning
- Info
- Accent 1
- Accent 2
- White and Black

Each has 9 weights (100, 200, 300, 400, 500, 600, 700, 800, 900) inspectable within the Figma, and definable within Tailwind using the [additional colors config](https://tailwindcss.com/docs/customizing-colors#adding-additional-colors)

A future issue will create storybook stories for these colors. Do not do that as scope of this issue.  

## Text

[Customize the text configuration](https://tailwindcss.com/docs/font-size#customizing-your-theme) according to the [Figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=415-8257&mode=design&t=or2YQ9xeYbw47kZf-4). There are 11 sizes:

- xs
- sm
- base
- lg
- xl
- 2xl
- 3xl
- 4xl
- 5xl
- 6xl
- 7xl

Turn off 8xl and 9xl if possible. It is not in the design.

![image](https://github.com/bmuenzenmeyer/nodejs.org/assets/298435/96552777-aecf-41f5-ac18-820638118301)

[Configure the default font-family](https://tailwindcss.com/docs/font-family#customizing-your-theme) as Open Sans. It can be intergrated with Next using `next/font` using [their Tailwind documentation](https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#with-tailwind-css).

Update the [themeProvider](https://github.com/nodejs/nodejs.org/blob/main/providers/themeProvider.tsx) used by our Storybooks to inject the styles. (Either removing this body global style) and replace with a className surrounding children. This part may require iteration to get right.

A future issue will create storybook stories for these text sizes and styles. Do not do that as scope of this issue.

**Comment by AugustinMauroy** [comment]
I had started to work on that 😁.
Should I remove `_token.scss`?

**Comment by ovflowd** [comment]
> I had started to work on that 😁.
Should I remove _token.scss?

No. Removal of the current `styles/new` folder is unrelated to this issue.

**Comment by araujogui** [comment]
Some questions:

1. What about the other dependencies? Like PostCSS and Autoprefixer.
2. Why `content` property from `tailwind.config.ts` is empty? 
3. And the `@tailwind` directives?

**Comment by bmuenzenmeyer** [comment]
> * What about the other dependencies? Like PostCSS and Autoprefixer.
> * Why `content` property from `tailwind.config.ts` is empty?
> * And the `@tailwind` directives?

If you know a better way to configure TW, please jump in. This scope was mostly taken from the getting started docs and I am very much in favor of us doing what makes sense for the project or what more experienced folks have discovered in the TW ecosystem. 

I suggest we go slow in considering what's best. Can you elaborate on what we need here?

**Comment by araujogui** [comment]
To ensure proper functionality with Next.js, these steps are essential. There's an exclusive Next.js guide in the Tailwind documentation https://tailwindcss.com/docs/guides/nextjs and here https://nextjs.org/docs/app/building-your-application/styling/tailwind-css.

We need to install `postcss` and `autoprefixer`, set up the `content` property and add `@tailwind` directives to a global css file. I can work on this.

**Comment by ovflowd** [comment]
Thanks @araujogui, Indeed, @AugustinMauroy's PR is missing some of the required dependencies.

Feel free to jump on that PR and push changes, as maintainers are allowed to modify PRs, and we want to prevent this from getting stuck.

**Comment by ovflowd** [comment]
Note that I'm also concerned about having Storybook Previewing both the new design Component/Styles and Nodejs.dev (Old Website Redesign) ones.

Either we remove all `nodejs.dev` styles, or IDK, to be very honest.

**Comment by bmuenzenmeyer** [comment]
In case people missed it, I've also [cut issues for the remaining deletions](https://github.com/nodejs/nodejs.org/labels/website%20redesign%3A%20port) which will improve the situation. 

Glad we have such a group of folks here that can help define the right pathway forward. Thanks!

**Comment by ovflowd** [comment]
I assume we can hold/park the Tailwind PR/Work until the remaining deletions are done.

@bmuenzenmeyer I assume you also made an issue for deleting all the packages used by those components + the nodejs.dev styles folder? (Styles/new)?

**Comment by bmuenzenmeyer** [comment]
@ovflowd Not with that defined precision, no.

The components I suspected had dependencies like codebox, I mentioned.

The scope of this TW pull request could be to delete the styles. I now mention this in the companion pull request to this issue. Deleting them didn't seem as important once they were removed from `Preview.ts`? :shrug:

When I return from travel I can double check for dependencies... But for now suggest each PR review to scrutinize the environment for unused code (first party and third party)

**Comment by ovflowd** [comment]
> The scope of this TW pull request could be to delete the styles. I now mention this in the companion pull request to this issue. Deleting them didn't seem as important once they were removed from Preview.ts? 🤷

It's more like because `preview.ts` imports the nodejs.dev styles, but in order for TW to work we need a new `base.scss` that imports TW styles. (I thought Next.js magically did that, but it was stupid of me from thinking so, still even if it did, it would conflict with nodejs.dev ones)

**Comment by ovflowd** [comment]
> When I return from travel I can double check for dependencies... But for now suggest each PR review to scrutinize the environment for unused code (first party and third party)

Yeah, I can also do a 2nd pass on dependencies that can be removed by myself.
