### ISSUE TITLE
Delete BlockQuote Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5699]
The BlockQuote component is being ported to the new website design. But we will remove it for now so as to not complicate our styles.

Remove all references to it within the current codebase. This includes:

- [ ] all files within [components/Article/BlockQuote ](https://github.com/nodejs/nodejs.org/tree/main/components/Article/BlockQuote )
   - [ ] if this is the last work within a higher directory, delete that too
   - [ ] perform a global search for the component. If found elsewhere, remove its usage

Note - there is a typo in components/Blog/BlogCard/index.stories.tsx where the default import for BlogCard is `import BlockQuote from './index';` - do not change that yet

As with all contributions, run local commands to ensure the deletion was cleanly executed:
- [ ] `npx turbo lint`
- [ ] `npx turbo format`
- [ ] `npx turbo test`
- [ ] `npx turbo build`
- [ ] `npx turbo serve`

**Comment by bmuenzenmeyer** [comment]
This one is an outlier in the analysis. There is no equivalent component in the Figma. So when we get to needing blockquotes we will need to use the base TW styles or raise it to Hayden.

cc @ovflowd

**Comment by ovflowd** [comment]
Imma gonna post on Slack asking Hayden 👀

**Comment by vishal6557** [comment]
Hello, can I work on this?
