### ISSUE TITLE
Delete Banner Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5702]
# ⚠️ MAKE SURE TO DELETE THE CORRECT FILES HERE. SOME ARE OUT OF SCOPE

---

The Banner component is being ported to the new website design. But we will remove it for now so as to not complicate our styles.

Remove all references to it within the current codebase. This includes:

- [ ] all files within [components/Common/Banner](https://github.com/nodejs/nodejs.org/tree/main/components/Common/Banner)
   - [ ] if this is the last work within a higher directory, delete that too
   - [ ] perform a global search for the component. If found elsewhere, remove its usage
- [ ] all references to the component within [internationalization files](https://github.com/nodejs/nodejs.org/tree/main/i18n/locales).
   - [ ] look for `components.common.banner.*` keys within `i18n/locales/{locale}.json` files
   - [ ] ensure these files remain valid JSON by being mindful of commas when deleting lines

> **DO NOT DELETE** `components/Home/Banner.tsx`

As with all contributions, run local commands to ensure the deletion was cleanly executed:
- [ ] `npx turbo lint`
- [ ] `npx turbo format`
- [ ] `npx turbo test`
- [ ] `npx turbo build`
- [ ] `npx turbo serve`

**Comment by bmuenzenmeyer** [comment]
@ovflowd again, a review on the scope of this one as it's a bit different with a potentially live version of this file too.

**Comment by ovflowd** [comment]
> @ovflowd again, a review on the scope of this one as it's a bit different with a potentially live version of this file too.

Gotcha!
