### ISSUE TITLE
Delete DarkModeToggle Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5703]
The DarkModeToggle component is being ported to the new website design. But we will remove it for now so as to not complicate our styles.

Remove all references to it within the current codebase. This includes:

- [ ] all files within [components/Common/DarkModeToggle ](https://github.com/nodejs/nodejs.org/tree/main/components/Common/DarkModeToggle )
   - [ ] if this is the last work within a higher directory, delete that too
   - [ ] perform a global search for the component. If found elsewhere, remove its usage
- [ ] all references to the component within [internationalization files](https://github.com/nodejs/nodejs.org/tree/main/i18n/locales).
   - [ ] look for `components.header.buttons.toggleDarkMode` keys within `i18n/locales/{locale}.json` files
   - [ ] ensure these files remain valid JSON by being mindful of commas when deleting lines

As with all contributions, run local commands to ensure the deletion was cleanly executed:
- [ ] `npx turbo lint`
- [ ] `npx turbo format`
- [ ] `npx turbo test`
- [ ] `npx turbo build`
- [ ] `npx turbo serve`

**Comment by NextThread** [comment]
hey, can i work on this please?

**Comment by bmuenzenmeyer** [comment]
Please only ask on a single issue at a time. We want to limit WIP and give others a chance to contribute.

**Comment by NextThread** [comment]
> Please only ask on a single issue at a time. We want to limit WIP and give others a chance to contribute.

Ahhh, Okay.
Can i go with this?

**Comment by bmuenzenmeyer** [comment]
sure thing

**Comment by ovflowd** [comment]
@bmuenzenmeyer I think the issue description has an error. The i18n `components.header.buttons.toggleDarkMode` should not be removed as it is used on the current `nodejs.org` website.
