### ISSUE TITLE
Delete Dropdown and LanguageSelector Components

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5704]
The Dropdown and LanguageSelector components are being ported to the new website design. But we will remove themfor now so as to not complicate our styles.

Remove all references to them within the current codebase. This includes:

- [ ] all files within [components/Common/Dropdown ](https://github.com/nodejs/nodejs.org/tree/main/components/Common/Dropdown )
   - [ ] if this is the last work within a higher directory, delete that too
   - [ ] perform a global search for the component. If found elsewhere, remove its usage
- [ ] all files within [components/Common/LanguageSelector](https://github.com/nodejs/nodejs.org/tree/main/components/Common/LanguageSelector)
   - [ ] if this is the last work within a higher directory, delete that too
   - [ ] perform a global search for the component. If found elsewhere, remove its usage
- [ ] all references to the component within [internationalization files](https://github.com/nodejs/nodejs.org/tree/main/i18n/locales).
   - [ ] look for `components.common.languageSelector.*` keys within `i18n/locales/{locale}.json` files
   - [ ] ensure these files remain valid JSON by being mindful of commas when deleting lines

As with all contributions, run local commands to ensure the deletion was cleanly executed:
- [ ] `npx turbo lint`
- [ ] `npx turbo format`
- [ ] `npx turbo test`
- [ ] `npx turbo build`
- [ ] `npx turbo serve`

**Comment by NextThread** [comment]
hey, can i work on this please?

**Comment by vishal6557** [comment]
Can I pick this up if available?

**Comment by NextThread** [comment]
@vishal6557 already opened #5724
