### ISSUE TITLE
Delete PreviousNextLink Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5705]
The PreviousNextLink component is being ported to the new website design. But we will remove it for now so as to not complicate our styles.

Remove all references to it within the current codebase. This includes:

- [ ] all files within [components/Learn/PreviousNextLink ](https://github.com/nodejs/nodejs.org/tree/main/components/Learn/PreviousNextLink )
   - [ ] if this is the last work within a higher directory, delete that too
   - [ ] perform a global search for the component. If found elsewhere, remove its usage
- [ ] all references to the component within [internationalization files](https://github.com/nodejs/nodejs.org/tree/main/i18n/locales).
   - [ ] look for `components.learn.previousNextLink.*` keys within `i18n/locales/{locale}.json` files
   - [ ] ensure these files remain valid JSON by being mindful of commas when deleting lines

As with all contributions, run local commands to ensure the deletion was cleanly executed:
- [ ] `npx turbo lint`
- [ ] `npx turbo format`
- [ ] `npx turbo test`
- [ ] `npx turbo build`
- [ ] `npx turbo serve`

**Comment by HinataKah0** [comment]
Oops, my bad. I just realized this issue isn't in ready.

**Comment by ovflowd** [comment]
I guess @bmuenzenmeyer just forgot to put it on ready
