### ISSUE TITLE
The link to node-v18.13.0-linux-x64.tar.xz returns a 500 error

### ISSUE THREAD

**Issue by Kwomkwommr** [nodejs/nodejs.org#5719]
### URL:

https://nodejs.org/dist/v18.13.0/node-v18.13.0-linux-x64.tar.xz

### Browser Name:

Firefox

### Browser Version:

116.0.3

### Operating System:

Windows 10

### How to reproduce the issue:

Open the link and you get a 500 error.

**Comment by pal03377** [comment]
This seems to be the case as well for 
https://nodejs.org/dist/v18.14.0/node-v18.14.0-linux-x64.tar.gz

Strangely, when you 
1. Open the URL
2. Edit it to be the other one (e.g. from 18.14.0 to https://nodejs.org/dist/v18.13.0/node-v18.13.0-linux-x64.tar.gz)

...the download works (?)

**Comment by pal03377** [comment]
Probably a duplicate of #4495 though

**Comment by josetaveiragomes** [comment]
Also happening for version: [https://nodejs.org/dist/v16.20.1/node-v16.20.1-linux-x64.tar.gz](https://nodejs.org/dist/v16.20.1/node-v16.20.1-linux-x64.tar.gz)

**Comment by UnoMomento12** [comment]
Same problem for https://nodejs.org/dist/v16.13.2/node-v16.13.2-win-x64.7z

**Comment by ljharb** [comment]
Duplicate of #4495.

**Comment by ovflowd** [comment]
Hey y'all. Just a FYI that we have a pinned Issue. Pretty please, avoid creating duplicated issues. Thanks.

![image](https://github.com/nodejs/nodejs.org/assets/12037269/22ddf001-2324-49cf-868e-f831283c2dfd)

**Comment by ovflowd** [comment]
Duplicate of https://github.com/nodejs/nodejs.org/issues/4495
