### ISSUE TITLE
serve: TypeError: cookies is not iterable

### ISSUE THREAD

**Issue by benhalverson** [nodejs/nodejs.org#5726]
### URL:

localhost:3000

### Browser Name:

any

### Browser Version:

any

### Operating System:

any

### How to reproduce the issue:

I re-cloned this repo and followed the instructions to start a local server.
I am getting this error in the server log
serve: TypeError: cookies is not iterable
```
serve: TypeError: cookies is not iterable
serve:     at get [headers map sorted] (node:internal/deps/undici/undici:1844:34)
serve:     at node:internal/deps/undici/undici:1865:43
serve:     at Headers Iterator.next (node:internal/deps/undici/undici:1108:26)
serve:     at toNodeOutgoingHttpHeaders (/home/ben/projects/nodejs.org/node_modules/next/dist/server/web/utils.js:106:31)
serve:     at handleRoute (/home/ben/projects/nodejs.org/node_modules/next/dist/server/lib/router-utils/resolve-routes.js:301:89)
serve:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
serve:     at async resolveRoutes (/home/ben/projects/nodejs.org/node_modules/next/dist/server/lib/router-utils/resolve-routes.js:483:28)
serve:     at async handleRequest (/home/ben/projects/nodejs.org/node_modules/next/dist/server/lib/router-server.js:320:102)
serve:     at async requestHandler (/home/ben/projects/nodejs.org/node_modules/next/dist/server/lib/router-server.js:464:13)
serve:     at async Server.<anonymous> (/home/ben/projects/nodejs.org/node_modules/next/dist/server/lib/start-server.js:117:13)
```

I was able to work around this error by manually adding a cookie in the chrome dev tools called `NEXT_LOCALE` with the value of `en` and the error went away. 
The other way was to change the `export const config = { matcher: '/' };` to something that doesn't actually exist.

**Comment by ovflowd** [comment]
Really interesting. What OS are you using? Because I doubt this applies to "any" OS, as it's working on my macOS and many other's 🤔  (It's also working on Prod and on CI)

**Comment by ovflowd** [comment]
Apparently this is a bug of a specific Node.js version: https://stackoverflow.com/questions/76969812/typeerror-cookies-is-not-iterable-next-js

Solution: Upgrade Node.js to latest LTS (v18.17.1) (for example)

**Comment by ovflowd** [comment]
Closing as this is not an issue of this repository.
