### ISSUE TITLE
Translation Guidelines link in README go to 404

### ISSUE THREAD

**Issue by regseb** [nodejs/nodejs.org#5747]
### URL:

https://github.com/nodejs/nodejs.org#contributing

### Browser Name:

Firefox

### Browser Version:

117.0

### Operating System:

Ubuntu 22.04.3 LTS

### How to reproduce the issue:

1. Go to [Contributing](https://github.com/nodejs/nodejs.org#contributing) chapter in README.
2. Click on _Translation Guidelines_

- Actually, you go to https://github.com/nodejs/TRANSLATION.md (404)
- We expect to go to https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md

---

The link in the [_Relevant Links_](https://github.com/nodejs/nodejs.org#relevant-links) chapter works. I think the problem is that the link is in a [block quote](https://github.com/nodejs/nodejs.org/blob/7ed2059/README.md?plain=1#L60-L61).

**Comment by ovflowd** [comment]
> We expect to go to [main/CONTRIBUTING.md](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md?rgh-link-date=2023-09-04T14%3A22%3A49Z)

Wrong. Expect to go to `TRANSLATION.md`. This seems to be a bug on GitHub-end. I'll update the README to use a direct link.

**Comment by ovflowd** [comment]
Solved by https://github.com/nodejs/nodejs.org/commit/2e70cb5d49f2cd40677ade15b85aab3403e7adb5
