### ISSUE TITLE
Create `Badge` component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5759]
Create a `Badge` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=495-1830&mode=design&t=hIIOhlH7Z09bkHIB-4). 

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/90b2b970-c86a-49e3-9a19-63faeacaaac5)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Create a new directory called `Badge` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code.
- Use the new tailwind color and typography system to assign properties. For example, the `Error Badge` uses `Error/600` per the figma.
- The `@heroicons/react` module has the icon `arrow-right` available for use
- Add a storybook story file `components/Common/Badge/index.stories.tsx` which exercises each of the badge's states.

Suggested props include:

- `type` (enum):  `default` | `error` | `warning`
- `badgeText` (string):  (`new` in the figma)
- `message` (string): (`OpenJS Foundation Cer....` in the figma) 
- `url` (`typeof next/link` or ??): Perhaps discuss how best to do this in our i18n environment 

There are 6 states to capture within styles and stories:

#### Light

- Default, Light
- Error, Light
- Warning, Light

#### Dark

- Default, Dark
- Error, Dark
- Warning, Dark

**Comment by bmuenzenmeyer** [comment]
@ovflowd defering to you and others on how to best structure the React and i18n required

**Comment by ovflowd** [comment]
> @ovflowd defering to you and others on how to best structure the React and i18n required

Wdym with the `React` part? i18n should be done following our TRANSLATION.md guidelines, if you want to attach that guideline here feel free.

**Comment by bmuenzenmeyer** [comment]
I mean, as a generic component, these should be getting pretty much all input from props of the caller,right? 

I am trying to think of whether or not it needs to be wired up to that at this stage of the React tree, or if all data is still a pass-through. 

I hope that makes sense

**Comment by ovflowd** [comment]
All components (or base components) of the design system should be simple and receive direct props of what they should render.

When we reach composite components then we can think of that.

**Comment by canerakdas** [comment]
Hey @bmuenzenmeyer can I work on this?

**Comment by bmuenzenmeyer** [comment]
yes @canerakdas you may!
