### ISSUE TITLE
Create `Banner` component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5760]
Create a `Banner` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=495-1805&mode=design&t=hIIOhlH7Z09bkHIB-4). 

This is the final port of the [Banner component recently deleted](https://github.com/nodejs/nodejs.org/issues/5702)

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/681e216c-9156-46a2-9c89-b4d3930f2006)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Create a new directory called `Banner` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code.
- Use the new tailwind color and typography system to assign properties. For example, the `Banner Default` uses `Green/600` per the figma.
- The `@heroicons/react` module has the icon `arrow-up-right` available for use
- Add a storybook story file `components/Common/Banner/index.stories.tsx` which exercises each of the component's states.

Suggested props include:

- `type` (enum):  `default` | `error` | `warning`
- `text` (string):  (`Claudio just took down web server. Get the latest updates here` in the figma)
- `url` (`typeof next/link` or ??): Perhaps discuss how best to do this in our i18n environment 

There are 3 states to capture within styles and stories:

- Default
- Error
- Warning

**Comment by AugustinMauroy** [comment]
Can I work an that ?

**Comment by bmuenzenmeyer** [comment]
sure thing @AugustinMauroy !
