### ISSUE TITLE
Create `CrossLink` component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5761]
Create a `CrossLink` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=429-3698&mode=design&t=hIIOhlH7Z09bkHIB-4). 

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.
- ❗ Review the [translation guide](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md), especially how to [add new keys](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md#adding-new-translation-keys).

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/e405fc07-7834-43bd-b748-8686dab87f9f)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)
🌐 This story requires some internationalization support. Slow down!

- Create a new directory called `CrossLink` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code. (This location may change in the future.)
- The `@heroicons/react` module has the icons `chevron-right` and `chevron-left` available for use
- Add a storybook story file `components/Common/CrossLink/index.stories.tsx` which exercises each of the component's states.
- `Prev` and `Next` must be internationalized. Add new keys `components.common.crossLink.prev` and `components.common.crossLink.next` to the `i18n/locales/en.json` file. `FormattedMessage` from `react-intl` should be used to reference the keys. Look for examples elsewhere in the codebase.

Suggested props include:

- `direction` (enum):  `left` | `right`
- `text` (string):  (`How to install Node.js` in the figma)
- `url` (`typeof next/link` or ??): Perhaps discuss how best to do this in our i18n environment 

There are 4 states to capture within styles and stories:

#### Light

- Prev
- Next

#### Dark

- Prev
- Next

### Open Questions, to Discuss

- Do the components layout together as indicated, occupying half the available horizonal space each?

Yes, but future layout code will worry about this. They will occupy half available horizontal space. For now, they can be block or inline-block elements.

- Should the content truncate as indicated?

The figmas suggest yes. If the content overflows the available width, truncate.

**Comment by HinataKah0** [comment]
If no one take this, I'll work on it 😄 
This is my first time writing a component from scratch so I'll need some time to tinker around with the styling

**Comment by ovflowd** [comment]
> If no one take this, I'll work on it 😄 This is my first time writing a component from scratch so I'll need some time to tinker around with the styling

We're here to help!
