### ISSUE TITLE
in the OSs list why is Linux no. 3?

### ISSUE THREAD

**Issue by peterjosvai** [nodejs/nodejs.org#577]
okay, I suppose, the concept is something like:  most used OSs (Win and Mac) are on top of the list because most people use it :) 

but if it was that, it'd make no logical sense....
It'd only be logical if one user wanted to download the Windows-version most of the times -- in this case, it'd be a help for the users, cause their most used version would be there...

but this is not the case, obviously...
everybody wants one version (at a time, at least)
and most people will download a given version only like a few times during a whole year...
so putting the “most used” OS first does not help anyone... 

and even if users were downloading node.js frequently, like on a daily basis...
what problem would WIN users have if the had to look for "W" to find Win -- and it wouldn't be #1 on the list ? :) 

my guess: it'd be no problem for a Win user ... :) 

So, all in all, what exactly does this listing "convention" serve? 
besides unawares promoting the hegemony of Microsoft and Apple by unawares accepting the order of OSs the way it is propagated everywhere...
Sure, I understand the commercial companies – but free software developers.. no

okay, just one last argument:
imagine someone who's new to linux... or is thinking about switching to Linux..
she or he goes to websites and sees listing of OSs in this “order” -- the more powerful ones first...
what will be the impression of this person?
what perception will she or he have of Linux – my guess: “it's not that much supported" ?

:: suggestion:
Browsers compete, OSs compete, databases compete – and the BIG ONES have huge advantages – including taking profit even as we speak... Why not to give some advantage to the open source, non-corporate projects, like treating them as equal in rank with the BIG ONES ? :) 

All I'm suggesting is the rethinking of this policy of putting the BIG ones first...
the BIG OSs first and Linux only after them...
Let Linux be found at “L” and Mac at “M” and so on... 

Linux deserves this fair treatment – doesn't it? :) 

![node-website](https://cloud.githubusercontent.com/assets/13543101/13761082/ceb06cfc-ea36-11e5-8da8-6bca35c32da6.jpg)

**Comment by MylesBorins** [comment]
Hey @peterjosvai thanks for posting.

One thing that is worth paying attention to on that list is that the `double click installers` are included first. Specifically the `.msi` and the `.pkg`.  There is currently no double click installer for the linux platform, and likely never will be.

If we start with the premise that individuals newer to learning development are more likely be on Windows or Mac (in that order) it may be easy to conclude that having the links to the installers at the top of the page would help them more than hurt those on the linux platform

If you look at the [statistic](https://nodejs.org/metrics/summaries/os.png) you will see that Linux is by FAR the largest consumer of our downloads, with more than double the downloads of 

Personally I'm -1 on the change as I believe it would negatively effect new developers

**Comment by rvagg** [comment]
Without digging in to details, I bet that if you trim the Linux download stats to include only those using a browser, the numbers would be a tiny fraction of the total.

It's the installers that matter most here, particularly for Windows where they don't have easier ways to download Node (OSX has Brew and can also use `curl|tar`). So I'm with @TheAlphaNerd on not touching this, although we are looking at simplifying the initial download table by removing the _secondary_ platforms to another table: https://github.com/nodejs/nodejs.org/pull/564

**Comment by mikeal** [comment]
Here's the website stats.

<img width="401" alt="screen shot 2016-03-14 at 8 06 12 pm" src="https://cloud.githubusercontent.com/assets/579/13766576/499161ea-ea20-11e5-9fc1-c3f7a3c423f7.png">

**Comment by peterjosvai** [comment]
hi Myles,

thanks for giving it a thought...

however, I think that you're still thinking within a certain logic ... 
namely that if MORE people use Windows, it should be on the top if the 
list ...
I think this is a wrong logic in every sense...

how would a new (or old) developer be hurt if they find their presently 
used OS in alphabetical order, and (OMG) next to Linux ? :)

the logic of "putting double click installers" first simply fails...

```
it should aim to help a GIVEN user...
that is, per OS there could be the most likely version put first...
(this is clean and positive logic)

but putting the most used (by the masses of us), the most "likely"
Os on the top ... does not help a given user.. it helps the given
corporation .. a lot .. for producing  a perception for masses of
users that "most people use Win and Mac"
```

my assertion:
putting the most used OSs first is a representation of power and doesn't 
help a given person ...
but helps the given corporation behind that Os...

as for the overall appearance (including corporate logos)

```
we could ask corporate image experts on the value of appearing first
in lists.. of having your logo shown where your BIGGEST (any real)
competitor's doesn't

-- get in the top of the list
-- get their logo displayed ..

My guess is, that the value for this PRIVILEGE is vast ...
and according to e = mc2, if it is a vast value for one competitor,
it must be a vast loss for the other :) 
```

Peter

**Comment by benjamingr** [comment]
I vote we keep the current behavior with Windows on top. 
Linux users would likely not install it from the website anyway (I don't).

**Comment by peterjosvai** [comment]
Mikeal, hi, I don't want to interrupt.. butt to insert one note...

I can see you're conversation is boiling down to
deciding what's fair in regards of user statistics ...

BUT --

```
if you're talking about helping people to download... and within
that, helping people who uses some OSs that more people use than
other OSs... or talking about helping the MAJORITY of your
downloaders...
you're (in my POV) making up a fictitious context...
(not to mention that to download something is NOT a difficult task
at all, and that we are talking about software developers !! :))
```

once again (I won't bring it up again):

```
the issue is misrepresentation of Linux (FREE software)
the other ones get on top of the list, the other ones get their
logos -- Linux doesn't ...
which is shaping the future in terms of how likely people are to end
up using Linux or Mac or Win...

I interpret the issue as fair and equal treatment for Linux :)
(seriously :))

would that hurt Microsoft? and if it did, would that be a problem...
cause even if Microsoft was a software developing community too,
what Linux would gain is only being treated equally.. no favoritism,
no privileges ...
```

thanks to all of you for giving a thought to considerations!

the future -- including the future of free software -- is our common 
responsibility.... just like environment in other sense

thank you

Peter

**Comment by peterjosvai** [comment]
Bejamin, just a hint: I am a linux user... and guess what I am doing at 
this very moment, too...

/OFF  --  I don't want to disturb your conversation... I understand that 
this is not really a place where a "user" gets a say, although software 
developing meritocracy originally involves the user as a contributor, too ..

bu, as for what I'm doing right now:  I'm downloading a version which 
would run on my arm6 piece -- despite how you'd go about it, I'm trying 
to do this through this website -- which I would call a classic approach
the website literally sucks, I can even see: arm6 -- but why would I 
assume that it is for linux?
I know nothing about windows and mac and other OSs... and until 
yesterday I had no idea that this pc of mine is arm6 .. and I am a linux 
user ...

Seriously, how can you assume that linux users are like yourself? that 
is, they only need what you say you need ....
while Microsoft's clients, whom you seem to like to serve as business 
class, at the top, need to get everything that could help their 
top-lives :)

you are linux user, okay ... but I am a linux user too, and even if 
there was more of you, which I doubt, I 'd still qualify just as much of 
linux user as you are...
:) :) I mean it ...

you know, Linux is  a popular OS, and it is intelligent, and it is 
supposed to be used with ease by ANYONE ... just like Microsoft's "top" 
product :))

policies regarding linux users as geeks and windows users as ignorant 
have a serious causation, actually .. .
Microsoft gains a big time image advantage for free, while Linux does 
not .. it is pushed back into the shed ...

OFF/

**Comment by phillipj** [comment]
Closing this for now as all votes has been in favor of keeping it as is.
