### ISSUE TITLE
Pardot integration (email subscription) needs help

### ISSUE THREAD

**Issue by williamkapke** [nodejs/nodejs.org#578]
Pardot is used for the "subscribe to news about the Node.js Foundation" in these locations:
https://github.com/nodejs/nodejs.org/search?q=pardot

After filling out the form, it just disappears... and stays missing even after refresh. Not even an email confirmation.

After some digging I found:

> By default, a prospect who fills out a form and then returns to the form page within a 10 minute window will not see the form again and will instead see the Thank You Content (or be redirected based on your other settings). This option disables that 10 minute window.

... I'm guessing that the _Thank You Content_ is blank...?

See: [Control What A Prospect Sees After the Form Submits](http://help.pardot.com/customer/portal/articles/2132705-forms-overview#control-what-a-prospect-sees-after-the-form-submits)

It doesn't look like this can be fixed with a PR- I think it requires someone with access to the Pardot account? :(

**Comment by stevemao** [comment]
Yup, and I don't think i have received any news.

**Comment by fhemberger** [comment]
ping @mikeal

**Comment by williamkapke** [comment]
To date, I still have not gotten any emails. 2 board meetings have been hosted online now- and I didn't know either of them were happening. I would think I an email would be sent about that :/

**Comment by mikeal** [comment]
We haven't announced the meetings anywhere but twitter, not have we really used that email list much.

We're working on a new newsletter (kicking off in July when the new budget rolls around) that will replace that.

@hackygolucky is working on a PR to add a page about the board meetings to the website.

**Comment by williamkapke** [comment]
Should we just remove this feature then?

**Comment by mikeal** [comment]
This does sign you up for something, I'm just not sure that we've ever used it :/

**Comment by gtewallace** [comment]
Hi all,

I'll look into the thank you field.

It adds you to our master email list, which we haven't used too much but we do use it.

Lately we've been sending emails to encourage people to submit talks for Node.js Interactive and also to announce early bird registration prices.

Earlier in the year we used it to ask people to take the Node.js User Survey.

Definitely more we can be doing with this channel, and would love suggestions.

Greg

**Comment by williamkapke** [comment]
@gtewallace great thanks! FWIW, I searched my inbox and found just 1 email on May 4th about Node.js Interactive. Nothing about early bird prices or a survey though.

**Comment by gtewallace** [comment]
survey email would have been in January, so maybe before you signed up?

some of our emails only go to certain geos - for instance the early bird pricing email is going only to EMEA contacts.

**Comment by gtewallace** [comment]
thank you field has been set-up and should work as expected now.

**Comment by williamkapke** [comment]
Thanks for fixing this @gtewallace. I just tested and got the "Thank You For Signing Up!" message.
