### ISSUE TITLE
FYI: Node.js blog posts are throwing a 500

### ISSUE THREAD

**Issue by leerob** [nodejs/nodejs.org#5804]
For awareness: https://nodejs.org/en/blog/release/v18.18.0

<img width="1602" alt="CleanShot 2023-09-19 at 08 31 16@2x" src="https://github.com/nodejs/nodejs.org/assets/9113740/13e4f444-5cb6-47e0-baa1-0bddacea7af3">

**Comment by ovflowd** [comment]
Investigating

**Comment by ovflowd** [comment]
https://github.com/nodejs/nodejs.org/pull/5806 Fixes

**Comment by balazsorban44** [comment]
Nice, works now!
