### ISSUE TITLE
Add static, external links to sitemap

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5813]
Add these links to the sitemap, currently on the footer of the site.

Add these to the [next.constants.mjs](https://github.com/nodejs/nodejs.org/blob/main/next.constants.mjs) file and then `app/sitemap.ts` - after  https://github.com/nodejs/nodejs.org/pull/5812 merges 

[Terms of Use](https://terms-of-use.openjsf.org/) | [Privacy Policy](https://privacy-policy.openjsf.org/) | [Bylaws](https://bylaws.openjsf.org/) | [Code of Conduct](https://code-of-conduct.openjsf.org/) | [Trademark Policy](https://trademark-policy.openjsf.org/) | [Trademark List](https://trademark-list.openjsf.org/) | [Cookie Policy](https://www.linuxfoundation.org/cookies)

**Comment by AugustinMauroy** [comment]
Can I take it ?

**Comment by bmuenzenmeyer** [comment]
sure - but I think we need #5812 first

**Comment by AugustinMauroy** [comment]
fix in : https://github.com/nodejs/nodejs.org/pull/5821
