### ISSUE TITLE
Cloudflare caching 500 responses

### ISSUE THREAD

**Issue by broksonic21** [nodejs/nodejs.org#5818]
### URL:

https://nodejs.org/dist/v18.17.1/node-v18.17.1-darwin-arm64.tar.gz

### Browser Name:

any http call

### Browser Version:

any http call

### Operating System:

any http call

### How to reproduce the issue:

```
curl -I https://nodejs.org/dist/v18.17.1/node-v18.17.1-darwin-arm64.tar.gz
HTTP/2 500
date: Wed, 20 Sep 2023 17:19:43 GMT
content-type: text/html
cf-cache-status: HIT
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
```

See that it's a HIT --- Looks like Cloudflare is configured to cache 500 responses. It goes away eventually if you retry, but this causes install issues across the ecosystem. Can this be changed to not cache so it gets to 200s easier

**Comment by bmuenzenmeyer** [comment]
@ovflowd or anyone on @nodejs/web-infra with cloudflare access - can you look into this?

**Comment by ovflowd** [comment]
We are aware of this. There is an issue already with this. I've been waiting the @nodejs/build WG to work on this for a month for now https://github.com/nodejs/build/issues/3473

cc @richardlau or @Trott if for god sake someone could pretty please take care of this little task

**Comment by Trott** [comment]
> cc @richardlau or @Trott if for god sake someone could pretty please take care of this little task

I don't have access to Cloudflare so I can't do it. I left another comment on the issue, though....

**Comment by ovflowd** [comment]
> > cc @richardlau or @Trott if for god sake someone could pretty please take care of this little task
> 
> 
> 
> I don't have access to Cloudflare so I can't do it. I left another comment on the issue, though....

Sorry, I forgot you don't have 🫠

**Comment by MattIPv4** [comment]
Should we open an issue with the build WG to look at getting web infra folks full access to Cloudflare? I'm not sure what the build WG process is for making Cf changes at the moment, but it seems like it is _incredibly_ slow, resulting in a poor experience for users, and the web infra team can't really do anything to fix it...

**Comment by ovflowd** [comment]
I think we should open an issue on the admin repo, as we should request the TSC to properly delegate access officially to the web-infra to such resources.

Otherwise we will forever depend on the build WG.

@MattIPv4 if you can open the issue, that'd be great!

Because pretty much that would require the TSC to delegate access, but the tricky part is that the Build WG already has ownership of that. So we need to figure that out.

**Comment by targos** [comment]
I'm sorry if I looked like someone selfish/not collaborative, but this request came during a long awaited period of holiday for me, where I tried to disconnect as much as possible, and the recurrent pings (especially on Slack) made me stop looking at everything. I'm slowly coming back but have a huge backlog now. This issue is in my saved notifications and I hope to come back to it in a few days.

**Comment by ovflowd** [comment]
> I'm sorry if I looked like someone selfish/not collaborative, but this request came during a long awaited period of holiday for me, where I tried to disconnect as much as possible, and the recurrent pings (especially on Slack) made me stop looking at everything. I'm slowly coming back but have a huge backlog now. This issue is in my saved notifications and I hope to come back to it in a few days.

No worries @targos, being frank, I am aware that the Build WG has a lot on its plate, even more with the macOS stuff right now, but I was worried that somehow I did something wrong and lost the trust of the Build WG. I know I've been nagging, and I'm so sorry for the immense amount of pings.

**Comment by MattIPv4** [comment]
I've filed https://github.com/nodejs/admin/issues/833 to explore expanding Cloudflare access, so that web-infra could handle changes directly without having to add more work to the build WG's plate.

**Comment by ovflowd** [comment]
These changes got deployed. Cloudflare should not be caching anymore 5XXs.
