### ISSUE TITLE
Create `CodeBox` component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5819]
Create a `CodeBox` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=437-3034&mode=dev). 

This is the final port of the [Codebox component recently deleted](https://github.com/nodejs/nodejs.org/pull/5713)

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.
- ❗ Review the [translation guide](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md), especially how to [add new keys](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md#adding-new-translation-keys).

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/7866fb9d-a04d-48d1-86d1-3426c83ed3a6)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)
🌐 This story requires some internationalization support. Slow down!

- Create a new directory called `CodeBox` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code.
- Use the new `Button` component introduced within https://github.com/nodejs/nodejs.org/pull/5783
- Use the new `Notification` component introduced within https://github.com/nodejs/nodejs.org/issues/5948
- Use the new `Tabs` and `Tab` components introduced within https://github.com/nodejs/nodejs.org/pull/5817 to support 1 to many files
- Use the `useCopyToClipboard.ts` hook that already exists.
  - `onClick` of the `Copy to clipboard` button, show the `Notification` and copy the contents of the current tab using the hook.
  - Disable the button's click handler functionality during this state
- The `@heroicons/react` module has the icon `document-duplicate` available for use. This is a slight variant of the Figma, as the icon in the design is not available.
- Add a storybook story file `components/Common/Codebox/index.stories.tsx` which exercises each of the component's states.
- Note: per a design decision, we will _only_ use dark mode (Nord theme) of [shiki](https://github.com/shikijs/shiki), despite the screenshot and figma still displaying a light mode
- `Copy to clipboard` must be internationalized. Add a new key `components.common.codebox.copy` to the `i18n/locales/en.json` file. `FormattedMessage` from `react-intl` should be used to reference the key. Look for examples elsewhere in the codebase.

Suggested props include:

- `language` (string):  displays in the bottom left of the Codebox, labeling the type of content
- `linkText` (string, optional): displays in the top-right of the Codebox if present and `linkUrl`
- `linkUrl` (`typeof next/link` or ??, optional): the location the user navigates to when `linkText` is clicked
- `children` in the form of `Tabs` and `Tab`s

Example of `linkText` and `linkUrl`:
<img width="777" alt="image" src="https://github.com/nodejs/nodejs.org/assets/298435/1022eb20-8491-4fe4-9f46-399e1441042c">
 

There are 3 states to capture within styles and stories:

- 1 file format (such as bash)
- 2 files (CJS and ESM)
- `linkText` and `linkUrl` present

**Comment by bmuenzenmeyer** [comment]
@ovflowd, @Harkunwar would appreciate a second glance at this before a contributor picks it up

**Comment by HinataKah0** [comment]
It looks interesting, I would be happy to work on it.
Since this depends on other components to finish, I'll wait while finishing the review for the `CrossLink` component. 😄

**Comment by ovflowd** [comment]
> other components to finish, I'll wait while finishing the review for the `CrossLink` component. 😄

This depends on the Tabs component afaik

**Comment by bmuenzenmeyer** [comment]
also broke out `Notification` per a discussion with @ovflowd

**Comment by bmuenzenmeyer** [comment]
@HinataKah0 I think this work is now unblocked

**Comment by HinataKah0** [comment]
Thanks for notifying! Saw the email today as well.

Sadly, my work will be at crunch time for the next few weeks.
I've hidden my above comment, hoping other person will pick this up.

**Comment by devjvao** [comment]
Can I start working on this one?

Edit: Still working on it.

**Comment by fa-901** [comment]
Hi, I created a PR on this issue

**Comment by devjvao** [comment]
It took me a while, but I've managed to propose a solution for implementing this component. I hope it suits the project well.

I'll be waiting for reviews! :sweat_smile:
