### ISSUE TITLE
Create `Blockquote` Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5820]
Create a `Blockquote` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=1509-16204&mode=dev). 

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/36793e9a-a03a-4c66-9c05-c306d5a0aaf1)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Create a new directory called `Blockquote` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code.
- Use the new tailwind color and typography system to assign properties. For example, `Light` uses `Green/600` per the figma.
- Add a storybook story file `components/Common/Blockquote/index.stories.tsx` which exercises each of the button's states.
- Add the em-dash `—` for users before the `attribution` prop renders

Suggested props include:

- `children` text content, rendered within a `p` tag: `“In a world older and more complete than ours...` in the figma
- `attribution` (string) : `Hayden Bleasel, Stoic Philosopher` in the figma

There are 2 states to capture within styles and stories:

- Light
- Dark

### Open Questions, to Discuss

- how should the semantic markup be structured? this is a topic of much debate, it seems. suggest starting with [MDN's approach](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote)
- how does a user-supplied markdown blockquote `> text` render in tailwind? that will certainly be something that comes up. I suggest we add a storybook story also rendering this (but not using the `Blockquote` component, as markdown-driven content won't have `attribution` in many cases. I don't think an MDX component map is appropriate right now either.

**Comment by AugustinMauroy** [comment]
Can I work on this ? _i know I have an other issue but it's ready on local_

**Comment by ovflowd** [comment]
> Can I work on this ? _i know I have an other issue but it's ready on local_

Lets let other people have a chance :)

**Comment by canerakdas** [comment]
I can work on this 👀

**Comment by canerakdas** [comment]
> how does a user-supplied markdown blockquote > text render in tailwind? that will certainly be something that comes up. I suggest we add a storybook story also rendering this (but not using the Blockquote component, as markdown-driven content won't have attribution in many cases. I don't think an MDX component map is appropriate right now either.

I want to add this story but I think I didn't get it correctly. Can you please explain it a bit more? @bmuenzenmeyer 

I guess mdx converting quotes into the following HTML;

MDX
```md
> text
````

HTML
```html
<blockquote>
  <p>text</p>
</blockquote>
```
- https://mdxjs.com/table-of-components/
- https://spec.commonmark.org/dingus/?text=%3E%20text

Do you want the to story only contain the following HTML?
```html
<blockquote>
  <p>text</p>
</blockquote>
```

**Comment by ovflowd** [comment]
> > how does a user-supplied markdown blockquote > text render in tailwind? that will certainly be something that comes up. I suggest we add a storybook story also rendering this (but not using the Blockquote component, as markdown-driven content won't have attribution in many cases. I don't think an MDX component map is appropriate right now either.
> 
> I want to add this story but I think I didn't get it correctly. Can you please explain it a bit more? @bmuenzenmeyer
> 
> I guess mdx converting quotes into the following HTML;
> 
> MDX
> 
> ```
> > text
> ```
> 
> HTML
> 
> ```
> <blockquote>
>   <p>text</p>
> </blockquote>
> ```
> 
> * [mdxjs.com/table-of-components](https://mdxjs.com/table-of-components/)
> * [spec.commonmark.org/dingus/?text=%3E%20text](https://spec.commonmark.org/dingus/?text=%3E%20text)
> 
> Do you want the to story only contain the following HTML?
> 
> ```
> <blockquote>
>   <p>text</p>
> </blockquote>
> ```

Well, the Component MDX-provided content comes as a `children` parameter; Since this component is used by the `MDXProvider`.

For Storybook, we can do the same, and `children` becomes a control. For the sake of simplicity, we will pass as default value a paragraph of plain text.

**Comment by bmuenzenmeyer** [comment]
I know how markdown blockquotes work...my comment is referring to the the attribution element which wont have a means to directly supply if someone merely authors a `>`

This story should cover designing the fancier custom Blockquote per figma,but also document a pure blockquote...both authoring scenarios in my mind.

**Comment by ovflowd** [comment]
> I know how markdown blockquotes work...my comment is referring to the the attribution element which wont have a means to directly supply if someone merely authors a `>`
> 
> This story should cover design the fancier custom Blockquote but also document a pure blockquote...both authoring scenarios in my mind.

I do not think we should add "attribution" on this Blockquote component

**Comment by canerakdas** [comment]
> > I know how markdown blockquotes work...my comment is referring to the the attribution element which wont have a means to directly supply if someone merely authors a `>`
> > This story should cover design the fancier custom Blockquote but also document a pure blockquote...both authoring scenarios in my mind.
> 
> I do not think we should add "attribution" on this Blockquote component

If there is no opposing opinion, I will update the draft PR. I agree with @ovflowd on simplicity

**Comment by bmuenzenmeyer** [comment]
I'm fine with that, but @HaydenBleasel should be made aware

**Comment by ovflowd** [comment]
> I'm fine with that, but @HaydenBleasel should be made aware

Why? Was the "attribution" part of blockquote on the system design?

If yes, Im quite sure that it was just part of the content of the Block-quote element

It's more like that if you see on the blockquote of the system design the "attribution" part it is very likely that it should be something in mdx:

```markdown
> my blockquote content
> some super cool stuff
>
> <cite>some author</cite>

// other valid markdown
<blockquote>
I like chocolate

<cite>By Claudio Wunder</cite>
</blockquote>
```

MDX will treat all of these as just children so when passed to our Blockquote they will be mapped as JSX nodes within the children parameter.

If we want to have custom styling for the cite element, then we should add styling to cite html tag within our CSS module

```scss

.blockquote {
  ... blockquote tailwind tokens

  cite {
     ... extra style for cite
  }
```
