### ISSUE TITLE
download page (#2), could there be a Linux “fast track” logo, too, at the top?

### ISSUE THREAD

**Issue by peterjosvai** [nodejs/nodejs.org#584]
// this issue (suggestion) is related to issue #577 //
![node-website-dl_page-top](https://cloud.githubusercontent.com/assets/13543101/13840496/1af19a76-ec23-11e5-913f-08f55bb3c853.jpg)

dear node.js site-admins,

I am a Linux user, too, and I download node.js a couple of times lately, that is, I am a new node.js user, and I think that the download page does not help me as much as it would if I wanted to download node.js for Windwos or Mac... 

**:: INTRO**
I initiated a discourse about this page already by filing a “website issue” (#577), and I can see how the decision is being made: developers basically vote on whether or not to leave it like this, “with windows on top”... in the left column of the page listing the OSs in written form (not logos)...

I was hoping that the conversation will reach the (TOP) problem, namely the logos on the very top of the page, Windows and Mac ... (and source code :))... but it got stalled at debating whether the list in the left column is justifiable by any logic... 
(like “the double click installers have to be on the top because the users would want it more likely” – sure, the Windows and the Mac users will want those links on top of their section... 
for a Linux user, for example, it is absolutely NOT LIKELY to want these Win or Mac links :) )

Linux users also want to install node.js...  and for sure, we'll come to the node.js site and try to find the “get node.js” page :) and sure, we will, at first (before learning to use the “get me the latest v5.x version” expression) check the download page, and sure, not seeing our “fast track” logo at the top (like Win and Mac users can) is by all means a disadvantage...

**:: SUGGESTION**
couldn't Linux users get a “fast track” logo at the top of the page, too?

it wouldn't hurt Microsoft or Apple OS users but it'd be great help for Linux users, and a great achievement, too, to see our logo next to the world Grand Old Corporations' logos... You know, “free software”, “cultural identity” :) It means a lot

**it could be labeled as:** “Linux info & packages” or **simply: “Linux links”** (so that it wouldn't take more space than the competitors') 

and, please, bear in mind that “downloading” is the synonym (in this Windows dominated culture) of “I want to install”, and for a Linux user to find the exact “apt-get install command line” is the same thing as for Win and Mac users to click on the download link of their double click installers – they look for that, we look for this... when wanting to install... when wanting the same thing...

knowing that you are concerned about a page structure that would “negatively effect new developers”, I'm sure you do have reasons to give this suggestion a thought, cause it'd effect new users, I can tell, absolutely positively :)

from my perspective, it'd make sense to have a Linux logo at the top, too, as a “fast track” which would land us, Linux users, at a page, section, whatsoever, where the various Linux installation infos, DL packages, etc could be found...

**thank you** for your time and your logical openness

Peter

**Comment by MylesBorins** [comment]
@peterjosvai for this issue in particular you might want to take a stab at doing an implementation and submitting a PR that we can comment on / critique

**Comment by benjamingr** [comment]
Are you really claiming NodeJS, a Linux Foundation collaborative project (with a big logo saying that on every page of NodeJS.org) whose foundation members are all linux foundation members is somehow biased against Linux :D ? 

Node is not operating in a "windows dominated culture", Node has always been a linux-support first project. All the tools in the ecosystem are linux first (like npm updating node, and nvm). 

> I initiated a discourse about this page already by filing a “website issue” (#577), and I can see how the decision is being made: developers basically vote on whether or not to leave it like this, “with windows on top”... in the left column of the page listing the OSs in written form (not logos)...

When you've asked that Mikeal posted a link backing the choice with data. https://github.com/nodejs/nodejs.org/issues/577#issuecomment-196630342 

That said - I recommend you do what @TheAlphaNerd has suggested and take a stab and implementing it though as a linux user I never double-click install things - I always just install it with pacman (or apt or whatever).

**Comment by mikeal** [comment]
> whose foundation members are all linux foundation members

That's not true. The Linux Foundation and Node.js Foundation are independent 501(c)6 orgs and have their own independent membership. While many of the Node.js Foundation members are also LF members there are many that aren't and being an LF member is not a requirement of being a Node.js Foundation member.

> Node is not operating in a "windows dominated culture", Node has always been a linux-support first project. All the tools in the ecosystem are linux first (like npm updating node, and nvm).

We use metrics for this stuff because people's opinions tend to be pretty biased. Those metrics tell us that Windows is the dominant development environment, and Mac is the second. They also tell us that the number one deployment environment is Linux and that is taken in to consideration for other decisions, it's just that this particular decision regarding the website is targeted at development environments for obvious reasons.

**Comment by fhemberger** [comment]
Closing this for now, feel free to file a PR with the proposed changes as @TheAlphaNerd already suggested.
