### ISSUE TITLE
"Governance" link on Foundation page goes to TSC github

### ISSUE THREAD

**Issue by williamkapke** [nodejs/nodejs.org#589]
On https://nodejs.org/en/foundation/, under "Core documents" the "Governance" link just sends me to https://github.com/nodejs/TSC.

I would expect this link to take me to something that explains the governance of  The Node.js Foundation.

Remove? Replace with...?

**Comment by rvagg** [comment]
probably consider this a WIP for now, hopefully we'll have more in a couple of weeks, both the TSC and the Board are discussing things around this.

**Comment by williamkapke** [comment]
This was fixed by @mikeal via 521b9efc
