### ISSUE TITLE
Add social icon X

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5894]
Add the X logo to the site assets. 

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

![image](https://github.com/bmuenzenmeyer/nodejs.org/assets/298435/a05c6e3f-f0f9-4be0-b8b6-249b47442109)

> from the [Figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=415-8379&mode=dev)

> displaying all. This issue only adds the X one.

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

Make sure that `npm ci` completes for you in a terminal pointing to your fork. If it doesn't or you aren't sure, ask a mentor.

---

#### Where to add the file

Site assets are found at https://github.com/nodejs/nodejs.org/tree/main/public/static/images/logos. 

- Add the file into this directory _on your fork_

#### Adding the file

This file is an SVG, which means it is represented as text.

Create a new file in the `public/static/images/logos` directory, called `social-x.svg`

Paste the below contents into the new file and save.

```
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M1.04717 2.05762L7.99429 11.3466L1.0033 18.8989H2.57669L8.69729 12.2867L13.6426 18.8989H18.9969L11.6589 9.08745L18.1661 2.05762H16.5927L10.9559 8.1473L6.40148 2.05762H1.04717ZM3.36096 3.21658H5.82074L16.6827 17.7398H14.223L3.36096 3.21658Z" fill="black"/>
</svg>
```

#### Adding a Storybook story to preview the file

Use [Storybook](https://storybook.js.org/) to preview the new logo.

Add your new image file to the storybook called `social-logos.stories.tsx` in the `components/__design__` directory.

We want to create a file that looks like this, eventually, for this and the other logos (separate stories)

```tsx
import Image from 'next/image';
import type { Meta as MetaObj, StoryObj } from '@storybook/react';

export const SocialLogos: StoryObj = {};

export default {
  title: 'Design System/Social Logos',
  component: () => {
    return (
    <div>
      <div>
        <Image
            src="/static/images/logos/social-github.svg"
            alt="GitHub Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/social-mastadon.svg"
            alt="Mastadon Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/social-linkedin.svg"
            alt="LinkedIn Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/social-slack.svg"
            alt="Slack Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/social-x.svg"
            alt="X Logo"
            width={64}
            height={64}
          />
      </div>
    </div>
  )},
} as MetaObj;
```

> Only add the `Image` for the logo you added.

#### Running Storybook

In a terminal, run `npm run storybook`.

Then, in a browser, go to http://localhost:6006/?path=/story/design-system-logos--social-logos and you should see the file you added.

#### Submitting the changes

[Submit a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) back to the main repository.

**Comment by AugustinMauroy** [comment]
FYI: " X" svg has already been added

**Comment by bmuenzenmeyer** [comment]
I see that now, but it's not in the storybook at https://github.com/nodejs/nodejs.org/blob/main/components/__design__/social-logos.stories.tsx - that still needs to be done, whoever picks it up.

Thanks for the clarification @AugustinMauroy

**Comment by AugustinMauroy** [comment]
can I work on that ?

**Comment by ovflowd** [comment]
> can I work on that ?

Aren't you already working on something?

**Comment by AugustinMauroy** [comment]
Technically yes 😁
