### ISSUE TITLE
Add social icon Slack

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5895]
Add the Slack logo to the site assets. 

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

![image](https://github.com/bmuenzenmeyer/nodejs.org/assets/298435/a05c6e3f-f0f9-4be0-b8b6-249b47442109)

> from the [Figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=415-8379&mode=dev)

> displaying all. This issue only adds the Slack one. 
---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

Make sure that `npm ci` completes for you in a terminal pointing to your fork. If it doesn't or you aren't sure, ask a mentor.

---

#### Where to add the file

Site assets are found at https://github.com/nodejs/nodejs.org/tree/main/public/static/images/logos. 

- Add the file into this directory _on your fork_

#### Adding the file

This file is an SVG, which means it is represented as text.

Create a new file in the `public/static/images/logos` directory, called `social-slack.svg`

Paste the below contents into the new file and save.

```
<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none"><path fill="#2EB67D" d="M16.563 9.375A1.562 1.562 0 1 0 15 7.813v1.562h1.563Zm-4.375 0c.862 0 1.562-.7 1.562-1.563V3.438a1.563 1.563 0 0 0-3.125 0v4.374c0 .863.7 1.563 1.563 1.563Z"/><path fill="#E01E5A" d="M3.437 10.625A1.562 1.562 0 1 0 5 12.187v-1.562H3.437Zm4.376 0c-.863 0-1.563.7-1.563 1.563v4.374a1.563 1.563 0 0 0 3.125 0v-4.374c0-.863-.7-1.563-1.563-1.563Z"/><path fill="#ECB22E" d="M10.625 16.563A1.562 1.562 0 1 0 12.187 15h-1.562v1.563Zm0-4.375c0 .862.7 1.562 1.563 1.562h4.374a1.562 1.562 0 1 0 0-3.125h-4.374c-.863 0-1.563.7-1.563 1.563Z"/><path fill="#36C5F0" d="M9.375 3.437A1.562 1.562 0 1 0 7.813 5h1.562V3.437Zm0 4.376c0-.863-.7-1.563-1.563-1.563H3.438a1.563 1.563 0 0 0 0 3.125h4.374c.863 0 1.563-.7 1.563-1.563Z"/></svg>
```

#### Adding a Storybook story to preview the file

Use [Storybook](https://storybook.js.org/) to preview the new logo.

Add your file to `social-logos.stories.tsx` in the `components/__design__` directory.

We want to create a file that looks like this, eventually, for this and the other logos (separate stories)

```tsx
import Image from 'next/image';
import type { Meta as MetaObj, StoryObj } from '@storybook/react';

export const SocialLogos: StoryObj = {};

export default {
  title: 'Design System/Social Logos',
  component: () => {
    return (
    <div>
      <div>
        <Image
            src="/static/images/logos/social-github.svg"
            alt="GitHub Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/social-mastadon.svg"
            alt="Mastadon Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/social-linkedin.svg"
            alt="LinkedIn Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/social-slack.svg"
            alt="Slack Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/social-x.svg"
            alt="X Logo"
            width={64}
            height={64}
          />
      </div>
    </div>
  )},
} as MetaObj;
```

> Only add the `Image` for the logo you added.

#### Running Storybook

In a terminal, run `npm run storybook`.

Then, in a browser, go to http://localhost:6006/?path=/story/design-system-logos--social-logos and you should see the file you added.

#### Submitting the changes

[Submit a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) back to the main repository.

**Comment by byt3h3ad** [comment]
hey, i am interested to work on this! if it isn't a problem can i make the PR on 1st of October so that it is counted in Hacktoberfest?

**Comment by virentalwar** [comment]
Hello, I had worked on this yesterday and hence raised the PR without checking the above comment. Please see if it can be considered or not.
