### ISSUE TITLE
Add platform icon Micosoft

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5897]
Add the Microsoft logo to the site assets. 

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

![image](https://github.com/bmuenzenmeyer/nodejs.org/assets/298435/b38b96cb-b868-424f-b200-2d143751f8fc)

> from the [Figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=423-27584&mode=dev)

> displaying all. This issue only adds the microsoft one.

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

Make sure that `npm ci` completes for you in a terminal pointing to your fork. If it doesn't or you aren't sure, ask a mentor.

---

#### Where to add the file

Site assets are found at https://github.com/nodejs/nodejs.org/tree/main/public/static/images/logos. 

- Add the file into this directory _on your fork_

#### Adding the file

This file is an SVG, which means it is represented as text.

Create a new file in the `public/static/images/logos` directory, called `platform-microsoft.svg`

Paste the below contents into the new file and save.

```
<svg width="32" height="32" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill="#FEBA08" d="M17 17h10v10H17z"/><path fill="#05A6F0" d="M5 17h10v10H5z"/><path fill="#80BC06" d="M17 5h10v10H17z"/><path fill="#F25325" d="M5 5h10v10H5z"/></svg>
```

#### Adding a Storybook story to preview the file

Use [Storybook](https://storybook.js.org/) to preview the new logo.

Add your file to `platform-logos.stories.tsx` in the `components/__design__` directory. 

We want to create a file that looks like this, eventually, for this and the other logos (separate stories)

```tsx
import Image from 'next/image';
import type { Meta as MetaObj, StoryObj } from '@storybook/react';

export const PlatformLogos: StoryObj = {};

export default {
  title: 'Design System/Platform Logos',
  component: () => {
    return (
    <div>
      <div>
        <Image
            src="/static/images/logos/platform-apple.svg"
            alt="Apple Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/platform-nvm.svg"
            alt="NVM Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/platform-microsoft.svg"
            alt="Microsoft Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/platform-homebrew.svg"
            alt="Homebrew Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/platform-placeholder.svg"
            alt="Placeholder Logo"
            width={64}
            height={64}
          />
      </div>
    </div>
  )},
} as MetaObj;
```

> Only add the `Image` for the logo you added.

#### Running Storybook

In a terminal, run `npm run storybook`.

Then, in a browser, go to http://localhost:6006/?path=/story/design-system-logos--platform-logos and you should see the file you added.

<details><summary>Preview</summary>
<img src="https://github.com/bmuenzenmeyer/nodejs.org/assets/298435/eab605bf-6576-4284-a190-fa4c11196061" />
</details>

#### Submitting the changes

[Submit a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) back to the main repository.

**Comment by AmitSingh-5600** [comment]
pls assign me to work on this

**Comment by AugustinMauroy** [comment]
@AmitSingh-5600 
you can work on this issue but we don't actually assign.
