### ISSUE TITLE
Add White Hex Logo

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5899]
Add the white Hex Logo to the site assets. 

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

![image](https://github.com/bmuenzenmeyer/nodejs.org/assets/298435/8c067b66-5c99-4907-adc7-b99187697ed7)

> from the [Figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=337-7897&mode=dev)

> displaying all. This issue only adds the white one.

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

Make sure that `npm ci` completes for you in a terminal pointing to your fork. If it doesn't or you aren't sure, ask a mentor.

---

#### Where to add the file

Site assets are found at https://github.com/nodejs/nodejs.org/tree/main/public/static/images/logos. 

- Add the file into this directory _on your fork_

#### Adding the file

This file is an SVG, which means it is represented as text.

Create a new file in the `public/static/images/logos` directory, called `hex-white.svg`

Paste the below contents into the new file and save.

```
<svg width="69" height="80" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_337_7896)"><path fill-rule="evenodd" clip-rule="evenodd" d="M33.023 2.01a3.727 3.727 0 0 1 3.688 0l30.38 17.58c1.158.652 1.809 1.882 1.809 3.184v35.018a3.77 3.77 0 0 1-1.809 3.184l-30.38 17.581a3.727 3.727 0 0 1-3.688 0L2.643 60.976C1.485 60.325.834 59.095.834 57.792v-35.09a3.77 3.77 0 0 1 1.809-3.184L33.023 2.01Z" fill="url(#paint0_linear_337_7896)"/><path opacity=".66" d="M66.946 19.518 36.71 1.937a5.021 5.021 0 0 0-.94-.362L1.556 60.107c.29.362.651.651 1.013.868l30.452 17.582c.94.506 1.953.651 2.893.29l31.971-58.533a2.613 2.613 0 0 0-.94-.796Z" fill="#4B4B4B"/><path d="m36.638 78.557 30.308-17.582c1.157-.65 1.663-1.88 1.663-3.183v-.145L35.77 1.575c-.94-.29-1.953-.145-2.82.362L2.858 19.3l32.694 59.618c.434-.073.796-.145 1.085-.362Z" fill="url(#paint1_linear_337_7896)"/></g><defs><linearGradient id="paint0_linear_337_7896" x1=".828" y1="40.273" x2="68.968" y2="40.273" gradientUnits="userSpaceOnUse"><stop offset=".005" stop-color="#fff"/><stop offset=".194" stop-color="#E8E8E8"/><stop offset=".542" stop-color="#C2C2C2"/><stop offset=".824" stop-color="#ABABAB"/><stop offset="1" stop-color="#A3A3A3"/></linearGradient><linearGradient id="paint1_linear_337_7896" x1=".356" y1="40.223" x2="70.647" y2="40.223" gradientUnits="userSpaceOnUse"><stop stop-color="#A3A3A3"/><stop offset=".176" stop-color="#ABABAB"/><stop offset=".458" stop-color="#C2C2C2"/><stop offset=".806" stop-color="#E8E8E8"/><stop offset=".995" stop-color="#fff"/></linearGradient><clipPath id="clip0_337_7896"><path fill="#fff" d="M0 .5h69v79H0z"/></clipPath></defs></svg>
```

#### Adding a Storybook story to preview the file

Use [Storybook](https://storybook.js.org/) to preview the new logo.

Add your file to `hex-logos.stories.tsx` in the `components/__design__` directory.

We want to create a file that looks like this, eventually, for this and the other logos (separate stories)

```tsx
import Image from 'next/image';
import type { Meta as MetaObj, StoryObj } from '@storybook/react';

export const HexLogos: StoryObj = {};

export default {
  title: 'Design System/Hex Logos',
  component: () => {
    return (
    <div>
      <div>
        <Image
            src={`/static/images/logos/hex-white.svg`}
            alt="Node.js"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src={`/static/images/logos/hex-green.svg`}
            alt="Node.js"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src={`/static/images/logos/hex-black.svg`}
            alt="Node.js"
            width={64}
            height={64}
          />
      </div>
    </div>
  )},
} as MetaObj;
```

> Only add the `Image` for the logo you added.

#### Running Storybook

In a terminal, run `npm run storybook`.

Then, in a browser, go to http://localhost:6006/?path=/story/design-system-logos--hex-logos and you should see the file you added.

<details><summary>Preview</summary>
<img src="https://github.com/bmuenzenmeyer/nodejs.org/assets/298435/11c8af1e-99db-4008-873d-7f0bd80f8f26" />
</details>

#### Submitting the changes

[Submit a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) back to the main repository.

**Comment by saurabh-nahar** [comment]
How do I get this assigned to me?

**Comment by AugustinMauroy** [comment]
Sorry @saurabh-nahar 😅 but @vaqueraoscar0 work on.

**Comment by bmuenzenmeyer** [comment]
@saurabh-nahar there are other issues still available (as of this writing, such as https://github.com/nodejs/nodejs.org/issues/5898)

**Comment by vaqueraoscar0** [comment]
@AugustinMauroy  @saurabh-nahar I apologize, i should’ve added some comment the moment i started working on this issue. i assumed based on the other issues that i saw that this was a first come, first serve type of deal. i’ll make sure to at least add some comment next time.

**Comment by saurabh-nahar** [comment]
Hey @vaqueraoscar0 no worries I will work on some other issue. @bmuenzenmeyer thanks will take up the issue you mentioned or anything that's available. 

Thanks for informing @AugustinMauroy :)

**Comment by bmuenzenmeyer** [comment]
@vaqueraoscar0 you are completely right, it is first-come, first-server, with the caveat you mention it in the issue first, else we get competing PRs

thanks again for your interest!

**Comment by mikeesto** [comment]
Resolved by https://github.com/nodejs/nodejs.org/pull/5903
