### ISSUE TITLE
Improved Get Involved page

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#59]
Our "Get Involved" page is pretty weak. We have so many places people can get involved nowadays and we basically just list bug writing guidelines. The page should
- List NodeSchool and other community events and learning.
- List the most accessible working groups.
- Link to information about getting involved in core.

**Comment by fhemberger** [comment]
I just did that, migrating https://nodejs.org/community/

**Comment by fhemberger** [comment]
@mikeal Can we close this again or do you want to edit the page even further?

**Comment by mikeal** [comment]
ya, looks fine for now, although eventually I'm going to cut like half of this. we should do a proper event at some point with *all* the events. and i don't think we should even mention the mailing list :)

**Comment by fhemberger** [comment]
Yes, I think a lot of the website content still needs to be restructured/rewritten. But for the launch, it's okay.
