### ISSUE TITLE
Create `Select` component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5909]
Create a `Select` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=433-3379&mode=dev). 

This component is a select and a label.

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/173d2133-63de-44ed-b9be-638673c5dd45)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Create a new directory called `Select` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code.
- Use the new tailwind color and typography system to assign properties. For example, the border uses `Neutral/300` per the figma.
- [Add a new dependency,`@radix-ui/react-select`](https://www.radix-ui.com/primitives/docs/components/select), for the basic `select` functionality. Follow the [the dependency guide](https://github.com/nodejs/nodejs.org/blob/main/DEPENDENCY_PINNING.md)
  - Use discretion when implementing elements of the radix API, such as `SelectItem`
  - Use `Select.Icon` to add the hero icon `chevron-down` from our existing dependency.
- Add a storybook story file `components/Common/Select/index.stories.tsx` which exercises each of the component's states.

Suggested props include:

- `label` (string): `Node.js version` in the figma
- `values` (string[]): `v20.3.1` in the figma
- `onChange` (function): a function to return to the caller if needed

There are 2 states to capture within styles and stories:

- Light
- Dark

**Comment by canerakdas** [comment]
Hey @bmuenzenmeyer, can I work on this?

**Comment by ovflowd** [comment]
> Hey @bmuenzenmeyer, can I work on this?

Go ahead! No need to ask :)
