### ISSUE TITLE
Invalid video link

### ISSUE THREAD

**Issue by williamkapke** [nodejs/nodejs.org#591]
The link for the video recording does not work on this page:
https://nodejs.org/en/foundation/tsc/minutes/2014-12-10/

**Comment by phillipj** [comment]
@misterdjules you know whether or not old TSC meeting videos hosted at bluejeans.com should be available, or available elsewhere?

The broken video link in question: https://bluejeans.com/s/7_j@/

**Comment by misterdjules** [comment]
Bluejeans had been used a few times around that time, but I was not the owner of the account we had used to host the calls, and so I have no idea how to retrieve that recording. @tjfontaine might know.

**Comment by williamkapke** [comment]
Perhaps it is lost forever...? :(

**Comment by misterdjules** [comment]
@williamkapke It is possible. What information are you missing?

**Comment by williamkapke** [comment]
@misterdjules I'm just trying to fix broken links and keep any available process minutia available to all that want it

**Comment by misterdjules** [comment]
@williamkapke Sounds good. Then I'm afraid I won't be able to help you fix that broken link :(

**Comment by williamkapke** [comment]
Ok thanks anyhow. I'll leave this open for another week or so to see if @tjfontaine or any others help out.

If not, I'll make a PR to remove it.

**Comment by phillipj** [comment]
@williamkapke are up for removing the link, or should we label this a good first contribution?

**Comment by williamkapke** [comment]
yeah. I have it stashed. I'll open a PR now.
