### ISSUE TITLE
Create `AvatarGroup` Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5910]
Create an `AvatarGroup` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=477-13668&mode=dev). 

This component is a group of multiple `Avatars`, with optional display of overflow.

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/762f3fb0-8bf3-4ca9-bf61-ac7c366dce22)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Create a new directory called `AvatarGroup` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code.
- Use the new tailwind color and typography system to assign properties. For example, the background of the overflow `Avatar` uses `Neutral/100` in light mode per the figma.
- [Add a new dependency,`@radix-ui/avatar`](https://www.radix-ui.com/primitives/docs/components/avatar), for the basic `Avatar` functionality. Follow the [the dependency guide](https://github.com/nodejs/nodejs.org/blob/main/DEPENDENCY_PINNING.md)
- After `limit` `Avatars` are provided, an overflow `Avatar` displaying `+N` should render, where `N` is the length of the avatar collection minus `limit`. Make sure the math is correct before, at, and past the limit.
- Add a storybook story file `components/Common/AvatarGroup/index.stories.tsx` which exercises each of the component's states.

Suggested props include:

- `limit` (integer, default 10): dictates total `Avatars` to render
- `avatars` (object[]): that follows this general shape:

```json
[
  {
    "imageUrl": "https://avatars.githubusercontent.com/u/298435?v=4",
    "href": "https://github.com/bmuenzenmeyer"
  },
  ...
]
```

There are 6 states to capture within styles and stories:

- Light, under limit
- Light, over limit
- Light, at limit
- Dark, under limit
- Dark, over limit
- Dark, at limit

**Comment by AugustinMauroy** [comment]
Can I work on this ?

**Comment by bmuenzenmeyer** [comment]
you bet!

**Comment by shishiro26** [comment]
@ovflowd if this issue still open I would like to work on this. can u please assign this to me

**Comment by ovflowd** [comment]
> @ovflowd if this issue still open I would like to work on this. can u please assign this to me

If you look with attention, you'll see this issue state is "In Review" and there's already an open PR.
