### ISSUE TITLE
Create `NavItem` Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5911]
Create a `NavItem` component using the new [figma design (direct link to Nav)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=422-9155&mode=dev) and [here is Footer](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=696-9074&mode=dev). 

This component is a link with additional styling for focus states, and an indicator if the href is an external link. This one component will be used for both the `Navbar` (green accents) and the `Footer` (grey accents) in future issues.

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/689af7da-0782-4d96-94d9-18989be8ff69)

![image](https://github.com/nodejs/nodejs.org/assets/298435/fbabf517-7503-4808-91ce-9656e60fc90c)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Create a new directory called `NavItem` within the [`sections` directory](https://github.com/nodejs/nodejs.org/tree/main/components/sections) that contains all the new code. `sections` may not exist yet
- Use the new tailwind color and typography system to assign properties. For example, the NavItem active states uses `Green/600` per the figma.
- Add a storybook story file `components/sections/NavItem/index.stories.tsx` which exercises each of the component's states.
- Use intelligent detection of the `href` host compared to the current host to determine if the link is external. If it is, render `arrow-up-right` icon from the hero icons dependency. This only applies for `type` === `nav`

Suggested props include:

- `label` (string): `Learn` in the figma
- `href` (`typeof next/link`)
- `type` (enum, `nav` | `footer`)

There are 8 Navbar states to capture within styles and stories:

- Light, internal link
- Light, internal link, active (focused or hovered)
- Light, external link
- Light, external link, active (focused or hovered)
- Dark, internal link
- Dark, internal link, active (focused or hovered)
- Dark, external link
- Dark, external link, active (focused or hovered)

There are 4 footer states to capture within styles and stories:

- Light
- Light, active (focused or hovered)
- Dark
- Dark, active (focused or hovered)

**Comment by shaikahmadnawaz** [comment]
Can I work on this issue?

**Comment by bmuenzenmeyer** [comment]
yes, go for it! thanks @shaikahmadnawaz

**Comment by shaikahmadnawaz** [comment]
> yes, go for it! thanks @shaikahmadnawaz

Thank you @bmuenzenmeyer

**Comment by shaikahmadnawaz** [comment]
![Screenshot (1284)](https://github.com/nodejs/nodejs.org/assets/96189881/4207beb4-4be9-40e3-b1d5-390647faaecf)

When I execute this command `npx turbo serve` I get this error and termination, I am not able to run the application locally.

![Screenshot (1285)](https://github.com/nodejs/nodejs.org/assets/96189881/4fa7da7d-6ad1-45f3-af3e-cd4e54d13c53)

can you please help @bmuenzenmeyer @ovflowd

**Comment by ovflowd** [comment]
> ![Screenshot (1284)](https://user-images.githubusercontent.com/96189881/271665625-4207beb4-4be9-40e3-b1d5-390647faaecf.png)
> 
> When I execute this command `npx turbo serve` I get this error and termination, I am not able to run the application locally.
> 
> ![Screenshot (1285)](https://user-images.githubusercontent.com/96189881/271666210-4fa7da7d-6ad1-45f3-af3e-cd4e54d13c53.png)
> 
> can you please help @bmuenzenmeyer @ovflowd

Have you installed the dependencies with `npm install`? I also see on your screenshot that you've updated the package-lock? 🤔

**Comment by shaikahmadnawaz** [comment]
Yes I did, how can I run without installing dependencies 😗

**Comment by ovflowd** [comment]
> Yes I did, how can I run without installing dependencies 😗

It's a common question to do. I would recommend you to open an issue so that we don't pollute this one. I can only tell you that the whole process works fine on Linux, macOS and Windows because we have CI for that.

Open a new issue reporting this problem and don't forget to attach your Node.js version and NPM version.

**Comment by shaikahmadnawaz** [comment]
> > Yes I did, how can I run without installing dependencies 😗
> 
> It's a common question to do. I would recommend you to open an issue so that we don't pollute this one. I can only tell you that the whole process works fine on Linux, macOS and Windows because we have CI for that.
> 
> Open a new issue reporting this problem and don't forget to attach your Node.js version and NPM version.

Okay 👍

**Comment by shaikahmadnawaz** [comment]
@ovflowd, check the issue once #5921, I mentioned the problem I am facing while running it locally.

Issue #5921

**Comment by shaikahmadnawaz** [comment]
#5921 issues solved, now I am good to go. 😊

**Comment by fa-901** [comment]
@ovflowd I noticed this issue was moved back to Ready status and no one was assigned to it. So I went ahead and made a PR
