### ISSUE TITLE
Create `Breadcrumbs` Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5914]
Create a `Breadcrumbs` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=433-4349&mode=dev). 

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.
- ❗ Review the [translation guide](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md), especially how to [add new keys](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md#adding-new-translation-keys).

---

### Details

<img width="644" alt="image" src="https://github.com/nodejs/nodejs.org/assets/298435/1fa1faae-ae23-42e9-b397-6b4418f23214">

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Create a new directory called `Breadcrumbs` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/common) that contains all the new code. (This location may change in the future.)
- Use the new tailwind color and typography system to assign properties. For example, the active link uses Green/600 per the figma.
- The `@heroicons/react` module has the icons `chevron-right` and `home available for use
- Add a storybook story file `components/common/Breadcrumbs/index.stories.tsx` which exercises each of the component's states.

Suggested props include:

- `links`, an array of objects that looks like this:

```js
[
    {
        value: "Learn",
        url: "path/to/learn"
    },
    {
        value: "Getting Started",
        url: "path/to/learn/getting-started"
    },
    {
        value: "Introduction to Node.js,
        url: "path/to/learn/getting-started/intro"
    }
]
```

- The home icon is always rendered, and goes to the root
- The last record in the array is considered the active location.
  - Research if [Next.js useRouter](https://nextjs.org/docs/pages/api-reference/functions/use-router) would be useful for confirming the user is at the leaf node. Though I don't know it it's better to be fully static, fully dynamic, or a hybrid.

There are 2 states to capture within styles and stories:

- Light
- Dark

### Open Questions, to Discuss

- Do breadcrumbs truncate at some point? The figma shows an ellipsis. I've asked @HaydenBleasel to clarify

<img width="736" alt="image" src="https://github.com/nodejs/nodejs.org/assets/298435/0eca3417-2819-41af-8ac6-b789b143f2fc">

**Comment by junwen-k** [comment]
This one looks interesting. Do you prefer if we use headless package like [react-aria](https://react-spectrum.adobe.com/react-aria/useBreadcrumbs.html) to handle the accessibility? I am a huge fan of [Radix UI](https://www.radix-ui.com/) but they do not offer Breadcrumbs component at the moment. See https://github.com/radix-ui/primitives/issues/2050#issue-1644371337.

**Comment by ovflowd** [comment]
> This one looks interesting. Do you prefer if we use headless package like [react-aria](https://react-spectrum.adobe.com/react-aria/useBreadcrumbs.html) to handle the accessibility? I am a huge fan of [Radix UI](https://www.radix-ui.com/) but they do not offer Breadcrumbs component at the moment. See [radix-ui/primitives#2050 (comment)](https://github.com/radix-ui/primitives/issues/2050#issue-1644371337).

We are adopting RadixUI across all interactive components. It doesn't look like Radix maintainers seem to be interested on that or no one has yet contributed one Component.

I guess we can make a minimal simple version without aria/accessibility in mind and revisit in the future this issue.

I saw that https://blueprintjs.com/docs/#core/components/breadcrumbs has Breadcrumbs and I like the idea of automatically striping the parts that overflow. We can inspire ourselves on that impl, even tho I'd say I'm fine by showing always the home icon and the first and current entry if there's lack of space..

We can also always truncate strings with ellipsis if they become too big.

I also believe we might want to only render the home icon and the current page on mobile, do the implementation on your discretion :)

**Comment by mrkirthi-24** [comment]
Hi @bmuenzenmeyer, I would like to work on this issue.

**Comment by DhairyaMajmudar** [comment]
@ovflowd sir pls. Assign this. I went through the codebase and also understood the approach as suggested by you. It would be so nice of you if this issue is assigned to me

**Comment by ovflowd** [comment]
> Hi @bmuenzenmeyer, I would like to work on this issue.

There is an open PR already.
