### ISSUE TITLE
Create `Pagination` Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5915]
Create a `Pagination` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=495-11573&mode=dev). 

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.
- ❗ Review the [translation guide](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md), especially how to [add new keys](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md#adding-new-translation-keys).

---

### Details

<img width="845" alt="image" src="https://github.com/nodejs/nodejs.org/assets/298435/ec3f8165-b08d-4421-b1a7-f00c5e9c20d6">

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)
🌐 This story requires some internationalization support. Slow down!

- Create a new directory called `Pagination` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/common) that contains all the new code. (This location may change in the future.)
- The `@heroicons/react` module has the icons `arrow-right` and `arrow-left` available for use
- Add a storybook story file `components/common/Pagination/index.stories.tsx` which exercises each of the component's states.
- `Previous` and `Next` must be internationalized. Add new keys `components.common.pagination.prev` and `components.common.pagination.next` to the `i18n/locales/en.json` file. `FormattedMessage` from `react-intl` should be used to reference the keys. Look for examples elsewhere in the codebase.
- always display pages 1, 2,3 and the last three, deduplicated
- style the current page according to the figma
- display an ellipsis when the total number of pages reaches 8 or more

<img width="340" alt="image" src="https://github.com/nodejs/nodejs.org/assets/298435/b35bde3b-40f1-40f9-9a82-5385a78f1b7e">

- use responsive styles to wrap the previous and next buttons below the page links 

<img width="428" alt="image" src="https://github.com/nodejs/nodejs.org/assets/298435/5bdd8236-5e76-46b2-89e9-54724520cae3">

Suggested props include:

- `currentPage` (integer)
- `pages`, an array of objects that looks like this:

```js
[
    {
        value: "1",
        url: "blog/en/1"
    },
    {
        value: "2",
        url: "blog/en/2"
    },
    {
        value: "3",
        url: "blog/en/3"
    },
]
```

> urls subject to change as our blog pagination development continues

There are 3 collection states to capture with stories:

- less than 8 pages, current page visible
- 8 or more pages, current page visible
- 8 or more pages, current page in center with ellipsis on both sides

There are 4 layout states to capture within styles and stories:

- Light, Desktop
- Light, Mobile
- Dark, Desktop
- Dark, Mobile

### Open Questions

If the current page is not in the displayed list per our previous rules, how should it get displayed? Research other pagination patterns to determine how this should look.

Material UI would suggest something like this:

<img width="341" alt="image" src="https://github.com/nodejs/nodejs.org/assets/298435/b0da1e56-ca27-4aaa-8f8c-090355b0b67d">

GitHub does something similar

<img width="586" alt="image" src="https://github.com/nodejs/nodejs.org/assets/298435/c1f9a8c0-f1e6-4bd2-a606-b06c2883bd07">

**Comment by shaikahmadnawaz** [comment]
Can I work on this issue?

**Comment by ovflowd** [comment]
> Can I work on this issue?

Go ahead :)

**Comment by bmuenzenmeyer** [comment]
actually, you just took https://github.com/nodejs/nodejs.org/issues/5911 - please limit yourself to one at a time

**Comment by ovflowd** [comment]
> actually, you just took #5911 - please limit yourself to one at a time

Didn't see that one.

**Comment by shaikahmadnawaz** [comment]
> actually, you just took #5911 - please limit yourself to one at a time

No worries, I will work on this issue after completion of #5911

**Comment by bmuenzenmeyer** [comment]
FYI we try to single thread so someone else might pick this issue up

**Comment by shaikahmadnawaz** [comment]
> FYI we try to single thread so someone else might pick this issue up

Okay 👍

**Comment by PrasathHari** [comment]
> FYI we try to single thread so someone else might pick this issue up

I would like to pick this up.

**Comment by mrkirthi-24** [comment]
Hey @bmuenzenmeyer, Can I work on this issue?

**Comment by shanpriyan** [comment]
Can I take this up?  @ovflowd 🙇🏽‍♂️

**Comment by ovflowd** [comment]
Anyone is free to grab these issues. We usually go on an approach of anyone can contribute. If multiple PRs are opened against this, I don't see it as a bad thing and the first PR that gets merged, alright.

I would ask for people who comment on issues asking if they can work on X, to ask on just one issue per time.

**Comment by danielmarcano** [comment]
Hi, @ovflowd. I would love to work on this issue!

**Comment by danielmarcano** [comment]
Hi, @bmuenzenmeyer.

After carefully reading the requirements, I have come up with a couple of doubts:

- What is the difference between these two states? They both start with "8 or more pages," and the condition for showing the current page in the center with two ellipses on both sides is not clear.
  - "8 or more pages, current page visible"
  - "8 or more pages, current page in center with ellipsis on both sides"
  - Moreover, mimicking the behavior of the [React Material UI one](https://mui.com/material-ui/react-pagination/) seems like a good idea.

- Are the ellipses clickable? If so, what should happen when they are clicked? Similar to before, though, mimicking the [React Material UI one](https://mui.com/material-ui/react-pagination/) behavior and leaving them as decorative elements seems reasonable.

- Can we use the new Common/Button component for all buttons of the Pagination component? Edit: the more accessible way to implement this would be to use anchor links. Should I try to reuse the styles of the button somehow, or create these new anchor links as a sub-component of the `Pagination`?

**Comment by danielmarcano** [comment]
Also, is there a reason why `@apply` is being used in all of the component's styles, instead of using Tailwind classes directly in the `index.tsx` files of the components?

I ask since Tailwind docs do not recommend using @apply for making the template / HTML look cleaner, as mentioned in their [docs](https://tailwindcss.com/docs/reusing-styles#avoiding-premature-abstraction)

**Comment by ovflowd** [comment]
> Also, is there a reason why `@apply` is being used in all of the component's styles, instead of using Tailwind classes directly in the `index.tsx` files of the components?

Read our Collaborator Guide.

> I ask since Tailwind docs do not recommend using https://github.com/apply for making the template / HTML look cleaner, as mentioned in their [docs](https://tailwindcss.com/docs/reusing-styles#avoiding-premature-abstraction)

Right, but it's just a recommendation, not a rule. And we instead separate CSS from the Components to keep the styling separated from the Component. (And other reasons)

**Comment by danielmarcano** [comment]
Awesome, thank you @ovflowd! I have gone through the Collaborator Guide and it's all crystal clear to me now.

**Comment by ovflowd** [comment]
> Hi, @bmuenzenmeyer.
> 
> After carefully reading the requirements, I have come up with a couple of doubts:
> 
> * What is the difference between these two states? They both start with "8 or more pages," and the condition for showing the current page in the center with two ellipses on both sides is not clear.
>   
>   * "8 or more pages, current page visible"
>   * "8 or more pages, current page in center with ellipsis on both sides"
>   * Moreover, mimicking the behavior of the [React Material UI one](https://mui.com/material-ui/react-pagination/) seems like a good idea.
> * Are the ellipses clickable? If so, what should happen when they are clicked? Similar to before, though, mimicking the [React Material UI one](https://mui.com/material-ui/react-pagination/) behavior and leaving them as decorative elements seems reasonable.
> * Can we use the new Common/Button component for all buttons of the Pagination component? Edit: the more accessible way to implement this would be to use anchor links. Should I try to reuse the styles of the button somehow, or create these new anchor links as a sub-component of the `Pagination`?

@bmuenzenmeyer double ping if you could support, Daniel here 🙇

**Comment by bmuenzenmeyer** [comment]
caveat this that i am just translating a static design how i see it - and that @nodejs/ux-and-design / @haydenbleasel is the final say...

> * Are the ellipses clickable? If so, what should happen when they are clicked? Similar to before, though, mimicking the [React Material UI one](https://mui.com/material-ui/react-pagination/) behavior and leaving them as decorative elements seems reasonable.

agree - the user can use the already existing arrows to navigate, no need to make elipses do anything

> Can we use the new Common/Button component for all buttons of the Pagination component? Edit: the more accessible way to implement this would be to use anchor links. Should I try to reuse the styles of the button somehow, or create these new anchor links as a sub-component of the Pagination?

I don't have strong opinions here, excepting that if the current `Button` does not work, it doesn't make a ton of sense to shoehorn it in. Duplication of effort to me is acceptable usually in 1,2 places, and then a third is where we try to be more efficient. so for now I think you should go with what's easiest or ergonomic and we can work it out in PR review. Maybe implementation will reveal a more obvious approach

**Comment by danielmarcano** [comment]
Perfect, thank you both @ovflowd @bmuenzenmeyer! 😎

**Comment by DhairyaMajmudar** [comment]
@ovflowd sir pls. Assign this. I went through the codebase and also understood the approach as suggested by you. It would be so nice of you if this issue is assigned to me .

**Comment by ovflowd** [comment]
> @ovflowd sir pls. Assign this. I went through the codebase and also understood the approach as suggested by you. It would be so nice of you if this issue is assigned to me .

I don't assign issues to people. You want to work on an issue, just do it. PRs are merged on a first-served. (https://www.redhat.com/en/blog/dont-lick-cookie)

**Comment by DhairyaMajmudar** [comment]
> > @ovflowd sir pls. Assign this. I went through the codebase and also understood the approach as suggested by you. It would be so nice of you if this issue is assigned to me .
> 
> I don't assign issues to people. You want to work on an issue, just do it. PRs are merged on a first-served. (https://www.redhat.com/en/blog/dont-lick-cookie)

Sir some of the previous issues which I saw was assigned to someone

**Comment by ovflowd** [comment]
> > > @ovflowd sir pls. Assign this. I went through the codebase and also understood the approach as suggested by you. It would be so nice of you if this issue is assigned to me .
> > 
> > 
> > I don't assign issues to people. You want to work on an issue, just do it. PRs are merged on a first-served. ([redhat.com/en/blog/dont-lick-cookie](https://www.redhat.com/en/blog/dont-lick-cookie))
> 
> Sir some of the previous issues which I saw was assigned to someone

Right, not by me. (Can you also please not call me "sir", thanks)

**Comment by DhairyaMajmudar** [comment]
> > > > @ovflowd sir pls. Assign this. I went through the codebase and also understood the approach as suggested by you. It would be so nice of you if this issue is assigned to me .
> > > 
> > > 
> > > I don't assign issues to people. You want to work on an issue, just do it. PRs are merged on a first-served. ([redhat.com/en/blog/dont-lick-cookie](https://www.redhat.com/en/blog/dont-lick-cookie))
> > 
> > 
> > Sir some of the previous issues which I saw was assigned to someone
> 
> Right, not by me. (Can you also please not call me "sir", thanks)

Oh! okay Bhaiya ( Word used to show respect in India ) then to whom should I ask for issue assignment

**Comment by ovflowd** [comment]
> > > > > @ovflowd sir pls. Assign this. I went through the codebase and also understood the approach as suggested by you. It would be so nice of you if this issue is assigned to me .
> > > > 
> > > > 
> > > > I don't assign issues to people. You want to work on an issue, just do it. PRs are merged on a first-served. ([redhat.com/en/blog/dont-lick-cookie](https://www.redhat.com/en/blog/dont-lick-cookie))
> > > 
> > > 
> > > Sir some of the previous issues which I saw was assigned to someone
> > 
> > 
> > Right, not by me. (Can you also please not call me "sir", thanks)
> 
> Oh! okay Bhaiya ( Word used to show respect in India ) then to whom should I ask for issue assignment

Right, no worries. (Now I learnt a word in Indian)

So, my recommendation is just work on a task. Assignment is just a formality. You can simply work on the issue and open an PR, and that's it :)

**Comment by DhairyaMajmudar** [comment]
> > > > > > @ovflowd sir pls. Assign this. I went through the codebase and also understood the approach as suggested by you. It would be so nice of you if this issue is assigned to me .
> > > > > 
> > > > > 
> > > > > I don't assign issues to people. You want to work on an issue, just do it. PRs are merged on a first-served. ([redhat.com/en/blog/dont-lick-cookie](https://www.redhat.com/en/blog/dont-lick-cookie))
> > > > 
> > > > 
> > > > Sir some of the previous issues which I saw was assigned to someone
> > > 
> > > 
> > > Right, not by me. (Can you also please not call me "sir", thanks)
> > 
> > 
> > Oh! okay Bhaiya ( Word used to show respect in India ) then to whom should I ask for issue assignment
> 
> Right, no worries. (Now I learnt a word in Indian)
> 
> So, my recommendation is just work on a task. Assignment is just a formality. You can simply work on the issue and open an PR, and that's it :)

Okay Bhaiya Thank you so much 😃

**Comment by danielmarcano** [comment]
Hi, @ovflowd and @bmuenzenmeyer, hope you are doing great. I have completed the development of this component in this [PR](https://github.com/nodejs/nodejs.org/pull/5971).

Please let me know if you have any questions, or if there's any modifications that need to be made.

Thank you, and have a great weekend!
