### ISSUE TITLE
Url doesn't match heading

### ISSUE THREAD

**Issue by williamkapke** [nodejs/nodejs.org#592]
The heading says "2015-04-17" but the URL is:
https://nodejs.org/en/foundation/tsc/minutes/2015-04-16/

**Comment by phillipj** [comment]
@williamkapke Good catch! I've located the original PR https://github.com/nodejs/nodejs.org-archive/pull/107 which created the minutes doc, but can't see any hint about which date the meeting was held.

I'm closing this for now as the difference between the two dates are not significant, and not sure using hours on digging into this is is worthwhile. Feel free to re-open the issue if you feel differently and would like to digg deeper into it.
