### ISSUE TITLE
Unable to Run Node.js Website Locally on Windows 11 with Node.js 18.18.0 and npm 9.8.1

### ISSUE THREAD

**Issue by shaikahmadnawaz** [nodejs/nodejs.org#5921]
### URL:

https://github.com/nodejs/nodejs.org

### Browser Name:

Brave

### Browser Version:

v1.58.135

### Operating System:

Windows 11, 22H2, 22621.2283

### How to reproduce the issue:

**Problem:** I am encountering difficulties when trying to run the Node.js Website locally on my Windows 11 machine using Node.js version 18.18.0 and npm version 9.8.1. The local development environment is not working as expected.

**Steps to Reproduce:**
1. Clone the Node.js Website repository.
2. Run `npm ci` to install project dependencies.
3. Attempt to start the local preview with `npx turbo serve`.

**Expected Behavior:** The local development environment should start without errors, allowing me to preview my changes.

**Actual Behavior:**

`npm ci`

![Screenshot (1286)](https://github.com/nodejs/nodejs.org/assets/96189881/6c794e42-36cc-4ef3-9271-27b22a356cc0)

`npx turbo serve`

![Screenshot (1287)](https://github.com/nodejs/nodejs.org/assets/96189881/fdf026a1-1aaa-4143-bf77-9e529708fe13)

**Environment:**

- Operating System: Windows 11
- Node.js Version: 18.18.0
- npm Version: 9.8.1

**Comment by AugustinMauroy** [comment]
have you try to use `npm I` ? it's can change something 🤔

**Comment by shaikahmadnawaz** [comment]
> have you try to use `npm I` ? it's can change something 🤔

I tried that too.

**Comment by shaikahmadnawaz** [comment]
> have you try to use `npm I` ? it's can change something 🤔

![Screenshot (1290)](https://github.com/nodejs/nodejs.org/assets/96189881/8d8904eb-47bf-43f2-9819-c6a9ad0b60b3)

Check this once @AugustinMauroy

**Comment by AugustinMauroy** [comment]
could you try to remove `node_modules` and after `npm i` ?

**Comment by shaikahmadnawaz** [comment]
> could you try to remove `node_modules` and after `npm i` ?

![Screenshot (1291)](https://github.com/nodejs/nodejs.org/assets/96189881/bf0b454a-94f1-4c2f-992f-5eb8c21c457a)

Still facing the same error 🥲, please help.

**Comment by AugustinMauroy** [comment]
apart from the error message during installation, what happens when you run the project ?

**Comment by shaikahmadnawaz** [comment]
> apart from the error message during installation, what happens when you run the project ?

![Screenshot (1292)](https://github.com/nodejs/nodejs.org/assets/96189881/894d72d9-61f7-4e75-9a33-0574201eb106)
![Screenshot (1293)](https://github.com/nodejs/nodejs.org/assets/96189881/c0a067fb-98e1-4f16-99c7-93cdc5877bc8)

**Comment by AugustinMauroy** [comment]
what is the change do in your branch ?

**Comment by shaikahmadnawaz** [comment]
> what is the change do in your branch ?

![Screenshot (1295)](https://github.com/nodejs/nodejs.org/assets/96189881/272a0b30-100d-4416-b411-de44d2e9a513)
![Screenshot (1296)](https://github.com/nodejs/nodejs.org/assets/96189881/d66909b9-0caa-44f6-b5bc-23a16bbf7a7f)
![Screenshot (1297)](https://github.com/nodejs/nodejs.org/assets/96189881/eec3c2b9-71e0-4862-a537-6445546e78a7)
![Screenshot (1298)](https://github.com/nodejs/nodejs.org/assets/96189881/1405aae9-cc33-4fb9-8283-fa7d34306028)

These are automatically generated when I try to install and run it.

**Comment by AugustinMauroy** [comment]
try to discard change. If not, I don't know why it's doing that.

**Comment by ovflowd** [comment]
> > what is the change do in your branch ?
> 
> ![Screenshot (1295)](https://user-images.githubusercontent.com/96189881/271768529-272a0b30-100d-4416-b411-de44d2e9a513.png) ![Screenshot (1296)](https://user-images.githubusercontent.com/96189881/271768533-d66909b9-0caa-44f6-b5bc-23a16bbf7a7f.png) ![Screenshot (1297)](https://user-images.githubusercontent.com/96189881/271768548-eec3c2b9-71e0-4862-a537-6445546e78a7.png) ![Screenshot (1298)](https://user-images.githubusercontent.com/96189881/271768554-1405aae9-cc33-4fb9-8283-fa7d34306028.png)
> 
> These are automatically generated when I try to install and run it.

The changes on package-lock should not be done. The files on `public` are generated automatically and that's fine. The changes on the VS Code settings are due to you probably altering it. Either by accepting/rejecting a VS Code prompt.

**Comment by ovflowd** [comment]
> > have you try to use `npm I` ? it's can change something 🤔
> 
> ![Screenshot (1290)](https://user-images.githubusercontent.com/96189881/271765450-8d8904eb-47bf-43f2-9819-c6a9ad0b60b3.png)
> 
> Check this once @AugustinMauroy

This is fine. We manually disable Next.js telemtry.

**Comment by shaikahmadnawaz** [comment]
Okay then, any solution for this? to stop the change in `package-lock.json` @ovflowd

**Comment by ovflowd** [comment]
It's important to mention that react is a peer dependency (https://github.com/nodejs/nodejs.org/blob/main/package.json) and since NPM v7 they are automatically installed.

Something is wrong on your Node.js setup. That's the only I thing I can think of. Do you use WSL or anything? How did you install Node.js?

**Comment by ovflowd** [comment]
I've made a fresh clone here, on my Windows machine. Everything is working fine.

![image](https://github.com/nodejs/nodejs.org/assets/12037269/a280e0de-8c24-46a2-8614-f3e472f7ec31)

**Comment by ovflowd** [comment]
My recommendation:

- Reinstall Git, and use Git Bash if possible
- Reinstall Node.js and check the mark of "install additional node.js dev tools" when using the Node.js installer. Download the latest LTS.
- Delete the nodejs.org folder after all of this and reclone the repository
- Disable/Remove VSCode Extensions. We recommend only using the ones recommended by the repository (.vscode/extensions.json)
  - Sometimes other extensions play and mess around with things

**Comment by ovflowd** [comment]
Also, regarding these two files, simply read the Collaborator Guidelines. These are autogenerated files, and they always generate automatically. It's fine keeping them and they never commit by themselves. We have a Git Hook that automatically ignores these files on commits.

![image](https://github.com/nodejs/nodejs.org/assets/12037269/159890a2-9ff6-43ed-90c5-2873710448f9)

**Comment by shaikahmadnawaz** [comment]
> It's important to mention that react is a peer dependency (https://github.com/nodejs/nodejs.org/blob/main/package.json) and since NPM v7 they are automatically installed.
> 
> Something is wrong on your Node.js setup. That's the only I thing I can think of. Do you use WSL or anything? How did you install Node.js?

I used NVM to install nodejs 18.18.0

**Comment by shaikahmadnawaz** [comment]
> My recommendation:
> 
> * Reinstall Git, and use Git Bash if possible
> * Reinstall Node.js and check the mark of "install additional node.js dev tools" when using the Node.js installer. Download the latest LTS.
> * Delete the nodejs.org folder after all of this and reclone the repository
> * Disable/Remove VSCode Extensions. We recommend only using the ones recommended by the repository (.vscode/extensions.json)
>   
>   * Sometimes other extensions play and mess around with things

Sure, I will do all these steps.

**Comment by shaikahmadnawaz** [comment]
> Also, regarding these two files, simply read the Collaborator Guidelines. These are autogenerated files, and they always generate automatically. It's fine keeping them and they never commit by themselves. We have a Git Hook that automatically ignores these files on commits.
> 
> ![image](https://user-images.githubusercontent.com/12037269/271770188-159890a2-9ff6-43ed-90c5-2873710448f9.png)

Okay

**Comment by shaikahmadnawaz** [comment]
> I've made a fresh clone here, on my Windows machine. Everything is working fine.
> 
> ![image](https://user-images.githubusercontent.com/12037269/271770101-a280e0de-8c24-46a2-8614-f3e472f7ec31.png)

Thank you so much for making these many efforts for me @ovflowd

**Comment by ovflowd** [comment]
No worries. Hopefully you figure out what's wrong

**Comment by shaikahmadnawaz** [comment]
> No worries. Hopefully you figure out what's wrong

Yes, working on the steps you mentioned, will update you if I figure it out. 👍

**Comment by shaikahmadnawaz** [comment]
It's not working 🥲 @ovflowd

**Comment by shaikahmadnawaz** [comment]
It's okay leave, I am using GitHub codespace to run it locally, see @ovflowd this is how it looks ✨

![Screenshot (1299)](https://github.com/nodejs/nodejs.org/assets/96189881/7cd195d8-c240-4845-93dc-5d78b639e0a3)
![Screenshot (1300)](https://github.com/nodejs/nodejs.org/assets/96189881/cc86284a-fc2e-48cc-89df-429bf50afa86)

**Comment by ovflowd** [comment]
Do you have Git Bash installed?

Can you run ls -la within node_modules with Git Bash?

How are you installing packages?

Are you still using NVM? Have you installed node with Node MSI installer and added the additional tools?

**Comment by ovflowd** [comment]
> It's okay leave, I am using GitHub codespace to run it locally, see @ovflowd this is how it looks ✨
> 
> 
> 
> ![Screenshot (1299)](https://github.com/nodejs/nodejs.org/assets/96189881/7cd195d8-c240-4845-93dc-5d78b639e0a3)
> 
> ![Screenshot (1300)](https://github.com/nodejs/nodejs.org/assets/96189881/cc86284a-fc2e-48cc-89df-429bf50afa86)
> 
> 

Codespaces saves the day, but Id still love to get to the bottom of it 😅

As Im genuinely curious what could be causing this 🫠

**Comment by shaikahmadnawaz** [comment]
> Do you have Git Bash installed?
> 
> Can you run ls -la within node_modules with Git Bash?
> 
> How are you installing packages?
> 
> Are you still using NVM? Have you installed node with Node MSI installer and added the additional tools?

git did, Yes, I installed node with Node MSI installer and added the additional tools, yes I can run ls -la within node_modules with Git Bash, I am Installing packages using git bash and the command is npm ci

**Comment by ovflowd** [comment]
> > Do you have Git Bash installed?
> 
> > 
> 
> > Can you run ls -la within node_modules with Git Bash?
> 
> > 
> 
> > How are you installing packages?
> 
> > 
> 
> > Are you still using NVM? Have you installed node with Node MSI installer and added the additional tools?
> 
> 
> 
> git did, Yes, I installed node with Node MSI installer and added the additional tools, yes I can run ls -la within node_modules with Git Bash, I am Installing packages using git bash and the command is npm ci

Gotcha, what I meant to ask is if with ls -la you see the react folder inside node_modules

I want to understand if somehow npm decided to not install the peerDependency

**Comment by shaikahmadnawaz** [comment]
![image](https://github.com/nodejs/nodejs.org/assets/96189881/59bc413f-f9bf-41fe-b7e6-98aaefd1c4b3)
![image](https://github.com/nodejs/nodejs.org/assets/96189881/5e55c646-8006-4d04-9b33-981a10dbd89e)

**Comment by shaikahmadnawaz** [comment]
> > > Do you have Git Bash installed?
> > 
> > 
> > > 
> > 
> > 
> > > Can you run ls -la within node_modules with Git Bash?
> > 
> > 
> > > 
> > 
> > 
> > > How are you installing packages?
> > 
> > 
> > > 
> > 
> > 
> > > Are you still using NVM? Have you installed node with Node MSI installer and added the additional tools?
> > 
> > 
> > git did, Yes, I installed node with Node MSI installer and added the additional tools, yes I can run ls -la within node_modules with Git Bash, I am Installing packages using git bash and the command is npm ci
> 
> Gotcha, what I meant to ask is if with ls -la you see the react folder inside node_modules
> 
> I want to understand if somehow npm decided to not install the peerDependency

![image](https://github.com/nodejs/nodejs.org/assets/96189881/1ed63d38-38a8-4c95-8719-9059fd268cb9)
![image](https://github.com/nodejs/nodejs.org/assets/96189881/521530d8-afbe-477b-88a6-e3cf14f38d5f)

**Comment by ovflowd** [comment]
I mean can you run

`cd node_modules && ls -la`

Also last question, do you have a `.npmrc` on your machine?


```
cat ~/.npmrc
```

**Comment by shaikahmadnawaz** [comment]
> I mean can you run
> 
> `cd node_modules && ls -la`
> 
> Also last question, do you have a `.npmrc` on your machine?
> 
> ```
> cat ~/.npmrc
> ```

![image](https://github.com/nodejs/nodejs.org/assets/96189881/31ca2927-f08a-463e-9548-6cb13e89b797)

**Comment by shaikahmadnawaz** [comment]
> cat ~/.npmrc

```
$ cat ~/.npmrc
legacy-peer-deps=true
```

**Comment by ovflowd** [comment]
> > cat ~/.npmrc
> 
> ```
> $ cat ~/.npmrc
> legacy-peer-deps=true
> ```

We found the issue. can you delete that file? And then delete `node_modules` of your repository and run `npm i` again. That should do the trick...

**Comment by shaikahmadnawaz** [comment]
> > > cat ~/.npmrc
> > 
> > 
> > ```
> > $ cat ~/.npmrc
> > legacy-peer-deps=true
> > ```
> 
> We found the issue. can you delete that file? And then delete `node_modules` of your repository and run `npm i` again. That should do the trick...

Yes, doing

**Comment by shaikahmadnawaz** [comment]
![image](https://github.com/nodejs/nodejs.org/assets/96189881/1c83ae56-5c30-4a02-b6ac-36dc4f5c7f4b)

**Comment by ovflowd** [comment]
Yeah seems alright now, feel free to try `npx turbo serve`

**Comment by shaikahmadnawaz** [comment]
![image](https://github.com/nodejs/nodejs.org/assets/96189881/2977715e-353f-4340-9415-9ee52f95c810)
![image](https://github.com/nodejs/nodejs.org/assets/96189881/ee8e5a4c-3d6e-4e59-b034-73c6d97df988)

Here we go, now it's working absolutely fine ✨

**Comment by ovflowd** [comment]
Glad to hear issue was solved ;)

**Comment by shaikahmadnawaz** [comment]
Thank you so much for guiding me, and hats off to your patience @ovflowd 👏

**Comment by ovflowd** [comment]
> Thank you so much for guiding me, and hats off to your patience @ovflowd 👏

Of course :) Here to help!

**Comment by shaikahmadnawaz** [comment]
One final query, what does .npmrc file do or why it is added or removed? @ovflowd

**Comment by ovflowd** [comment]
> One final query, what does .npmrc file do or why it is added or removed? @ovflowd

`.npmrc` is a NPM configuration file that allows you to override default NPM settings. The issue that comes from that specific issue, is that since NPM v7, `peerDependencies` (which react is one) are installed automatically alongside regular dependencies.

With the `legacy-peer-deps` they won't. Hence why `react` did not get installed.

More details: https://github.com/npm/cli/issues/4934
