### ISSUE TITLE
Website WG Meetings

### ISSUE THREAD

**Issue by williamkapke** [nodejs/nodejs.org#593]
From: https://github.com/nodejs/nodejs.org/blob/master/GOVERNANCE.md#wg-meetings

> The WG meets weekly on a Google Hangout On Air. The meeting is run by a designated moderator approved by the WG. Each meeting should be published to YouTube.

Which YouTube account has the videos?
Where can I view the past agendas/minutes?
Where do future meetings get announced?

**Comment by MylesBorins** [comment]
@williamkapke afaik there has not been a WG meeting for the website team since I joined the org in october...

I bet that copy is old and should likely be updated

**Comment by phillipj** [comment]
No WG meetings since I got involved in august either. Could be there were some meetings in the io.js periode, possibly something @fhemberger knows more about.

Both `README.md` and `GOVERANCE.md` really needs updating.

**Comment by fhemberger** [comment]
I only participated once on an io.js call last year when I started working on the website. ;) So yes, this is old and should be updated. The GitHub flow worked so well for the website team so far, there simply wasn't the need to get together in a call. Also we have far more contributors working on the site compared to last year, so everything is just running smoothly. :+1:

**Comment by justsml** [comment]
Good to know, I thought I was missing out.

**Comment by mikeal** [comment]
This WG works really well without meetings, adding them would only end up excluding some people who have timezone difficulties.

**Comment by fhemberger** [comment]
Closed via a1e54a8cc3f6b81fea8b3c45813a491696f7e384.

**Comment by williamkapke** [comment]
This is a FAST group! :D 

...however I missed my chance to comment before the merge:
https://github.com/nodejs/nodejs.org/pull/598#issuecomment-200964250

I had just said:

> I think it would be better to say something that indicates that there are no regularly scheduled meetings, but the group may choose to schedule one at its discretion.
> 
> Having nothing might make someone unsure if they're just not looking the the right place.

Thoughts?

**Comment by phillipj** [comment]
Just answered your comment in #598.
