### ISSUE TITLE
Create `Anchor` styling

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5933]
Create a anchor `<a/>` styling using the new [figma design (pagelink)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=696-15704&mode=dev). 

This isn't a new React component, just a globally styled HTML element we want to illustrate. The primary use case for this styling is anchor tags within rendered markdown/MDX files.

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/ce3b222a-3f61-4eab-9481-61b399bbd3d0)

![image](https://github.com/nodejs/nodejs.org/assets/298435/b77d4fb1-f3dc-4d1c-b481-91ffde866439)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Add these anchor styles to the existing [storybook story file `components/__design__/text.stories.tsx`](https://github.com/nodejs/nodejs.org/blob/main/components/__design__/text.stories.tsx)which will excercise each of the component's states.
- Use the new tailwind color and typography system to assign properties. For example, Dark `color` uses Green/400 per the figma.

There are 2 states to capture within styles and stories:

- Light
- Dark

### Open Questions

Could we make this an `Anchor` component and then add it to an MDX provider? That might isolate markdown-driven use cases more, but at the cost of increased complexity. For now, let's show what an `<a/>` tag renders like. Perhaps what it looks like within `<p>` tag only?

**Comment by ovflowd** [comment]
I think you forgot to mention the file were those styles should be done? Which I think probably is `styles/new/base.css`...

**Comment by SayyamJain101** [comment]
@bmuenzenmeyer I would like to solve this issue. Please assign me.

**Comment by Baburao-sanivada** [comment]
Hii There
On my way to review the issue I tried to find blog Section in your website i couldn't find it
and can i know where the browser should be redirected when clicked on the list items?

**Comment by ovflowd** [comment]
> @bmuenzenmeyer I would like to solve this issue. Please assign me.

We usually avoid assigning issues to newcomers (in the sense of assign the issue), but please feel free to work on the issue.

**Comment by ovflowd** [comment]
> Hii There On my way to review the issue I tried to find blog Section in your website i couldn't find it and can i know where the browser should be redirected when clicked on the list items?

Not sure I get your questions. Please re-read what is being asked to be done here.

**Comment by shaikahmadnawaz** [comment]
![Screenshot 2023-10-01 153911](https://github.com/nodejs/nodejs.org/assets/96189881/aae9f58b-d6a6-45c0-b57b-080fc937adbd)
![Screenshot 2023-10-01 153937](https://github.com/nodejs/nodejs.org/assets/96189881/c329f22a-4f28-4cfb-aa08-ec7ae97fedb4)

Hey are they okay? @ovflowd @bmuenzenmeyer

**Comment by shaikahmadnawaz** [comment]
![Screenshot 2023-10-01 234015](https://github.com/nodejs/nodejs.org/assets/96189881/078faedc-b58e-47f3-bd11-a0f314817114)

![Screenshot 2023-10-01 234000](https://github.com/nodejs/nodejs.org/assets/96189881/cbe3bf0d-88a9-4f3d-b7d2-d5fca59158a7)

Hey, are they okay? @ovflowd @bmuenzenmeyer

**Comment by shaikahmadnawaz** [comment]
Hello @ovflowd

**Comment by ovflowd** [comment]
> Hey, are they okay? @ovflowd @bmuenzenmeyer

Please don't spam an issue with development questions. You can create a Draft PR and do that there, thank you!

**Comment by shaikahmadnawaz** [comment]
> > Hey, are they okay? @ovflowd @bmuenzenmeyer
> 
> Please don't spam an issue with development questions. You can create a Draft PR and do that there, thank you!

Sorry @ovflowd

**Comment by ovflowd** [comment]
> > > Hey, are they okay? @ovflowd @bmuenzenmeyer
> > 
> > 
> > Please don't spam an issue with development questions. You can create a Draft PR and do that there, thank you!
> 
> Sorry @ovflowd

All good, no worries :)

**Comment by danielmarcano** [comment]
Hi, @ovflowd.

I was looking for an issue to work on, and have realized that this issue is no longer open, as it seems to have been merged in this [PR](https://github.com/nodejs/nodejs.org/pull/5954)

Could you please mark this one as closed?

**Comment by ovflowd** [comment]
Sorry! My bad, forgot to close this issue 😅
