### ISSUE TITLE
Create `inline code block` styling

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5934]
Create a inline code `<code/>` styling using the new [figma design (pagelink)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=696-15704&mode=dev). 

This isn't a new React component, just a globally styled HTML element we want to illustrate. The primary use case for this styling is \`code\` tags within rendered markdown/MDX files.

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/afa66d9d-8c7f-45d4-a4b7-c05a0d525334)

![image](https://github.com/nodejs/nodejs.org/assets/298435/10e132a7-1bd9-4c11-afa7-2e0c1a27d00c)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Add these code block styles to the existing [storybook story file `components/__design__/text.stories.tsx`](https://github.com/nodejs/nodejs.org/blob/main/components/__design__/text.stories.tsx)which will excercise each of the component's states.
- Use the new tailwind color and typography system to assign properties. For example, Light `background` uses Neutral/100 per the figma.

There are 2 states to capture within styles and stories:

- Light
- Dark

### Open Questions

Could we make this an `InlineCodeblock` component and then add it to an MDX provider? That might isolate markdown-driven use cases more, but at the cost of increased complexity. For now, let's show what an `<code/>` tag renders like. Perhaps what it looks like within `<p>` tag only?

**Comment by akhilender-bongirwar** [comment]
@bmuenzenmeyer, I would like to try working on this issue. Please assign me : ).

**Comment by bmuenzenmeyer** [comment]
go ahead, thanks!

**Comment by ovflowd** [comment]
I think you forgot to mention the file were those styles should be done? Which I think probably is `styles/new/base.css`...
