### ISSUE TITLE
Create `unordered` and `ordered` list styling

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5935]
Create a unordered `<ul/>` and ordered `<ol/>` styling using the new [figma design (pagelink)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=696-15704&mode=dev). 

This aren't a new React components, just a globally styled HTML elements we want to illustrate. The primary use case for this styling is `<ul/>` and `<ol/>` tags within rendered markdown/MDX files.

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/b795ec18-5433-44ad-b375-f0f3e3ff327b)

![image](https://github.com/nodejs/nodejs.org/assets/298435/3a6f59aa-2cd7-4527-879d-fb499454fa83)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Add these list styles to the existing [storybook story file `components/__design__/text.stories.tsx`](https://github.com/nodejs/nodejs.org/blob/main/components/__design__/text.stories.tsx)which will excercise each of the component's states.
- Use the new tailwind color and typography system to assign properties. These might in fact just be tailwind defaults, so make sure to spend time confirming that.

There are 4 states to capture within styles and stories:

- Light, ordered
- Light, unordered
- Dark, ordered
- Dark, unordered

Feel free to provide some nesting, the screnshots do not show this

### Open Questions

Could we make these a `OrderedList` and `UnorderedList` components and then add them to an MDX provider? That might isolate markdown-driven use cases more, but at the cost of increased complexity. For now, let's show what the raw tags renders like.

**Comment by vk-44** [comment]
Hi, I would like to work on this. Please assign me.

**Comment by ovflowd** [comment]
I think you (@bmuenzenmeyer) forgot to mention the file were those styles should be done? Which I think probably is `styles/new/base.css`...

**Comment by charandeepsinghb** [comment]
Hi, I'll be happy to work on this and be part of the community!

I've reviewed the design and understood the requirements 😊.

Thank you

**Comment by princepal-dev** [comment]
Hii, can you assign this to me? 
Thanks

**Comment by devendra66** [comment]
Can you assign this to me I would like to work on this issue
Thanks

**Comment by kshitij-hash** [comment]
Hi @bmuenzenmeyer 

I've updated [components/__design__/text.stories.tsx](https://github.com/nodejs/nodejs.org/blob/main/components/__design__/text.stories.tsx) to include tailored styles for `<ol/>` and `<ul/>` based on Figma's design. 
The styles reflecting the mentioned four states: Light ordered/unordered and Dark ordered/unordered, using the new tailwind color and typography system. Screenshots are attached for your review.
 
Do let me know if any changes are required.

![dark_mode](https://github.com/nodejs/nodejs.org/assets/83551355/9d9d9282-e4ae-4644-b035-0396f685d6d7)
![light_mode](https://github.com/nodejs/nodejs.org/assets/83551355/dcc07416-8877-4ba7-bfc8-fe772349cefa)
