### ISSUE TITLE
Create `Notification` Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5948]
Create a `Notification` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=616-6963&mode=dev). 

> This issue is broken out of https://github.com/nodejs/nodejs.org/issues/5819

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.
- ❗ Review the [translation guide](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md), especially how to [add new keys](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md#adding-new-translation-keys).

---

### Details

<img width="467" alt="image" src="https://github.com/nodejs/nodejs.org/assets/298435/3f4329cf-2af1-47a9-bc8d-e0a8997b8e45">

<img width="312" alt="image" src="https://github.com/nodejs/nodejs.org/assets/298435/59fdb610-9cd4-4fb3-b908-987726d244d3">

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)
🌐 This story requires some internationalization support. Slow down!

- Create a new directory called `Notification` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/common) that contains all the new code.
- For a period of `5` seconds (configurable via the `Provider` (see below)), show the `Notification` on the bottom right of the screen. Use the [`Toast`](https://www.radix-ui.com/primitives/docs/components/toast) radix component, which will need to be installed. Follow the [the dependency guide](https://github.com/nodejs/nodejs.org/blob/main/DEPENDENCY_PINNING.md). 
- Use the hero-icon `code-bracket`. This is a slight variant of the Figma, as the icon in the design is not available. This functionality matches the "component" called [`Notification` within the Figma](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=616-6968&mode=dev)
 - `Copied to clipboard!` must be internationalized. Add a new key `components.common.codebox.copied` to the `i18n/locales/en.json` file. `FormattedMessage` from `react-intl` should be used to reference the key. Look for examples elsewhere in the codebase.
- Add a storybook story file `components/common/Codebox/index.stories.tsx` which exercises each of the component's states.
- Radix `Toast` requires a global `Provider` wrapper around the entire application. This will need to be present in the storybooks too https://www.radix-ui.com/primitives/docs/components/toast#provider either as a new file within https://github.com/nodejs/nodejs.org/tree/main/providers and/or simply wrapped within https://github.com/nodejs/nodejs.org/blob/main/.storybook/preview.tsx for now

There are 2 states to capture within styles and stories:

- Light
- Dark

**Comment by bmuenzenmeyer** [comment]
@ovflowd do you have opinions where the `Notification` `Toast.Provider` should be?

**Comment by ovflowd** [comment]
> @ovflowd do you have opinions where the `Notification` `Toast.Provider` should be?

Within the `Providers` folder. And when used, it wraps the App. But right now on Storybook it would wrap `preview.tsx`

**Comment by Yogesh01000100** [comment]
Hi I would like to work on this, can you assign this to me!

**Comment by madtitan02** [comment]
Hi, I would like to work on this issue can you assign this to me, Thanks.

**Comment by ovflowd** [comment]
We do not assign issues to newcomers. Simply feel free to work on a PR.

**Comment by fa-901** [comment]
> Add a storybook story file components/common/Codebox/index.stories.tsx which exercises each of the component's states.

@bmuenzenmeyer is this correct? Shouldn't it be `components/common/Notification/index.stories.tsx`?

**Comment by ovflowd** [comment]
> > Add a storybook story file components/common/Codebox/index.stories.tsx which exercises each of the component's states.
> 
> @bmuenzenmeyer is this correct? Shouldn't it be `components/common/Notification/index.stories.tsx`?

Right, you're correct.

**Comment by DhairyaMajmudar** [comment]
@bmuenzenmeyer I pls. assign this issue to me . I have gone through  the codebase and also the approach told by you is known to me. So will be following the same approach to implement this feature

**Comment by DhairyaMajmudar** [comment]
@bmuenzenmeyer pls. assign this issue to me . I have gone through  the codebase and also the approach told by you is known to me. So will be following the same approach to implement this feature

**Comment by ovflowd** [comment]
> @bmuenzenmeyer pls. assign this issue to me . I have gone through the codebase and also the approach told by you is known to me. So will be following the same approach to implement this feature

There is already a PR open...

**Comment by DhairyaMajmudar** [comment]
> > @bmuenzenmeyer pls. assign this issue to me . I have gone through the codebase and also the approach told by you is known to me. So will be following the same approach to implement this feature
> 
> There is already a PR open...

oh ! I understand. Sir can you pls. assign me any other issue. It would be so nice of you.
