### ISSUE TITLE
Comment each actions/checkout sha with the correct full version numer

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5965]
Take a look at the files at https://github.com/nodejs/nodejs.org/pull/5937/files

This PR is showing me that all actions labeled with the right version comment

Only one had dependabot accurately update its version number in the comment. I suspect this is because they are either:

- missing completely
- not a direct, complete semver `3.5` instead of `3.5.x`

For each image in our workflows, reference the sha and add a the full comment afterwards

For example:

`actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608` is a reference to https://github.com/actions/checkout/releases and https://github.com/actions/checkout/commit/8ade135a41bc03ea155e62e844d188df1ea18608

note the shorthad sha in the left side of the screenshot below

![image](https://github.com/nodejs/nodejs.org/assets/298435/39a48605-ab76-4e3f-ae1a-5766e1db89a8)

So the line should be 

```
      - name: Git Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
```

_Originally posted by @bmuenzenmeyer in https://github.com/nodejs/nodejs.org/pull/5937#pullrequestreview-1658225230_

**Comment by rahulrk-dev** [comment]
Hi @bmuenzenmeyer, can I work on this?

**Comment by bmuenzenmeyer** [comment]
No need to ask, go ahead
