### ISSUE TITLE
Download links are not links on release posts

### ISSUE THREAD

**Issue by richardlau** [nodejs/nodejs.org#5977]
### URL:

https://nodejs.org/en/blog/release/v20.8.0

### Browser Name:

Edge

### Browser Version:

117.0.2045.60

### Operating System:

Windows 11 Enterprise, 22H2, 22621.2283

### How to reproduce the issue:

Go to any of  the release posts on nodejs.org. e.g.
- https://nodejs.org/en/blog/release/v20.8.0
- https://nodejs.org/en/blog/release/v19.3.0

Note that the download links are not links:
![image](https://github.com/nodejs/nodejs.org/assets/5445507/79eda4d2-a6b8-4a15-bce5-de8aaa17bdd8)

Compare to the old site (from 1 Jan 2023 via the Internet Archive): http://web.archive.org/web/20221223205720/https://nodejs.org/en/blog/release/v19.3.0/
![image](https://github.com/nodejs/nodejs.org/assets/5445507/f5bfda3d-06ea-4c8a-ba76-f4757b7ca89f)

**Comment by ovflowd** [comment]
I think MDX might not be _by default_ transforming text into links when not explicitly asked for. I wonder if this is a GitHub Flavored Markdown thing.

I'm not usually a fan of automagically transforming text into links without due reason; I think a more straightforward future-proof solution is to update the release script generation to make these explicit links and retroactively update all existing blog posts (if possible).

Or we simply automatically convert links.

As far as I can see `remark-gfm` should do the trick. I can see if this easily fixes the issue. I remember we had issues with remark-gfm lately.

**Comment by ovflowd** [comment]
~Apparently the issue of `remark-gfm` got fixed: https://github.com/remarkjs/remark-gfm/issues/57~

Nope, still broken https://github.com/hashicorp/next-mdx-remote/issues/403

**Comment by ovflowd** [comment]
(Note that we had remark-gfm but we removed)

**Comment by ljharb** [comment]
yes, GFM auto-turns all URLs into links.
