### ISSUE TITLE
Create `Footer` Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5980]
Create a `Footer` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=415-9454&mode=dev). 

This component completes the responsive footer for the new site.

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/4555ed1e-0f8c-4736-9268-bd2976050e26)
![image](https://github.com/nodejs/nodejs.org/assets/298435/03b7c82f-e51f-4a57-9329-fc7abca3e56b)

![image](https://github.com/nodejs/nodejs.org/assets/298435/3d2d5379-a4c4-4d82-94c8-f321f2973f88)
![image](https://github.com/nodejs/nodejs.org/assets/298435/170ac236-9bdc-4d41-a36d-d1c6756901b4)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Create a new directory called `Footer` within the [`sections` directory](https://github.com/nodejs/nodejs.org/tree/main/components/sections) that contains all the new code.
- Use the new `NavItem` component introduced within https://github.com/nodejs/nodejs.org/pull/5972
- Use the social icons already [added to the site as assets](https://github.com/nodejs/nodejs.org/tree/main/public/static/images/logos). Using Next [Image](https://nextjs.org/docs/pages/api-reference/components/image) is fine for now, though these may change to React SVGs in the future. 
  - The figmas show the old X icon. Use the twitter icon
  - For some light or dark modes, the fill of an icon may need to change 
- The figma puts the mobile breakpoint at 375px. Explore if we can use that directly or an [new/existing tailwind token (if any)](https://github.com/nodejs/nodejs.org/blob/main/tailwind.config.ts)
- Add a storybook story file `components/sections/Footer/index.stories.tsx` which exercises each of the component's states.

The links:

- [Trademark Policy](https://trademark-policy.openjsf.org/)
- [Privacy Policy](https://privacy-policy.openjsf.org/)
- [Code of Conduct](https://code-of-conduct.openjsf.org/)
- [Security](https://github.com/nodejs/node/blob/HEAD/SECURITY.md#security)
- [OpenJS Foundation](https://openjsf.org/)
- [GitHub](https://github.com/nodejs/node)
- [Mastadon](https://social.lfx.dev/@nodejs)
- [Twitter](https://twitter.com/nodejs)
- [Slack](https://slack-invite.openjsf.org/)
- [LinkedIn](https://www.linkedin.com/company/node-js)

There are 4 Footer states to capture within styles and stories:

- Light
- Light, mobile
- Dark
- Dark, mobile

### Open Questions to Discuss

The footer is not currently internationalized. @ovflowd is this a design goal? See https://nodejs.org/es or https://nodejs.org/de

**Comment by shishiro26** [comment]
@bmuenzenmeyer I would like to work on this issue can u please assign this to me.

**Comment by bmuenzenmeyer** [comment]
We don't assign issues. Feel free to work on it

**Comment by ezhillragesh** [comment]
@bmuenzenmeyer I am currently working on this issue

**Comment by AnkurDG** [comment]
@bmuenzenmeyer  i am also working on this issue

**Comment by ovflowd** [comment]
> The footer is not currently internationalized. @ovflowd is this a design goal? See [nodejs.org/es](https://nodejs.org/es) or [nodejs.org/de](https://nodejs.org/de)

Yes, we want the footer to be internationalized.

**Comment by bmuenzenmeyer** [comment]
@ovflowd okay - then we will have to addess in PR as they come in - but I'll make a big edit to this too

**Comment by areebamirr** [comment]
I am also working on this Issue.

**Comment by fa-901** [comment]
@bmuenzenmeyer @ovflowd I see no one is assigned, so I went ahead and made a PR
