### ISSUE TITLE
Create `LanguageDropDown` component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5981]
Create a `LanguageDropDown` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=695-15031&mode=dev).  

This component is an icon-button that when activated shows a dropdown of all locales. This is the final port of the [LanguageDropDowncomponent recently deleted](https://github.com/nodejs/nodejs.org/pull/5724/files). Much of the functionality is the same to end users, but with different tech.

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.
- ❗ Review the [translation guide](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md), especially how to [add new keys](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md#adding-new-translation-keys).

---

### Details
![image](https://github.com/nodejs/nodejs.org/assets/298435/392477e0-4b8b-44c8-a8c7-6089589a39b9)
![image](https://github.com/nodejs/nodejs.org/assets/298435/bccf6df4-a1c4-4acf-97fd-98eee8db6182)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)
🌐 This story requires some internationalization support. Slow down!

- Create a new directory called `LanguageDropDown` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code.
- [Install `@radix-ui/react-dropdown-menu`](https://www.radix-ui.com/primitives/docs/components/dropdown-menu) for the accessible foundation and functionality we need.
  - Use `DropdownMenu.Trigger` to place the icon and button
  - The `@heroicons/react` module has the icon `language` available for use.
  - source the languages to display and the current value from the ['@/hooks/useLocale' hook](https://github.com/nodejs/nodejs.org/blob/main/hooks/useLocale.ts)
  - implement a no-op for the click handler
- Add a storybook story file `components/Common/LanguageDropDown/index.stories.tsx` which exercises each of the component's states.
- Delete https://github.com/search?q=repo%3Anodejs%2Fnodejs.org%20useClickOutside&type=code after a quick search of the codebase - this was leftover from the previous design
- The `aria-label` must be internationalized, and in English state `Choose Language`. Add a new key `components.common.languageDropdown.label` to the `i18n/locales/en.json` file. `useIntl` from `react-intl` should be used to reference the key. Look for examples elsewhere in the codebase or in the old PR.

There are 2 states to capture within styles and stories:

- Light
- Dark

**Comment by burhanharoon** [comment]
Hi @bmuenzenmeyer, I would love to work on this, can you please assign me this so that I can start the development? Thanks!

**Comment by burhanharoon** [comment]
@bmuenzenmeyer nevermind about assigning, I just got to know you guys don't assign the issues, FYI I'm still working on this.

**Comment by ovflowd** [comment]
Also, for the Storybook, feel free to add mocked language options to the Dropdown, we don't need to get the real Dropdown options (Available Languages) for the Storybook.

**Comment by ovflowd** [comment]
It would also be interesting to add Unit Tests to ensure that onClick behaviour actually renders the Dropdown

**Comment by DhairyaMajmudar** [comment]
@ovflowd I am working on the model but not able to preview what I am building can you pls. help for that

**Comment by ovflowd** [comment]
> @ovflowd I am working on the model but not able to preview what I am building can you pls. help for that

Read the Contribution Guidelines. It's all documented there. I'm not going to provide 1:1 support, sorry. (I don't have time for that)

**Comment by DhairyaMajmudar** [comment]
> > @ovflowd I am working on the model but not able to preview what I am building can you pls. help for that
> 
> Read the Contribution Guidelines. It's all documented there. I'm not going to provide 1:1 support, sorry. (I don't have time for that)

OkayJi 🥺

**Comment by ovflowd** [comment]
> > > @ovflowd I am working on the model but not able to preview what I am building can you pls. help for that
> > 
> > 
> > Read the Contribution Guidelines. It's all documented there. I'm not going to provide 1:1 support, sorry. (I don't have time for that)
> 
> OkayJi 🥺

But is there anything specific that is not working? To preview changes you simply need to run `npm run storybook` then open `http://localhost:6006`

**Comment by Rounak-stha** [comment]
Hey, I was already working on this. As issues are not assigned, I didn't leave any comments.
