### ISSUE TITLE
Website WG members

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs.org#599]
The list [here](https://github.com/nodejs/nodejs.org/blob/master/README.md#website-working-group-members) seems a bit outdated, right? I don't remember the exact WG onboarding process and the differentiation between WG admin, WG member and contributor any more. :confused: 

Also, contributors should point to https://github.com/orgs/nodejs/teams/website.

**Comment by phillipj** [comment]
Absolutely. Lots of collaborators who should be added to that list a long time ago.

I've always thought of collaborators as WG members. Therefore the WG has admins (https://github.com/nodejs/nodejs.org/issues/228) and collaborators.

There hasn't really been an official onboarding process as far as I remember. IMO we don't need one either. Although creating a `COLLABORATOR_GUIDE.md` might be valueable for new comers.

> Also, contributors should point to https://github.com/orgs/nodejs/teams/website.

The team member list are only visible for those inside the nodejs organization AFAIK. Or did I misunderstood what you meant with "point to"?

**Comment by fhemberger** [comment]
@phillipj Ah, thanks for brushing up my memory. ;)

Tried the link above from a different browser and you're right, the list is not visible for people outside the org. :(

**Comment by fhemberger** [comment]
Ok, wrote a little script to get all members of the team, list is here: 96bb9dbdebc371ae3b8ebc95667f85b42cc1315a
