### ISSUE TITLE
Logo colors in AI file are incorrect

### ISSUE THREAD

**Issue by avindra** [nodejs/nodejs.org#600]
They are showing up as tones of blue, purple, etc, instead of green.

[@ChALkeR pointed this out 28 days ago](https://github.com/nodejs/evangelism/issues/179#issuecomment-188994710)

Page:

https://nodejs.org/en/about/resources/

AI File:

https://nodejs.org/static/images/logos/nodejs-new-pantone-black.ai

Additionally, there is no .svg available, only the proprietary adobe format.

**Comment by phillipj** [comment]
@gtewallace seemed to have some insights into the colours and the logo in #526

**Comment by zlatanvasovic** [comment]
Is there still an issue with this? I can view AI normally.

**Comment by fhemberger** [comment]
No further feedback from original poster, closing this issue now.
Please feel free to re-open it, if this issue still exists.
