### ISSUE TITLE
Table is not rendered

### ISSUE THREAD

**Issue by victorsptt** [nodejs/nodejs.org#6002]
### URL:

https://nodejs.org/en/docs/guides/debugging-getting-started#command-line-options

### Browser Name:

Mozilla Firefox

### Browser Version:

118.0.1

### Operating System:

Fedora Linux 37 (Workstation Edition)

### How to reproduce the issue:

1. What I did.

I opened the documentation page at "https://nodejs.org/en/docs/guides/debugging-getting-started#command-line-options".

2. What I expected to get.

The options table properly rendered.

3. What I actually got.

The options table was missing.

**Comment by victorsptt** [comment]
I am working to fix it.

**Comment by victorsptt** [comment]
I tried to convert the tables from HTML to Markdown, but they are not rendered.

Pipe tables are a syntax extension included in GFM, they are not a CommonMark syntax, and `@mdx-js/mdx` only supports CommonMark by default.

HTML tables are not being rendered because the `@mdx-js/mdx` compiler removes the HTML text from files in `md` format.

From [mdx/lib/core.js](https://github.com/mdx-js/mdx/blob/44ca1ff69b78b1c68493dab3b4baf7a4bf7c10b4/packages/mdx/lib/core.js#L134):

```js
if (format === 'md') {
  pipeline.use(rehypeRemoveRaw)
}
```

To save the HTML in `md` files, we need to use the `rehype-raw` plugin.

**Comment by ovflowd** [comment]
> Pipe tables are a syntax extension included in GFM, they are not a CommonMark syntax, and @mdx-js/mdx only supports CommonMark by default.

Interesting, I had no idea it was a part of `gfm`. This sucks because `remark-gfm` 4.0 has a bug with their tables. I guess for now `rehype-raw` is the solution then.

**Comment by ovflowd** [comment]
```
if (format === 'md') {
  pipeline.use(rehypeRemoveRaw)
}
```

I wonder what would happen if we parsed regular Markdown files as MDX? (By changing extension settings on `next.dynamic.mjs`
