### ISSUE TITLE
Create `ThemeToggle` Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6005]
Create a `ThemeToggle` component using the new [figma design (indirect link to NavBar)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=415-8491&mode=dev).  

This component is an icon-button that when activated toggles the current theme (light to dark, or dark to light). This is the final port of the [DarkModeToggle recently deleted](https://github.com/nodejs/nodejs.org/pull/5730). Much of the functionality is the same to end users, but with different tech.

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.
- ❗ Review the [translation guide](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md), especially how to [add new keys](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md#adding-new-translation-keys).

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/c8eb6920-4985-4848-ad25-0ced4c8d6cfc)

> showing the whole navbar . The icon is only this icon button

![image](https://github.com/nodejs/nodejs.org/assets/298435/ca2ef487-3ae7-4f8e-b8b9-6d93fa4ddb61)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)
🌐 This story requires some internationalization support. Slow down!

- Create a new directory called `ThemeToggle` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code.
- [Install `@radix-ui/react-accessible-icon`](https://www.radix-ui.com/primitives/docs/utilities/accessible-icon) for the accessible foundation and functionality we need.
- The `@heroicons/react` module has the icons `moon` and `sun` available for use.
- Add a storybook story file `components/Common/ThemeToggle/index.stories.tsx` which exercises each of the component's states.
- The [`label` prop](https://www.radix-ui.com/primitives/docs/utilities/accessible-icon#root) must be internationalized, and use the [existing key `components.header.buttons.toggleDarkMode`](https://github.com/nodejs/nodejs.org/blob/main/i18n/locales/en.json#L39) in the `i18n/locales/en.json` file. `useIntl` from `react-intl` should be used to reference the key. Look for examples elsewhere in the codebase or in the old PR.
- The component should set its default mode to the user's system setting. Tailwind [offers some guidance](https://tailwindcss.com/docs/dark-mode).

There are 2 states to capture within styles and stories:

- Light Mode, which shows the `moon` icon to toggle to dark mode
- Dark Mode, which shows the `sun` icon to toggle to light mode

**Comment by AugustinMauroy** [comment]
Can I work on this ?

**Comment by arianxq** [comment]
This seems like an interesting task. Can I try to solve this?

**Comment by ovflowd** [comment]
> Can I work on this ?

Do you mind if we let newcomers have a first chance on working on this? As they're eligible for Hacktoberfest? Thanks!

**Comment by ovflowd** [comment]
@bmuenzenmeyer just out of curiosity, any other existing component that we want to add `AccessibleIcon`?

**Comment by bmuenzenmeyer** [comment]
I can see it's utility for every icon-only UI element... So LanguageSelector, ThemeToggle, mobile 'hamburger menu', even the social icons in the footer.

Wish I'd known about it sooner.

**Comment by ovflowd** [comment]
Should we retroactively update then?

**Comment by bmuenzenmeyer** [comment]
i think so - i can create a single story to do so in the future - just wanted a second opinion

**Comment by arianxq** [comment]
Thank you @ovflowd! It looks like @AugustinMauroy has created a pull request, I'll be looking for a new issue to contribute to
