### ISSUE TITLE
Create `MetaBar` Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6008]
Create a `MetaBar` component using the new [figma design (direct link to)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=433-3741&mode=dev).  

This component is a sidebar that will display on most content/markdown pages. It displays metadata about the content

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.
- ❗ Review the [translation guide](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md), especially how to [add new keys](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md#adding-new-translation-keys).

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/6e8753f3-f33b-4d77-8258-c0097fe73a28)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)
🌐 This story requires some internationalization support. Slow down!

- Create a new directory called `MetaBar` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code.
- Use the new `AvatarGroup` component introduced within https://github.com/nodejs/nodejs.org/pull/5916
- The `@heroicons/react` module has the icon `code-bracket` available for use.
- The [static file `social-github.svg`](https://github.com/nodejs/nodejs.org/blob/main/public/static/images/logos/social-github.svg) should be used for the `Edit this page` icon

#### Suggested Props

Only display these values on the `Metabar` if provided

| Name | type | comments | label | 
| - | - | - | - | 
`lastUpdate` | `Date`  | format per Figma | `Last Updated` (internationalized as `components.metabar.lastUpdated`)
`readingTime` | `string` | | `Reading Time`  (internationalized as `components.metabar.readingTime`)
`addedInVersion` | `string` | | `Added In`  (internationalized as `components.metabar.addedIn`) 
`author` | `string` | | `Author`  (internationalized as `components.metabar.author`)
`authors` | `Object[]` | Object array capable of rendering `AvatarGroup` | `Authors`  (internationalized as `components.metabar.authors`) 
`sourceURL` | `string` or typeof `Next Link` | | `Contribute` (internationalized as `components.metabar.contribute`)
`viewAsURL` | `string` or typeof `Next Link` | Render the `code-bracket` link if the `viewAsURL` is provided | `View as`  (internationalized as `components.metabar.viewAs`)
`toc` | `object[]` | Nested list of links that could mimic a markdown heading hierarchy. See below commentary. | `Table of Contents`  (internationalized as `components.metabar.tableOfContents`)

#### Storybook

Add a storybook story file `components/Common/MetaBar/index.stories.tsx` which exercises each of the component's states.

There are 2 states to capture within styles and stories: 

- Light Mode
- Dark Mode

#### Open and Future Questions

the `toc` prop needs to be supplied by static or dynamic analysis of the content it is rendering. I have seen this work a couple ways, but suggest it's out of scope for this simple story and want to omit it. A future layout or provider needs to supply this data. 

For this initial work, let's make a best effort to render a nested hierarchy of headings as an unordered list.

**Comment by bmuenzenmeyer** [comment]
@ovflowd would love an opinion on the `toc` prop - i think it's out of scope for this simple component, but makes for harder work in the future

**Comment by ovflowd** [comment]
> @ovflowd would love an opinion on the `toc` prop - i think it's out of scope for this simple component, but makes for harder work in the future

Shouldn't we start with the ToC component first?

**Comment by ovflowd** [comment]
But to answer your question, afaik the ToC comes directly from `Remark`, there's already a defined data structure, defined here: https://github.com/nodejs/nodejs.org/blob/main/types/dynamic.ts#L8

This is the type of the ToC that is automatically inferred from Markdown files and available here https://github.com/nodejs/nodejs.org/blob/main/theme.tsx#L15

So I assume that's what the `toc` prop should accept? And I think we should call it "headings" instead of `ToC` just for consistency between files.

**Comment by adeyinkaezra123** [comment]
Hello, I'd love to pick this up

**Comment by bmuenzenmeyer** [comment]
Thanks @ovflowd I assumed there would be an elegant way!

**Comment by ovflowd** [comment]
> Thanks @ovflowd I assumed there would be an elegant way!

Define elegant 👀👀

**Comment by bmuenzenmeyer** [comment]
I meant I am happy that you pointed us to an already existent solution

**Comment by bmuenzenmeyer** [comment]
> Shouldn't we start with the ToC component first?

We can break it out into a separate component, sure
