### ISSUE TITLE
Create `Preview` Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6011]
Create a `Preview` component using the [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=695-2355&mode=dev).  

This component that is a themed image with text that re-use in blogs and OpenGraph.

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

---

### Details

![image](https://github.com/bmuenzenmeyer/nodejs.org/assets/298435/10d541c4-486d-46bd-bd0c-de27c2dead83)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Create a new directory called `Preview` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code.
- Use the existing [js-white SVG](https://github.com/nodejs/nodejs.org/blob/main/public/static/images/logos/js-white.svg)
- Add the [Frame, Group 3, Group 1 hexagons from the Figma](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=415-6717&mode=design&t=gghCgmQfCIVIEoO5-4) as a new SVG, not the Ellipse
- Use our tailwind tokens to help style the blurred effect. The Figma suggests the CSS if you need help
  - Announcement: Green/700
  - Release: Info/600
  - Vulnerability: Warning/600

#### Suggested Props

| Name | type | comments |
| - | - | - |
`title` | `string`  | example: `Changing the End-of-Life Date for Node.js 16 to September 11th, 2023` per Figma
`type` | enum `announcement` \| `release` \| `vulnerability` | default is `announcement`

#### Storybook

Add a storybook story file `components/Common/Preview/index.stories.tsx` which exercises each of the API's states.

There are 4 states to capture within styles and stories: 

- Default (Announcement)
- Announcement
- Release
- Vulnerability

**Comment by arianxq** [comment]
Can I work on this one?

**Comment by nikhilnrr** [comment]
Hi @bmuenzenmeyer , could you assign this issue to me? Would be great to start from this :)
