### ISSUE TITLE
Download link labels are shifted in some languages

### ISSUE THREAD

**Issue by oboenikui** [nodejs/nodejs.org#6013]
### Enter your suggestions in details:

Download link labels are shifted at [this commit](https://github.com/nodejs/nodejs.org/commit/8b4f69838aeb3b2dd0a2d87cd239e0c1a413dfa8#diff-aa3f90eea12523db330a01d926a8648195725fdef9e6efe69613ce3451cfaf6a).

For example, Mac binary can download from "Windows Binary" link in Japanese page.

<img width="1020" alt="image" src="https://github.com/nodejs/nodejs.org/assets/3191462/ad1e79eb-2ecf-4cd5-9c96-2e042359d400">

https://nodejs.org/ja/download

Affected languages are ja, ru, uk and zh-tw.

**Comment by ovflowd** [comment]
Oh god. This is a mess. Thanks for reporting!
