### ISSUE TITLE
release-post script is broken

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/nodejs.org#6020]
```
➜  nodejs.org git:(v21-release) ✗ node ./scripts/release-post/index.mjs 21.0.0
Some error occurred here! TypeError: Cannot read properties of null (reading 'length')
    at file:///Users/rafaelgss/repos/os/nodejs.org/scripts/release-post/index.mjs:153:15
    at new Promise (<anonymous>)
    at file:///Users/rafaelgss/repos/os/nodejs.org/scripts/release-post/index.mjs:152:12
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
```

cc: @ovflowd 

For now, I'll checkout a prior commit to make it work.

**Comment by ovflowd** [comment]
@RafaelGSS the actual error is "Some error occurred here! Error: Could not find changelog body of 21.0.0 release"

**Comment by RafaelGSS** [comment]
Yes, I'm looking to it now. Looks like a "Notable Changes" section is desirable.

**Comment by ovflowd** [comment]
Right, it's a "mandatory section" afaik

**Comment by RafaelGSS** [comment]
It shouldn't. As well as the "commit" section. It doesn't fit semver-major commits. Anyway, I have a fix locally to upload the blog post, I'll open a PR soon.

**Comment by ovflowd** [comment]
> It shouldn't. As well as the "commit" section. It doesn't fit semver-major commits. Anyway, I have a fix locally to upload the blog post, I'll open a PR soon.

Are you sure about that? The old commit also required them, no?

**Comment by RafaelGSS** [comment]
Not for semver-major releases.

**Comment by ovflowd** [comment]
> Not for semver-major releases.

Let me double-check the original code. Because I can definitely see a rejection there on the original code.

**Comment by ovflowd** [comment]
Right, I think I see the issue. Pushing a hot-fix. Would you mind waiting a little bit?

**Comment by RafaelGSS** [comment]
https://github.com/nodejs/nodejs.org/pull/6022 I have the blog post ready. No need to rush.

**Comment by ovflowd** [comment]
> #6022 I have the blog post ready. No need to rush.

It's not about rushing, but about validating that the updated script works. Anyhow, I've pushed a hotfix.

**Comment by RafaelGSS** [comment]
Confirmed the hotfix works.
