### ISSUE TITLE
Nominate @canerakdas to the `nodejs-website` Team

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#6026]
Caner has been an active contributor to the Node.js Website Redesign and has been actively active in conversations, reviewing other people's PRs, and upholding excellent standards for developing the Node.js Website.

I always believe in adding new people to the `nodejs-website` team who have the ability to bring value in the long term. Caner has also proven to have a solid knowledge of React, specifically Tailwind, which is excellent.

Their addition to the team will further provide value and further allow the team to reach its goals.

[Pull requests opened throughout the Node.js organization](https://github.com/search?q=author%3Acanerakdas+org%3Anodejs&type=pullrequests)
[Comments on pull requests throughout the Node.js organization](https://github.com/search?q=commenter%3Acanerakdas+org%3Anodejs&type=pullrequests)
[Comments on issues throughout the Node.js organization](https://github.com/search?q=commenter%3Acanerakdas+org%3Anodejs&type=issues)
Comments on pull requests and issues in the [nodejs/nodejs.org](https://github.com/nodejs/nodejs.org/issues?q=commenter%3Acanerakdas+sort%3Aupdated-desc+) repository

cc @canerakdas 
cc @nodejs/web
cc @nodejs/nodejs-website

**Comment by AugustinMauroy** [comment]
+1 
and potentially welcome @canerakdas 🎉💚

**Comment by canerakdas** [comment]
Thank you for the nomination @ovflowd 

It's great to contribute to a project with talented people in their field.  I've learned a lot! Checking and applying standards while contributing is enough to make me happy as a developer.

The opportunity to be a part of the team and help the project and the community even excites me more!

**Comment by ovflowd** [comment]
Enough time has passed! Welcome to the team, @canerakdas! Invitation sent :)
