### ISSUE TITLE
Add the OpenSSF Badge to the new site

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6031]
Placeholder so we don't forget to port this work to the new site design - where it will likely not be in the footer.

---

do we know what content is within the new "Security Reporting" page? if it's just a rename of the current "Security" page, that wont work well - as that's just a link to https://github.com/nodejs/node/security/policy#security

_Originally posted by @bmuenzenmeyer in https://github.com/nodejs/nodejs.org/issues/5432#issuecomment-1770990882_

**Comment by bmuenzenmeyer** [comment]
#6030 added the badge to the existing site

**Comment by ovflowd** [comment]
@bmuenzenmeyer I assume this is ready to be tackled now?

**Comment by bmuenzenmeyer** [comment]
Yes it could be added to the now present page.
