### ISSUE TITLE
Create `Card` Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6033]
Create a `Card` component using the [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=497-10522&mode=dev).  

This component is a card that previews other content, usually a blog post.

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/a0bbf254-5e62-4331-88e5-6df3f4950fd4)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Create a new directory called `Card` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code.
- Use the new `Preview` component introduced within https://github.com/nodejs/nodejs.org/issues/6011
- Use the new `AvatarGroup` component introduced within https://github.com/nodejs/nodejs.org/issues/5910
- Use the new tailwind color and typography system to assign properties. For example, the subheading uses Green/400 per the figma.

#### Suggested Props

| Name | type | comments |
| - | - | - |
`heading` | `string`  | example: `Node.js March 17th Infrastructure Incident Post-mortem` per figma, passes through to `Preview`
`subheading` | `string`  | example: `Vulnerabilities` per figma
`type` | enum `announcement` \| `release` \| `vulnerability` | default is `announcement`, passes through to `Preview` - this enum is already in preview - reuse it
`supportingText` | `string` | excerpt of post content, limited to 3 lines via [line-clamp](https://caniuse.com/css-line-clamp). `Starting on March 15th and going through to March 17th (with much of the issue being mitigated on the 16th), users were receiving intermittent 404 responses when trying to download Node.js from nodejs.org, or even accessing parts of the website.` per figma
`avatars` | typeof `Avatar[]` | use the `alt` value from Avatar as the author's full name, such as `Hayden Bleasel` per figma
`date` | `Date` | formatted as `20 Jan 2024` per figma

#### Storybook

Add a storybook story file `components/Common/Cards/index.stories.tsx` which exercises each of the compnent's states.

There are 2 states to capture within styles and stories: 

- Light
- Dark

**Comment by YashM211** [comment]
Can I get this one.

**Comment by bmuenzenmeyer** [comment]
Thanks for your interest. We don't assign tickets if we can help it. Feel free to submit a pull request if you have time.
Reference 🍪 https://www.redhat.com/en/blog/dont-lick-cookie

**Comment by danielmarcano** [comment]
Hi, @bmuenzenmeyer! Hope you are doing great. I have just created a [PR](https://github.com/nodejs/nodejs.org/pull/6037) with the new `Common/Card` component ✨
