### ISSUE TITLE
Run Prettier as part of the blog post script

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6041]
Now we have to run Prettier on blog posts? Please do it as part of the script that generates them!

_Originally posted by @targos in https://github.com/nodejs/nodejs.org/issues/6040#issuecomment-1777304015_

See https://github.com/nodejs/nodejs.org/blob/main/scripts/release-post/index.mjs - add a exec call to run prettier in some way.

You can validate this works by re-running the 21.1.0 release from which this  issue came

**Comment by ovflowd** [comment]
I feel that this is a mismanagement of expectations: https://github.com/nodejs/nodejs.org/pull/6040#issuecomment-1777446535

As if they simply run `npm install` that would automatically setup their Git Hooks. So I assume they just didn't do that.

@targos have you at least run `npm install` and `npm run serve` to test locally that the blog post was created and rendered as expected?

**Comment by targos** [comment]
I did run `npm install`. Not `npm run serve`. I respectfully ask that we are not expected to do that. The release process is already complicated enough.

**Comment by ovflowd** [comment]
>  Not npm run serve. I respectfully ask that we are not expected to do that.

You're not expected. Just saying that you can run that command to test/view the blog post locally :)

> I did run npm install. 

That's odd, because Husky should be adding a precommit hook to prettify files. @bmuenzenmeyer can you check into that / see if there's a ignore maybe?

**Comment by targos** [comment]
Note that Git Hooks and npm install scripts are disabled globally on my computer for security reasons.

**Comment by targos** [comment]
> You're not expected. Just saying that you can run that command to test/view the blog post locally :)

I think in this case the rendered post wouldn't look different. Prettier only asked to remove unnecessary escapes.

**Comment by ovflowd** [comment]
> > You're not expected. Just saying that you can run that command to test/view the blog post locally :)
> 
> 
> 
> I think in this case the rendered post wouldn't look different. Prettier only asked to remove unnecessary escapes.

Youre absolutely right. Sorry my prettier comment was not related to running locally to preview the post.

Just wanted to say that previewing a new blog post to verify it looks as expected is nice. But I suppose Vercel branch deployments already do that for you, so disregard that!

**Comment by ovflowd** [comment]
> 
Note that Git Hooks and npm install scripts are disabled globally on my computer for security reasons.

Oh, that makes sense. Right, then @bmuenzenmeyer might make sense to invoke prettier/eslint CLI directly from the blog script. And then write the resulting content to the file.

**Comment by targos** [comment]
I'm also fine with a documentation update in https://github.com/nodejs/node/blob/main/doc/contributing/releases.md#17-create-a-blog-post that asks to run whatever is needed.
