### ISSUE TITLE
Not found error (404) on main page

### ISSUE THREAD

**Issue by krassx** [nodejs/nodejs.org#6053]
### URL:

https://nodejs.org/ru

### Browser Name:

Chrome

### Browser Version:

118.0.5993.117

### Operating System:

macOS 14.0 (23A344)

### How to reproduce the issue:

1. Navigate to https://nodejs.org
2. I am automatically redirected to https://nodejs.org/ru
3. 404 error is returned (screenshot is attached below)

<img width="813" alt="Screenshot 2023-10-27 at 10 50 07" src="https://github.com/nodejs/nodejs.org/assets/8613766/d678b940-247e-4bea-947c-fbcfc8592596">

**Comment by ovflowd** [comment]
Fixed on https://github.com/nodejs/nodejs.org/commit/00726f9a30b224560ecacae84dc03cc263d2c64a, if you open https//nodejs.org now, it should go to a supported language.

**Comment by ovflowd** [comment]
FYI note that we disabled translations for now: https://github.com/nodejs/nodejs.org/issues/6036

**Comment by krassx** [comment]
Great! Thank you.
