### ISSUE TITLE
the nodejs.org/en/learn page is not found

### ISSUE THREAD

**Issue by laariane** [nodejs/nodejs.org#6056]
### Affected URL(s)

https://nodejs.org/en/learn

### Description of the problem

404 error of the learn page in nodeJs docs platform .
![image](https://github.com/nodejs/node/assets/48860436/eff1852c-2e11-4690-95ef-95ac2e48f1fa)

**Comment by ovflowd** [comment]
There's no such page. We deactivated the https://nodejs.dev website, which is probably from (and contains such pages) where you came from, as it was deprecated and old.

We are going at a point of time to add the learn pages back to the leading site as part of the website redesign initiative.

SEO might take a few days to update that these links do not exist anymore.

**Comment by ovflowd** [comment]
Closing as there's no actionable ATM.

**Comment by AndrewLamYW** [comment]
The link is from https://nodejs.org/en/docs/guides#nodejs-core-concepts > Introduction to Node.js

In the meantime, do you have any recommended alternatives?

![image](https://github.com/nodejs/nodejs.org/assets/11419166/218d0548-bd32-45b4-b25f-174f4f73fd80)

**Comment by ovflowd** [comment]
> The link is from [nodejs.org/en/docs/guides#nodejs-core-concepts](https://nodejs.org/en/docs/guides#nodejs-core-concepts) > Introduction to Node.js

Right removing that link.

> In the meantime, do you have any recommended alternatives?

There's a lot of learning material out there. We'll try our best to add these as soon as possible to the current website. Apologies.
