### ISSUE TITLE
"stability" banner is visually a far more prominent heading than the actual headings.

### ISSUE THREAD

**Issue by Pomax** [nodejs/nodejs.org#6059]
### URL:

https://nodejs.org/api/cli.html#--experimental-detect-module

### Browser Name:

n/a

### Browser Version:

n/a

### Operating System:

n/a

### How to reproduce the issue:

The way stability banners are currently styled, using a full width coloured background, means that rather than seeing content where each heading is a section heading, the docs become segmented on stability banners. https://nodejs.org/api/cli.html#--experimental-detect-module is a perfect example of this, where visitors will not see content that is segmented based on each `--experimental-flag-name`, but instead see a document that is divided up into sections that start with a stability banner instead.

There are a number of ways to address that, from making the banner less wide and giving each real heading a full width underline to coloring the heading instead of the banner and giving the stability banner a black border outline with a coloured icon instead, but as is the "footnote to the content" is taking over as the heading, which probably needs addressing.

**Comment by ovflowd** [comment]
Hey @Pomax, I recommend you keep an eye on the README of this repository. We're currently redesigning the Node.js Website and, in the future, the API Docs.

I agree that the current designs are awful and that's going to be addressed by current work. Now I don't think this is a bug and there's nothing we're going to do now in the sort term as we're eventually going to abandon the current API Docs design.

The screenshot below showcases for example how the API Docs would look like in the future.

![image](https://github.com/nodejs/nodejs.org/assets/12037269/064dd171-06b1-43bc-879a-d5eb37e615a4)

I'm closing this issue as there's no planned action for now. Thank you anyways for sharing your opinions :)

**Comment by Pomax** [comment]
Looking pretty tidy! I look forward to the switchover =)

**Comment by ovflowd** [comment]
> Looking pretty tidy! I look forward to the switchover =)

Ty! If you have any other feedback, and even on the new designs, please feel free to provide feedback 🙇
