### ISSUE TITLE
Create `Navbar` Component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6060]
Create a `Navbar` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=415-8491&mode=dev). 

This component starts the responsive header for the new site.

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/35dde007-2a93-41e5-9dac-9fc953b81eaf)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)
🌐 This story requires some internationalization support. Slow down!

- Create a new directory called `Navbar` within the [`sections` directory](https://github.com/nodejs/nodejs.org/tree/main/components/sections) that contains all the new code.
- Omit search fpr now, that is the scope of another story not yet started.
- Use the new `NavItem` component introduced within https://github.com/nodejs/nodejs.org/pull/5972
- Use the new `ThemeToggle` component introduced within https://github.com/nodejs/nodejs.org/pull/6007
- Use the new `LanguageDropdown` component introduced within https://github.com/nodejs/nodejs.org/pull/5982
- Use the new [social-github.svg](https://github.com/nodejs/nodejs.org/blob/main/public/static/images/logos/social-github.svg) along with [AccessibleIcon](https://www.radix-ui.com/primitives/docs/utilities/accessible-icon) to link to https://github.com/nodejs/node
- The figma puts the mobile breakpoint at 375px. Explore if we can use that directly or an [new/existing tailwind token (if any)](https://github.com/nodejs/nodejs.org/blob/main/tailwind.config.ts)
- The links must be internationalized. 
   - Add the following new keys to the `i18n/locales/en.json` file. 
      - `components.headers.links.learn` 
   - Use the existing `components.headers.links.[about,docs,download,blog,certification] keys 
- FormattedMessage from react-intl should be used to reference the keys. Look for examples elsewhere in the codebase.

### Storybook

Add a storybook story file `components/sections/Navbar/index.stories.tsx` which exercises each of the component's states.

There are 4 Navbar states to capture within styles and stories:

- Light
- Light, mobile
- Dark
- Dark, mobile

Light and dark modes toggle between https://github.com/nodejs/nodejs.org/blob/main/public/static/images/logos/horizontal-light.svg and https://github.com/nodejs/nodejs.org/blob/main/public/static/images/logos/horizontal-dark.svg. I imagine there is a way to do this with just a fill, but I didn't confirm.

### Open Questions

- Should the links be defined within `site.json`? Today many are in `navigation.json` but that's for the live site.

**Comment by Shubhangam333** [comment]
Hi @bmuenzenmeyer,

I would like to work on this Issue. Please assign it to me.

Thanks,
Shubhangam

**Comment by bmuenzenmeyer** [comment]
Thanks for your interest. We don't assign tickets if we can help it. Feel free to submit a pull request if you have time.
Reference 🍪 https://www.redhat.com/en/blog/dont-lick-cookie

**Comment by bmuenzenmeyer** [comment]
Looks like we will be using `navigation.json` per https://github.com/nodejs/nodejs.org/pull/6064

**Comment by mirza-mohibul-hasan** [comment]
Is that work done?

**Comment by 08Uzair** [comment]
Please assign this to me i will do this work in  1-2 hrs

**Comment by Rounak-stha** [comment]
> There are 4 Footer states to capture within styles and stories:

Hey, I think you have a typo here. You probably meant to write `Navbar` right?

**Comment by bmuenzenmeyer** [comment]
> Hey, I think you have a typo here. You probably meant to write `Navbar` right?

yes

**Comment by Rounak-stha** [comment]
> Looks like we will be using `navigation.json` per #6064

The json file has a field `getInvolved` which is used in the current site but is not in the new design file.

**Comment by NIKHIL-bot27** [comment]
is this issue still open . Can you please assign me this issue

**Comment by ovflowd** [comment]
This issue already has an open PR which is already in review...
