### ISSUE TITLE
Create `Sidebar` Component family

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6061]
Create a `SidebarItem`, `SidebarGroup`, and `Sidebar` components using the new [figma design (direct link to)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=695-15268&mode=dev).  

This feature acts as a section subnavigation for new areas of the site.

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/794fae91-5d6d-4c99-84f3-eb2236312d3d)
![image](https://github.com/nodejs/nodejs.org/assets/298435/f5c32e92-f035-4706-9fb0-dd368dca7a57) 
![image](https://github.com/nodejs/nodejs.org/assets/298435/450615fb-63d3-411b-9252-4a819ab6fe32)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Create a new directory called `Sidebar ` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code.
- Compose the `Sidebar` from `SidebarGroups` and `SidebarItem` components
- Support a prop to indicate a `SidebarItem` is `active`. Use the tailwind tokens available to style
- Omit the `Node.js version`  `Select` for now. That will the scope of future work.

#### Suggested Props

Accept a an array of `items` to render.

Sample Javascript 
```js
[
  {
     groupName: "Getting Started",
     items: [
        {
          url: "",
          title: ""
        },
        ...
     ]
  },
  ...
]
```

where `url` is `string` or typeof `Next Link` and `title` is string or 

#### Storybook

Add a storybook story file `components/Common/Sidebar/index.stories.tsx` which exercises each of the component's states.

There are 8 states to capture within styles and stories: 

- SidebarItem, Light
- SidebarItem, Light, Active
- SidebarItem, Dark
- SidebarItem, Dark, Active
- SidebarGroup, Light
- SidebarGroup, Dark
- Sidebar, Light
- Sidebar, Dark

**Comment by manikantamavireddy** [comment]
@bmuenzenmeyer to determine active item can we compare current item url with asPath prop of [useRouter](https://nextjs.org/docs/pages/api-reference/functions/use-router)

or do we need to set state on click of sidebarItem to store groupName and item title

**Comment by bmuenzenmeyer** [comment]
i understand we can use that but our components should be as simple as possible, so the caller would determine and pass that in as a prop. Thats how we've done others.
