### ISSUE TITLE
Create `ProgressionSidebar` Component family

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6062]
Create a `ProgressionSidebarItem`, `ProgressionSidebarGroup`, and `ProgressionSidebar` components using the new [figma design (direct link to)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=433-3032&mode=dev).  

This feature acts as a section subnavigation for new areas of the site.

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/298435/e7da8017-65da-4b57-93fb-61fae8fe0523)

![image](https://github.com/nodejs/nodejs.org/assets/298435/51a38cdb-afae-4445-831f-1b710dcdc60b)
 

![image](https://github.com/nodejs/nodejs.org/assets/298435/2daaad5c-3554-433e-92d4-c79832323516)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Create a new directory called `ProgressionSidebar` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code.
- Compose the `ProgressionSidebar` from `ProgressionSidebarGroups` and `ProgressionSidebarItem` components
- Support a prop to indicate a `ProgressionSidebarItem` is active.
- Omit the read indicators for now. That is the scope of a future issue.

#### Suggested Props

Accept a an array of `items` to render.

Sample Javascript 
```js
[
  {
     groupName: "Getting Started",
     items: [
        {
          url: "",
          title: ""
        },
        ...
     ]
  },
  ...
]
```

where `url` is `string` or typeof `Next Link` and `title` is string or 

#### Storybook

Add a storybook story file `components/Common/Sidebar/index.stories.tsx` which exercises each of the component's states.

There are 8 states to capture within styles and stories: 

- ProgressionSidebarItem, Light
- ProgressionSidebarItem, Light, Active
- ProgressionSidebarItem, Dark
- ProgressionSidebarItem, Dark, Active
- ProgressionSidebarGroup, Light
- ProgressionSidebarGroup, Dark
- ProgressionSidebar, Light
- ProgressionSidebar, Dark

**Comment by adilJamshad** [comment]
Can you assign this task to me?
I want to work on this.

**Comment by bmuenzenmeyer** [comment]
Thanks for your interest. We don't assign tickets if we can help it. Feel free to submit a pull request if you have time.
Reference 🍪 https://www.redhat.com/en/blog/dont-lick-cookie

**Comment by Manish4044** [comment]
Hey @bmuenzenmeyer, just wanted to know can we add dependencies that are not currently used? I wanted to use material-ui for this.

**Comment by bmuenzenmeyer** [comment]
We do not use material-ui.

Please read the issue and learn more about our design goals.

**Comment by Manish4044** [comment]
@bmuenzenmeyer I have prepared the component for this ProgressionSidebar. I am just stuck at implementation of active groupItem( changing itemIcon to green color). Just wanted some ideas on identifying the active item using props. Can you provide some approach?

**Comment by NIKHIL-bot27** [comment]
Can you assign this task to me?
I want to work on this.
