### ISSUE TITLE
Hover effect in OpenSSF Best Practices badge

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/nodejs.org#6063]
### URL:

https://nodejs.org/en/about/security-reporting

### Browser Name:

Chrome

### Browser Version:

116.0.5845.187 (Official Build) (x86_64)

### Operating System:

Macos 13.4.1 (22F82)

### How to reproduce the issue:

Here is a gif that shows the hover effect as the link includes an image

![hover_bug](https://github.com/nodejs/nodejs.org/assets/5110813/e4edda68-7483-4747-af24-ba109ff9d8f4)

I think is not expected the background affect

**Comment by bmuenzenmeyer** [comment]
i had this fixed within my PR but must have removed the style declaration during final testing - should be resolved now
