### ISSUE TITLE
High CPU usage when browsing API documentation

### ISSUE THREAD

**Issue by yafietdanialecode** [nodejs/nodejs.org#6066]
### URL:

https://nodejs.org/dist/latest-v20.x/docs/api/

### Browser Name:

Every browser showed this

### Browser Version:

firefox 119.0 (64-bit) , edge (Version 118.0.2088.69 (Official build) (64-bit))

### Operating System:

windows 10

### How to reproduce the issue:

# Hard/Unwanted/Unlimited loop function is making the site to stop on some amount of time interval
- there is some kind of loop function going on the /docs website that prevents clients from scrolling and clicking and takes over CPU usage.
- I checked if it was a browser problem but this issue occurred on browsers like ( firefox, Firefox Developers, chrome, edge, and Brave)
- please check the client-side code if there is some kind of hard loop function for the browser.

**Comment by bmuenzenmeyer** [comment]
i will start investigating by opening the page and trying to recreate

**Comment by mikeesto** [comment]
Thanks for the report. I wasn't able to reproduce this with Chrome but perhaps others will be able to. I kept the page open for a while and then profiled it, which all seemed normal - 

```
6 ms  Scripting
29 ms  System
10347 ms  Idle
10383 ms  Total
```

Are you sure you linked to the correct page? And do you have any screenshots of the high CPU usage (whether through the task manager, browser dev tools or otherwise)? Thanks

**Comment by bmuenzenmeyer** [comment]
also cannot recreate

**Comment by ovflowd** [comment]
This is the source JS for API Docs: https://github.com/nodejs/node/blob/main/doc/api_assets/api.js I don't see anything obvious there that would create high CPU usage

**Comment by bmuenzenmeyer** [comment]
I am going to close this as not reproducable - @yafietdanialecode if you can find reliably replicate this on multiple devices please let us know. On my Windows machine everything seems fine, and we have not had any other reports.
