### ISSUE TITLE
Lighthouse report sometimes failing in CI

### ISSUE THREAD

**Issue by mikeesto** [nodejs/nodejs.org#6068]
### How to reproduce the issue:

See, for example: https://github.com/nodejs/nodejs.org/actions/runs/6684891162/job/18162610188?pr=6067

```
 /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/fix-broken-link-to-page*:refs/remotes/origin/fix-broken-link-to-page* +refs/tags/fix-broken-link-to-page*:refs/tags/fix-broken-link-to-page*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 16 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/fix-broken-link-to-page*:refs/remotes/origin/fix-broken-link-to-page* +refs/tags/fix-broken-link-to-page*:refs/tags/fix-broken-link-to-page*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 13 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/fix-broken-link-to-page*:refs/remotes/origin/fix-broken-link-to-page* +refs/tags/fix-broken-link-to-page*:refs/tags/fix-broken-link-to-page*
  Error: The process '/usr/bin/git' failed with exit code 1
  ```

**Comment by bmuenzenmeyer** [comment]
testing a theory to make this more stable - but i'll admit i dont exactly know what causes it to fail yet

**Comment by mikeesto** [comment]
This is another very recent example of it failing: https://github.com/nodejs/nodejs.org/actions/runs/6713687116/job/18245658050?pr=6072

It seems to only happen when a PR is from a fork which makes me think that something is amiss here: https://github.com/nodejs/nodejs.org/blob/ed0ddfaa4219e700af04cb35af580702b6eba4a7/.github/workflows/lighthouse.yml#L40-L50

Perhaps we could add some debugging temporarily to work out what's going on. The error message that we currently get is not helpful. Something like this:

```
- name: Print Repository and Ref Details
  run: |
    echo "Repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}"
    echo "Ref: ${{ github.event.pull_request.head.ref || github.ref }}"
```

**Comment by bmuenzenmeyer** [comment]
the thing i want to test is whether the second checkout is even necessary. i suspect it was copy-pasta from a source

**Comment by ovflowd** [comment]
> the thing i want to test is whether the second checkout is even necessary. i suspect it was copy-pasta from a source

Right the `repository` field is actually exactly what allows us to checkout their fork, if this was an issue, I don't see how the other CI checks that use the same command would be failing...

**Comment by ovflowd** [comment]
It looks like it's setting the wrong repository.

![image](https://github.com/nodejs/nodejs.org/assets/12037269/25b0b381-778b-415b-b610-a050e4f75bb8)
