### ISSUE TITLE
Node website issue

### ISSUE THREAD

**Issue by TheMagicHands** [nodejs/nodejs.org#6070]
### Details

I was looking at page https://nodejs.org/en/download/package-manager as I am getting ready to install node on a new pi. If you go take a look the flex box is going in a row and is making it look weird, hard to read, etc. Good news is it should be an easy fix. I had success going into the inspector and adding ` flex-direction: column` to the #main .container, .row{} selector.

### Node.js version

Not applicable.

### Operating system

Windows 11

### Scope

Node.js Website

### Module and version

Not applicable.

**Comment by canerakdas** [comment]
Thank you for the reporting! fixed with [be07bf8](https://github.com/nodejs/nodejs.org/pull/6069/commits/be07bf8ef67e0b389ce9b3efff38d3b2b40f64c2)
