### ISSUE TITLE
Lighthouse workflows are failing at startup

### ISSUE THREAD

**Issue by mikeesto** [nodejs/nodejs.org#6094]
### How to reproduce the issue:

See, for example: https://github.com/nodejs/nodejs.org/actions/runs/6741728133
Or https://github.com/nodejs/nodejs.org/actions/workflows/lighthouse.yml for a list of recent failures

I think either the hash needs to be updated in the workflow, or in our settings page.

```
thollander/actions-comment-pull-request@1d3973dc4b8e1399c0620d3f2b1aa5e795465308 is not allowed to be used in nodejs/nodejs.org. 
Actions in this workflow must be: within a repository owned by nodejs, created by GitHub, verified in the GitHub Marketplace, or matching the following
```

**Comment by bmuenzenmeyer** [comment]
updated the settings - lets keep this open until we get a green one

**Comment by ovflowd** [comment]
Same was happening for Crowdin Checks. Also updated.

**Comment by mikeesto** [comment]
All seems OK now - https://github.com/nodejs/nodejs.org/actions/workflows/lighthouse.yml . Thanks
