### ISSUE TITLE
Mozilla Firefox 45.0.1 home page bug

### ISSUE THREAD

**Issue by piermarcobarbe** [nodejs/nodejs.org#610]
<img width="1440" alt="screen shot 2016-03-28 at 16 09 00" src="https://cloud.githubusercontent.com/assets/9352238/14079633/82734386-f4ff-11e5-9698-fb4efae6fd8f.png">
<img width="1440" alt="screen shot 2016-03-28 at 16 08 56" src="https://cloud.githubusercontent.com/assets/9352238/14079635/85ab3f18-f4ff-11e5-9879-9aa2826b80d7.png">
I think there are come problems with the width for Firefox..

**Comment by fhemberger** [comment]
While trying to check this, my Firefox went straight from 45.0 to 46.0b5. This behavior doesn't occur on this version on OS X at least. Can someone please verify different versions/OSes?

**Comment by hiroppy** [comment]
My firefox(47.0a2)
<img width="1440" alt="2016-03-28 23 16 03" src="https://cloud.githubusercontent.com/assets/3367801/14079799/5c80b10e-f53b-11e5-976a-50ac9fca04de.png">

2320 x 700
<img width="1440" alt="2016-03-28 23 18 47" src="https://cloud.githubusercontent.com/assets/3367801/14079816/86d25ac0-f53b-11e5-8913-f1c75828aa28.png">

I think I'll be OK though.
I checked Mac and Linux mint.

**Comment by piermarcobarbe** [comment]
Same bug on Ubuntu 14.04 LTS - Firefox 45.0
Same bug on Windows 10 - Internet Explorer 11.162.10586.0
Same bug on Windows 10 - Firefox 45.0

**Comment by fhemberger** [comment]
Looks okay for me on Chrome 49, 51 (Canary) and Safari 9.1 on OS X, tested on 2560 x 1440 and below.

**Comment by diagramatics** [comment]
Managed to replicate the bug in Firefox 44.0.2 and OS X. Investigating this.

<img width="1440" alt="screen shot 2016-03-28 at 11 38 09 pm" src="https://cloud.githubusercontent.com/assets/5153378/14083125/313145a6-f53e-11e5-858b-0b2a657b82d0.png">

**Comment by diagramatics** [comment]
Found it. It's a flexbox issue documented in Philip Walton's flexbugs [here](https://github.com/philipwalton/flexbugs#1-minimum-content-sizing-of-flex-items-not-honored). Firefox got omitted from the list of browsers with the issue in philipwalton/flexbugs#103.

Set up a PR in #611.

**Comment by MylesBorins** [comment]
This is fixed! thanks @diagramatics
