### ISSUE TITLE
Error loading '@sentry/profiling-node' native module on Windows

### ISSUE THREAD

**Issue by ezhillragesh** [nodejs/nodejs.org#6124]
### URL:

https://nodejs.org/en

### Browser Name:

Firefox Developer Edition

### Browser Version:

Version 120.0b9 (64 bit)

### Operating System:

Windows 10 22H2, 19045.3570

### What I Did:

Installed Node.js on a Windows machine.
Set up a Node.js application using the '@sentry/profiling-node' package.
Ran the application using the specified commands or steps.
What I Expected to Happen:

The application should run without encountering any errors related to the '@sentry/profiling-node' package.
All dependencies, including the native module 'sentry_cpu_profiler-win32-x64-120.node', should be loaded successfully.

### What I Actually Got:

The application failed to load the 'sentry_cpu_profiler-win32-x64-120.node' module.
An error message was displayed indicating a problem with module resolution, specifically pointing to the file 'D:\Opensorce\nodejs.org\node_modules@sentry\profiling-node\lib\sentry_cpu_profiler-win32-x64-120.node'.

**Comment by ovflowd** [comment]
I'm not understanding your bug report. Is this a bug report about not being able to run the Node.js Website locally... or?

I am able to run and build this on my local Windows computer without any issues. @bmuenzenmeyer are you able to reproduce this?

I don't think this is a bug on the Website, you should probably open a bug report on `@sentry/profiling-node` repository with stack trace and details.

**Comment by bmuenzenmeyer** [comment]
I cannot recreate this.

Did you make sure you cleanly ran `npm ci` first?

I am seeing this locally on the tip of `main`, however

![image](https://github.com/nodejs/nodejs.org/assets/298435/47ddc0ec-f52f-4eb6-b287-5219f9fac062)

**Comment by ovflowd** [comment]
> I cannot recreate this.
> 
> Did you make sure you cleanly ran `npm ci` first?
> 
> I am seeing this locally on the tip of `main`, however
> 
> ![image](https://user-images.githubusercontent.com/298435/283486441-47ddc0ec-f52f-4eb6-b287-5219f9fac062.png)

Unrelated the warning. It's just a sad reality from `next-themes`, also this warning is a dev-only warning.

**Comment by ezhillragesh** [comment]
> I cannot recreate this.
> 
> Did you make sure you cleanly ran `npm ci` first?
> 
> I am seeing this locally on the tip of `main`, however
> 
> ![image](https://github.com/nodejs/nodejs.org/assets/298435/47ddc0ec-f52f-4eb6-b287-5219f9fac062)
> 

Yup I ran npm ci and then tried this but I am getting this issue.

**Comment by bmuenzenmeyer** [comment]
okay then can we close this? 

`The application failed to load the 'sentry_cpu_profiler-win32-x64-120.node' module.` is no longer occurring, and the above warning is a dev-only quirk

**Comment by ovflowd** [comment]
> okay then can we close this?
> 
> `The application failed to load the 'sentry_cpu_profiler-win32-x64-120.node' module.` is no longer occurring, and the above warning is a dev-only quirk

I have the feeling that they meant they're getting the error from above, not the warning your screenshoted.

**Comment by bmuenzenmeyer** [comment]
feel free to ask to/reopen if still experiencing the original issue, we can try to debug further
