### ISSUE TITLE
Create `ChangelogModal` Component

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#6125]
Create a `ChangelogModal` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?node-id=719%3A13818&mode=dev). 

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.
- ❗ Review the [translation guide](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md), especially how to [add new keys](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md#adding-new-translation-keys).

---

### Details

![image](https://github.com/nodejs/nodejs.org/assets/12037269/14ea0664-8ad5-4222-a2cb-df99c3a827dd)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)
🌐 This story requires some internationalization support. Slow down!

- Create a new directory called `ChangelogModal` within the [`Downloads` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Downloads) that contains all the new code.
- [Install `@radix-ui/react-dialog`](https://www.radix-ui.com/primitives/docs/components/dialog) as the base component for Modals.
- The trigger should be a prop as a react node that renders within the Modal Component:
    ```tsx
     <Dialog.Trigger asChild>
       {trigger}
     </Dialog.Trigger>
    ```
- If possible component should use no states, and should be a RSC (React Server Component)

#### Suggested Props

| Name | type | comments |
|---|---|---|
| `heading` | `string` | example: `Node v18.17.0` per figma |
| `subheading` | `string` | example: `2023-07-18, Version 18.17.0 'Hydrogen' (LTS), @danielleadams` per figma |
| `avatars` | typeof `Avatar[]` | use the `alt` value from Avatar as the author's full name, such as `Hayden Bleasel` per figma |
| `trigger` | typeof `React.ReactNode` | A React Node/Element (i.e. a button) that acts as a trigger |
| `children` | React Children | The content of the Modal to render (aka the Changelog), per figma |

#### Storybook

Add a storybook story file `components/Downloads/ChangelogModal/index.stories.tsx`, which exercises each of the component's states.

There are 2 states to capture within styles and stories: 

- Light
- Dark

**Comment by TheFossilDev** [comment]
I would love to adopt this as my first issue and contribute this feature. If you assign it to me I'll get right on it! 👨🏼‍🎤  *I should say I'm already working on it

**Comment by AugustinMauroy** [comment]
Thanks for your interest. We don't assign tickets if we can help it. Feel free to submit a pull request if you have time.
Reference 🍪 https://www.redhat.com/en/blog/dont-lick-cookie

**Comment by TheFossilDev** [comment]
> Thanks for your interest. We don't assign tickets if we can help it. Feel free to submit a pull request if you have time. Reference 🍪 https://www.redhat.com/en/blog/dont-lick-cookie

_That was a great read, thanks! A great mindset adjustment for sure._  

Also a couple of clarification questions while I'm getting started:

1. Since we'll be nesting the content of the changelog as children, do we need to worry about styling those Nodes within ChangelogModal?
2. Within the download pages of the new nodejs.org, would this changelog be what is presented upon clicking _"read the release notes for this version" etc_?

Thanks again, I'm getting the ball rolling locally now.

**Comment by ovflowd** [comment]
> Since we'll be nesting the content of the changelog as children, do we need to worry about styling those Nodes within ChangelogModal?

Nope, we don't. They should already have all regular Markdown-applied styles. (To clarify the content there will be something that MDX will parse on-the-fly)

> Within the download pages of the new nodejs.org, would this changelog be what is presented upon clicking "read the release notes for this version" etc?

Good question. At the moment not 100% sure what button will trigger hit, hence the Modal right now should be just the container. You don't need to care about the trigger for now, but you can make the trigger be the a prop. Let me update the props on the table

**Comment by ovflowd** [comment]
Just updated the issue description!

**Comment by TheFossilDev** [comment]
Alright thanks @ovflowd that's a big help. Some follow-ups:

- Which component is the "Start contributing >" link inside the Figma? Struggled to find it within the app components or Design System section.
- Getting an ESLint issue regarding the use of an AvatarGroup tag. When I import Avatar as an object it complains that I can import it as a type since I'm only using it for its type, but then when I change it to `import type { Avatar } from '@...'`, I get an error saying that AvatarGroup doesn't export that type. Snippet for context:

```javascript
import { Avatar } from '@/components/Common/AvatarGroup/Avatar';
type ChangelogModalProps = {
  heading: string;
  subheading: string;
  avatars: ComponentProps<typeof Avatar>[];
  trigger: ReactNode;
  children: ReactNode;
};
...
          <div>
            <AvatarGroup avatars={avatars} />
            {/* TODO: Add "Start Contributing" */}
          </div>
...

```

**Comment by AugustinMauroy** [comment]
@TheFossilDev open a pr so we can review and help you if necessary. It seems more appropriate to me

**Comment by ovflowd** [comment]
> Which component is the "Start contributing >" link inside the Figma? Struggled to find it within the app components or Design System section.

That is just a regular link. You can use our Link component and simply link it to the https://nodejs.org/en/get-involved page (the link should just point to /get-involved)

> Getting an ESLint issue regarding the use of an AvatarGroup tag. When I import Avatar as an object it complains that I can import it as a type since I'm only using it for its type, but then when I change it to import type { Avatar } from '@...', I get an error saying that AvatarGroup doesn't export that type. Snippet for context:

Well first, Avatar is a default export. There's no such `import { Avatar }` just `import Avatar`

Also you don't want to import the type of Avatar, You should probably do:

```tsx
type ChangelogModalProps = {
  heading: string;
  subheading: string;
  avatars: ComponentProps<typeof AvatarGroup>['avatars'];
  trigger: ReactNode;
  children: ReactNode;
};
```

**Comment by ovflowd** [comment]
Keep also in mind that if you get ESLint warning about "imports" you can simply use VSCode to auto fix them, this is mostly because we prefer `import type { Types }` when importing types (we separate regular imports from type imports)

**Comment by TheFossilDev** [comment]
> Also you don't want to import the type of Avatar, You should probably do:

Right on, got that resolved thanks. I'll keep chugging along and PR when I've got something more substantive. Thanks to you both!

**Comment by ovflowd** [comment]
> > Also you don't want to import the type of Avatar, You should probably do:
> 
> Right on, got that resolved thanks. I'll keep chugging along and PR when I've got something more substantive. Thanks to you both!

I'd indeed recommend starting with a Draft PR and pour your questions there (when you have something more substantive), it also helps us to illustrate and understand your progress.

Anyhow, we're here to help ;)
