### ISSUE TITLE
Create `Search` Component, add to `Navbar`

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6131]
Create a `Search` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=464-6397&mode=dev). 

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

This component does not do anything quite yet, but future Orama Search stories will expand upon it.

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.
- ❗ Review the [translation guide](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md), especially how to [add new keys](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md#adding-new-translation-keys).

---

### Details

standalone

![image](https://github.com/nodejs/nodejs.org/assets/298435/01b34a25-abae-4540-ba20-b51af1d67855)
![image](https://github.com/nodejs/nodejs.org/assets/298435/dfd9e98e-fccc-4158-8e68-25ed09ab855d)

integrated into `Navbar`

![image](https://github.com/nodejs/nodejs.org/assets/298435/f0b85827-3878-4e45-b96f-b3506e867305)
![image](https://github.com/nodejs/nodejs.org/assets/298435/8978bbf1-5848-4d98-80d5-8a7f9940a2de)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)
🌐 This story requires some internationalization support. Slow down!

- Create a new directory called `Search` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code.
- Use the hero icon `magnifying-glass` from https://heroicons.com/, already a dependency
- Add the component to `Navbar` per the figma
- Within https://github.com/nodejs/nodejs.org/blob/main/i18n/locales/en.json, add a new key `components.header.search.empty`  with the value `Start typing...`
- Within https://github.com/nodejs/nodejs.org/blob/main/i18n/locales/en.json, add a new key `components.header.search.noResults`  with the value `No results found`
- Within https://github.com/nodejs/nodejs.org/blob/main/i18n/locales/en.json, add a new key `components.header.search.noResultsSuggestion`  with the value `Perhaps try another query?`

#### Suggested Props

| Name | type | comments |
|---|---|---|
| `onChange` | `function` | `() => {}` no-op for now |

#### Storybook

Add a storybook story file `components/Common/Search/index.stories.tsx`, which exercises each of the component's states.

There are 2 states to capture within styles and stories: 

- Light
- Dark

**Comment by TheFossilDev** [comment]
This would be my second issue since I'm also working on the changelogModal but is it alright if I get going on this too? Of course others are welcome ✌🏼

**Comment by AugustinMauroy** [comment]
gives someone else a chance to contribute but thank you for your interest in the project.  😄

**Comment by Ragnarrlothbrok** [comment]
Hi, I would like to work on this.

**Comment by bmuenzenmeyer** [comment]
Thanks for your interest. We don't assign tickets if we can help it. Feel free to submit a pull request if you have time.
Reference 🍪 https://www.redhat.com/en/blog/dont-lick-cookie

**Comment by ovflowd** [comment]
Hey there, sadly, this issue is already locked-in and not available for grabs.

(This is specific to this issue) as we have a partner (3rd party company) being involved on the development of the search functionality of the Website. (cc @micheleriva)
