### ISSUE TITLE
dist/index.json broken

### ISSUE THREAD

**Issue by echalone** [nodejs/nodejs.org#6136]
### URL:

https://nodejs.org/dist/index.json

### Browser Name:

Chrome

### Browser Version:

119.0.6045.160

### Operating System:

Windows

### How to reproduce the issue:

The https://nodejs.org/dist/index.json is suddenly broken and no longer a valid json. It seems to break after 256kb and now ends with 
```
{"version":"v0.1.20","date":"2011-08-26","files":["src"],"v8":"2.0.2.0","lts":false,"security":false},
{"version":"v0.1.19","date":"2011-08-26","files":["src"],"v8":"2.0.2.0","lts":false,"security":false},
{"version":"v0.1.18","date":"2011-08-26",
```
and that's it. As you can see, the json data cuts off in the middle of the 0.1.18 version data. Our builds all broke because they try to read in this file.
It doesn't matter with which browser or on which operating system you retrieve this file, it's always broken. Happens since 22.11.2023, just a few minutes or so ago.

**Comment by Enet4** [comment]
This appears to be a recurrent issue (#6023). Regardless of which tools are used, the contents behind link https://nodejs.org/dist/index.json are currently ending like this:

```json
{"version":"v0.1.20","date":"2011-08-26","files":["src"],"v8":"2.0.2.0","lts":false,"security":false},
{"version":"v0.1.19","date":"2011-08-26","files":["src"],"v8":"2.0.2.0","lts":false,"security":false},
{"version":"v0.1.18","date":"2011-08-26",
```

Is this something to be expected shortly after a new release?

**Comment by ovflowd** [comment]
Please refer to: https://github.com/nodejs/nodejs.org/issues/4495
