### ISSUE TITLE
Update how-to-read-environment-variables-from-nodejs.md  with new `.env` guidance

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6140]
Update pages/en/learn/command-line/how-to-read-environment-variables-from-nodejs.md

This `.env` file addition should be a separate issue - otherwise this PR will be unresolved for longer.

_Originally posted by @bmuenzenmeyer in https://github.com/nodejs/nodejs.org/pull/6132#discussion_r1403442791_

**Comment by ShashwatPS** [comment]
Hey i would like to work on this issue. Can you describe a little bit of what exactly is supposed to be updated in the md file ?

**Comment by AugustinMauroy** [comment]
@ShashwatPS  [this section](https://github.com/nodejs/nodejs.org/blob/588511a314face6d41ce2f775c32af9190c6c2b8/pages/en/learn/command-line/run-nodejs-scripts-from-the-command-line.md?plain=1#L49C12-L59) in particular

**Comment by ShashwatPS** [comment]
I apologize for any inconvenience, but I noticed a discrepancy. The issue mentions a different file, while the reference you provided is for a file that seems to be different. @AugustinMauroy

**Comment by AugustinMauroy** [comment]
oops fail in copy paste 
[good link](https://github.com/nodejs/nodejs.org/blob/588511a314face6d41ce2f775c32af9190c6c2b8/pages/en/learn/command-line/how-to-read-environment-variables-from-nodejs.md?plain=1#L7-L48)

**Comment by ShashwatPS** [comment]
Got it. Could you please assign me to this issue? Would like to work on it.

**Comment by AugustinMauroy** [comment]
Thanks for your interest. We don't assign tickets if we can help it. Feel free to submit a pull request if you have time.
Reference 🍪 https://www.redhat.com/en/blog/dont-lick-cookie
