### ISSUE TITLE
"Certification" Link In Node.js Header No Longer Working 

### ISSUE THREAD

**Issue by bensternthal** [nodejs/nodejs.org#6151]
### URL:

https://openjsf.org/certification

### Browser Name:

Arc

### Browser Version:

- 

### Operating System:

- 

### How to reproduce the issue:

The header of the node.js website contains a link to https://openjsf.org/certification

The redesigned and recently launched OpenJS site no longer has a page at that URL and links directly to https://training.linuxfoundation.org/application-development/

**Comment by ovflowd** [comment]
@bensternthal quick question: Shouldn't a redirect link on openjsf.org be set to redirect openjsf.org/certification to training.linuxfoundation.org/application-development?

**Comment by ljharb** [comment]
Probably a 302 tho, since the former is a nicer URL than the latter, and the latter is more likely to change?

**Comment by haydenbleasel** [comment]
Resolved in https://github.com/openjs-foundation/openjsf/commit/783182bbfb8a0888f7280f7aecf00c17750226c1

**Comment by bmuenzenmeyer** [comment]
as this looks resolved, I am closing
