### ISSUE TITLE
blog: news from year

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/nodejs.org#6180]
### URL:

https://nodejs.org/en/blog/year-2010

### Browser Name:

NA

### Browser Version:

NA

### Operating System:

NA

### How to reproduce the issue:

if you go on `https://nodejs.org/en/blog/year-2011` there are no problem but if you go on `https://nodejs.org/en/blog/year-2010` getting 500 server error.

# Expected behaviourt:

404 page or date not found

**Comment by bmuenzenmeyer** [comment]
this is working for me. can you try again?

![image](https://github.com/nodejs/nodejs.org/assets/298435/9a9e9605-3f23-4dbc-b952-4548bad3aebc)

**Comment by AugustinMauroy** [comment]
I don't understand now the problem is fixed when I opened the exit I had a 505?

**Comment by ovflowd** [comment]
> I don't understand now the problem is fixed when I opened the exit I had a 505?

It's fixed on my hot-fix of today https://github.com/nodejs/nodejs.org/commit/1a16c4c129f7d4627bd99da185e4690c171b2a25 the issue being that if `dynamicParams` are disabled for Vercel deployments, it will give 5XX instead od 404s for dynamic segments. Which is genuinely speaking, weird.

But genuinely speaking, this page should probably 404. This can be done in another PR, and I'll do it.

**Comment by ovflowd** [comment]
Hot-fix: https://github.com/nodejs/nodejs.org/commit/b609fee4e72f8cc399f55838467c15d3e9f9a5a6
