### ISSUE TITLE
Linux Foundation svg is cutoff on smaller mobile devices

### ISSUE THREAD

**Issue by evanlucas** [nodejs/nodejs.org#62]
I wanted to open an issue to see if it is possible to edit the svg that is used. I wasn't sure if that was provided by the Linux Foundation and could have any changes. If changes can be made, I can work on making it fit on mobile now.

Here is what it currently looks like:
![screen shot 2015-08-30 at 8 07 10 am](https://cloud.githubusercontent.com/assets/677994/9567379/2a21757a-4eee-11e5-9cf3-17afab4b2ea3.png)

**Comment by fhemberger** [comment]
It can be changed. I ripped it from a Linux Foundation PDF because we didn't have a proper SVG version. ;)

**Comment by evanlucas** [comment]
Fixed by https://github.com/nodejs/new.nodejs.org/pull/63
