### ISSUE TITLE
https://nodejs.org/en/blog is returning a 404

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6205]
>[!NOTE]
> WORKAROUND https://nodejs.org/en/blog/year-2023

---

https://nodejs.org/en/blog

![image](https://github.com/nodejs/nodejs.org/assets/298435/8d20de8b-a8ee-42a7-9c7a-e1a68396bac7)

**Comment by bmuenzenmeyer** [comment]
likely one of these dependencies broke it 
![image](https://github.com/nodejs/nodejs.org/assets/298435/314a5325-edd2-44e2-ab7b-38329c17731a)

**Comment by bmuenzenmeyer** [comment]
temporary workaround at https://nodejs.org/en/blog/year-2023

**Comment by MattIPv4** [comment]
As a more permanent fix, I think we'd want to update https://github.com/nodejs/nodejs.org/blob/dbd0322f54f230ee65c09bcdfe67ed82147a8c3f/layouts/BlogCategoryLayout.tsx#L37

We'd probably want to try fetching the previous year if, and only if, we're exactly on `/blog`, and `posts.length` is `0`:

```ts
const { posts, pagination } = await getBlogData(category)
  .then(data => data.posts.length === 0 && pathname === '/blog'
    ? getBlogData(`year-${new Date().getFullYear() - 1}`) : data);
```
