### ISSUE TITLE
Migrate the legacy guide "Diagnostics - Flame Graphs" to the learn section

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6221]
Migrate the content currently at [Diagnostics - Flame Graphs](https://nodejs.org/en/guides/diagnostics-flamegraph/) to a new page under the "learn" section found at https://github.com/nodejs/nodejs.org/tree/main/pages/en/learn.

- [ ] Use your judgement about what existing or new folder the content should go in. Ask in a draft PR if you are unsure. 
- [ ] Review the content during migration, please do not simply copy/paste the content. Similar to #6140, the content may need edits to account for the latest Node.js features.
- [ ] Run your content through a spell-checker in the editor, like https://github.com/streetsidesoftware/vscode-spell-checker, Word/Google Docs, Grammarly, or https://alexjs.com/

**Comment by paulobelucci** [comment]
Hi there, I leave here the PR for review: #6285

**Comment by mikeesto** [comment]
Resolved by https://github.com/nodejs/nodejs.org/pull/6285 . Thanks @paulobelucci
