### ISSUE TITLE
Migrate the legacy guide "Backpressuring in Streams" to the learn section

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6228]
Migrate the content currently at [Backpressuring in Streams](https://nodejs.org/en/guides/backpressuring-in-streams/) to a new page under the "learn" section found at https://github.com/nodejs/nodejs.org/tree/main/pages/en/learn.

- [ ] Use your judgement about what existing or new folder the content should go in. Ask in a draft PR if you are unsure. 
- [ ] Review the content during migration, please do not simply copy/paste the content. Similar to #6140, the content may need edits to account for the latest Node.js features.
- [ ] Add a redirect to the new content in `redirects.json`
- [ ] Run your content through a spell-checker in the editor, like https://github.com/streetsidesoftware/vscode-spell-checker, Word/Google Docs, Grammarly, or https://alexjs.com/

**Comment by NextThread** [comment]
Hey, can I work on this?

**Comment by AugustinMauroy** [comment]
@NextThread yeah gooo headed !

**Comment by NextThread** [comment]
#6261  raised my PR here

**Comment by paulobelucci** [comment]
Hi there! Here is my PR #6352 to review.
