### ISSUE TITLE
Widely referenced /about/releases page returns 404

### ISSUE THREAD

**Issue by mohd-akram** [nodejs/nodejs.org#6231]
### URL:

https://nodejs.org/en/about/releases

### Browser Name:

Safari

### Browser Version:

17.2.1

### Operating System:

macOS 14.2.1

### How to reproduce the issue:

1. Go to https://nodejs.org/en/about/releases
2. See 404

This page is referenced in [many places](https://github.com/search?q=https%3A%2F%2Fnodejs.org%2Fen%2Fabout%2Freleases&type=code) to link to the Node.js release schedule.

**Comment by ovflowd** [comment]
Thanks for reporting this! Let me make a quick hot-fix.

**Comment by ovflowd** [comment]
Fixed on https://github.com/nodejs/nodejs.org/commit/2c8782575743ef84cc987605ded6cfaabf90071c deployment in progress: https://vercel.com/openjs/nodejs-org/4EyvoAbfFNaAMe6mS24sTbtRqvqC

**Comment by ovflowd** [comment]
Fixed
