### ISSUE TITLE
Downloads page OR docs should indicate more obviously that WSL is NOT supported but should still work

### ISSUE THREAD

**Issue by picklesnathan** [nodejs/nodejs.org#6269]
### Enter your suggestions in details:

The link to instructions on installing Node on WSL's downloads page - [Install on Windows Subsystem for Linux (WSL)](https://github.com/nodejs/node/blob/main/BUILDING.md#building-nodejs-on-supported-platforms) goes to the "supported platforms" section of the build instructions which only contains information on linux platforms which ARE supoprted. This nearly lead me to believe it was actually supported until I ctrl+f "WSL" and jump down to that footnote.

In my opinion, some change that further distinguishes WSL within the website or the docs would save a bit of confusion. Simplest apparent fix is changing [Install on Windows Subsystem for Linux (WSL)](https://github.com/nodejs/node/blob/main/BUILDING.md#building-nodejs-on-supported-platforms)'s destination to as close to the [footnote 3 as possible.](https://github.com/nodejs/node/blob/main/BUILDING.md#user-content-fnref-3-4da43b5df4fa2531d1f3d8a53fef907b)

**Comment by lemire** [comment]
Why is it not supported?

**Comment by picklesnathan** [comment]
Not sure, that is the wording used in the footnote. It still has its own
issue reporting page though so some unofficial support.

**Comment by lemire** [comment]
What is the issue reporting page?

**Comment by picklesnathan** [comment]
I'm on mobile and can't check GitHub at the moment but it's linked in the
same footnote referenced in my post

**Comment by mikeesto** [comment]
It took me a while to understand but I think I get it now.

On https://nodejs.org/en/download there is a link at the bottom of the page for "Install on Windows Subsystem for Linux (WSL)" which navigates to https://github.com/nodejs/node/blob/main/BUILDING.md#building-nodejs-on-supported-platforms. On this markdown document there is a footnote that says:

>The Windows Subsystem for Linux (WSL) is not supported, but the GNU/Linux build process and binaries should work. The community will only address issues that reproduce on native GNU/Linux systems. Issues that only reproduce on WSL should be reported in the [WSL issue tracker](https://github.com/Microsoft/WSL/issues).

The "WSL issue tracker" is the Microsoft WSL GitHub issue page. This is not part of the Node project. Essentially what this footnote is saying is that Node should build and run on GNU/Linux. If there is an issue that is only reproducible on WSL, then it should be reported to MS and needs to be resolved on the WSL side.

The nodejs.org download page is going to be updated as part of the overall [website redesign](https://github.com/nodejs/nodejs.org/discussions/5131). On the redesign this "Install on Windows Subsystem for Linux (WSL)" link is not present so hopefully that will resolve any confusion.

**Comment by lemire** [comment]
Maybe we can close this issue? And reopen it if the site update does not clear the confusion.

@bronco-henry If you encounter issues while running node under WSL, I encourage you to report them as bugs if needed.

**Comment by picklesnathan** [comment]
Okay sounds great, thank you all for the quick and sincere resonse. @mikeesto perhaps I shouldve looked into upcoming change. Will keep that in mind moving forward.
