### ISSUE TITLE
Question: should document encourage/discourage userland code from introducing error code name?

### ISSUE THREAD

**Issue by bitinn** [nodejs/nodejs.org#629]
Apologize if this is not the place to discuss this.

I am thinking about standardizing error object for one of my module, but I can't seem to make up my mind on whether `err.code` should follow `E`-style naming like node.js core and linux, or introduce a custom `err.type` attribute with my custom name.

Does Node.js has a preference on this? Should it be in document? On client-side error standardization beyond `err.name` and `err.message` isn't going anyway as far as I can tell... 

ref:
https://nodejs.org/api/errors.html#errors_system_errors
https://github.com/bitinn/node-fetch/pull/99

**Comment by fhemberger** [comment]
You are right, you got the wrong place. This is the issue tracker of the **Node.js website**.
Please head over to https://github.com/nodejs/help.

(But to shed some light on your question: If it's just a regular error, use an instance of `Error`. If it's a special type of error, define a new one inheriting from `Error`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Custom_Error_Types. Those `E`-style errors are system errors (and IMHO should only be used for this). They usually cause more confusion in JavaScript land than help. :smile:)
