### ISSUE TITLE
Separate doc pages for ES2015, ES2016, etc

### ISSUE THREAD

**Issue by amirmohsen** [nodejs/nodejs.org#633]
I noticed that in https://github.com/nodejs/nodejs.org/blob/master/locale/en/docs/es6.md , there's a mention of Array.prototype.includes. Isn't that technically ES2016 and not 2015?
Wouldn't it be better to have separate pages for each ES version?
Another option is to have a table that maps node versions with individual features regardless of the ES release they are included in.
Or at the very least, just changing that page to say something more generic like ES Future.

**Comment by fhemberger** [comment]
Work on that has already started: https://github.com/nodejs/nodejs.org/pull/434

**Comment by amirmohsen** [comment]
Cool. I had a look through the issues before posting. I guess I should have checked the PRs as well. Good to know that progress is being made.
