### ISSUE TITLE
Discuss about the design at `foundation/in-the-news/`

### ISSUE THREAD

**Issue by hiroppy** [nodejs/nodejs.org#636]
I think that  it is better for this page to use a list.
This is because I think that this page is hard to watch on Smartphone if it is not the list.
### PC

<img width="1066" alt="2016-04-07 0 22 53" src="https://cloud.githubusercontent.com/assets/3367801/14322692/bc743404-fc58-11e5-8ff6-03faab85302d.png">
### Smartphone

![screenshot_20160407-001812](https://cloud.githubusercontent.com/assets/3367801/14322707/c5b7f91a-fc58-11e5-8e65-5ca47165b09a.png)
### PC

<img width="1088" alt="2016-04-06 22 37 16" src="https://cloud.githubusercontent.com/assets/3367801/14322725/db905db8-fc58-11e5-9439-bd538bd8035a.png">
### Smartphone

![screenshot_20160407-001834](https://cloud.githubusercontent.com/assets/3367801/14322750/e9a536bc-fc58-11e5-8e03-a9d58d499482.png)

How does everybody think?

**Comment by lpinca** [comment]
I don't have a preference I'm fine with both.
Maybe it would be better to use a date as prefix instead of a bullet.
I mean something like the "Announcements" page.

**Comment by fhemberger** [comment]
It would be great if both "Announcements" and "In the News" would use the same style (regardless of list bullets or not).

**Comment by fhemberger** [comment]
Added a PR. @abouthiroppy Would you still favor the bullet point list variant?

**Comment by hiroppy** [comment]
@fhemberger  Thank you so much! I think that's ok.
