### ISSUE TITLE
NodeJS LTS Linux download link dead

### ISSUE THREAD

**Issue by theo-meow** [nodejs/nodejs.org#6360]
### URL:

https://nodejs.org/

### Browser Name:

Firefox

### Browser Version:

123.0

### Operating System:

Manjaro Linux 6.7.2

### How to reproduce the issue:

1. Using a Browser running under Linux, visit https://nodejs.org/en
2. under "Download Node.js", click the left hand button that says "20.11.1 LTS"

Expected: tar.xz download
Actual: Dead link, reporting a 404 nginx error

Additional info:
It seems the link points to a x86 build, which does not exist.
Specifically, it points to:  
 https://nodejs.org/dist/v20.11.1/node-v20.11.1-linux-x86.tar.xz
While it should point to:  
https://nodejs.org/dist/v20.11.1/node-v20.11.1-linux-x64.tar.xz

**Comment by theo-meow** [comment]
![nodejs](https://github.com/nodejs/nodejs.org/assets/45607304/eba14b0d-d490-48da-815e-45c08ab37eca)

for reference

**Comment by theo-meow** [comment]
I believe this is due to bitness detection in util/getNodeDownloadUrl.ts
For whatever reason it detects an x86 build, even though I am on x64.
In Issue nodejs/build#885, 32bit builds were dropped.
My suggestion, though this is a dirty solution, would be to always link x64 builds for linux, since any other bitness can never be delivered.

**Comment by ovflowd** [comment]
> I believe this is due to bitness detection in util/getNodeDownloadUrl.ts For whatever reason it detects an x86 build, even though I am on x64. In Issue [nodejs/build#885](https://github.com/nodejs/build/issues/885), 32bit builds were dropped. My suggestion, though this is a dirty solution, would be to always link x64 builds for linux, since any other bitness can never be delivered.

This issue only exists on the old/legacy Node.js website. Can you check if the same issue happens on the new website? (https://beta-node-js-org.vercel.app/en) (This website is not yet public)

**Comment by theo-meow** [comment]
Hi @ovflowd , I have tried this and the issue does persist.
This does not seem solved on the new site.

**Comment by ovflowd** [comment]
> Hi @ovflowd , I have tried this and the issue does persist. This does not seem solved on the new site.

We use the Browser Bitness API to get your system bitness. What browser do you use? You wrote 123.0 on Browser, is that a version or?

Note that it is only supported on these Browsers: https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/getHighEntropyValues

**Comment by theo-meow** [comment]
As written in my initial message, my browser is Firefox 123.0 (version).
On other websites that I tried, my browser bitness comes back as 32 bit too.

Whatever the case may be; I think since there are no x86 versions of nodejs for linux available, the website should not generate a download link that can never be valid.

**Comment by ovflowd** [comment]
> As written in my initial message, my browser is Firefox 123.0 (version).

I completely missed the name of the Browser!

And yes, this API is not available on Firefox.

> Whatever the case may be; I think since there are no x64 versions of nodejs for linux available, the website should not generate a download link that can never be valid.

I'm unfortunately unable to reproduce your issue on the redesign. Could you mention in which tab you're facing this issue? The only tab supporting Linux on the redesign is the "Prebuilt Binaries" one, and we don't even show a x86 option for Linux there 🤔 could you record a screenshot/video of the issue on the redesig? i.e. https://beta-node-js-org.vercel.app

**Comment by theo-meow** [comment]
In the prebuilt binaries I do not have this issue,
However on the home page it looks like the page autodetects a linux x86, and generates a corresponding download link.
I have reproduced this on 3 different devices, all running the latest KDE manjaro linux. So it's probably not something weird with my setup that's causing this.

Find a GIF attached.

![nodejs](https://github.com/nodejs/nodejs.org/assets/45607304/72172ece-daa8-48fd-bf08-c097a7bd4db2)

**Comment by ovflowd** [comment]
> In the prebuilt binaries I do not have this issue,
> 
> However on the home page it looks like the page autodetects a linux x86, and generates a corresponding download link.
> 
> I have reproduced this on 3 different devices, all running the latest KDE manjaro linux. So it's probably not something weird with my setup that's causing this.
> 
> 
> 
> Find a GIF attached.
> 
> 
> 
> ![nodejs](https://github.com/nodejs/nodejs.org/assets/45607304/72172ece-daa8-48fd-bf08-c097a7bd4db2)
> 
> 
> 
> 

Right, but again, just to clarify the issue is not that it is detecting x86, it is just probably fall-backing to x86... But Ill work on a fix anyways

**Comment by o5k** [comment]
by the by https://nodejs.org/en/download/prebuilt-binaries links to `https://nodejs.org/dist/v20.11.1/node-v20.11.1-linux-64.tar.xz` (note the `64` instead of `x64`)... which is also a 404. to bypass it you need to click to a different option then back (at which point it will select `x64` properly)

![image](https://github.com/nodejs/nodejs.org/assets/52112045/a53f58e5-f025-48b3-b08c-9182b7ff5227)

Tested on FF 115 (Waterfox G6.0.9, which is built against FF ESR). Please respect the UNOFFICIAL DRAFT splashed all over https://wicg.github.io/ua-client-hints/#dom-navigatoruadata-gethighentropyvalues ...

**Comment by ovflowd** [comment]
> ![Screenshot](https://private-user-images.githubusercontent.com/75916193/314189900-1eb86eeb-171c-458b-84fd-6986f7d13c1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NzU3NzMsIm5iZiI6MTcxMDg3NTQ3MywicGF0aCI6Ii83NTkxNjE5My8zMTQxODk5MDAtMWViODZlZWItMTcxYy00NThiLTg0ZmQtNjk4NmY3ZDEzYzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE5MTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NTVjZGZjYWIzZTY2MmUwZDY2ZTdkN2IwNWUzNGVjYjdkY2RhNjU4MTE0NTEzN2IyYzljNTExMTZjNTNmYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wx3nQbJ9mXCVppz9JYqDYGYKPkDr8pYIn9RvEhiC7eQ) Why the hell is this broken for 3 weeks (and counting)? FF has a 7.26% desktop browser market share

This issue has nothing to do with Firefox. It affects Firefox, but it's not related to Firefox.

**Comment by ovflowd** [comment]
> by the by [nodejs.org/en/download/prebuilt-binaries](https://nodejs.org/en/download/prebuilt-binaries) links to https://nodejs.org/dist/v20.11.1/node-v20.11.1-linux-64.tar.xz (note the 64 instead of x64)... which is also a 404. to bypass it you need to click to a different option then back (at which point it will select x64 properly)

Oh that seems a typo from our side. @nodejs/nodejs-website can someone look into this?

**Comment by ovflowd** [comment]
> ![Screenshot](https://private-user-images.githubusercontent.com/75916193/314189900-1eb86eeb-171c-458b-84fd-6986f7d13c1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NzU3NzMsIm5iZiI6MTcxMDg3NTQ3MywicGF0aCI6Ii83NTkxNjE5My8zMTQxODk5MDAtMWViODZlZWItMTcxYy00NThiLTg0ZmQtNjk4NmY3ZDEzYzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE5MTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NTVjZGZjYWIzZTY2MmUwZDY2ZTdkN2IwNWUzNGVjYjdkY2RhNjU4MTE0NTEzN2IyYzljNTExMTZjNTNmYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wx3nQbJ9mXCVppz9JYqDYGYKPkDr8pYIn9RvEhiC7eQ) Why the hell is this broken for 3 weeks (and counting)? FF has a 7.26% desktop browser market share

We did fix this issue, or at least we thought so that we did with the recently released redesign. Please mind your tone. We are all volunteers here.

**Comment by anandMohanan** [comment]
![image](https://github.com/nodejs/nodejs.org/assets/36781763/f83eb896-03f7-431b-bc5a-3564b138508d)

Using firefox version 123.0.1 and the issue still exists FYI.
![image](https://github.com/nodejs/nodejs.org/assets/36781763/bb417f99-d41a-44e5-927f-8062ce464f2d)

![image](https://github.com/nodejs/nodejs.org/assets/36781763/07e0d1c8-b636-4d9b-a15e-b96b7da836c8)

**Comment by ovflowd** [comment]
> > Please mind your tone.
> 
> no fix your software

As mentioned before, we are working on a fix already, so there's no need for hostility.

**Comment by ovflowd** [comment]
I'd appreciate it if y'all could test https://nodejs-org-git-fork-canerakdas-fix-linux-bitness-openjs.vercel.app/ this preview branch and check if the bug is fixed.

**Comment by anandMohanan** [comment]
Hi @ovflowd 
![image](https://github.com/nodejs/nodejs.org/assets/36781763/f9c17ebf-4402-43c7-9886-f8300b037a7a)
![image](https://github.com/nodejs/nodejs.org/assets/36781763/8af8677f-3cb6-4edb-8d73-e54bfad23a87)


Yes, I am able to download the file now using this branch https://nodejs-org-git-fork-canerakdas-fix-linux-bitness-openjs.vercel.app/ 
Have a Great day.

**Comment by theo-meow** [comment]
> I'd appreciate it if y'all could test https://nodejs-org-git-fork-canerakdas-fix-linux-bitness-openjs.vercel.app/ this preview branch and check if the bug is fixed.

Looks good to me, unable to reproduce the bug on this website.
