### ISSUE TITLE
bash script code highlight on `<name>` with ending white charater

### ISSUE THREAD

**Issue by himself65** [nodejs/nodejs.org#6363]
### URL:

https://nodejs.org/en/learn/getting-started/an-introduction-to-the-npm-package-manager

### Browser Name:

Chrome

### Browser Version:

Version 121.0.6167.184 (Official Build) (arm64)

### Operating System:

macOS 14.3.1 (23D60)

### How to reproduce the issue:

<img width="744" alt="image" src="https://github.com/nodejs/nodejs.org/assets/14026360/43dc3523-c5ec-4559-ae21-a9135cb1eccc">

https://github.com/nodejs/nodejs.org/blob/04fd007aa4528b88abcd0722c1c6ff1788cb08cc/pages/en/learn/getting-started/an-introduction-to-the-npm-package-manager.md?plain=1#L38

**Comment by nidhinshah** [comment]
Hi @himself65 i see this in each of the line where we have bash and `>` character. i.e. `npm install <package-name>@<version>` or `npm run <task-name>` in each browser.

it seems this happens when any letter / character appears before `>` in Bash.
If we do quotation like `npm install <'package-name'>` instead of `npm install <package-name>` might resolve issue. 

that has to be consistent throughout all documents though when we use bash and has `>` character.

**Comment by ovflowd** [comment]
> ### URL:
> [nodejs.org/en/learn/getting-started/an-introduction-to-the-npm-package-manager](https://nodejs.org/en/learn/getting-started/an-introduction-to-the-npm-package-manager)
> 
> ### Browser Name:
> Chrome
> 
> ### Browser Version:
> Version 121.0.6167.184 (Official Build) (arm64)
> 
> ### Operating System:
> macOS 14.3.1 (23D60)
> 
> ### How to reproduce the issue:
> <img alt="image" width="744" src="https://private-user-images.githubusercontent.com/14026360/308731420-43dc3523-c5ec-4559-ae21-a9135cb1eccc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMzM0MTMsIm5iZiI6MTcwOTMzMzExMywicGF0aCI6Ii8xNDAyNjM2MC8zMDg3MzE0MjAtNDNkYzM1MjMtYzVlYy00NTU5LWFlMjEtYTkxMzVjYjFlY2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDIyNDUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MTU2YjE0ZWY4NDNjYzE3NmZiYjZhM2ZhNmJkZjNhODgxM2RkZTdhZmU2MTI2MjI0Njk5Y2ExMzM0MWI0NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sMJGSIMBTt8J1S91VNUnoF1ipo9ZFrZa3eHoVaDUiI8">
> https://github.com/nodejs/nodejs.org/blob/04fd007aa4528b88abcd0722c1c6ff1788cb08cc/pages/en/learn/getting-started/an-introduction-to-the-npm-package-manager.md?plain=1#L38

I assume this is an issue on Shiki rather than on our side of things. @himself65 can you reproduce similar behaviour with a simple react app (or any example) using Shiki? (If you have the capacity/time to test)

**Comment by himself65** [comment]
Yeah, I will do that!

**Comment by himself65** [comment]
https://github.com/shikijs/shiki/issues/606

**Comment by ovflowd** [comment]
Oh seems indeed a bug on their side, hm! @himself65 mind if I close this issue here? I'll keep a track on the issue on /shiki side of things 👀
