### ISSUE TITLE
Breadcrumbs not updating on Learn pages

### ISSUE THREAD

**Issue by mikeesto** [nodejs/nodejs.org#6365]
### URL:

https://nodejs-bjq0pcoku-openjs.vercel.app/en/learn/getting-started/how-to-install-nodejs

### Browser Name:

Chrome

### Browser Version:

122.0.6261.69

### Operating System:

MacOS

### How to reproduce the issue:

The breadcrumbs on the Learn pages display "Diagnostics" regardless of what module the page actually falls under. The breadcrumbs should dynamically update to reflect the correct module.
<img width="1175" alt="Screen Shot 2024-02-29 at 1 19 49 pm" src="https://github.com/nodejs/nodejs.org/assets/21051488/87df5332-ff12-44dc-bbf0-eaf191dac3a1">

**Comment by ovflowd** [comment]
> The breadcrumbs on the Learn pages display "Diagnostics" regardless of what module the page actually falls under. The breadcrumbs should dynamically update to reflect the correct module.

This issue has happened before, and it is usually related to the logic of current pathname, definitely something we should fix.

**Comment by yanggggjie** [comment]
> > The breadcrumbs on the Learn pages display "Diagnostics" regardless of what module the page actually falls under. The breadcrumbs should dynamically update to reflect the correct module.
> 
> This issue has happened before, and it is usually related to the logic of current pathname, definitely something we should fix.

Is anyone taking it? I have nextjs programming experience and I'm happy to help.

**Comment by AugustinMauroy** [comment]
> Is anyone taking it? 

Thanks for your interest. We don't assign tickets if we can help it. Feel free to submit a pull request if you have time.
Reference 🍪 https://www.redhat.com/en/blog/dont-lick-cookie

So yeah go ahead

**Comment by ovflowd** [comment]
> > > The breadcrumbs on the Learn pages display "Diagnostics" regardless of what module the page actually falls under. The breadcrumbs should dynamically update to reflect the correct module.
> > 
> > 
> > This issue has happened before, and it is usually related to the logic of current pathname, definitely something we should fix.
> 
> Is anyone taking it? I have nextjs programming experience and I'm happy to help.

Yeah, feel free to just tackle the work :)
