### ISSUE TITLE
New webpage Read Streams example is confusing

### ISSUE THREAD

**Issue by yoavain** [nodejs/nodejs.org#6390]
### Enter your suggestions in details:

Lines 3-4 of the "Read Streams" example are confusing.
I suggest extracting them into a new "Fetch" example.

![image](https://github.com/nodejs/nodejs.org/assets/644871/fa8482f2-27f2-48eb-b7db-59e393c38000)

**Comment by ovflowd** [comment]
I see! That's indeed confusing because the Read Streams shows two different examples.

Feel free to make a PR removing the first fetch part, but if possible, find a way to make the example still last 11 lines. (We're aiming for every example to be 11 lines to keep the CodeBox consistent)

**Comment by bmuenzenmeyer** [comment]
agree on this - mentioned when first introduced too https://github.com/nodejs/nodejs.org/pull/6215#pullrequestreview-1814550649

**Comment by bmuenzenmeyer** [comment]
closed via https://github.com/nodejs/nodejs.org/pull/6457
