### ISSUE TITLE
Confusing "Download Node.js" button on homepage

### ISSUE THREAD

**Issue by uncenter** [nodejs/nodejs.org#6392]
### Enter your suggestions in details:

![Screenshot 2024-03-02 at 09 06 39 (Arc)](https://github.com/nodejs/nodejs.org/assets/47499684/d07b860e-d797-418f-8008-a2e87e19d5a7)

This button has a sideways arrow (->), implying that it will bring you to the downloads page ([https://beta-node-js-org.vercel.app/en/download](https://t.co/dXms7U0ziX)) but instead it downloads a file (I know this is explained by the text below but it isn't immediate apparent).  I would either change the link to go to the download page or change the icon to a download icon.

**Comment by gillian-black** [comment]
@ovflowd Any direction on link vs icon swap? Looking to make my first contribution and this one's nice and simple.

**Comment by AugustinMauroy** [comment]
@blackg33 an pr is already opened #6395
