### ISSUE TITLE
The blog's event page is not found.

### ISSUE THREAD

**Issue by KazooTTT** [nodejs/nodejs.org#6394]
### URL:

https://beta-node-js-org.vercel.app/en/blog

### Browser Name:

arc (Based on Chromium)

### Browser Version:

122.0.6261.94

### Operating System:

macos 14.4

### How to reproduce the issue:

After I click on the "event " tab button, it shows "Page could not be found."

<img width="1920" alt="image" src="https://github.com/nodejs/nodejs.org/assets/31075337/ff97edd5-0d8e-48f7-99f2-81b9fbf70b9b">

<img width="1920" alt="image" src="https://github.com/nodejs/nodejs.org/assets/31075337/b878d77d-9b22-4df8-a67d-2d155a994f47">

**Comment by AugustinMauroy** [comment]
'cause there are no post about events.

So what we can do:
- Hide "events" from TabsLink
- Add feature to handle if "there are not post yet"
- or write post about future and past events

**Comment by ovflowd** [comment]
To clarify it's NOT a bug, we just don't render a blog category if there aren't blog posts for such category.

And in general such situations should never exist. I guess we can for the time being simply remove that Events tab until we actually have blog posts on that category.

**Comment by AugustinMauroy** [comment]
So let's hide "events" from TabsLink. To do that just remove [this line](https://github.com/nodejs/nodejs.org/blob/2f6e08bbcc5a3f4df041f5dd13082672f6d6a691/layouts/Blog.tsx#L54)
