### ISSUE TITLE
Linux :penguin: is disabled on the Download page (Prebuilt Installer)

### ISSUE THREAD

**Issue by nina-mir** [nodejs/nodejs.org#6397]
### URL:

https://beta-node-js-org.vercel.app/en/download

### Browser Name:

Chrome

### Browser Version:

  122.0.6261.94

### Operating System:

Linux Ubuntu 20

### How to reproduce the issue:

On the Prebuilt Installer tab on the Download page, the Linux OS option for any version of Node on any CPU architecture appears to be disabled and not possible to be selected by the user. 

I guess if Prebuilt installer is not supposed to be an option for Linux users, it is best to not have that option displayed instead of disabling it. 

![image](https://github.com/nodejs/nodejs.org/assets/39842445/d8db8498-b560-4deb-99b7-1ad6ff7d2a97)

**Comment by ovflowd** [comment]
The reason why we have it there is to clarify that there's no "Linux Installer explicitly"... The concept of an installer is non-existent on Linux.

This is an intentional behaviour, because otherwise people would also ask "Why there's no Linux option", with having it there and disabled it gives the explicit information that we don't have one.

I'm closing this as a wont-fix as this is not a bug but a UI preference. Feel free to reopen if you have stronger feelings about this, but again, it's a matter of choice here...

**Comment by nina-mir** [comment]
Got it! Makes sense! Thanks for your response!

**Comment by ovflowd** [comment]
> Got it! Makes sense! Thanks for your response!

No worries. Let us know if you find any other oddity or if you have any other question 🙇

**Comment by ThomasAunvik** [comment]
Would it be a better way for it to then default show package manager as the default tab for linux? Cause by default today, the first download link leads to windows.

**Comment by ovflowd** [comment]
> Would it be a better way for it to then default show package manager as the default tab for linux? Cause by default today, the first download link leads to windows.

It leads to Windows if it detects Windows. But yes, we're considering changing "Package Manager" as the default tab.

**Comment by aral** [comment]
If there is no prebuilt installer for Linux, I would:

- Not display the Linux (or AIX) entries in the drop-down (existing but being disabled is a different state than not existing.)

- When Linux is detected, display either the prebuilt binaries or package manger tab by default.

With the current affordance, my thought was, “oh, there must be some reason I can’t download the prebuilt installer for Linux. I wonder if it’s detecting my OS incorrectly and not allowing me to.”

**Comment by ovflowd** [comment]
> If there is no prebuilt installer for Linux, I would:
> 
> 
> 
> - Not display the Linux (or AIX) entries in the drop-down (existing but being disabled is a different state than not existing.)
> 
> 
> 
> - When Linux is detected, display either the prebuilt binaries or package manger tab by default.
> 
> 
> 
> With the current affordance, my thought was, “oh, there must be some reason I can’t download the prebuilt installer for Linux. I wonder if it’s detecting my OS incorrectly and not allowing me to.”

That interpretation below sounds pretty individual. It's a common understanding of being disabled = not being allowed to. It's clearer to explicitly show that Linux is not available rather than not showing at all which can create the opposite effect: "where is the linux option?"

**Comment by aral** [comment]
> That interpretation below sounds pretty individual. It's a common understanding of being disabled = not being allowed to. It's clearer to explicitly show that Linux is not available rather than not showing at all which can create the opposite effect: "where is the linux option?"

Sure, just my opinion as a designer. It’s worth exactly as much as you paid for it ;)

Not my circus, not my monkeys :)

**Comment by ovflowd** [comment]
> > That interpretation below sounds pretty individual. It's a common understanding of being disabled = not being allowed to. It's clearer to explicitly show that Linux is not available rather than not showing at all which can create the opposite effect: "where is the linux option?"
> 
> Sure, just my opinion as a designer. It’s worth exactly as much as you paid for it ;)
> 
> Not my circus, not my monkeys :)

All good. I Appreciate your feedback. I'll keep an eye on Sentry's Session Replay and more feedback coming it, depending on how much we see that people are reaching out to the same conclusion/blocker as you, we will revert the decision of displaying Linux as "disabled"
