### ISSUE TITLE
Hard to read the navigation menu items in light mode

### ISSUE THREAD

**Issue by rluvaton** [nodejs/nodejs.org#6398]
### URL:

https://beta-node-js-org.vercel.app/en

### Browser Name:

Safari

### Browser Version:

Good question

### Operating System:

iOS 17

### How to reproduce the issue:

1. Go to website
2. Click on the menu bar
3. Change to light mode

![IMG_9525](https://github.com/nodejs/nodejs.org/assets/16746759/d9eff032-8be4-4d07-9ef4-4eaa74d6afff)

**Comment by AugustinMauroy** [comment]
FYI: the strange hexagon redering is Safari bug.
I thinks the effect should be "push" by the deployment of the nav

**Comment by ovflowd** [comment]
> FYI: the strange hexagon redering is Safari bug. I thinks the effect should be "push" by the deployment of the nav

We should give a solid background to the nav. Can you make a PR?, the background shouldn't be transparent.

**Comment by ovflowd** [comment]
Now regarding the hexagons being like this, I wasn't able to reproduce this on my Safari on latest iOS (iPhone 15 Pro).

Is this some accessibility setting?

**Comment by AugustinMauroy** [comment]
> Is this some accessibility setting?

I never active some  accessibility setting so IDK ?

I have this randomly on my Mac with safari 17.1

**Comment by ovflowd** [comment]
> I have this randomly on my Mac with safari 17.1

Weird, I never seen this happening, but I'll keep an eye on that. Meanwhile, we should give a solid background for the expanded nav.

**Comment by ovflowd** [comment]
@AugustinMauroy want to tackle it?

**Comment by AugustinMauroy** [comment]
Yeah I'm working on
