### ISSUE TITLE
Learn Page dropdown clickable entries not visibly distinct on mobile

### ISSUE THREAD

**Issue by mojitane** [nodejs/nodejs.org#6400]
### URL:

https://nodejs-baeh8grik-openjs.vercel.app/en/learn/getting-started/introduction-to-nodejs

### How to reproduce the issue:

1. Go to Learn on mobile breakpoint
2. Open change page drop-down
3. Some entries are clickable and some aren’t with almost no visible difference, especially on dark mode

![IMG_8610](https://github.com/nodejs/nodejs.org/assets/15133101/2306be9c-5a48-4557-92b8-18cea7da3cd4)

It feels like trial and error on mobile to find the clickable entries. They are slightly different but not enough.
This issue does not exist on bigger screens as they use a different nav. It also does not exist when hover is available.

Idea: Style chapter headlines more visually distinct

**Comment by AugustinMauroy** [comment]
FYI: [Figma design](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=719-8395&mode=design&t=8NiG2VbGkS7xxqq9-0)

But I allow with you the headlines should have different style

**Comment by ovflowd** [comment]
> It feels like trial and error on mobile to find the clickable entries. They are slightly different but not enough.
This issue does not exist on bigger screens as they use a different nav. It also does not exist when hover is available.

The ones that aren't clickable, are actually "Category sections".

> But I allow with you the headlines should have different style

I think this could be easily fixed, if we increase the left-padding of the entries (keeping the headings with lower left-padding)

**Comment by AugustinMauroy** [comment]
> I think this could be easily fixed, if we increase the left-padding of the entries (keeping the headings with lower left-padding)

IMHO, I think we should put a larger padding on the top to make "sections".  Or put border on top of title

**Comment by ovflowd** [comment]
> > I think this could be easily fixed, if we increase the left-padding of the entries (keeping the headings with lower left-padding)
> 
> IMHO, I think we should put a larger padding on the top to make "sections". Or put border on top of title

But... I literally said that. Usually Select Lists with "sections" have

- Section A
  - Option A
  - Option B
- Section B
- ...

That's the same concept with lists. The options themselves have a higher left-padding.

**Comment by AugustinMauroy** [comment]
also padding left will trunk the long titles. No ?

**Comment by mojitane** [comment]
> also padding left will trunk the long titles. No ?

It seems the truncation is not working correctly already. A lot of titles are cut off. 
I looked a bit at the styles, and it seems the `truncate` class is applied to the wrapping `.dropdown .item`. But at the same time, there is additional styling on `.text span`. This sets the span as `display: flex` and with that currently disables the truncation completely without apparent benefit.

Current:
<img width="373" alt="image" src="https://github.com/nodejs/nodejs.org/assets/15133101/0e2561a8-ccdc-431f-afc6-763f92a984f7">

Flex removed:
<img width="355" alt="image" src="https://github.com/nodejs/nodejs.org/assets/15133101/3e034797-ad62-42cc-aa87-f9a47eb84ac5">

Might try a simple fix. But this would modify the select styling generally, and I am not familiar enough with the codebase to know every place it's used exactly and if that flex was meant for future use. Feel free to reject with something better :)

**Comment by ovflowd** [comment]
> > also padding left will trunk the long titles. No ?
> 
> It seems the truncation is not working correctly already. A lot of titles are cut off. I looked a bit at the styles, and it seems the `truncate` class is applied to the wrapping `.dropdown .item`. But at the same time, there is additional styling on `.text span`. This sets the span as `display: flex` and with that currently disables the truncation completely without apparent benefit.
> 
> Current: <img alt="image" width="373" src="https://private-user-images.githubusercontent.com/15133101/309508410-0e2561a8-ccdc-431f-afc6-763f92a984f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MjY1NjAsIm5iZiI6MTcwOTQyNjI2MCwicGF0aCI6Ii8xNTEzMzEwMS8zMDk1MDg0MTAtMGUyNTYxYTgtY2NkYy00MzFmLWFmYzYtNzYzZjkyYTk4NGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDAwMzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNDQ2MDAyZDM1ZmE4YjNlYmFjMTMwNWRiYjI1Y2ZjZDUxNDQ1YjE1NzgxZGYwOGYxNDY3NTRiZWM0NjVmOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5TO2GrQTv95AdUvVZ_OpXiPJMme_RnYM5f9uQEHhEbo">
> 
> Flex removed: <img alt="image" width="355" src="https://private-user-images.githubusercontent.com/15133101/309508367-3e034797-ad62-42cc-aa87-f9a47eb84ac5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MjY1NjAsIm5iZiI6MTcwOTQyNjI2MCwicGF0aCI6Ii8xNTEzMzEwMS8zMDk1MDgzNjctM2UwMzQ3OTctYWQ2Mi00MmNjLWFhODctZjlhNDdlYjg0YWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDAwMzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxN2FkY2JiNDA4N2IwNjczZWE2YTI5MDQ3ODNlYzhiMzgxOTA0NWJmNDJlYThiNzlkYzc0OTVmYWE1OGJkMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mtfyx8IjQ0-qjzpMhs02ckAOZI3B8Cd7kE9VgUbo-vY">
> 
> Might try a simple fix. But this would modify the select styling generally, and I am not familiar enough with the codebase to know every place it's used exactly and if that flex was meant for future use. Feel free to reject with something better :)

Feel free to make a PR, I believe everything you need to read is available on the Collaborator Guide, and I can point you to the right components if needed.

**Comment by mojitane** [comment]
Created a PR here to quickly show the relevant styling #6410.

It does fix the issue of truncation and adds some spacing. There are some questions and possible improvements though I have mentioned in the PR.
