### ISSUE TITLE
Privacy Policy footer link goes to 404 page

### ISSUE THREAD

**Issue by jenewland1999** [nodejs/nodejs.org#6401]
### URL:

https://beta-node-js-org.vercel.app/en

### Browser Name:

Chrome

### Browser Version:

122.0.6261.94

### Operating System:

macOS 14.3.1

### How to reproduce the issue:

1. Went to the new beta Node.js website https://beta-node-js-org.vercel.app/en
2. Clicked the "Privacy Policy" link in the footer
3. Expected it to take me to https://images.prismic.io/openjsf/ba00b254-685f-4e54-b1ca-17984b0f3e55_OpenJS-Foundation-Privacy-Policy-2019-11-15.pdf
4. Instead it takes me to https://openjsf.org/wp-content/uploads/sites/84/2021/04/OpenJS-Foundation-Privacy-Policy-2019-11-15.pdf

**Comment by AugustinMauroy** [comment]
`https://privacy-policy.openjsf.org/` it's correct link to put

**Comment by MohitKambli** [comment]
Hello,
I would like to work on this issue.

Thanks and Regards,
Mohit Kambli
