### ISSUE TITLE
OpenJS Foundation Slack link in Footer is invalid

### ISSUE THREAD

**Issue by jenewland1999** [nodejs/nodejs.org#6403]
### URL:

https://beta-node-js-org.vercel.app/en

### Browser Name:

Chrome

### Browser Version:

122.0.6261.94

### Operating System:

macOS 14.3.1

### How to reproduce the issue:

1. Went to the new beta Node.js website https://beta-node-js-org.vercel.app/en
2. Clicked the Slack logo link in the footer
3. Expected it to take me to OpenJS Foundation Slack
4. Instead it goes to the Slack invalid link page (screenshot below)

<img width="1512" alt="image" src="https://github.com/nodejs/nodejs.org/assets/34895363/91bd192d-a572-45dd-9cb8-771263928a54">

**Comment by ovflowd** [comment]
This is not an issue. We temporarily closed our Slack due to moderation reasons. We will reopne our Slack ton the public later this week. Thank you!
