### ISSUE TITLE
Version dropdown on download page doesn't scroll on overflow

### ISSUE THREAD

**Issue by jenewland1999** [nodejs/nodejs.org#6404]
### URL:

https://beta-node-js-org.vercel.app/en/download

### Browser Name:

Chrome

### Browser Version:

122.0.6261.94

### Operating System:

macOS 14.3.1

### How to reproduce the issue:

1. Went to the new beta Node.js website's download page https://beta-node-js-org.vercel.app/en/download
2. Clicked the version dropdown (also known as a combobox or select)
3. Expected it to be scrollable if the complete list cannot be shown within the visible viewport
4. Instead, the overflow is hidden and thus means I cannot see the full list unless I zoom out.

<img width="1512" alt="image" src="https://github.com/nodejs/nodejs.org/assets/34895363/bb7f9c9b-3aa2-4ff7-846e-3c75fd42db7c" />

**Comment by ovflowd** [comment]
That's odd! There should be a maximum height. I assume that is doable with https://www.radix-ui.com/primitives/docs/components/select following the docs of the component we use.

**Comment by MohitKambli** [comment]
Hello,
I would like to work on this issue.

Thanks and Regards,
Mohit Kambli

**Comment by MohitKambli** [comment]
Hello,
Hope you're doing well.
I have implemented the possible code changes and raised a PR for the same.
If at all there are any changes required from my end, then do let me know.
Sincere apologies if I made any mistakes while implementing the code changes or raising a PR for the same.
Hope the code changes help in meeting the requirement.

Thanks and Regards,
Mohit Kambli
