### ISSUE TITLE
The "events" category link on the blog 

### ISSUE THREAD

**Issue by jenewland1999** [nodejs/nodejs.org#6407]
### URL:

https://beta-node-js-org.vercel.app/en/blog

### Browser Name:

Chrome

### Browser Version:

122.0.6261.94

### Operating System:

macOS 14.3.1

### How to reproduce the issue:

1. Went to the new beta Node.js website - specifically the blog route https://beta-node-js-org.vercel.app/en/blog
2. Clicked the "Events" category link
3. Expected it to show me blog posts related to events
4. Instead, it shows a 404 page

If a page isn't currently available for this, then perhaps worth removing the link until such time it is, or link to https://beta-node-js-org.vercel.app/en/about/get-involved/events

**Comment by Nyx1on** [comment]
No blogs available in events folder yet.

**Comment by bmuenzenmeyer** [comment]
closed via #6408
