### ISSUE TITLE
Learn menu items is unwrapped causing some text to be hidden

### ISSUE THREAD

**Issue by rluvaton** [nodejs/nodejs.org#6412]
### URL:

https://beta-node-js-org.vercel.app/en/learn

### Browser Name:

Safari

### Browser Version:

Good question 

### Operating System:

iOS 17

### How to reproduce the issue:

https://github.com/nodejs/nodejs.org/assets/16746759/0a32a25f-e109-4c24-8922-42df0b7cefc8

**Comment by AugustinMauroy** [comment]
Sorry I don't get your issue. Could you elaborate for example, by proposing a solution.

**Comment by rluvaton** [comment]
Wrapping the text
<img width="360" alt="image" src="https://github.com/nodejs/nodejs.org/assets/16746759/2a4ccbb5-e6b6-45cb-b137-e89b013e7d41">

**Comment by ovflowd** [comment]
I assume https://github.com/nodejs/nodejs.org/pull/6410 fixes this issue?

**Comment by AugustinMauroy** [comment]
> I assume https://github.com/nodejs/nodejs.org/pull/6410 fixes this issue?

for me it's close to if someone thinks that a line return is better than trunck.

**Comment by rluvaton** [comment]
The issue has been solved, i would prefer new line but this can be close to avoid overwhelming issues
