### ISSUE TITLE
Navigation Panel Issue

### ISSUE THREAD

**Issue by Nyaughh** [nodejs/nodejs.org#6416]
https://github.com/nodejs/nodejs.org/assets/110736557/3a18d5bc-5cf2-41f6-b5e6-3ed2cae35b26

When you click on the navigation bar, it increases the size of the page
(I'm using Brave here but it's the same for chrome too)

**Comment by mwenku** [comment]
Hey @Nyaughh what's your screen size? i tried it on my phone(1080px × 2280px) it works fine. and doesn't zoom in when i open the menu

**Comment by Nyaughh** [comment]
> Hey @Nyaughh what's your screen size? i tried it on my phone(1080px × 2280px) it works fine. and doesn't zoom in when i open the menu

Almost the same as yours, 1080×2400

**Comment by mwenku** [comment]
i was unable to replicate this issue, in chrome, brave, desktop with your exact screen dimentions? anyone else having the same issue ?

**Comment by manishprivet** [comment]
https://github.com/nodejs/nodejs.org/blob/5380385e456f718648d9be3b8e2a69e0deb31224/next.dynamic.constants.mjs#L93

We should probably add `maximumScale: 1` here I was able to replicate this on a pixel 3

**Comment by ovflowd** [comment]
> https://github.com/nodejs/nodejs.org/blob/5380385e456f718648d9be3b8e2a69e0deb31224/next.dynamic.constants.mjs#L93
> 
> We should probably add `maximumScale: 1` here I was able to replicate this on a pixel 3

Feel free to make a PR

**Comment by manishprivet** [comment]
Sorry about the accidental close

**Comment by mwenku** [comment]
> https://github.com/nodejs/nodejs.org/blob/5380385e456f718648d9be3b8e2a69e0deb31224/next.dynamic.constants.mjs#L93
> 
> We should probably add `maximumScale: 1` here I was able to replicate this on a pixel 3

thanks @manishprivet i tried it on a pixel 4 but looked fine. thanks for the pr. learnt something new today 😊
