### ISSUE TITLE
Link to next-intl is missing in Collaborator Guide

### ISSUE THREAD

**Issue by trivikr** [nodejs/nodejs.org#6424]
## Describe the bug
Link to next-intl is missing in Collaborator Guide

## Steps to reproduce
View [Technologies used in the Website section](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) of the Collaborator Guide

#### Observed behavior
Link to next-intl is missing

#### Expected behavior
next-intl is clickable with respective link

#### Screenshots

<details>
<summary>Details</summary>

<img width="823" alt="Screenshot 2024-03-03 at 8 49 32 PM" src="https://github.com/nodejs/nodejs.org/assets/16024985/0375fbd0-a34d-4aa7-a7e3-5d4ead6a9cb7">

</details>

## Additional context
Possibly missed in commit https://github.com/nodejs/nodejs.org/commit/f32ce2343cf35ef744e1d6380e9159471676277b

**Comment by mahmudhmh** [comment]
I fixed this at #6426 
added also some fixes to broken links I saw at the collaborator guide
