### ISSUE TITLE
The location of the search box seems inappropriate

### ISSUE THREAD

**Issue by lopo12123** [nodejs/nodejs.org#6427]
### URL:

https://beta-node-js-org.vercel.app/en

### Browser Name:

Chrome

### Browser Version:

122.0.6261.94

### Operating System:

windows 11

### How to reproduce the issue:

I found that the position of the main body of the search box is "top: 15rem", but this causes it to be positioned lower on the laptop and the bottom is obscured

![image](https://github.com/nodejs/nodejs.org/assets/59609929/074cbed9-aee0-40b8-b773-0ce81bb7b2c1)

full screen
![image](https://github.com/nodejs/nodejs.org/assets/59609929/19c11390-716f-437c-b922-49d4fd1a281b)

Not full screen (In this state I cannot scroll to the lower part)
![image](https://github.com/nodejs/nodejs.org/assets/59609929/365ec0aa-24ec-48c8-84b7-0e3faeea7e6d)

**Comment by marwan-mohamed12** [comment]
@lopo12123 I've fixed the issue #6428, Could you please review the PR?
![Screenshot 2024-03-04 122659](https://github.com/nodejs/nodejs.org/assets/40841193/593295d6-87bc-45a3-96c3-d9335f749058)

**Comment by AugustinMauroy** [comment]
fix on #6428
