### ISSUE TITLE
The homepage style is different in different browsers

### ISSUE THREAD

**Issue by G-WangZH** [nodejs/nodejs.org#6430]
### URL:

https://beta-node-js-org.vercel.app/en

### Browser Name:

chome、safari

### Browser Version:

chome：122.0.6261.94，safari：版本16.6

### Operating System:

macbook pro，13-inch, M1, 2020

### How to reproduce the issue:

The homepage style is different in different browsers.
chrome：
<img width="1412" alt="image" src="https://github.com/nodejs/nodejs.org/assets/24827526/0a6b72dc-35e8-4429-92d2-70df664fb02d">

safari：
<img width="1422" alt="image" src="https://github.com/nodejs/nodejs.org/assets/24827526/9090af59-8274-4402-96a4-e6f130f586a9">

**Comment by AugustinMauroy** [comment]
Hi, sadly we cannot do something. Why it's different on safari? It's just how WebKit handle blur. 

If someone have idea to solve safari rendering. It's will be perfect.

**Comment by ovflowd** [comment]
Unfortunately, indeed, it's not something we can handle, as it might as well be an issue on WebKit. It's also such a small detail that I wouldn't consider it a bug.

Closing as "won't fix"
