### ISSUE TITLE
feat(download): link on bottom of page have white icon

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/nodejs.org#6440]
## Problem

On bottom https://beta-node-js-org.vercel.app/en/download/source-code of we have link with small icon like you can see on dark theme. But on light theme we didn't see the icon.

**Dark Theme :**

<img width="837" alt="Capture d’écran 2024-03-05 à 13 20 56" src="https://github.com/nodejs/nodejs.org/assets/97875033/97fa613c-38d3-4813-b1be-de8f800584a5">

**Light Theme :**

<img width="837" alt="Capture d’écran 2024-03-05 à 13 22 23" src="https://github.com/nodejs/nodejs.org/assets/97875033/5e35a513-b535-43d7-8c42-b21b2b12b32f">

## How to solve ?

Just add dark color for light theme. Also other things to do on this component is use module-css instead of inline tailwindcss.

[this](https://github.com/nodejs/nodejs.org/blob/main/components/Downloads/Release/LinkWithArrow.tsx#L14) is  the file concerned

**Comment by themujahidkhan** [comment]
I would like to work on it, can you assign it to me?
