### ISSUE TITLE
Redesign suggests all versions of Node.js include corepack

### ISSUE THREAD

**Issue by richardlau** [nodejs/nodejs.org#6441]
### URL:

https://nodejs-org-git-meta-remove-legacy-website-code-openjs.vercel.app/en/download

### Browser Name:

Firefox

### Browser Version:

115.8.0

### Operating System:

Windows 11

### How to reproduce the issue:

In the redesign it looks like the download page unconditionally includes the string "and corepack":
https://github.com/nodejs/nodejs.org/blob/0e15186fde66f5972357f427c7e5bffb213c2c69/pages/en/download/package-manager/current.mdx#L14

This means the string is always present, even if you select a really old version of Node.js e.g. v8.17.0.

AFAIK there is currently no quick way of determining if an arbitrary release of Node.js includes corepack short of looking at the source for the version or unpacking one of the archives. Corepack is not indexed in `index.json`/`index.tab` and is unlikely to be while it is experimental.

**Comment by richardlau** [comment]
![image](https://github.com/nodejs/nodejs.org/assets/5445507/5fc6435d-01a6-45fd-b4a4-c78841139e88)

**Comment by AugustinMauroy** [comment]
There are a ways to know which version of Corepack is ship or not ship with nodejs ? Like for npm version.

**Comment by ovflowd** [comment]
> There are a ways to know which version of Corepack is ship or not ship with nodejs ? Like for npm version.

Apparently not. @richardlau, when was Corepack introduced? We can make an if statement to not render this to versions it is known for not being supported. Or should we remove the mention from corepack in the meanwhile until the TSC has an agreement on whether we should or should not have it there? Cc @nodejs/tsc

**Comment by richardlau** [comment]
> > There are a ways to know which version of Corepack is ship or not ship with nodejs ? Like for npm version.
> 
> Apparently not. @richardlau, when was Corepack introduced? We can make an if statement to not render this to versions it is known for not being supported. Or should we remove the mention from corepack in the meanwhile until the TSC has an agreement on whether we should or should not have it there? Cc @nodejs/tsc

According to the links from https://github.com/nodejs/node/pull/39608 16.9.0 and 14.9.0. It's not available in any version of Node.js 13.x and below.
I'd prefer not to mention it until its future is decided. The pre-redesign website doesn't mention it.

**Comment by mhdawson** [comment]
> I'd prefer not to mention it until its future is decided

Thats my preference as well.

**Comment by ovflowd** [comment]
cc @nodejs/nodejs-website feel free to make a PR (or @ruyadorno) cc @nodejs/tsc for awareness.

**Comment by ruyadorno** [comment]
Sorry I was OOO this week and I could not follow up with the conversation on #6396. @ovflowd  feel free to either reopen that PR or open a new one please. 😊

**Comment by ovflowd** [comment]
I've removed the Corepack mention for the time being, until the TSC decides the future of Corepack.
