### ISSUE TITLE
Redesign is missing "Additional Platforms"

### ISSUE THREAD

**Issue by richardlau** [nodejs/nodejs.org#6479]
### URL:

https://nodejs.org/en/download

### Browser Name:

Firefox

### Browser Version:

115.9.0esr

### Operating System:

Windows 11, 22H2, Build 22621.3155

### How to reproduce the issue:

Compared to the pre-redesign, https://web.archive.org/web/20240301012624/https://nodejs.org/en/download/, the redesigned https://nodejs.org/en/download appears to have no way to get to the "Additional Platforms" for Docker images or AIX, i.e. the first and last options in:

![image](https://github.com/nodejs/nodejs.org/assets/5445507/9a65b0cf-2567-49ce-a587-c956895ef47c)

**Comment by bmuenzenmeyer** [comment]
This seems to ring a bell in my mind somewhere, especially Docker. I'll poke around to see if there was a decision somewhere.

**Comment by ovflowd** [comment]
> Compared to the pre-redesign, [web.archive.org/web/20240301012624/https://nodejs.org/en/download](https://web.archive.org/web/20240301012624/https://nodejs.org/en/download/), the redesigned [nodejs.org/en/download](https://nodejs.org/en/download) appears to have no way to get to the "Additional Platforms" for Docker images or AIX, i.e. the first and last options in:

That's incorrect. They are on the "Prebuilt Binaries" page :)

**Comment by ovflowd** [comment]
And Docker is available on the "Package Managers" page 👀

**Comment by richardlau** [comment]
> > Compared to the pre-redesign, [web.archive.org/web/20240301012624/https://nodejs.org/en/download](https://web.archive.org/web/20240301012624/https://nodejs.org/en/download/), the redesigned [nodejs.org/en/download](https://nodejs.org/en/download) appears to have no way to get to the "Additional Platforms" for Docker images or AIX, i.e. the first and last options in:
> 
> That's incorrect. They are on the "Prebuilt Binaries" page :)

Where? I don't see them.

**Comment by ovflowd** [comment]
![image](https://github.com/nodejs/nodejs.org/assets/12037269/7a6398fa-ec85-4138-a61a-8ea0e9ef50ac)

![image](https://github.com/nodejs/nodejs.org/assets/12037269/6a9282bf-4458-4d55-b84a-c9aa2851de15)

**Comment by richardlau** [comment]
> And Docker is available on the "Package Managers" page 👀

Not selectable:
![image](https://github.com/nodejs/nodejs.org/assets/5445507/c4b23b73-8afe-4013-adaf-cfa26a2d688d)

**Comment by ovflowd** [comment]
> > And Docker is available on the "Package Managers" page 👀
> 
> Not selectable: ![image](https://private-user-images.githubusercontent.com/5445507/314202124-c4b23b73-8afe-4013-adaf-cfa26a2d688d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NzY4MzAsIm5iZiI6MTcxMDg3NjUzMCwicGF0aCI6Ii81NDQ1NTA3LzMxNDIwMjEyNC1jNGIyM2I3My04YWZlLTQwMTMtYWRhZi1jZmEyNmEyZDY4OGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMTkyODUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGZhNWFhYjZiMTlkZGI1MjA4NTJmMjY1ODliNTk4OGU0MmJiOGM3MTVjZTIyZmZjY2Q4NGQzMmY3MTAyZmE5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tGUV9OtgQq7BuivUgOdtkbUl-w8FX0c58WHJpvowBas)

Yes, not for Linux. Because there's not a streamlined way to install Docker on Linux, it varies per distro.

**Comment by richardlau** [comment]
> ![image](https://private-user-images.githubusercontent.com/12037269/314202174-7a6398fa-ec85-4138-a61a-8ea0e9ef50ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NzY4NDcsIm5iZiI6MTcxMDg3NjU0NywicGF0aCI6Ii8xMjAzNzI2OS8zMTQyMDIxNzQtN2E2Mzk4ZmEtZWM4NS00MTM4LWE2MWEtOGVhMGU5ZWY1MGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE5MjkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ODVkZDdjMWE4YmUwOTdmZmY0YjJkNGI1M2FjOWU0NWVlNzUzMDIwOGQwYzc5Zjg1OThlM2YzYWIxMDk0NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.veNBLOTfJKDmYpbWU2bhuYJqM5vCyoQGWvCnwt3tiN0)
> 
> ![image](https://private-user-images.githubusercontent.com/12037269/314202340-6a9282bf-4458-4d55-b84a-c9aa2851de15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NzY4NDcsIm5iZiI6MTcxMDg3NjU0NywicGF0aCI6Ii8xMjAzNzI2OS8zMTQyMDIzNDAtNmE5MjgyYmYtNDQ1OC00ZDU1LWI4NGEtYzlhYTI4NTFkZTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE5MjkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ODZlYjgzZmY0YjY1MGRiYTFjZjc4ZGUwMjEzNTI0OWQ2OTFkZDZjZmNmMDQxNDY5NDM2ZGYzMDBhNzc0OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u8EkgOI20bBlC1elt5wTzh1K--11wbQWP5avWyQaCzI)

AIX is not in that list.

**Comment by ovflowd** [comment]
> > ![image](https://private-user-images.githubusercontent.com/12037269/314202174-7a6398fa-ec85-4138-a61a-8ea0e9ef50ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NzY4NDcsIm5iZiI6MTcxMDg3NjU0NywicGF0aCI6Ii8xMjAzNzI2OS8zMTQyMDIxNzQtN2E2Mzk4ZmEtZWM4NS00MTM4LWE2MWEtOGVhMGU5ZWY1MGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE5MjkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ODVkZDdjMWE4YmUwOTdmZmY0YjJkNGI1M2FjOWU0NWVlNzUzMDIwOGQwYzc5Zjg1OThlM2YzYWIxMDk0NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.veNBLOTfJKDmYpbWU2bhuYJqM5vCyoQGWvCnwt3tiN0)
> > ![image](https://private-user-images.githubusercontent.com/12037269/314202340-6a9282bf-4458-4d55-b84a-c9aa2851de15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NzY4NDcsIm5iZiI6MTcxMDg3NjU0NywicGF0aCI6Ii8xMjAzNzI2OS8zMTQyMDIzNDAtNmE5MjgyYmYtNDQ1OC00ZDU1LWI4NGEtYzlhYTI4NTFkZTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE5MjkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ODZlYjgzZmY0YjY1MGRiYTFjZjc4ZGUwMjEzNTI0OWQ2OTFkZDZjZmNmMDQxNDY5NDM2ZGYzMDBhNzc0OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u8EkgOI20bBlC1elt5wTzh1K--11wbQWP5avWyQaCzI)
> 
> AIX is not in that list.

Is it relevant for have AIX?

**Comment by richardlau** [comment]
It's an officially supported platform.

**Comment by ovflowd** [comment]
> It's an officially supported platform.

I'll make a PR then.

**Comment by ovflowd** [comment]
cc @nodejs/nodejs-website can someone take care of adding AIX as an option again? Unfortunately I'm a bit out of availability these days!

**Comment by mhdawson** [comment]
@ovflowd in terms of docker I don't think we need to tell people how to install docker, but it is valuable show how to use the containers(or at least the names of the docker containers) which run across all platforms. For platforms other than MacOs I would just show the docker pull and later lines.

**Comment by mhdawson** [comment]
Also longer term I'm not sure package manager is the right place. It may make sense to have a "docker" tab along with Prebuilt Binaries and Package Manager. From the stats I look at there are >200M docker pulls a quarter so its a signicant way people use node

**Comment by ovflowd** [comment]
> @ovflowd in terms of docker I don't think we need to tell people how to install docker, but it is valuable show how to use the containers(or at least the names of the docker containers) which run across all platforms. For platforms other than MacOs I would just show the docker pull and later lines.

The reasoning behind that decision was as if we only have the snippets of the `docker` commands, people would try to copy paste those commands and they would not run at all if they don't have Docker.

But if we're okay with that, I can definitely remove the Docker install steps, and then make the command also available through Linux platform option.

**Comment by ovflowd** [comment]
> Also longer term I'm not sure package manager is the right place. It may make sense to have a "docker" tab along with Prebuilt Binaries and Package Manager. From the stats I look at there are >200M docker pulls a quarter so its a signicant way people use node

Well it's not like people will manually download the Docker image. They will only ever use it through the `docker` CLI. And that in its own is a form of "package management" as docker images are "packages"

**Comment by mhdawson** [comment]
> But if we're okay with that, I can definitely remove the Docker install steps, and then make the command also available through Linux platform option.

What I meant is to leave as is for MacOS, but for platforms where we can't have easy docker instructions just leave out the install part, or maybe have a comment that says install docker and then the part that references the containers.

**Comment by ovflowd** [comment]
> as is for MacOS, but for platforms where we can't have easy docker instructions just leave out the install part, or maybe have a comment that says install docker and then the part that

I will come up with something for this. Thanks for the feedback!
