### ISSUE TITLE
The new website is missing prominent display of the new project mascot

### ISSUE THREAD

**Issue by wesleytodd** [nodejs/nodejs.org#6480]
### URL:

https://nodejs.org/en

### Browser Name:

All Browsers

### Browser Version:

All Versions

### Operating System:

All OSs

### How to reproduce the issue:

https://nodejs.org/en/about/branding is the only place I could find it.

We need more rocket turtle!

**Comment by bmuenzenmeyer** [comment]
ope - it used to be on about - but didn't get ported to the new site

**Comment by ovflowd** [comment]
> ope - it used to be on about - but didn't get ported to the new site

Yes, we got feedback that on the /about page it was not a good place

**Comment by bmuenzenmeyer** [comment]
oh, i was about to add it

**Comment by AugustinMauroy** [comment]
We can't put it on a content page because that would take up unnecessary space. But we could try to find something cool like a 404 page.  Or a little more "easter egg" on the last page of the plog post.

**Comment by bmuenzenmeyer** [comment]
for now I've reintroduced the change via https://github.com/nodejs/nodejs.org/pull/6481 - happy to iterate

**Comment by wesleytodd** [comment]
> But we could try to find something cool like a 404 page. Or a little more "easter egg" on the last page of the plog post.

These are all great ideas imo! That said......hear me out.....

Every once in a while when we have an announcement it should pop out of the side of the screen with a speech bubble like clipy. Or maybe just fully jet across the screen once in a while for fun.

**Comment by darcyclarke** [comment]
Much ❤️ to the recent redesign. I'm Just going to leave these here & feel free to poke me if you want a PR with any/all of these (can animate as well if we want) 👀

<img width="2054" alt="Screenshot 2024-03-19 at 7 00 25 PM" src="https://github.com/nodejs/nodejs.org/assets/459713/81efc3bc-9f2b-4517-a27c-df43d905665a">
<img width="2054" alt="Screenshot 2024-03-19 at 7 06 37 PM" src="https://github.com/nodejs/nodejs.org/assets/459713/801320b9-ad2b-460d-9067-33027d011106">
<img width="2001" alt="Screenshot 2024-03-19 at 7 09 09 PM" src="https://github.com/nodejs/nodejs.org/assets/459713/dddf1cac-3e1b-4550-9985-2ffaea16a3b1">

**Comment by darcyclarke** [comment]
I made the turtle surf...

- PR: https://github.com/nodejs/nodejs.org/pull/6492
- Preview: https://nodejs-org-git-fork-darcyclarke-darcyclarke-make-80ed19-openjs.vercel.app/en

**Comment by bnb** [comment]
not gonna lie, the aesthetic of the mascot doesn't fit in with the site and IMO probably shouldn't be statically featured prominently ¯\\_(ツ)\_/¯

Down for 404, that seems like a good place!

**Comment by kyliewd** [comment]
chiming in - i agree with @bnb. 404 is a good solution for now. Maybe in the future when we have announcements or similar we can add Rocket Turtle in the corner like Clippy (love that @wesleytodd)

thanks for including rocket turtle 😄

**Comment by bmuenzenmeyer** [comment]
I pivoted #6481 to the 404. take a look.

- real content is first
- mascot is roughly vertically centered
![image](https://github.com/nodejs/nodejs.org/assets/298435/8f727037-741a-4c4d-b399-820c48670b38)

**Comment by wesleytodd** [comment]
![the new Node js Rocket Turtle Mascot in a jail cell](https://github.com/nodejs/nodejs.org/assets/1027776/531a7b66-0632-4626-a1cd-11644615b5bf)


Thanks for the good work! It might be a ~jail cell~ 404 page but this Turtle has a rocket and dreams of the ~stars~ home page 😄.

**Comment by ovflowd** [comment]
> good work! It might be a ~jail cell~ 404 page but this Turtle has a rocket a

Wes, I love you dude. This made my day

**Comment by wesleytodd** [comment]
I really should have given credit where it is due. The idea is @ljharb's! All I did was ask AI to make the image and wrote the tag line. I am just happy to make you happy @ovflowd. Seriously you all did such great work on the new website, people like it so much now they asking when the docs will get the new look 😎
