### ISSUE TITLE
Offer fnm as an installation option on all platforms

### ISSUE THREAD

**Issue by MattIPv4** [nodejs/nodejs.org#6490]
### Enter your suggestions in details:

[fnm](https://github.com/Schniz/fnm) is a Node version manager (similar to NVM) designed to be fast with full cross-platform support for macOS/Linux/Windows. I think it would be beneficial to add it to the site as an option for folks looking to download/install a Node.js version on any platform.

https://formulae.brew.sh/formula/fnm shows 22k installs in the last year via brew, for some context on usage. https://formulae.brew.sh/formula/nvm sits at 457k installs in the same period.

**Comment by MattIPv4** [comment]
I believe this tangentially relates to nodejs/package-maintenance#591

**Comment by ovflowd** [comment]
@MattIPv4 feel free to open a PR.
