### ISSUE TITLE
Slack link broken

### ISSUE THREAD

**Issue by SociableSteve** [nodejs/nodejs.org#6498]
### URL:

https://nodejs.org/en

### Browser Name:

Arc

### Browser Version:

1.34.0

### Operating System:

Mac OS Sonoma 14.3.1 

### How to reproduce the issue:

1. Clicked the Slack link in the footer on the homepage
2. I expected it to send me to the Slack server for NodeJS
3. I got a message saying that the link is no longer active
4. 
![image](https://github.com/nodejs/nodejs.org/assets/52213009/647bd078-c87c-4642-b45e-c60bd2c6639d)

**Comment by AugustinMauroy** [comment]
for me it's work. It should be because I'm already in the slack.
@ovflowd I know you're in the foundation. Hadn't the invitation been closed temporarily?

**Comment by MattIPv4** [comment]
🤔 Don't Slack invites have an expiry/usage limit? K8s for example uses communityinviter.com to manage allow folks to join whenever (slack.k8s.io).

**Comment by AugustinMauroy** [comment]
I'm sure this link work https://slack-invite.openjsf.org/ because Antoni shew use it to join our slack

**Comment by MattIPv4** [comment]
That link sounds a lot better to put in the footer, as I imagine it is something openjsf maintains, rather than the direct Slack link currently used
