### ISSUE TITLE
Outdated "Previous Releases" Page

### ISSUE THREAD

**Issue by sinansonmez** [nodejs/nodejs.org#6504]
### URL:

https://nodejs.org/en/about/previous-releases#release-schedule

### Browser Name:

not applicable

### Browser Version:

not applicable

### Operating System:

not applicable

### How to reproduce the issue:

The chart is last updated 6 months ago. Do you plan to update it soon?
https://github.com/nodejs/nodejs.org/blob/main/pages/en/about/previous-releases.mdx
https://nodejs.org/en/about/previous-releases#release-schedule

**Comment by ovflowd** [comment]
The chart is not outdated. It's directly sourced from the releases repository. Hence we don't need to update anything on our side.

If you feel this chart is outdated by any means, please open an issue on the nodejs/Release repository :)
