### ISSUE TITLE
Adding dutch (/nl) language support?

### ISSUE THREAD

**Issue by BluntKatana** [nodejs/nodejs.org#6514]
### Enter your suggestions in details:

All routes leading to https://nodejs.org/nl/ currently return a 404 error. 

Before translating most pages I wanted to ask if it is encouraged to create such translation PRs? And if yes, should all pages need to be committed at once, or could it be done incrementally with multiple PRs?

**Comment by OscarNOW** [comment]
The TRANSLATION.md describes how to translate the website into a different language. I don't think Dutch is currently added, so you will probably have to add that first.

**Comment by AugustinMauroy** [comment]
Dutch is available for translation on Crowdin. When there is 100% translation the language will be available on the site.
