### ISSUE TITLE
Improve inactive codebox tab text on light mode

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6527]
Lighthouse is dinging us for poor contrast here 

This is only in light mode

![image](https://github.com/nodejs/nodejs.org/assets/298435/85b57504-9e8f-4c41-9cfc-47c1313fe447)

**Comment by AugustinMauroy** [comment]
in our system design the codebox has a light style, why we don't apply it?
I think the discussion has already taken place but I can't find it.

**Comment by surengalstyan** [comment]
the search input appears to have the same contrast issue too.

<img width="1680" alt="image" src="https://github.com/nodejs/nodejs.org/assets/17316828/2dd9f805-d18e-40c7-80e0-bae45d2baca3">

**Comment by ovflowd** [comment]
> the search input appears to have the same contrast issue too.
> 
> 
> 
> <img width="1680" alt="image" src="https://github.com/nodejs/nodejs.org/assets/17316828/2dd9f805-d18e-40c7-80e0-bae45d2baca3">
> 
> 

I feel that the search input one was intentional, but indeed it does not pass accessibility tests. We should fix it!

**Comment by bmuenzenmeyer** [comment]
> in our system design the codebox has a light style, why we don't apply it?

we decided to only have one. it might have been shikiji-related?

**Comment by AugustinMauroy** [comment]
> we decided to only have one. it might have been shikiji-related?

it would be cool to have both but i'm willing to bet it will increase the bundle size
