### ISSUE TITLE
Missing page

### ISSUE THREAD

**Issue by alyahmedaly** [nodejs/nodejs.org#6549]
### URL:

https://nodejs.dev/learn/nodejs-streams

### Browser Name:

chrome

### Browser Version:

latest

### Operating System:

macos

### How to reproduce the issue:

looks like this page is missing from the new site, maybe redirect to the new link will help

I got this link from react types
```
/**
 * Only available in the environments with [Node.js Streams](https://nodejs.dev/learn/nodejs-streams).
 *
 * @see [API](https://reactjs.org/docs/react-dom-server.html#rendertopipeablestream)
 *
 * @param children
 * @param options
 */
export function renderToPipeableStream(children: ReactNode, options?: RenderToPipeableStreamOptions): PipeableStream;
```

**Comment by AugustinMauroy** [comment]
that an issue of React type. Also strange link because on nodejs.dev there are nos learn ressource about stream.

**Comment by thisalihassan** [comment]
@AugustinMauroy @alyahmedaly maybe we can replace the link with https://nodejs.org/api/stream.html#stream
??

**Comment by bmuenzenmeyer** [comment]
here's the content, perhaps https://web.archive.org/web/20210413020915/https://nodejs.dev/learn/nodejs-streams

**Comment by ovflowd** [comment]
Well, nodejs.dev is not in this repository. That website was removed/archived a while ago.

This is not a bug from our side, nothing really to do here. The relevant React Type docs should be updated.

**Comment by AugustinMauroy** [comment]
note we have a page look similar in content https://nodejs.org/en/learn/modules/backpressuring-in-streams
