### ISSUE TITLE
Add internationalization for Hebrew speakers (/he)

### ISSUE THREAD

**Issue by EtanHey** [nodejs/nodejs.org#6551]
### Enter your suggestions in details:

1. going to [https://nodejs.org/he/](url) and seeing the page load in hebrew.
2. leads to 404 page could not be found.
3. I will translate it.

**Comment by bmuenzenmeyer** [comment]
Hi @EtanHey thanks!

you can add the config for Hebrew by adapting a PR like this https://github.com/nodejs/nodejs.org/pull/6544

**Comment by AugustinMauroy** [comment]
<img width="873" alt="Capture d’écran 2024-06-20 à 18 11 36" src="https://github.com/nodejs/nodejs.org/assets/97875033/26133673-f2b2-4bea-b0b3-3b1272aee45c">

Hebrew is ready for the translation. I invite you to join the crowdin.
