### ISSUE TITLE
RSS alternate link tag does not expose release/vuln feeds

### ISSUE THREAD

**Issue by MattIPv4** [nodejs/nodejs.org#6559]
### URL:

https://nodejs.org/en/blog/release

### Browser Name:

Firefox

### Browser Version:

124.0b9 (64-bit)

### Operating System:

macOS 14.3.1 (23D60)

### How to reproduce the issue:

Observe `application/rss+xml` alternate link tag in `head`. Should be `https://nodejs.org/en/feed/releases.xml`, but is `https://nodejs.org/en/feed/blog.xml`. Same applies to https://nodejs.org/en/blog/vulnerability

**Comment by thisalihassan** [comment]
For all other pages (i.e download, learn etc), the general blog RSS feed (blog.xml) is being used in `application/rss+xml` alternate link tag in `head`
is that correct behavior?

@MattIPv4 @AugustinMauroy
