### ISSUE TITLE
Strange behavior of drop-down menu on download page

### ISSUE THREAD

**Issue by kujo205** [nodejs/nodejs.org#6560]
### URL:

https://nodejs.org/en/download

### Browser Name:

Chrome

### Browser Version:

123.0.6312.40

### Operating System:

Android 14

### How to reproduce the issue:

1. Go to downloads page
2. Click categories drop-down
3. See the visual bug
![Screenshot_20240326-211310](https://github.com/nodejs/nodejs.org/assets/86970828/62d6607b-4b5a-4e94-96b2-5ae9f747c3b3)

**Comment by medmor** [comment]
Hi
If you mean the popover behavior, then I think this behavior is implemented in [radix select component](https://www.radix-ui.com/primitives/docs/components/select).

The code source responsible for this behavior is [here](https://github.com/nodejs/nodejs.org/blob/main/components/Common/Select/index.tsx)

```
          <SelectPrimitive.Content
            position={inline ? 'popper' : 'item-aligned'}
            className={classNames(styles.dropdown, { [styles.inline]: inline })}
          >
```

They can force `item-aligned` to mimic the normal HTML select behavior.

**Comment by ovflowd** [comment]
This issue got fixed, closing!
