### ISSUE TITLE
Language En To Bn Converting

### ISSUE THREAD

**Issue by devlopersabbir** [nodejs/nodejs.org#6561]
### Enter your suggestions in details:

Can anyone give me any hint on how can I start to converting English to Bengali?? 

**I mean**
`https://nodejs.org/en` to `https://nodejs.org/bn`

**Comment by AugustinMauroy** [comment]
read [translation.md](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md) and tell me if you have question. It's should give answer to you question
