### ISSUE TITLE
Enable Hindi Language Support

### ISSUE THREAD

**Issue by G-nizam-A** [nodejs/nodejs.org#6570]
## 1. What I Expected to Happen:

I expected the application to support the Hindi language so that users can view content and interact with the interface in Hindi when they select the Hindi language option.

## 2. Your Reason:
Providing language support for Hindi allows users who prefer to use Hindi as their primary language to access and understand the content of the application more effectively. It enhances user experience and makes the application more accessible to a wider audience, including Hindi-speaking users.

## 3. What I Want to Do:

I want to enable Hindi language support by implementing functionality that loads Hindi translations dynamically when the user selects Hindi as their preferred language. This involves updating the codebase to include the necessary logic for language selection and loading the corresponding translation files for Hindi. Additionally, I plan to ensure that the application's user interface elements, such as buttons, labels, and messages, are appropriately localized in Hindi.

**Comment by AugustinMauroy** [comment]
duplicate as #6508
