### ISSUE TITLE
Add author image to blog posts

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/nodejs.org#6573]
### Enter your suggestions in details:

Instead of the initials of each author, could we use the GitHub image for each author?

<img width="845" alt="image" src="https://github.com/nodejs/nodejs.org/assets/26234614/63a10b21-24e7-467a-bf55-99576d02f948">

**Comment by AugustinMauroy** [comment]
[litle bits of context](https://github.com/nodejs/nodejs.org/blob/b6929e181d6f48ddab0408f4da52c387dfbb5b4e/util/blogUtils.ts#L16-L18)

But I'm more in favor of having GitHub username in frontMatter. So IMHO, the pr should update `blogUtils` to use `getGitHubAvatarUrl`. and update markdown frontMatter
