### ISSUE TITLE
Confusing Error Message

### ISSUE THREAD

**Issue by marcocbn** [nodejs/nodejs.org#6576]
### Enter your suggestions in details:

I use Linux and I want to create a temporary folder outside the application folder.

when I want to run the application, an error appears about "root-owned files". after I checked, there are no files or folders owned by root. It turns out there is a folder that cannot be created. There should be a message showing that you cannot create a file or folder.

<img width="1262" alt="image" src="https://github.com/nodejs/nodejs.org/assets/165233220/223f1558-1800-4422-a162-24d37b0033fa">

**Comment by mikeesto** [comment]
Hi there @marcocbn . This is the issue tracker for the [Node.js website](https://nodejs.org/). This issue isn't related to the website so I'm going to close it.
