### ISSUE TITLE
<details>

### ISSUE THREAD

**Issue by Eianaftyio** [nodejs/nodejs.org#6582]
<details>
  <summary>Premise (Outdated)</summary>
  
	Much work through these last years was done on the https://github.com/nodejs/nodejs.dev repository. From drafting the new design from [this](https://www.figma.com/file/lOxAGGg5KXb6nwie7zXkz6/NJ---Design-System) Figma, to implementation of the pages, curation of what should be the content of the new website, and much more. 
	
	These last months have been incredibly important; with fascinating work being pushed through the edge of this open-source furnace, we finally finished the main goals and features of the Website Redesign Initiative.
	
	This allowed us to focus on migrating the Node.js Website (this very own repository) [into a modern Framework](https://github.com/nodejs/nodejs.org/issues/4958) that would also be compatible with the work we've done on the `nodejs.dev` repository. These changes were the foundational milestone allowing us to adopt the content, design and feature set from https://nodejs.dev.
	
	But what's next? This discussion aims to highlight what the Website Team is coordinating to get done and how we want to make these changes transparent and allow the inner and outer community to contribute, As one of our core goals is to improve the Developer Experience and allow more people to be able to contribute towards the Node.js Website.
  
</details>

# Node.js Website Redesign

#### A quick preamble

Hey y'all 👋 we're currently in the process of redesigning the Node.js Website. This multi-year effort has evolved from many previous efforts (for the curious ones: The Node.js Website Redesign Initiative, The `nodejs.dev` repository, and others).

This process has brought a lot of technical refactoring, restructuring of the Website Repository, and change of technologies used. This has been a long process, but to keep the new contributors short, most of the historical information is available on the hidden comments, and all the current relevant information is available below and on the non-hidden comments).

## The Effort

The Node.js Website Redesign is the initiative of revamping the current design of the Node.js Website into the newly done [Figma Design](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js).

#### The process consists of 3 main steps: (Creating Components -> Creating Layouts -> Migrating Pages)

Note that Issues regarding the Website Redesign will have a `website redesign` label. Issues that are ready to be worked on will have a `Ready` status.

- Creating React Components that follow the designs and implementation specs from the Figmas.
  - Each Component is described within the Figma on the "Design System" Tab
  - Issues will be created for each Component by the Website Team Maintainers
    - Changes should not be done before these issues get created
    - Issues will describe how the Components should work and the validation process
    - Issues will describe where styles, hooks and other pieces of code should live and any other 3rd party needed information
  - Contributors and Newcomers are free to work on the implementation of these Issues
- Creating the Layouts that will be used for the Pages
  - Layouts will be done following the same process mentioned before
- Pages will be migrated from the [`nodejs.dev/content/`](https://github.com/nodejs/nodejs.dev/tree/main/content) folder into `pages/new` folder
  - The `pages/new` folder is a temporary folder
  - Instructions on how to migrate each page, such as:
    - Filenaming and Extension of each file
    - What should be changed on each migrated page [Markdown Frontmatter](https://daily-dev-tips.com/posts/what-exactly-is-frontmatter/)
    - Which Layout each migrated page should adopt
    - Which pages should not be migrated

#### Then, after this process is done and validated:

- The old pages, styles, components and layouts will be removed
- All pages under `pages/new` will be moved to `pages/`
- Other minor changes such as on `pages/_app.tsx` and `pages/_document.tsx` will be done

Most of the communication of each step will be done before we move to each step, so don't worry!

### Recommended Reading Material

We recommend reading the Contributing and Collaborator Guidelines and the comments below.

---

cc @nodejs/website

_Originally posted by @ovflowd in https://github.com/nodejs/nodejs.org/discussions/5131_

**Comment by AugustinMauroy** [comment]
Why did you repost that ?
