### ISSUE TITLE
Please add a searchbar for optimized searching facility

### ISSUE THREAD

**Issue by mthirumalai2905** [nodejs/nodejs.org#6583]
### Enter your suggestions in details:

Im really facing difficulties in finding specific modules and docs so having a search bar would really easy it 
![Screenshot (250)](https://github.com/nodejs/nodejs.org/assets/98790479/8ea56b51-c80b-4400-9a89-1d535a32dafb)

**Comment by AugustinMauroy** [comment]
Hello hello!
The docs api is going to get a facelift in the same design as the rest. The search component already exists on nodejs.org.

**Comment by jsumners** [comment]
I came here specifically looking to see if this issue had already been raised, and to raise it myself if not. The docs page needs a search field. I'm not going to figure out how to get back to the non-docs portion of the site in order to issue a search term for the docs page and then deal with multiple clicks to get back to the docs site.

**Comment by avivkeller** [comment]
Hi @jsumners! Our beta documentation page, https://nodejs-api-docs-tooling.vercel.app, contains a search bar.

**Comment by jsumners** [comment]
Much better. Ship it :shipit:.

**Comment by ovflowd** [comment]
> Much better. Ship it <img alt=":shipit:" width="20" height="20" src="https://github.githubassets.com/images/icons/emoji/shipit.png">.

We're working on it! Feedback is welcome tho!

**Comment by jsumners** [comment]
From what I saw, I'd rather just have a page of search results than a pop up. But anything is better than the current situation.

**Comment by ovflowd** [comment]
> From what I saw, I'd rather just have a page of search results than a pop up. But anything is better than the current situation.

We had a results page in the past. It got removed eventually. We _could_ add it back tho

**Comment by jsumners** [comment]
The pop up is simply a small view port. It is more difficult to see the results than in a full page.
