### ISSUE TITLE
Homepage LTS link downloads non LTS version

### ISSUE THREAD

**Issue by siimots** [nodejs/nodejs.org#6584]
### URL:

https://nodejs.org/en

### Browser Name:

Microsoft Edge for Business

### Browser Version:

Version 123.0.2420.65 (Official build) (64-bit)

### Operating System:

Windows 10, Version 22H2

### How to reproduce the issue:

Homepage shows and links:

[Download Node.js (LTS)](https://nodejs.org/dist/v21.7.1/node-v21.7.1-x64.msi)
Downloads Node.js v21.7.11 with long-term support. Node.js can also be installed via [package managers](https://nodejs.org/en/download/package-manager).

21.7.11 is not LTS.

![image](https://github.com/nodejs/nodejs.org/assets/7014925/c5fec547-aba3-492d-a410-9dd7f1e1924a)

Also would be nice to show 2 buttons (LTS & Current) like in previous homepage.

**Comment by ovflowd** [comment]
Hmmm, apparently, the latest version was not flagged correctly as "Active". This seems to be due to https://github.com/nodejs/Release/blob/main/schedule.json#L119

cc @nodejs/releasers what should we do? Since the v21 is not marked as "Active" but we also don't have v22 yet, so apparently at the moment, there's no Active Node.js version at all.

**Comment by targos** [comment]
It seems the correct fix is to use the "end" date from the JSON file.

**Comment by ovflowd** [comment]
> It seems the correct fix is to use the "end" date from the JSON file.

End is used to mark end-of-life whilst maintenance to mark when it enters maintenance.

Should we not use the maintenance field for non-LTS versions?

**Comment by targos** [comment]
I don't understand why you would use the maintenance field at all (including for LTS). What we should suggest to download is the most recent version. Maintenance means it will get less updates, but people should still install those updates.

**Comment by ovflowd** [comment]
> I don't understand why you would use the maintenance field at all (including for LTS). What we should suggest to download is the most recent version. Maintenance means it will get less updates, but people should still install those updates.

I see. Let me change our internal logic then.
