### ISSUE TITLE
"Run Javascript Anywhere" invisible when text is selected in dark mode

### ISSUE THREAD

**Issue by rithviknishad** [nodejs/nodejs.org#6585]
### URL:

https://nodejs.org/en

### Browser Name:

Firefox

### Browser Version:

125.0b4 (64-bit)

### Operating System:

Mac OS Sonama 14.4.1

### How to reproduce the issue:

1. Visited https://nodejs.org/en
2. Selected the `Run Javascript Anywhere` h1 text while being in dark mode.
3. Expected to have a readable text when selected

<img width="1440" alt="image" src="https://github.com/nodejs/nodejs.org/assets/25143503/06f8ac05-9e0f-41a8-8922-e8be7fafb0fb">

**Comment by bmuenzenmeyer** [comment]
Additional step - i can only get this to happen if the browser window loses focus. it's odd for sure but reduces the concern ever so slightly to me

**Comment by rithviknishad** [comment]
I'm able to replicate this without the browser window to loose focus.

**Comment by mikolertesx** [comment]
I tested it myself, if you remove this property on the CSS h1 document:
```css
-webkit-text-fill-color: transparent;
```

It starts working again.

**Comment by mikolertesx** [comment]
@rithviknishad Could you test this branch?

https://github.com/nodejs/nodejs.org/pull/6605

**Comment by rithviknishad** [comment]
Yup! Works as expected!
