### ISSUE TITLE
The menu links on some 404 pages is incorrect

### ISSUE THREAD

**Issue by azu** [nodejs/nodejs.org#6608]
### URL:

https://nodejs.org/es/download/

### Browser Name:

Chrome

### Browser Version:

125.0.6382.3

### Operating System:

macOS

### How to reproduce the issue:

1. Visit https://nodejs.org/es/download/
2. Show 404 page
3. Click "Download" link of menu
4. Show https://nodejs.org/download/ instead of https://nodejs.org/en/download/

"Learn" link is also 404.

https://github.com/nodejs/nodejs.org/assets/19714/a951c7a5-49c3-4200-836e-19a03cdf029c

**Comment by ovflowd** [comment]
Any link from a broken translation page is 404, that's because it actually doesn't know what language to put. It only happens on 404s on "unsuported" languages.

Closing this, as the other issue should already cover this.
