### ISSUE TITLE
rsync support for /dist mirroring

### ISSUE THREAD

**Issue by jsumners** [nodejs/nodejs.org#662]
Way back in 2012 you asked on Twitter if there are any public mirrors -- https://twitter.com/nodejs/status/211311765479374848

Someone asked you how, and you were silent. Today, I find myself wanting to mirror at least v4.x and v5.x of /dist to a local system for other systems I run that can't access the Internet. Using wget is a rather poor solution, and you probably don't want that load on the web server.

So, I'm asking you to provide us with a better way to mirror the /dist content.

**Comment by stevemao** [comment]
ping @nodejs/build 
This should be probably asked in the build or help repo.

**Comment by jsumners** [comment]
Okay. I wasn't sure where it should go.

**Comment by fhemberger** [comment]
This may help:
https://github.com/nodejs/nodejs.org-archive/issues/23
https://gist.github.com/rgbkrk/5499863

**Comment by jsumners** [comment]
@fhemberger I already know of the python script. It's a decent stop-gap, but it isn't a good replacement for rsync.

**Comment by fhemberger** [comment]
@rvagg @nodejs/build Do we need to change something in `/dist` to allow rsync mirroring?

**Comment by jsumners** [comment]
@fhemberger no. You just need to add an rsync server definition:

`/etc/rsyncd.conf`:

``` conf
[dist]
  path = /path/to/web/dist
  comment = dist files via rsync
```

**Comment by jsumners** [comment]
For the interim, or if you decide to not implement rsync, I wrote a better script, bandwidth saving, script:

https://gist.github.com/jsumners/4d1861c586708fab7c758f711952ed85

**Comment by ghost** [comment]
@jsumners could you put that in a gist and link it here? kinda clutters up the issue a bit 😶

**Comment by rvagg** [comment]
If anyone here's interested in beta testing an rsync endpoint, please hit me up @ rod@vagg.org and @jbergstroem and I will get you set up to try out our shiny new experiment.

**Comment by fhemberger** [comment]
@nodejs/build Is this issue resolved?

**Comment by jbergstroem** [comment]
We have a rsync endpoint up and running at `unencrypted.nodejs.org`. The idea was to make it official as part of hsts but seeing how that hasn't happened the public announcement is pending. It is working and gets regularly updated, though.

**Comment by fhemberger** [comment]
Closing this issue here due to lack of activity, further discussion should take place in @nodejs/build.
Feel free to re-open if there's a new development.
