### ISSUE TITLE
Sentry lazy loading in browser is incorrect

### ISSUE THREAD

**Issue by r34son** [nodejs/nodejs.org#6621]
### Enter your suggestions in details:

Related https://github.com/getsentry/sentry-javascript/issues/11460

**Comment by mikeesto** [comment]
Hi, could you please add some more info about how this relates to nodejs.org?

**Comment by r34son** [comment]
https://github.com/nodejs/nodejs.org/blob/main/sentry.client.config.ts

You are trying to lazy load some sentry integrations, but it's incorrect. Take a look to the linked issue.

**Comment by bmuenzenmeyer** [comment]
@r34son nice research and work with Sentry on this one; care to send a PR our way?
