### ISSUE TITLE
Add links to "Node.js Live" events under 'conferences'

### ISSUE THREAD

**Issue by stevemao** [nodejs/nodejs.org#663]
I don't think http://live.nodejs.org/ is linked under the main website. If it is, it's probably not very obvious.

**Comment by fhemberger** [comment]
No, it's not linked yet. And I don't know a good place to do so. The homepage would be best, but we already have the huge Node Interactive banner there.

**Comment by mikeal** [comment]
These events are pretty localized so the best place is probably just in the events page next to other conferences.

**Comment by fhemberger** [comment]
Can someone please add a PR for this? /cc @nodejs/website

**Comment by lpinca** [comment]
> These events are pretty localized so the best place is probably just in the events page next to other conferences.

Does this mean that the live events should be added in `events.md`?
For example:

``` diff
diff --git a/locale/en/get-involved/events.md b/locale/en/get-involved/events.md
index fdbce94..5a39664 100644
--- a/locale/en/get-involved/events.md
+++ b/locale/en/get-involved/events.md
@@ -7145,6 +7145,14 @@ regions:
         lat: 37.788678
         lon: -122.4126467
         location: "Marine's Memorial Theatre, 609 Sutter Street, San Francisco, CA 94102"
+      - name: Node.js Live Los Angeles
+        dates:
+          - 2016-02-25T00:00:00.000Z
+        link: 'http://live.nodejs.org/events/los-angeles.html'
+        desc: Global event bringing together local Node.js developers around the world.
+        lat: 34.097144
+        lon: -118.327328
+        location: '6360 Sunset Blvd, Los Angeles, CA 90028'
     meetups:
       - country: US
         city: Austin
```

**Comment by fhemberger** [comment]
Yes, that would be great.
