### ISSUE TITLE
Improve Frontend 

### ISSUE THREAD

**Issue by Akshaypmna18** [nodejs/nodejs.org#6632]
### Enter your suggestions in details:

I would love to contribute to this project. I'm a frontend developer with expertise in react and next.js. 

If anyone can assist or guide me. It would be a great help for my coding experience.

**Comment by AugustinMauroy** [comment]
Hey ! What do you what to improve ?

**Comment by ovflowd** [comment]
This is not an issue, sounds more like a discussion. If you want to contribute, just read the open issues and the contributing guidelines.

**Comment by Akshaypmna18** [comment]
@AugustinMauroy anything that makes my code and my thinking better

**Comment by AugustinMauroy** [comment]
> @AugustinMauroy anything that makes my code and my thinking better

Just a reminder, is not for learning purposes.
