### ISSUE TITLE
Wrong redirection for Download link in not found page

### ISSUE THREAD

**Issue by mAmineChniti** [nodejs/nodejs.org#6636]
### URL:

https://nodejs.org/ja (or any not found locale)

### Browser Name:

Chrome

### Browser Version:

Version 123.0.6312.106 (Official Build) (64-bit)

### Operating System:

Windows 10 22H2 10.0.19045

### How to reproduce the issue:

on not yet supported/translated locales like https://nodejs.org/ja it seems that the `Download` link in `navBar` redirects to `/download`
instead of default locale/path which is `en/download` all other navBar links have this behavior except `Download`
![chrome_iYiJ5JpbHQ](https://github.com/nodejs/nodejs.org/assets/124379229/6af04d78-630b-4d2f-abda-6bd61d2bd757)
![chrome_bLwpv575fb](https://github.com/nodejs/nodejs.org/assets/124379229/c0733428-acea-40a7-b6ef-b6c3d2a96d49)

**Comment by ovflowd** [comment]
This is a duplicated issue 👀 (in sorts) but still we should work into fixing this @bmuenzenmeyer
