### ISSUE TITLE
Install Node.js LTS version on windows by chocolate failed for the wrong Package 

### ISSUE THREAD

**Issue by saintak** [nodejs/nodejs.org#6637]
### URL:

https://nodejs.org/en/download/package-manager

### Browser Name:

Microsoft Edge

### Browser Version:

123.0.2420.81

### Operating System:

Windows 11 23H2 22631.3296

### How to reproduce the issue:

1. I want to install Install Node.js LTS version on windows by chocolate, as the https://nodejs.org/en/download/package-manager show below
![QQ截图20240410154222](https://github.com/nodejs/nodejs.org/assets/9425842/dded5172-6c69-4b39-8cf2-97c5eebf1fcf)

2. But it failed like below
![QQ截图20240410154237](https://github.com/nodejs/nodejs.org/assets/9425842/70d5b733-fc27-441d-a38e-eb01647c03cb)

3. And I find that there is no 20.12.1 in Package nodejs. https://community.chocolatey.org/packages/nodejs#versionhistory
4. But I should install 20.12.1 LTS by the Package  https://community.chocolatey.org/packages/nodejs-lts#versionhistory
5. so I think the file nodejs/nodejs.org/util/getNodeDownloadSnippet.ts should be modified to change the command to` choco install nodejs-lts --version="${release.version}"` when we check the LTS version

**Comment by ovflowd** [comment]
Oh that is really interesting! Does Chocolatey publish two different packages for LTS and Non-LTS version? O.o

In my previous findings this was not the case, could it be that it just did not get published yet on the regular nodejs package?

**Comment by saintak** [comment]
> Oh that is really interesting! Does Chocolatey publish two different packages for LTS and Non-LTS version? O.o
> 
> In my previous findings this was not the case, could it be that it just did not get published yet on the regular nodejs package?

@ovflowd you will find that in the link https://community.chocolatey.org/packages/nodejs#versionhistory  , so it is still recommended to use the [nodejs-lts](https://chocolatey.org/packages/nodejs-lts) package  if only targeting the latest LTS release is required.
And there is no LTS version added since 20.12.0.
The last LTS version in nodejs package is [20.11.1](https://community.chocolatey.org/packages/nodejs/20.11.1) which was added in February 15, 2024, while the last current version is Node JS 21.7.1 which was added in April 4, 2024
>- While this package now provides both Current and LTS releases of Node.js, it is still recommended to use the [nodejs-lts](https://chocolatey.org/packages/nodejs-lts) package if only targeting the latest LTS release is required.
>- If the package is out of date please check [Version History](https://community.chocolatey.org/packages/nodejs#versionhistory) for the latest submitted version. If you have a question, please ask it in [Chocolatey Community Package Discussions](https://github.com/chocolatey-community/chocolatey-packages/discussions) or raise an issue on the [Chocolatey Community Packages Repository](https://github.com/chocolatey-community/chocolatey-packages/issues) if you have problems with the package. Disqus comments will generally not be responded to.

![QQ截图20240410190350](https://github.com/nodejs/nodejs.org/assets/9425842/cf0b1694-ae2c-4052-8324-c0c23f37b06f)
![QQ截图20240410190403](https://github.com/nodejs/nodejs.org/assets/9425842/657b78c3-8b92-4e82-919c-43dc597c9beb)

So I think it's time to switch to the new package [nodejs-lts](https://community.chocolatey.org/packages/nodejs-lts) for LTS version

**Comment by ovflowd** [comment]
> > Oh that is really interesting! Does Chocolatey publish two different packages for LTS and Non-LTS version? O.o
> 
> > 
> 
> > In my previous findings this was not the case, could it be that it just did not get published yet on the regular nodejs package?
> 
> 
> 
> @ovflowd you will find that in the link https://community.chocolatey.org/packages/nodejs#versionhistory  , so it is still recommended to use the [nodejs-lts](https://chocolatey.org/packages/nodejs-lts) package  if only targeting the latest LTS release is required.
> 
> And there is no LTS version added since 20.12.0.
> 
> The last LTS version in nodejs package is [20.11.1](https://community.chocolatey.org/packages/nodejs/20.11.1) which was added in February 15, 2024, while the last current version is Node JS 21.7.1 which was added in April 4, 2024
> 
> >- While this package now provides both Current and LTS releases of Node.js, it is still recommended to use the [nodejs-lts](https://chocolatey.org/packages/nodejs-lts) package if only targeting the latest LTS release is required.
> 
> >- If the package is out of date please check [Version History](https://community.chocolatey.org/packages/nodejs#versionhistory) for the latest submitted version. If you have a question, please ask it in [Chocolatey Community Package Discussions](https://github.com/chocolatey-community/chocolatey-packages/discussions) or raise an issue on the [Chocolatey Community Packages Repository](https://github.com/chocolatey-community/chocolatey-packages/issues) if you have problems with the package. Disqus comments will generally not be responded to.
> 
> 
> 
> ![QQ截图20240410190350](https://github.com/nodejs/nodejs.org/assets/9425842/cf0b1694-ae2c-4052-8324-c0c23f37b06f)
> 
> ![QQ截图20240410190403](https://github.com/nodejs/nodejs.org/assets/9425842/657b78c3-8b92-4e82-919c-43dc597c9beb)
> 
> 
> 
> So I think it's time to switch to the new package [nodejs-lts](https://community.chocolatey.org/packages/nodejs-lts) for LTS version

Are you saying the regular nodejs package also doesn't contain the latest non-lts versions? 🤔

**Comment by ovflowd** [comment]
Hmm, nevermind, they have the latest version (just not the latest one released a few days ago)... Since this package seems community-maintained, we depend on them updating those versions manually...

**Comment by saintak** [comment]
> Hmm, nevermind, they have the latest version (just not the latest one released a few days ago)... Since this package seems community-maintained, we depend on them updating those versions manually...

Yes, but the nodejs-lts has been updated to the latest version.
I think it's possible to indicate on the download page that chocolate may not download the latest version of node.js in a timely manner. I suggest that users can go to this [link](https://community.chocolatey.org/packages/nodejs#versionhistory) to view the latest version they provide
