### ISSUE TITLE
Node.js compilation for QNX

### ISSUE THREAD

**Issue by rameshpasunoori** [nodejs/nodejs.org#664]
Hello All

How to build Node.js for QNX.
Document not available for cross compilation.
Provide some info .
Thanks
Ramesh

**Comment by phillipj** [comment]
Hi @rameshpasunoori,

this repository is strictly for our website (https://nodejs.org). I'm assuming this is related to the actual Node.js runtime, which is located in the [nodejs/node](https://github.com/nodejs/node) repository. Head over there and [create a new issue](https://github.com/nodejs/node/issues/new) and you'll probably get more answers.

**Comment by stevemao** [comment]
I think you should probably ask here @rameshpasunoori https://github.com/nodejs/help
