### ISSUE TITLE
[Broken Link]: Node.js v7 has updated V8 to 5.4

### ISSUE THREAD

**Issue by unclebay143** [nodejs/nodejs.org#6641]
### URL:

https://nodejs.org/en/blog/announcements/update-v8-5.4

### Browser Name:

Chrome

### Browser Version:

123.0.6312.87

### Operating System:

MacOS

### How to reproduce the issue:

1. Visit: https://nodejs.org/en/blog/announcements/nodejs-certified-developer-program
2. Click the next button: ![image](https://github.com/nodejs/nodejs.org/assets/58919619/8b36a252-d965-4160-9d63-f6a459210f80)
3. This leads to a 404 page to: https://nodejs.org/en/blog/announcements/update-v8-5.4
![image](https://github.com/nodejs/nodejs.org/assets/58919619/03d817a1-66cc-4f1f-85a3-acbb56c6d236)

**Comment by reeveng** [comment]
Would love to tackle this one. Found the issue, it's either in the frontmatter of the [page](https://github.com/nodejs/nodejs.org/blob/main/pages/en/blog/community/update-v8-5.4.md) (wrong category, which i doubt) or the location of the [page](https://github.com/nodejs/nodejs.org/blob/main/pages/en/blog/community/update-v8-5.4.md) (should be moved to the folder "announcements", which corresponds with the category in the frontmatter).
