### ISSUE TITLE
Consider moving the breadcrumbs to the top of the page in nodejs/learn section

### ISSUE THREAD

**Issue by FatumaA** [nodejs/nodejs.org#6651]
### Enter your suggestions in details:

1. My expectation is that breadcrumbs are usually at the top of the page
2. I'm basing the suggestion on that other users probably also expect breadcrumbs to be at the top of the page. It can be a bit disorienting to find it at the bottom of the page
3. I suggest it is moved to the top

Having it go from this:
![Group 11 (1)](https://github.com/nodejs/nodejs.org/assets/67555014/086f1163-5aa2-4fed-8032-153748359913)

To something like this:
![Group 12](https://github.com/nodejs/nodejs.org/assets/67555014/c654e264-4c02-4a24-a490-8f7e0664e4b5)

We had a discussion on Slack with Claudio where he suggested opening this issue.

**Comment by AugustinMauroy** [comment]
-1 for this proposal.

I prefer to give importance to content. So that's why I think the Breadcrumb should be at the bottom of the page.

**Comment by FatumaA** [comment]
Breadcrumbs don't compete with content. They enhance navigation

**Comment by AugustinMauroy** [comment]
> Breadcrumbs don't compete with content. They enhance navigation

I don't agree with you, the BreadCrumb is there to help users find their way around the site. For navigation, there's the nav bar (on the left) which does just that.

**Comment by FatumaA** [comment]
> > Breadcrumbs don't compete with content. They enhance navigation
> 
> I don't agree with you, the BreadCrumb is there to help users find their way around the site. For navigation, there's the nav bar (on the left) which does just that.

Yes, it acts as a secondary navigation

**Comment by ovflowd** [comment]
I wonder, what sort of problem are we trying to solve by moving the Breadcrumbs to the top 🤔

**Comment by FatumaA** [comment]
I don't think it is a problem necessarily, more of an enhancement. I base the suggestion on breadcrumbs being generally put near the top of web pages, hence creating an expectation of the same among users. 

Here are some links I found:

1. https://www.nngroup.com/articles/breadcrumbs/
2. https://www.pencilandpaper.io/articles/breadcrumbs-ux
3. https://www.semrush.com/blog/breadcrumbs-for-websites/
4. https://app.uxcel.com/courses/ui-components-best-practices/breadcrumbs-best-practices-269

Notice in almost all the visual examples, the breadcrumbs are at the top. 

That said, it can stay as is if deemed unnecessary.

**Comment by prabeshkunwar12** [comment]
**Support for Moving Breadcrumbs to the Top**

I wanted to express my support for FatumaA's suggestion regarding the placement of breadcrumbs in our UI design. FatumaA proposed relocating them to the top of the page, and I believe this change has significant merit.

Placing breadcrumbs at the top aligns with established UI conventions and enhances usability for our users. It leverages their existing knowledge and experiences, making it easier for them to navigate through the hierarchy of our website or application.

By following this familiar pattern, we can improve the overall user experience and ensure consistency with popular platforms. Additionally, this change would likely contribute to a smoother and more intuitive navigation flow for our users.

I encourage us to explore FatumaA's suggestion further and consider conducting usability testing to validate its potential benefits. Implementing this change could be a valuable enhancement to UI design, and I believe it's worth exploring in more detail.

**Comment by reeveng** [comment]
Giving my 2 cents on this, when I read an article at first and saw the breadcrumbs at the bottom, it didn't make any sense, what so ever, that they were there. Also known as +1 for this proposal.

Although given that the sidebar navigation is right next to it, and that there are barely any (if any) that go more than 2 levels deep, it might be superfluous at the moment to have breadcrumbs there in the first place, that paired with the fact that:

![image](https://github.com/nodejs/nodejs.org/assets/36441093/45ed42aa-64cf-4ad4-9218-d186d4f0ddc1)

apparently sometimes the breadcrumbs are broken or don't behave exactly the same everywhere (more important?). But I guess that's a different issue.

Personally would focus on only re-rendering the article and not the sidebar navigation (if that is meant to be used as main navigation?), causing me to shift upwards in the navigation, when I click on a new article.
Sidebar should stay in this exact location when I click on a new item:

![image](https://github.com/nodejs/nodejs.org/assets/36441093/fc2ee66a-f767-4a53-895e-86df49e7e885)

**Comment by ovflowd** [comment]
> apparently sometimes the breadcrumbs are broken or don't behave exactly the same everywhere (more important?). But I guess that's a different issue.

Unrelated issue, feel free to open a new issue, please 🙇 

> Personally would focus on only re-rendering the article and not the sidebar navigation (if that is meant to be used as main navigation?), causing me to shift upwards in the navigation, when I click on a new article.
Sidebar should stay in this exact location when I click on a new item:

Also, it is an unrelated issue of which we are aware... Feel free to open an issue :)

**Comment by bmuenzenmeyer** [comment]
closing this as not planned
