### ISSUE TITLE
i18n dynamic locale load

### ISSUE THREAD

**Issue by faeztgh** [nodejs/nodejs.org#6658]
## URL:

https://nodejs.org/fa

### Browser Name:

Chrome

### Browser Version:

103

### Operating System:

Windows 10 x64

### How to reproduce the issue:

I added a new locale and expect it to load dynamically in the following function in the `i18n.tsx` file:
```typescript

const loadLocaleDictionary = async (locale: string) => {
  if (locale === 'en') {
    // This enables HMR on the English Locale, so that instant refresh
    // happens while we add/change texts on the source locale
    return import('./i18n/locales/en.json').then(f => f.default);
  }

  if (availableLocaleCodes.includes(locale)) {
    // Other languages don't really require HMR as they will never be development languages
    // so we can load them dynamically
    return import(`./i18n/locales/${locale}.json`).then(f => f.default);
  }

  throw new Error(`Unsupported locale: ${locale}`);
};
```

But second if seems not working properly. 
It worked after I add another if like first if :
```typescript
const loadLocaleDictionary = async (locale: string) => {
  if (locale === 'en') {
    // This enables HMR on the English Locale, so that instant refresh
    // happens while we add/change texts on the source locale
    return import('./i18n/locales/en.json').then(f => f.default);
  }

  if (locale === 'fa') {
    // This enables HMR on the Persian Locale, so that instant refresh
    // happens while we add/change texts on the source locale
    return import('./i18n/locales/fa.json').then(f => f.default);
  }


  if (availableLocaleCodes.includes(locale)) {
    // Other languages don't really require HMR as they will never be development languages
    // so we can load them dynamically
    return import(`./i18n/locales/${locale}.json`).then(f => f.default);
  }

  throw new Error(`Unsupported locale: ${locale}`);
};
```

**Comment by AugustinMauroy** [comment]
What is the issue ? Did you want to enable `fa` on website ?

**Comment by faeztgh** [comment]
> What is the issue ? Did you want to enable `fa` on website ?

Yes

**Comment by AugustinMauroy** [comment]
You just need to enable on `config.json`.
But say on `translation.md` it's a decision taken by the website team.

any other questions?

**Comment by faeztgh** [comment]
> You just need to enable on `config.json`. But say on `translation.md` it's a decision taken by the website team.

I did that too.

> any other questions?

My opinion is mentioned function for importing languages dynamically not work as it should. Have you ever test it with another language?!

**Comment by AugustinMauroy** [comment]
> My opinion is mentioned function for importing languages dynamically not work as it should. Have you ever test it with another language?!

It's work you can see on #6445 that is working.

**Comment by ovflowd** [comment]
i18n is working as expected. It is not meant to be manually enabled. Crowdin is supposed to manage making the locale actually work. Only after Crowdin imports said files, we can actually flip the switch on `config.json`.

I'm closing this for now. Just a FYI we are waiting for Crowdin to fix something on their MDX parser on their side :)
