### ISSUE TITLE
Release schedule too difficult to find

### ISSUE THREAD

**Issue by jsumners** [nodejs/nodejs.org#6669]
Every time I try to find the release schedule page on the current site I get frustrated and give up. It used to be prominent on the homepage. Now, I haven't a clue where to find it.

<img width="1333" alt="Monosnap Node js - Vivaldi 2024-04-23 21-58-13" src="https://github.com/nodejs/nodejs.org/assets/321201/e511d024-67bc-467a-a03b-e78043247050">

**Comment by AugustinMauroy** [comment]
I allow with you release schedule is not "promoted". But I'm more in favor of putting the link to release schedule on download page.

**Comment by ovflowd** [comment]
> Every time I try to find the release schedule page on the current site I get frustrated and give up

What are the paths you've attempted? I don't think the Release Schedule is something the average user is attempting to look for, but we could probably make it more prominent on the "Download pages"?

The release schedule is under: About > Previous Releases, I assume the naming "Previous Releases" could be improved to something like "Node.js Releases"

**Comment by jsumners** [comment]
I've clicked all over the site. The change to "previous releases" obfuscates what the link goes to. In other words, it doesn't make any sense when looking for the release schedule. 

I also think it's short sighted to assume "regular users" are not concerned about the schedule. Those regular users are developers that need to plan for deploying their software in a supported manner. 

Frankly, the schedule doc is the only thing I visit the site for 98% of the time. Occasionally I am looking for the API docs, and _very_ rarely the tutorials. Which is to say, I think the release schedule is the most important information on the site and it was featured as such on the old site.

**Comment by ovflowd** [comment]
> I also think it's short sighted to assume "regular users" are not concerned about the schedule. Those regular users are developers that need to plan for deploying their software in a supported manner.

My "regular users" assessment is based on behavioral data from Sentry's Session Replays, which calculated that an extremely low percentile clicked that link. It's not a "wild guess" assessment.

**Comment by ovflowd** [comment]
> Frankly, the schedule doc is the only thing I visit the site for 98% of the time. Occasionally I am looking for the API docs, and very rarely the tutorials. Which is to say, I think the release schedule is the most important information on the site and it was featured as such on the old site.

That's your use case. If that's the only information you want to check, you should go over https://github.com/nodejs/release ... Not the website.

But feedback taken, We'll investigate into improving this experience.

**Comment by ovflowd** [comment]
(accidentally clicked to close the issue 🤦)

**Comment by jsumners** [comment]
> > Frankly, the schedule doc is the only thing I visit the site for 98% of the time. Occasionally I am looking for the API docs, and very rarely the tutorials. Which is to say, I think the release schedule is the most important information on the site and it was featured as such on the old site.
> 
> 
> 
> That's your use case. If that's the only information you want to check, you should go over https://github.com/nodejs/release ... Not the website.
> 
> 
> 
> But feedback taken, We'll investigate into improving this experience.

It's much easier to type `nodejs.org` into a URL bar than it is to type a GitHub project URL.

**Comment by ovflowd** [comment]
> > > Frankly, the schedule doc is the only thing I visit the site for 98% of the time. Occasionally I am looking for the API docs, and very rarely the tutorials. Which is to say, I think the release schedule is the most important information on the site and it was featured as such on the old site.
> > 
> > 
> > That's your use case. If that's the only information you want to check, you should go over [nodejs/release](https://github.com/nodejs/release) ... Not the website.
> > But feedback taken, We'll investigate into improving this experience.
> 
> It's much easier to type `nodejs.org` into a URL bar than it is to type a GitHub project URL.

Right, and also, the average user isn't required to be aware of such a repository. Just saying specifically for you that this repository URL is the actual source of what we display on the page 👀

**Comment by srl295** [comment]
100%. in fact, i just stumbled on an old version of the homepage promoting "Node 18" by searching for "Node Release Cycle"
