### ISSUE TITLE
Document ReadStream.prototype.destroy

### ISSUE THREAD

**Issue by dotnetCarpenter** [nodejs/nodejs.org#667]
[`ReadStream.prototype.destroy`](https://github.com/nodejs/node/blob/697790c1176bb4bb8062458c765fecc5e8a07646/lib/fs.js#L1739) is missing from the [documentation](https://nodejs.org/api/stream.html). Others, than me, [have had question](http://stackoverflow.com/questions/19277094/how-to-close-a-readable-stream-before-end)s about it. I think it's about time to get the method documented :dancers:

**Comment by lpinca** [comment]
@dotnetCarpenter maybe it's better to open this issue in [node](https://github.com/nodejs/node) repository. API documentation lives there.

**Comment by dotnetCarpenter** [comment]
@lpinca thanks - wasn't sure and made the wrong guess. [#5898](https://github.com/nodejs/node/issues/5898) is amended.
