### ISSUE TITLE
Inconsistency of breadcrumbs detail shown in about page of the website

### ISSUE THREAD

**Issue by TenzDelek** [nodejs/nodejs.org#6679]
### URL:

https://nodejs.org/en/about

### Browser Name:

brave

### Browser Version:

1.65.123

### Operating System:

Windows 11

### How to reproduce the issue:

1. the behavior of the breadcrumb is not consistent across the sidebar in about page.
2. the expected behavior should be like the part of the (Project governance) and the (branding of the nodejs) where the visual are expected. 
<img width="475" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/cce8cc0d-dd91-4815-bed7-7f3236169bed">

3. rest of the sub parts are only showing about nodejs as the title. the expected behavior is it should be like above mention
4. current behavior problem screenshot:
<img width="925" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/a1cda90a-d9aa-4217-ba13-74d656dccda1">

5. expected behavior: 
<img width="914" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/a2aa30f7-0867-4ea8-8bc2-a8f9f96d68d3">

**Comment by ovflowd** [comment]
Indeed, sounds like it is rendering the breadcrumbs inconsistently.

**Comment by TenzDelek** [comment]
@ovflowd  after going through the code base for a while i notice two thing. 
1. The path that doesnt have the dash(-) are rendering the breadcrumb as expected
<img width="506" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/2dcd2d6f-a2fd-4535-879b-cdae435bd2fa">

![Screenshot 2024-04-29 162744](https://github.com/nodejs/nodejs.org/assets/122612557/bfc2c6f7-6089-42cd-9085-b69e7597e589)



3. but the path which have the dash(-) in their path are not rendering correctly
<img width="335" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/18e967f0-20c2-46ab-a56f-4bb32e82cc88">

<img width="605" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/9fa845b0-51ac-4cad-8c01-bedeaed3fd7a">

do you think that the issue lies in handling the dash or somewhere else?

**Comment by TenzDelek** [comment]
# found the issue regarding this problem,
the nodeWithCurrentPath for the paths which doesnt show the correct breadcrumbs are having undefined value.
![Screenshot 2024-04-29 220449](https://github.com/nodejs/nodejs.org/assets/122612557/a3f1f011-cfcc-4634-bf33-84e0ac9912aa)

whereas the path which are working fine have the values in nodeWithCurrentPath.
<img width="493" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/cd81cd5a-a879-4b8e-9eb0-9498d431a9db">

 @ovflowd @AugustinMauroy **what your guys thought on this?** i tried debugging but was not able to come up with the solution. my assumption is regarding the mismatch of the pathname when we convert it to dashed. 
<img width="407" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/43d19588-633f-4fa8-bd51-08076edf1e71">
the navigation tree has this values but the path that we are looking at has 
<img width="359" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/d140954f-d79a-4fb5-911e-52a733774b99">
which should be releases instead of previousReleases in the pathlist.

**Comment by TenzDelek** [comment]
try: with a small logic of instead doing the camelcase i tried to remove the one side of the hypen 
<img width="284" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/764ee57d-58e9-402f-80d1-cbf898c279ee">
works with releases 
before:
<img width="300" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/8941cca7-31f7-4bb7-a49d-5a9ebe430c10">
after:
<img width="455" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/ff80c557-3c53-43ca-8d64-0be4643ba045">
but for the security reporting subpart ( the [0] pos is used) thats why it is not affecting.

also another issue is with the whole section of 
<img width="194" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/bbb8b3dc-7fc6-4105-b15d-9a65b5ab1da1">
the path is showing complety wrong 
<img width="355" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/0682e19f-dda9-493f-bf49-d2d954ef3414">
the current not path should be get involved instead of about i guess. 
can you guys look at it and give your thoughts on how we can implement this changes. :smiley:

**Comment by TenzDelek** [comment]
why get involved is set under about but about is set only one dynamic route 
about ss:
<img width="617" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/a62065db-ad7c-436c-8d79-05bce9addc0b">
get involved ss:
<img width="749" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/a109bdd1-8e01-4029-ae25-fbd0b185dddc">
# my doubt:
shouldnt the about route look same as the get involved like /about/about/branding instead of /about/branding

**Comment by mikeesto** [comment]
I'm not sure if this is related - just further down in the "Get Involved" section all of the breadcrumbs do not include the name of the page. For example: https://nodejs.org/en/about/get-involved/events

**Comment by tquocanvn** [comment]
@TenzDelek @mikeesto 

As I understand, there are 2 problems on the breadcrumbs handling:

1. HOC `withBreadcrums.tsx` expected key name of side bar navigation in `navigation.json` to be matched with its last route path value, for example: 

```
"releases": {
          "link": "/about/previous-releases",
          "label": "components.navigation.about.links.releases"
}
```

while it should be updated following:

```
"previousReleases": {
          "link": "/about/previous-releases",
          "label": "components.navigation.about.links.releases"
}
```

=> Update key name might be a proper solution for this case, but I'm not sure if changing key name might affect other places in the project or not, will need the help of @ovflowd to confirm about it.

2. Section `About Node.js` and `Get Involved` are using same root path `/about`, therefore, when getting data for `/about/get-involved/**`, it will falls into data of `About Node.js` section while the correct one should be the other section`Get Involved`.

=> Update `getBreadcrumbs` function in `withBreadcrumbs.tsx` to check also child item route path will help to determine correct navigation data.

I've created a PR for this issue at https://github.com/nodejs/nodejs.org/pull/6710

**Comment by TenzDelek** [comment]
> @TenzDelek @mikeesto
> 
> As I understand, there are 2 problems on the breadcrumbs handling:
> 
> 1. HOC `withBreadcrums.tsx` expected key name of side bar navigation in `navigation.json` to be matched with its last route path value, for example:
> 
> ```
> "releases": {
>           "link": "/about/previous-releases",
>           "label": "components.navigation.about.links.releases"
> }
> ```
> 
> while it should be updated following:
> 
> ```
> "previousReleases": {
>           "link": "/about/previous-releases",
>           "label": "components.navigation.about.links.releases"
> }
> ```
> 
> => Update key name might be a proper solution for this case, but I'm not sure if changing key name might affect other places in the project or not, will need the help of @ovflowd to confirm about it.
> 
> 2. Section `About Node.js` and `Get Involved` are using same root path `/about`, therefore, when getting data for `/about/get-involved/**`, it will falls into data of `About Node.js` section while the correct one should be the other section`Get Involved`.
> 
> => Update `getBreadcrumbs` function in `withBreadcrumbs.tsx` to check also child item route path will help to determine correct navigation data.
> 
> I've created a PR for this issue at #6710

@tquocanvn  your approach of passing the value seems correct, will close my pr!!

**Comment by abizek** [comment]
I also found a few related issues with the breadcrumbs on the learn page. Particularly in these 4 articles

> https://nodejs.org/en/learn/getting-started/ecmascript-2015-es6-and-beyond
https://nodejs.org/en/learn/asynchronous-work/discover-javascript-timers
https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick
https://nodejs.org/en/learn/manipulating-files/working-with-different-filesystems

I think we should consider these as well in the fix @tquocanvn
