### ISSUE TITLE
Changes in Copy to ClipBoard button in main page

### ISSUE THREAD

**Issue by TenzDelek** [nodejs/nodejs.org#6685]
### URL:

https://nodejs.org/en

### Browser Name:

brave

### Browser Version:

1.65.123

### Operating System:

Windows 11

### The Problem: 
1. the current copy to clipboard has a display like this

<img width="584" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/bb8b9fa5-469e-43c7-848b-2147cf470f27">

making it not so UI friendly. and in smaller screen it is not even showing

### Approach:
- instead of the popup like the current version, we can so make it transition to a state of true and false when it is being clicked.
- so when it is click it transition to the clicked state.

**Comment by AugustinMauroy** [comment]
I remove bug label because that not a bug.
also why remove toast ? What's wrong with announcing that something non-visual has happened with a toast?

**Comment by TenzDelek** [comment]
@AugustinMauroy  personally, it feels more intrusive to have a change in the button itself than displaying  a toast, other than that no such reason to remove, :smiley:
+ also the current display is happening like this in smaller screen: 
<img width="173" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/bd08e310-e80c-431a-8606-d4374592728c">

**Comment by AugustinMauroy** [comment]
Ok, so there are an issue for displaying toast on small screen.
And you propose to remove toast.

But you can't mix the two. One is a problem of consepction and the other is an ideology/point of view.

**Comment by TenzDelek** [comment]
@AugustinMauroy agreed with your input, my point was to show the underlying issue with the current toast, plus an approach to use state base instead of a toast. If you feel the toast is fine , then I guess it's fine to leave it as such. 👍
