### ISSUE TITLE
ES6 page should be ready to be updated when Node.js v6 drops.

### ISSUE THREAD

**Issue by evanlucas** [nodejs/nodejs.org#671]
Node.js v6.0.0 is in the rc phase. See https://github.com/nodejs/node/issues/5766 for status updates. This will include a jump to v8 5.0. That jump will greatly increase the amount of ES2015 features and we need to update the ES6 page (https://nodejs.org/en/docs/es6/).

**Comment by mikeal** [comment]
Should we maybe just start directing people to node.green?

**Comment by evanlucas** [comment]
I thought node.green included some staging flags. We probably do not want to include things that require staging flags IMO

**Comment by jasnell** [comment]
It does, but there is a toggle (barely visible) at the top of the page to turn off the things that require flags. Perhaps we could ask @williamkapke to make that toggle more evident? Or perhaps visually distinguish the things that do require a flag?

**Comment by williamkapke** [comment]
see: https://github.com/williamkapke/node-compat-table/issues/1

I will change the colors soon (just swamped at the moment). PR welcome ;)

**Comment by evanlucas** [comment]
ok, I'm +1 for removing the page entirely and linking to node.green if we can get work out the flag issue

**Comment by stevemao** [comment]
Linking https://github.com/nodejs/nodejs.org/pull/434

**Comment by lpinca** [comment]
Also linking #653.

**Comment by fhemberger** [comment]
Linking #488 as well.

**Comment by fhemberger** [comment]
PR is ready: #674.
Requires a redirect of `https://nodejs.org/en/docs/es6/` => `http://node.green` as well: https://github.com/nodejs/build/pull/394

**Comment by ChALkeR** [comment]
@fhemberger 

Does node.green explain the «shipping»/«staged»/«in progress» status of the features and the `--es_staging`/`--harmony`/`--harmony-*` flags? Afaik it doesn't, and that information is valuable there.

It should be moved somehwere, perhaps to a new page.

**Comment by jbergstroem** [comment]
@fhemberger: does this mean we should look at hosting node.green as well?

**Comment by jbergstroem** [comment]
My 2c would be to keep it separate.

**Comment by benjamingr** [comment]
I think node.green is not a good idea for the page (but is amazing otherwise) because the page should be a lot more reader friendly.

**Comment by lpinca** [comment]
@benjamingr honestly I think that we will end with something very similar to node.green if we continue #434.

**Comment by williamkapke** [comment]
FYI, I pushed the gold color & percent changes. I am not opposed to turning it over to the node community... that's what I built it for!

At minimum, I'd like to have contributors/collaborators. ;)

**Comment by benjamingr** [comment]
I'm in favor with the direction the PR is taking: keeping the part explaining what ES6 is about and then linking to node.green in the "what ES6 features are supported" part.

I'm also in favor of the foundation taking over node.green and @williamkapke joining the node foundation and maintaining it from within.

**Comment by jasnell** [comment]
I'm not sure I would characterize it as "taking it over" :-) We're more
than happy to give node.green a home here and to help promote it. It's a
fantastic tool and definitely something that's needed.

Question for @williamkapke: how closely does this follow test262?

**Comment by williamkapke** [comment]
> how closely does this follow test262

@jasnell All of the tests are pulled from [Kangax's project](https://github.com/kangax/compat-table)\- so I'm not sure. They are quite active at adding/updating/improving the tests. It is all automatic- tests are pulled and run daily.

**Comment by williamkapke** [comment]
@jasnell [The V8 blog has more info](http://v8project.blogspot.com/2016/04/es6-es7-and-beyond.html) on your question about test262.

> Kangax makes it easy to skim to see whether a particular feature (like arrow functions) has been implemented in a given engine, but doesn’t test all the conformance edge cases that test262 does. Currently, Chrome Canary scores a 98% on the Kangax table for ES6 and 100% on the sections of Kangax corresponding to ES7 (e.g. the sections labelled “2016 features” and “2016 misc” under the ESnext tab).
