### ISSUE TITLE
Blog Word Break

### ISSUE THREAD

**Issue by MitchTalmadge** [nodejs/nodejs.org#6711]
### URL:

https://nodejs.org/en/blog/announcements/v22-release-announce

### Browser Name:

Arc

### Browser Version:

1.41.0 (49440)

### Operating System:

MacOS 14.4.1 (23E224)

### How to reproduce the issue:

The blog currently uses `word-break: break-all` for the body text. This seems like a bug to me. It makes it difficult to read the posts. I would recommend changing it to `word-break: normal`.

1. Go to https://nodejs.org/en/blog/announcements/v22-release-announce
2. Look at the end of each line of text. Many words will be chopped off, not even hyphenated.

It looks like it was introduced in #6680. I think that change was only supposed to affect small screens, like phones, but I am using a full desktop browser on a large screen and having the issue.

## Before
Notice the way that every line ends in a broken word.

![image](https://github.com/nodejs/nodejs.org/assets/8848080/2a98fbf1-56dd-45fd-b113-61130e5e3fe9)

## After (`word-break: normal`)
![image](https://github.com/nodejs/nodejs.org/assets/8848080/3fc8fc79-faeb-4263-9365-aa38f84c0eaa)

**Comment by AugustinMauroy** [comment]
I take a look to the pr and I didn't found any reason behind. so let's revert this change.

**Comment by AugustinMauroy** [comment]
> [!NOTE]
> On project we use tailwind so you I'll need to use [word-break](https://tailwindcss.com/docs/word-break)
