### ISSUE TITLE
Implement debouncing in search

### ISSUE THREAD

**Issue by rahulkhattri0** [nodejs/nodejs.org#6717]
![image](https://github.com/nodejs/nodejs.org/assets/72620481/bcce98af-d95b-40ca-bd19-90d71445aa8a)
1. Current behaviour is that every time the search text or the selected facet changes,we call the search api.
2. This useEffect can be improved by adding basic debouncing.

**Comment by mikeesto** [comment]
Thanks for the issue. There is some [history here](https://github.com/nodejs/nodejs.org/pull/6497) as to why it is this way. Unless the Orama folk ask us to change it, I don't think it will be.

**Comment by rahulkhattri0** [comment]
Ok I get it. Thanks for the explanation!

**Comment by rahulkhattri0** [comment]
I guess a comment with this issue link can be added in the code.

**Comment by rahulkhattri0** [comment]
Also, I feel this useEffect can be avoided because we just need to add the search logic in 2 event handlers, **which is not a lot** , IMO
The two places where this search needs to be added are:
1. `onChange={event => setSearchTerm(event.target.value)}` (in the search input)
2. `const changeFacet = (idx: string) => setSelectedFacet(Number(idx));` (where we change the facet)
and moreover, using `// eslint-disable-next-line react-hooks/exhaustive-deps` is not really a good practice

**Comment by rahulkhattri0** [comment]
@mikeesto please let me know what you think

**Comment by ovflowd** [comment]
Feel free to make a PR, @rahulkhattri0. 

cc @micheleriva

**Comment by micheleriva** [comment]
Hi there,
First of all, I strongly encourage everyone to use debounce. There's no real need, in my opinion... we are gifting unlimited searches to Node.js, and the front-end is not in trouble refreshing search results once every 100ms.

If you want to try debouncing search, you can use the Orama SDK itself:

```js
const searchConfig = {
  debounce: 250
}

await orama.search({
  term: 'hello world',
}, searchConfig)
```

But again, I don't see a real reason why a debouncer is needed :)

**Comment by rahulkhattri0** [comment]
@ovflowd ok so I'm removing the unnecessary useEffect and as @micheleriva is saying that that we don't need denouncing, so let it be that way.
