### ISSUE TITLE
Sync of Orama Search Indexes is broken on CI

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#6719]
In summary, the automatic compilation/build of the search index and upload to Orama cloud has been broken since always, and hence it always required me manually updating the search indexes.

On GitHub Actions the step runs, and succeeds but actually nothing happens/gets uploaded. We need to debug why and find a solution :)

**Comment by canerakdas** [comment]
Fixed with #6806, #6814 and #6824
