### ISSUE TITLE
having logo in pride style

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/nodejs.org#6733]
**Moderation note**: Hey, if you have issues with the project's decision here, please send them to [report@nodejs.org](mailto:report@nodejs.org) instead of opening new issues. That does not help the project and only constitutes of harassment.

-----

June 1 to June 30 is Pride, a month-long to celebrate LGBTQIA+ community.
I propose that we have our logo with the LGBTQIA+ flag. In order to bring an open support to all the community.

What can we do? I propose to have a code that checks if we are between two dates with `dateIsBetween` _already implemented_ if the condition is true we put the logo variant. I thinks we can just touch the nav logo.

Here logo:

<img width="593" alt="Capture d’écran 2024-05-22 à 09 39 23" src="https://github.com/nodejs/nodejs.org/assets/97875033/7d61010d-70bd-4917-9563-656a3834744b">

> [!NOTE]
> It's will not affect UX

**Comment by ovflowd** [comment]
cc @nodejs/nodejs-website and @kyliewd as it affects branding 👀

**Comment by ovflowd** [comment]
Also instead of a date checker, we can add the logo variants to the site config and simply upload the pride logos on our static folder, and during pride month swap those logos on the settings.

**Comment by AugustinMauroy** [comment]
> and during pride month swap those logos on the settings.

You're not wrong and it's reduce calculation, it just requires human action every time.

**Comment by kyliewd** [comment]
this is fine with me

**Comment by ovflowd** [comment]
Feel free to proceed with a PR, Augustin :)

**Comment by e3dio** [comment]
Hi all, I just went to Nodejs.org to look for some information and I see the Gay flag in the main Node logo. I wonder did someone deface the website, was it hacked ? I come here and see people actually planning this out. What does sexual orientation have to do with Node.js ? Why are we pushing gay sexual orientation into the Node.js logo ?

**Comment by egoroof** [comment]
what a shame! 💩

**Comment by marco-ippolito** [comment]
I believe @nodejs/tsc should have been informed about this

**Comment by benjamingr** [comment]
Hey, if you have issues with the project's decision here, please send them to report@nodejs.org instead of opening new issues. That does not help the project and only constitutes of harassment.

**Comment by benjamingr** [comment]
@marco-ippolito I absolutely agree and we should amend our process to require that in the future. I plan to raise it Wednesday on the TSC meeting.

**Comment by marco-ippolito** [comment]
I believe @nodejs/tsc should be notified when adding flags to the website
Edit: I mistakenly deleted comment from mobile.

**Comment by mcollina** [comment]
I'm sorry but this should have been run via the tsc.

**Comment by benjamingr** [comment]
I opened a governance change PR at https://github.com/nodejs/nodejs.org/pull/6772

**Comment by ovflowd** [comment]
This issue is locked, can we please not comment anymore here?

It genuinely doesn't make sense to keep commenting here. Appropriate governance changes are being held.
