### ISSUE TITLE
Offer n as an installation option on macOS and Linux

### ISSUE THREAD

**Issue by shadowspawn** [nodejs/nodejs.org#6738]
### Enter your suggestions in details:

The new download page is very spiffy! https://nodejs.org/en/download/package-manager

I maintain [n](https://github.com/tj/n) which last year was the second most popular node version manager in the [next-10 2023](https://github.com/nodejs/next-10/tree/main/surveys/2023-04) survey.

I am interesting in including `n` in the download options, but have seen there are multiple things in consideration such as permissions and major-only vs version managers:
- https://github.com/nodejs/package-maintenance/issues/591
- https://github.com/nodejs/nodejs.org/pull/6720

Are you open to a PR now (like [fnm](https://github.com/nodejs/nodejs.org/pull/3645)), or should I wait a few weeks while other discussions progress?

**Comment by ovflowd** [comment]
Hey there 👋 appreciate your suggestion, but `n` is already listed [here](https://nodejs.org/en/download/package-manager/all); Our goal with the main Package Manager download options is to list only very few options that are either the utmost used version manager for the most available OSs;

In this category `fnm` and `nvm` are the top candidates; I assume `fnm` would have gotten more votes than `n` if there was an option for `fnm`; Based on the preliminary results of 2024's survey results, `fnm` is the most used so far, in par with `nvm` (https://github.com/nodejs/nodejs.org/pull/6720#issuecomment-2118102617)

We also want to limit the options to reduce confusion; The more options we show, the lesser the user will know what the hell to use and will give up, hence at most 2 options are shown. `fnm` is included by being the only options that supports all main OSs (Windows, Linux, macOS);

Although that's pretty much personal maintainer's decision, we're in the process of reorganising the package managers and version managers tab (as described in the comments of the same PR) and that might allow room for `n` in the future. Having that said, we don't have a concrete process on how to accept entries on this main page, and I definitely know that having your project showcased there could potentially increase the visibility of your project, but ultimately I'm making the "maintainer's decision" for the time being, on holding back additions of other version managers.

I'm closing this as "wont-fix" as we won't address this now, but feel free to share your opinion, reply here, and etc. Note that this is my personal opinion and might not reflect on the other collaborator's opinions.

**Comment by shadowspawn** [comment]
Showing the most popular and the most popular cross-platform is a pragmatic approach to limit the options. Thanks for the explanation.

> In this category fnm and nvm are the top candidates; I assume fnm would have gotten more votes than n if there was an option for fnm; Based on the preliminary results of 2024's survey results, fnm is the most used so far, in par with nvm (https://github.com/nodejs/nodejs.org/pull/6720#issuecomment-2118102617)

That link is to a comment with the last years results? However, fnm was the most mentioned cross-platform version manager, getting more mentions in the Other category than `nvs` got direct votes in the multi-choice.

> `fnm` is included by being the only options that supports all main OSs (Windows, Linux, macOS);

For interest, `nvs` and `vfox` are both all-main-OSs version managers listed on the [package managers](https://nodejs.org/en/download/package-manager/all) page. I also often see [Volta](https://volta.sh) mentioned, which is a multiple product version manager rather than focused on node.

Both `fnm` and `volta` are listed in the multi choice on the [PR](https://github.com/nodejs/next-10/pull/261/files) for this years survey, so there will be a more level playing field for comparing numbers, for what they are worth!

**Comment by ovflowd** [comment]
> That link is to a comment with the last years results?

You are correct, I misunderstood, Geoffre's statement, it gave the impression he was sharing the partial results of this year's poll.

> For interest, nvs and vfox are both all-main-OSs version managers listed on the package managers page.

I was referring from top-to bottom in terms of usages. Definitely there are other version managers that suit most main OSs.

> Both fnm and volta are listed in the multi choice on the PR for this years survey, so there will be a more level playing field for comparing numbers, for what they are worth!

Looking forward for these results. On a different note, I wonder how much of these results actually match on real demographics. My fear is of adding way too many version managers, and people getting lost.

The download process should be quick and to the point; IMO we have two version managers there just to cover all main OSs there, personally Im not concerned about popularity of version managers and my intent here is not to "promote them", but just to provide well known and reliable ways of installing Node.

If nvm supported natively all main OSs, it would have been the only one to be mentioned there. It's less burden for us to maintain, check if they are up to date, maintained, supporting Node well, including latest versions and all sorts of things. So we are strongly focusing on a reliability and streamlined approach here for users to install Node, if that makes sense.

**Comment by ovflowd** [comment]
@shadowspawn just an update here :) we might reconsider this in the future, as we're planning on separating version managers from OS package managers. We're still thinking how to achieve such a design without overcomplexities.

But I'll let you know once we're ready to accept a PR for `n` :bow:

**Comment by sagarpanchal** [comment]
@ovflowd 
<img width="1439" alt="image" src="https://github.com/nodejs/nodejs.org/assets/6555461/6d5471c2-a06b-46ee-b126-38aa5c56a743">

**Comment by ovflowd** [comment]
@bmuenzenmeyer @canerakdas @AugustinMauroy recent changes broke this page. Please give urgent attention to this 🙏

**Comment by bmuenzenmeyer** [comment]
@sagarpanchal  a screenshot on an unrelated issue is not an issue report. 
please open a new issue and report steps to reproduce

the site is working for me on Chrome and Firefox

**Comment by ovflowd** [comment]
> @sagarpanchal  a screenshot on an unrelated issue is not an issue report. 
> 
> please open a new issue and report steps to reproduce
> 
> 
> 
> the site is working for me on Chrome and Firefox
> 
> 
> 
> 

Correct, although Im able to reproduce on nodejs.org/en/download/package-manager/all
