### ISSUE TITLE
Add Background Color Transition to Header Buttons

### ISSUE THREAD

**Issue by SantyDeale** [nodejs/nodejs.org#6752]
### Enter your suggestions in details:

1. Hovering the mouse over the buttons (Learn About Download Blog Docs Certification) makes a background color change transition like the footer buttons (Trademark Policy Privacy Policy Code of Conduct Security Policy)
2. Ensure consistency with the header and footer buttons
3. Add the same background transition to the header buttons

**Comment by Wellitsabhi** [comment]
@SantyDeale  this issue is still marked as OPEN
