### ISSUE TITLE
Enhancement: Breadcrumb breakpoint

### ISSUE THREAD

**Issue by TenzDelek** [nodejs/nodejs.org#6754]
## Issue
some of the  breadcrumb that are long have a inconsistent layout.
resulting in some layout shifting of the breadcrumb detail.
<img width="629" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/521a2599-81d0-4f60-9e89-55421d3b2516">
<img width="648" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/47a7759d-5143-410a-8a9c-fa7a2b01c65b">

also in some case, the layout is breaking down like this below:
<img width="698" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/f5e51553-05db-4ef5-998f-347307364a73">
ref:
1. https://nodejs.org/en/learn/getting-started/nodejs-the-difference-between-development-and-production
## idea
Proposal: creating a breakpoint function of till 4 word (seems ideal when i tried) 
## Solution preview
- only trigger the breakpoint when the word count excede 4
<img width="634" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/cc757aae-22b9-4d32-a6e3-784ca73b5053">
<img width="547" alt="image" src="https://github.com/nodejs/nodejs.org/assets/122612557/689e3f9d-1d66-41b4-bdcf-6bd5f3e585a3">

**Comment by ovflowd** [comment]
I believe we can set the width to 100% and simply add ellipsis in case the title is too long.

We also added a breakpoint that for small screens only the last node would show. But that seems to not be enough of course.

I don't think we should have line breaks, but have "..." when the text is too long 👀

**Comment by TenzDelek** [comment]
> I believe we can set the width to 100% and simply add ellipsis in case the title is too long.
> 
> We also added a breakpoint that for small screens only the last node would show. But that seems to not be enough of course.
> 
> I don't think we should have line breaks, but have "..." when the text is too long 👀

definitely that sounds great. will implement that instead of the line break 👍
