### ISSUE TITLE
Refactor the nodejs logo component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6768]
I'm thinking we get this released sooner rather than later, even if we aren't in complete alignment on the approach. 

_Originally posted by @bmuenzenmeyer in https://github.com/nodejs/nodejs.org/pull/6734#issuecomment-2143461166_

**Comment by AugustinMauroy** [comment]
@jasnell why did you close it ?

**Comment by jasnell** [comment]
Oh, I think that was accidental.
