### ISSUE TITLE
Gay flag in Node.js logo ?

### ISSUE THREAD

**Issue by e3dio** [nodejs/nodejs.org#6771]
### Enter your suggestions in details:

I asked a simple question for an explanation of why the Gay flag is in the Node.js logo, and my question was hidden and the conversation was locked down ? Was there any discussion about this before or did a couple people force this thru without a consensus ? Is there any reason we are forcing kinky sexual orientation onto every person who visits the website for a JavaScript runtime ?

![Screenshot_20240602-091921](https://github.com/nodejs/nodejs.org/assets/85405955/34b82b9b-4a5e-4799-ac0b-a00a022d9aad)

**Comment by AugustinMauroy** [comment]
1. It's not a gay flag, I'd ask you to rethink the subject before opening an issue. It's the flag/symbol of the LGBTQIA++ community.
2. We added it to support the cause. Because the nodejs project is open to everyone's inclusivity.
