### ISSUE TITLE
Requesting the Previous NodeJS Logo Instead of the Current One

### ISSUE THREAD

**Issue by rakibul-dev** [nodejs/nodejs.org#6776]
### Enter your suggestions in details:

I think the previous logo on Node's official site looked nicer than the current one.
The current logo has a meaning other than NodeJS. 
I hope the previous logo will be used again.

**Comment by bmuenzenmeyer** [comment]
This logo is a temporary acknowledgement of Pride Month and LBTQIA inclusivity.
