### ISSUE TITLE
Shouldn't Tech Logos Remain Gender-Neutral?

### ISSUE THREAD

**Issue by foyzulkarim** [nodejs/nodejs.org#6778]
### URL:

https://nodejs.org/en

### Browser Name:

Chrome

### Browser Version:

125.0.6422.113

### Operating System:

Mac

## Should Tech Logos Remain Gender-Neutral?

Why can't tech frameworks be gender-neutral? While many people identify as part of the LGBT community, we must remember that there are billions who don't and may not feel the same way. If Node.js or any other framework isn't explicitly biased towards any gender, why should its logo be changed to support various gender identities?

**Can't we keep tech logos purely neutral?**

**Comment by sakibb7** [comment]
**I NodeJS team will consider these points and maintain a simple, inclusive, and neutral approach to their logos.**

**Comment by shamim-42** [comment]
I am strongly raising my voice agreeing this issue title. There are billions of people who don't feel like LG**Q. So, tech platform should be gender neutral. Nodejs maintainers should consider the thought.

**Comment by said7388** [comment]
Billions of people do not identify as LG**Q. I hope the Node.js team will consider these points and maintain a simple, inclusive, and neutral approach to their logos.

**Comment by foyzulkarim** [comment]
I saw the note:
`Moderation note: Hey, if you have issues with the project's decision here, please send them to [report@nodejs.org](mailto:report@nodejs.org) instead of opening new issues. That does not help the project and only constitutes of harassment.`

Will send the email soon.

**Comment by sayid2kx** [comment]
Remove the LGBT logo from the Nodejs website
