### ISSUE TITLE
Re-enable turbo flag in dev script

### ISSUE THREAD

**Issue by mikeesto** [nodejs/nodejs.org#6808]
We had to disable the `--turbo` flag in the development script due to an error when updating to Nextjs 14.2 (https://github.com/nodejs/nodejs.org/pull/6803). It would be good to re-enable it once the underlying issue is resolved.

**Steps to Reproduce**
1. Enable the `--turbo` flag in the dev script.
2. Run the development server.

```
Error: Expected process result to be a module, but it was ignored

Debug info:
- Execution of get_written_endpoint_with_issues failed
- Execution of <AppEndpoint as Endpoint>::write_to_disk failed
- Execution of Project::emit_all_output_assets failed
- Execution of VersionedContentMap::insert_output_assets failed
- Execution of all_assets_from_entries failed
- Execution of AppEndpointOutput::output_assets failed
- Execution of AppEndpoint::output failed
- Execution of ClientReferenceGraph::entry failed
- Execution of ClientReferenceGraph::new failed
- Execution of primary_referenced_modules failed
- Execution of <ModuleCssAsset as Module>::references failed
- Execution of ModuleCssAsset::module_references failed
- Execution of ModuleCssAsset::classes failed
- Execution of process_css_with_placeholder failed
- Execution of parse_css failed
- Execution of <PostCssTransformedAsset as Asset>::content failed
- Execution of PostCssTransformedAsset::process failed
- Execution of evaluate_webpack_loader failed
- Execution of Completions::completed failed
- Execution of any_content_changed_of_module failed
- Execution of ProcessResult::module failed
- Expected process result to be a module, but it was ignored
```

**Expected Behavior**
The development server should run without errors with the `--turbo` flag enabled.

**Comment by ovflowd** [comment]
Thanks for opening this!

**Comment by styfle** [comment]
@ovflowd I believe this will be fixed in https://github.com/vercel/turbo/pull/8303

@wbinnssmith Do you know when this fix will be available in Next.js?

**Comment by styfle** [comment]
This has been fixed in canary, thanks!

https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.13

**Comment by ovflowd** [comment]
> This has been fixed in canary, thanks!
> 
> 
> 
> https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.13

Will it be backported to 14x?

**Comment by ovflowd** [comment]
Because I'm not sure what other sort of breaking changes we need to 👀 for Next.js v15

**Comment by styfle** [comment]
I spoke to @ztanner and we are expecting to release a patch to v14 sometime in the next week or two.

**Comment by neslob** [comment]
still happing in 14.2.4 (turbo), for me.

**Comment by ovflowd** [comment]
> still happing in 14.2.4 (turbo), for me.

You should report this as a bug on Vercel's turbo repository, not here :)
