### ISSUE TITLE
Adding 2 buttons to minimize the sidebars on nodejs > learn "docs

### ISSUE THREAD

**Issue by kshitjj** [nodejs/nodejs.org#6811]
## What is the problem this feature will solve?

the sidebars are not minimizable, which causes the body to have less width, which cramps the body.

![image](https://github.com/nodejs/nodejs.org/assets/50615534/0abf9f80-926d-45eb-b13d-659e0ff47bd4)

## What is the feature you are proposing to solve the problem?

adding two buttons, which would allow a dev to minimize the sidebars.

**Comment by dtsuper3** [comment]
@ovflowd can we use an arrow icon as content for the buttons?

**Comment by ovflowd** [comment]
I'd say so? But we could use `arrow-left-end-on-rectangle` and `arrow-right-end-on-rectangle` from https://heroicons.com/

**Comment by dtsuper3** [comment]
@ovflowd This feature to minimize the sidebar requires client-side interactivity due to that reason we have to introduce a state to control whether the sidebar is minimized. Can I use "use client" in LearnLayout? I will then add a new class in ArticleLayout based on this state to control the grid widths.
<img width="1679" alt="Untitled" src="https://github.com/nodejs/nodejs.org/assets/32347879/7b030ada-b04e-4a55-b9fc-7bd01e1862dd">

**Comment by ovflowd** [comment]
Hmmm, wouldn't add an use client on the Metabar and the Sidebar components be enough? 👀

**Comment by bmuenzenmeyer** [comment]
I'm also curious how this effort may relate to https://github.com/nodejs/nodejs.org/pull/6821

**Comment by abizek** [comment]
#6821 modifies the default behavior while this behavior is opt-in (hide the sidebar if needed). It seems like we are going with open as the default sidebar state here. #6821 also keeps the metabar below the article up to a larger breakpoint than before to give more space to the article. Sidebar controls could still be used on the left sidebar in that case.

I'm actually curious to see where the state control buttons will be placed (in both open and closed states) without appearing clunky or crowding the header as we are not moving the sidebars up in z axis here and the sidebar state affects the width occupied by the article.

**Comment by ovflowd** [comment]
I believe, as @abizek, the best approach would be for #6821 to be the default behavior. And then the feature described on this issue only works on non-mobile screens.

And if you hide the meta bar/sidebar, well, on mobile screens, they become respectively on the bottom of the article and the select button.

**Comment by ovflowd** [comment]
Do we still want to follow-up here? Or was #6821 enough?

**Comment by kshitjj** [comment]
#6821 fixes the issue
