### ISSUE TITLE
Responsiveness issues between 670px and 1023px

### ISSUE THREAD

**Issue by JakobJingleheimer** [nodejs/nodejs.org#6819]
### URL:

https://nodejs.org/en/learn

### Browser Name:

Brave

### Browser Version:

Version 1.66.115 Chromium: 125.0.6422.112 (Official Build) (arm64)

### Operating System:

macOS 14.5

### How to reproduce the issue:

<img width="716" alt="squashed layout" src="https://github.com/nodejs/nodejs.org/assets/3012099/efb468bd-3eed-4c16-a062-e44a802ae8d2">

When the viewport is between 670px and 1023px (such as when 2 browser windows are split-screen), the layout is kinda b0rked (the main content area is heavily cropped (especially code-blocks).

I would expect the left menu and right sidebar to somehow collapse, which leaves enough space:
<img width="716" alt="no sidebars" src="https://github.com/nodejs/nodejs.org/assets/3012099/6bae27e4-fce6-4e65-bf1d-5f48868eb52e">

**Comment by abizek** [comment]
Would you say this is better?

<video src="https://github.com/nodejs/nodejs.org/assets/91976421/0b0de0a8-da3c-4e47-a3af-713390d155f9" >

**Comment by ovflowd** [comment]
> Would you say this is better?
> 
>  after-responsiveness.mp4

Looks way better ❤️
