### ISSUE TITLE
add 'use strict' in documentation for ES6 classes

### ISSUE THREAD

**Issue by gh-amistry** [nodejs/nodejs.org#682]
Examples in the "Events" section of the documentation relating to newly introduced ES6 functionality, like classes, don't work unless strict mode is specified, but `'use strict'`doesn't appear in the example.

My suggestion is to include `'use strict'` in these examples so that the code can simply be copied and pasted as-is and run as working examples.

**Comment by jasnell** [comment]
SGTM. Interested in submitting a PR? :-)

**Comment by evanlucas** [comment]
IIRC that will no longer be an issue once v6 drops, but a good idea IMO

**Comment by gh-amistry** [comment]
@jasnell Sure - it will be my first one - Is that cool?

**Comment by gh-amistry** [comment]
Where do I find this content in the repo?
https://nodejs.org/dist/latest-v5.x/docs/api/events.html

**Comment by phillipj** [comment]
@gh-amistry https://github.com/nodejs/node/blob/master/doc/api/events.md :)

**Comment by gh-amistry** [comment]
@phillipj Thanks!

**Comment by phillipj** [comment]
@gh-amistry np! I'm closing this issue for now, but don't hesitate to comment here if you've got any questions. See you in the node repo.
