### ISSUE TITLE
Download stats stopped after `2024-05-02`

### ISSUE THREAD

**Issue by Electroid** [nodejs/nodejs.org#6822]
### URL:

https://storage.googleapis.com/access-logs-summaries-nodejs/index.html

### Browser Name:

N/A

### Browser Version:

N/A

### Operating System:

N/A

### How to reproduce the issue:

There are no more download logs after: `https://storage.googleapis.com/access-logs-summaries-nodejs/nodejs.org-access.log.20240502.json`.

**Comment by bmuenzenmeyer** [comment]
Sorry.  I'm not familiar with this data set. Can you tell me more about its provenance?

**Comment by mikeesto** [comment]
This is handled by the build team: https://github.com/nodejs/build/tree/main/ansible/roles/metrics . Feel free to open an issue there - thanks.

**Comment by richardlau** [comment]
This is being tracked in https://github.com/nodejs/build/issues/3697.
