### ISSUE TITLE
Footer missing on Learn layout

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6829]
https://nodejs.org/en/learn/getting-started/introduction-to-nodejs

![Screenshot_20240610_181426_Chrome.jpg](https://github.com/nodejs/nodejs.org/assets/298435/9a808139-5baa-4e5f-98f8-f9e895bcec2c)

**Comment by mikeesto** [comment]
Same on About too https://nodejs.org/en/about

**Comment by Wellitsabhi** [comment]
footer missing in 'About and 'Learn"  layout , already on it,raising PR

**Comment by ovflowd** [comment]
Id say these pages are following the figmas, which have no footer. Now, not sure if we should add or not :shrug: 

Im fine eitherways.

**Comment by bmuenzenmeyer** [comment]
I noticed that too but it looks REALLY out of place to me to selectively render a global component. I am surprised it didn't come up earlier, TBH.

**Comment by rakeshkumar1019** [comment]
@bmuenzenmeyer raised pr for this issue https://github.com/nodejs/nodejs.org/pull/6949.
can you review the PR.

**Comment by velu-murugesan** [comment]
Can you please assign this project or if it is assigned for someone please give me another issue I am new to open source is there any advice or roadmap that is appreciatable
