### ISSUE TITLE
Wrong Node versions in the link text content

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/nodejs.org#684]
I don't know, if it is so important before v6 release tomorrow, but just to be on the safe side.

Now [in this page](https://nodejs.org/en/docs/) in the left toc column the "v4.4.2 API LTS" link actually directs to "Node.js v4.4.3 Documentation", and the "v5.10.1 API" link actually directs to "Node.js v5.11.0 Documentation".

I does not dare to create a PR because I'm not familiar with all the templates and localization things involved. Sorry.

**Comment by fhemberger** [comment]
This has just been fixed by @tianp, I'm keeping this ticket open as a reminder for the 6.0 release.

Maybe we can modify `scripts/plugins/navigation.js` to pull the current Node.js versions and inject them into the navigation template.

**Comment by detailyang** [comment]
+1 agree with @fhemberger, but how to get the current correct Node.js versions?

**Comment by fhemberger** [comment]
We have a script for that: https://github.com/nodejs/nodejs.org/blob/master/build.js#L243

**Comment by phillipj** [comment]
+1 to improving the navigation generator so we don't have to update our `locale/*/site.json` files every time a new version gets released. IIRC there's nothing else on the website that needs to be updated cause of new releases.
