### ISSUE TITLE
Certain languages break the max height of the search bar

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#6841]
### URL:

https://nodejs.org/pt or https://nodejs.org/fr

### Browser Name:

Chrome

### Browser Version:

N/A

### Operating System:

N/A

### How to reproduce the issue:

1. Switch to a Localized Language
2. You'll notice that the search bar height is not respected

**Comment by nilkhankari** [comment]
Can I work on resolving this issue?

**Comment by bmuenzenmeyer** [comment]
Thanks for your interest. We don't assign tickets if we can help it. Feel free to submit a pull request if you have time.
Reference 🍪 https://www.redhat.com/en/blog/dont-lick-cookie

As an implementation suggestion, I'd explore expanding the available space on large viewports. There is plenty.

![image](https://github.com/nodejs/nodejs.org/assets/298435/0ee29ca9-9a73-4237-a4aa-146cc4425f9a)

**Comment by nilkhankari** [comment]
Thanks! Yes, we can fix this by increasing the width. I'll work on it and submit a PR as soon as possible.
