### ISSUE TITLE
Add translations of snippet comments from Download Package Manager boxes

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#6849]
The snippets below are defined on a TypeScript file and shown below:

![image](https://github.com/nodejs/nodejs.org/assets/12037269/35b79bf9-6640-43eb-8054-1fe2f1e88107)

We can call the translation service (t) and include translation strings within the i18n JSON files for such comments; otherwise, it feels like the translation is lacking here.

**Comment by PalashChitnavis** [comment]
Hey, can I work on this issue?  
Could you explain the issue and the approach?

**Comment by bmuenzenmeyer** [comment]
Thanks for your interest. We don't assign tickets if we can help it. Feel free to submit a pull request if you have time.
Reference 🍪 https://www.redhat.com/en/blog/dont-lick-cookie

**Comment by AugustinMauroy** [comment]
@bmuenzenmeyer Hello, they weren't asking to be assigned an outcome, they were asking for guidance 😁.

So @PalashChitnavis, in [`util/getNodeDownloadSnippet.ts`](https://github.com/nodejs/nodejs.org/blob/main/util/getNodeDownloadSnippet.ts) you have a function that return string to put on codebox. So issue "ask" to add i18n for comment. To add i18n on a string you I'll need to use client hooks from next-intl call [`useTranslation`](https://next-intl-docs.vercel.app/docs/usage/messages).

Also we have this doc about how to contribute on this repo : [`COLLABORATOR_GUIDE.md`](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md)

**Comment by bmuenzenmeyer** [comment]
To be fair, they did both. On mobile i answered too quickly,  thanks for giving them next steps!

**Comment by nilkhankari** [comment]
Hey @PalashChitnavis , Could you please let me know if you are working on this? else I will look into it.
Thanks

**Comment by AugustinMauroy** [comment]
@nilkhankari I think you can go head
