### ISSUE TITLE
Misleading debugging information: "Node.js and the Chrome need to be run on the same platform"

### ISSUE THREAD

**Issue by june07** [nodejs/nodejs.org#6853]
### URL:

https://nodejs.org/en/learn/getting-started/debugging

### Browser Name:

Chrome

### Browser Version:

126.0.6478.62

### Operating System:

Windows

### How to reproduce the issue:

![Screenshot 2024-06-20 154224](https://github.com/nodejs/nodejs.org/assets/11353590/01857f4c-08c2-418a-b99a-a27e31788cd8)

Since when has this been the case?!

The requirement that Node.js and Chrome need to be run on the same platform is not accurate in the context of debugging. Cross-platform debugging using Chrome DevTools is a standard practice and works seamlessly due to the underlying network and WebSocket protocols that facilitate communication between Node.js and DevTools. The documentation should ideally clarify this to avoid confusion.

I have no idea why this was added in the first place...
https://github.com/nodejs/nodejs.org/commit/15774e7744da60bb418aa1ee14f5d88b7b9cda1e

**Comment by ovflowd** [comment]
Please feel free to open a PR to fix this; I also have no record of why this was merged/added. This was before my time on the project.

**Comment by Wellitsabhi** [comment]
should i just remove that portion ??
will that be it.
