### ISSUE TITLE
More messaging on the front page?

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#686]
I think it might be a good idea to redo the content on the front page to say a bit more about _what_ Node.js is, _why_ people use it, and _what_ they are doing with it.

We have a lot of new and solid messaging around this now like "Node.js Everywhere" and "The New FUll Stack" that we can lean on, along with some good new art like this:

![full](https://cloud.githubusercontent.com/assets/579/14801194/633f2396-0afc-11e6-98df-24fa2bd06a03.png)

Thoughts?

**Comment by saadq** [comment]
Would it be better to move this issue [here](https://github.com/nodejs/nodejs.org-new/issues)?

**Comment by Trott** [comment]
Closing as stale/inactive but also something the website redesign folks are no doubt considering.
