### ISSUE TITLE
Broken link to "An Introduction to Linux Block I/O"

### ISSUE THREAD

**Issue by andresakata** [nodejs/nodejs.org#6861]
### URL:

https://nodejs.org/en/learn/asynchronous-work/dont-block-the-event-loop

### Browser Name:

Chrome

### Browser Version:

125.0.6422.176

### Operating System:

MacOS

### How to reproduce the issue:

On this page, there is a link to "http://researcher.ibm.com/researcher/files/il-AVISHAY/01-block_io-v1.3.pdf". However, this link is not working anymore. You can still find it on the [webarchive](https://web.archive.org/web/20210401062443/https://researcher.watson.ibm.com/researcher/files/il-AVISHAY/01-block_io-v1.3.pdf), but I couldn't find the actual location for this content (if there is any).

**Comment by mikeesto** [comment]
Thanks. I wasn't able to find a live version either. I guess the question is do we remove the link, or do we link to the wayback machine. It's being referenced in the context of an example so I'm leaning towards removing it - but welcome to other thoughts

**Comment by andresakata** [comment]
An alternative is to reference the [IO schedulers documentation from Ubuntu Wiki](https://wiki.ubuntu.com/Kernel/Reference/IOSchedulers) if we want to keep the example.

**Comment by Wellitsabhi** [comment]
Hi, I want to contrubute in this issue. 
Should i update it with new link as given by @andresakata, or remove it.

**Comment by andresakata** [comment]
I'm in favor of removing the example. I just read the paragraph again, and the explanation of I/O-intensive tasks and its implications are well covered.

**Comment by ovflowd** [comment]
Feel free to open a PR :)
