### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by andresakata** [nodejs/nodejs.org#6862]
### Affected URL(s)

https://nodejs.org/en/learn/asynchronous-work/dont-block-the-event-loop

### Description of the problem

On this page, there is a link to "http://researcher.ibm.com/researcher/files/il-AVISHAY/01-block_io-v1.3.pdf". However, this link is not working anymore. You can still find it on the [webarchive](https://web.archive.org/web/20210401062443/https://researcher.watson.ibm.com/researcher/files/il-AVISHAY/01-block_io-v1.3.pdf), but I couldn't find the actual location for this content (if there is any).

**Comment by avivkeller** [comment]
Hi! This repo is for issues with the Node.js core or documentation. For issues with the website (and `learn`), please refer to https://github.com/nodejs/nodejs.org

CC @nodejs/web-infra

**Comment by bmuenzenmeyer** [comment]
@RedYetiDev in the future, these issues can be transferred too. I thought a triager could do that, but I'd have to double-check

![image](https://github.com/nodejs/node/assets/298435/c36bb5ca-7263-412b-8ab9-87cc4cc1e5f6)

**Comment by avivkeller** [comment]
Oh, okay. Sorry for the mistake.

(FWIW we can't do that)

**Comment by MattIPv4** [comment]
(Also, not to pile on, but web-infra feels like the wrong ping? There should be a team for the website itself, not the infrastructure?)

**Comment by ovflowd** [comment]
Yes, the right ping is `@nodejs/nodejs-website`

**Comment by bmuenzenmeyer** [comment]
#6861 is a cleaner copy of this - closing this one as the duplicate :D
