### ISSUE TITLE
Navigation Anomalies on Node.js API Documentation Website

### ISSUE THREAD

**Issue by bukowa** [nodejs/nodejs.org#6869]
### URL:

https://nodejs.org/api/test.html

### Browser Name:

Chrome

### Browser Version:

126.0.6478.127

### Operating System:

Windows 10

### How to reproduce the issue:

![lol](https://github.com/nodejs/nodejs.org/assets/38087302/5df31e45-0218-4eef-8da5-800e32e040ea)

1. Go to https://nodejs.org/api/test.html
2. Click on any link.
3. You will realize it scrolls somewhere else.
4. Click on any link.
5. You will realize it forwards you to the correct one. (probably something with #hash in the url)

P.S No idea why the header is not at the top.

![8bb3a4d1f9729410967d1847a0cf9976](https://github.com/nodejs/nodejs.org/assets/38087302/027ff4ef-6c36-4c38-97f6-99147b1f5c03)

**Comment by mikeesto** [comment]
Thanks for raising, but the API documentation is not part of this repo. I think this may be potentially resolved in https://github.com/nodejs/node/pull/53662 ?

**Comment by bukowa** [comment]
> Thanks for raising, but the API documentation is not part of this repo. I think this may be potentially resolved in [nodejs/node#53662](https://github.com/nodejs/node/pull/53662) ?

Thank you.
