### ISSUE TITLE
v22.4.0 release blog post missing after pull 6850 "Scaffold multi-package workspace."

### ISSUE THREAD

**Issue by Waldenesque** [nodejs/nodejs.org#6894]
### URL:

https://nodejs.org/en/blog/release

### Browser Name:

Chrome / irrelevant

### Browser Version:

126.0.6478.127 / irrelevant

### Operating System:

Windows 10 version 10.0.19045.4529 / irrelevant

### How to reproduce the issue:

https://github.com/nodejs/nodejs.org/pull/6850

Looks like somehow this inadvertently deleted the release blog post for Node v22.4.0.

**Comment by AugustinMauroy** [comment]
the post wasn't remove https://nodejs.org/en/blog/release/v12.22.4/
it's a display bug
