### ISSUE TITLE
Commitizen is a terrible experience on Windows

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6900]
If I use VSCode's panel, it errors out because it is not interactive.
If I use the CLI I get this.
![image](https://github.com/nodejs/nodejs.org/assets/298435/d07c21b8-750c-4e2c-bcc1-ab8e2c159941)

This is actively worsening the contributing environment.

There are ways to enforce semantic versioning, like [changesets](https://github.com/changesets/changesets) or [auto](https://intuit.github.io/auto/docs), that don't force git commit conventions.

**Comment by ovflowd** [comment]
Afaik, we've removed cz from the Git Hooks for the time being since it was breaking multiple users workflows.

It is unfortunate as the original author spent so much time on this here.
