### ISSUE TITLE
issue: `searchButton` component breaks visually on portuguese website.

### ISSUE THREAD

**Issue by nazarepiedady** [nodejs/nodejs.org#6903]
### URL:

https://nodejs.org/pt

### Browser Name:

Mozilla Firefox

### Browser Version:

Version 127.0.2 (64-bit)

### Operating System:

Lubuntu 22.04.4 LTS x86_64

### How to reproduce the issue:

1. Toggle the language to a different language than English, more specifically Portuguese.

**Comment by mikeesto** [comment]
Thanks. I think this is the same as https://github.com/nodejs/nodejs.org/issues/6841 . There is also an open PR that is attempting to modify the width. Feel free to contribute there. I will close this issue.

**Comment by nazarepiedady** [comment]
@mikeesto, thanks for your immediate review, I already created a pull request to solve this visual issue and referred to the older issue to show that the modification is coming to fix both issues.
