### ISSUE TITLE
Page tends to scroll up on "trying" to select

### ISSUE THREAD

**Issue by sauhardh** [nodejs/nodejs.org#6906]
### URL:

https://nodejs.org/docs/latest/api/child_process.html

### Browser Name:

Firefox

### Browser Version:

127.0.2 (64-bit)

### Operating System:

Ubuntu Linux

### How to reproduce the issue:

1) Tried to select the text.
2) page scrolls up.
3) it should not be scrolling that too sensitively, should it? 
(this usually happens when i try to select the text that are above halfway through the view port height but does not occur below it)

**Comment by sauhardh** [comment]
i don't know if it is feature or bug but could be really annoying if it is occurring to everyone.

**Comment by mikeesto** [comment]
Thanks. The API documentation does not live in this repo. There is an [open PR](https://github.com/nodejs/node/pull/53662) in `nodejs/node` that is attempting a fix
