### ISSUE TITLE
Fix "Edit this page" links

### ISSUE THREAD

**Issue by isaacs** [nodejs/nodejs.org#6912]
### URL:

https://nodejs.org/en/about/previous-releases

### Browser Name:

N/A

### Browser Version:

N/A

### Operating System:

all

### How to reproduce the issue:

I can't send a PR, because GitHub thinks I already have a fork. (Perhaps this was originally mine from back in the day? I'm not sure.)

Anyway, here's the patch, which can be landed with `git am`: https://gist.github.com/isaacs/5e168ac0ab5df0fead2dffa98c719eb9

```patch
From 0536a49691e13aa2c858770a447657332c07a3c9 Mon Sep 17 00:00:00 2001
From: isaacs <i@izs.me>
Date: Mon, 8 Jul 2024 10:32:06 -0700
Subject: [PATCH] fix: correct 'Edit this page' links

---
 apps/site/util/gitHubUtils.ts | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/apps/site/util/gitHubUtils.ts b/apps/site/util/gitHubUtils.ts
index 3abf386b..813eaada 100644
--- a/apps/site/util/gitHubUtils.ts
+++ b/apps/site/util/gitHubUtils.ts
@@ -10,7 +10,7 @@ export const createGitHubSlugger = () => {
 };
 
 export const getGitHubBlobUrl = (filename: string) =>
-  `https://github.com/nodejs/nodejs.org/blob/main/pages/en/${filename}`;
+  `https://github.com/nodejs/nodejs.org/blob/main/apps/site/pages/en/${filename}`;
 
 export const getGitHubApiDocsUrl = (ref: string) =>
   `https://api.github.com/repos/nodejs/node/contents/doc/api?ref=${ref}`;
-- 
2.39.3 (Apple Git-146)

```

**Comment by isaacs** [comment]
@AugustinMauroy tagging this as "help wanted" or "good first issue" is a bit weird, isn't it? The patch is right there, just needs someone other than me to make the PR and/or land it.

Though, idk, maybe that is the help I'm wanting, and "the patch is already written" does make it a pretty trivial first issue. 🤔

**Comment by AugustinMauroy** [comment]
I put the tag for someone to do it. Be you if you find a solution. If not something else.

**Comment by ovflowd** [comment]
Thank you for the patch, @isaacs! (Good catch btw!)
Augustin, I think you misunderstood Isaac's statement. 
Isaac, I'm landing this now.

**Comment by ovflowd** [comment]
Landed on fd327e872da0a9293cebc31c506b26b43e0a6095

**Comment by isaacs** [comment]
Yeah, I'm not sure why GitHub won't let me fork this repo.

**Comment by ovflowd** [comment]
> Yeah, I'm not sure why GitHub won't let me fork this repo.

I found your fork: https://github.com/isaacs/new.nodejs.org

**Comment by bmuenzenmeyer** [comment]
> > Yeah, I'm not sure why GitHub won't let me fork this repo.
> 
> I found your fork: https://github.com/isaacs/new.nodejs.org

"This branch is [5090 commits behind](https://github.com/isaacs/new.nodejs.org/compare/master...nodejs%3Anodejs.org%3Amain) nodejs/nodejs.org:main." 😅
