### ISSUE TITLE
NPM should be lower case

### ISSUE THREAD

**Issue by MikeMcC399** [nodejs/nodejs.org#6917]
### Enter your suggestions in details:

URL https://nodejs.org/en/download/package-manager

Multiple instructions include the line:

> verifies the right NPM version is in the environment

This is not aligned with npm's branding which states on https://github.com/npm/cli#faq-on-branding:

> #### Is it "npm" or "NPM" or "Npm"?

> **`npm`** should never be capitalized unless it is being displayed in a location that is customarily all-capitals (ex. titles on `man` pages).

This should be changed to:

> verifies the right npm version is in the environment

**Comment by bmuenzenmeyer** [comment]
eagle eyes! thanks for this. it snuck in. luckily, this will be resolved via https://github.com/nodejs/nodejs.org/pull/6907 after we internationalize the comments

**Comment by MikeMcC399** [comment]
@bmuenzenmeyer 

> eagle eyes! thanks for this. it snuck in. luckily, this will be resolved via #6907 after we internationalize the comments

That's great! Thanks for the confirmation that it will be fixed!
