### ISSUE TITLE
Improve fnm download instructions for Windows

### ISSUE THREAD

**Issue by CukitoYT** [nodejs/nodejs.org#6925]
### Enter your suggestions in details:

1. It shlould appear a command to config fnm when installing on windows.
2. ![image of where am I refering to](https://github.com/user-attachments/assets/78eec0ca-5f2e-456a-a59f-7492256bad2b)
3. I will only add 2 lines of code.

It should see like this...
![image](https://github.com/user-attachments/assets/96eda3ab-e14a-4155-9504-62b57db5b455)

**Comment by ovflowd** [comment]
Feel free to make a PR :)
