### ISSUE TITLE
Non-standard drag-to-select behavior

### ISSUE THREAD

**Issue by colinhacks** [nodejs/nodejs.org#6926]
### URL:

all pages

### Browser Name:

all browsers

### Browser Version:

n/a

### Operating System:

n/a

### How to reproduce the issue:

The current site hijacks default "drag to select" behavior in a way that is surprising. When dragging-to-select, once the cursor is above the halfway line of the page, the site starts scrolling upwards, assuming the user is trying to drag the selection north of the current viewport. Typically this would only start happening when the selection has been pulled near or beyond the top border of the page.

---

Dragging a word that's far above the halfway line results in very fast scrolling:

![Jul-15-2024 15-58-41](https://github.com/user-attachments/assets/fe3cf427-869b-4ace-90f1-5eb9d0a4c2b2)

Dragging from below the halfway line to above it shows the proportional upward scroll speed:

![Jul-15-2024 15-53-39](https://github.com/user-attachments/assets/d1476bdf-d926-4154-bb08-a9506c30787a)

**Comment by mikeesto** [comment]
Thanks, but the API documentation is not in this repo. It lives in [nodejs/node](https://github.com/nodejs/node). I believe there's been some recent attempts to fix this issue too.
