### ISSUE TITLE
Open docs link in same window

### ISSUE THREAD

**Issue by wesleytodd** [nodejs/nodejs.org#6927]
### Enter your suggestions in details:

I searched for related discussions but could not find them, is there a good reason I am not aware of to force a new window for that link? For me personally I find it unexpected even with the icon, and since it forces the behavior I as a user have no way to control it and open in the same tab. I didn't look, but I believe this was not the case with the old version, so just wanted to open an issue to discuss this new behavior and if folks are open to removing `target="_blank"`?

**Comment by AugustinMauroy** [comment]
I'm not sure when we did it.
But what I remember is that the design had a little arrow so we put the opening on another tab to respect the design rules.
My opinion is that we should remove the little arrow and leave it on the same tab. It often happens that I type nodejs.org and then go to doc and I always have to close the previous tab.

**Comment by wesleytodd** [comment]
Yep, that is exactly my most common action, open the homepage, click the docs link, close the extra tab. I would say that unless we can come up with a good reason to keep it we should make this change. I am happy to open the PR, but wanted to get some consensus first.

**Comment by Jay-Karia** [comment]
Removing `"target": "_blank"` would fix it (and the icon).

From this file:
apps/site/navigation.json

**Comment by wesleytodd** [comment]
Yep, just making sure folks agree this is a good change to make. Maybe I will just open the PR now that this has been here a few days and it seems like we agree it would be better to keep it in the same tab.

**Comment by ovflowd** [comment]
> Yep, that is exactly my most common action, open the homepage, click the docs link, close the extra tab. I would say that unless we can come up with a good reason to keep it we should make this change. I am happy to open the PR, but wanted to get some consensus first.

It's considered an external link, since it is a different web application. The Node.js docs aren't served by the Node.js Website app.

**Comment by wesleytodd** [comment]
That seems like a fine implementation detail, but I assume you agree the user behavior here would be improved by opening in the same tab?
