### ISSUE TITLE
icon: need update LinkedIn

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/nodejs.org#6928]
## Issue:

We are violating LinkedIn Trademark ! Here the LinkedIn [trademark policy](https://brand.linkedin.com/content/brand/global/en_us/index/visual-identity/logo)

## Solution:

Update the component [`components/Icons/Social/LinkedIn.tsx`](https://github.com/nodejs/nodejs.org/blob/main/apps/site/components/Icons/Social/LinkedIn.tsx)

Here svg extract from LinkedIn website:
_(yeah they didn't furnish svg)_

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="mercado-match" width="24" height="24" focusable="false">
      <path d="M20.5 2h-17A1.5 1.5 0 002 3.5v17A1.5 1.5 0 003.5 22h17a1.5 1.5 0 001.5-1.5v-17A1.5 1.5 0 0020.5 2zM8 19H5v-9h3zM6.5 8.25A1.75 1.75 0 118.3 6.5a1.78 1.78 0 01-1.8 1.75zM19 19h-3v-4.74c0-1.42-.6-1.93-1.38-1.93A1.74 1.74 0 0013 14.19a.66.66 0 000 .14V19h-3v-9h2.9v1.3a3.11 3.11 0 012.7-1.4c1.55 0 3.36.86 3.36 3.66z"></path>
</svg>
```

**Comment by sauhardh** [comment]
Hi, can you help me to understand this  attribute  class="mercado-match", should it be class or className? and does class="mercado-match" exists? because there were no class used in other svg like in Twitter.tsx.

**Comment by ovflowd** [comment]
> Hi, can you help me to understand this attribute class="mercado-match", should it be class or className? and does class="mercado-match" exists? because there were no class used in other svg like in Twitter.tsx.

`class` is a reserved word in React; The HTML counterpart for `class` in React is `className`
