### ISSUE TITLE
ui: layout shifts on dropdown

### ISSUE THREAD

**Issue by Jay-Karia** [nodejs/nodejs.org#6937]
### URL:

https://nodejs.org/en/download/package-manager

### Browser Name:

Chrome

### Browser Version:

103.0.5060

### Operating System:

Windows 10

### How to reproduce the issue:

1. Open downloads page (https://nodejs.org/en/download/package-manager)
2. Click on the dropdown menu followed by **"Install Node js"**
![node issue dropdown](https://github.com/user-attachments/assets/4f70c5ba-a9e6-4844-b815-bc882a237941)

By clicking any one of the dropdowns, the layout of the website shifts due to a vertical scroll bar disappearing.
However, this issue does not occur on other tabs such as **Prebuild Installer**, **Prebuilt Binaries**, and **Source Code** (because they don't have a scrollbar!).)

**Comment by ovflowd** [comment]
This isn't a bug; we've been back and forth non-stop. People open PRs to fix said layout shift, then someone opens another PR to revert that, and the cat-and-mouse game continues.

At this point, I honestly don't see any advantage in either.

**Comment by ovflowd** [comment]
https://github.com/nodejs/nodejs.org/pull/6865 fixes the issue, I assume. Closing the issue!
