### ISSUE TITLE
Incorrect order of events in the example

### ISSUE THREAD

**Issue by myheadisempty** [nodejs/nodejs.org#6950]
### URL:

https://nodejs.org/en/learn/asynchronous-work/understanding-processnexttick#an-example-of-the-order-of-events

### Browser Name:

Chrome

### Browser Version:

126.0.6478.183

### Operating System:

Windows 10, 22H2, 19045.4717

### How to reproduce the issue:

1. I executed a Node.js script.
2. What I expected to happen:
```
Hello => number 1
Running at next tick => number 2
Running before the timeout => number 3
The timeout running last => number 4
```
3. What I actually got:
```
Hello => number 1
Running at next tick => number 2
The timeout running last => number 4
Running before the timeout => number 3
```

**Comment by mikeesto** [comment]
Please see here https://github.com/nodejs/nodejs.org/issues/6920
