### ISSUE TITLE
Add alternate refs to sitemap

### ISSUE THREAD

**Issue by Baccega** [nodejs/nodejs.org#6956]
While looking at the sitemap code ([link](https://github.com/nodejs/nodejs.org/blob/7dabdc35b0ba69aaee729765b2d42e5cbcd5af8e/apps/site/app/sitemap.ts#L16C51-L16C52)), I noticed the comment explaining that the `alternate` refs are not yet supported by nextjs ([link to discussion on nextjs github](https://github.com/vercel/next.js/discussions/55646)), but while going through the nextjs docs I actually found that there is a way to add them ([link to nextjs docs](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap#generate-a-localized-sitemap)).

I wondered if the comment is outdated, or if I misunderstood the underlining problem, hence this issue.

**Comment by pr2897** [comment]
@AugustinMauroy  @Baccega can i pick up this issue.

**Comment by Baccega** [comment]
> @AugustinMauroy @Baccega can i pick up this issue.

Thank you for the offer @pr2897, but I'd like to fix it myself if possible 👍🏻

**Comment by pr2897** [comment]
sure, ✌️

**Comment by Baccega** [comment]
Fixed
