### ISSUE TITLE
Mobile view Style issue in page "http://events.linuxfoundation.org/events/node-interactive"

### ISSUE THREAD

**Issue by Navajyoth** [nodejs/nodejs.org#697]

**Comment by fhemberger** [comment]
Even if the Node Interactive website is not maintained by the Website WG, can you provide a bit more detail and/or a screenshot?

**Comment by fhemberger** [comment]
The only thing I noticed is a font loading issue on the page:

> Font from origin 'https://events.linuxfoundation.org' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://events.linuxfoundation.org' is therefore not allowed access.

Maybe @mikeal can reach out to the foundation to fix this.

**Comment by fhemberger** [comment]
Issue reported to the events team, closing.
