### ISSUE TITLE
blog.nodejs.org structure from joyent/node-website on nodejs/new.nodejs.org

### ISSUE THREAD

**Issue by bnb** [nodejs/nodejs.org#7]
The current nodejs.org at joyent/node-website uses complete, individual markdown files for metadata such as title, post date, etc. What needs to be done to model the old posts into the blog given a build process similar to the one iojs.org has? Just wanted to get this topic rolling so everyone's aware of it.

**Comment by mikeal** [comment]
It's relatively easy to adapt a tool to pull that metadata out of the markdown and parse it, if we need that.
