### ISSUE TITLE
nodejs.org/learn leads to 404

### ISSUE THREAD

**Issue by JakobJingleheimer** [nodejs/nodejs.org#7000]
### URL:

https://nodejs.org/learn

### Browser Name:

Brave

### Browser Version:

Version 1.68.141 (arm64)

### Operating System:

macOS 14.6

### How to reproduce the issue:

Go to https://nodejs.org/learn
Observe 404

In addition, clicking the "learn" TL nav link does nothing. One must manually update the address to escape.

https://nodejs.org/learn should redirect to the "root" of learn.

**Comment by AugustinMauroy** [comment]
This bug should from middleware or redirect

**Comment by Nirmalkumar6112** [comment]
Would like to work on this.

**Comment by velu-murugesan** [comment]
Could you please assign me this project or Is there any project not assign for someone please assign it to me. I think we should check it out middle ware and routing

**Comment by bmuenzenmeyer** [comment]
Thanks for your interest. We don't assign tickets if we can help it. Feel free to submit a pull request if you have time.
Reference 🍪 https://www.redhat.com/en/blog/dont-lick-cookie
