### ISSUE TITLE
Profiling summary output processed.txt differs from documentation

### ISSUE THREAD

**Issue by hidaviddong** [nodejs/nodejs.org#7007]
### URL:

https://nodejs.org/en/learn/getting-started/profiling

### Browser Name:

Chrome

### Browser Version:

127.0.6533.120

### Operating System:

macOS, 14.0, 23A344

### How to reproduce the issue:

# Issue Description
## What I did

I followed the instructions on the [Node.js profiling guide](https://nodejs.org/en/learn/getting-started/profiling)  to profile my Node.js application.

## What I expected to happen

According to the official documentation, the `processed.txt` file should contain a summary similar to this:

```
[Summary]:
   ticks  total  nonlib   name
     79    0.2%    0.2%  JavaScript
  36703   97.2%   99.2%  C++
      7    0.0%    0.0%  GC
    767    2.0%          Shared libraries
    215    0.6%          Unaccounted
```

## What i actually got

However, the `processed.txt` file I generated contains the following summary:
```
[Summary]:
   ticks  total  nonlib   name
    139    0.8%    0.8%  JavaScript
      0    0.0%    0.0%  C++
     50    0.3%    0.3%  GC
      0    0.0%          Shared libraries
  16309   99.2%          Unaccounted
```
the `ticks` for C++ is 0

## Environment

- Node.js Version: v20.17.0

## Additional Information
Here is the code I used for profiling:

```js
import express from 'express';
import crypto from 'node:crypto';

const app = express();
const users = {};
app.get('/auth', (req, res) => {
  let username = req.query.username || '';
  const password = req.query.password || '';
  
  username = username.replace(/[!@#$%^&*]/g, '');
  
  if (!username || !password || !users[username]) {
      return res.sendStatus(400);
  }
  
  const { salt, hash } = users[username];
  const encryptHash = crypto.pbkdf2Sync(password, salt, 10000, 512, 'sha512');
  
  if (crypto.timingSafeEqual(hash, encryptHash)) {
      res.sendStatus(200);
  } else {
      res.sendStatus(401);
  }
});

  
app.get('/newUser', (req, res) => {
  let username = req.query.username || '';
  const password = req.query.password || '';
  
  username = username.replace(/[!@#$%^&*]/g, '');
  
  if (!username || !password || users[username]) {
      return res.sendStatus(400);
  }
  
  const salt = crypto.randomBytes(128).toString('base64');
  const hash = crypto.pbkdf2Sync(password, salt, 10000, 512, 'sha512');
  
  users[username] = { salt, hash };
  res.sendStatus(200);
});
  

app.listen(8080, (req,res) => {
  console.log('Server running at http://localhost:8080/');   
});
```
And i ran the following commands:

- `NODE_ENV=production node --prof app.js`
- `curl -X GET "http://localhost:8080/newUser?username=matt&password=password"`
- `ab -k -c 20 -n 250 "http://localhost:8080/auth?username=matt&password=password"`
- `node --prof-process isolate-0x7fabc9600000-30933-v8.log > processed.txt`

![CleanShot 2024-08-27 at 17 13 06@2x](https://github.com/user-attachments/assets/3821c30d-3645-4e35-a2f3-3cea29610d6d)

Here are my log and txt files
- [isolate-0x7fabc9600000-30933-v8](https://drive.google.com/file/d/1WI2tFcB7qUjLEyj6vgPPWWIpNsNa1NVE/view?usp=sharing)
- [processed.txt](https://drive.google.com/file/d/1RJnYOc5RLSqhazyHACIsGApKjqlnSsHI/view?usp=drive_link)

**Comment by hidaviddong** [comment]
cc @anthonyshew 👋

**Comment by AugustinMauroy** [comment]
@hidaviddong why did you ping anthony ?

**Comment by hidaviddong** [comment]
> @hidaviddong why did you ping anthony ?

Sorry, I pinged the wrong person because I misread the commit author. :)

**Comment by hidaviddong** [comment]
It seems like the issue is specific to the macOS platform, when i tested the same code in my Ubuntu machine, i got this summary result :

```
Statistical profiling result from isolate-0x1acae0e0-655-v8.log, (49 ticks, 31 unaccounted, 0 excluded).

 [Shared libraries]:
   ticks  total  nonlib   name
      1    2.0%          /usr/lib/x86_64-linux-gnu/libc.so.6

 [JavaScript]:
   ticks  total  nonlib   name

 [C++]:
   ticks  total  nonlib   name
     11   22.4%   22.9%  __write@@GLIBC_2.2.5
      3    6.1%    6.3%  _IO_fwrite@@GLIBC_2.2.5
      2    4.1%    4.2%  _IO_file_xsputn@@GLIBC_2.2.5
      1    2.0%    2.1%  std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)@@GLIBCXX_3.4.9

 [Summary]:
   ticks  total  nonlib   name
      0    0.0%    0.0%  JavaScript
     17   34.7%   35.4%  C++
      0    0.0%    0.0%  GC
      1    2.0%          Shared libraries
     31   63.3%          Unaccounted
```

**Comment by mikeesto** [comment]
Hi @hidaviddong . Yes, it seems like on your MacOS run the profiler is unable to attribute a larger number of ticks. Improvements to the profiler would need to happen in [nodejs/node](https://github.com/nodejs/node). This repo is for the documentation, and I'm not sure if there are any changes to the documentation that are needed?

**Comment by hidaviddong** [comment]
> Hi @hidaviddong . Yes, it seems like on your MacOS run the profiler is unable to attribute a larger number of ticks. Improvements to the profiler would need to happen in [nodejs/node](https://github.com/nodejs/node). This repo is for the documentation, and I'm not sure if there are any changes to the documentation that are needed?

The documentation is fine, it's just that I'm not getting the correct results on my machine. There is a similar issue https://github.com/nodejs/node/issues/48263
