### ISSUE TITLE
Node 0.12 is hard to get to

### ISSUE THREAD

**Issue by papertigers** [nodejs/nodejs.org#702]
It would be nice to have a link to the node 0.12 docs on this page https://nodejs.org/en/docs/
rather than clicking a doc and guessing at the URL.

In addition to the docs issue finding node 0.12 releases is difficult.  When looking to update node on my laptop I have to hunt for the release in order to determine what the latest version is with security fixes.

**Comment by papertigers** [comment]
Well, never mind on the docs I did eventually spot the link on the docs page further down the page.

**Comment by fhemberger** [comment]
There is https://nodejs.org/en/download/releases/ and also https://nodejs.org/dist/latest-v0.12.x/
