### ISSUE TITLE
Downloads section is offline

### ISSUE THREAD

**Issue by mprobst** [nodejs/nodejs.org#703]
E.g. https://nodejs.org/dist/v6.0.0/node-v6.0.0.pkg times out between CloudFlare and the backend.

```
Error 522 Ray ID: 29b74d917e612228 • 2016-04-30 01:43:44 UTC
Connection timed out
```

**Comment by mprobst** [comment]
Appears to be back up.

**Comment by phillipj** [comment]
@mprobst thanks for reporting 👍
