### ISSUE TITLE
Is orama search on the main page broken?

### ISSUE THREAD

**Issue by sparecycles** [nodejs/nodejs.org#7042]
### URL:

https://nodejs.org/en

### Browser Name:

Firefox

### Browser Version:

130.0

### Operating System:

OSX 14.4.1 (23E224)

### How to reproduce the issue:

I searched for `reviver` (I know it's in the `JSON.parse` API), got the numbers of hits in various sections, but no results are displayed.

<img width="537" alt="image" src="https://github.com/user-attachments/assets/67646354-48d2-49f9-b609-2c7e348ee674">

I notice some words ("port") display results, some don't... it's all bit weird.

**Comment by bmuenzenmeyer** [comment]
Confirmed. Will try to look tonight

**Comment by bmuenzenmeyer** [comment]
search term `reviver`

response

```json
{
    "count": 0,
    "elapsed": {
        "raw": 0,
        "formatted": "0ms"
    },
    "hits": [],
    "facets": {
        "siteSection": {
            "count": 3,
            "values": {
                "docs": 25,
                "learn": 5,
                "about": 2
            }
        }
    }
}
```

I cannot find `reviver` within https://nodejs.org/docs/latest/api/all.html, or the website's source code, so to me it's returning the correct result but also reporting some hits, which is misleading.

Reviver is within https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#reviver - so why the hits here.

Also not sure yet why the OP thinks it _should_ be here, regardless, the search result is implying that it is.

**Comment by sparecycles** [comment]
I was checking up on NodeJS docs to confirm MDC's claim that the context parameter is passed in v21, and to see if there were any more notes.

<img width="755" alt="image" src="https://github.com/user-attachments/assets/7549801c-2cfb-4443-a3a1-11fc33413a5d">

So the built-in (ECMA standard-ish) Javascript globals in node have no notes in the Node docs? (JSON doesn't even appear in list of [globals](https://nodejs.org/docs/latest/api/globals.html)...)

**Comment by ovflowd** [comment]
cc @micheleriva

**Comment by micheleriva** [comment]
We're checking on this! Will update you all asap.

**Comment by micheleriva** [comment]
@ovflowd, @sparecycles, we have identified a possible issue and we're working to fix it asap. We'll keep you posted.

**Comment by matijagaspar** [comment]
Issue of wrongly reported hits is fixed and deployed, it was a server side issue, so no need to change anything on the website.

**Comment by bmuenzenmeyer** [comment]
Closing as complete.  Thanks Orama team!!!!!
