### ISSUE TITLE
Website is down for me

### ISSUE THREAD

**Issue by helciofranco** [nodejs/nodejs.org#7047]
### URL:

https://nodejs.org/en

### Browser Name:

Google Chrome

### Browser Version:

Version 128.0.6613.138 (Official Build) (arm64)

### Operating System:

Mac Sonoma 14.6.1 (23G93)

### How to reproduce the issue:

The website fails to load, resulting in an infinite loading screen. 
I am located in Brazil and have confirmed with friends that the website is down for everyone here.

- All requests to nodejs.org end with a timeout.
- Location: Brazil
- Confirmed by multiple users in the same region

**Comment by brismuth** [comment]
The status page says everything is operational, which is not correct:
https://status.nodejs.org/

<img width="1142" alt="image" src="https://github.com/user-attachments/assets/d90f786d-2b75-4e2b-ac19-ad3c8d51f534">

**Comment by helciofranco** [comment]
@brismuth is offline for you as well?

**Comment by felipecrs** [comment]
Accessing it from Canada also doesn't work. Times out.

```console
$ curl -fsSL https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.gz --output /dev/null
curl: (28) Failed to connect to nodejs.org port 443 after 214978 ms: Connection timed out
```

And also from Sweden, which is causing our CI/CD pipelines to break.

**Comment by ljharb** [comment]
It's not working for me right now either, from Boston.

**Comment by brismuth** [comment]
Down Detector is showing the outage:
https://downdetector.com/status/npm/

<img width="785" alt="image" src="https://github.com/user-attachments/assets/c957f185-06b4-4c9d-b74e-8d7b9c4b594f">

And uptime.com:
https://uptime.com/upstatus/nodejs.org

<img width="882" alt="image" src="https://github.com/user-attachments/assets/d9c21ff2-af65-4c2a-821d-0af72825391f">

It's down for me as well, and seems to be down globally. Breaking my CI/CD pipelines as well.

**Comment by mccolljr** [comment]
Confirming that I also see this problem in Ohio

**Comment by flakey5** [comment]
Ongoing incident we're looking into w/ Cloudflare

nodejs/release-cloudflare-worker#140

**Comment by ovflowd** [comment]
We are aware of the issue and are investigating. It seems like an issue on Cloudflare-level.

**Updates:** https://status.nodejs.org/incidents/42mqxc04ddmj

**Comment by flakey5** [comment]
https://status.nodejs.org/incidents/42mqxc04ddmj

**Comment by flakey5** [comment]
The website should be back up, we're continuing to monitor it

**Comment by anonrig** [comment]
Incident is now resolved. https://www.cloudflarestatus.com/incidents/jnj1y9f5c1r8
