### ISSUE TITLE
nodejs.org offline

### ISSUE THREAD

**Issue by felipecrs** [nodejs/nodejs.org#7048]
### URL:

https://nodejs.org

### Browser Name:

N/A

### Browser Version:

N/A

### Operating System:

N/A

### How to reproduce the issue:

Times out after 3m35s:

```console
$ curl -fsSL https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.gz --output /dev/null
curl: (28) Failed to connect to nodejs.org port 443 after 214978 ms: Connection timed out
```

This is completely breaking our CI/CD pipelines.

Issue observed when pulling from Brazil and Canada.

**Comment by ljharb** [comment]
Duplicate of #7047?

**Comment by felipecrs** [comment]
lol, by one minute.
