### ISSUE TITLE
`.browserslistrc` isn't understand by nexts

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/nodejs.org#7051]
The next.js docs mention that next only undersant browserslist form `package.json`. And found nothing about storybook and browslist.

https://nextjs.org/docs/architecture/supported-browsers#browserslist

**Comment by AugustinMauroy** [comment]
A simple action is to delete `.browserslistrc`. Because nobody noticed that their browser wasn't supported when we were using the next.js standard.

**Comment by bmuenzenmeyer** [comment]
actually from what I can tell, their default is ...poor

![image](https://github.com/user-attachments/assets/276d5fd0-dcdb-4606-ad2f-6c7b9106d4d8)

- https://nextjs.org/docs/architecture/supported-browsers
- [their default in browserslists REPL for 31% global coverage](https://browsersl.ist/#q=chrome%3E%3D64%0Aedge%3E%3D79%0Afirefox%3E%3D67%0Aopera%3E%3D51%0Asafari%3E%3D12)
- [our (inert) config, for 94% global coverage](https://browsersl.ist/#q=defaults+and+supports+es6-module%0Amaintained+node+versions%0Acover+95%25%0Anot+dead)

**Comment by ovflowd** [comment]
> The next.js docs mention that next only undersant browserslist form `package.json`. And found nothing about storybook and browslist.
> 
> [nextjs.org/docs/architecture/supported-browsers#browserslist](https://nextjs.org/docs/architecture/supported-browsers#browserslist)

Where do you see it mentioned it does not support `.browserlistsrc`?

Next.js supports Browser lists, which means they have the Browser lists package, which automatically searches for the numerous variations of Browser list configuration files, including within the package.json

This is a standard for many libraries, such as Jest, for example.

**Comment by ovflowd** [comment]
I'm pretty sure they support this file format :) cc @styfle

**Comment by bmuenzenmeyer** [comment]
Yes i was reading the source code earlier today. The user config is read before the defaults are applied.

**Comment by ovflowd** [comment]
Ill close this issue. I understand Augustin has good intentions, but please assume (this is for Augustin) first that we did our homework when implementing things, or come from a path of curiosity, not already off the bat assuming things :)

**Comment by AugustinMauroy** [comment]
> Where do you see it mentioned it does not support .browserlistsrc?

in nextjs docs:

"If you would like to target specific browsers or features, Next.js supports [Browserslist](https://browsersl.ist/) configuration in your package.json file. Next.js uses the following Browserslist configuration by default:"

**Comment by ovflowd** [comment]
You are misunderstanding their docs. It never states that it does not support the other approaches.

**Comment by styfle** [comment]
Next.js uses swc, which does support `.browserslistrc` as seen here:

https://swc.rs/docs/configuration/supported-browsers#path
