### ISSUE TITLE
Question about promises

### ISSUE THREAD

**Issue by bluejellybean** [nodejs/nodejs.org#706]
Is there a way to not have to type 'return new Promise(( resolve, reject ) => {' every single function?

I almost want to get rid of all callbacks from javascript hah!

**Comment by ghost** [comment]
hi @bluejellybean! you may have stumbled upon the wrong repository here. you may be looking for https://github.com/nodejs/help! please [open your issue](https://github.com/nodejs/help/issues/new) there, thanks ❤️
