### ISSUE TITLE
Tabs off of https://nodejs.org/en/download/package-manager/all all 404

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#7062]
### URL:

https://nodejs.org/en/download/package-manager/all

### Browser Name:

Chrome

### Browser Version:

128.0.6613.138

### Operating System:

Windows

### How to reproduce the issue:

1. Go to https://nodejs.org/en/download/package-manager
2. Click on `package managers` on the bottom of the page
3. Land on https://nodejs.org/en/download/package-manager/all
4. Click on `Prebuilt Installer`, `Prebuilt binaries`, or `Source Code`

All tabs except the default 404

**Comment by mikeesto** [comment]
I'm wondering whether we even need the tabs on https://nodejs.org/en/download/package-manager/all

**Comment by Nyx1on** [comment]
I think it's better to hide all the tabs from https://nodejs.org/en/download/package-manager/all

**Comment by ovflowd** [comment]
Why are the tabs even there? This was not the case in the past? Did someone change the layouts recently?

**Comment by canerakdas** [comment]
IMHO this page should not be in the downloads directory, it looks more like a content page that should be under the learn.

If we want to use a different layout in the download directory, this PR actually solves this issue; https://github.com/nodejs/nodejs.org/pull/6929

**Comment by ovflowd** [comment]
> IMHO this page should not be in the downloads directory, it looks more like a content page that should be under the learn.
> 
> 
> 
> If we want to use a different layout in the download directory, this PR actually solves this issue; https://github.com/nodejs/nodejs.org/pull/6929

I assume this page eventually will go away with the redesign of the downloads page; I don't think it should reside under learn... It is not a learn page, but a download page.

**Comment by canerakdas** [comment]
> > IMHO this page should not be in the downloads directory, it looks more like a content page that should be under the learn.
> > If we want to use a different layout in the download directory, this PR actually solves this issue; #6929
> 
> I assume this page eventually will go away with the redesign of the downloads page; I don't think it should reside under learn... It is not a learn page, but a download page.

I think it's a nice feature to be able to see other download options while on a download page, but I can't defend it since this page will be completely changed soon 😄  I think we can move on with this PR; https://github.com/nodejs/nodejs.org/pull/6929

Here is the preview; https://nodejs-1gq1n4ies-openjs.vercel.app/en/download/package-manager/all

**Comment by bmuenzenmeyer** [comment]
closed via https://github.com/nodejs/nodejs.org/pull/6929
