### ISSUE TITLE
The package manager page is outdated in translated versions of the website

### ISSUE THREAD

**Issue by stof** [nodejs/nodejs.org#7117]
### URL:

https://nodejs.org/fr/download/package-manager/all

### Browser Name:

Firefox

### Browser Version:

131

### Operating System:

Ubuntu 22.04

### How to reproduce the issue:

French page:
![image](https://github.com/user-attachments/assets/78424ff8-cdf9-49f6-b372-06a5199a125a)

English page:
![image](https://github.com/user-attachments/assets/160d3a3b-6788-4f7b-bbd3-79439656258d)

As the French page has not been updated in #6929, it also means that https://github.com/nodejs/nodejs.org/issues/6922 is not actually fixed yet.

**Comment by AugustinMauroy** [comment]
We're aware of the problem, there's nothing to do but wait for the next crowdin sync.

**Comment by bmuenzenmeyer** [comment]
https://github.com/nodejs/nodejs.org/pull/7089 should resolve this

**Comment by bmuenzenmeyer** [comment]
![image](https://github.com/user-attachments/assets/b6853a35-9c4c-4c51-a873-5a20a57088d8)
