### ISSUE TITLE
`Copy to clipboard` button does not work

### ISSUE THREAD

**Issue by geeksilva97** [nodejs/nodejs.org#7118]
### URL:

https://nodejs.org/en/learn/diagnostics/memory/using-heap-snapshot/

### Browser Name:

Chrome

### Browser Version:

129.0.6668.90 (Official Build) (arm64) 

### Operating System:

Darwin LM-JNVH7RPW6J 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14: 30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030 arm64

### How to reproduce the issue:

1. Go to https://nodejs.org/en/learn/diagnostics/memory/using-heap-snapshot/
2. Find a code snippet
3. Click on `Copy to clipboard`

<img width="801" alt="image" src="https://github.com/user-attachments/assets/1891bf00-8f82-465e-b4ec-125b2c480a2e">

**Comment by ovflowd** [comment]
Seems to be working fine here.

**Comment by AugustinMauroy** [comment]
Work on large screen. But not on mobile

**Comment by ovflowd** [comment]
> Work on large screen. But not on mobile

Wdym? Doesn't work on touch devices? The author described it is not working on macOS, and their screenshot is of a desktop device.

**Comment by AugustinMauroy** [comment]
Look at this. I can't really explain 

https://github.com/user-attachments/assets/8c359a6e-bd2f-4a3f-a4bc-8ca0988e3811

And on landning page

https://github.com/user-attachments/assets/d0d1c751-102c-41ff-aa99-0fa585f4c208

**Comment by AugustinMauroy** [comment]
Maybe this page is broken 'cause of to code snippet without name or lang
REF: https://github.com/nodejs/nodejs.org/blob/f116efe39e942f67b302b3e9853c823a9beff92d/apps/site/pages/en/learn/diagnostics/memory/using-heap-snapshot.md?plain=1#L53-L63

**Comment by Hamza1610** [comment]
> Work on large screen. But not on mobile

Tested on mobile it's working.
![node  issue](https://github.com/user-attachments/assets/c6cb0a99-1a6c-41fb-9dca-e13bd34add84)

**Comment by AugustinMauroy** [comment]
now I can't reproduce. IDK what is going on here.

**Comment by geeksilva97** [comment]
Hey guys. I just tested it. Now it works.

**Comment by Hamza1610** [comment]
> Hey guys. I just tested it. Now it works.

That's great
