### ISSUE TITLE
Store gzip representations of common files on deploy

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/nodejs.org#712]
Since we're using `gzip_static on` in the server we could shave off an considerable amount of cpu power by storing a gzip representation of each file we deploy (for instance `index.html` would be accompanied by `index.html.gz`). Additionally, since we default to `-6` in nginx, we'd likely make each file a bit smaller by using `-9` on deploy.

**Comment by fhemberger** [comment]
We could add a npm task, which is only run on the build machine:
`find -E build -type f -regex ".*(html|css|js|xml|json)$" -exec gzip -9 -k {} \;`

Takes 0.75s on my MacBook Pro for the current website.
