### ISSUE TITLE
Can't add any changes locally

### ISSUE THREAD

**Issue by Serpentarius13** [nodejs/nodejs.org#7136]
### URL:

.

### Browser Name:

Chrome

### Browser Version:

Latest

### Operating System:

Arch Linux latest

### How to reproduce the issue:

1. Cloned the repo
2. Changed node version to .nvmrc => 20
3. `npm ci`
4. Added a change and reloaded the page
5. Have received this error and idk what it even means xD 
![image](https://github.com/user-attachments/assets/c950173b-ff11-4d35-9562-6bb93ad1544f)

**Comment by AugustinMauroy** [comment]
> Have received this error and idk what it even means xD

I think it's mean you import a nodejs api on client context. Or import a full esm package 

> Added a change and reloaded the page

what did you change ?

**Comment by AugustinMauroy** [comment]
remove `bug` label because on lasted commit on main branch everything is fine

**Comment by ovflowd** [comment]
Have you restarted after reinstalling packages?

**Comment by Serpentarius13** [comment]
> > Have received this error and idk what it even means xD
> 
> I think it's mean you import a nodejs api on client context. Or import a full esm package
> 
> > Added a change and reloaded the page
> 
> what did you change ?

Just one style in tailwind, but any change just breaks it. It doesnt break immediately, only after few saves to the file and then maybe reload the page, quite random

**Comment by Serpentarius13** [comment]
> Have you restarted after reinstalling packages?

Yes, I have removed and reinstalled them few times, still getting this. Idk what's wrong

**Comment by AugustinMauroy** [comment]
can you push your change on your fork and give it to us?

**Comment by Serpentarius13** [comment]
> can you push your change on your fork and give it to us?

This happens on *any* change. For example, I just added a simple console log:

```tsx
const shortAvatarList = useMediaQuery(
    '(min-width: 670px) and (max-width: 1280px)'
  );

  console.log('hello');

  return (
    <MetaBar
      items={{
```

And reloaded the page with receiving the same error. I will try to reclone the repo

EDIT: It did not help. My exact path:
`git clone https://github.com/nodejs/nodejs.org nodejs`
`cd nodejs`
`nvm use`
`npm ci`
`npm run dev`
`Add a change, save`
`Error happens in console`
`Reload, error happens in the browser`

**Comment by AugustinMauroy** [comment]
honestly I have any clue

**Comment by bmuenzenmeyer** [comment]
this happened to me locally today. a restart of the dev server fixed it. I have auto-save turned on, i wonder if it can spam the HMR on bad syntax

**Comment by canerakdas** [comment]
This problem happening to me too, when removing the `--turbo` flag in the `/nodejs.org/apps/site/package.json` file fixes for me

**Comment by AugustinMauroy** [comment]
We can try to manually bump next to 14.2.15 but on release note there are nothing about turbopack. I didn't had time to search if there are already issue to track this problem.

**Comment by avivkeller** [comment]
Sometimes this happens to me, and as @bmuenzenmeyer siad, restarting the dev server fixes it. Did that solve your query?

Additionally, it hasn't happened to me since the upgrade to Next.js 15 (so maybe that fixed it?)

**Comment by canerakdas** [comment]
The issue I was experiencing was completely resolved with the Next.js 15 update 🙌

**Comment by avivkeller** [comment]
I think I'll close this, and if something changes, we can reopen.
