### ISSUE TITLE
learn: make the links to the author profile clickable

### ISSUE THREAD

**Issue by mcollina** [nodejs/nodejs.org#7141]
<img width="1107" alt="Screenshot 2024-10-25 at 18 02 12" src="https://github.com/user-attachments/assets/94af6adb-e375-4e63-994a-69f0af2f914a">

Each learn page as an author frontmatter. I think it would be really nice to add a backlink to the author github profile.

**Comment by mikeesto** [comment]
+1. Many of our authors are also missing from https://github.com/nodejs/nodejs.org/blob/main/apps/site/authors.json (for example, you are Matteo)

**Comment by AugustinMauroy** [comment]
Also mention issue #7093

**Comment by ovflowd** [comment]
> +1. Many of our authors are also missing from [`main`/apps/site/authors.json](https://github.com/nodejs/nodejs.org/blob/main/apps/site/authors.json?rgh-link-date=2024-10-26T01%3A06%3A00Z) (for example, you are Matteo)

Feel free to complete that list ;D

**Comment by AugustinMauroy** [comment]
> [!CAUTION]
> The `authors.json` file is only valid for the blog section, because the learn section has a valid GitHub username. So don't include the authors of the learn section in `authors.json`.
