### ISSUE TITLE
The code example does not work as described

### ISSUE THREAD

**Issue by slavamuravey** [nodejs/nodejs.org#7151]
### URL:

https://nodejs.org/docs/latest/api/process.html#when-to-use-queuemicrotask-vs-processnexttick

### Browser Name:

Chrome

### Browser Version:

latest

### Operating System:

Linux Ubuntu 22.04

### How to reproduce the issue:

1. Open [when-to-use-queuemicrotask-vs-processnexttick](https://nodejs.org/docs/latest/api/process.html#when-to-use-queuemicrotask-vs-processnexttick) link.
2. Look at the code example:

**CJS**
```
const { nextTick } = require('node:process');

Promise.resolve().then(() => console.log(2));
queueMicrotask(() => console.log(3));
nextTick(() => console.log(1));
// Output:
// 1
// 2
// 3
```

**ESM**
```
const { nextTick } = require('node:process');

Promise.resolve().then(() => console.log(2));
queueMicrotask(() => console.log(3));
nextTick(() => console.log(1));
// Output:
// 1
// 2
// 3
```
**Expected:**
For **ESM** the output should be:
```
// 2
// 3
// 1
```
Because **ESM** module is already a microtask.

**Actual:**
The output is identical for **CJS** and **ESM**.

**Comment by mikeesto** [comment]
Hi. Thanks for the issue but this documentation doesn't actually live in this repository - it's in `/nodejs/node`: https://github.com/nodejs/node/blob/main/doc/api/process.md .

**Comment by slavamuravey** [comment]
Ok, thanks!
