### ISSUE TITLE
learn: is "how-to-install-nodejs" still need

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/nodejs.org#7184]
It's was originally written in `nodejs.dev`, and it's redirect to `nodejs.org` maybe because at the time of writing the download page wasn't near `nodejs.dev` (but I'm not sure).
I don't think there's any point in having this document anymore. Maybe we should just add a link to download at the bottom of the ‘introduction-to-nodejs’ page.

REF:
- https://github.com/nodejs/nodejs.org/blob/main/apps/site/pages/en/learn/getting-started/how-to-install-nodejs.md
- https://github.com/nodejs/nodejs.org/blob/main/apps/site/pages/en/learn/getting-started/introduction-to-nodejs.md

**Comment by AugustinMauroy** [comment]
@ovflowd if you put "good first issue" I think it's because it's okay to remove it ?

**Comment by ovflowd** [comment]
> @ovflowd if you put "good first issue" I think it's because it's okay to remove it ?

What?

**Comment by AugustinMauroy** [comment]
my proposition is to remove `how-to-install-nodejs` and redirect to download page. So I suppose you allow with me if you put good first issue
