### ISSUE TITLE
UI improvement for docs in dark mode.

### ISSUE THREAD

**Issue by replyre** [nodejs/nodejs.org#7206]
### Enter your suggestions in details:

The colors used in dark mode are very bright warm colors, which are not recommended.

#### Reference Image:

![image](https://github.com/user-attachments/assets/a7d95189-ea0f-467c-ac2a-7a3828dcc022)

I suggest to go with more eye-friendly dark mode colors for the dark theme.

#### Reference article:
https://m2.material.io/design/color/dark-theme.html#ui-application

**Comment by AugustinMauroy** [comment]
This repo deosn't contain source code of docs.
We are planing to redesign the docs [fima link ](https://www.figma.com/design/pu1vZPqNIM7BePd6W8APA5/Node.js?node-id=695-14399&t=FgXPHDy6nHeuqXzp-1) for the stability index

**Comment by replyre** [comment]
hey @AugustinMauroy, I would like to be a part of that.

**Comment by avivkeller** [comment]
If you have any concerns or comments, feel free to add a comment on the Figma. Any/all suggestions are appreciated!!

(for record keeping, part of this convo was on X @ https://twitter.com/redyetidev/status/1855756770192347158?s=46)
