### ISSUE TITLE
Add blue sky in footer link

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/nodejs.org#7207]
(very) recently we joined blue sky. We'll have to put the link somewhere to let people know it exists. For example in the footer and why not a badge on the home page.

REF: https://github.com/nodejs/admin/issues/932

TODO:

- Add icon component 
- Add link to `navigation.json`

**Comment by TenzDelek** [comment]
is this issue open to take or are you implementing it (cc @AugustinMauroy )

**Comment by AugustinMauroy** [comment]
You can go ahead 👍
