### ISSUE TITLE
Nominate @RedYetiDev to the `web-infra` Team

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#7208]
Aviv has shown a strong interest in the Node project, has engaged in several web and web-infra-related works, and has been on the website repository for a while. Whilst primarily acting as a triager and providing support on the Website repository, they've shown solid technical skills on the Node.js core repository and activity and engagement on repositories owned by the Web Infra team.

Knowing their engagement, they would be a great addition to helping develop the new Cloudflare Worker and API docs tooling.

Note that since being on this team gives specific access to internal tooling, we opt-in for a trial period without access to Sentry/Vercel/etc.

[Pull requests opened throughout the Node.js organization](https://github.com/search?q=author%3ARedYetiDev+org%3Anodejs&type=pullrequests)
[Comments on pull requests throughout the Node.js organization](https://github.com/search?q=commenter%3ARedYetiDev+org%3Anodejs&type=pullrequests)
[Comments on issues throughout the Node.js organization](https://github.com/search?q=commenter%3ARedYetiDev+org%3Anodejs&type=issues)
Comments on pull requests and issues in the [nodejs/nodejs.org](https://github.com/nodejs/nodejs.org/issues?q=commenter%3ARedYetiDev+sort%3Aupdated-desc+) repository

cc @RedYetiDev
cc @nodejs/web
cc @nodejs/web-infra

**Comment by ovflowd** [comment]
Unfortunately, I got an objection to this nomination in private, which means we cannot proceed. Sorry, Aviv 😞

**Comment by ovflowd** [comment]
Incidentally, we could make another nomination just for the Website team :) -- which I believe has less privileges by nature. How would you feel about this, @RedYetiDev?

**Comment by avivkeller** [comment]
Sure!
