### ISSUE TITLE
Nominate @RedYetiDev to the `nodejs-website` Team

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#7210]
Aviv has shown a strong interest in the Node project, has engaged in several web and web-infra-related works, and has been on the website repository for a while. Whilst primarily acting as a triager and providing support on the Website repository, they've shown solid technical skills on the Node.js core repository and activity and engagement on repositories related to the Website team. Although they are more active on the repositories owned by the Web Infra team, membership here at least showcases good faith towards their contributions.

Knowing their engagement, they would be a great addition to helping develop the new Cloudflare Worker and API docs tooling.

[Pull requests opened throughout the Node.js organization](https://github.com/search?q=author%3ARedYetiDev+org%3Anodejs&type=pullrequests)
[Comments on pull requests throughout the Node.js organization](https://github.com/search?q=commenter%3ARedYetiDev+org%3Anodejs&type=pullrequests)
[Comments on issues throughout the Node.js organization](https://github.com/search?q=commenter%3ARedYetiDev+org%3Anodejs&type=issues)
Comments on pull requests and issues in the [nodejs/nodejs.org](https://github.com/nodejs/nodejs.org/issues?q=commenter%3ARedYetiDev+sort%3Aupdated-desc+) repository

cc @RedYetiDev
cc @nodejs/web
cc @nodejs/nodejs-website

**Comment by avivkeller** [comment]
I'm so happy to have the privilege to be able to contribute to such an amazing project!!

**Comment by AugustinMauroy** [comment]
+1 for that.
Welcome @RedYetiDev !

**Comment by bmuenzenmeyer** [comment]
big +1 - too bad you couldn't have hung out with us at NodeConfEU/CollabSummit

**Comment by flakey5** [comment]
+1

**Comment by ovflowd** [comment]
> big +1 - too bad you couldn't have hung out with us at NodeConfEU/CollabSummit

True! @RedYetiDev I see you are based in the US; Would love having tou joining us next collab summit either in-person or virtually. We will also have a JSConf happening later next year :)

**Comment by avivkeller** [comment]
Hopefully I'll pop in! If I can't be there in person, I'll surely hop on  virtually!!

**Comment by avivkeller** [comment]
I'm so honored to be nominated. If/when (fingers crossed) the nomination passes, is there any onboarding that needs to be scheduled?

**Comment by AugustinMauroy** [comment]
> I'm so honored to be nominated. If/when (fingers crossed) the nomination passes, is there any onboarding that needs to be scheduled?

there are no onboarding. Just need to add you in the team when all active website membres approve the nominations

**Comment by canerakdas** [comment]
> I'm so honored to be nominated. If/when (fingers crossed) the nomination passes, is there any onboarding that needs to be scheduled?

If you haven't looked yet, you can find information on many subjects in the links below; https://github.com/nodejs/nodejs.org?tab=readme-ov-file#relevant-links

If you find anything missing or incorrect in these documents, you can ask the team 🙇

**Comment by ovflowd** [comment]
Nomination passed! Welcome, @RedYetiDev!

**Comment by AugustinMauroy** [comment]
Woooowww welcome  🫶

**Comment by avivkeller** [comment]
![image](https://github.com/user-attachments/assets/ee8c697b-f74b-4fe0-9bcd-928014a2ad06)
