### ISSUE TITLE
[Docs]: Inconsistency in development start command between Contributing Guide and README

### ISSUE THREAD

**Issue by TenzDelek** [nodejs/nodejs.org#7219]
I noticed a discrepancy in the commands provided to start the development environment:

1. In CONTRIBUTING.md, it states: 
 https://github.com/nodejs/nodejs.org/blob/main/README.md
```js
npm ci
npm run dev
```

3. In the main README.md, it states:
https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md
```js 
npm ci
npx turbo dev
```
The inconsistency between the Contributing Guide and the README regarding the development start command appears to be a result of the project's migration to Turborepo. To ensure clarity and consistency for contributors, it would be beneficial to align the documentation across all project files.

**Comment by AugustinMauroy** [comment]
readme need to be updated

**Comment by TenzDelek** [comment]
Are we not going to use the turbo command🤔

**Comment by AugustinMauroy** [comment]
npm run => turbo dev 
So it's mean npm run dev call turbo dev. And turbo dev will go on all packages to run dev task
