### ISSUE TITLE
Ang_ngl is no longer on Twitter.

### ISSUE THREAD

**Issue by avivkeller** [nodejs/nodejs.org#7231]
Currently, according to the website, credit for our lovely mascot goes to Angela Angelini, however the Twitter account linked no longer exists.

Ref: https://twitter.com/nodejs/status/1760358555180220811?lang=en
Ref: https://nodejs.org/en/about/branding

**Comment by avivkeller** [comment]
Maybe we can instead link to https://www.linkedin.com/in/angeliningl?

**Comment by ovflowd** [comment]
Feel free to open a PR

**Comment by TenzDelek** [comment]
should i raise the pr ? @RedYetiDev

**Comment by TenzDelek** [comment]
also i notice that the credit are missing in these localization: 
1. Indonesian
2. Ukrainian
3. Simplified and Traditional Chinese
ref:  indo:
<img width="548" alt="image" src="https://github.com/user-attachments/assets/813b9aa4-36c2-4d0f-b466-0d11922fd485">
cc @ovflowd  @RedYetiDev

**Comment by AugustinMauroy** [comment]
> also i notice that the credit are missing in these localization:

DO no touch it, it's handle with crowdin and an automatization. If you want more info read `TRANSALTION.md`

**Comment by TenzDelek** [comment]
> > also i notice that the credit are missing in these localization:
> 
> DO no touch it, it's handle with crowdin and an automatization. If you want more info read `TRANSALTION.md`

ah thanks for the heads up, I believe we can change the en/ one or is it also through crowdin 🤔  ? @AugustinMauroy

**Comment by AugustinMauroy** [comment]
Nop en one need to be updated with git

**Comment by marco-ippolito** [comment]
cc @micheleriva

**Comment by avivkeller** [comment]
> should i raise the pr ? @RedYetiDev 

Be my guest! But as @AugustinMauroy said, leave the translations alone.
