### ISSUE TITLE
Add "Contributing" to the navigation bar?

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/nodejs.org#7237]
### Enter your suggestions in details:

This came from a Bluesky thread and somehow we went a bit off-topic to discuss about how to find the useful information about contributing to the project https://bsky.app/profile/patak.dev/post/3lbash7plsk2q

Currently, there is a page on the website about contributing but it's a bit hidden: in About -> Contribute to Node.js: https://nodejs.org/en/about/get-involved/contribute

Considering the project has always been very understaffed, I think it would be overall better for the project if we can have a more prominent place for the information about contribution on the website, say putting it in the navigation bar.

**Comment by AugustinMauroy** [comment]
@RedYetiDev we put the good first issue to issue with consensus. Also when labeling that please add a "tuto" to how to fix the issue. So that allow the new comer to know what they can do

**Comment by AugustinMauroy** [comment]
I'm -1 for that
If we do what Joyee is proposing, we'll find ourselves in the same ‘support version’ situation. Basically, the problem is that ‘support version’ and ‘contribute’ are sub-sections and so if you put them in the navbar there will be two entries that could be active, which is strange for a user. And in the other case, if we take the general section, there will be one entry that will never be active, which means that the user won't get any feedback on his action.

**Comment by joyeecheung** [comment]
The idea is more about promoting a page with information about how to contribute. If being in a subsection gets in the way, maybe we could just move it out to be its own page?

**Comment by joyeecheung** [comment]
Or, it does not need to be a page on the website, since the website page is mostly copying from other documents and could get out of sync over time. We can link the nav bar item to https://github.com/nodejs/node/blob/main/CONTRIBUTING.md directly as well. If that document is missing information, we can easily add more information there, and benefit those who look at that document too.

**Comment by AugustinMauroy** [comment]
> The idea is more about promoting a page with information about how to contribute. If being in a subsection gets in the way, maybe we could just move it out to be its own page?

I'm in favour of having more documents to contribute to the project. Just putting it in the navBar is -1

**Comment by AugustinMauroy** [comment]
> https://github.com/nodejs/node/blob/main/CONTRIBUTING.md directly as well. If that document is missing information, we can easily add more information there, and benefit those who look at that document too.

We could see a sub-section called ‘Contribute to the project’, which would be a collection of links (to GH) that would allow each team/working group to highlight their own contributions. So each WG/team needs to have a document that does a proper onboarding.

**Comment by joyeecheung** [comment]
I think the subsection idea doesn't address the issue about information about contribution being hidden. For example, the nav bar currently links to https://training.linuxfoundation.org/openjs/ too - is that information more important to the project than recruiting more contributors, though?

**Comment by ovflowd** [comment]
Many prominent open source projects have Contributed or Donated on their main navigation bars.

Strong +1; I'm usually against adding extra links up there, but this one makes sense, and it could still go to our page which is an abridged version of the CONTRIBUTING.md

**Comment by AugustinMauroy** [comment]
I was wondering if the contributing page (the one on the site) shouldn't just be a series of ordered links to understand how node-core works.

_"though they are usually not properly linked or listed, which was why I opened"_ Joyee

**Comment by joyeecheung** [comment]
I think it would be better for the contribution info on the website to redirect to links in the core repo (at least, when we are talking about contributing to core), otherwise it risks getting out of date again - even in the core repo, documentation gets out of date all the time, but on the website it would be even worse, for example when someone update a file name, at least find-and-replace in the repository helps you update the document as well. But if it's in a separate repository, it will probably only get noticed after years. I think every time I check out the website about this kind of information, it's never *not* outdated. e.g. https://github.com/nodejs/nodejs.org/pull/7238 and https://github.com/nodejs/nodejs.org/pull/6604

**Comment by bmuenzenmeyer** [comment]
👍 for adding a more prominent link to https://github.com/nodejs/node/blob/main/CONTRIBUTING.md 

I've created https://github.com/nodejs/nodejs.org/pull/7274 to show what that would look like.
