### ISSUE TITLE
It's impossible to navigate to "Copy to clipboard" button using keyboard

### ISSUE THREAD

**Issue by wojtekmaj** [nodejs/nodejs.org#7247]
### URL:

https://nodejs.org/en/download/package-manager

### Browser Name:

Edge

### Browser Version:

131.0.2903.51

### Operating System:

Windows 11, 24H2, 26100.2314

### How to reproduce the issue:

1. Go to https://nodejs.org/en/download/package-manager
2. Tab tab tab tab tab
3. Focus never lands on "Copy to clipboard" button, making it impossible to easily copy the code snippet above using keyboard only.

Oddly enough, you can focus _the code itself_ using keyboard, but that seems to do nothing at all.

**Comment by ovflowd** [comment]
Thanks for opening this issue :) -- striving for better accessibility is important <3

**Comment by bjohansebas** [comment]
Hi, i can help with this

**Comment by avivkeller** [comment]
PRs are always welcome, no need to ask

**Comment by canerakdas** [comment]
Fixed with #7287
