### ISSUE TITLE
Incorrect Highlighting on Main Codebox

### ISSUE THREAD

**Issue by avivkeller** [nodejs/nodejs.org#7249]
### URL:

https://nodejs.org/en

### Browser Name:

Chrome

### Browser Version:

131

### Operating System:

Linux

### How to reproduce the issue:

When visiting the site, the second line of the main codebox has incorrect highlighting. The text is all grey.

This only applies to this tab, not the others.

![image](https://github.com/user-attachments/assets/f38af445-71dc-481a-94eb-a210d2a3bef0)

For comparison, on GFM:
```mjs
import { createServer } from 'node:http'
```

**Comment by avivkeller** [comment]
Looks like it was caused by https://github.com/nodejs/nodejs.org/commit/c5345f551ea545cf9d04017204b17f3099940ada.

I can spend some time tomorrow looking into this, but if someone wants to go ahead, please be my guest

**Comment by TenzDelek** [comment]
in local server , It is rendering correctly 🤔 
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/c6c0a84a-02cb-4c72-909f-1425863209fb">

**Comment by bmuenzenmeyer** [comment]
could it be browser specific? 
it is rendering for me correctly

<img width="812" alt="image" src="https://github.com/user-attachments/assets/c316ca04-0571-4cef-a65b-be42d5da533c">

Vivaldi 7.0.3495.10 (Stable channel) (arm64) 
macOS Version 14.7 (Build 23H124)

**Comment by avivkeller** [comment]
It's rendering correctly for me now too. I'm gonna check the deployments to see when it fixed itself?

**Comment by avivkeller** [comment]
Looks like it started in https://nodejs-abfhxokt0-openjs.vercel.app/en (c5345f551ea545cf9d04017204b17f3099940ada) and fixed itself in https://nodejs-nei5kgypu-openjs.vercel.app/en (52e04b06a93c961084e97d5f33b8f02888c87be4)

**Comment by RedYetiDev** [comment]
This does seem to be fixed

**Comment by avivkeller** [comment]
It seems intermittent. Right now, In Chrome 131, I am experiencing it on https://nodejs.org/en. (Edit 2min later: Not anymore :thinking:)

It seems like a client-side issue, not server-side tho.

**Comment by avivkeller** [comment]
> could it be browser specific?

I don't think so. Look ing at the HTML code, the browser render is matching the HTML shown, probably a Shiki client side issue?

**Comment by ovflowd** [comment]
Could this be caused by Shiki's JavaScript-based parser versus their WebAssembly one? Or could this even be a Shiki-specific bug?

FYI that Im making local changes to the index page to re-indent things and keep them tight and nice.

**Comment by AugustinMauroy** [comment]
if someone still have this issue ?

**Comment by ovflowd** [comment]
Apparently with the latest chances on our CodeBoxes rendering (Shiki) this issue doesn't seem to be present anymore ✨
