### ISSUE TITLE
Fix : whitespaces between the main content and progressive sidebar (scroll issue)

### ISSUE THREAD

**Issue by TenzDelek** [nodejs/nodejs.org#7251]
### URL:

https://nodejs.org/en/learn/getting-started/how-to-install-nodejs

### Browser Name:

brave

### Browser Version:

1.65.123

### Operating System:

Windows 11

### How to reproduce the issue:

<img width="1255" alt="image" src="https://github.com/user-attachments/assets/a3f3884b-41d5-4685-be8f-62add60a372c">

current behavior of the website scroll is base on such that the sidebar and the main content are being dependent on each other when scrolling , leaving a huge whitespace for some long main content. this issue was raised in the following pr [Issue Link](https://github.com/nodejs/nodejs.org/pull/6949#issuecomment-2304970795) by @AugustinMauroy . 

i believe the scroll behavior of both should be independent like our previous version before that pr was merge.

**Comment by amyy2** [comment]
Hello, can I take on this issue?

**Comment by avivkeller** [comment]
PRs are always welcome

**Comment by Bgregg93** [comment]
> Hello, can I take on this issue?

Page will be removed and redirecting to the download page

#7283

**Comment by AugustinMauroy** [comment]
> > Hello, can I take on this issue?
> 
> 
> 
> Page will be removed and redirecting to the download page
> 
> 
> 
> #7283 

That doesn't mean we didn't need to fix this style issue.
