### ISSUE TITLE
download pages need clear indicators about npm versions

### ISSUE THREAD

**Issue by bengl** [nodejs/nodejs.org#731]
As it stands, this page https://nodejs.org/en/download/current/ doesn't make it very clear at all which version of npm is included with a version of node. It's also pretty easy to be mistaken and think that you can only use the included npm with a given node release. Needs better messaging here.

**Comment by Fishrock123** [comment]
All the versions are included in https://nodejs.org/en/download/releases/ -- shouldn't be too hard if someone wants to pick it up.

We don't keep pages for older releases though, so messaging users of older versions about this isn't really possible in this way.

**Comment by MylesBorins** [comment]
we could include a note at the end similar to the python disclaimer.

> The version of Node.js comes with npm vx.y.z. You can get the latest version of npm with the command `npm install --global npm`

**Comment by rvagg** [comment]
"This version of Node.js is bundled with npm vx.y.z." I'm hesitant to support the upgrade advice, there's good a reason we ship npm's v2 LTS with our LTS.

As already noted, the information about which version of npm is included is already live in the build system for the site so it wouldn't be hard to pick it up for this if someone wants to find a place to put the note on the download page.

**Comment by fhemberger** [comment]
Added a PR for this.
