### ISSUE TITLE
Enable vercel preview on translations PRs

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#7324]
PRs like https://github.com/nodejs/nodejs.org/pull/7321 would be greatly aided in their quality assurance if we allowed previews to be built from them.

Historically, our integration was pushing batches of commits which was very noisy. These now come in as a single commit, so it is not as wasteful in CI or noisy to maintainers

**Comment by bmuenzenmeyer** [comment]
I just double checked on vercel side, there is nothing stopping deployments on that end, so i think the problem is this line - but I am not 100% sure

https://github.com/nodejs/nodejs.org/blob/main/.github/workflows/build.yml#L123

**Comment by bmuenzenmeyer** [comment]
on a second look, i found a setting related to ignoring vercel builds for chore/crowdin branches - let's see what happens next time we sync or push a commit

**Comment by AugustinMauroy** [comment]
bump @ovflowd (the guys who setup Vercel thing)

**Comment by ovflowd** [comment]
> bump [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/12037269?s=64&amp;u=a063cc6b37efab7323f181d260b61ceb834e3e1f&amp;v=4">@ovflowd](https://github.com/ovflowd?rgh-link-date=2024-12-18T11%3A10%3A37.000Z) (the guys who setup Vercel thing)

What are you asking from me? 🤔

**Comment by ovflowd** [comment]
> on a second look, i found a setting related to ignoring vercel builds for chore/crowdin branches - let's see what happens next time we sync or push a commit

Yes, there is a small config that can be removed (at least for the crowdin piece) on Vercel side on the Git Ignore configuration.

**Comment by bmuenzenmeyer** [comment]
everything should be good to go - the next sync via GH Action or workflow dispatch -should- trigger a vercel preview

**Comment by bmuenzenmeyer** [comment]
https://github.com/nodejs/nodejs.org/pull/7343 created the preview 💃 🕺
