### ISSUE TITLE
Incorrect "Want new features sooner?" download suggested on Windows arm64 machines

### ISSUE THREAD

**Issue by wojtekmaj** [nodejs/nodejs.org#7362]
### URL:

https://nodejs.org/en

### Browser Name:

Edge

### Browser Version:

131.0.2903.86

### Operating System:

Windows 11, 24H2, 26100.2314

### How to reproduce the issue:

Closely related to #7239 

1. Open nodejs.org on Windows arm64 machine (e.g. Surface Laptop, 7th edition)
1. Click "Want new features sooner? Get Node.js v23.5.0 instead."
1. At the moment of writing, node-v23.5.0-x64.msi gets downloaded.

**Comment by ovflowd** [comment]
Your Browser is probably not reporting being arm64. Can you verify both your User Agent and run this on your Browser Dev Console? https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/getHighEntropyValues

**Comment by wojtekmaj** [comment]
It's reporting it very well :)

![Image](https://github.com/user-attachments/assets/3f4aae55-d8e4-4e4c-b801-70c305364948)

The big "Download Node.js (LTS)" correctly points to arm64 build - since #7239 has been fixed with #7240 :)

**Comment by ovflowd** [comment]
I see! Let me give it a 👀

**Comment by ovflowd** [comment]
Fixed by https://github.com/nodejs/nodejs.org/pull/7357

**Comment by wojtekmaj** [comment]
Can confirm, working like a charm :)
