### ISSUE TITLE
Install node.js v22.12.0 failed use powershell with unknown problem.

### ISSUE THREAD

**Issue by djx314** [nodejs/nodejs.org#7363]
System: Windows x64
Use the command in nodejs.org to install node.js v22.12.0, and call unknown exception in powershell.

![Image](https://github.com/user-attachments/assets/a296e75e-2334-4917-a37e-7b179b0f2e52)

``` powershell
Windows PowerShell
版权所有（C） Microsoft Corporation。保留所有权利。

安装最新的 PowerShell，了解新功能和改进！https://aka.ms/PSWindows

PS D:\f\tools>
PS D:\f\tools>
PS D:\f\tools> # installs fnm (Fast Node Manager)
PS D:\f\tools> curl -fsSL https://fnm.vercel.app/install | bash
bash : 无法将“bash”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确
，然后再试一次。
所在位置 行:1 字符: 45
+ curl -fsSL https://fnm.vercel.app/install | bash
+                                             ~~~~
    + CategoryInfo          : ObjectNotFound: (bash:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS D:\f\tools>
PS D:\f\tools>
```

**Comment by ljharb** [comment]
Whoops, when I restored the preambles in #7360 i didn't realize fnm had windows-specific install instructions (`winget install Schniz.fnm` and then `fnm env --use-on-cd | Out-String | Invoke-Expression` instead of the first two lines that are currently there). I'll see if I can fix it.

**Comment by ljharb** [comment]
It's also possible that #7357 will fix this.

**Comment by ljharb** [comment]
I believe #7357 has indeed fixed it. Please comment if not, and I'll be sure to reopen.

**Comment by djx314** [comment]
> I believe [#7357](https://github.com/nodejs/nodejs.org/pull/7357) has indeed fixed it. Please comment if not, and I'll be sure to reopen.

@ljharb  Yes, problem with (Windows + fnm) is already fixed.

**Comment by ovflowd** [comment]
Awesome!
