### ISSUE TITLE
"All download options" link broken

### ISSUE THREAD

**Issue by zacharyhamm** [nodejs/nodejs.org#738]
- **URL**: https://nodejs.org/en/download/current/
- **Browser version**: Chrome 50
- **Operating system**: Linux

The link to "All download options" at the bottom of the page points to https://nodejs.org/dist/[object%20Object]

Looks like someone is passing an object where a string was wanted.

**Comment by fhemberger** [comment]
Great, thanks for catching that! This was introduced with 6063d53727c7cc41244911ea5972b95f6bfb95d2, I just pushed the fix.
