### ISSUE TITLE
nodejs.org API doc mistake？

### ISSUE THREAD

**Issue by crazyluffy** [nodejs/nodejs.org#741]
- **URL**:
- **Browser version**:
- **Operating system**:

**Comment by crazyluffy** [comment]
URL: https://nodejs.org/dist/latest-v6.x/docs/api/http.html; 
question: 
    http header message should be [ [key, value], [key2, value2],...], not [key, value, key2, value2,...] ？
    I wonder if it's my mistake of my understand or it's a really mistake. though it's almost not to be used

**Comment by fhemberger** [comment]
Hi,

a) This rather belongs into 'nodejs/node'
b) `message.headers` is a key-value-representation of received HTTP headers, `request.rawHeaders` is an array. As the docs say:

> The raw request/response headers list exactly as they were received.
> 
> **Note that the keys and values are in the same list. It is not a list of tuples.** So, the even-numbered offsets are key values, and the odd-numbered offsets are the associated values.

You probably want to use `message.headers`, as there's usually no real need to access the raw header data.

**Comment by crazyluffy** [comment]
Hi,  
    @fhemberger,  
    Thanks for your reply, I know what I was wrong, 
    this **_options.headers_** is not the **_message.headers_**
    in addition, I'm very appreciate that you can understand what I said. 

.--------------------------------------------------------------------------------------------------
var options = {
  hostname: 'www.google.com',
  port: 80,
  path: '/upload',
  method: 'POST',
._____________________________________________
|  **_headers_**: {
|    'Content-Type': 'application/x-www-form-urlencoded',
|    'Content-Length': postData.length
.|  }
.-----------------------------------------------------------------------------

_// headers:[
//     ['Content-Type', 'application/x-www-form-urlencoded'],
//     [ 'Content-Length', postData.length]
// ]_

};

var req = http.request(options, (res) => {
   ...
};

**Comment by stevemao** [comment]
@crazyluffy You might want to use markdown properly to make it more readable as well 😄 Thanks!

**Comment by crazyluffy** [comment]
@stevemao   yes, I edited it for more readable cause I suddenly remembered the markdown.
also I'm learning both node.js and markdown,  and... english. and sorry to trouble you. Thandks
