### ISSUE TITLE
Add shasums to download page

### ISSUE THREAD

**Issue by raphaelokon** [nodejs/nodejs.org#742]
- **URL**: https://nodejs.org/en/download/current/

I think it would be really helpful to have a direct link to SHASUMS (eg. [SHASUMS256.txt](https://nodejs.org/dist/v6.1.0/SHASUMS256.txt) right on the nodejs.org download page. This would save some users searching for it and extra clicks on _All download options_ to find it there. 

A naive implementation may look like …

<img width="1333" alt="shasums" src="https://cloud.githubusercontent.com/assets/527631/15270537/7756991e-1a23-11e6-9a6a-704da6827913.png">

**Comment by rvagg** [comment]
"for current releases" doesn't make much sense, so probably something like "Signed SHASUMS for vx.y.z release files" and link to the .txt.asc file.

Would you mind sending a pull request to this repo with a change like this along with a screenshot so it can be reviewed?

**Comment by raphaelokon** [comment]
@rvagg Yeah, sorry, I didn't look into the wording that much – was more about the UX to have the functionality straight there. I think `Signed SHASUMS for vx.y.z release files` makes much more sense.

> Would you mind sending a pull request to this repo with a change like this along with a screenshot so it can be reviewed?

I will give it a bash tonight. Cheers.

**Comment by lpinca** [comment]
Can we use "Signed SHASUMS for release files" without specifying the version?
This will simplify the translation as the version position in the sentence depends on the language. Otherwise we have to split the sentence in 3 parts (prefix, version, suffix).
An alternative is to put the version always at the end using something like "Signed SHASUMS for release files (vx.y.z)" but I think it can be omitted as the page already refers to a specifc version.

**Comment by fhemberger** [comment]
I think it's fine to omit the version number, as you said, download pages always refer to a Node.js version anyway.

**Comment by raphaelokon** [comment]
Oh. Damn … I forgot to push my code. I had the change locally since May 16th and forgot to create the PR for it since then … :(

**Comment by lpinca** [comment]
oops sorry @raphaelokon I should have pinged you before creating a new pr. If yours is better I'm fine with closing mine.

**Comment by stevemao** [comment]
@raphaelokon competing PR is always encouraged :)

**Comment by raphaelokon** [comment]
@lpinca Hey no worries :-) I just forgot to push mine. The only difference between yours and mine:
I included the shasum text in the `download` section of `locale/en/site.json`

@stevemao True :-)

**Comment by fhemberger** [comment]
Closed by #819.
