### ISSUE TITLE
Create blog post: Changes between v4 and v6

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs.org#743]
As Node.js v6 will become the new LTS release in a few months, it would be good to have a blog posts explaining the differences between the two to be ready for the update phase.

> If you’re developing on #nodejs 6.x but servers run on 4.x, is there a tool that tells you about features you can’t use? Re: Buffer.from() …
> https://twitter.com/PatrickHeneise/status/731774683528482816

That could be a simple diff between [4.x API docs](https://nodejs.org/dist/latest-v4.x/docs/api/all.html) and [6.x API docs](https://nodejs.org/dist/latest-v6.x/docs/api/all.html) or based on the Wiki articles [Breaking changes between v4 and v5](https://github.com/nodejs/node/wiki/Breaking-changes-between-v4-and-v5) and [Breaking changes between v5 and v6](https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6).

**Comment by PatrickHeneise** [comment]
Context: I was using Buffer.from() as documented in 5+ docs, and there was no information it's not available in 4.x; problem was Buffer.from() didn't break with a 'is not a function' but a TypeError, which was very confusing.

I think these changes should also be documented somewhere in machine readable form (.json f.e.) so we could analyse projects/code and tell developers they're using functions which are not implemented or behave differently in the LTS version, compared to the Current version.

**Comment by Fishrock123** [comment]
Sounds like you're actually asking for https://github.com/nodejs/node/issues/6578?

**Comment by fhemberger** [comment]
@Fishrock123 I think that's at least a big part of the solution, still as soon as v6 becomes the new LTS, people want to know what's changed since v4 (just like the "breaking changes" wiki article you already did for past versions).
