### ISSUE TITLE
Please replace Sauce Labs logo with new one

### ISSUE THREAD

**Issue by gtewallace** [nodejs/nodejs.org#750]
- **URL**:
- **Browser version**:
- **Operating system**:

On Foundation > Members, need to replace the Sauce Labs logo with the attached.

thanks!

![sauce-labs_vert_red-grey_200x200](https://cloud.githubusercontent.com/assets/12159820/15369802/3a874b50-1d02-11e6-9bab-0317d718c4a4.png)

**Comment by MylesBorins** [comment]
@gtewallace here is a pull for that update --> https://github.com/nodejs/nodejs.org/pull/751

Do they have a better copy of the logo though? That one is pretty blury
