### ISSUE TITLE
Not all globals are documented

### ISSUE THREAD

**Issue by dfahlander** [nodejs/nodejs.org#753]
- **URL**: [https://nodejs.org/api/globals.html](https://nodejs.org/api/globals.html)
- **Browser version**: N/A
- **Operating system**: N/A

In the list of globals, I don't find some globals, such as Uint16Array, Uint8Array, etc even though they are obviously globals and don't need to be required in.

For people trying to write universal javascript, it would be quite nice to have a proper documentation of all globals in node.

Running the following code will print out many globals that are missing in the global documentation page:

``` js
Object.getOwnPropertyNames(global).forEach(x => console.log(x));
```

**Comment by lpinca** [comment]
@dfahlander thanks, but you are in the wrong repo.
This should be reported to https://github.com/nodejs/node/issues.

**Comment by dfahlander** [comment]
I thought this was the website, right? Doesn't this belong here since it's about missing content on the web site?

**Comment by lpinca** [comment]
Yes, this is the website repo but API [documentation](https://github.com/nodejs/node/tree/master/doc/api) lives in the main repo.

**Comment by dfahlander** [comment]
Ok, thanks.

**Comment by ghost** [comment]
to be fair we should probably put a note somewhere that the docs live in the main repo

**Comment by lpinca** [comment]
@tentakel yes I agree. Right now the website seems the natural place where to post API docs issues.

**Comment by lpinca** [comment]
We can probably update the issue template as discussed in https://github.com/nodejs/nodejs.org/pull/707 and add this info.

**Comment by fhemberger** [comment]
It's already in the issue template: https://raw.githubusercontent.com/nodejs/nodejs.org/master/.github/ISSUE_TEMPLATE.md

**Comment by lpinca** [comment]
ops, I should have read it more carefully 😄
