### ISSUE TITLE
CloudFlare blocking nodejs.org web site access for users running Tor

### ISSUE THREAD

**Issue by fredrikgrohn** [nodejs/nodejs.org#757]
- **URL**: https://nodejs.org/
- **Browser version**: Tor Browser 5.5.5 (Mozilla Firefox 38.8.0)
- **Operating system**: Windows 7 SP1

In case there is someone not familiar with Tor: Tor is a network that enables users to maintain online anonymity and resist censorship and surveillance. It is the biggest network of its kind. For further refernce please see the Tor web site (https://torproject.org), or the Wikipedia article (https://en.wikipedia.org/wiki/Tor_%28anonymity_network%29).

As a Tor user myself, I have noticed that I very frequently am blocked from accessing the node.js web site by CloudFlare. The experience for a user that gets blocked by CloudFlare is that, instead of the node.js web site, the user is shown a page explaining that the connection has been blocked and requesting the user to complete one or more CAPTCHA tests. These tests also require cookies to be stored in the browser client. It is usually possible to get past the CAPTCHA test from within one minute, to no more than a couple of minutes, the requests to complete CAPTCHA tests can then be repeated as often as for every page load.

These tests constitute a significant obstacle for accessing any web site where they are deployed. There are also frequent anecdotal reports of users being given infinite repeating CAPTCHA tests and never given access to the target web site, or the CAPTCHA tests simply failing to load. It should also be noted that CAPTCHA tests can be difficult to solve for people who are visually impaired.

The problem appears to be that CloudFlares threat scoring algorithm gets confused by the large number of diverse connections coming from Tor exit nodes, and mistakenly classifies it them as malicious, and then retains this classification indefinitely.

It is also worth noting that the CloudFlare competitor Akamai does not have the same issue with their threat scoring algorithm.

CloudFlare appears to be aware of the problem, but unable to solve the problem with their scoring algorithm. Instead they have posted a workaround on their support web site:

https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-

As stated on their web site, CloudFlare has changed their system to classify all Tor exit nodes as a separate geo-location and are recommending that web site owners add a white-list entry for users coming from this Tor network geo-location under their "firewall" interface. (See web site for full details.)

It appears simple to do, and would help users like me a lot.

**Comment by mikeal** [comment]
@nodejs/build

**Comment by rvagg** [comment]
I've whitelisted the "Tor" country, could you give it a try now and report back if you have further problems with this please @fredrikgrohn?

**Comment by fredrikgrohn** [comment]
Yes I have verified about 10 exit nodes. It seems to be unblocked now. Thanks for your help!
