### ISSUE TITLE
outdated governance information

### ISSUE THREAD

**Issue by Trott** [nodejs/nodejs.org#758]
- **URL**: https://nodejs.org/en/get-involved/development/#collaborators
- **Browser version**: n/a
- **Operating system**: n/a

The information in https://github.com/nodejs/nodejs.org/blob/master/locale/en/get-involved/development.md is out of date. Primarily, it mentions the TSC many times but there is no mention of the CTC. It seems like it duplicates info in the nodejs/node repo. I wonder if it should be much shorter and link out to the .md files in that repo so as to not have the issue of needing to stay in sync with it?

**Comment by fhemberger** [comment]
You are right, it's too long and too complicated. Nobody is going to read that entire page before submitting something for the first time. Having a shorter version (or linking to CONTRIBUTING.md in nodejs/node) would be a great idea.

IIRC part of the texts still date back to the old Node.js website and were extended with new content. So maybe a general review would make sense as well.

**Comment by williamkapke** [comment]
I also agree. The information on that page is important, but too granular. For **anything** in these areas on the website, I think things should stay pretty high level.

Because the website is the entry point for the general public, I like to think to myself "If a typical journalist were to see this page, would they be able to understand of the majority of the content?"

**Comment by Trott** [comment]
@fhemberger On the principle of not having more than one place to manage information, perhaps that section could be replaced with a sentence that links to https://github.com/nodejs/node/blob/master/GOVERNANCE.md#collaborators. That doc is kept up-to-date. It would also help make that far-too-long (IMO) web page a little shorter.

**Comment by Trott** [comment]
I think the section labeled "A Few Open Questions" should also be removed. In fact, that should be so uncontroversial that I'll open a PR to do that right now....

**Comment by mlosh** [comment]
Landed, so this can be closed.

**Comment by Trott** [comment]
(By the way, now my original comment above from May 2016 is out of date--there is no CTC anymore, so lots of TSC mentions probably makes sense again. Another argument for directing people to the GOVERNANCE.md doc in the repo rather than trying to duplicate the information on the website.)

**Comment by fhemberger** [comment]
@Trott So what part of the page should be replaced with the link? Only the "Collaborators" section or the entire thing?

Personally I'd love to get rid of the entire page (this is *way* too much badly structured information, no one will read it anyway). First step would be replacing it with a link. But in the future, I'd love to pull the page's content directly from the repo during build. The website should IMHO still be the first entry point for answering general questions, not just a proxy for a bunch of GitHub links (we had the same issue already somewhere else).

**Comment by Trott** [comment]
@fhemberger I agree the page can be removed entirely. Not sure how many links there are to it, but those links can be replaced with links to CONTRIBUTING.md or GOVERNANCE.md or something else (depending on their context).
