### ISSUE TITLE
Dead link in non-English language

### ISSUE THREAD

**Issue by undownding** [nodejs/nodejs.org#764]
- **URL**: https://nodejs.org/zh-cn/
- **Browser version**: Chrome 50
- **Operating system**: Ubuntu 16.04

![404](https://cloud.githubusercontent.com/assets/11864301/15632238/e2faf282-25bd-11e6-8f9c-9bcdacd0fb6a.png)

What's the right way to solve this problem? Add a translated `index.md` in `locale/zh-cn/download`, or change this link to [https://nodejs.org/en/download/](https://nodejs.org/en/download/)?

**Comment by lpinca** [comment]
I think that adding the translated *.md files is the correct way to handle this.
If I'm not wrong there is also an open pr (https://github.com/nodejs/nodejs.org/pull/490) to "fix" this.

**Comment by undownding** [comment]
OK, I will fix zh-cn language.

**Comment by ghost** [comment]
yeah, the zh-cn locale basically only has the index and a couple more pages. there's a huge amount missing, which is why #490 would help

**Comment by Fishrock123** [comment]
#490 does not actually help this.

That only helps if you run it locally.

The actual issue is https://github.com/nodejs/build/pull/316

**Comment by fhemberger** [comment]
This has been fixed now: Links are falling back to the English version.
