### ISSUE TITLE
Add São Paulo NodeConf Brazil 2016 to events page

### ISSUE THREAD

**Issue by glennschler** [nodejs/nodejs.org#767]
As recognized in pull #766 discussion, the Nodeconf Brazil 2016 is actually the first international Node conference planned to occur in Latin America. It should be added to the https://nodejs.org/en/get-involved/events page

**Comment by glennschler** [comment]
@alanhoff If you would like, I can add the Brazil conference when I edit the Argentina description I recently submitted. If you send a description, plus lat/lon coordinates for the map.

**Comment by alanhoff** [comment]
@glennschler that would be awesome

**Description**
This is the first edition of NodeConf in Latin America and is also the first major event focused exclusively on Node.js of Brazil. We'll have an amazing experience in São Paulo on 2 days filled with large lectures and some surprises waiting for you.
In this first edition, we will be bringing news about how is the current scenario of Node.js. We will create an environment of contact between companies and developers, a space for disseminating the knowledge, cool projects made by Community and also have special guests who are influence on Node.js at world level.

**Location**
LAT -23.5539247, LON -46.6550992
https://goo.gl/yIGucy

**Comment by lpinca** [comment]
Closed as the event has been added.
