### ISSUE TITLE
Highlight deprecated API components in "Table of Contents"

### ISSUE THREAD

**Issue by ilfroloff** [nodejs/nodejs.org#772]
Hello All!

I have a proposal of how to increase understanding on which of properties/methods in module API are deprecated. When someone opens module's API page, he/she sees "Table of Contents" and it's not clear which part is deprecated (especially in `util` module).

My vision of deprecated parts in "Table of Contents":
![Change the color](https://cloud.githubusercontent.com/assets/2785744/15742967/d483b22e-28ca-11e6-96bc-eff3f529fbbc.png)

CSS for list item:

``` sass
li.deprecated,
li.deprecated a {
    color: #D60027; // same as backgroud-color of Deprecated box
}
```

Thanks!

**Comment by MylesBorins** [comment]
I really like this idea

/cc @nodejs/documentation 

@ilfroloff I think you will want to send a PR against the main repo to this file https://github.com/nodejs/node/blob/master/doc/api_assets/style.css

**Comment by lpinca** [comment]
👍

**Comment by ghost** [comment]
sounds good, yeah!

**Comment by benjamingr** [comment]
I think graying it out rather than making it red would be better since red catches the eye.

**Comment by Knighton910** [comment]
LGTM
+1 GRAY

**Comment by steebchen** [comment]
What about striking through deprecated lines: ~~deprecated~~
Or striking through while colored grey?

``` css
li.deprecated,
li.deprecated a {
    color: #ccc;
    text-decoration: line-through;
}
```

**Comment by evanlucas** [comment]
I think I would like gray. It would be awesome to see some prototypes though

**Comment by benjamingr** [comment]
@evanlucas sure, run this in the chrome devtools at the production docs and it will strikethrough and change the color of all deprecated APIs.

``` js
var links = Array.from(document.querySelectorAll("#toc li a"))
for(const method of links) { // very hacky
  const marker = document.querySelector(method.getAttribute("href"));
  if(!marker) continue;
  const heading = marker.parentNode.parentNode;
  let stability = heading.nextElementSibling;
  if(stability.className === "api_metadata") stability = stability.nextElementSibling; 
  if(stability.className.includes("api_stability_0")) {
     method.style.color = "#999";
     method.style.textDecoration = "line-through";
  }
}
```

**Comment by evanlucas** [comment]
thanks @benjamingr. So the link becomes a lot less readable on hover would be my only complaint with that. I'm sure we could fix that quite easily though. I think the best think to do here would be to have a pr with one of these on nodejs/node and we can go from there?

**Comment by addaleax** [comment]
As much as I would find gray more intuitive, too, I’d be worried that the low contrast from graying out entries might not work out as well as striking through for people with visual impairments. But then again I’m also definitely not an expert on that topic.

**Comment by Knighton910** [comment]
I was thinking about a `dark blue`, but at the same time i don't want the docs to look like a rainbow. no offense to rainbows. But something of `grey` or `dark grey` or even `vanilla white` should be fine, i guess.

**Comment by benjamingr** [comment]
@addaleax that's a good point, `#999999` doesn't meat [the contrast accessibility standard](http://webaim.org/resources/contrastchecker/), we should go with something more like `#555555`.

**Comment by RafaelKr** [comment]
> As much as I would find gray more intuitive, too, I’d be worried that the low contrast from graying out entries might not work out as well as striking through for people with visual impairments. But then again I’m also definitely not an expert on that topic.

You could make deprecated items grey and add a toogle-button at the top to also strike them through (Or don't show them at all, when button is toggled).

**Comment by ilfroloff** [comment]
> @ilfroloff I think you will want to send a PR against the main repo to this file https://github.com/nodejs/node/blob/master/doc/api_assets/style.css

Created PR https://github.com/nodejs/node/pull/7189
