### ISSUE TITLE
We should consider updating the changelog links

### ISSUE THREAD

**Issue by evanlucas** [nodejs/nodejs.org#775]
- **URL**: https://nodejs.org/en/
- **Browser version**: *
- **Operating system**: *

Recently, there was a large change made to the way the changelog for core is structured. We have now split the changelog up by version. Both of the changelog links for the latest release lines point to the specific tag for that version. However, only the changelog on master is guaranteed to be updated/correct.

We could point them to the changelog for that major version like:

From: https://github.com/nodejs/node/blob/v6.2.1/CHANGELOG.md
To: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md

Or we could simply have a single changelog link.

I think I would prefer the first. Would love to hear everyone's thoughts on this though.

The links are below the version buttons as shown in the image below:

![screen shot 2016-06-02 at 8 44 08 pm](https://cloud.githubusercontent.com/assets/677994/15766326/cc1b2346-2902-11e6-81db-f26023b176bb.png)

**Comment by MylesBorins** [comment]
It is worth mentioning that v4 is still using the old changelog... so that link works as expected

**Comment by evanlucas** [comment]
ooooo thanks for the heads up @TheAlphaNerd. Are there plans to backport it to v4?

**Comment by MylesBorins** [comment]
Tbh I wasn't planning to as the original changelog just works in v4.
Totally willing to do it if it helps simplify the website /cc @jasnell

**Comment by jasnell** [comment]
I've had an open low priority to-do to backport the changelog changes. I'll likely get to it next week.
