### ISSUE TITLE
Collaborating on the next redesign

### ISSUE THREAD

**Issue by leo** [nodejs/nodejs.org#779]
Hey awesome people!

After many emails between me and the technical steering committee, @mikeal and I finally worked out a plan for me continuing with the [design](https://github.com/nodejs/nodejs.org/issues/508) for the new site:

We're going to set up a new repo within which I'm going to ask the community for feedback in the process of designing the site. After the design is ironed out, I'm going to start developing it with the rest of the website WG on top of the current repo/commit history of the site (so that no old commits get lost).

To keep things clear, I'd like all upcoming design-related issues to be forwarded to the design repo so that I can consider them while designing.

Because of this, I'd like to be a member of the website WG. A great side-effect of this is me being able to these things without having to wait for someone else to do it. @mikeal said he could advocate for that... But since the most important aspect of a good community is everyone being as transparent as possible, I definitely need to tell you what we're planning. :blush:

Let's rock this! :metal:

**Comment by ghost** [comment]
woot! the website wg is gonna do their best to help migrate the content!

**Comment by mikeal** [comment]
Created a repo for the re-design assets https://github.com/nodejs/nodejs.org-redesign

**Comment by ghost** [comment]
@mikeal what do you mean by 'html and css assets' specifically?

**Comment by mikeal** [comment]
@ore So, it is quite challenging to do the whole design and iteration on top of all the tools and templates we have in this repo. The basic idea is to create image mockups and then implement as static html/css in the other repo until the design is correct. Once it is what people want we can port that back over to this repo and all the tools and templating.

**Comment by ghost** [comment]
@mikeal yeah, that sounds fair enough.

also, while we're basically redoing the whole site, i'd like to take the opportunity and unfuddle and modernize the backend a little bit. it's very hack-ish in some places and i'd like to see if i can make something work there.

**Comment by leo** [comment]
Exactly like @mikeal said it! It's already pretty hard to gather the most relevant feedback of a big group of people. So doing the design in a separate repo makes it a lot easer.

@ore Yey, great to hear!

**Comment by MylesBorins** [comment]
first issue opened over at https://github.com/nodejs/nodejs.org-redesign/issues/1

Around making sure download page can support more than 2 release lines (for upcoming v6 lts)

**Comment by rvagg** [comment]
please ping the build WG when you have some content to work with so we can set up a `redesign.nodejs.org` or similar that automatically builds from `master`, it'll help you but also us when we finally need to ship it so we can iron out any surprises along the way

**Comment by leo** [comment]
@rvagg Got it! The plan is to start working on a separate branch of this repo (as soon as the design is finished and we're ready to implement it).

**Comment by italoacasas** [comment]
@leo any status about the design, I would like to give you a hand to implement it.

**Comment by leo** [comment]
@italoacasas I'm on it! But for the official start, I'm still waiting for @mikeal to make me a collaborator on this repo (for the reasons mentioned above). He's probably pretty busy currently (tried email)...

**Comment by Fishrock123** [comment]
@leo Where is the discussion about access? I don't see it here. I can add you though if you need it...

**Comment by leo** [comment]
@Fishrock123 @mikeal didn't say exactly that he "will add me as a collaborator". But he did say that "adding me to the WG wouldn't be a problem" and he "would advocate for that" (we've discussed it via email).

**Comment by Fishrock123** [comment]
cc @nodejs/website ^^

**Comment by ghost** [comment]
i mean, sure

**Comment by raphaelokon** [comment]
If you guys have a need for an MA Interaction/Interface designer with +10 years of frontend/JS experience … give me a ping. I am using Node in production and would like to give back a bit what I got out of Node.

**Comment by leo** [comment]
### Quick update

I'm now working full-time at @zeit, where I'm currently leading Open Source and community-facing projects. I've already chatted with @rauchg about this and we came to the conclusion that I'll soon get a few weeks time specially for designing the site.

I don't yet know when this will be (probably in a month or so), but I definitely think that it's a great way to handle it because it ensures that I can put a constant stream of creativity into it, which means that it won't just be a half-backed design.

For all of you who would like to help with the UI part: You can find my email address on my GitHub profile. If you have any basic ideas how the layout (not necessarily the colors, really just the basic order of the elements) could look like, please send me an example and I'll include it in the process of creating the full-blown design.

**Comment by mikeal** [comment]
@leo Congratulations on getting a role with @zeit!!! I don't often get excited about infrastructure services but I've been jumping up and down about zeit/now for a while now.

**Comment by leo** [comment]
@mikeal Thank you! ❤️

You won't be disappointed about what we have in the pipeline for the future!

**Comment by phillipj** [comment]
> For all of you who would like to help with the UI part: You can find my email address on my GitHub profile. If you have any basic ideas how the layout (not necessarily the colors, really just the basic order of the elements) could look like, please send me an example and I'll include it in the process of creating the full-blown design.

@leo it would be great if further progress and ideas on this could be made public, e.g. as one or more issues in this repo. We're all very excited about this, and doing it public could only lead to more feedback and contributions - great success 😸

**Comment by ghost** [comment]
@phillipj there's https://github.com/nodejs/nodejs.org-new for this AFAIK

**Comment by leo** [comment]
@fene Exactly.

@phillipj Please read the full issue text on the top. :blush:

**Comment by zaynv** [comment]
I think he meant that instead of having people email you, it might be better for them to just raise issues in the repo so that it's more publicly available and the community will be able to share opinions on proposals as well.

**Comment by leo** [comment]
@zaynv Sure, why not! 👌

**Comment by phillipj** [comment]
> @phillipj there's https://github.com/nodejs/nodejs.org-new for this AFAIK

@fene yet @leo [said earlier](https://github.com/nodejs/nodejs.org/issues/779#issuecomment-225449094) that work was going to be done on a branch on _this_ repo. Which repo is not important to me, as long as we get the party started 👯

**Comment by leo** [comment]
@phillipj Like mentioned above, the "nodejs.org-new" repo is for the design process:

> We're going to set up a new repo within which I'm going to ask the community for feedback in the process of designing the site.

And the branch on the current repo is where the actual development happens:

> After the design is ironed out, I'm going to start developing it with the rest of the website WG on top of the current repo/commit history of the site (so that no old commits get lost).

😊

**Comment by phillipj** [comment]
Any progress here @leo?

**Comment by zlatanvasovic** [comment]
If you need human help to finish the proposed changes, I'll be glad to help with that. :smile:

**Comment by leo** [comment]
I've been chatting with @rauchg again and we're scheduling some time for me to work on this in the coming weeks, and some additional resources if needed. Stay tuned! 🚀 ⭐️

**Comment by bnb** [comment]
@leo Would love to help with feedback and commentary - this is much needed, and I'm happy to help with some cycles.

**Comment by timneutkens** [comment]
@leo I can help coding stuff 👍

**Comment by stefanivic** [comment]
@leo I am here for any design/coding related stuff. :D

**Comment by timothyis** [comment]
I'm happy to propose a redesign for the website. I'll follow up with a submission soon.

**Comment by L-A** [comment]
Happy to jump in on the design side too. I don't know if the existing redesign is still the plan? – I won't take the lead without being asked for it but I have a good amount of time I could dedicate in the coming days.

**Comment by leo** [comment]
https://github.com/nodejs/nodejs.org/issues/1074#issuecomment-267754752

**Comment by fhemberger** [comment]
Closing this in favor of https://github.com/nodejs/nodejs.org/projects/1.
