### ISSUE TITLE
Why does nodejs.org use cloudflare-nginx?

### ISSUE THREAD

**Issue by marler8997** [nodejs/nodejs.org#780]

**Comment by stevemao** [comment]
Can you elaborate what the problem is?

**Comment by marler8997** [comment]
Why doesn't it use nodejs?

**Comment by PatrickHeneise** [comment]
CloudFlare is a content delivery network to distribute the website around the globe, that's why you see `cloudflare-nginx`.

**Comment by marler8997** [comment]
Ah oh, makes sense
