### ISSUE TITLE
Error 522 on cloudflare 

### ISSUE THREAD

**Issue by GaryWayneSmith** [nodejs/nodejs.org#781]
Error 522 Ray ID: 2b06db3818810da9 • 2016-06-09 19:05:54 UTC
Error 522 Ray ID: 2b06de40df221ed1 • 2016-06-09 19:07:59 UTC
Connection timed out

Windows 7 x64, tried multiple browsers

Can't download Windows binaries or installers.

**Comment by rvagg** [comment]
@GaryWayneSmith I'm going to close this as I'm assuming it was a temporary blip. Please let us know if this is persistent for you and we might be able to dig deeper.
