### ISSUE TITLE
TSC minutes page is off track

### ISSUE THREAD

**Issue by williamkapke** [nodejs/nodejs.org#791]
There is [a page on the website](https://nodejs.org/en/foundation/tsc/minutes/) that isn't too easy to find but it, in theory, to be for posting the TSC minutes. It doesn't have TSC minutes, it has other working groups.... and nothing has been added since last year :(

No biggie- this page lost steam. Let's put it on the radar for doing SOMETHING with it :)

I came across this while adding the minutes to the TSC repo. [PR is here](https://github.com/nodejs/TSC/pull/111). If the page is really for TSC minutes, I'd just change the link on https://nodejs.org/en/foundation/tsc to point to the `meetings` folder I added with my PR.

**Comment by fhemberger** [comment]
The TSC minutes on that page were imported from the old Node.js website.

**Comment by mikeal** [comment]
Maybe we should just link to the minutes directory in all the related projects? Maybe also link to the videos?

**Comment by williamkapke** [comment]
@fhemberger ah yep, that sounds right!

@mikeal It would be nice to link all the projects. I'll do more PRs adding them as I go. The videos are linked in the meeting minutes markdown (well, they are for the TSC).

**Comment by Fishrock123** [comment]
Yeah maintaining the list here seems difficult unless it is generated somehow.

**Comment by fhemberger** [comment]
Closing because of https://github.com/nodejs/TSC/issues/312

**Comment by williamkapke** [comment]
The merge doesn't invalidate that that page is still quite invalid.

We should still do as @mikeal said:
> Maybe we should just link to the minutes directory in all the related projects? Maybe also link to the videos?

**Comment by maclover7** [comment]
Sorry, forgot to link this from #1440... I think this can be closed now?

**Comment by maclover7** [comment]
ping @fhemberger -- I think this can be closed
