### ISSUE TITLE
Update Code + Learn page

### ISSUE THREAD

**Issue by williamkapke** [nodejs/nodejs.org#796]
There will be Code + Learn events in Amsterdam and Austin: See [here](http://events.linuxfoundation.org/events/node-interactive-europe/attend/agenda) and [here](http://events.linuxfoundation.org/events/node-interactive/attend/agenda).

[The Code + Learn page](https://nodejs.org/en/get-involved/code-and-learn/) should be updated. I am, unfortunately, unlikely able to do a PR for this anytime soon so I'm hoping someone will pick it up.

also: https://github.com/nodejs/code-and-learn/issues/56

**Comment by fhemberger** [comment]
Can someone please add a PR for this? /cc @nodejs/website
