### ISSUE TITLE
release post script breaking without ### Notable Changes

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/nodejs.org#802]
If a release post does not include`### Notable Changes` the tool blows up

**Comment by lpinca** [comment]
I think it makes sense to always include a `### Notable Changes` section even if it is a security only release. For example this is what @rvagg did with `0.12.15` and `0.10.46`:
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V012.md#2016-06-23-version-01215-maintenance-rvagg
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V010.md#2016-06-23-version-01046-maintenance-rvagg

**Comment by phillipj** [comment]
IMO the release script should never stand in the way of getting a release post out the door asap. Ideally it would be forgiving and try to do as best as it can, and maybe print a warning or two if something is missing. Of course it simplifies the release post script if could be confident the changelog is formatted correctly, but that would imply linting the changelog somehow before it's merged into core.

**Comment by lpinca** [comment]
The changelog should definitely be linted before being commited.
I agree that the release script should be forgiving but to a certain degree. If an important section is missing, for example, it should throw an error, like it does now.

**Comment by lpinca** [comment]
Ref: https://github.com/nodejs/node/pull/7394.

**Comment by lpinca** [comment]
It was like [this](https://github.com/nodejs/nodejs.org/pull/739/files#diff-f417caca187eb6b21f702d5ab2d9aab7L130) (no Notable Changes -> error) even before the script had been updated to handle the new changelog structure.
I still think that this is the correct behavior but I'm fine with changing it to handle cases where "Notable Changes" is missing.

**Comment by fhemberger** [comment]
@TheAlphaNerd @lpinca Does this issue still exist?

**Comment by MylesBorins** [comment]
it does AFAIK

**Comment by lpinca** [comment]
Yeah but the tool was designed to do this.
I mean it errors if there isn't a "### Notable Changes" section. It was like this from the beginning.
