### ISSUE TITLE
Language picker

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/nodejs.org#806]
Now that https://github.com/nodejs/nodejs.org/pull/490 has landed and the related build/deployment work seems to be completed, we should be able to get the language groups once again more involved with the website.

We should also start thinking of a way to choose the language.

I'm not sure io.js's way was really that great. I know we discussed the flag thing before, but to me that is the most easily recognizable way.

We don't have to have that open a country list, but we can use it as a prompt for language nonetheless.

cc @nodejs/website 
cc also @leo who may have some ideas?

**Comment by leo** [comment]
That seems like something that should be implemented with the next redesign. So it would be great if you could add it to [this repo](https://github.com/nodejs/nodejs.org-new/issues). More details [here](https://github.com/nodejs/nodejs.org/issues/779):

> To keep things clear, I'd like all upcoming design-related issues to be forwarded to the design repo so that I can consider them while designing.

**Comment by Fishrock123** [comment]
Sure, I guess? But we kinda need it before then. Can't hold everything up for that.

**Comment by ghost** [comment]
one thing we could do if we're really getting translation efforts back up again is probe for the activeness of the i18n WGs

**Comment by fhemberger** [comment]
Quoting myself here from https://github.com/nodejs/iojs.org/issues/235:

> Flags != Languages.
> We could add automatic redirection to the localized version based on the user's 'Accept-Language' header settings. There's an nginx module for that: http://wiki.nginx.org/AcceptLanguageModule

**EDIT** New link: https://www.nginx.com/resources/wiki/modules/accept_language/

I think it's the most reliable way to determine a user's language without the need for user interaction.

**Comment by ghost** [comment]
we should also probably assemble a separate team to control translation efforts. the iojs way wasn't the best

**Comment by leo** [comment]
@Fishrock123 Ahh, no problem! Didn't know that.

**Comment by ghost** [comment]
@fhemberger i wouldn't do it automatically though. maybe a hint from somewhere within the site asking if you want to switch to the version of the site in your language

**Comment by Fishrock123** [comment]
@ore https://github.com/nodejs/nodejs-ko is quite active.

---

> > Flags != Languages.

My point also, but we shouldn't have the selection be flags, only the initial, along with the Language indicator.

I.e. 

[🇩🇪 DE] is a little more visible than [DE] for such a thing.

> > We could add automatic redirection to the localized version based on the user's 'Accept-Language' header settings. There's an nginx module for that: http://wiki.nginx.org/AcceptLanguageModule
> 
> I think it's the most reliable way to determine a user's language without the need for user interaction.

perhaps but idk if I'm comfortable not having an easy way to adjust it?

I'm willing to look into the nginx thing though

**Comment by ghost** [comment]
@Fishrock123 yeah, but that's one of the only ones 😞

**Comment by fhemberger** [comment]
@ore You still could add a cookie for example: "Nah, I want to browse the site in Klingon". In case we're adding a manual selection dropdown, this should be done anyway.

**Comment by fhemberger** [comment]
Link to the nginx module is now https://www.nginx.com/resources/wiki/modules/accept_language/
… and meh, it's a 3rd party module. Thought it was a core feature.

**Comment by srl295** [comment]
I'd recommend (1) content negotiation and then (2) a simple popup with a textual list of languages.

I would NOT recommend flags. You could put a little stylized globe for an icon to represent the language choice perhaps. [English 🇦🇺](http://www.unicode.org/cldr/charts/latest/supplemental/language_territory_information.html#en)  is spoken in a lot of places, as is [French🇧🇱](http://www.unicode.org/cldr/charts/latest/supplemental/language_territory_information.html#fr), etc. for that matter. Would be a lot of flags.

You could add a cookie and not change the URL. That means if you're browsing in French and you send the link to someone who prefers Spanish, they will see the same content in Spanish. 

It might be better to redirect to a specific URL  ( like /fr/ or /en/ ) so that links go to the right thing, with a popup offering to take you to your "preferred" language (content / cookie negotiated) if different.

**Comment by ghost** [comment]
i am going to open a separate issue regarding translation in general in this repo

**Comment by Fishrock123** [comment]
From The Korean Translation Group: https://github.com/nodejs/nodejs-ko/issues/381#issuecomment-229031422:

> and I think there is a dropdown menu is needed to select languages.

**Comment by alexandrtovmach** [comment]
Hello, I'm not sure what is the current status with language picker implementation. Can I propose something? I'm ready to implement and create PR with language picker on my own. Does it's have a reason?

**Comment by srl295** [comment]
@alexandrtovmach just an example on my above discussion, instead of flags use `українська | français | español | 日本語` etc

**Comment by alexandrtovmach** [comment]
@srl295 could you take a look on my PR?

**Comment by alexandrtovmach** [comment]
This feature already merged, so I think is good idea to close this issue
