### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#807]
this is a general thread for bringing translation efforts for the website back on track. in a way, a continuation from #806.

list of potential things to do:
- check i18n WGs for activeness, if needed, call for new translators
- assemble a dedicated team/WG for translation (?)

**Comment by Fishrock123** [comment]
Made possible by https://github.com/nodejs/nodejs.org/pull/490 / https://github.com/nodejs/build/pull/316

**Comment by edsadr** [comment]
quick question, what would be the minimum amount of content suggested to create the locale? we are currently planning to translate a lot here: 

https://github.com/nodejs/nodejs-es/issues/139 (Warning: Spanish there)

But we already have some basic content translated and reviewed here: https://github.com/nodejs/nodejs-es/pull/138 

When should we create the PR?

**Comment by fhemberger** [comment]
I'd say whenever you think the site's state useful for the visitor.

**Comment by Fishrock123** [comment]
> quick question, what would be the minimum amount of content suggested to create the locale?

@edsadr I'd say the top-level `home`, `about`, `downloads`, and `docs` pages. `404` is also simple and important.

Even better, also include the top-level `foundation`, `get-involved`, and `security` pages.

**Comment by edsadr** [comment]
ok @Fishrock123  home, downloads, security and 404 are done, working on about and then we will see about docs so hopefully next week we could have a basic PR for ES locale
