### ISSUE TITLE
EU/US confusion

### ISSUE THREAD

**Issue by naugtur** [nodejs/nodejs.org#813]
Should this link open a page starting with SAN FRANCISCO, June 29, 2016?

https://nodejs.org/en/blog/announcements/interactive-2016-ams/
It's been advertised as the european one on twitter

```
We are excited to announce #NodeInteractive Europe's agenda happening in Amsterdam, Sept 15 -16: http://bit.ly/2942pod
```

**Comment by mikeal** [comment]
It's a press release, press releases always start with a day and location they originate.

**Comment by naugtur** [comment]
That's not the most intuitive thing ever, but sorry for spamming you guys anyway ;)
