### ISSUE TITLE
Always translate header & footer templates?

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/nodejs.org#825]
I'm not sure this is feasible, but maybe we should build all possible pages that exist from `en` in every language using the localized templates (header, footer, etc), and use those pages as the fall-backs rather than the actual english pages.

This has two obvious downsides, beyonds complexity:
1. Build times would be dramatically increased.
2. Build output size.
## 

Perhaps a bit more involved, maybe we can get nginx to serve some sort of partials where we concat the header to the body directly during serving? Is that even possible? I have no idea.

**Comment by phillipj** [comment]
> This has two obvious downsides, beyonds complexity:
> 1. Build times would be dramatically increased.
> 2. Build output size.
1. Mostly an issue when developing locally. Could be less of an issue if we made it possible to specify which locale to build.
2. With the current set of locales, it would have increased the total build size from ~26MB -> 58MB. Still pretty low figure IMO.

> Perhaps a bit more involved, maybe we can get nginx to serve some sort of partials where we concat the header to the body directly during serving? Is that even possible? ..

Server Side Includes could be an option if we want to go down this route... http://nginx.org/en/docs/http/ngx_http_ssi_module.html

**Comment by ZYSzys** [comment]
> I'm not sure this is feasible, but maybe we should build all possible pages that exist from en in every language using the localized templates (header, footer, etc), and use those pages as the fall-backs rather than the actual english pages.

If I'm not wrong, the PR #1940 has implemented this now.

**Comment by fhemberger** [comment]
Yes, it did. Closing.
