### ISSUE TITLE
questions for "about" documents

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs.org#830]
We're working on translating the website as Korean, see https://github.com/nodejs/nodejs-ko/issues/381. We encounter a few issue with content.
1. In [locale/en/about](https://github.com/nodejs/nodejs.org/tree/master/locale/en/about/), there is an `advisory-board` folder, but we can't found where it is used on the website. we guess it is a missing link.
2. [locale/en/about/organization.md](https://github.com/nodejs/nodejs.org/blob/master/locale/en/about/organization.md) is same with above. 

So, we can't decide whether we put our effort to translate these documents into Korean. If these aren't used anymore, these should be removed. We can make a pull request for it, if so.

And we can't understand the meaning at [Addon API Working Group](https://nodejs.org/en/about/working-groups/#addon-api)

> The NAN project makes available an abstraction layer for native add-on authors for `both Node.js and Node.js`, assisting in the writing of code that is compatible with many actively used versions of `Node.js, Node.js`, V8 and libuv.

in `both Node.js and Node.js` and `Node.js, Node.js`, why is there two "Node.js". Does it means different respectively. It was introduced in [this commit](https://github.com/nodejs/nodejs.org/commit/41fe898c4e6a24dd0620e12519504d4545e7dda9#diff-2a9a3bc70d631e83d2e68bae34835c95).

**Comment by stevemao** [comment]
> in both Node.js and Node.js and Node.js, Node.js, why is there two "Node.js". Does it means different respectively.

This must be a mistake.

**Comment by Fishrock123** [comment]
> 1. In [locale/en/about](https://github.com/nodejs/nodejs.org/tree/master/locale/en/about/), there is an `advisory-board` folder, but we can't found where it is used on the website. we guess it is a missing link.
> 2. [locale/en/about/organization.md](https://github.com/nodejs/nodejs.org/blob/master/locale/en/about/organization.md) is same with above. 

You'd need to check the website nginx config: https://raw.githubusercontent.com/nodejs/build/master/setup/www/resources/config/nodejs.org

I've copied the relevant bits below:

<details>

``` nginx

    rewrite ^/about/advisory-board(.*)$                           https://$server_name/en/about/organization/ permanent;
    rewrite ^/advisory-board(.*)$                                 https://$server_name/en/about/organization/ permanent;
    rewrite ^/about/organization/tsc-meetings/?$                  https://$server_name/en/foundation/tsc/minutes/ permanent;
    rewrite ^/about/organization/tsc-meetings/(.*?)/minutes.html$ https://$server_name/en/foundation/tsc/minutes/$1/ permanent;
    rewrite ^/about/security/?$                                   https://$server_name/en/security/ permanent;
    rewrite ^/contribute/?$                                       https://$server_name/en/get-involved/ permanent;
    rewrite ^/contribute/accepting_contributions.html$            https://github.com/nodejs/dev-policy permanent;
    rewrite ^/contribute/becoming_collaborator.html$              https://$server_name/en/get-involved/ permanent;
    rewrite ^/contribute/code_contributions/?$                    https://$server_name/en/get-involved/ permanent;
    rewrite ^/contribute/code_contributions/workflow.html$        https://$server_name/en/get-involved/ permanent;
    rewrite ^/documentation(.*)$                                  https://$server_name/en/docs/ permanent;
    rewrite ^/foundation/blog.html$                               https://$server_name/en/blog/ permanent;
    rewrite ^/foundation/members.html$                            https://$server_name/en/foundation/members/ permanent;
    rewrite ^/images/foundation-visual-guidelines.pdf$            https://$server_name/static/documents/foundation-visual-guidelines.pdf permanent;
    rewrite ^/images/logos/js-black(.*)$                          https://$server_name/static/images/logos/js-black$1 permanent;
    rewrite ^/images/logos/nodejs-(.*)$                           https://$server_name/static/images/logos/nodejs-$1 permanent;
    rewrite ^/images/node-foundation-by-laws.pdf$                 https://$server_name/static/documents/node-foundation-by-laws.pdf permanent;
    rewrite ^/images/.*trademark-policy.pdf$                      https://$server_name/static/documents/trademark-policy.pdf permanent;
    rewrite ^/video(.*)$                                          https://$server_name/static/video$1 permanent;
    rewrite ^/changelog.html$                                     https://github.com/nodejs/node/blob/master/CHANGELOG.md permanent;
    rewrite ^/api.html$                                           https://$server_name/api/ permanent;
    rewrite ^/index.html$                                         https://$server_name/ permanent;

    rewrite ^/(20\d\d/\d\d/\d\d/.*)$                              http://blog.nodejs.org/$1 permanent;

    rewrite ^/about/?$                                            https://$server_name/en/about/ permanent;
    rewrite ^/about/advisory-board/?$                             https://$server_name/en/about/organization/ permanent;
    rewrite ^/about/advisory-board/members/?$                     https://$server_name/en/about/organization/ permanent;
    rewrite ^/about/organization/?$                               https://$server_name/en/about/organization/ permanent;
    rewrite ^/about/organization/tsc-meetings/(\d\d\d\d-\d\d-\d\d)/?$ https://$server_name/en/foundation/tsc/minutes/$1/ permanent;
    rewrite ^/about/organization/tsc-meetings/(\d\d\d\d-\d\d-\d\d)/minutes.html$ https://$server_name/en/foundation/tsc/minutes/$1/ permanent;
    rewrite ^/about/releases/?$                                   https://$server_name/en/about/releases/ permanent;
    rewrite ^/about/resources/?$                                  https://$server_name/en/about/resources/ permanent;
    rewrite ^/about/security/?$                                   https://$server_name/en/security/ permanent;
    rewrite ^/about/trademark/?$                                  https://$server_name/en/about/trademark/ permanent;
    rewrite ^/blog/?$                                             https://$server_name/en/blog/ permanent;
    rewrite ^/community/?$                                        https://$server_name/en/get-involved/ permanent;
    rewrite ^/foundation/?$                                       https://$server_name/en/foundation/ permanent;

    rewrite ^/dist/staging/(.*)$                                  https://$server_name/dist/$1 permanent;
```

</details>

**Comment by fhemberger** [comment]
@outsideris @stevemao This was taken originally from the io.js website, but all occurrences of "io.js" were replaced with "Node.js". Thanks, you're the first who found this mistake.

**Comment by outsideris** [comment]
@Fishrock123 Thanks for providing nginx conf.
There are URLs for the documents that I said, but I can't find which links on the website point to it.
- [about/organization](https://github.com/nodejs/nodejs.org/blob/master/locale/en/about/organization.md) is same with [foundation/tsc/index](https://github.com/nodejs/nodejs.org/blob/master/locale/en/foundation/tsc/index.md). I think `about/organization isn't need anymore.
- `advisory-board` is a legacy from io.js. There is no advisory-board no. right? Instead, there is TSC, CTC, WG and foundation.

**Comment by outsideris** [comment]
@fhemberger Thank you for confirming it. I will fix it.

**Comment by Fishrock123** [comment]
@outsideris Hmm, that could be correct.

Yes, the `advisory-board` has been replaced by the actual foundation board.

**Comment by outsideris** [comment]
@Fishrock123  Can I remove `about/organization` and `about/advisory-board`? Or, I should keep them and translate them as Korean because there is a reason for keeping theses file.

**Comment by Fishrock123** [comment]
@outsideris You definitely do not need to translate them in my opinion, see my comment at https://github.com/nodejs/nodejs.org/issues/807#issuecomment-233004811

**Comment by outsideris** [comment]
@Fishrock123 Thank you.
