### ISSUE TITLE
Error 522 on nodejs v5.5.0 download

### ISSUE THREAD

**Issue by rgoupil** [nodejs/nodejs.org#834]
- https://nodejs.org/dist/v5.5.0
- Curl | Chrome 49.0.2623.112
- Debian |  Windows 7 SP1

While https://nodejs.org/dist/ or https://nodejs.org/dist/index.json seems to be working fine, I get an error 522 when ever I try to download any build of Nodejs.
So far I tried without success:
- https://nodejs.org/dist/v5.5.0/node-v5.5.0-linux-x64.tar.gz
- https://nodejs.org/dist/v5.5.0/node-v5.5.0-linux-arm64.tar.gz
- https://nodejs.org/dist/v0.1.104/node-v0.1.104.tar.gz
- https://nodejs.org/dist/node-v0.1.98.tar.gz

![522](https://cloud.githubusercontent.com/assets/5578546/17050306/7194dacc-4ff2-11e6-9f33-21bcfa229168.png)

Thank you for your time.

**Comment by fhemberger** [comment]
Seemed to be a temporary glitch, works fine for me (Germany).

**Comment by rgoupil** [comment]
Oh yes, as you might guess by the 'Paris', I am located in France, thanks for the quick answer anyway.

**Comment by rgoupil** [comment]
Just tried again, I am able to download the archive correctly.

Have a good day.
