### ISSUE TITLE
Allow squash merging

### ISSUE THREAD

**Issue by JungMinu** [nodejs/nodejs.org#839]
Repository administrators now have a few options to choose from when deciding how to handle history.
<img width="757" alt="r" src="https://cloud.githubusercontent.com/assets/5035902/17075841/9bbd0e8e-50db-11e6-8bda-3023764ab704.png">
This is a new option which lets you force commit squashing on all pull requests merged via the merge button.

Allowing squash commits via the merge button would be really convenient

@mikeal @fhemberger whaddya reckon?

**Comment by fhemberger** [comment]
I'd really like to see that for this repo as well.

Unfortunately, I can't enable it myself: Only one of the WG Admins (i.e. @rvagg) is a repo owner (and thus can administrate stuff) along with @Trott @Fishrock123 and @evanlucas.

**Comment by lpinca** [comment]
+1 to disable merge commits and only allow squash merging.

**Comment by phillipj** [comment]
Both options are already enabled.

**Comment by JungMinu** [comment]
@phillipj then, +💯 to only allow squash merging and disable merge commits.

**Comment by phillipj** [comment]
Alright, merge commits just disabled :)

**Comment by evanlucas** [comment]
yay!
