### ISSUE TITLE
remove advisory-board (and others)

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#845]
during translation efforts, we decided that the `advisory-board` documents were not needed anymore and can be removed. do we have any other documents like this that can be removed?

**Comment by ghost** [comment]
FYI `advisory-board` is an artifact from io.js times (?) and is superseded by the foundation's board

**Comment by Fishrock123** [comment]
I think it can be removed, cc @mikeal

**Comment by mikeal** [comment]
Yup, can be removed.

**Comment by lpinca** [comment]
Hmm there are links in some blog posts that point to https://nodejs.org/about/advisory-board/.
If we remove it the links will 404.

**Comment by fhemberger** [comment]
@lpinca Then let's remove the links from the blog posts.
