### ISSUE TITLE
Download page's bottom link is missing.

### ISSUE THREAD

**Issue by wongzigii** [nodejs/nodejs.org#846]
- **URL**: https://nodejs.org/zh-cn/download/
- **Browser version**: Version 51.0.2704.103 (64-bit)
- **Operating system**: Mac OSX 10.11

The bottom link is missing.

**Comment by Knighton910** [comment]
Good job on the pull Req, once merged, come back & close issue https://github.com/nodejs/nodejs.org/pull/847

👍
