### ISSUE TITLE
Use standard in static JS?

### ISSUE THREAD

**Issue by zaynv** [nodejs/nodejs.org#851]
I've noticed that you guys are using `standard` for linting, what do you think about also following the `standard` style for the client side as well for consistency? I understand you couldn't do it for the `modernizr.custom.js` but it could probably be easily done in the `download.js` file.

**Comment by lpinca** [comment]
I'm fine with fixing the style of `download.js` but in the `static/legacy` folder there are other scripts which don't follow the `standard` style. All of them along with `modernizr.custom.js` should be ignored.
