### ISSUE TITLE
Abooooout translations.

### ISSUE THREAD

**Issue by Hojin-Ryu** [nodejs/nodejs.org#853]
Korean translation persentage is too low.
Cuz I can do English very well, that wasn't problem.
But it seems there is a problem a lot.
For example, the reference. Moreover different than written in korean.
I don't have much time on it, so i'll make it short.
Is there any seats for translators in node.js's site?
If not, i'll now work on it.

**Comment by Fishrock123** [comment]
You may want to coordinate with @nodejs/nodejs-ko, but there is not a limit on seats for translators. More are always welcome! :)

You will need one other person from that group to review your work before it goes live, but otherwise feel free to create new pull requests here.

**Comment by outsideris** [comment]
We're now trying to translate the website. (see, https://github.com/nodejs/nodejs.org/pull/843 and https://github.com/nodejs/nodejs-ko/issues/381 )
You can join nodejs-ko to contribute it and you have to discuss it to prevent to translate same contents twice.

**Comment by taggon** [comment]
@Hojin-Ryu Node.js foundation already has @nodejs/nodejs-ko team, which I belong to. We've been translating contents related to Node.js into Korean for 18 months. You can join us if you're interested in. 

@Fishrock123 I think you can close this issue. :)

**Comment by lpinca** [comment]
Closing as per @taggon comment.

**Comment by Hojin-Ryu** [comment]
damn.
Thx a lot for a comment guys.

2016-08-09 19:11 GMT+09:00 Luigi Pinca notifications@github.com:
