### ISSUE TITLE
Node 6.5 checksum says incorrect SHA512

### ISSUE THREAD

**Issue by manikantag** [nodejs/nodejs.org#868]
- **URL**: https://nodejs.org/dist/v6.4.0/SHASUMS256.txt.asc
- **Browser version**: Doesn't matter (but using Chrome 52)
- **Operating system**: Doesn't matter (but using Windows 8.1)

Node.js 6.4 binaries hash algorithm is mentioned as SHA512, but they are really SHA256 hashes. 

_I've downloaded twice because I saw hash mismatch, before I realised the mentioned algo wrong_

**Comment by lpinca** [comment]
cc: @nodejs/release

**Comment by Fishrock123** [comment]
@cjihrig I think you did 6.4.0?

**Comment by cjihrig** [comment]
I did. I just followed the release instructions, using the same key I've used before.

**Comment by stevemao** [comment]
Is this still an issue?

**Comment by lpinca** [comment]
@stevemao I think so.

**Comment by phillipj** [comment]
Linking with #976 which removes the line mentioning both 512 and 256 shasums

**Comment by fhemberger** [comment]
@nodejs/build Would it make sense to update `SHASUMS256.txt.asc` for past releases as well? (Just replacing "SHA512" with "SHA256" in the header.)

**Comment by jbergstroem** [comment]
Not super keen on touching old stuff; but I can do the work if others insist.

**Comment by fhemberger** [comment]
Okay, closing this issue. Let's keep old releases as they were.
If the problem should come up again, we can link to this issue.
