### ISSUE TITLE
Wrong interactive US end date?

### ISSUE THREAD

**Issue by phillipj** [nodejs/nodejs.org#870]
@mikeal what's the correct end date for interactive US? You changed it in https://github.com/nodejs/nodejs.org/commit/b185dfe917dbcfa80d32acabe727fef439ba9fd2 but the alt-text and text in the image isn't the same...

Refs https://twitter.com/wa7son/status/766633689220546560

**Comment by lpinca** [comment]
I think the correct end date is Dec 2, see http://events.linuxfoundation.org/events/node-interactive.

**Comment by lpinca** [comment]
I would happily update the image but I have no idea what the font is and the layers are flattened 😢 .

**Comment by phillipj** [comment]
@mikeal ping ^

**Comment by phillipj** [comment]
@gtewallace you able to help on this?

**Comment by williamkapke** [comment]
@phillipj I just spoke with Cassandra (with Linux Foundation) here at Interactive EU. She said the artwork has been done - and it is waiting on @mikeal (giving him the stink eye 😜). She is sending it to me & I'll update it 👍
