### ISSUE TITLE
SHA1 Listed in SHA256 sum List may cause confusion

### ISSUE THREAD

**Issue by yingding** [nodejs/nodejs.org#871]
- **https://nodejs.org/dist/v4.5.0/SHASUMS256.txt.asc**:
- **Chrome**:
- **Ubuntu 16.04**:

In the header of SHASUMS256.txt is HASH: SHA1 listed. But the checksum for all release package are calculated by sha256sum, which is confusing at the first moment. Thought the release node packages are all corrupted.

Can you update the correct header text in the hashsum file, so that it is clear which hash is used.

**Comment by Fishrock123** [comment]
@nodejs/build Has to do with https://github.com/nodejs/node/blob/master/tools/release.sh#L67-L126

Should we just be signing the shasums file with 256 too?

**Comment by Fishrock123** [comment]
also @nodejs/release

**Comment by roneesh** [comment]
Second on this causing confusion, I spent around 1 hour trying to figure out if I was running the shasum command wrong or if I had deeper issues. Glad I finally found this issue to figure out what's up. A fix indicating to use sha256 would be appreciated.

**Comment by fhemberger** [comment]
This has been fixed a while for current releases, but for the moment, we decided against modifying older releases as well.
