### ISSUE TITLE
Content issues with Node Interactive NA 2016 announcement

### ISSUE THREAD

**Issue by mscdex** [nodejs/nodejs.org#891]
- **URL**: https://nodejs.org/en/blog/announcements/interactive-2016-north-america-schedule/
- **Browser version**: n/a
- **Operating system**: n/a

There's at least a couple of things I noticed that were incorrect for this article:
- The date at the very top is wrong, it says 9/27 but the date at the beginning of the article text is 9/12.
- There seems to be a missing link towards the bottom with `Visit here to register`. I'm assuming 'here' should be actually be a link to somewhere?

**Comment by ghost** [comment]
#893 fixes the link
