### ISSUE TITLE
v6.5.0 windows install issue

### ISSUE THREAD

**Issue by crh225** [nodejs/nodejs.org#895]
- **URL**:
  https://nodejs.org/dist/v6.5.0/node-v6.5.0-x64.msi
- **Browser version**:
  ![image](https://cloud.githubusercontent.com/assets/19475195/18566634/39820c34-7b5a-11e6-9e0f-2f225b3b86e5.png)
- **Operating system**:
  ![image](https://cloud.githubusercontent.com/assets/19475195/18566639/415f34fe-7b5a-11e6-8760-19d2bac4ff7f.png)

![image](https://cloud.githubusercontent.com/assets/19475195/18566608/20cc803e-7b5a-11e6-9fd7-f56821e48976.png)

**Comment by crh225** [comment]
it happens for other versions as well

**Comment by crh225** [comment]
for what its worth my team members get the same error also.

**Comment by joaocgreis** [comment]
@crh225 I can download and install that exact file without any issues. Can you check the SHA256 sum to make sure the download is not corrupt? You can use `CertUtil`:

```
C:\Users\Administrator\Downloads>CertUtil -hashfile node-v6.5.0-x64.msi SHA256
SHA256 hash of file node-v6.5.0-x64.msi:
2a 26 9b 0b 9f ee 2c 50 2d 4a 81 16 8f 12 31 5e 9d 55 39 66 41 52 22 49 93 1f 0f
 88 e0 26 38 c4
CertUtil: -hashfile command completed successfully.
```

Your result must match mine as above exactly, which is the same as listed in https://nodejs.org/dist/v6.5.0/SHASUMS256.txt .

**Comment by crh225** [comment]
@joaocgreis for two days in a row it wasn't working, but magically I it works now. Cheers all.
![image](https://cloud.githubusercontent.com/assets/19475195/18586803/32a5d500-7be4-11e6-9654-ecdaf3c27cc0.png)

**Comment by crh225** [comment]
@joaocgreis just for fun I did certutil: 
![image](https://cloud.githubusercontent.com/assets/19475195/18587066/aa51aa74-7be5-11e6-917e-6225e69e0812.png)
