### ISSUE TITLE
Linux Binaries should say Linux (x86) Binaries and ARM binaries should say Linux (ARM) Binaries?

### ISSUE THREAD

**Issue by stevemao** [nodejs/nodejs.org#899]
https://github.com/nodejs/help/issues/278#issuecomment-247746229
This confuses me for a while and I'm a noob of systems so I was afraid to ask. But I thought ARM should be architectures for computer processors, and it's under "Additional Platforms", where as Linux is an OS. The page makes "ARM" look like an OS/Platform. Is there any reason to make it this way?

**Comment by fhemberger** [comment]
Good point. +1
