### ISSUE TITLE
Discoverability: guides

### ISSUE THREAD

**Issue by a0viedo** [nodejs/nodejs.org#901]
We were talking with some contributors about a few guides at https://github.com/nodejs/node/tree/master/doc/topics and https://github.com/nodejs/node/tree/master/doc/guides and we wondered why those are not listed in the website, at least not under https://nodejs.org/en/docs/guides/.

**Comment by Fishrock123** [comment]
@a0viedo build issues, see the likes of https://github.com/nodejs/node/pull/6522

**Comment by joshgav** [comment]
It seems these are currently in this repo at https://github.com/nodejs/nodejs.org/tree/master/locale/en/docs/guides. It would be ideal if the site instead pulled from the [topics](https://github.com/nodejs/node/tree/master/doc/topics) and [guides](https://github.com/nodejs/node/tree/master/doc/guides) section in nodejs/node.

I also have a new debugging guide I'm working on which it looks like I'll need to add here (https://github.com/nodejs/node/pull/8978).

**Comment by joyeecheung** [comment]
This has been fixed by https://github.com/nodejs/nodejs.org/pull/1105?

**Comment by joshgav** [comment]
@joyeecheung 

> This has been fixed by #1105?

Indeed!
