### ISSUE TITLE
Learn/Education initiatives subsection on nodejs.org

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/nodejs.org#908]
- **URL**: https://nodejs.org/en/foundation/

As the education initiatives move forward(such as Certification development or Outreachy participation), it would be helpful to have these efforts surfaced on nodejs.org. 

In the short term, as part of the Node.js community's participation in the [Outreachy effort](), I will need to have a page or subsection to share the information about the Node.js project's specific information for applicants up. I was thinking this could go under the [Foundation](https://nodejs.org/en/foundation/) section of the site and create a new tab which would be either 'Outreachy' or 'Education'(I think 'Education' makes more sense and 'Outreachy' would simply be a section on that page since it is a time-boxed effort).

In the long term, I'd love to see 'Learn' as a top-level navigation where we have Getting Started resources among whatever else we can dream up and see fit to put there(or link to). I think that it might also make sense to keep what I've mentioned above(the Education initiatives tab under Foundation) because I really, really want to find as many ways as possible to communicate/be transparent about what is happening here.

Would love thoughts on this!

**Comment by Fishrock123** [comment]
Maybe it would be better under "get involved"

or maybe we should switch "get involved" to "learn"?

**Comment by hackygolucky** [comment]
@Fishrock123  Ah! This _is_ a tough one. There are a number of ways to learn under Get Involved, but when I think of that naming, it ultimately implies you're considering participating or giving back, not necessarily learning as a top-level. I'd say ultimately that getting involved and learning are two separate, important activities that absolutely can converge. Is it that you think we should take an opinion that eventually as people become more comfortable with the platform that they -should- contribute?(no judgement there honest question and an interesting one at that). 

I LOVE the call to action that is 'Get Involved'. I don't think I want that to go away. It's a better label than just 'Community' to me. It empowers folks. I think I'd like a separate 'Learn' that contains a Getting Started section, but that ensures we're able to cover multiple users because not everyone is getting started--yay to Node.js being 🎉 7 🎉  !

I've turned this into a weird bikeshedding. I tried to look at what other communities that I respect have set precedence with in regards to this, but I'm not very satisfied with what I saw :)

**Comment by Fishrock123** [comment]
In that case, could we roll "Foundation" into "About"? I suspect the main objection to this would be that the top nav is getting to crowded... which I think is partially true.

cc @nodejs/website thoughts appreciated, but I'd really like to have a "Lear" sort of section way more front and center.

**Comment by evanlucas** [comment]
+1 to having Learn top level item and rolling Foundation into About from me.

**Comment by williamkapke** [comment]
Yup- I've always felt a bit off about the fact that Working Groups are under About and Board/TSC stuff was under foundation. Plus, Announcements & In The News seem out-of-place under Foundation.

+1 to combining them somehow.

**Comment by hackygolucky** [comment]
Sounds good to me!

**Comment by hackygolucky** [comment]
I'll PR the nav changes suggested here and add a separate PR for the Outreachy page.

**Comment by Fishrock123** [comment]
@hackygolucky sounds good! You'll probably need to modify `site.json` quite a bit as a start: https://github.com/nodejs/nodejs.org/blob/master/locale/en/site.json#L105-L132

**Comment by fhemberger** [comment]
Closing this as #929 was merged …
