### ISSUE TITLE
Links for downloads to pLinux, zLinux and AIX missing 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/nodejs.org#91]
The previous download page when hosted on the old side included links to where you could download versions for these platforms.  This section was added under this PR https://github.com/nodejs/nodejs.org/pull/101#issuecomment-87781755

and it looked like this

![bildschirmfoto 2015-03-28 um 14 31 00](https://cloud.githubusercontent.com/assets/298166/6881246/527fe6ac-d557-11e4-9b78-7020c3c9c8d8.png)

**Comment by mhdawson** [comment]
@jasnell FYI

**Comment by fhemberger** [comment]
Thanks, added the section again.
