### ISSUE TITLE
Abort trap 6. when dns servers are invalid

### ISSUE THREAD

**Issue by liesislukas** [nodejs/nodejs.org#918]
OS X El Capitan (10.11.6 (15G1004))
node -v: v5.0.0

https://nodejs.org/api/dns.html#dns_dns_setservers_servers

```
let servers = [ '8.8.4.4', '156.154.71.1' ];
dns.setServers(servers);
dns.resolve(...);
```

and i get 

> Assertion failed: (ares__is_list_empty(&server->queries_to_server)), function ares__destroy_servers_state, file ../deps/cares/src/ares_destroy.c, line 102. 
> Abort trap: 6

seems like i get it if i call dns.resolve 2nd time while 1st call haven't fired callback yet. 

promises would be great too. Like MongoDb nodejs lib is made. If you pass in callback - it will be fired, if not - then promise is returned.

**Comment by fhemberger** [comment]
Hi, this is the repository for the Node.js **website**. For your case, please open an issue over here: https://github.com/nodejs/node/issues

There is also a discussion going on already about the support of Promises for Node.js core: https://github.com/nodejs/node/pull/5020.
