### ISSUE TITLE
Committer Onboarding Time

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#939]
Let's identify all the new contributors and add them as committers!!!

**Comment by fhemberger** [comment]
I have the script to do that, I'll run it next week when I'm back from vacation.

**Comment by fhemberger** [comment]
Script used is [contribution-report](https://github.com/bengl/contribution-report/) (recent version is not on npm):
`./index.js -r nodejs/nodejs.org -s 2016-03-24 -C -U <githib user> -P <github token>`

```
513 commits in `nodejs/nodejs.org` since 2016-03-24:
* @outsideris 9 commits
* @hackygolucky 6 commits
* @sotayamashita 4 commits
* @yorkie 3 commits
* @gonenduk 2 commits
* @yasinaydin 2 commits
* @mweagle 2 commits
* @SamuelBolduc 2 commits
* @cjihrig 2 commits
* @zdroid 2 commits
* @denysdovhan 2 commits
* @wongzigii 2 commits
* @trentontri 2 commits
* @ghaiklor 2 commits
* @edsadr 2 commits
* @tgfjt 2 commits
* @ykzts 2 commits
* @indutny 2 commits
* @undownding 2 commits
* @glennschler 2 commits
* @watilde 2 commits
* @cdnadmin 2 commits
* @pin3da 2 commits
* @qbit 2 commits
* @jrit 2 commits
* @yodeyer 1 commits
* @sinaomrani 1 commits
* @bcmarinacci 1 commits
* @tianp 1 commits
* @PeterDaveHello 1 commits
* @tungtouch 1 commits
* @yoshuawuyts 1 commits
* @ryanmurakami 1 commits
* @jjlangholtz 1 commits
* @vsemozhetbyt 1 commits
* @raphaelokon 1 commits
```

**Comment by mikeal** [comment]
+1 to everybody :)

**Comment by ghost** [comment]
same! welcome, new committers!

**Comment by fhemberger** [comment]
They stil have to be added to the group/repo, I don't have the rights for this. @mikeal can you help, please?

**Comment by MylesBorins** [comment]
I have permissions. Adding people now

also +1 to all the peeps

**Comment by MylesBorins** [comment]
and done 🎉

Closing the issue. Please reopen if there is more discussion to be done

**Comment by outsideris** [comment]
Thank you for adding me as commiters.

**Comment by wongzigii** [comment]
Thanks!

**Comment by outsideris** [comment]
I have some questions. Are these new committers website WG collaborators? (If so, we should update them in README.)
And I now have permission for repositories related with the webiste. However, I have no idea when I could merge PR. Is there a guideline for new committers or an IRC channel?

**Comment by ghost** [comment]
@outsideris yes, we should update the readme. if you want to open a pull request for that, feel free to!

as for your second question, we have a [collaborator guide](https://github.com/nodejs/nodejs.org/blob/master/COLLABORATOR_GUIDE.md) specifically for that

**Comment by zlatanvasovic** [comment]
@fene Maybe opening a Gitter or an IRC chat would be helpful for the cause of discussing the changes? E.g. before you send a PR, you can talk with other collaborators about it.

**Comment by ghost** [comment]
@zdroid we usually open a PR and then discuss it over github itself! i don't know if there's an irc or gitter channel for the website specifically, you might wanna ask @fhemberger or @phillipj

**Comment by zlatanvasovic** [comment]
I know right @fene. Just saying real-time communication methods are better for collaboration.

**Comment by outsideris** [comment]
Thank you @fene . I missed the collaborator guide.

**Comment by phillipj** [comment]
> I know right @fene. Just saying real-time communication methods are better for collaboration.

So far, we've done really good with async communication, primarly using GitHub PRs and issues. Around here, _everything_ can be created as an issue, from trivial to big questions and thoughts, plus bugs of course. E.g. questions related to the collaborator role would be a very good fit.

Keeping to async communication is also about respecting others precious spare time. Not everyone can reply within minutes or hours. An often used trick if a PR/issue stalls for many days, is to ping everyone in the Website Work Group by saying something like:

ping @nodejs/website

That said, several of us hangs on IRC freenode / #node-dev if you feel the need to ask someone directly.

**Comment by fhemberger** [comment]
Also: Timezones. The website team is spread across the globe, so async communication wins. It's also better for looking up issues/decisions afterwards than to skim through an endless list of irc/gitter/slack/whatever logs.
