### ISSUE TITLE
How does this project automatically install a pre-commit hook?

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#942]
I'm seeing a sym link in my .git/hooks directory that was installed _at some point_.

The `pre-commit` package is a dev dep but we aren't configuring it in any way and we don't ever call it.

**Comment by jasnell** [comment]
`pre-commit` appears to check for the existence of a test config script here: https://github.com/observing/pre-commit/blob/master/index.js#L99-L107

**Comment by phillipj** [comment]
I'd suspect its [npm install override](https://github.com/observing/pre-commit/blob/master/package.json#L10) which executes the [install.js script](https://github.com/observing/pre-commit/blob/master/install.js).

**Comment by PatrickHeneise** [comment]
I can recommend [ghooks](https://www.npmjs.com/package/ghooks), which might be more explicit in package.json.

**Comment by lpinca** [comment]
Configuration via package.json is also available for per-commit but yes I think the symlink is still silently created.

**Comment by phillipj** [comment]
Closing this for now, shout if you're not pleased with our answers so far

**Comment by mikeal** [comment]
Thanks, I should have closed this myself, I'm happy with the answer :)
