### ISSUE TITLE
A little confuse for "Current version" and "Current"

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs.org#944]
<img width="487" alt="2016-10-08 20 18 25" src="https://cloud.githubusercontent.com/assets/390146/19212811/c3c4de02-8d94-11e6-86b0-d66d0bb9ea68.png">

We call Node.js's latest version as "Current". So, I think there is a little confuse in [the download page](https://nodejs.org/en/download/) to beginners because there are two "current".

How do you think?

**Comment by rauschma** [comment]
If you really want to promote LTS as “safe” and Current as “latest” then a separate link underneath would probably work better than a toggle than doesn’t look like a toggle (among other issues: its bottom half could be mistaken for a description of the top half).

**Comment by rauschma** [comment]
Other UI options to express alternatives: tabs and radio buttons

**Comment by mxstbr** [comment]
Yeah I can confirm, I did not get that's a toggle until @rauschma pointed it out.

**Comment by rauschma** [comment]
As @outsideris  mentioned, the other confusing element is “Current version: v4.6.0”. Here, it may be better to write, e.g., “Version to download: …”.

**Comment by mairead** [comment]
If I were to take a look at this who is the best person to contact re: browser support/testing list? Thanks, m

**Comment by MylesBorins** [comment]
I've submitted a fix for this specific issue, thank you @outsideris for submitting the bug.

For other UI / UX related problems please open a separate issue to focus specifically on them.

**Comment by outsideris** [comment]
@TheAlphaNerd Awesome!

**Comment by mairead** [comment]
oh :/

**Comment by MylesBorins** [comment]
@mairead I may have misunderstand your original comment. If you were volunteering to help I apologize for stepping in.

If you would like some help finding ways to collaborate on this project or on node.js core please feel free to reach out, you can find my contact info on my website https://thealphanerd.io
