### ISSUE TITLE
Download toggle for current/latest has confusing UI

### ISSUE THREAD

**Issue by mairead** [nodejs/nodejs.org#947]
- **https://nodejs.org/en/download/**:
- **Chrome 52.0.2743.116 (64-bit)**:
- **Mac OS X 10.10.5**:

Download toggle for current/latest has confusing UI. 

New UI for downloading Node.js confusing:
– It calls v4.6.0 the current version
– The toggle doesn’t look like one
XOR could be expressed via tabs, radio buttons, etc.

<img width="487" alt="download" src="https://cloud.githubusercontent.com/assets/604477/19234184/e09e18ce-8ee1-11e6-873a-85d94b2eb547.png">

I have prepared a prototype layout using tabs for both large and smaller views. Not super happy with tabs on smaller screens because I think horizontal layouts are problematic, especially when i18n is concerned. Wouldn't recommend radio buttons though as forms add extra complexity/accessibility issues. 

See screenshots below for large and small screen

<img width="1024" alt="screen shot 2016-10-10 at 12 07 44" src="https://cloud.githubusercontent.com/assets/604477/19234243/3b73c438-8ee2-11e6-8ed9-0b63e6248538.png">

<img width="524" alt="screen shot 2016-10-10 at 12 07 53" src="https://cloud.githubusercontent.com/assets/604477/19234244/4044269c-8ee2-11e6-986d-047ee6c7dab5.png">

**Comment by ghost** [comment]
the first issue has just been fixed, see #945

**Comment by Fishrock123** [comment]
What about adding a checkmark to the one which is selected?

**Comment by mairead** [comment]
Could you do a quick sketch to give me an indication of what you mean by checkmark?

**Comment by mhdawson** [comment]
I'm also interested in how this is going to look for secondary platforms with respect to:

https://github.com/nodejs/nodejs.org/pull/940

**Comment by MylesBorins** [comment]
closing in favor of #953

**Comment by MylesBorins** [comment]
reopening... I mixed this up with #945 

This discussion is good to have separately. Sorry about confusion

**Comment by Fishrock123** [comment]
@mairead I mean putting the checkmark character into the corner of the one that is selected... maybe that's not clear either though.

**Comment by mairead** [comment]
@Fishrock123 - Ideally what I'd like is a visual example of what you consider a checkmark, if thats possible, ta.

**Comment by mairead** [comment]
So I got lost in the numerous conversations about releases you want to display. As far as I can tell from #940 you still want to show latest and current. The conversation on #982 seems to cover a change to the Homepage. Do you still want changes which echo that for the download page? I can see that you've been working on it in #990 but that doesn't resolve the UX issues stated above.

**Comment by phillipj** [comment]
> Do you still want changes which echo that for the download page?

The main take aways from #982 / #990 is considering that **current** might not exist in a small transition period. That's what we experienced a week or two ago, when v5 (the previous **current**) was end of life and v6 took over as the latest LTS version.

ATM that won't be an issue for a long time, so I'd say you don't have to think about that when working on your proposed changes. We could handle that part in a separate issue / PR.

**Comment by fhemberger** [comment]
I'm closing this issue after the style update in #1233. @mairead please feel free to open a new issue if you have further ideas how to improve the UX.
