### ISSUE TITLE
Evangelism: Weekly Update for October ~

### ISSUE THREAD

**Issue by JungMinu** [nodejs/nodejs.org#950]
Let's write down for next week :gift:

**Comment by hfeeri** [comment]
Hello Folks,

We created an article discussing Node.js Enterprise use-cases:
https://blog.risingstack.com/node-js-examples-what-companies-use-node-for/

I hope you'll enjoy it.

Cheers,
Ferenc

**Comment by hfeeri** [comment]
Hello Again,

A new article has been published on our community website:

"This article teaches you how to build a distributed application with ZeroMQ and Node.js by developing an exciting sample project: a brute-force cracker for JWT tokens."

https://community.risingstack.com/zeromq-node-js-cracking-jwt-tokens-1/

Cheers,
Ferenc

**Comment by hfeeri** [comment]
Hi, me again. :)

We wrote a short piece on async/await in the Node 7 nightly.

https://blog.risingstack.com/async-await-node-js-7-nightly/

**Comment by raphaelokon** [comment]
@hfeeri I think there is a typo in the blog post …

```
function async getTrace () { 
```

AFAIK `async` needs to be in front of the function keyword … https://tc39.github.io/ecmascript-asyncawait/

**Comment by hfeeri** [comment]
@raphaelokon Thanks for noticing, you're absolutely right. Corrected the typo!

**Comment by hfeeri** [comment]
New article: https://blog.risingstack.com/node-js-at-scale-module-system-commonjs-require/

"Learn how the Node.js module system & CommonJS works and what does require do under the hood."

**Comment by hfeeri** [comment]
Hello!

We published a new article on how to do graceful shutdown with Node.js and Kubernetes.

https://blog.risingstack.com/graceful-shutdown-node-js-kubernetes/

Cheers,

**Comment by JungMinu** [comment]
PR: https://github.com/nodejs/nodejs.org/pull/999
