### ISSUE TITLE
Download Page Layout to support v4.x LTS, v6.x LTS, and v7.x Current

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/nodejs.org#953]
Currently our downloads is designed for a single LTS release and a single Current release.

On October 18th we will have 2 LTS releases.

On October 25th we will have 2 LTS releases and 1 current release.

As far as I can tell we don't have any visual designs or implementations for this. We can likely put together a quick solution for the 18th, but we definitely need to re-envision our download section by the 25th. I would like to suggest that we should use this issue to replace #947 and work together to get something good together for these upcoming deadlines.

**Comment by mairead** [comment]
Here is the proposed tab layout I suggested for issue #947 I think you could get away with several items on the larger view but tabs are a real problem on small screens. You'd need to move to a better UI if you wanted to handle multiple/scaling items

<img width="1024" alt="screen shot 2016-10-10 at 12 07 44" src="https://cloud.githubusercontent.com/assets/604477/19263968/c6063356-8f96-11e6-9d97-fedc64fc1ac9.png">
<img width="524" alt="screen shot 2016-10-10 at 12 07 53" src="https://cloud.githubusercontent.com/assets/604477/19263967/c6061114-8f96-11e6-9d47-48541014b35c.png">

**Comment by lpinca** [comment]
@TheAlphaNerd I remember that something about this was already discussed in another issue (I'm trying to find it now).
If I remember correctly the intention was to only display the latest LTS  and the current version on the frontpage, probably also on the download page.

**Comment by lpinca** [comment]
Here it is https://github.com/nodejs/nodejs.org/issues/779#issuecomment-224390581, https://github.com/nodejs/nodejs.org-new/issues/1, I think it was this one.

**Comment by MylesBorins** [comment]
doesn't look like there was any explicit decision there. I personally don't
think it makes sense to remove v4 from the download page until v6 is as
stable.

**Comment by MylesBorins** [comment]
@mairead I like that design. Would we be able to include the version numbers in the tabs?

Also how would the mobile mock up work for 3 releases?

**Comment by rvagg** [comment]
I think my (soft) vote would be for promoting v6 downloads as soon as it goes LTS. We've stabilised a lot during Current and have been building up to this point. It would be nice to be able to easily switch between the two with a really obvious visual cue. I have zero idea how that would work tho.

**Comment by ghost** [comment]
perhaps some sort of banner advertising v6? doesn't even have to be on the downloads page, it could be on the main page or other pages. other than that, i think the mockup @mairead made would work pretty well, even for promoting v6

**Comment by mhdawson** [comment]
Would it even make sense to keep in line with what we do now and just show v6 as the LTS releease with 4.x relegated to the older release sections like 0.10.X and 0.12.X are now ?

**Comment by mhdawson** [comment]
I see the earlier discussion above, I think we should believe that v6 is stable enough.

**Comment by MylesBorins** [comment]
Personally, I think we should be promoting both as long as v4.x is still in active LTS. That being said, I am open to the idea of only showing one LTS if others believe strongly in it

**Comment by gibfahn** [comment]
(In my opinion)

If you know you specifically want v4 you can always find it in the downloads section, the front page is a convenience for people who aren't up to date with node's LTS cycles, and just want to get the latest LTS release. 

Once v6 goes LTS we want people arriving on the download page to get v6 by default. If we say we have varying degrees of stability amongst LTS releases then we have to say "keep using v4 until v6 goes _really_ stable", in which case is it even really LTS? Making it LTS is the point at which you say "this is as stable as v4 or anything else", at which point I don't see the purpose behind promoting v4.

**Comment by MylesBorins** [comment]
I've been thinking about it and I think I can get behind dropping v4 from the download page when v7 moves to current. We can make two forks from the current website to handle this rewrite which won't be terribly complicated, and we can deal with the redesign separately.

We can revisit this If people have an issue with v4 dropping from the download page.

**Comment by phillipj** [comment]
I create a separate issue to discuss UX for the frontpage and LTS/current: #982
