### ISSUE TITLE
Need System Requirements information on the website and at the surface

### ISSUE THREAD

**Issue by fselcukcan** [nodejs/nodejs.org#955]
This is not a visual issue. I want Nodejs.org to be more simple and the crucial information on the surface. For this, I need the system requirements data is directly available and at the surface for each release, from the Nodejs.org.

**Comment by phillipj** [comment]
Is this the data you're looking for? https://nodejs.org/download/release/index.json

**Comment by phillipj** [comment]
@isikfsc ping, did the URL I posted satisfy your needs?

**Comment by oresmus** [comment]
@phillipj  I can't speak for @isikfsc , but I was about to report what I assume is the same website bug. If it is the same bug, that URL does not satisfy my desires. 

What I think you need (but could not find anywhere), on both the home page (next to the big download button) and on the more detailed download page at https://nodejs.org/en/download/ , is a clear human-readable statement of "system requirements" (or a link to them) for each operating system you support. 

For example, for Mac OS X, you would state something like "requires Mac OS X version xxx or later". (For each Mac OS version, it either works or it doesn't; and your build system probably has to encode the desired earliest OS version to support; and your testing also has to test it on specific OS versions; so you should be able to say what this earliest supported version is.)

(Of course this info potentially differs for each build and each OS.)

(If there is any other variable you know about which would cause node to fail to run on certain machines (like required RAM or disk space), you'd ideally say that too. But that's less important.)

**Comment by zlatanvasovic** [comment]
@oresmus nodejs doesn't take much disk space nor RAM (unless you're running a big-scale website), so  think that information is not needed.

**Comment by oresmus** [comment]
@zdroid that's reasonable. Probably all that's needed is the earliest supported version of the OS (at least for Mac -- I can't speak to what analogous info is needed for other OSes).

**Comment by oresmus** [comment]
(I can report by experiment that a "hello world" node server (node v4.6.1) seems to work on Mac OS X 10.10.5.)

**Comment by fselcukcan** [comment]
@phillipj No, [it is not](https://nodejs.org/download/release/index.json) the data I was looking for, of course as far as I can parse(!) it. No offense but, that was clear from the question. The data in the linked page does not have system requirements, but only have systems required.

To be more and more clear; I mean _at the surface_, not buried deep down and I mean _human friendly and human readable_, not javascript readable.

@zdroid @oresmus I know, on my mac it does take 9.5MBs, but anyway it can be there with extreme ease and that data was the data I was asking for. I think it would be nice to have.

**Comment by mpathy** [comment]
Same over here, I search for an eternity for system requirements for Node.

I know of course, that it works on my current machine, but I need more information for something that gets distributed to many many machines, not just on my PC or a server. 

These can be quite old machines, with old OS X, old Linux and so on.

It would be fatal to begin developing and find out we have a big problem with older machines later.

So it would be great to state the minimum requirements for each platform.

Every other big project does this, too.

But @oresmus - thanks for the information, that helps narrow it down. Win I know, Linux distributions, well.. A lot of installations necessary

**Comment by mpathy** [comment]
I now found out, that the BUILDING.md of the source code gives some hints about the compability..

Maybe the text just can get extracted from there for every readme

**Comment by gibfahn** [comment]
The source of truth for platform support is indeed in BUILDING.md:

https://github.com/nodejs/node/blob/master/BUILDING.md#supported-platforms-1

I agree that it should definitely be hosted on the website. As it's version specific, and changes to it are a breaking change, I think it should ideally be defined within the API docs (which are stored [here](https://github.com/nodejs/node/tree/master/doc/api) and uploaded to nodejs.org on release). Then we could link to them from the main download page.

**Comment by fhemberger** [comment]
@gibfahn I think it's not about I think it would be okay to list the systems requirements for **running** Node.js on tier 1 platforms (guessing it aligns with the requirements for building):

GNU/Linux: kernel >= 2.6.32
macOS: >= 10.10
Windows: >= Windows 7 / 2008 R2

Do we have additional information like minimal memory requirements, etc?
I'd also limit this to LTS/Current releases (as I'm not going through all previous releases to find out, which Node.js version was the last to run on Windows XP. :smile:)

**Comment by ovflowd** [comment]
So far, we don't have metadata regarding system requirements easy to be fetched through our website. I'm closing this issue for now, as any new feature is frozen here as we get things ready for the nodejs.dev replacement.
