### ISSUE TITLE
feature request - callbacks in exit handlers - to block even if async code is used

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/nodejs.org#957]
I'm on the latest version of Node (6.7)

I have been using Node for awhile and one thing that seems to be a missing feature is shutdown hooks that are blocking, even if they feature async code.

for example what we have this:

```
process.on('beforeExit', function () {

});

process.on('exit', function (code, signal) {

});
```

what I am looking for is:

```
process.on('beforeExit', function (cb) {
         setTimeout(cb, 3000);
});

process.on('exit', function (err, code, signal) {
        // if 'beforeExit' handler is in place, then this will only be called when the callback fires
        // in the beforeExit handler
});

```

does this functionality exist? The temporary solution is to simply put blocking code in these handlers, but that's not always idea. Hope this makes sense :) I believe it's possible to do this just wondering if it is a sensible request.

The use case is I have programs which need to run shutdown hooks even if there is a fatal exception in the code, these shutdown hooks have asynchronous code by nature (process.send, for one). So it's a feature that I really need.

**Comment by lpinca** [comment]
@ORESoftware you are posting this in the wrong issue tracker.
You should post this here https://github.com/nodejs/node/issues.

**Comment by ORESoftware** [comment]
ok I can do that thx
