### ISSUE TITLE
Anatomy of an HTTP Transaction - Should the example for '/echo' use the POST or PUT verb?

### ISSUE THREAD

**Issue by coderaj** [nodejs/nodejs.org#962]
- **URL**: https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction/
- **Browser version**: Chrome 53
- **Operating system**: Win 10

I'm a beginner, learning NodeJS and web programming. When I tried to understand the program for an echo server, I have a question on whether it is possible to add a payload from website when it is expecting a GET verb for an echo server. Shouldn't that be POST?

Kindly ignore and close this issue if I was wrong. Please help me understand.

**Comment by zlatanvasovic** [comment]
If I have understood you correctly, you have an issue with node.js itself and not the site. Please report it in [node repository](https://github.com/nodejs/node/issues) instead. You'll get more helpful reply there. :smile:

**Comment by saadq** [comment]
This issue section is meant for people to open issues regarding the nodejs.org website. For any general help questions about node, you'll want to head over to [nodejs/help](https://github.com/nodejs/help) :)
