### ISSUE TITLE
Redirect www.nodejs.org ?

### ISSUE THREAD

**Issue by targos** [nodejs/nodejs.org#968]
Opening this because today I made the mistake to type `www.nodejs.org` in my browser and got a non-friendly `ERR_NAME_NOT_RESOLVED` page. Is there a reason not to redirect this domain to `nodejs.org` ?

**Comment by ghost** [comment]
cc @nodejs/build

**Comment by jbergstroem** [comment]
I've contacted cloudflare support.

**Comment by jbergstroem** [comment]
Was fixed two hours after reporting.

**Comment by zlatanvasovic** [comment]
Thanks @jbergstroem. @targos Please write a comment here if the issue appears in future.
