### ISSUE TITLE
Don't link to Node.js 6.8.1 on the home page

### ISSUE THREAD

**Issue by mgol** [nodejs/nodejs.org#981]
- **URL**: https://nodejs.org/en/
- **Browser version**:  Chrome 54.0.2840.59
- **Operating system**: macOS Sierra 10.12 (16A323)

Currently the main page of https://nodejs.org advertises Node.js 6.9.0 as "LTS, Recommended For Most Users" and 6.8.1 as "Current, Latest Features". This is weird as 6.9.0 is newer than 6.8.1. Node 6.8.1 shouldn't be linked from the home page at all, both links should point to the same version until Node.js 7.0.0 is released.

**Comment by mikeal** [comment]
<img width="682" alt="screen shot 2016-10-18 at 11 27 33 am" src="https://cloud.githubusercontent.com/assets/579/19490929/f75b8b06-9525-11e6-9fa0-14e621c0c717.png">

**Comment by MylesBorins** [comment]
this has been fixed and is in production

**Comment by mikeal** [comment]
@TheAlphaNerd is this what we want now, linking to two LTS releases?

<img width="598" alt="screen shot 2016-10-18 at 11 33 02 am" src="https://cloud.githubusercontent.com/assets/579/19491139/b2e3c122-9526-11e6-8e0f-41dbcb6a67d4.png">

**Comment by MylesBorins** [comment]
there is no current release at the moment. once v7 is promoted it will fall
back to a single Lts and current

there is another issue open to discuss what the site should look like

**Comment by mikeal** [comment]
Cool, thanks.
