### ISSUE TITLE
Plans for frontpage related to 2 x LTS releases + current

### ISSUE THREAD

**Issue by phillipj** [nodejs/nodejs.org#982]
Any thoughts on how we could improve the current UX related to displaying 2 x LTS releases, plus the current release (v7) coming soon?

Tonight v6.9.0 transitioned into LTS 🎉 That means we currently have two LTS releases, and no current. With https://github.com/nodejs/nodejs.org/pull/973 merged we now display these two releases side by side, which I assume is quite confusing and not ideal in the long run.

<img width="580" alt="screen shot 2016-10-18 at 21 11 31" src="https://cloud.githubusercontent.com/assets/1231635/19492571/78d0b89a-9577-11e6-8c91-49ecabd39d63.png">

And what should we promote when a new current release is cut? Only display v6 LTS + v7 current? v4 is still LTS thought, so it's probably still valuable for those who don't want to jump the v6 train just yet.

![s1](https://github.com/nodejs/LTS/raw/master/schedule.png)

**Comment by MylesBorins** [comment]
the simplest way to move forward is to revert the change I landed when 7
drops and simply have a single Lts v6 and current v7

I've thought about this quite a bit and think it is the right move. people
who want v4 will know how to find it. we can bring the "all versions " link
further up the page and make it more noticeable

**Comment by phillipj** [comment]
Going back to promoting two releases in total would at least avoid "which LTS should I choose" questions which I see as the biggest confusion.

> people who want v4 will know how to find it

Sure enough, if not, we'll probably hear from the users struggling.

**Comment by mairead** [comment]
I submitted a layout for a tabbed version in the previous issue #953, which Axel had originally suggested but I'm actually thinking if you want something scalable (so 1, or any future number of releases) and something mobile friendly you'd be much better putting it all in an accordion and having the preferred version expanded on page load. Horizontal layouts like tabs are lousy on mobile especially if the number of useful releases to promote is something which changes frequently. I am struggling to follow all the conversation here though. Is there actually a consensus on this yet?

**Comment by gibfahn** [comment]
@mairead I think all the opinions on here so far are against adding more than 2 releases, so I think the current website version (one LTS, one Current) should be fine.

**Comment by mhdawson** [comment]
I've also commented that I think the one LTS and one Current is fine.  Next time we switch over I'd recommend that during the transition we should show the same release as LTS and as Current  until the new current is available.  In that way we'll be always be consistent with one LTS and one Current version being promoted.  I agree may look a little odd during that week, but I think less odd than switching to 2 LTS releases for one week.

**Comment by MylesBorins** [comment]
what was particularly confusing was that current was an 6.8.1 while Lts was
6.90

**Comment by gibfahn** [comment]
I guess we do need to have Current and LTS at least matching (e.g. at 6.9.0) in the interim period.

**Comment by MylesBorins** [comment]
we could also have a greyed out current that days coming soon

**Comment by mhdawson** [comment]
I like the idea of greying out with the coming soon.

**Comment by phillipj** [comment]
@TheAlphaNerd something like this?

<img width="561" alt="screen shot 2016-10-19 at 20 59 03" src="https://cloud.githubusercontent.com/assets/1231635/19533153/eba02a5a-963e-11e6-9289-9c4d61578fbd.png">

**Comment by MylesBorins** [comment]
that looks great to me!

it doesn't cover the download page though

**Comment by ronkorving** [comment]
Please also mark v6 as LTS on https://nodejs.org/en/docs/

**Comment by mhdawson** [comment]
looks good to me as well, provide of course we do it everywhere the 2 are shown.

**Comment by MylesBorins** [comment]
We decided to stick to a single lts. Closing but feel free to reopen or make a new issue
