### ISSUE TITLE
Use one stylesheet for all locales

### ISSUE THREAD

**Issue by zlatanvasovic** [nodejs/nodejs.org#985]
Basically, there are no changes in the `styles.styl` files of all locales. I am wondering why do we still have them.

In case we really need to add language-specific styles, there is [:lang pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:lang) in CSS.

**Comment by phillipj** [comment]
I'm all for removing complexity 👍

@fhemberger @mikeal maybe you remember what the actual need behind locale `.styl`s were back in the day?

**Comment by mikeal** [comment]
I think we were worried that someone _might_ need to adjust something in a locale specific way so we wanted the option, but they should fall back to the english one when unused.

Being that nobody has actually used them it's probably best to get rid of them.

**Comment by fhemberger** [comment]
+1 for removing them.

There should be no need for language specific styling. RTL languages for example could be handled in the global styles as well.

**Comment by zlatanvasovic** [comment]
@nodejs/documentation Any other opinions? Let's decide on this to make the process of translating even easier.

**Comment by Fishrock123** [comment]
I think we should use a single stylesheet if possible.

**Comment by diagramatics** [comment]
I've created a preliminary PR #1085 if this is going to be the decision.
